(define (two-sum nums target)
  (define indices (hash))
  (for* ((i (in-range (length nums)))
         (num nums))
    (hash-set! indices num i))
  (for* ((i (in-range (length nums)))
         (num nums))
    (let ((complement (- target num)))
      (when (hash-has? indices complement)
        (let ((j (hash-ref indices complement)))
          (when (not (= i j))
            (return (list i j))))))))