(define (common-characters strs)
  (let loop ((char-count (make-vector 26 0))
             (strs strs))
    (if (null? strs)
        (let ((result '()))
          (for ((i (in-range 26)))
            (when (= (vector-ref char-count i) (length (list->vector strs)))
              (set! result (cons (string (integer->char (+ i 97))) result))))
          (reverse result))
        (let* ((current (car strs))
               (current-count (make-vector 26 0)))
          (for ((c (in-string current)))
            (vector-set! current-count (- (char->integer c) 97) (+ 1 (vector-ref current-count (- (char->integer c) 97)))))
          (for ((i (in-range 26)))
            (set! (vector-ref char-count i) (min (vector-ref char-count i) (vector-ref current-count i))))
          (loop char-count (cdr strs))))))

(define (find-common-characters strs)
  (common-characters strs))