(define (num-pairs-divisible-by-60 time)
  (define counts (make-vector 60 0))
  (define result 0)
  (for-each (lambda (t)
              (let ((mod (modulo t 60)))
                (set! result (+ result (vector-ref counts (modulo (- 60 mod) 60))))
                (vector-set! counts mod (+ 1 (vector-ref counts mod)))))
            time)
  result)