(define (can-ship packages capacity days)
  (define (days-required capacity)
    (define total 0)
    (define days 1)
    (for-each (lambda (weight)
                (when (> (+ total weight) capacity)
                  (set! total weight)
                  (set! days (+ days 1))))
              packages)
    days)
  (<= (days-required capacity) days))

(define (ship-within-days packages days)
  (define low (apply max packages))
  (define high (apply + packages))
  (define (binary-search low high)
    (if (= low high)
        low
        (define mid (quotient (+ low high) 2))
        (if (can-ship packages mid days)
            (binary-search low mid)
            (binary-search (+ mid 1) high))))
  (binary-search low high))

(define (ship-packages-within-d-days packages days)
  (ship-within-days packages days))