(define (next-greater-nodes head)
  (define lst '())
  (define (collect-nodes node)
    (when node
      (set! lst (cons (node-value node) lst))
      (collect-nodes (node-next node))))
  (collect-nodes head)
  (set! lst (reverse lst))
  (define n (length lst))
  (define result (make-vector n 0))
  (define stack '())
  (for ([i (in-range n)])
    (while (and (not (null? stack))
                (> (list-ref lst i) (list-ref lst (car stack)))))
      (vector-set! result (car stack) (list-ref lst i))
      (set! stack (cdr stack)))
    (set! stack (cons i stack)))
  (vector->list result))