(define (isBoomerang points)
  (let ((p1 (car points))
        (p2 (cadr points))
        (p3 (caddr points)))
    (and (not (= (car p1) (car p2)))
         (not (= (car p2) (car p3)))
         (not (= (cadr p1) (cadr p2)))
         (not (= (cadr p2) (cadr p3)))
         (not (= (car p1) (car p3)))
         (not (= (cadr p1) (cadr p3)))
         (not (= (car p1) (car p2)))
         (not (= (cadr p1) (cadr p2)))
         (not (= (car p2) (car p3)))
         (not (= (cadr p2) (cadr p3)))
         (not (= (car p1) (car p3)))
         (not (= (cadr p1) (cadr p3)))
         (not (= (car p1) (car p2)))
         (not (= (cadr p1) (cadr p2)))
         (not (= (car p2) (car p3)))
         (not (= (cadr p2) (cadr p3)))
         (not (= (car p1) (car p3)))
         (not (= (cadr p1) (cadr p3)))))))

(isBoomerang '((1 1) (2 3) (3 2)))