(define (gardenNoAdj n paths)
  (define graph (make-vector (+ n 1) '()))
  (for-each (lambda (edge)
              (let ((u (car edge))
                    (v (cadr edge)))
                (vector-set! graph u (cons v (vector-ref graph u)))
                (vector-set! graph v (cons u (vector-ref graph v)))))
            paths)
  (define colors (make-vector (+ n 1) 0))
  (define (dfs node)
    (let ((used-colors (make-set)))
      (for-each (lambda (neighbor)
                  (when (> (vector-ref colors neighbor) 0)
                    (set-add! used-colors (vector-ref colors neighbor))))
                (vector-ref graph node))
      (for ((color (in-range 1 5)))
        (unless (set-member? used-colors color)
          (vector-set! colors node color)
          (return)))
      (for-each (lambda (neighbor)
                  (unless (> (vector-ref colors neighbor) 0)
                    (dfs neighbor)))
                (vector-ref graph node))))
  (for ((i (in-range 1 (+ n 1))))
    (unless (> (vector-ref colors i) 0)
      (dfs i)))
  (vector->list (vector-slice colors 1 (+ n 1))))