(define (largestValuesFromLabels values labels numWanted useLimit)
  (define label-count (make-hash))
  (for ([i (in-range (length labels))])
    (define label (vector-ref labels i))
    (hash-set! label-count label 0))
  (define value-label-pairs (map list values labels))
  (define sorted-pairs (sort value-label-pairs (lambda (a b) (> (car a) (car b)))))
  (define total-sum 0)
  (define total-count 0)

  (for ([pair sorted-pairs])
    (define value (car pair))
    (define label (cadr pair))
    (define current-count (hash-ref label-count label 0))
    (when (and (< total-count numWanted) (< current-count useLimit))
      (set! total-sum (+ total-sum value))
      (hash-set! label-count label (+ current-count 1))
      (set! total-count (+ total-count 1))))

  total-sum)