(define (printFooBar n)
  (define (foo)
    (for ([i (in-range n)])
      (display "Foo")
      (flush-output)))
  (define (bar)
    (for ([i (in-range n)])
      (display "Bar")
      (flush-output)))
  (define (worker)
    (let ([foo-thread (thread foo)]
          [bar-thread (thread bar)])
      (thread-wait foo-thread)
      (thread-wait bar-thread)))
  (worker))