(define (smallestSufficientTeam reqSkills people)
  (define (helper skills team)
    (if (null? skills)
        (list team)
        (let* ((skill (car skills))
               (remaining-skills (cdr skills))
               (options (filter (lambda (x) (member skill (cdr x))) people)))
          (apply append (map (lambda (x) (helper remaining-skills (cons (car x) team))) options)))))

  (define skills (map car reqSkills))
  (define teams (helper skills '()))
  (define min-team (apply min (map length teams)))
  (define result (filter (lambda (x) (= (length x) min-team)) teams))
  (if (null? result)
      '()
      (map car result)))

(define reqSkills (list (list "java" 0) (list "nodejs" 0) (list "reactjs" 0)))
(define people (list (list "james" (list "java")) (list "Emily" (list "bjs" "nodejs")) (list "simon" (list "java" "nodejs" "reactjs"))))
(smallestSufficientTeam reqSkills people)