(define (alphabet-board-path target)
  (define board '("abcde" "fghij" "klmno" "pqrst" "uvwxy" "z"))
  (define (find-position char)
    (for/fold ([pos '()]) ([row (in-range 6)] [col (in-range (string-length (list-ref board row)))])
      (if (char=? char (string-ref (list-ref board row) col))
          (cons (list row col) pos)
          pos)))
  (define (move-from-to from to)
    (define row-delta (- (car to) (car from)))
    (define col-delta (- (cadr to) (cadr from)))
    (define moves "")
    (set! moves (string-append moves (make-string (max 0 row-delta) #\D)))
    (set! moves (string-append moves (make-string (max 0 (- col-delta)) #\R)))
    (set! moves (string-append moves (make-string (max 0 (- row-delta)) #\U)))
    (set! moves (string-append moves (make-string (max 0 (- col-delta)) #\L)))
    moves)
  (define start '(0 0))
  (define result "")
  (for-each (lambda (char)
              (define target-pos (find-position char))
              (set! result (string-append result (move-from-to start target-pos)))
              (set! result (string-append result (string char)))
              (set! start target-pos))
            (string->list target))
  result)