(define (min-moves-to-zigzag nums)
  (define (zigzag-cost nums)
    (define n (length nums))
    (define total-cost 0)
    (for ([i (in-range n)])
      (when (and (> i 0) (> (vector-ref nums i) (vector-ref nums (- i 1))))
        (set! total-cost (+ total-cost (- (vector-ref nums i) (vector-ref nums (- i 1)) 1)))))
    total-cost)
  (min (zigzag-cost nums) (zigzag-cost (vector->list (vector-map (lambda (x) x) nums)))))