(define (numDistinct s t)
  (define n (string-length s))
  (define m (string-length t))
  (define dp (make-vector (+ 1 n) 0))
  (vector-set! dp 0 1)

  (for ([j (in-range 1 (+ 1 n))])
    (vector-set! dp j 0))

  (for ([i (in-range 1 (+ 1 m))])
    (define prev (vector-ref dp 0))
    (vector-set! dp 0 0)
    (for ([j (in-range 1 (+ 1 n))])
      (define temp (vector-ref dp j))
      (if (char=? (string-ref t (- i 1)) (string-ref s (- j 1)))
          (vector-set! dp j (+ prev (vector-ref dp (- j 1))))
          (vector-set! dp j (vector-ref dp (- j 1)))
        )
      (set! prev temp)
    )
  )
  (vector-ref dp n))