(define (countVowelPermutation n)
  (define mod (expt 10 9))
  (define dp (make-vector 5 (make-vector n 0)))
  (for ([i 0 5])
    (vector-set! (vector-ref dp i) 0 1))
  (for ([i 1 n])
    (vector-set! (vector-ref dp 0) i (modulo (+ (vector-ref (vector-ref dp 1) (- i 1))
                                                  (vector-ref (vector-ref dp 2) (- i 1))
                                                  (vector-ref (vector-ref dp 4) (- i 1))) mod))
    (vector-set! (vector-ref dp 1) i (modulo (+ (vector-ref (vector-ref dp 0) (- i 1))
                                                  (vector-ref (vector-ref dp 2) (- i 1))) mod))
    (vector-set! (vector-ref dp 2) i (modulo (+ (vector-ref (vector-ref dp 1) (- i 1))
                                                  (vector-ref (vector-ref dp 3) (- i 1))) mod))
    (vector-set! (vector-ref dp 3) i (modulo (vector-ref (vector-ref dp 2) (- i 1)) mod))
    (vector-set! (vector-ref dp 4) i (modulo (+ (vector-ref (vector-ref dp 2) (- i 1))
                                                  (vector-ref (vector-ref dp 3) (- i 1))) mod)))
  (apply + (map (lambda (x) (vector-ref (vector-ref dp x) (- n 1))) (list 0 1 2 3 4)) mod))