(define (maxEqualFreq nums)
  (define (helper freq-count)
    (define freq-set (map car freq-count))
    (define freq-map (make-hash))
    (for-each (lambda (f) (hash-set! freq-map f (+ (hash-ref freq-map f 0) 1))) freq-set)
    (define freqs (hash->list freq-map))
    (if (or (= (length freqs) 1)
            (and (= (length freqs) 2)
                 (or (and (= (car freqs) 1) (= (cdr freqs) 1))
                     (or (= (car freqs) (+ (cdr freqs) 1))
                         (= (cdr freqs) (+ (car freqs) 1))))))
            (and (= (length freqs) 3)
                 (or (and (= (car freqs) 1) (= (cadr freqs) (caddr freqs)))
                     (and (= (cadr freqs) 1) (= (car freqs) (caddr freqs)))
                     (and (= (car freqs) (+ (cadr freqs) 1)) (= (caddr freqs) (cadr freqs)))
                     (and (= (caddr freqs) (+ (car freqs) 1)) (= (cadr freqs) (car freqs)))))))
      (length nums)
      (apply max (map (lambda (f) (- (length nums) (hash-ref freq-map f))) freqs))))

  (define freq-count (make-hash))
  (for-each (lambda (num) (hash-set! freq-count num (+ (hash-ref freq-count num 0) 1))) nums)
  (define freq-list (hash->list freq-count))
  (helper freq-list))

(maxEqualFreq '(1 2 3 4 5)) ; Example usage