(define (find-solutions a b)
  (define (helper x)
    (if (and (> x 0) (= (+ a x (* b x)) 0))
        (list x)
        '()))
  (define results '())
  (for ((x (in-range 1 (+ a b))))
    (set! results (append results (helper x))))
  results)