(define (oddCells n m indices)
  (define matrix (make-vector n (make-vector m 0)))
  (for-each (lambda (index)
              (define r (vector-ref index 0))
              (define c (vector-ref index 1))
              (for ([i (in-range m)])
                (vector-set! (vector-ref matrix r) i (+ (vector-ref (vector-ref matrix r) i) 1)))
              (for ([j (in-range n)])
                (vector-set! (vector-ref matrix j) c (+ (vector-ref (vector-ref matrix j) c) 1))))
              )
            indices)
  (define count 0)
  (for ([i (in-range n)] [j (in-range m)])
    (when (odd? (vector-ref (vector-ref matrix i) j))
      (set! count (+ count 1))))
  count)