(define (find-ladders begin-word end-word word-list)
  (define (construct-paths paths dict)
    (if (null? paths)
        '()
        (let loop ((current (car paths)) (rest (cdr paths)) (results '()))
          (if (null? current)
              (append results (loop rest dict))
              (let* ((last (car current))
                     (next-words (filter (lambda (word) (and (not (member word current))
                                                             (one-char-diff? last word)))
                                         dict)))
                (for-each (lambda (word)
                            (let ((new-path (cons word current)))
                              (set! results (cons (reverse new-path) results))))
                          next-words)
                (loop (cdr current) rest results))))))

  (define (one-char-diff? s1 s2)
    (let loop ((s1 s1) (s2 s2) (diffs 0))
      (cond
        ((or (null? s1) (null? s2)) (= diffs 1))
        ((char=? (car s1) (car s2)) (loop (cdr s1) (cdr s2) diffs))
        (else (loop (cdr s1) (cdr s2) (+ diffs 1))))))

  (define (bfs begin-word end-word dict)
    (define visited (make-hash))
    (define queue (list (list begin-word)))
    (define found false)
    (define paths '())

    (let loop ()
      (if (or (null? queue) found)
          paths
          (let* ((current (car queue))
                 (last-word (car current)))
            (set! queue (cdr queue))
            (if (equal? last-word end-word)
                (begin
                  (set! found true)
                  (set! paths (cons current paths)))
                (for-each (lambda (word)
                            (when (and (not (hash-ref visited word #f))
                                       (one-char-diff? last-word word))
                              (hash-set! visited word #t)
                              (set! queue (cons (cons word current) queue))))
                          dict))
            (loop)))))

  (define dict (set word-list))
  (define paths (bfs begin-word end-word dict))
  (map reverse (construct-paths paths dict)))