(define (shift-grid grid k)
  (define rows (length grid))
  (define cols (length (car grid)))
  (define total ( * rows cols))
  (define k (modulo k total))
  (define flat-grid (apply append grid))
  (define shifted-grid (append (drop flat-grid (- total k)) (take flat-grid (- total k))))
  (define (build-grid lst)
    (if (null? lst) '()
        (cons (take lst cols) (build-grid (drop lst cols)))))
  (build-grid shifted-grid))