(define (suggested-products products searchWord)
  (define sorted-products (sort products string<?))
  (define (get-suggestions prefix)
    (filter (lambda (product) (string-prefix? prefix product)) sorted-products))
  (define (build-suggestions word)
    (let loop ((i 1) (results '()))
      (if (> i (string-length word))
          (reverse results)
          (let ((prefix (substring word 0 i)))
            (let ((suggestions (get-suggestions prefix)))
              (loop (+ i 1) (cons (take suggestions 3) results)))))))
  (build-suggestions searchWord))

(define (solution products searchWord)
  (suggested-products products searchWord))