(define (subtractProductAndSum n)
  (define (digits n)
    (if (zero? n)
        '()
        (cons (modulo n 10) (digits (quotient n 10)))))
  (define ds (digits n))
  (define product (apply * ds))
  (define sum (apply + ds))
  (- product sum))