(define (solve board)
  (define (dfs x y)
    (if (or (< x 0) (>= x (length board)) 
            (< y 0) (>= (length (vector-ref board x)) (length (vector-ref board 0)))
            (not (= (vector-ref (vector-ref board x) y) #\O)))
        #f
        (begin
          (vector-set! (vector-ref board x) y #\T)
          (for-each (lambda (d)
                      (dfs (+ x (car d)) (+ y (cadr d))))
                    '((-1 0) (1 0) (0 -1) (0 1)))))
  (for-each (lambda (i)
              (if (or (= i 0) (= i (- (length board) 1)))
                  (for-each (lambda (j) (dfs i j))
                            (range (length (vector-ref board 0))))
                  (begin
                    (dfs i 0)
                    (dfs i (- (length (vector-ref board 0) 1)))))
              )
            (range (length board)))
  (for-each (lambda (j)
              (if (or (= j 0) (= j (- (length (vector-ref board 0) 1)))
                      (= j 0))
                  (begin
                    (dfs 0 j)
                    (dfs (- (length board) 1) j))))
            (range (length (vector-ref board 0))))
  (for-each (lambda (i)
              (for-each (lambda (j)
                          (if (= (vector-ref (vector-ref board i) j) #\T)
                              (vector-set! (vector-ref board i) j #\O)
                              (vector-set! (vector-ref board i) j #\X)))
                        (range (length (vector-ref board 0)))))
            (range (length board)))
  board)