(define (watchedVideosByFriends watchedVideos friends friendID)
  (define (count-videos videos)
    (foldl (lambda (video acc)
             (hash-update acc video (lambda (x) (+ x 1)) 1))
           (make-hash)
           videos))
  (define friend-videos (list-ref watchedVideos friendID))
  (define friend-friends (list-ref friends friendID))
  (define video-count (count-videos (apply append (map (lambda (fid) (list-ref watchedVideos fid)) friend-friends))))
  (define sorted-videos (sort (hash->list video-count) (lambda (a b) (or (< (second a) (second b)) (and (= (second a) (second b)) (< (first a) (first b))))))
  (map first sorted-videos))