(define (min-insertion-steps s)
  (define n (string-length s))
  (define dp (make-vector n (make-vector n 0)))
  (for ([i (in-range n)])
    (vector-set! dp i i 0))
  (for ([len (in-range 2 n+1)])
    (for ([i (in-range (- n len +1))])
      (define j (+ i len -1))
      (if (char=? (string-ref s i) (string-ref s j))
          (vector-set! dp i j (vector-ref dp (+ i 1) (- j 1)))
          (vector-set! dp i j (+ 1 (min (vector-ref dp (+ i 1) j) (vector-ref dp i (- j 1))))))))
  (vector-ref dp 0 (- n 1)))

(min-insertion-steps "your_input_string_here")