(define (max-value-after-reversing arr)
  (define (max-pair-sum arr)
    (define n (length arr))
    (define max-sum 0)
    (for ([i (in-range (- n 1))])
      (set! max-sum (max max-sum (+ (list-ref arr i) (list-ref arr (+ i 1))))))
    max-sum)

  (define original-sum (max-pair-sum arr))
  (define n (length arr))
  (define max-sum original-sum)

  (for ([i (in-range n)])
    (for ([j (in-range (+ i 1) n)])
      (define reversed-sum (+ (list-ref arr i) (list-ref arr j)))
      (define new-sum (max 
                        (max-pair-sum (append (sublist arr 0 i)
                                               (list (list-ref arr j))
                                               (sublist arr (+ i 1) j)
                                               (list (list-ref arr i))
                                               (sublist arr (+ j 1) n)))
                        (max-pair-sum (append (sublist arr 0 j)
                                               (list (list-ref arr i))
                                               (sublist arr (+ j 1) i)
                                               (list (list-ref arr j))
                                               (sublist arr (+ i 1) n)))))
      (set! max-sum (max max-sum new-sum))))

  max-sum)