(define (minSetSize arr)
  (define counts (make-hash))
  (for-each (lambda (x)
              (hash-set! counts x (+ (hash-ref counts x 0) 1)))
            arr)
  (define sorted-counts (sort (hash->list counts) (lambda (a b) (> (cdr a) (cdr b)))))
  (define total (length arr))
  (define half (/ total 2))
  (define count 0)
  (define size 0)
  (for-each (lambda (pair)
              (set! count (+ count (cdr pair)))
              (set! size (+ size 1))
              (when (>= count half) (set! count #f)))
            sorted-counts)
  size)