(define (numOfSubarrays arr k threshold)
  (define target (/ (* k threshold) k))
  (define (count-subarrays arr k target)
    (define n (length arr))
    (define count 0)
    (define sum (apply + (take arr k)))
    (when (>= sum target)
      (set! count (+ count 1)))
    (for ([i (in-range k n)])
      (set! sum (+ sum (list-ref arr i)))
      (when (>= sum target)
        (set! count (+ count 1)))
      (set! sum (- sum (list-ref arr (- i k)))))
    count)
  (count-subarrays arr k (* threshold k)))