(define (frogPosition n edges t, target)
  (define (dfs current time probability)
    (if (= time 0)
        (if (= current target) probability 0)
        (let ((total-ways (length (filter (lambda (x) (not (equal? x current))) edges))))
          (if (= total-ways 0)
              (if (= current target) probability 0)
              (let ((new-prob (/ probability total-ways)))
                (apply + (map (lambda (next)
                                (dfs next (- time 1) new-prob))
                              (filter (lambda (x) (not (equal? x current))) edges))))))))
  (dfs 1 t 1.0))