(define (luckyNumbers matrix)
  (define min-rows (map (lambda (row) (apply min row)) matrix))
  (define max-cols (map (lambda (col) (apply max col)) (apply map list matrix)))
  (define (is-lucky num row col)
    (and (= num (list-ref (list-ref matrix row) col))
         (= num (list-ref min-rows row))
         (= num (list-ref max-cols col))))
  (define lucky-numbers '())
  (for ([i (in-range (length matrix))])
    (for ([j (in-range (length (list-ref matrix i)))])
      (when (is-lucky (list-ref (list-ref matrix i) j) i j)
        (set! lucky-numbers (cons (list-ref (list-ref matrix i) j) lucky-numbers)))))
  lucky-numbers)