(define (entityParser text)
  (define entities (hash '("&quot;" . "\"")
                          '("&apos;" . "'")
                          '("&amp;" . "&")
                          '("&gt;" . ">")
                          '("&lt;" . "<")
                          '("&frasl;" . "/")))
  (define (replace-entities str)
    (for/fold ([result ""]) ([i (in-string str)])
      (if (char=? i #\&)
          (let loop ([j (add1 (string-index str i))])
            (if (or (>= j (string-length str)) (char=? (string-ref str j) #\;))
                (string-append result (substring str i j))
                (let ([entity (substring str i (add1 j))])
                  (if (hash-has-key? entities entity)
                      (string-append result (hash-ref entities entity))
                      (loop (add1 j))))))
          (string-append result (string i)))))
  (replace-entities text))