(define (findDiagonalOrder nums)
  (define (add-diagonal-diagonals lst)
    (for ([i (in-range (length lst))])
      (for ([j (in-range (length (list-ref lst i)))])
        (define diagonal (+ i j))
        (set! result (if (>= (length result) diagonal)
                         (vector-set! (vector-ref result diagonal) (vector-ref (list-ref lst i) j) (list-ref lst i j))
                         (begin (set! result (vector-append result (vector (make-vector (+ 1 diagonal) '()))))
                                (vector-set! (vector-ref result diagonal) (vector-ref (list-ref lst i) j) (list-ref lst i j)))))))
    result)

  (define result (make-vector 0))
  (add-diagonal-diagonals nums)
  (define res '())
  (for ([i (in-range (vector-length result))])
    (for ([j (in-range (vector-length (vector-ref result i)))])
      (set! res (cons (vector-ref (vector-ref result i) j) res))))
  (reverse res))

(define (findDiagonalOrder nums)
  (let ([result '()])
    (define (add-diagonal lst)
      (for ([i (in-range (length lst))])
        (for ([j (in-range (length (list-ref lst i)))])
          (define diagonal (+ i j))
          (if (>= (length result) diagonal)
              (vector-set! (vector-ref result diagonal) (vector-ref (list-ref lst i) j) (list-ref lst i j))
              (begin (set! result (vector-append result (vector (make-vector (+ 1 diagonal) '()))))
                     (vector-set! (vector-ref result diagonal) (vector-ref (list-ref lst i) j) (list-ref lst i j)))))))
    (add-diagonal nums)
    (define res '())
    (for ([i (in-range (vector-length result))])
      (for ([j (in-range (vector-length (vector-ref result i)))])
        (set! res (cons (vector-ref (vector-ref result i) j) res))))
    (reverse res)))