(define (minTimeToCollectAllApples edges hasApple)
  (define (dfs node parent)
    (define total-time 0)
    (for-each (lambda (child)
                (unless (= child parent)
                  (let ((time (dfs child node)))
                    (set! total-time (+ total-time time))
                    (when (> time 0)
                      (set! total-time (+ total-time 2))))))
              (vector-ref edges node))
    (if (and (= total-time 0) (not (vector-ref hasApple node)))
        0
        total-time))
  (dfs 0 -1))

(define (minTimeToCollectAllApples edges hasApple)
  (let ((n (vector-length hasApple)))
    (define tree (make-vector n '()))
    (for-each (lambda (edge)
                (let ((u (vector-ref edge 0))
                      (v (vector-ref edge 1)))
                  (vector-set! tree u (cons v (vector-ref tree u)))
                  (vector-set! tree v (cons u (vector-ref tree v)))))
              edges)
    (define (dfs node parent)
      (define total-time 0)
      (for-each (lambda (child)
                  (unless (= child parent)
                    (let ((time (dfs child node)))
                      (set! total-time (+ total-time time))
                      (when (> time 0)
                        (set! total-time (+ total-time 2))))))
                (vector-ref tree node))
      (if (and (= total-time 0) (not (vector-ref hasApple node)))
          0
          total-time))
    (dfs 0 -1)))