(define (cherryPickup II grid)
  (define n (length grid))
  (define m (length (car grid)))
  (define dp (make-vector n (make-vector m 0)))

  (define (max-cherries r1 c1 r2 c2)
    (if (or (< r1 0) (>= r1 n) (< c1 0) (>= c1 m) 
            (< r2 0) (>= r2 n) (< c2 0) (>= c2 m))
        -1
        (+ (if (= r1 r2 c1 c2) (vector-ref grid r1 c1) 
               (+ (vector-ref grid r1 c1) (vector-ref grid r2 c2))
           )
           (if (and (not (= r1 r2)) (not (= c1 c2)))
               (max (max-cherries (+ r1 1) c1 (+ r2 1) c2)
                    (max-cherries (+ r1 1) c1 (+ r2 1) (+ c2 1))
                    (max-cherries r1 c1 (+ r2 1) c2)
                    (max-cherries r1 c1 (+ r2 1) (+ c2 1))
                    (max-cherries (+ r1 1) (+ c1 1) (+ r2 1) c2)
                    (max-cherries (+ r1 1) (+ c1 1) (+ r2 1) (+ c2 1))
                    (max-cherries r1 (+ c1 1) (+ r2 1) c2)
                    (max-cherries r1 (+ c1 1) (+ r2 1) (+ c2 1)))
               (max (max-cherries (+ r1 1) c1 (+ r2 1) c2)
                    (max-cherries r1 c1 (+ r2 1) c2))))))

  (define (dp-cherry r1 c1 r2 c2)
    (if (vector-ref dp r1 c1 r2 c2)
        (vector-ref dp r1 c1 r2 c2)
        (let* ([result (max-cherries r1 c1 r2 c2)])
          (vector-set! dp r1 c1 r2 c2 result)
          result)))

  (dp-cherry 0 0 0 (- m 1)))