(define (canArrange arr k)
  (define counts (make-vector k 0))
  (for-each (lambda (x)
              (vector-set! counts (modulo x k) (+ 1 (vector-ref counts (modulo x k)))))
            arr)
  (for ([i (in-range 1 (quotient k 2))])
    (if (not (= (vector-ref counts i) (vector-ref counts (- k i))))
        (return #f)))
  (if (zero? (vector-ref counts 0))
      (return #f))
  (return #t))

(define (solve arr k)
  (canArrange arr k))