(define (num-split s)
  (define freq (make-hash))
  (for-each (lambda (c) (hash-set! freq c (add1 (hash-ref freq c 0)))) (string->list s))
  (define left (make-hash))
  (define right freq)
  (define good-ways 0)
  (for ([i (in-range (sub1 (string-length s)))])
    (define c (string-ref s i))
    (hash-set! left c (add1 (hash-ref left c 0)))
    (hash-set! right c (sub1 (hash-ref right c)))
    (when (and (> (hash-count left) 0) (> (hash-count right) 0))
      (set! good-ways (add1 good-ways))))
  good-ways)