(define (find-min nums)
  (define (binary-search left right)
    (if (= left right)
        (vector-ref nums left)
        (let* ((mid (quotient (+ left right) 2))
               (mid-val (vector-ref nums mid))
               (left-val (vector-ref nums left))
               (right-val (vector-ref nums right)))
          (cond
            ((< mid-val right-val) (binary-search left mid))
            ((> mid-val left-val) (binary-search mid right))
            (else (binary-search left (+ mid -1))))))
    )
  (binary-search 0 (- (vector-length nums) 1)))