(define (findSmallestSetOfVertices n edges)
  (define indegree (make-vector n 0))
  (for-each (lambda (edge)
              (vector-set! indegree (second edge) (+ 1 (vector-ref indegree (second edge)))))
            edges)
  (define result '())
  (for ([i (in-range n)])
    (when (= (vector-ref indegree i) 0)
      (set! result (cons i result))))
  result)