(define (mostVisited n rounds)
  (define sectors (make-vector n 0))
  (for-each (lambda (round)
              (let* ((start (car round))
                     (end (cadr round)))
                (if (<= start end)
                    (for-each (lambda (i) (vector-set! sectors i (+ (vector-ref sectors i) 1)))
                              (range start (add1 end)))
                    (begin
                      (for-each (lambda (i) (vector-set! sectors i (+ (vector-ref sectors i) 1)))
                                (range start n))
                      (for-each (lambda (i) (vector-set! sectors i (+ (vector-ref sectors i) 1)))
                                (range 0 (add1 end))))))))
            rounds)
  (let* ((max-visited (apply max (vector->list sectors)))
         (result (for/list ((i (in-range n))
                             #:when (= (vector-ref sectors i) max-visited))
                        (+ i 1))))
    result))

(define (range start end)
  (if (>= start end)
      '()
      (cons start (range (add1 start) end))))