(define (min-cost colors neededTime)
  (define (helper idx total-cost max-time)
    (if (>= idx (length colors))
        total-cost
        (let* ((current-color (vector-ref colors idx))
               (current-time (vector-ref neededTime idx))
               (next-idx (if (< idx (sub1 (length colors)))
                             (if (equal? current-color (vector-ref colors (add1 idx)))
                                 (add1 idx)
                                 (add1 idx))
                             (add1 idx)))
               (next-color (if (< idx (sub1 (length colors))) (vector-ref colors next-idx) #f))
               (next-time (if (< idx (sub1 (length colors))) (vector-ref neededTime next-idx) 0)))
          (if (equal? current-color next-color)
              (helper next-idx (+ total-cost (min current-time max-time)) (max current-time max-time))
              (helper next-idx total-cost 0)))))
  (helper 0 0 0))

(define (minCost colors neededTime)
  (min-cost (vector->list colors) (vector->list neededTime)))