(define (min-subarray nums p)
  (define total (apply + nums))
  (define target (modulo total p))
  (if (= target 0) 0
      (define n (length nums))
      (define last (make-vector p -1))
      (define min-length (+ n 1))
      (vector-set! last 0 -1)
      (define curr-sum 0)
      (for ([i (in-range n)])
        (set! curr-sum (modulo (+ curr-sum (vector-ref nums i)) p))
        (define idx (vector-ref last curr-sum))
        (when (not (= idx -1))
          (set! min-length (min min-length (- i idx))))
        (vector-set! last curr-sum i))
      (if (= min-length (+ n 1)) -1 min-length)))