(define (alert-using-same-keycard keyName timeStamp)
  (define keycard-map (make-hash))
  (define alerts '())
  (for ((i (in-range (length keyName))))
    (let* ((name (list-ref keyName i))
           (time (list-ref timeStamp i))
           (time-list (hash-ref keycard-map name '())))
      (set! time-list (cons time time-list))
      (hash-set! keycard-map name (filter (lambda (t) (>= t (- time 60))) time-list))
      (when (>= (length (hash-ref keycard-map name)) 3)
        (set! alerts (cons name alerts)))))
  (remove-duplicates alerts))

(alert-using-same-keycard '("alice" "alice" "alice" "bob" "bob" "bob" "alice") '(1 2 3 4 5 6 7))