(define (maximal-network-rank n roads)
  (define adj (make-vector n 0))
  (for-each (lambda (road)
              (vector-set! adj (car road) (add1 (vector-ref adj (car road))))
              (vector-set! adj (cadr road) (add1 (vector-ref adj (cadr road)))))
            roads)
  (define (count-roads city)
    (vector-ref adj city))
  (define (connected? city1 city2)
    (or (member city2 (map cdr (filter (lambda (x) (= (car x) city1)) roads)))
        (member city1 (map cdr (filter (lambda (x) (= (car x) city2)) roads)))))
  (define max-rank 0)
  (for ([i (in-range n)])
    (for ([j (in-range n) :when (> j i)])
      (let ([rank (+ (count-roads i) (count-roads j))])
        (when (connected? i j)
          (set! rank (sub1 rank)))
        (set! max-rank (max max-rank rank)))))
  max-rank)