(define (bestCoordinate towers radius)
  (define (distance p1 p2)
    (sqrt (+ (expt (- (car p1) (car p2)) 2)
             (expt (- (cadr p1) (cadr p2)) 2))))

  (define (quality x y)
    (foldl (lambda (tower acc)
              (let* ((xi (car tower))
                     (yi (cadr tower))
                     (qi (caddr tower))
                     (d (distance (list x y) (list xi yi))))
                (if (<= d radius)
                    (+ acc (floor (/ qi (+ 1 d)))
                       )
                    acc)))
            0
            towers))

  (define best (list 0 0 0))
  (for ([x (in-range 51)])
    (for ([y (in-range 51)])
      (let ((q (quality x y)))
        (when (> q (caddr best))
          (set! best (list x y q))))))
  (list (car best) (cadr best)))