(define (slowest-key release-times keys-pressed)
  (let loop ((max-time -1)
             (result #\0)
             (i 0))
    (if (< i (length keys-pressed))
        (let* ((current-time (- (vector-ref release-times i) 
                                 (if (zero? i) 0 (vector-ref release-times (- i 1)))))
               (current-key (string-ref keys-pressed i)))
          (if (or (> current-time max-time)
                  (and (= current-time max-time) (> (char->integer current-key) (char->integer result))))
              (loop current-time current-key (+ i 1))
              (loop max-time result (+ i 1)))
        result)
      result)))

(define (slowest-key-solution release-times keys-pressed)
  (slowest-key release-times keys-pressed))