(define (matrixRankTransform matrix)
  (define (find-parent parent x)
    (if (not (= (vector-ref parent x) x))
        (find-parent parent (vector-ref parent x))
        x))

  (define (union parent rank x y)
    (let* ((rootX (find-parent parent x))
           (rootY (find-parent parent y)))
      (when (not (= rootX rootY))
        (if (> (vector-ref rank rootX) (vector-ref rank rootY))
            (vector-set! parent rootY rootX)
            (begin
              (vector-set! parent rootX rootY)
              (when (= (vector-ref rank rootX) (vector-ref rank rootY))
                (vector-set! rank rootY (+ (vector-ref rank rootY) 1))))))))

  (define (get-rank matrix)
    (let* ((rows (vector-length matrix))
           (cols (vector-length (vector-ref matrix 0)))
           (parent (make-vector (* rows cols) #f))
           (rank (make-vector (* rows cols) 0))
           (positions (for/list ((i (in-range rows))
                                 (j (in-range cols)))
                        (list (vector-ref (vector-ref matrix i) j) i j))))
      (vector-set! parent 0 0)
      (for-each (lambda (i) (vector-set! parent i i)) (in-range (* rows cols)))
      (for-each (lambda (p)
                   (let ((val (car p))
                         (x (cadr p))
                         (y (caddr p)))
                     (for-each (lambda (dx dy)
                                 (let ((nx (+ x dx))
                                       (ny (+ y dy)))
                                   (when (and (>= nx 0) (< nx rows) (>= ny 0) (< ny cols))
                                         (union parent rank (+ (* x cols) y) (+ (* nx cols) ny)))))
                               (list 0 1 -1)))))
                 (sort positions (lambda (a b) (< (car a) (car b)))))
      (let ((result (make-vector rows (make-vector cols 0))))
        (for-each (lambda (i)
                     (for-each (lambda (j)
                                  (let* ((idx (+ (* i cols) j))
                                         (root (find-parent parent idx)))
                                    (vector-set! (vector-ref result i) j (vector-ref rank root))))
                                (in-range cols)))
                   (in-range rows))
        result)))

  (get-rank matrix))