(define (minimumJumps forbidden a b x)
  (define forbidden-set (set forbidden))
  (define (bfs)
    (define queue (list (list 0 0)))
    (define visited (set 0))
    (define max-reach (+ (max x (if (> b 0) (* 2 (max x (+ b 1))) 0)) (car (last forbidden))))
    (define (valid? pos)
      (and (not (set-member? forbidden-set pos))
           (>= pos 0)
           (<= pos max-reach)))
    (define (loop)
      (if (null? queue)
          -1
          (define current (car queue))
          (define curr-pos (car current))
          (define jumps (cadr current))
          (define new-queue (cdr queue))
          (if (= curr-pos x)
              jumps
              (for-each (lambda (next-pos)
                          (when (valid? next-pos)
                            (set-add! visited next-pos)
                            (set-add! new-queue (list next-pos (+ jumps 1)))))
                        (list (+ curr-pos a) (- curr-pos b)))
              (loop new-queue))))
    (loop))
  (bfs))