(define (distribute-repeating-integers nums)
  (define (helper n count)
    (if (= count 0)
        '()
        (cons (if (null? n) 0 (car n))
              (helper (if (null? n) '() (cdr n)) (- count 1)))))
  (define total (apply + nums))
  (if (or (null? nums) (zero? total))
      '()
      (let ((k (length nums)))
        (let loop ((i 0) (result '()))
          (if (= i total)
              (reverse result)
              (loop (+ i 1) (append result (helper nums (min (length nums) (max 0 (floor (/ (- total i) (length nums))))))))))))))

(distribute-repeating-integers '(1 2 3 4))