(define (minOperations nums x)
  (define total (apply + nums))
  (define target (- total x))
  (define n (length nums))
  (define (max-length target)
    (define sum 0)
    (define left 0)
    (define max-len -1)
    (for ([right (in-range n)])
      (set! sum (+ sum (list-ref nums right)))
      (while (>= sum target)
        (set! sum (- sum (list-ref nums left)))
        (set! left (+ left 1)))
      (when (= sum target)
        (set! max-len (max max-len (- right left 1)))))
    max-len)
  (define result (max-length target))
  (if (= result -1) -1 (- n result)))