(define (mostCompetitive nums k)
  (define (helper nums k)
    (if (or (null? nums) (zero? k)) '() 
        (if (>= (length nums) k)
            (let loop ((i 0) (min-index 0) (result '()))
              (if (and (< min-index (length nums)) 
                       (< (length result) k))
                  (let* ((next-index (or (find-next nums min-index) (length nums)))
                         (min-value (if (= next-index (length nums)) 
                                        #f 
                                        (list-ref nums next-index)))
                         (new-result (if (and (not (null? result)) 
                                              (< (car result) min-value))
                                         (cons (car result) (loop (+ min-index 1) (+ min-index 1) (cdr result)))
                                         (if (null? result)
                                             (loop (+ min-index 1) (+ min-index 1) result)
                                             (loop (+ min-index 1) (+ min-index 1) (cons (list-ref nums min-index) result))))))
                  (if (= (length new-result) k)
                      (reverse new-result)
                      (loop (+ min-index 1) (+ min-index 1) new-result)))
                '()))))
  (helper nums k))

(define (find-next nums start)
  (define (loop i)
    (if (>= i (length nums)) #f
        (if (< (list-ref nums i) (list-ref nums start)) i
            (loop (+ i 1))
            (loop (+ i 1)))))
  (loop start))