(define (maxHeight cuboids)
  (define (sort-cuboids cuboids)
    (sort cuboids (lambda (a b) (and (> (vector-ref a 0) (vector-ref b 0))
                                   (> (vector-ref a 1) (vector-ref b 1))
                                   (> (vector-ref a 2) (vector-ref b 2)))))

  (define (dp heights)
    (define n (length heights))
    (define dp (make-vector n 0))
    (for ([i (in-range n)])
      (vector-set! dp i (vector-ref heights i)))
    (for ([i (in-range n)])
      (for ([j (in-range i)])
        (when (and (<= (vector-ref (vector-ref heights i) 0) (vector-ref (vector-ref heights j) 0))
                   (<= (vector-ref (vector-ref heights i) 1) (vector-ref (vector-ref heights j) 1)))
          (vector-set! dp i (max (vector-ref dp i) (+ (vector-ref dp j) (vector-ref (vector-ref heights i) 2))))))
    (apply max (vector->list dp)))

  (define sorted-cuboids (map (lambda (c) (vector (max (vector-ref c 0) (vector-ref c 1) (vector-ref c 2))
                                                  (min (vector-ref c 0) (vector-ref c 1))
                                                  (min (min (vector-ref c 0) (vector-ref c 1)) (vector-ref c 2))))
                              cuboids))
  (dp sorted-cuboids))

(maxHeight (list (vector 1 2 3) (vector 3 2 1) (vector 2 3 4)))