(define (average-waiting-time customers)
  (define (helper customers current-time total-waiting-time)
    (if (null? customers)
        (/ total-waiting-time (length customers))
        (let* ((arrival (car customers))
               (duration (cadr customers))
               (start-time (max current-time arrival))
               (waiting-time (+ (- start-time arrival) duration))
               (new-current-time (+ start-time duration)))
          (helper (cdr customers) new-current-time (+ total-waiting-time waiting-time)))))
  (helper customers 0 0))