(define (can-form-array arr pieces)
  (define (helper arr pieces)
    (for/fold ([i 0]) ([p pieces])
      (let ([len (length p)])
        (if (and (<= i (length arr)) 
                 (= (take arr len) p))
            (+ i len)
            (return #f)))))
  (helper arr pieces))

(define (main)
  (define arr (vector-ref (vector-ref inputs 0) 0))
  (define pieces (vector-ref (vector-ref inputs 1) 0))
  (can-form-array arr pieces))