(define (countPairs root distance)
  (define (dfs node)
    (if (null? node)
        '()
        (let* ((left (dfs (node-left node)))
               (right (dfs (node-right node)))
               (result (apply + (map (lambda (x) (count (lambda (y) (< y distance)) right)) left))))
               (new-depths (map (lambda (d) (+ d 1)) (append left right))))
          (cons result (filter (lambda (d) (< d distance)) new-depths)))))
  (define depths (dfs root))
  (apply + depths))