(define (min-side-jumps obstacles)
  (define n (length obstacles))
  (define dp (make-vector n (make-vector 4 1e9)))
  (vector-set! dp 0 1 0)
  (for ([i (in-range n)])
    (for ([j (in-range 1 4)])
      (when (not (= (vector-ref obstacles i) j))
        (set! (vector-ref (vector-ref dp i) j) (min (vector-ref (vector-ref dp i) j)
                                                      (if (> i 0) (vector-ref (vector-ref dp (- i 1)) j) 1e9)
                                                      (if (> j 1) (+ 1 (vector-ref (vector-ref dp i) (- j 1))) 1e9)
                                                      (if (< j 3) (+ 1 (vector-ref (vector-ref dp i) (+ j 1))) 1e9))))))
    (when (< i (- n 1))
      (for ([j (in-range 1 4)])
        (when (not (= (vector-ref obstacles (+ i 1)) j))
          (set! (vector-ref (vector-ref dp (+ i 1)) j) (min (vector-ref (vector-ref dp (+ i 1)) j)
                                                             (vector-ref (vector-ref dp i) j))))))
    (for ([j (in-range 1 4)])
      (when (not (= (vector-ref obstacles (+ i 1)) j))
        (set! (vector-ref (vector-ref dp (+ i 1)) j) (min (vector-ref (vector-ref dp (+ i 1)) j)
                                                            (if (> j 1) (+ 1 (vector-ref (vector-ref dp (+ i 1)) (- j 1))) 1e9)
                                                            (if (< j 3) (+ 1 (vector-ref (vector-ref dp (+ i 1)) (+ j 1))) 1e9)))))))
  (min (vector-ref (vector-ref dp (- n 1)) 2) (vector-ref (vector-ref dp (- n 1)) 3)))