(define (maximumElementAfterDecreasingAndRearranging arr)
  (define (helper lst)
    (sort lst <))
  (define sorted (helper arr))
  (define n (length sorted))
  (define (iter idx prev)
    (if (>= idx n)
        (car (last sorted))
        (let ((current (list-ref sorted idx)))
          (if (<= current (+ prev 1))
              (iter (+ idx 1) (+ prev 1))
              (iter (+ idx 1) prev)))))
  (iter 0 0))