(define (sumOfFlooredPairs nums)
  (define n (length nums))
  (define max-num (apply max nums))
  (define counts (make-vector (+ max-num 1) 0))
  (for ([num nums])
    (vector-set! counts num (+ (vector-ref counts num) 1)))
  (define result (make-vector (+ max-num 1) 0))
  (for ([i (range 1 (+ max-num 1))])
    (for ([j (range i (+ max-num 1) i)])
      (vector-set! result j (+ (vector-ref result j) (vector-ref counts i)))))
  (define total-sum (apply + (vector->list result)))
  total-sum)

(sumOfFlooredPairs '(2 5 9))