(define (min-swaps s)
  (define n (string-length s))
  (define count-0 (length (filter (lambda (c) (equal? c #\0)) (string->list s))))
  (define count-1 (length (filter (lambda (c) (equal? c #\1)) (string->list s))))
  (define swaps (if (even? n) (min count-0 count-1) (max count-0 count-1)))
  (define expected-0 (if (even? n) (quotient n 2) (quotient (+ n 1) 2)))
  (define expected-1 (if (even? n) (quotient n 2) (quotient (- n 1) 2)))
  (define actual-0 (if (even? n) count-0 (if (even? count-0) count-0 (add1 count-0))))
  (define actual-1 (if (even? n) count-1 (if (even? count-1) count-1 (add1 count-1))))
  (if (even? n)
      (if (and (= actual-0 expected-0) (= actual-1 expected-1))
          0
          (if (or (= actual-0 expected-0) (= actual-1 expected-1))
              (if (= actual-0 expected-0) 
                  (quotient (- actual-1 expected-1) 2) 
                  (quotient (- actual-0 expected-0) 2))
              (quotient (abs (- actual-0 expected-0)) 2)))
      (if (and (= actual-0 expected-0) (= actual-1 expected-1))
          0
          (if (or (= actual-0 expected-0) (= actual-1 expected-1))
              (if (= actual-0 expected-0) 
                  (quotient (- actual-1 expected-1) 2) 
                  (quotient (- actual-0 expected-0) 2))
              (quotient (abs (- actual-0 expected-0)) 2)))))