(define (find-pairs nums k)
  (define counts (make-hash))
  (for-each (lambda (n) (hash-set! counts n (+ (hash-ref counts n 0) 1))) nums)
  (define result 0)
  (for-each (lambda (n)
              (when (and (hash-contains? counts (+ n k))
                         (not (= k 0)))
                (set! result (+ result 1))))
            (hash-keys counts))
  (if (= k 0)
      (for-each (lambda (v) (when (>= v 2) (set! result (+ result (quotient v 2)))))
                (hash-values counts)))
  result)