(define (find-repeated-dna-sequences s)
  (define sequences (make-hash))
  (define result '())
  (define len (string-length s))
  (for ([i (in-range (- len 10))])
    (define sub (substring s i (+ i 10)))
    (if (hash-exists? sequences sub)
        (when (not (member sub result))
          (set! result (cons sub result)))
        (hash-set! sequences sub #t)))
  (reverse result))