(define (isCovered ranges left right)
  (define covered (make-vector (+ right 1) #f))
  (for-each (lambda (range)
              (let ((start (car range))
                    (end (cadr range)))
                (for ([i start (in-range (+ end 1))])
                  (vector-set! covered i #t))))
            ranges)
  (for ([i left (in-range (+ right 1))])
    (if (not (vector-ref covered i))
        (return #f)))
  #t)