(define (earliestAndLatest n firstPlayer secondPlayer)
  (define (dfs curr round)
    (if (or (= (length curr) 1) (= round n))
        (if (= (length curr) 1)
            (list (list (car curr) round))
            '())
        (let* ((next-round (if (even? (length curr)) 
                               (length curr) 
                               (add1 (length curr)))))
          (append 
           (dfs (filter (lambda (x) (not (= x (car curr)))) curr) 
                (add1 round))
           (dfs (filter (lambda (x) (not (= x (cadr curr)))) curr) 
                (add1 round))))))
  (define players (range 1 (add1 n)))
  (define matches (dfs players 1))
  (define earliest (car (filter (lambda (x) (and (= (car x) firstPlayer) 
                                                 (= (cadr x) secondPlayer))) 
                                 matches)))
  (define latest (car (reverse (filter (lambda (x) (and (= (car x) firstPlayer) 
                                                       (= (cadr x) secondPlayer))) 
                                       matches))))
  (list (cadr earliest) (cadr latest)))