(define (maxProductDifference nums)
  (define sorted (sort nums <))
  (define n (length nums))
  (- (* (list-ref sorted (- n 1)) (list-ref sorted (- n 2)))
     (* (list-ref sorted 0) (list-ref sorted 1))))