(define (areOccurrencesEqual s)
  (define freq (make-hash))
  (for-each (lambda (c)
              (hash-set! freq c (+ (hash-ref freq c 0) 1)))
            (string->list s))
  (define counts (hash->list freq))
  (define first-count (cdr (first counts)))
  (for/all ([count counts])
    (= (cdr count) first-count)))