(define (min-swaps s)
  (define count 0)
  (define imbalance 0)
  (for-each (lambda (ch)
              (if (equal? ch #\]) 
                  (begin (set! imbalance (- imbalance 1)) 
                         (when (< imbalance 0) 
                           (set! count (+ count 1)) 
                           (set! imbalance 0)))
                  (set! imbalance (+ imbalance 1))))
            (string->list s))
  count)

(min-swaps "]]][[[")