(define (num-islands grid)
  (define (dfs i j)
    (when (and (>= i 0) (< i (length grid))
               (>= j 0) (< j (length (vector-ref grid i)))
               (eq? (vector-ref (vector-ref grid i) j) #\1))
      (vector-set! (vector-ref grid i) j #\0)
      (for-each (lambda (d)
                  (dfs (+ i (car d)) (+ j (cadr d))))
                '((-1 0) (1 0) (0 -1) (0 1))))
  (define count 0)
  (for* ([i (in-range (length grid))]
         [j (in-range (length (vector-ref grid i)))])
    (when (eq? (vector-ref (vector-ref grid i) j) #\1)
      (dfs i j)
      (set! count (+ count 1))))
  count)

(define (num-islands-main grid)
  (num-islands (map (lambda (row) (vector (string->list row))) grid)))