(define (find-original-array changed)
  (define n (length changed))
  (if (odd? n) 
      '() 
      (begin
        (define counts (make-hash))
        (for-each (lambda (x) 
                    (hash-set! counts x (+ (hash-ref counts x 0) 1))) 
                  changed)
        (define sorted (sort changed <))
        (define result '())
        (for-each (lambda (x)
                    (when (and (not (zero? (hash-ref counts x 0))) 
                               (hash-ref counts (* 2 x) 0))
                      (set! result (cons x result))
                      (hash-set! counts x (- (hash-ref counts x 0) 1))
                      (hash-set! counts (* 2 x) (- (hash-ref counts (* 2 x) 0) 1))))
                  sorted)
        (if (= (length result) (/ n 2)) 
            (reverse result) 
            '())))))

(define (main)
  (display (find-original-array '(1 3 4 2 6 8))))
(main)