(define (sum-of-beauty nums)
  (define n (length nums))
  (if (< n 3) 0
      (define left-max (vector 0))
      (define right-min (vector 0))
      (for ([i (in-range n)])
        (vector-set! left-max i (if (= i 0) (vector-ref nums 0) (max (vector-ref left-max (- i 1)) (vector-ref nums i)))))
      (for ([i (in-range (- n 1) -1 -1)])
        (vector-set! right-min i (if (= i (- n 1)) (vector-ref nums (- n 1)) (min (vector-ref right-min (+ i 1)) (vector-ref nums i)))))
      (define beauty 0)
      (for ([i (in-range 1 (- n 1))])
        (when (and (> (vector-ref left-max (- i 1)) (vector-ref nums i))
                   (< (vector-ref nums i) (vector-ref right-min (+ i 1))))
          (set! beauty (+ beauty 2))
          (when (and (< (vector-ref left-max (- i 1)) (vector-ref nums i))
                     (> (vector-ref nums i) (vector-ref right-min (+ i 1))))
            (set! beauty (+ beauty 1))))
      beauty)))