(define (count-primes n)
  (define (sieve limit)
    (define is-prime (make-vector limit #t))
    (vector-set! is-prime 0 #f)
    (vector-set! is-prime 1 #f)
    (for ([i (in-range 2 (sqrt limit))])
      (when (vector-ref is-prime i)
        (for ([j (in-range (* i i) limit i)])
          (vector-set! is-prime j #f))))
    (for/sum ([i (in-range limit)] #:when (vector-ref is-prime i))
      1))
  (sieve n))