(define (secondMinimum n edges time change)
  (define graph (make-vector n '()))
  (for-each (λ (edge)
              (define u (car edge))
              (define v (cadr edge))
              (vector-set! graph (sub1 u) (cons v (vector-ref graph (sub1 u))))
              (vector-set! graph (sub1 v) (cons u (vector-ref graph (sub1 v)))))
            edges)

  (define (dijkstra)
    (define distances (make-vector n (make-vector 3 +inf.0)))
    (vector-set! distances 0 (vector 0 0))
    (define pq (make-priority-queue))
    (priority-queue-enqueue! pq (vector 0 0 0))

    (let loop ()
      (when (not (priority-queue-empty? pq))
        (define node (priority-queue-dequeue! pq))
        (define cur-time (vector-ref node 0))
        (define cur-node (vector-ref node 1))
        (define cur-ways (vector-ref distances cur-node))

        (if (and (= cur-node (sub1 n)) (> (vector-ref cur-ways 1) cur-time))
            (begin
              (vector-set! distances cur-node (vector cur-time (+ cur-time change)))
              (loop))
            (for-each (λ (neighbor)
                        (define new-time (+ cur-time time))
                        (define wait-time (if (even? cur-time) 0 change))
                        (define total-time (+ new-time wait-time))
                        (define ways (vector-ref distances neighbor))
                        (when (< total-time (vector-ref ways 0))
                          (vector-set! distances neighbor (vector total-time (vector-ref ways 1)))
                          (priority-queue-enqueue! pq (vector total-time neighbor)))
                        (when (and (< total-time (vector-ref ways 1))
                                   (> total-time (vector-ref ways 0)))
                          (vector-set! distances neighbor (vector (vector-ref ways 0) total-time))
                          (priority-queue-enqueue! pq (vector total-time neighbor))))
                      (vector-ref graph cur-node))
        (loop))))

  (dijkstra)
  (define final (vector-ref (vector-ref (make-vector n (vector +inf.0)) (sub1 n)) 1))
  (if (= final +inf.0) -1 final))