(define (isomorphic-strings s t)
  (define (helper s t)
    (define mapping-s (make-hash))
    (define mapping-t (make-hash))
    (for ([i (in-range (string-length s))])
      (define char-s (string-ref s i))
      (define char-t (string-ref t i))
      (define mapped-s (hash-ref mapping-s char-s #f))
      (define mapped-t (hash-ref mapping-t char-t #f))
      (if (or (and mapped-s (not (= mapped-s char-t)))
              (and mapped-t (not (= mapped-t char-s))))
          (return #f)
          (begin
            (hash-set! mapping-s char-s char-t)
            (hash-set! mapping-t char-t char-s))))
    #t)
  (if (= (string-length s) (string-length t))
      (helper s t)
      #f))