(define (minFoodBuckets (food (listof integer)))
  (define n (length food))
  (define dp (make-vector (+ n 1) 0))
  (for ([i (in-range 1 (+ n 1))])
    (define maxFood 0)
    (for ([j (in-range 1 (min i 3))])
      (set! maxFood (max maxFood (vector-ref food (- i j)))))
    (vector-set! dp i (+ maxFood (if (>= i 3) (vector-ref dp (- i 3)) 0))))
  (vector-ref dp n))