(define (find-even-numbers digits)
  (define (is-even? n) (= (modulo n 2) 0))
  (define (valid-number? num)
    (and (>= num 100) (< num 1000) (is-even? num)))
  (define (generate-numbers lst)
    (for/fold ([result '()]) ([d1 lst] [d2 lst] [d3 lst])
      (define num (+ (* 100 d1) (* 10 d2) d3))
      (if (valid-number? num)
          (cons num result)
          result)))
  (define unique-digits (remove-duplicates digits))
  (define all-numbers (generate-numbers unique-digits))
  (remove-duplicates (sort all-numbers <)))