(define (highest-ranked-items items price-range k)
  (define (filter-items items)
    (filter (lambda (item)
              (and (<= (item 'price) (second price-range))
                   (>= (item 'price) (first price-range))))
            items))
  (define (sort-items items)
    (sort items (lambda (a b)
                  (let ((price-a (a 'price))
                        (price-b (b 'price)))
                    (if (= price-a price-b)
                        (< (a 'id) (b 'id))
                        (< price-a price-b)))))
  (define filtered-items (filter-items items))
  (define sorted-items (sort-items filtered-items))
  (map (lambda (item) (item 'id)) (take sorted-items k)))

(define (k-highest-ranked-items-within-price-range items price k)
  (highest-ranked-items items price k))