(define (get-skyline buildings)
  (define heights (map (λ (b) (list (car b) (cadr b) (caddr b))) buildings))
  (define events (map (λ (h) (list (car h) (caddr h))) heights))
  (define end-events (map (λ (h) (list (cadr h) (caddr h))) heights))
  (define all-events (append (map (λ (e) (list (car e) (caddr e) #t)) events)
                              (map (λ (e) (list (cadr e) (caddr e) #f)) end-events)))
  (define sorted-events (sort all-events (λ (x y) (or (< (car x) (car y))
                                                       (and (= (car x) (car y))
                                                            (< (cadr x) (cadr y)))))))
  (define result '())
  (define height-map (make-hash))
  (define current-height 0)
  (for-each (λ (event)
              (let ((position (car event))
                    (height (cadr event))
                    (is-start? (caddr event)))
                (if is-start?
                    (begin
                      (hash-set! height-map height (+ (hash-ref height-map height 0) 1))
                      (let ((max-height (apply max (hash-map height-map (λ (k v) v)))))
                        (when (> max-height current-height)
                          (set! current-height max-height)
                          (set! result (append result (list (list position current-height)))))))
                    (begin
                      (hash-set! height-map height (- (hash-ref height-map height) 1))
                      (when (= (hash-ref height-map height) 0)
                        (hash-remove! height-map height))
                      (let ((max-height (apply max (hash-map height-map (λ (k v) v)))))
                        (when (< max-height current-height)
                          (set! current-height max-height)
                          (set! result (append result (list (list position current-height))))))))))
            sorted-events)
  result)