(define (mergeNodes head)
  (define (helper node)
    (if (null? node)
        '()
        (let loop ((current node)
                   (sum 0)
                   (result '()))
          (cond
            ((null? current) (if (> sum 0) (cons sum result) (reverse result)))
            ((= (car current) 0)
             (if (= sum 0)
                 (loop (cdr current) sum result)
                 (loop (cdr current) 0 (cons sum result)))
            (else (loop (cdr current) (+ sum (car current)) result))))))
  (helper head))