(define (countPairs nums k)
  (define freq (make-vector k 0))
  (for-each (lambda (num)
              (vector-set! freq (modulo num k) (+ (vector-ref freq (modulo num k)) 1)))
            nums)
  (define count 0)
  (for ([i (in-range (add1 (quotient k 2)))])
    (if (= i 0)
        (define pairs (/ (* (vector-ref freq 0) (- (vector-ref freq 0) 1)) 2))
        (set! count (+ count (* (vector-ref freq i) (vector-ref freq (- k i))))))
    (when (= i (quotient k 2))
      (set! count (+ count (/ (* (vector-ref freq i) (- (vector-ref freq i) 1)) 2)))))
  count)