(define (mostFrequent nums key)
  (define freq (make-hash))
  (define key-found #f)
  (for ([num nums])
    (when key-found
      (hash-set! freq num (+ (hash-ref freq num 0) 1)))
    (when (= num key)
      (set! key-found #t)))
  (define max-freq 0)
  (define result #f)
  (for ([entry (hash-map freq)])
    (when (> (cdr entry) max-freq)
      (set! max-freq (cdr entry))
      (set! result (car entry))))
  result)