(define (containsNearbyAlmostDuplicate nums k t)
  (define len (length nums))
  (define (abs x) (if (< x 0) (- x) x))
  (define (check i j)
    (and (< j len) (<= (abs (- (list-ref nums i) (list-ref nums j))) t)))
  (for ([i (in-range len)])
    (for ([j (in-range (+ i 1) (min (+ i k 1) len))])
          #:when (check i j))
      (return #t)))
  #f)