(define (countArtifacts n artifacts)
  (define graph (make-vector n '()))
  (for-each (lambda (artifact)
              (let ((a (vector-ref artifact 0))
                    (b (vector-ref artifact 1)))
                (vector-set! graph a (cons b (vector-ref graph a)))
                (vector-set! graph b (cons a (vector-ref graph b)))))
            artifacts)

  (define visited (make-vector n #f))

  (define (dfs node)
    (set! visited (vector-set! visited node #t))
    (define count 1)
    (for-each (lambda (neighbor)
                (unless (vector-ref visited neighbor)
                  (set! count (+ count (dfs neighbor)))))
              (vector-ref graph node))
    count)

  (define total 0)
  (for-each (lambda (i)
              (unless (vector-ref visited i)
                (set! total (+ total (dfs i)))))
            (range n))
  total)