(define (minimum-white-tiles carpet-length carpet-count floor)
  (define n (length floor))
  (define dp (make-vector (add1 n) +inf.0))
  (vector-set! dp 0 0)
  (define (cover start end)
    (let loop ((i start) (count carpet-count))
      (if (or (>= i (min end n)) (zero? count))
          (vector-ref dp end)
          (begin
            (vector-set! dp (max i end) (min (vector-ref dp (max i end)) (vector-ref dp i)))
            (loop (add1 i) count))))
  (for ((i n))
    (let ((white (if (< (vector-ref floor i) 1) 0 1)))
      (if (and (> white 0) (> carpet-count 0))
          (cover (max 0 (- i carpet-length)) i)
          (vector-set! dp i (+ white (vector-ref dp (max 0 (- i 1))))))))
  (vector-ref dp n))