(define (maximal-square matrix)
  (if (null? matrix) 0)
  (define rows (length matrix))
  (define cols (length (car matrix)))
  (define dp (make-vector (+ 1 rows) (make-vector (+ 1 cols) 0)))
  (define max-side 0)
  (for ([i (in-range 1 (+ 1 rows))])
    (for ([j (in-range 1 (+ 1 cols))])
      (when (equal? (string-ref (list-ref matrix (- i 1)) (- j 1)) #\1)
        (let ([side (min (vector-ref dp (- i 1) (- j 1))
                         (vector-ref dp (- i 1) j)
                         (vector-ref dp i (- j 1)))])
          (vector-set! dp i j (+ side 1))
          (set! max-side (max max-side (+ side 1))))))
  (* max-side max-side))