(define (compute-area ax1 ay1 ax2 ay2 bx1 by1 bx2 by2)
  (define (rect-area x1 y1 x2 y2)
    (if (or (>= x2 x1) (>= y2 y1))
        (* (- x2 x1) (- y2 y1))
        0))
  (define area1 (rect-area ax1 ay1 ax2 ay2))
  (define area2 (rect-area bx1 by1 bx2 by2))
  (define overlap-x (max 0 (min ax2 bx2) (max ax1 bx1)))
  (define overlap-y (max 0 (min ay2 by2) (max ay1 by1)))
  (define overlap-area (* overlap-x overlap-y))
  (- (+ area1 area2) overlap-area))