(define (countUnguarded m n guards)
  (define grid (make-vector m (lambda () (make-vector n #f))))
  (for-each (lambda (g) (vector-set! (vector-ref grid (car g)) (cadr g) #t)) guards)
  (for-each (lambda (g)
              (let loop ((i (car g)) (j (cadr g)))
                (when (and (>= i 0) (< i m) (>= j 0) (< j n))
                  (when (not (vector-ref (vector-ref grid i) j))
                    (vector-set! (vector-ref grid i) j #t))
                  (loop (- i 1) j)
                  (loop (+ i 1) j)
                  (loop i (- j 1))
                  (loop i (+ j 1)))))
            guards)
  (define count 0)
  (for ([i (in-range m)] [j (in-range n)])
    (when (not (vector-ref (vector-ref grid i) j))
      (set! count (+ count 1))))
  count)

(define (countUnguardedCells m n guards)
  (countUnguarded m n guards))