(define (appealSum s)
  (define n (string-length s))
  (define total 0)
  (define last-pos (make-vector 26 -1))
  (for ([i (in-range n)])
    (let ([char (- (char->integer (string-ref s i)) (char->integer #\a))])
      (vector-set! last-pos char i)
      (for ([j (in-range 26)])
        (if (= (vector-ref last-pos j) -1)
            (set! total (+ total (add1 i)))
            (set! total (+ total (- i (vector-ref last-pos j)))))))
      )
    )
  total)

(define (count-appeal s)
  (appealSum s))