(define (k-beauty x k)
  (define (is-beautiful? s)
    (and (not (string=? s "")) (not (equal? (string->number s) 0))))
  (define str-x (number->string x))
  (define length (string-length str-x))
  (define k-beauty-count 0)
  (for ([i (in-range (- length k -1))])
    (define substring (substring str-x i (+ i k)))
    (when (is-beautiful? substring)
      (set! k-beauty-count (+ k-beauty-count 1))))
  k-beauty-count)

(define (kBeauty x k)
  (k-beauty x k))