(define (summaryRanges nums)
  (define (helper nums start end)
    (if (null? nums)
        (if (= start end) 
            (list (number->string start))
            (list (string-append (number->string start) "->" (number->string end))))
        (if (= (car nums) (+ end 1))
            (helper (cdr nums) start (car nums))
            (cons (if (= start end) 
                      (number->string start) 
                      (string-append (number->string start) "->" (number->string end)))
                  (helper (cdr nums) (car nums) (car nums))))))
  (if (null? nums) '() (helper (cdr nums) (car nums) (car nums))))