(define (applyDiscount sentence discount)
  (define (apply-to-price price)
    (number->string (round (* (string->number price) (/ (- 100 discount) 100)))))
  (define (process-word word)
    (if (string-match? "^[0-9]+(\\.[0-9]+)?$" word)
        (apply-to-price word)
        word))
  (define words (string-split sentence))
  (define modified-words (map process-word words))
  (string-join modified-words " "))