(define (calculateTax brackets income)
  (define (helper brackets income tax-acc)
    (if (null? brackets)
        tax-acc
        (let* ((current (car brackets))
               (upper (car current))
               (rate (cadr current))
               (prev-upper (if (null? (cdr brackets)) income (car (cdr brackets))))
               (taxable-income (min (- upper (if (null? (cdr brackets)) 0 (car (car brackets)))) income))
               (tax (if (> taxable-income 0)
                        (* taxable-income (/ rate 100))
                        0)))
          (helper (cdr brackets) (max 0 (- income upper)) (+ tax-acc tax)))))
  (helper brackets income 0))