(define (min-path-cost grid move-cost)
  (define rows (length grid))
  (define cols (length (first grid)))
  (define dp (make-vector rows (make-vector cols +inf.0)))
  (vector-set! dp 0 0 (vector-ref (vector-ref grid 0) 0))

  (for ([i (in-range rows)]
        [j (in-range cols)])
    (for ([k (in-range (max 0 (- i 1)) (min rows (+ i 2)))])
      (for ([l (in-range (max 0 (- j 1)) (min cols (+ j 2)))])
        (when (and (not (and (= k i) (= l j)))
                   (>= k 0) (< k rows)
                   (>= l 0) (< l cols))
          (let ([cost (+ (vector-ref (vector-ref grid i) j)
                         (vector-ref (vector-ref move-cost k) l))])
            (vector-set! dp i j (min (vector-ref dp i j) cost)))))
    (when (> j 0)
      (vector-set! dp i j (min (vector-ref dp i j) (vector-ref dp i (- j 1)))))
    (when (> i 0)
      (vector-set! dp i j (min (vector-ref dp i j) (vector-ref dp (- i 1) j)))))
  (apply min (for/list ([j (in-range cols)]) (vector-ref dp (- rows 1) j))))