(define (longest-binary-subsequence s k)
  (define n (string-length s))
  (define count 0)
  (define result 0)
  (for ((i (in-range n)))
    (when (equal? (string-ref s i) #\1)
      (set! count (+ count 1)))
    (when (< (string->number (substring s 0 (+ i 1))) (+ k 1))
      (set! result (max result (+ count 1)))))
  result)