(define (maximumScore(nums1 nums2))
  (define n (length nums1))
  (define sum1 (apply + nums1))
  (define sum2 (apply + nums2))
  (define (max-sum arr1 arr2)
    (define len (length arr1))
    (define prefix (make-vector (+ len 1) 0))
    (for ([i (in-range len)])
      (vector-set! prefix (+ i 1) (+ (vector-ref prefix i) (vector-ref arr1 i))))
    (define suffix (make-vector (+ len 1) 0))
    (for ([i (in-range (- len 1) -1 -1)])
      (vector-set! suffix i (+ (vector-ref suffix (+ i 1)) (vector-ref arr1 i))))
    (define max-sum 0)
    (for ([i (in-range len)])
      (set! max-sum (max max-sum (+ (vector-ref suffix i) (vector-ref prefix (+ i 1))))))
    max-sum)
  (max (max-sum nums1 nums2) (max-sum nums2 nums1)))