(define (minScore n edges)
  (define (build-graph edges)
    (define graph (make-vector n '()))
    (for-each (lambda (edge)
                (let ((u (car edge))
                      (v (cadr edge)))
                  (vector-set! graph u (cons v (vector-ref graph u)))
                  (vector-set! graph v (cons u (vector-ref graph v)))))
              edges)
    graph)

  (define (dfs node parent)
    (define min-score (vector-ref scores node))
    (for-each (lambda (neighbor)
                (when (not (= neighbor parent))
                  (set! min-score (min min-score (dfs neighbor node)))))
              (vector-ref graph node))
    min-score)

  (define graph (build-graph edges))
  (define scores (make-vector n (lambda () (random 100))))
  (dfs 0 -1))

(define (minScoreAfterRemovals n edges)
  (minScore n edges))