(define (spiralMatrix m n)
  (define result (make-vector m (make-vector n 0)))
  (define left 0)
  (define right (- n 1))
  (define top 0)
  (define bottom (- m 1))
  (define num 1)

  (define (fill-spiral)
    (when (<= left right)
      (for ([i (in-range left right +1)])
        (vector-set! (vector-ref result top) i num)
        (set! num (+ num 1)))
      (set! top (+ top 1)))
    (when (<= top bottom)
      (for ([i (in-range top bottom +1)])
        (vector-set! (vector-ref result i right) num)
        (set! num (+ num 1)))
      (set! right (- right 1)))
    (when (<= left right)
      (for ([i (in-range right left -1)])
        (vector-set! (vector-ref result bottom) i num)
        (set! num (+ num 1)))
      (set! bottom (- bottom 1)))
    (when (<= top bottom)
      (for ([i (in-range bottom top -1)])
        (vector-set! (vector-ref result i left) num)
        (set! num (+ num 1)))
      (set! left (+ left 1)))
    (when (and (<= left right) (<= top bottom))
      (fill-spiral)))

  (fill-spiral)
  result)