(define (latestTimeToCatchBus buses passengers capacity)
  (define sorted-buses (sort buses <))
  (define sorted-passengers (sort passengers <))
  (define (find-passengers bus)
    (define count 0)
    (for ([p sorted-passengers])
      (when (and (< count capacity) (<= p bus))
        (set! count (+ count 1))))
    count)

  (define (find-latest-time bus)
    (if (and (not (null? sorted-passengers))
             (<= (car sorted-passengers) bus))
        (let loop ([p (car sorted-passengers)] [last-time bus])
          (if (null? sorted-passengers)
              last-time
              (if (< p bus)
                  (loop (cdr sorted-passengers) (sub1 last-time))
                  (sub1 last-time))))
        bus))

  (define latest-time 0)
  (for ([bus sorted-buses])
    (define passengers-count (find-passengers bus))
    (if (< passengers-count capacity)
        (set! latest-time (max latest-time bus))
        (let ([time (find-latest-time bus)])
          (set! latest-time (max latest-time time)))))
  (if (> latest-time 0)
      (if (zero? (modulo latest-time 100))
          (format "~a" (- latest-time 1))
          (format "~a" latest-time))
      "00:00"))