(define (fillCups A)
  (define (max-heapify h n i)
    (define largest i)
    (define left (+ (* 2 i) 1))
    (define right (+ (* 2 i) 2))
    (when (and (< left n) (> (list-ref h left) (list-ref h largest)))
      (set! largest left))
    (when (and (< right n) (> (list-ref h right) (list-ref h largest)))
      (set! largest right))
    (when (not (= i largest))
      (let ([temp (list-ref h i)])
        (set! (list-ref h i) (list-ref h largest))
        (set! (list-ref h largest) temp)
        (max-heapify h n largest))))

  (define (build-max-heap h n)
    (for ((i (in-range (floor (/ n 2)) -1 -1)))
      (max-heapify h n i)))

  (define (heap-sort h)
    (define n (length h))
    (build-max-heap h n)
    (for ((i (in-range (- n 1) 0 -1)))
      (let ([temp (list-ref h 0)])
        (set! (list-ref h 0) (list-ref h i))
        (set! (list-ref h i) temp)
        (max-heapify h i 0)))
    h)

  (define (time-to-fill h)
    (define total 0)
    (for ((cup (in-list h)))
      (set! total (+ total (max 0 cup))))
    total)

  (define cups (heap-sort A))
  (let loop ([time 0])
    (if (time-to-fill cups) 
        (begin
          (set! (list-ref cups 0) (- (list-ref cups 0) 1))
          (set! (list-ref cups 1) (- (list-ref cups 1) 1))
          (loop (+ time 1)))
        time)))

(fillCups '(1 4 2))