(define (arithmeticTriplets nums diff)
  (define count 0)
  (define num-set (set nums))
  (for-each (lambda (x)
              (when (and (set-member? num-set (+ x diff))
                         (set-member? num-set (+ x (* 2 diff))))
                (set! count (+ count 1))))
            nums)
  count)