(define (largest-local matrix)
  (define n (sub1 (length matrix)))
  (define m (sub1 (length (car matrix))))
  (define (max-in-3x3 i j)
    (apply max (map (lambda (row) (apply max (sublist row j (+ j 3)))) (sublist matrix i (+ i 3)))))
  (define result (for/list ([i (in-range n)]))
    (for/list ([j (in-range m)])
      (max-in-3x3 i j))))
  result)