(define (minimum-recolors blocks k)
  (define (count-white blocks)
    (foldl (lambda (b acc)
             (if (equal? b "W")
                 (+ acc 1)
                 acc)) 
           0 
           blocks))
  (define n (length blocks))
  (define min-white (count-white (substring blocks 0 k)))
  (define current-white min-white)
  (for ([i (in-range 1 (- n k 1))])
    (set! current-white (if (equal? (string-ref blocks (- i 1)) "W")
                            (- current-white 1)
                            current-white))
    (set! current-white (if (equal? (string-ref blocks (+ i k -1)) "W")
                            (+ current-white 1)
                            current-white))
    (set! min-white (min min-white current-white)))
  min-white)