(define (product-except-self nums)
  (define n (length nums))
  (define result (make-vector n 1))
  (define left-product 1)
  (for ([i (in-range n)])
    (vector-set! result i left-product)
    (set! left-product (* left-product (vector-ref nums i))))
  (define right-product 1)
  (for ([i (in-range (- n 1) -1 -1)])
    (vector-set! result i (* (vector-ref result i) right-product))
    (set! right-product (* right-product (vector-ref nums i))))
  (vector->list result))