(define (max-sliding-window nums k)
  (define (helper nums k)
    (define n (length nums))
    (if (or (zero? n) (<= k 0))
        '()
        (let loop ((i 0) (deq '()) (result '()))
          (if (< i n)
              (begin
                (set! deq (filter (lambda (x) (>= x i)) deq))
                (set! deq (append (filter (lambda (x) (<= (list-ref nums x) (list-ref nums i))) deq) (list i)))
                (when (>= i (- k 1))
                  (set! result (append result (list (list-ref nums (car deq))))))
                (loop (+ i 1) deq result))
              result))))
  (helper nums k))