(define (find-equal-sum-subarrays nums)
  (define sums (make-hash))
  (define result '())
  (for ([i (in-range (length nums))])
    (define current-sum 0)
    (for ([j (in-range i (length nums))])
      (set! current-sum (+ current-sum (list-ref nums j)))
      (hash-set! sums current-sum (cons (list i j) (hash-ref sums current-sum '())))
      (when (hash-has-key? sums current-sum)
        (for ([pair (hash-ref sums current-sum '())])
          (when (not (equal? pair (list i j)))
            (set! result (cons (list (car pair) (cadr pair) i j) result)))))))
  (map (lambda (x) (list (car x) (cadr x) (caddr x) (cadddr x))) result))

(define (main)
  (define nums (vector->list (vector 1 2 3 4 5 6 7 8 9)))
  (find-equal-sum-subarrays nums))

(main)