(define (most-frequent-even nums)
  (define counts (make-hash))
  (for-each
   (lambda (num)
     (when (even? num)
       (hash-set! counts num (+ (hash-ref counts num 0) 1))))
   nums)
  (define max-count 0)
  (define result -1)
  (for-each
   (lambda (num)
     (when (> (hash-ref counts num 0) max-count)
       (set! max-count (hash-ref counts num 0))
       (set! result num))
     (when (and (= (hash-ref counts num 0) max-count)
                (< num result))
       (set! result num)))
   (hash-keys counts))
  result)