(define (diffWaysToCompute expression)
  (if (string? expression)
      (let loop ((i 0) (result '()))
        (cond
          ((= i (string-length expression)) (list '()))
          ((char=? (string-ref expression i) #\+) 
           (append (loop (+ i 1) result) 
                   (map (lambda (x) (append (list (string->number (substring expression 0 i))) x)) 
                        (append (diffWaysToCompute (substring expression (+ i 1))) (list '())))))
          ((char=? (string-ref expression i) #\-) 
           (append (loop (+ i 1) result) 
                   (map (lambda (x) (append (list (string->number (substring expression 0 i))) x)) 
                        (append (diffWaysToCompute (substring expression (+ i 1))) (list '())))))
          ((char=? (string-ref expression i) #\*) 
           (append (loop (+ i 1) result) 
                   (map (lambda (x) (append (list (string->number (substring expression 0 i))) x)) 
                        (append (diffWaysToCompute (substring expression (+ i 1))) (list '())))))
          (else (loop (+ i 1) result)))))
    (list (string->number expression))))