(define (sum-prefix-scores words)
  (define prefix-scores (make-hash))
  (for-each (lambda (word)
              (for/fold ([prefix ""])
                        ([i (in-range (string-length word))])
                (define new-prefix (string-append prefix (string (string-ref word i))))
                (hash-set! prefix-scores new-prefix (+ (hash-ref prefix-scores new-prefix 0) 1))
                new-prefix))
            words)
  (map (lambda (word)
         (for/fold ([prefix ""] [total 0])
                   ([i (in-range (string-length word))])
           (define new-prefix (string-append prefix (string (string-ref word i))))
           (values new-prefix (+ total (hash-ref prefix-scores new-prefix 0)))))
       words))

(define (sum-prefix-scores-of-strings words)
  (map (lambda (x) (second x))
       (sum-prefix-scores words)))