(define (max-sum-hourglass grid)
  (define (hourglass-sum i j)
    (+ (list-ref (list-ref grid i) j)
       (list-ref (list-ref grid i) (+ j 1))
       (list-ref (list-ref grid i) (+ j 2))
       (list-ref (list-ref grid (+ i 1)) (+ j 1))
       (list-ref (list-ref grid (+ i 2)) j)
       (list-ref (list-ref grid (+ i 2)) (+ j 1))
       (list-ref (list-ref grid (+ i 2)) (+ j 2))))

  (define max-sum -inf)
  (for ([i (in-range 0 (- (length grid) 2))])
    (for ([j (in-range 0 (- (length (list-ref grid i)) 2))])
      (set! max-sum (max max-sum (hourglass-sum i j)))))
  max-sum)

(max-sum-hourglass '((1 1 1 0 0 0)
                      (0 1 0 0 0 0)
                      (1 1 1 0 0 0)
                      (0 0 2 4 4 0)
                      (0 0 1 2 4 0)
                      (0 0 0 2 0 1)))