(define (countPaths matrix k)
  (define rows (length matrix))
  (define cols (length (first matrix)))
  (define dp (make-vector rows))
  (for ([i (in-range rows)])
    (vector-set! dp i (make-vector cols (make-vector k 0))))
  (vector-set! (vector-ref dp 0) 0 (vector-fill! (make-vector k 0) 0 1))

  (for ([i (in-range rows)])
    (for ([j (in-range cols)])
      (for ([mod (in-range k)])
        (define new-mod (mod (+ mod (vector-ref (vector-ref matrix i) j)) k))
        (when (> i 0)
          (vector-set! (vector-ref dp i) j (vector-ref (vector-ref dp (sub1 i)) j)))
        (when (> j 0)
          (vector-set! (vector-ref dp i) j (modulo (+ (vector-ref (vector-ref dp i) j) 
                                                       (vector-ref (vector-ref dp i) (sub1 j))) k)))
        (vector-set! (vector-ref dp i) j (modulo (+ (vector-ref (vector-ref dp i) j) 
                                                     (vector-ref (vector-ref dp (sub1 i)) j)) k)))))

  (define result 0)
  (for ([i (in-range rows)])
    (for ([j (in-range cols)])
      (set! result (+ result (vector-ref (vector-ref dp i) j)))))

  result)