#lang racket

(define (create-components-with-same-value edges value)
  (define (dfs node visited)
    (set! visited (set-add visited node))
    (define sum (vector-ref values node))
    (for-each (lambda (neighbor)
                (when (not (set-member? visited neighbor))
                  (define next-sum (dfs neighbor visited))
                  (set! sum (+ sum next-sum))))
              (vector-ref graph node))
    sum)

  (define (count-components)
    (define visited (set))
    (define count 0)
    (for ([i (in-range (vector-length graph))])
      (when (not (set-member? visited i))
        (when (zero? (modulo (dfs i visited) value))
          (set! count (+ count 1)))))
    count)

  (define n (length edges))
  (define graph (make-vector n '()))
  (define values (make-vector n 0))
  (for ([edge edges])
    (define u (car edge))
    (define v (cadr edge))
    (vector-set! graph u (cons v (vector-ref graph u)))
    (vector-set! graph v (cons u (vector-ref graph v))))
  (for ([i (in-range n)])
    (vector-set! values i value))
  (count-components))

(define edges '((0 1) (1 2) (1 3)))
(define value 3)
(create-components-with-same-value edges value)