(define (countUnequalTriplets arr)
  (define n (length arr))
  (define count 0)
  (for ([i (in-range n)])
    (for ([j (in-range i)])
      (for ([k (in-range j)])
        (when (and (not (= (list-ref arr i) (list-ref arr j)))
                   (not (= (list-ref arr i) (list-ref arr k)))
                   (not (= (list-ref arr j) (list-ref arr k))))
          (set! count (+ count 1))))))
  count)