(define (removeNodes head)
  (define (helper node max-so-far)
    (if (null? node)
        '()
        (let* ((next (helper (cdr node) (max max-so-far (car node))))
               (current (car node)))
          (if (>= current max-so-far)
              (cons current next)
              next))))
  (let ((result (helper head -inf)))
    (if (null? result)
        '()
        (reverse result))))

(define (removeNodesFromLinkedList head)
  (if (null? head)
      '()
      (let* ((list (removeNodes head))
             (new-head (make-node (car list)))
             (current new-current new-head))
        (for-each (lambda (val)
                     (set! current (set-cdr! current (make-node val)))
                     (set! current (cdr current)))
                   (cdr list))
        new-head)))