(define (countSubarrays nums k)
  (define n (length nums))
  (define (count-ways arr)
    (define count 0)
    (define prefix-sum (make-vector (+ n 1) 0))
    (for ([i (in-range n)])
      (vector-set! prefix-sum (+ 1 (if (= (vector-ref arr i) 1) 1 0)) (1+ (vector-ref prefix-sum i))))
    (for ([j (in-range n)])
      (define m (if (<= j 0) 0 (vector-ref prefix-sum j)))
      (for ([i (in-range j n)])
        (define m2 (if (<= i 0) 0 (vector-ref prefix-sum i)))
        (when (= m m2)
          (set! count (+ count 1)))))
    count)

  (define transformed (map (lambda (x) (cond ((< x k) -1) ((= x k) 0) ((> x k) 1))) nums))
  (count-ways transformed))

(countSubarrays '(1 3 2 4 5) 3)