(define (delete-greatest-value grid)
  (define (max-in-row row)
    (apply max row))
  (define (remove-max row max-value)
    (filter (lambda (x) (not (= x max-value))) row))
  (define max-values (map max-in-row grid))
  (for-each (lambda (max-value row)
              (set! grid (cons (remove-max row max-value) (cdr grid))))
            max-values grid)
  grid)