(define (maxScore nums k)
  (define n (length nums))
  (define total-sum (apply + nums))
  (define (max-sum-subarray arr len)
    (define max-sum (apply + (take arr len)))
    (define current-sum max-sum)
    (for ([i (in-range len n)])
      (set! current-sum (+ current-sum (list-ref arr i) (- (list-ref arr (- i len)))))
      (set! max-sum (max max-sum current-sum)))
    max-sum)
  (for/sum ([i (in-range 0 (add1 k))])
    (max-sum-subarray (take (reverse nums) i) (- k i)))
  )