(define (create)
  (let ((arr '())
        (sums '()))
    (define (update i val)
      (set! arr (vector->list (vector-map (lambda (v) (if (= (vector-ref arr i) v) val v)) (list->vector arr))))
      (set! sums (map (lambda (x) (if (< x i) (vector-ref arr x) (+ (vector-ref arr x) val))) (range (length arr)))))
    (define (sumRange i j)
      (apply + (sublist sums i (add1 j))))
    (define (get-arr) arr)
    (define (get-sums) sums)
    (lambda (op . args)
      (cond
        ((equal? op 'update) (apply update args))
        ((equal? op 'sumRange) (apply sumRange args))
        (else (error "Unknown operation"))))))

(define handler (create))
(handler 'update 0 1)
(handler 'update 1 2)
(handler 'sumRange 0 1)
(handler 'update 1 3)
(handler 'sumRange 0 2)