(define (countRootNodes edges)
  (define in-degrees (make-vector (add1 (length edges)) 0))
  (for-each (lambda (edge)
              (vector-set! in-degrees (car edge) (+ (vector-ref in-degrees (car edge)) 1)))
            edges)
  (define count 0)
  (for-each (lambda (i)
              (when (= (vector-ref in-degrees i) 0)
                (set! count (+ count 1))))
            (range (vector-length in-degrees)))
  count)

(define (countRootNodes edges)
  (define in-degrees (make-vector (add1 (apply max (map max edges))) 0))
  (for-each (lambda (edge)
              (vector-set! in-degrees (car edge) (+ (vector-ref in-degrees (car edge)) 1)))
            edges)
  (define count 0)
  (for-each (lambda (i)
              (when (= (vector-ref in-degrees i) 0)
                (set! count (+ count 1))))
            (range (vector-length in-degrees)))
  count)