(define (collectCoins edges coins)
  (define (build-tree edges)
    (let ((tree (make-hash)))
      (for-each (lambda (edge)
                  (let ((u (car edge))
                        (v (cadr edge)))
                    (hash-set! tree u (hash-set! (hash-ref tree u '()) v))
                    (hash-set! tree v (hash-set! (hash-ref tree v '()) u))))
                edges)
      tree))

  (define (dfs node parent visited)
    (set! visited (cons node visited))
    (for-each (lambda (child)
                (unless (member child visited)
                  (dfs child node visited)))
              (hash-ref tree node '()))
    visited)

  (define (count-coins visited)
    (length (filter (lambda (v) (> (hash-ref coins v 0) 0)) visited)))

  (define tree (build-tree edges))
  (define visited '())
  (define total-coins (count-coins (dfs 0 -1 visited)))
  total-coins)

(define (collect-coins-in-tree edges coins)
  (collectCoins edges coins))