(define (min-reverse-operations n k)
  (define (bfs)
    (define queue (list 0))
    (define visited (make-vector n #f))
    (vector-set! visited 0 #t)
    (define level 0)
    (define result -1)
    (define (process)
      (define size (length queue))
      (for ([i (in-range size)])
        (define pos (first queue))
        (set! queue (rest queue))
        (when (= pos (- n 1))
          (set! result level))
        (for ([next (list (+ pos k) (- pos k))])
          (when (and (>= next 0) (< next n) (not (vector-ref visited next)))
            (vector-set! visited next #t)
            (set! queue (append queue (list next))))))
      (when (not (= result -1)) (set! level (+ level 1))))
    (let loop ()
      (if (null? queue) result
          (begin (process) (loop)))))
  (bfs))