(define (find-prefix-common-array A B)
  (define n (length A))
  (define result (make-vector n 0))
  (define (count-prefix-common i count-a count-b)
    (if (< i n)
        (let ([new-count-a (+ count-a (if (= (vector-ref A i) 0) 0 1))])
              [new-count-b (+ count-b (if (= (vector-ref B i) 0) 0 1))])
              [common (if (= new-count-a new-count-b) new-count-a 0)])
          (vector-set! result i common)
          (count-prefix-common (+ i 1) new-count-a new-count-b)))
    result)
  (count-prefix-common 0 0 0)
  (vector->list result))