(define (frequencyTracker queries)
  (let* ((freq (make-hash))
         (freq-count (make-hash)))
    (for-each (lambda (q)
                (when (> q 0)
                  (let* ((old-freq (hash-ref freq q 0))
                         (new-freq (+ old-freq 1)))
                    (hash-set! freq q new-freq)
                    (hash-set! freq-count old-freq (sub1 (hash-ref freq-count old-freq 0)))
                    (hash-set! freq-count new-freq (add1 (hash-ref freq-count new-freq 0)))))))
              queries)
    (for-each (lambda (q)
                (when (> q 0)
                  (let ((count (hash-ref freq-count q 0)))
                    (if (> count 0)
                        (display "1")
                        (display "0"))
                    (display "\n")))))
              (range 1 (+ (apply max (hash-keys freq)) 1)))))