(define (count-seniors details)
  (define (is-senior age)
    (>= (string->number age) 60))
  (define (extract-age detail)
    (substring detail 11 13))
  (define senior-count 0)
  (for-each (lambda (detail)
              (if (is-senior (extract-age detail))
                  (set! senior-count (+ senior-count 1))))
            details)
  senior-count)