(define (findLosers n k)
  (define (helper players idx)
    (if (= (length players) 0)
        '()
        (let* ((next-idx (modulo (+ idx k -1) (length players)))
               (loser (list-ref players next-idx)))
          (set! players (remove (lambda (x) (equal? x loser)) players))
          (cons loser (helper players next-idx)))))
  (let ((losers (helper (range 1 (+ n 1)) 0)))
    (sort (remove-duplicates losers) <)))