(define (h-index citations)
  (define n (length citations))
  (define (binary-search low high)
    (if (>= low high)
        (if (>= (list-ref citations low) (+ 1 low))
            (+ 1 low)
            low)
        (let* ((mid (quotient (+ low high) 2))
               (current (list-ref citations mid)))
          (if (>= current (+ 1 mid))
              (binary-search low mid)
              (binary-search (+ mid 1 high))))))
  (binary-search 0 (sub1 n)))