(define (ways-to-split-array nums)
  (define n (length nums))
  (define prefix-sums (make-vector (add1 n) 0))
  (for ([i (in-range n)])
    (vector-set! prefix-sums (add1 i) (+ (vector-ref prefix-sums i) (list-ref nums i))))
  (define total-ways (if (zero? n) 0 0))
  (for ([i (in-range 1 n)])
    (define left-sum (vector-ref prefix-sums i))
    (define right-sum (- (vector-ref prefix-sums n) left-sum))
    (when (>= left-sum right-sum)
      (set! total-ways (+ total-ways 1))))
  total-ways)

(define (num-ways nums)
  (ways-to-split-array nums))