(define (count-continuous-subarrays nums)
  (define (check-subarray start end)
    (let loop ((i start) (min-val (list-ref nums start)) (max-val (list-ref nums start)))
      (if (> i end)
          (and (<= min-val (list-ref nums start)) (>= max-val (list-ref nums end)))
          (begin
            (set! min-val (min min-val (list-ref nums i)))
            (set! max-val (max max-val (list-ref nums i)))
            (loop (+ i 1) min-val max-val))))
  (define n (length nums))
  (define count 0)
  (for ((i (in-range n)))
    (for ((j i n))
      (when (check-subarray i j)
        (set! count (+ count 1)))))
  count)

(define (countSubarrays nums)
  (count-continuous-subarrays nums))