(define (countPoints rings)
  (define colors (string->list rings))
  (define n (/ (length colors) 2))
  (define points (make-vector 10 '()))
  (for ([i (in-range n)])
    (let* ([pos (char->integer (list-ref colors (* 2 i)))]
           [color (char->string (list-ref colors (+ (* 2 i) 1)))])
      (vector-set! points pos (cons color (vector-ref points pos)))))
  (define (is-intersecting point)
    (let ([colors (vector-ref points point)])
      (and (member "R" colors)
           (member "G" colors)
           (member "B" colors))))
  (define (count-intersections)
    (for/sum ([i (in-range 10)])
      (if (is-intersecting i) 1 0)))
  (count-intersections))

(countPoints "B0B6G0R6R0R6G0B4G0R4B5G5R5")