(define (countPairs points k)
  (define count 0)
  (define (distance p1 p2)
    (let ((dx (- (car p1) (car p2)))
          (dy (- (cadr p1) (cadr p2))))
      (+ (* dx dx) (* dy dy))))
  (for ([i (in-range (length points))])
    (for ([j (in-range (add1 i) (length points))])
      (when (= (distance (list-ref points i) (list-ref points j)) (* k k))
        (set! count (add1 count)))))
  count)