(define (minEdgeReversals edges)
  (define graph (make-hash))
  (for-each (lambda (edge)
              (let ((u (car edge))
                    (v (cadr edge)))
                (hash-set! graph u (cons v (hash-ref graph u '())))
                (hash-set! graph v (cons u (hash-ref graph v '())))))
            edges)
  (define (dfs node visited)
    (if (hash-set? (hash-ref visited node #f))
        0
        (begin
          (hash-set! visited node 'visited)
          (apply + (map (lambda (neighbor)
                          (if (hash-set? (hash-ref graph neighbor #f))
                              (dfs neighbor visited)
                              1))
                        (hash-ref graph node '()))))))
  (define visited (make-hash))
  (define count 0)
  (for-each (lambda (node)
              (unless (hash-set? (hash-ref visited node #f))
                (set! count (+ count (dfs node visited)))))
            (hash-keys graph))
  count)