(define (min-subarray-length target nums)
  (define n (length nums))
  (define (helper start end sum)
    (if (>= sum target)
        (if (< (- end start) 0)
            (+ 1 (- end start))
            (min (+ 1 (- end start)) (helper start (+ end 1) (+ sum (list-ref nums (modulo (+ end 1) n)))))
        )
        (if (< end n)
            (helper start (+ end 1) (+ sum (list-ref nums end)))
            (if (< start n)
                (helper (+ start 1) end (- sum (list-ref nums start)))
                #f)))))
  (let loop ((start 0) (end 0) (sum 0) (min-length +inf.0))
    (if (>= start n)
        (if (= min-length +inf.0) 0 min-length)
        (if (< end n)
            (loop start (+ end 1) (+ sum (list-ref nums end)) min-length)
            (let ((current-length (helper start end sum)))
              (loop (+ start 1) start sum (if current-length (min min-length current-length) min-length)))))))