(define (divide a b)
  (if (= b 0)
      (error "Division by zero")
      (let loop ((a (if (and (< a 0) (< b 0)) (- a) a))
                 (b (if (< b 0) (- b) b))
                 (result 0))
        (if (>= a b)
            (loop (- a b) (+ result 1))
            result))))

(define (divide-integers a b)
  (let ((result (divide a b)))
    (if (or (and (= result 0) (not (= a 0)))
            (and (not (= result 0)) (or (< result -2147483648) (> result 2147483647)))))
        (if (> result 0) 2147483647 -2147483648)
        result)))