(define (get-beautiful-string n k)
  (define (next-beautiful s)
    (let loop ((i (- n 1)))
      (if (< i 0)
          #f
          (let ((c (char->integer (string-ref s i))))
            (if (< c (+ 97 k))
                (let ((new-char (integer->char (+ c 1))))
                  (define new-s (string-append (substring s 0 i) (string new-char)))
                  (if (and (not (string-contains? new-s (integer->char (+ c 1))))
                           (not (string-contains? new-s (integer->char (+ c 2)))))
                      (begin
                        (define new-s (string-append new-s (make-string (- n (string-length new-s)) #\a)))
                        (if (string-contains? new-s (integer->char (+ c 1)))
                            (loop (- i 1))
                            new-s))
                      (loop (- i 1))))
                (loop (- i 1))))))
  (let ((s (make-string n #\a)))
    (if (string? (next-beautiful s))
        (next-beautiful s)
        "")))

(define (smallest-beautiful-string n k)
  (get-beautiful-string n k))