(define (subarray-sum-squares nums)
  (define n (length nums))
  (define (squared-sum lst)
    (apply + (map (lambda (x) (* x x)) lst)))
  (define (distinct-sum-squares start)
    (define seen (make-hash))
    (define total 0)
    (define squares 0)
    (for ([i start n])
      (if (hash-has-key? seen (list-ref nums i))
          (begin
            (set! total (+ total squares))
            (set! squares (squared-sum (hash-ref seen)))
            (hash-set! seen (list-ref nums i) (+ (hash-ref seen (list-ref nums i) 0) 1)))
            )
          (begin
            (hash-set! seen (list-ref nums i) 1)
            (set! squares (+ squares (expt (list-ref nums i) 2)))
            ))
      )
    total)
  (define result 0)
  (for ([i 0 n])
    (set! result (+ result (distinct-sum-squares i))))
  result)

(define (subarrayDistinctElementSumOfSquaresII nums)
  (subarray-sum-squares nums))