(define (find-champion II)
  (let loop ((candidates II))
    (if (null? candidates)
        '()
        (let* ((count (length candidates))
               (half (quotient count 2))
               (winners (for/list ((i (in-range half)))
                          (if (= (list-ref candidates i) (list-ref candidates (+ i half)))
                              (list-ref candidates i)
                              '())))
               (next-round (remove-duplicates winners)))
          (loop next-round)))))

(define (find-champion candidates)
  (if (null? candidates)
      '()
      (loop candidates)))

(find-champion '("a" "b" "a" "c" "b" "b" "c" "a" "a"))