(define (minOperations nums)
  (define (helper nums m)
    (define n (length nums))
    (define sorted (sort nums <))
    (define dp (make-vector (+ m 1) (make-vector (add1 n) 1e9)))
    (vector-set! dp 0 0)
    (for ([i (in-range n)])
      (for ([j (in-range m 0 -1)])
        (for ([k (in-range 1 (add1 n))])
          (let ([curr (vector-ref sorted (- n k))])
            (when (>= (vector-ref dp j) (+ (vector-ref dp (- j (if (= k 1) 1 0))) (if (= k 1) 1 (* 2 (if (= curr (vector-ref sorted (- n k))) 0 1)))))
              (vector-set! dp j (min (vector-ref dp j) (+ (vector-ref dp (- j (if (= k 1) 1 0))) (if (= k 1) 1 (* 2 (if (= curr (vector-ref sorted (- n k))) 0 1)))))))))))
    (for ([j (in-range m 0 -1)])
      (for ([k (in-range 1 (add1 n))])
        (when (>= j k)
          (vector-set! dp j (min (vector-ref dp j) (vector-ref dp (- j k)))))))
    (for ([j (in-range m 0 -1)])
      (when (>= j (vector-ref sorted (- n 1)))
        (vector-set! dp j (min (vector-ref dp j) (if (= j (vector-ref sorted (- n 1))) 0 1)))))
    (apply min (for/list ([j (in-range (add1 m))]) (vector-ref dp j))))
  (helper nums (length nums)))