(define (find-peaks arr)
  (define n (length arr))
  (define peaks '())
  (when (and (> n 0) (not (null? arr)))
    (for ([i (in-range n)])
      (when (or (and (= i 0) (> (list-ref arr i) (list-ref arr (+ i 1))))
                (and (= i (- n 1)) (> (list-ref arr i) (list-ref arr (- i 1))))
                (and (> i 0) (< i (- n 1)) 
                     (and (> (list-ref arr i) (list-ref arr (- i 1)))
                          (> (list-ref arr i) (list-ref arr (+ i 1))))))
        (set! peaks (cons (list-ref arr i) peaks)))))
  (reverse peaks))