(define (longest-subarray nums k)
  (define freq (make-hash))
  (define left 0)
  (define max-length 0)

  (for-each (lambda (right)
              (hash-set! freq (vector-ref nums right) 
                         (+ 1 (hash-ref freq (vector-ref nums right) 0)))
              (while (> (hash-length freq) k)
                (hash-set! freq (vector-ref nums left) 
                           (- (hash-ref freq (vector-ref nums left)) 1))
                (when (= (hash-ref freq (vector-ref nums left) 0) 0)
                  (hash-remove! freq (vector-ref nums left)))
                (set! left (+ left 1)))
              (set! max-length (max max-length (- (+ right 1) left))))
            (in-range (vector-length nums)))
  max-length)

(define (length-of-longest-subarray-with-at-most-k-frequency nums k)
  (longest-subarray (vector->list nums) k))