(define (largestPerimeter A)
  (define sorted (sort A >))
  (define (perimeter a b c)
    (if (and (< a (+ b c)) (< b (+ a c)) (< c (+ a b)))
        (+ a b c)
        0))
  (for/fold ([max-perim 0]) ([i (in-range (length sorted))])
    (define a (list-ref sorted i))
    (define b (if (> i 0) (list-ref sorted (- i 1)) 0))
    (define c (if (> i 1) (list-ref sorted (- i 2)) 0))
    (max max-perim (perimeter a b c)))
)