(define (count-incremovable-subarrays arr)
  (define n (length arr))
  (define (count-incremovable-starts)
    (define starts (make-vector n #f))
    (define left 0)
    (for ([i (in-range 1 n)])
      (if (<= (vector-ref arr i) (vector-ref arr (sub1 i)))
          (set! left (add1 left))
          (do ([j left (sub1 j)])
              ((< j 0))
            (vector-set! starts j #t)))
      (set! left (if (= left 0) 0 (add1 left))))
    starts)
  (define (count-incremovable-ends)
    (define ends (make-vector n #f))
    (define right 0)
    (for ([i (in-range (sub1 n) -1 -1)])
      (if (<= (vector-ref arr i) (vector-ref arr (add1 i)))
          (set! right (add1 right))
          (do ([j right (sub1 j)])
              ((< j 0))
            (vector-set! ends j #t)))
      (set! right (if (= right 0) 0 (add1 right))))
    ends)
  (define starts (count-incremovable-starts))
  (define ends (count-incremovable-ends))
  (define count 0)
  (for ([i (in-range n)])
    (when (vector-ref starts i)
      (set! count (+ count 1)))
    (when (vector-ref ends i)
      (set! count (+ count 1))))
  count)

(count-incremovable-subarrays (vector 1 2 3 4 5)) ; Example usage