(define (powerfulIntegers x y bound)
  (define powerful-integers (hash-set))
  (for ([i (in-range (add1 (floor (log (exact->inexact bound) (exact->inexact x)))))])
       [j (in-range (add1 (floor (log (exact->inexact bound) (exact->inexact y)))))])
    (define p (expt x i))
    (define q (expt y j))
    (define sum (+ p q))
    (when (<= sum bound)
      (hash-set! powerful-integers sum)))
  (hash-count powerful-integers))

(define (powerfulIntegers x y bound)
  (if (or (> x bound) (> y bound))
      0
      (let ((result (make-hash)))
        (for ([i (in-range (add1 (floor (log bound x)))])
              [j (in-range (add1 (floor (log bound y)))])
              #:when (<= (+ (expt x i) (expt y j)) bound))
          (hash-set! result (+ (expt x i) (expt y j))))
        (hash-count result))))