(define (find-substring s words)
  (define word-length (string-length (car words)))
  (define total-length (* word-length (length words)))
  (define word-set (for/list ([word words]) (string->symbol word)))
  (define (is-valid-substring start)
    (define seen (make-hash))
    (define count 0)
    (for ([i (in-range 0 (length words))])
      (let* ([word (substring s (+ start (* i word-length)) (+ start (* i word-length) word-length))])
             [sym (string->symbol word)])
        (if (hash-has-key? word-set sym)
            (begin
              (hash-update! seen sym (lambda (x) (+ x 1)) 1)
              (when (> (hash-ref seen sym) (hash-ref word-set sym))
                (set! count (add1 count))))
            (set! count (add1 count)))))
    (= count 0))
  (for*/list ([i (in-range 0 (- (string-length s) total-length + 1))])
    (when (is-valid-substring i)
      i)))

(find-substring "barfoothefoobarman" '("foo" "bar"))