(define (applyOperations s)
  (define (helper s ops)
    (if (null? s)
        (list 0)
        (let* ((first (car s))
               (rest (cdr s))
               (new-ops (if (and (not (null? rest))
                                 (= first (car rest)))
                             (cons (* 2 first) (cdr rest))
                             (cons first (helper rest ops)))))
          (helper (cdr new-ops) (cons (if (equal? first 0) 1 0) ops)))))
  (define result (helper (string->list s) '()))
  (if (equal? (car result) 0)
      (list '() (reverse (cdr result)))
      (list '() (reverse result))))

(applyOperations "your_input_here")