(define (shortest-subarray-or-at-least-k nums k)
  (define n (length nums))
  (define (or-sum lst)
    (foldl (lambda (x acc) (logior x acc)) 0 lst))
  (define result +inf.0)
  (define (helper start end)
    (when (< start n)
      (let loop ((i start) (or-acc 0))
        (when (< i n)
          (set! or-acc (logior or-acc (vector-ref nums i)))
          (when (>= or-acc k)
            (set! result (min result (- i start 1))))
          (loop (+ i 1) or-acc)))))
  (for-each (lambda (x) (helper 0 x)) (range n))
  (if (= result +inf.0) -1 result))

(shortest-subarray-or-at-least-k '(1 2 3 4) 5)