(define (smallestString s a)
  (define (union-find)
    (define parent (make-vector (string-length s)))
    (define (find x)
      (if (equal? (vector-ref parent x) x)
          x
          (let ((p (find (vector-ref parent x))))
            (vector-set! parent x p)
            p)))
    (define (union x y)
      (define rootX (find x))
      (define rootY (find y))
      (when (not (= rootX rootY))
        (vector-set! parent rootX rootY)))
    (for ([i (in-range (string-length s))])
      (vector-set! parent i i))
    (for ([i (in-range (sub1 (string-length s)))])
      (when (and (= (string-ref s i) #\a) (= (string-ref s (add1 i)) #\a))
        (union i (add1 i))))
    (for ([i (in-range (string-length s))])
      (find i))
    parent)

  (define parent (union-find))
  (define smallest (make-vector (string-length s)))
  (for ([i (in-range (string-length s))])
    (vector-set! smallest (find (vector-ref parent i)) (min (vector-ref smallest (find (vector-ref parent i))) (string-ref s i))))
  (define result "")
  (for ([i (in-range (string-length s))])
    (set! result (string-append result (vector-ref smallest i))))
  result)

(define (find x)
  (if (equal? (vector-ref parent x) x)
      x
      (let ((p (find (vector-ref parent x))))
        (vector-set! parent x p)
        p)))