(define (min-sum-arr nums k)
  (define (min-heapify arr n i)
    (define largest i)
    (define left (+ (* 2 i) 1))
    (define right (+ (* 2 i) 2))
    (when (and (< left n) (> (vector-ref arr left) (vector-ref arr largest)))
      (set! largest left))
    (when (and (< right n) (> (vector-ref arr right) (vector-ref arr largest)))
      (set! largest right))
    (when (not (= largest i))
      (let ([temp (vector-ref arr i)])
        (vector-set! arr i (vector-ref arr largest))
        (vector-set! arr largest temp))
      (min-heapify arr n largest)))

  (define (build-min-heap arr)
    (let loop ((i (quotient (vector-length arr) 2) - 1))
      (when (>= i 0)
        (min-heapify arr (vector-length arr) i)
        (loop (sub1 i)))))

  (define (heap-sort arr)
    (let ((n (vector-length arr)))
      (build-min-heap arr)
      (for ((i (in-range (sub1 n) 0 -1)))
        (let ((temp (vector-ref arr 0)))
          (vector-set! arr 0 (vector-ref arr i))
          (vector-set! arr i temp)
          (min-heapify arr i 0))))
    arr)

  (define heap (vector->list (heap-sort (vector->list (vector nums)))))
  (define total 0)
  (for ((i (in-range k)))
    (set! total (+ total (car heap)))
    (set! heap (cdr heap)))
  total)

(min-sum-arr (vector 1 2 3 4 5) 2)