(define (count-special-characters s)
  (define (is-special? c)
    (or (char=? c #\!) (char=? c #\@) (char=? c #\$) (char=? c #\%) 
        (char=? c #\^) (char=? c #\&) (char=? c #\*) 
        (char=? c #\() (char=? c #\)) (char=? c #\-) 
        (char=? c #\+) (char=? c #\=) (char=? c #\[) 
        (char=? c #\]) (char=? c #\{) (char=? c #\}) 
        (char=? c #\:) (char=? c #\;) (char=? c #\') 
        (char=? c #\") (char=? c #\<) (char=? c #\>) 
        (char=? c #\,) (char=? c #\.) (char=? c #\/)))
  (foldl (lambda (c acc) 
            (if (is-special? c) 
                (+ acc 1) 
                acc)) 
          0 
          (string->list s)))

(define (count-special-characters-ii s)
  (count-special-characters s))