(define (makesquare matchsticks)
  (define total (apply + matchsticks))
  (define side (/ total 4))
  (define (can-form-square sides sticks)
    (if (null? sticks)
      (and (= (length (filter (lambda (x) (= x side)) sides)) 4) (= (apply + sides) total))
      (let loop ((sides sides) (stick (car sticks)) (remaining (cdr sticks)))
        (if (null? sides)
          #f
          (let ((new-sides (map + sides (list stick))))
            (or (and (all? (lambda (x) (<= x side)) new-sides)
                     (loop (cdr sides) (car remaining) (cdr remaining)))
                (loop (cdr sides) stick remaining)))))))
  (if (or (zero? (modulo total 4)) (< side 0))
    (can-form-square (list 0 0 0 0) (sort matchsticks >))
    #f))

(define (all? pred lst)
  (foldl (lambda (x acc) (and acc (pred x))) #t lst))