(define (product-except-self nums)
  (define n (length nums))
  (define result (make-vector n 1))
  (define prefix 1)
  (for ((i 0 n))
    (vector-set! result i prefix)
    (set! prefix (* prefix (vector-ref nums i))))
  (define suffix 1)
  (for ((i (- n 1) -1))
    (vector-set! result i (* (vector-ref result i) suffix))
    (set! suffix (* suffix (vector-ref nums i))))
  (vector->list result))