(define (maxProduct words)
  (define (word-to-bitmask word)
    (foldl (lambda (ch acc) (bitwise-or acc (ash 1 (- (char->integer ch) (char->integer #\a))))) 0 word))
  (define (calculate-max-product w1 w2)
    (if (zero? (bitwise-and w1 w2)) (* (string-length (number->string w1)) (string-length (number->string w2))) 0))
  (define bitmasks (map word-to-bitmask words))
  (define max-product 0)
  (for ((i (in-range (length words)))
        (j (in-range (length words)))
        #:when (< i j))
    (set! max-product (max max-product (calculate-max-product (list-ref bitmasks i) (list-ref bitmasks j)))))
  max-product)