(define (maximumReward nums operations)
  (define n (length nums))
  (define dp (make-vector (+ 1 n) 0))
  (for ([i (in-range n)])
    (vector-set! dp (+ 1 i) (max (vector-ref dp i) (vector-ref dp (+ i 1))) (list-ref nums i)))
  (for ([op (in-range operations)])
    (define new-dp (make-vector (+ 1 n) 0))
    (for ([i (in-range n)])
      (vector-set! new-dp (+ 1 i) (max (vector-ref new-dp i) (vector-ref new-dp (+ i 1))) (list-ref nums i (+ op 1))))
      (when (> i 0)
        (vector-set! new-dp (+ 1 i) (max (vector-ref new-dp i) (vector-ref dp i) (vector-ref dp (+ i 1)))))
      (when (< (+ i 1) n)
        (vector-set! new-dp (+ 1 i) (max (vector-ref new-dp i) (vector-ref dp i) (vector-ref dp (+ i 1)))))
      )
    (set! dp new-dp))
  (apply max (vector->list dp)))

(define (maximumTotalReward nums operations)
  (maximumReward nums operations))