(define (minAreaRect points)
  (define point-set (set points))
  (define min-area (lambda (x1 y1 x2 y2)
                     (* (abs (- x1 x2)) (abs (- y1 y2)))))
  (define result (lambda ()
                   (let loop ((points points) (min-area-value +inf.0))
                     (if (null? points)
                         (if (= min-area-value +inf.0) 0 min-area-value)
                         (let* ((p1 (car points))
                                (rest (cdr points))
                                (p2 (car rest)))
                           (if (and (not (= p1 p2))
                                    (set-contains? point-set (list (car p1) (cdr p2)))
                                    (set-contains? point-set (list (car p2) (cdr p1)))
                                    (not (= (car p1) (car p2)))
                                    (not (= (cdr p1) (cdr p2)))
                                    (let ((area (min-area (car p1) (cdr p1) (car p2) (cdr p2))))
                                      (< area min-area-value)))
                               (loop rest (min min-area-value (min-area (car p1) (cdr p1) (car p2) (cdr p2))))
                               (loop rest min-area-value)))))))
  (result))

(define points '((1 1) (1 0) (0 1) (0 0) (2 2)))
(minAreaRect points)