(define (findMaxLength nums)
  (define (helper nums map)
    (if (null? nums)
        (length map)
        (let* ((num (car nums))
               (next-map (if (hash-ref map num #f)
                              (hash-set map num (1+ (hash-ref map num)))
                              (hash-set map num 1)))
               (length-without-increment (helper (cdr nums) map))
               (length-with-increment (helper (cdr nums) next-map)))
          (max length-without-increment length-with-increment))))
  (helper nums (make-hash)))