(define (max-score-grid grid)
  (let* ((n (length grid))
         (m (if (> n 0) (length (car grid)) 0))
         (dp (make-vector m 0)))
    (for ((i (in-range n)))
      (for ((j (in-range m)))
        (let* ((score (vector-ref (vector-ref grid i) j))
               (prev-max (if (zero? j) 0 (vector-ref dp (sub1 j)))))
          (vector-set! dp j (max (vector-ref dp j) (+ score prev-max))))))
    (for ((j (in-range m)))
      (let* ((score (vector-ref (vector-ref grid (sub1 n)) j)))
        (vector-set! dp j (max (vector-ref dp j) score))))
    (apply max (vector->list dp))))

(max-score-grid '((1 2 3) (4 5 6) (7 8 9)))