(define (max-removals s p removable)
  (define (can-remove k)
    (define (helper s p idx)
      (if (or (null? s) (null? p))
          (null? p)
          (if (and (not (null? p)) (not (null? s)))
              (if (equal? (car s) (car p))
                  (helper (cdr s) (cdr p) idx)
                  (if (and (<= idx (sub1 (length removable)))
                           (equal? (car s) (list-ref removable idx)))
                      (helper (cdr s) p (add1 idx))
                      (helper (cdr s) p idx))
              )
              (null? p)))
    (helper (string->list s) (string->list p) 0))

  (define (binary-search low high)
    (if (>= low high)
        low
        (define mid (quotient (+ low high) 2))
        (if (can-remove mid)
            (binary-search (add1 mid) high)
            (binary-search low mid))))

  (binary-search 0 (length removable)))