(define (finalString s)
  (define (process str)
    (define result '())
    (for-each (lambda (char)
                (if (equal? char #\b)
                    (if (not (null? result)) (set! result (cdr result)))
                    (set! result (cons char result))))
              (string->list str))
    (list->string (reverse result)))
  (process s))