(define (findMinimumTime time)
  (define n (length time))
  (define dist (make-vector n (lambda () (make-vector n +inf.0))))
  (vector-set! dist 0 (make-vector n 0))
  (define (dijkstra)
    (define pq (make-pq))
    (pq-insert! pq (list 0 0))
    (let loop ()
      (when (not (pq-empty? pq))
        (define current (pq-extract-min! pq))
        (define u (car current))
        (define curr-time (cadr current))
        (for ((v (in-range n)))
          (define new-time (+ curr-time (vector-ref (vector-ref time u) v)))
          (when (< new-time (vector-ref (vector-ref dist u) v))
            (vector-set! (vector-ref dist u) v new-time)
            (pq-insert! pq (list v new-time))))
        (loop))))
  (dijkstra)
  (apply min (vector->list (vector-ref dist (- n 1)))))