(define (maximalTargetNodes trees edges)
  (define graph (make-hash))
  (for-each (lambda (edge)
              (define u (car edge))
              (define v (cadr edge))
              (hash-set! graph u (cons v (hash-ref graph u '())))
              (hash-set! graph v (cons u (hash-ref graph v '())))))
            edges)
  (define (dfs node visited)
    (if (hash-ref visited node #f)
        0
        (begin
          (hash-set! visited node #t)
          (define total 1)
          (for-each (lambda (neighbor)
                      (set! total (+ total (dfs neighbor visited))))
                    (hash-ref graph node '()))
          total)))
  (define visited (make-hash))
  (define total-nodes (for-each (lambda (tree)
                                   (dfs tree visited))
                                 trees))
  total-nodes)