(define (zigzag-traversal grid skip)
  (define n (length grid))
  (define m (length (first grid)))
  (define result '())
  (define (traverse row col dir)
    (when (and (>= row 0) (< row n) (>= col 0) (< col m))
      (set! result (append result (list (list row col))))
      (if (not (= (car (list row col)) skip))
          (traverse (+ row dir) (+ col (if (= dir 1) 1 -1)) dir)))
    (when (or (< row 0) (>= row n) (< col 0) (>= col m))
      (if (= dir 1)
          (traverse (+ row 1) (+ col 1) -1)
          (traverse (+ row 1) (- col 1) 1))))
    )
  (traverse 0 0 1)
  result)