(define (find-improved-students scores)
  (define improved-students '())
  (for-each (lambda (student)
              (let ((id (car student))
                    (prev (cadr student))
                    (curr (caddr student)))
                (when (> curr prev)
                  (set! improved-students (cons id improved-students)))))
            scores)
  (sort improved-students <))