(define (totalFruits fruits)
  (define (max-fruits start end)
    (define count (make-hash))
    (define max-fruit 0)
    (define unique-fruits 0)
    (for ([i (in-range start end)])
      (hash-set! count (vector-ref fruits i) (+ (hash-ref count (vector-ref fruits i) 0) 1))
      (when (= (hash-ref count (vector-ref fruits i)) 1)
        (set! unique-fruits (+ unique-fruits 1)))
      (while (> unique-fruits 2)
        (hash-set! count (vector-ref fruits start) (- (hash-ref count (vector-ref fruits start)) 1))
        (when (= (hash-ref count (vector-ref fruits start)) 0)
          (set! unique-fruits (- unique-fruits 1)))
        (set! start (+ start 1)))
      (set! max-fruit (max max-fruit (- end start)))
      (set! end (+ end 1)))
    max-fruit)

  (max-fruits 0 (vector-length fruits)))