(define (analyze-subscription-conversion data)
  (define conversion-counts '())
  (define total-count 0)
  (for-each (lambda (entry)
              (let* ((split-entry (string-split entry ","))
                     (subscription (string->number (car split-entry)))
                     (conversion (string->number (cadr split-entry))))
                (set! total-count (+ total-count subscription))
                (set! conversion-counts (cons conversion conversion-counts))))
            data)
  (define average-conversion (if (> total-count 0) (/ (apply + conversion-counts) total-count) 0))
  (list average-conversion total-count))