(define (maxProfit k prices)
  (if (zero? (length prices)) 0)
  (define n (length prices))
  (if (>= k (/ n 2)) 
      (define (maxProfitInf prices)
        (define total 0)
        (for ([i (in-range 1 n)])
          (if (> (list-ref prices i) (list-ref prices (- i 1)))
              (set! total (+ total (- (list-ref prices i) (list-ref prices (- i 1))))))
          )
        total)
      (define dp (make-vector (+ 1 k) (make-vector (+ 1 n) 0)))
      (for ([i (in-range 1 (+ 1 k))])
        (define maxDiff -1)
        (for ([j (in-range 1 (+ 1 n))])
          (set! maxDiff (max maxDiff (- (vector-ref dp (- i 1)) (list-ref prices (- j 1)))))
          (vector-set! dp i j (max (vector-ref dp i j) (+ (list-ref prices (- j 1)) maxDiff))))
        )
      (vector-ref dp k n)))

(maxProfit 2 (list 3 2 6 5 0 3))