(define (minOperations nums k)
  (define n (length nums))
  (define prefix-sums (make-vector (+ n 1) 0))
  (for ([i (in-range n)])
    (vector-set! prefix-sums (+ i 1) (+ (vector-ref prefix-sums i) (vector-ref nums i))))
  (define (get-sum l r)
    (- (vector-ref prefix-sums r) (vector-ref prefix-sums l)))
  (define min-ops (make-vector n +inf.0))
  (for ([i (in-range n)])
    (for ([j (in-range i k)])
      (when (>= (+ j 1) k)
        (vector-set! min-ops i 
          (min (vector-ref min-ops i) 
               (get-sum i (+ i 1 j))))))
    (when (>= i k)
      (vector-set! min-ops i 
        (min (vector-ref min-ops i) 
             (vector-ref min-ops (- i k))))))
  (vector-ref min-ops (- n 1)))