(define (count-unique-xor-triplets nums)
  (define (xor a b) (bitwise-xor a b))
  (define (unique-triplets lst)
    (define seen (make-hash))
    (for-each (lambda (a)
                (for-each (lambda (b)
                            (for-each (lambda (c)
                                        (let* ((xor-result (xor a (xor b c)))
                                               (triplet (list a b c)))
                                          (hash-set! seen xor-result triplet))))
                                      lst)))
              lst)
    (hash-count seen))
  (unique-triplets (remove-duplicates nums)))

(define (main)
  (define nums (list 1 2 3 2 1))
  (count-unique-xor-triplets nums))

(main)