(define (smallest-palindromic-rearrangement s)
  (define freq (make-hash))
  (for-each (lambda (c) (hash-update! freq c (lambda (x) (if x (+ x 1) 1)) 0)) s)
  (define odd-char #f)
  (define half-string "")
  (for-each (lambda (key)
              (if (odd? (hash-ref freq key 0))
                  (begin
                    (set! odd-char (if (or (not odd-char) (< key odd-char)) key odd-char)))
                    (hash-set! freq key (1- (hash-ref freq key))))
                  (void))
              (set! half-string (string-append half-string (make-string (/ (hash-ref freq key 0) 2) key))))
            (hash-keys freq))
  (define palindrome (string-append half-string (if odd-char (string odd-char "")) (string-reverse half-string)))
  palindrome)