(define (max-product-of-two-digits n)
  (define (digits n)
    (if (= n 0)
        '()
        (cons (modulo n 10) (digits (quotient n 10)))))
  (define ds (digits n))
  (define max-product 0)
  (for ([i (in-range (length ds))])
    (for ([j (in-range i (+ 1 (length ds)))])
      (define product (* (list-ref ds i) (list-ref ds j)))
      (when (and (not (= i j)) (> product max-product))
        (set! max-product product))))
  max-product)

(max-product-of-two-digits 29)