(define (maximumSumOfEdgeValues edges)
  (define graph (make-hash))
  (for-each (lambda (edge)
              (define u (car edge))
              (define v (cadr edge))
              (define w (caddr edge))
              (hash-set! graph u (if (hash-has? graph u) (max w (hash-ref graph u)) w))
              (hash-set! graph v (if (hash-has? graph v) (max w (hash-ref graph v)) w)))
            edges)
  (for/fold ([max-sum 0]) ([k (hash-keys graph)])
    (define value (hash-ref graph k))
    (set! max-sum (max max-sum value))
    max-sum))

(define (maximumSum edges)
  (maximumSumOfEdgeValues edges))