(define (solve-sudoku board)
  (define (is-valid? board row col num)
    (let ((block-row (quotient row 3))
          (block-col (quotient col 3)))
      (and (not (memv num (list-ref board row)))
           (not (memv num (map (lambda (r) (list-ref r col)) board)))
           (not (memv num (apply append (map (lambda (r) (sublist r (* block-col 3) (+ (* block-col 3) 3))) (sublist board (* block-row 3) (+ (* block-row 3) 3)))))))))

  (define (solve board)
    (for ((i (in-range 9)) (j (in-range 9)))
      (when (eq? (list-ref (list-ref board i) j) #\.)
        (for ((num (in-range 1 10)))
          (when (is-valid? board i j num)
            (set! board (list-set! board i (list-set! (list-ref board i) j num)))
            (if (solve board)
                (begin (set! board board) (return #t))
                (set! board (list-set! board i (list-set! (list-ref board i) j #\.)))))
        (return #f)))
    #t)

  (solve board)
  board)