(define (combinationSum4 nums target)
  (define dp (make-vector (+ target 1) 0))
  (vector-set! dp 0 1)
  (for ([i (in-range 1 (+ target 1))])
    (for ([num nums])
      (when (>= i num)
        (vector-set! dp i (+ (vector-ref dp i) (vector-ref dp (- i num))))))
    )
  (vector-ref dp target))

(combinationSum4 '(1 2 3) 4)