(define (add-strings num1 num2)
  (define (str->num str)
    (foldl (lambda (c acc) (+ (* acc 10) (- (char->integer c) (char->integer #\0)))) 0 str))
  (define (num->str n)
    (if (= n 0) 
        (string #\0)
        (let loop ((n n) (acc '()))
          (if (= n 0)
              (list->string (reverse acc))
              (loop (floor (/ n 10)) (cons (integer->char (+ (modulo n 10) (char->integer #\0))) acc))))))
  (num->str (+ (str->num num1) (str->num num2)))
)