(define (characterReplacement s k)
  (define (max-length s k)
    (define counts (make-vector 26 0))
    (define max-count 0)
    (define left 0)
    (define result 0)
    (for ((right (in-range (string-length s))))
      (define index (- (char->integer (string-ref s right)) (char->integer #\A)))
      (vector-set! counts index (+ 1 (vector-ref counts index)))
      (set! max-count (max max-count (vector-ref counts index)))
      (while (> (- (+ 1 right) left) (+ max-count k))
        (define left-index (- (char->integer (string-ref s left)) (char->integer #\A)))
        (vector-set! counts left-index (- (vector-ref counts left-index) 1))
        (set! left (+ left 1)))
      (set! result (max result (- (+ 1 right) left))))
    result)
  (max-length s k))

(characterReplacement "AABABBA" 1)