(define-struct Node (val prev next child))

(define (flatten head)
  (define (flatten-helper node)
    (if (null? node)
        '()
        (let* ((next-node (if (null? (Node-next node)) '() (flatten-helper (Node-next node))))
               (child-node (if (null? (Node-child node)) '() (flatten-helper (Node-child node))))
               (merged (append (list node) child-node next-node)))
          (for-each (lambda (n)
                      (set! (Node-next n) (if (null? next-node) '() (first next-node)))
                      (set! (Node-prev (if (null? next-node) '() (first next-node))) n))
                    child-node)
          (set! (Node-next node) (if (null? next-node) '() (first next-node)))
          (if (not (null? (Node-next node)))
              (set! (Node-prev (first next-node)) node))
          merged)))
  (if (null? head)
      '()
      (flatten-helper head)))