(define (predict-the-winner nums)
  (define (helper left right)
    (if (= left right)
        (list (list-ref nums left) 0)
        (let* ((left-choice (helper (+ left 1) right))
               (right-choice (helper left (- right 1)))
               (left-score (- (car left-choice) (list-ref nums left)))
               (right-score (- (car right-choice) (list-ref nums right))))
          (if (>= left-score right-score)
              (list left-score (car left-choice))
              (list right-score (car right-choice)))))
  (>= (car (helper 0 (- (length nums) 1))) 0))