(define (findMinStep board hand)
  (define (helper board hand memo)
    (if (string= board "")
        0
        (if (hash-has-key? memo board)
            (hash-ref memo board)
            (define new-hand (string->list hand))
            (define min-steps +inf.0)
            (for ((i (in-range (string-length board))))
              (define char (string-ref board i))
              (define count (count (lambda (x) (char=? x char)) new-hand))
              (when (> count 0)
                (define new-board (remove-balls board char i))
                (define new-hand (string-delete new-hand (string char)))
                (define steps (helper new-board new-hand memo))
                (when (< steps min-steps)
                  (set! min-steps steps))))
            (hash-set! memo board (+ min-steps 1))
            min-steps)))
  (helper board hand (make-hash)))

(define (remove-balls board char index)
  (define left (substring board 0 index))
  (define right (substring board (+ index 1)))
  (define new-board (string-append left right))
  (define reduced-board (reduce new-board))
  reduced-board)

(define (reduce board)
  (define (loop board)
    (define (remove-adjacent board)
      (define new-board (string-append board))
      (for ((i (in-range (string-length board - 1))))
        (when (and (char=? (string-ref new-board i) (string-ref new-board (+ i 1)))
                   (> (string-length new-board) 2))
          (set! new-board (string-append (substring new-board 0 i)
                                         (substring new-board (+ i 2)))))
      new-board)
    (define reduced (remove-adjacent board))
    (if (string=? reduced board)
        reduced
        (loop reduced)))
  (loop board))