(define (find-subsequences nums)
  (define (helper start curr res)
    (if (>= start (length nums))
        (if (>= (length curr) 2) (list curr) '())
        (let ((next-res (helper (+ start 1) curr res)))
          (if (or (null? curr) (<= (last curr) (list-ref nums start)))
              (append next-res (helper (+ start 1) (append curr (list (list-ref nums start))) res))
              next-res))))
  (define (remove-duplicates lst)
    (foldl (lambda (x acc)
              (if (member x acc) acc (cons x acc)))
            '() lst))
  (remove-duplicates (helper 0 '() '())))