(define (findDiagonalOrder matrix)
  (define (in-bounds? x y)
    (and (>= x 0) (< x (length matrix)) (>= y 0) (< y (length (vector-ref matrix x)))))
  (define (traverse-diagonal x y dir)
    (if (not (in-bounds? x y))
        '()
        (cons (vector-ref (vector-ref matrix x) y)
              (traverse-diagonal (+ x dir) (+ y (- dir)) dir))))
  (define (traverse-all)
    (define result '())
    (for* ([d (in-range (length matrix))])
      (if (in-bounds? 0 d)
          (set! result (append result (traverse-diagonal 0 d 1)))))
    (for* ([d (in-range 1 (length (vector-ref matrix 0)))])
      (if (in-bounds? d (- (length (vector-ref matrix 0)) 1))
          (set! result (append result (traverse-diagonal d (- (length (vector-ref matrix 0)) 1) -1)))))
    result))
  (traverse-all))

(define (diagonalTraverse matrix)
  (if (null? matrix)
      '()
      (findDiagonalOrder matrix)))