(define (ipo k w profits capital)
  (define n (length profits))
  (define indices (map list (range n)))
  (define sorted-indices (sort indices (lambda (a b) 
                                          (let ([pa (vector-ref profits (car a))])
                                            (< (vector-ref capital (car a)) 
                                               (vector-ref capital (car b)))))))
  (define max-heap (make-heap))
  (define available 0)
  (do ((i 0 (+ i 1)))
      ((>= i n) (if (= k 0) w available))
    (while (and (< available n) 
                (<= (vector-ref capital (vector-ref sorted-indices available)) w))
      (heap-insert! max-heap (vector-ref profits (vector-ref sorted-indices available))
                     (vector-ref sorted-indices available))
      (set! available (+ available 1)))
    (if (zero? (heap-size max-heap)) 
        (break))
    (set! w (+ w (heap-extract-max! max-heap)))
    (set! k (- k 1)))
  w)