(define (next-greater-elements nums)
  (define n (length nums))
  (define result (make-vector n -1))
  (define stack '())
  (for ([i (in-range (* 2 n))])
    (let ([index (modulo i n)]
          [current (vector-ref nums (modulo i n))])
      (while (and (not (null? stack))
                  (> current (vector-ref nums (car stack))))
        (define idx (car stack))
        (vector-set! result idx current)
        (set! stack (cdr stack)))
      (if (< i n)
          (set! stack (cons index stack)))))
  (vector->list result))