(define (find-relative-ranks score)
  (define sorted-scores (sort score >))
  (define ranks (map (lambda (x) 
                       (cond ((= x (list-ref sorted-scores 0)) "Gold Medal")
                             ((= x (list-ref sorted-scores 1)) "Silver Medal")
                             ((= x (list-ref sorted-scores 2)) "Bronze Medal")
                             (else (number->string (+ 1 (index-of sorted-scores x)))))) 
                     score))
  ranks)