(define (singleNonDuplicate nums)
  (define (binary-search left right)
    (if (>= left right)
        (list-ref nums left)
        (let* ((mid (/ (+ left right) 2))
               (is-even? (even? mid)))
          (if (and is-even? (equal? (list-ref nums mid) (list-ref nums (+ mid 1))))
              (binary-search (+ mid 2) right)
              (if (and (not is-even?) (equal? (list-ref nums mid) (list-ref nums (- mid 1))))
                  (binary-search left (- mid 2))
                  (binary-search left right))))))
  (binary-search 0 (sub1 (length nums))))