(define (merge-intervals intervals)
  (define (merge-intervals-helper intervals)
    (if (null? intervals)
        '()
        (let* ((sorted (sort intervals (lambda (a b) (< (car a) (car b)))))
               (merged (list (car sorted))))
          (for-each (lambda (current)
                      (let ((last (car (last merged))))
                        (if (>= (car current) (cdr last))
                            (set-cdr! last (cdr current))
                            (set-cdr! last (cdr last)))))
                    (cdr sorted))
          merged)))
  (merge-intervals-helper intervals))

(define (sort lst cmp)
  (if (null? lst)
      '()
      (let ((pivot (car lst))
            (less '())
            (greater '()))
        (for-each (lambda (x)
                    (if (cmp x pivot)
                        (set! less (cons x less))
                        (set! greater (cons x greater))))
                  (cdr lst))
        (append (sort less cmp) (cons pivot '()) (sort greater cmp)))))

(define (car lst) (if (null? lst) '() (first lst)))
(define (cdr lst) (if (null? lst) '() (rest lst)))
(define (last lst) (if (null? (cdr lst)) lst (last (cdr lst))))

(define (first lst) (if (null? lst) '() (car lst)))
(define (rest lst) (if (null? lst) '() (cdr lst)))