(define (findPaths m n maxMove startRow startColumn)
  (define dp (make-vector (+ m 2) (lambda () (make-vector (+ n 2) 0))))
  (define mod 1000000007)
  (vector-set! dp 0 (make-vector (+ n 2) 1))
  (define (loop moves)
    (if (zero? moves)
        0
        (begin
          (for ([i (in-range m)])
            (for ([j (in-range n)])
              (define count (vector-ref (vector-ref dp i) j))
              (vector-set! dp (+ 1 i) j (mod (+
                (mod (vector-ref (vector-ref dp (- (+ 1 i) 1)) j) mod)
                (mod (vector-ref (vector-ref dp (+ 1 i)) j) mod)
                (mod (vector-ref (vector-ref dp i (- (+ 1 j) 1)) mod) mod)
                (mod (vector-ref (vector-ref dp i (+ 1 j)) mod) mod)) mod)))
          (loop (sub1 moves)))))
  (loop maxMove)
  (define result 0)
  (for ([i (in-range (add1 m))])
    (set! result (mod (+ result (vector-ref (vector-ref dp i) startColumn)) mod)))
  (for ([j (in-range (add1 n))])
    (set! result (mod (+ result (vector-ref (vector-ref dp startRow j)) mod) mod)))
  result)