(define (outerTrees trees)
  (define (cross p1 p2 p3)
    (< (* (- (second p2) (second p1)) (- (first p3) (first p1)))
       (* (- (second p3) (second p1)) (- (first p2) (first p1)))))

  (define (hull points)
    (let loop ((points (sort points (lambda (a b) (or (not (= (first a) (first b)))
                                                     (< (first a) (first b))))))
               (lower '())
               (upper '()))
      (if (null? points)
          (append lower upper)
          (let ((p (car points)))
            (loop (cdr points)
                  (if (or (null? lower) (null? (cdr lower))
                          (not (cross (car (cdr lower)) (car lower) p)))
                      (cons p lower)
                      lower)
                  (if (or (null? upper) (null? (cdr upper))
                          (not (cross (car (cdr upper)) (car upper) p)))
                      (cons p upper)
                      upper)))))

  (define unique-trees (remove-duplicates trees))
  (define convex-hull (hull unique-trees))
  (remove-duplicates convex-hull))

(outerTrees (list (list 1 1) (list 2 2) (list 2 0) (list 2 4) (list 3 3) (list 4 2)))