(define (generateMatrix n)
  (define matrix (make-vector n (make-vector n 0)))
  (define (fill-spiral row-start row-end col-start col-end num)
    (when (and (< row-start row-end) (< col-start col-end))
      (for ([i (in-range col-start col-end)])
        (vector-set! (vector-ref matrix row-start) i num)
        (set! num (+ num 1)))
      (for ([i (in-range (+ row-start 1) row-end)])
        (vector-set! (vector-ref matrix i) (sub1 col-end) num)
        (set! num (+ num 1)))
      (when (< (+ row-start 1) row-end)
        (for ([i (in-range (sub1 col-end) col-start -1)])
          (vector-set! (vector-ref matrix (sub1 row-end)) i num)
          (set! num (+ num 1))))
      (when (< row-start (sub1 row-end))
        (for ([i (in-range (sub1 row-end) row-start -1)])
          (vector-set! (vector-ref matrix i) col-start num)
          (set! num (+ num 1))))
      (fill-spiral (add1 row-start) (sub1 row-end) (add1 col-start) (sub1 col-end) num)))
  (fill-spiral 0 n 0 n 1)
  (vector->list matrix))