(define (validSquare p1 p2)
  (define (dist-sq p1 p2)
    (+ (expt (- (car p1) (car p2)) 2)
       (expt (- (cadr p1) (cadr p2)) 2)))
  (define d1 (dist-sq p1 p2))
  (define d2 (dist-sq p1 (list (car p2) (cadr p1))))
  (define d3 (dist-sq (list (car p2) (cadr p1)) p2))
  (define d4 (dist-sq (list (car p1) (cadr p2)) p2))
  (define dists (list d1 d2 d3 d4))
  (define unique-dists (remove (lambda (x) (= x 0)) (remove-duplicates dists)))
  (and (= (length unique-dists) 2) (every? (lambda (x) (= x (car unique-dists))) (filter (lambda (x) (= (length (filter (lambda (y) (= y x)) dists)) 2)) unique-dists))))
)

(define (remove-duplicates lst)
  (foldl (lambda (x acc)
            (if (member x acc) acc (cons x acc)))
          '() lst))

(define (validSquare p1 p2)
  (let ((x1 (car p1)) (y1 (cadr p1))
        (x2 (car p2)) (y2 (cadr p2)))
    (and (not (and (= x1 x2) (= y1 y2)))
         (= (abs (- x1 x2)) (abs (- y1 y2))))))