(define (find-duplicate paths)
  (define file-map (make-hash))
  (for-each (lambda (path)
              (define split-path (string-split path " "))
              (define dir (car split-path))
              (for-each (lambda (file)
                          (define parts (string-split file "("))
                          (define filename (car parts))
                          (define content (cadr parts))
                          (define full-path (string-append dir "/" filename))
                          (hash-set! file-map content (cons full-path (hash-ref file-map content '())))))
                        (cdr split-path)))
            paths)
  (filter (lambda (files) (> (length files) 1))
          (hash-values file-map)))