(define (leastInterval tasks n)
  (let* ((task-count (make-hash))
         (max-count 0)
         (max-frequency 0))
    (for-each (lambda (task)
                (hash-set! task-count task (+ 1 (hash-ref task-count task 0))))
              tasks)
    (for-each (lambda (count)
                (when (> count max-frequency)
                  (set! max-frequency count)
                  (set! max-count 1))
                (when (= count max-frequency)
                  (set! max-count (+ max-count 1))))
              (hash-values task-count))
    (max (length tasks) (-(+ (* (- max-frequency 1) (+ max-count n)) 1) 1))))