(define (k-inverse-pairs n k)
  (define mod 1000000007)
  (define dp (make-vector (+ n 1) (make-vector (+ k 1) 0)))
  (vector-set! dp 0 0)
  (for ([i (in-range 1 (+ n 1))])
    (vector-set! dp i 1))
  (for ([i (in-range 1 (+ n 1))])
    (for ([j (in-range 1 (+ k 1))])
      (define sum 0)
      (for ([m (in-range (min i j) -1 -1)])
        (set! sum (mod (+ sum (vector-ref dp (- i 1 m))) mod)))
      (vector-set! dp i j sum)))
  (vector-ref dp n k))

(k-inverse-pairs n k)