(define (uniquePathsWithObstacles grid)
  (let* ((rows (length grid))
         (cols (length (car grid)))
         (dp (make-vector rows (make-vector cols 0))))
    (if (zero? (vector-ref (vector-ref grid 0) 0)) 
        (vector-set! (vector-ref dp 0) 0 1))
    (for ([i (in-range rows)])
      (for ([j (in-range cols)])
        (when (not (= (vector-ref (vector-ref grid i) j) 1))
          (cond
            ((= i 0) 
             (if (= j 0) 
                 (vector-set! (vector-ref dp i) j (vector-ref (vector-ref dp i) j))
                 (vector-set! (vector-ref dp i) j (+ (vector-ref (vector-ref dp i) (sub1 j)) (vector-ref (vector-ref dp i) j)))))
            ((= j 0) 
             (vector-set! (vector-ref dp i) j (vector-ref (vector-ref dp (sub1 i)) j))
            (else 
             (vector-set! (vector-ref dp i) j (+ (vector-ref (vector-ref dp (sub1 i)) j) (vector-ref (vector-ref dp i) (sub1 j)))))))))
    (vector-ref (vector-ref dp (sub1 rows)) (sub1 cols))))