(define (scheduleCourse courses)
  (define sorted-courses (sort courses (λ (a b) (> (second a) (second b)))))
  (define (can-schedule courses time)
    (if (null? courses)
        0
        (let* ((course (car courses))
               (duration (car course))
               (end-time (+ time (second course)))
               (next-courses (cdr courses)))
          (if (> end-time (third course))
              (can-schedule next-courses time)
              (max (can-schedule next-courses time)
                   (+ 1 (can-schedule next-courses end-time)))))))
  (can-schedule sorted-courses 0))