(define (construct-maximum-binary-tree nums)
  (if (null? nums)
      #f
      (let* ((max-index (index-of (apply max nums) nums))
             (node (make-node (list-ref nums max-index)))
             (left (construct-maximum-binary-tree (sublist nums 0 max-index)))
             (right (construct-maximum-binary-tree (sublist nums (+ max-index 1) (length nums)))))
        (set-left node left)
        (set-right node right)
        node)))

(define (make-node value)
  (let ((node (list 'node value '() '())))
    (define (set-left n left)
      (set-cdr! (cadr n) left))
    (define (set-right n right)
      (set-caddr! (cadr n) right))
    (define (index-of item lst)
      (define (helper lst index)
        (cond ((null? lst) -1)
              ((equal? (car lst) item) index)
              (else (helper (cdr lst) (+ index 1)))))
      (helper lst 0))
    (define (sublist lst start end)
      (if (>= start end)
          '()
          (cons (list-ref lst start) (sublist lst (+ start 1) end))))
    (list set-left set-right node)))

(define (set-cdr! pair value)
  (set-cdr! pair value))

(define (set-caddr! pair value)
  (set-cdr! (cdr pair) value))