(define (isPossible nums)
  (define freq (make-hash))
  (define tails (make-hash))
  (for-each (lambda (num)
              (hash-set! freq num (+ (hash-ref freq num 0) 1)))
            nums)
  (for-each (lambda (num)
              (when (> (hash-ref (hash-ref freq num) 0) 0)
                (if (> (hash-ref (hash-ref tails (- num 1)) 0) 0)
                    (begin
                      (hash-set! tails (- num 1) (- (hash-ref (hash-ref tails (- num 1)) 0) 1))
                      (hash-set! tails num (+ (hash-ref (hash-ref tails num) 0) 1)))
                    (if (and (> (hash-ref freq num 0) 0)
                             (> (hash-ref freq (+ num 1)) 0)
                             (> (hash-ref freq (+ num 2)) 0))
                        (begin
                          (hash-set! freq num (- (hash-ref freq num) 1))
                          (hash-set! freq (+ num 1) (- (hash-ref freq (+ num 1)) 1))
                          (hash-set! freq (+ num 2) (- (hash-ref freq (+ num 2)) 1))
                          (hash-set! tails (+ num 2) (+ (hash-ref (hash-ref tails (+ num 2)) 0) 1)))
                        (if (> (hash-ref freq num) 0)
                            #f)))))))
  (for-each (lambda (num)
              (when (> (hash-ref freq num 0) 0)
                (if (> (hash-ref (hash-ref tails num) 0) 0)
                    (begin
                      (hash-set! tails num (- (hash-ref (hash-ref tails num) 0) 1)))
                    (if (> (hash-ref freq num) 0)
                        #f))))) 
            (hash-keys freq))
  (for-each (lambda (num)
              (when (> (hash-ref freq num 0) 0)
                (if (> (hash-ref (hash-ref tails num) 0) 0)
                    (begin
                      (hash-set! tails num (- (hash-ref (hash-ref tails num) 0) 1)))
                    (if (> (hash-ref freq num) 0)
                        #f))))) 
            (sort (hash-keys freq) <)
  (not (for/or ((num (hash-keys freq)))
               (> (hash-ref freq num 0) 0))))