(define (maximumSwap num)
  (define digits (map (lambda (c) (- (char->integer c) (char->integer #\0))) (string->list (number->string num))))
  (define last (make-vector 10 -1))
  (for ([i (in-range (length digits))])
    (vector-set! last (list-ref digits i) i))
  (for ([i (in-range (length digits))])
    (for ([d (in-range 9 -1 -1)])
      (when (and (> d (list-ref digits i))
                 (vector-ref last d) 
                 (> (vector-ref last d) i))
        (let* ([j (vector-ref last d)]
               [swapped (vector-copy digits)])
          (vector-set! swapped i (list-ref digits j))
          (vector-set! swapped j (list-ref digits i))
          (return (string->number (list->string (map (lambda (x) (integer->char (+ x (char->integer #\0)))) swapped))))))))
  num)