(define KthLargest
  (lambda (k nums)
    (define (KthLargestConstructor)
      (define sorted-nums (sort nums <))
      (define (add val)
        (set! sorted-nums (sort (cons val sorted-nums) <))
        (if (<= (length sorted-nums) k)
            (last sorted-nums)
            (list-ref sorted-nums (- (length sorted-nums) k))))
      (define (getKthLargest)
        (if (<= (length sorted-nums) k)
            (last sorted-nums)
            (list-ref sorted-nums (- (length sorted-nums) k))))
      (values add getKthLargest))
    KthLargestConstructor))

(define (KthLargest__init (k nums))
  (define-values (add getKthLargest) (KthLargest k nums))
  (values add getKthLargest))

(define (KthLargest__add (this val))
  (define-values (add getKthLargest) this)
  (add val)
  (getKthLargest))