(define RangeModule
  (lambda ()
    (define intervals '())

    (define (addRange left right)
      (set! intervals (filter (lambda (interval)
                                 (or (< (second interval) left)
                                     (> (first interval) right)))
                               intervals))
      (set! intervals (cons (list left right) intervals))
      (set! intervals (sort intervals (lambda (a b) (< (first a) (first b)))))

      (define (merge-intervals lst)
        (if (null? lst)
            '()
            (let loop ((current (car lst))
                       (rest (cdr lst))
                       (merged '()))
              (if (null? rest)
                  (cons current merged)
                  (let ((next (car rest)))
                    (if (<= (second current) (first next))
                        (loop next (cdr rest) (cons current merged))
                        (loop (list (first current) (max (second current) (second next))) (cdr rest) merged)))))))
      (set! intervals (reverse (merge-intervals (reverse intervals)))))

    (define (queryRange left right)
      (let ((result #f))
        (for-each (lambda (interval)
                    (when (and (<= (first interval) left)
                               (>= (second interval) right))
                      (set! result #t)))
                  intervals)
        result))

    (define (removeRange left right)
      (set! intervals (filter (lambda (interval)
                                 (or (< (second interval) left)
                                     (> (first interval) right)))
                               intervals))
      (for-each (lambda (interval)
                  (when (and (<= (first interval) left)
                             (>= (second interval) right))
                    (set! intervals (cons (list (first interval) left) intervals))
                    (set! intervals (cons (list right (second interval)) intervals))))
                intervals)
      (set! intervals (sort intervals (lambda (a b) (< (first a) (first b))))))
    (values addRange queryRange removeRange)))