(define (countOfAtoms formula)
  (define (parse-formula formula)
    (define len (string-length formula))
    (define (helper start)
      (if (>= start len)
          (values '() start)
          (let* ((ch (string-ref formula start))
                 (next-start (if (char=? ch #\() 
                                 (let-values (((atoms next-start) (helper (+ start 1))))
                                   (values atoms next-start))
                                 (if (char=? ch #\))
                                     (values '() (+ start 1))
                                     (let loop ((i start) (atom "") (count 0))
                                       (cond
                                         ((char=? (string-ref formula i) #\() 
                                          (let-values (((atoms next-start) (helper (+ i 1))))
                                            (values atoms next-start)))
                                         ((char=? (string-ref formula i) #\)) 
                                          (if (zero? count) 
                                              (values (cons (cons atom 1) '()) (+ i 1))
                                              (values (cons (cons atom count) '()) (+ i 1))))
                                         (else
                                          (let* ((next-char (string-ref formula i))
                                                 (is-upper (char=? next-char #\A))
                                                 (is-lower (and (char=? next-char #\a) (not is-upper)))
                                                 (next-atom (if is-upper 
                                                                (string-append atom (string next-char))
                                                                (if is-lower 
                                                                    (string-append (string (char-upcase atom)) (string next-char)) 
                                                                    atom)))
                                                 (next-count (if (char-numeric? (string-ref formula (+ i 1)))
                                                                 (let loop ((j (+ i 1)) (num-str ""))
                                                                   (if (or (>= j len) (not (char-numeric? (string-ref formula j))))
                                                                       (values (string->number num-str) j)
                                                                       (loop (+ j 1) (string-append num-str (string (string-ref formula j))))))
                                                                 1)))
                                            (loop (+ i (if (char-numeric? (string-ref formula i)) 1 0)) next-atom (+ count next-count)))))))))
      (helper 0))

  (define (combine-atoms atoms)
    (foldl (lambda (atom acc)
              (let ((name (car atom))
                    (count (cdr atom)))
                (if (assoc name acc)
                    (begin
                      (set-cdr! (assoc name acc) (+ (cdr (assoc name acc)) count))
                      acc)
                    (cons (cons name count) acc))))
            '() atoms))

  (define (format-output atoms)
    (define (sort-by-key lst)
      (sort lst (lambda (a b) (string<? (car a) (car b)))))
    (define sorted-atoms (sort-by-key atoms))
    (apply string-append 
           (map (lambda (atom)
                  (let ((name (car atom))
                        (count (cdr atom)))
                    (if (= count 1)
                        name
                        (string-append name (number->string count)))))
                sorted-atoms)))

  (define atoms (parse-formula formula))
  (define combined-atoms (combine-atoms atoms))
  (format-output combined-atoms))