(define (floodFill image sr sc newColor)
  (define originalColor (vector-ref (vector-ref image sr) sc))
  (define (in-bounds? r c)
    (and (>= r 0) (< r (vector-length image)) (>= c 0) (< c (vector-length (vector-ref image r)))))
  (define (fill r c)
    (when (and (in-bounds? r c) (equal? (vector-ref (vector-ref image r) c) originalColor))
      (vector-set! (vector-ref image r) c newColor)
      (for-each (lambda (d)
                  (fill (+ r (car d)) (+ c (cadr d))))
                '((0 1) (1 0) (0 -1) (-1 0))))
  (fill sr sc)
  image)