(define (cherryPickup grid)
  (define n (vector-length grid))
  (define (dp x1 y1 x2)
    (define y2 (+ x1 y1 x2))
    (if (or (< x1 0) (< y1 0) (< x2 0) (< y2 0) (>= x1 n) (>= y1 n) (>= x2 n) (>= y2 n) 
            (not (= (vector-ref (vector-ref grid x1) y1) 1)) 
            (not (= (vector-ref (vector-ref grid x2) y2) 1)))
        -1
        (if (and (= x1 n - 1) (= y1 n - 1) (= x2 n - 1) (= y2 n - 1))
            (vector-ref (vector-ref grid x1) y1)
            (let ((cherries (+ (vector-ref (vector-ref grid x1) y1) 
                               (vector-ref (vector-ref grid x2) y2))))
              (if (or (zero? cherries) (= cherries -1))
                  -1
                  (+ cherries (max (dp (+ x1 1) y1 (+ x2 1))
                                   (dp (+ x1 1) y1 x2)
                                   (dp x1 (+ y1 1) (+ x2 1))
                                   (dp x1 (+ y1 1) x2))))))))
  (max 0 (dp 0 0 0)))