(define (next-greatest-letter letters target)
  (define (binary-search low high)
    (if (>= low high)
        (if (>= (string-ref letters low) target)
            (string-ref letters low)
            (string-ref letters 0))
        (let ((mid (quotient (+ low high) 2)))
          (if (>= (string-ref letters mid) target)
              (binary-search low mid)
              (binary-search (+ mid 1) high)))))
  (binary-search 0 (sub1 (length letters))))