(define (sortColors nums)
  (define red 0)
  (define white 1)
  (define blue 2)
  (define (swap i j)
    (let ((temp (list-ref nums i)))
      (set! (list-ref nums i) (list-ref nums j))
      (set! (list-ref nums j) temp)))
  (define (dutchNationalFlag)
    (define p0 0)
    (define p1 0)
    (define p2 (length nums))
    (while (< p1 p2)
      (cond
        [(= (list-ref nums p1) red)
         (swap p0 p1)
         (set! p0 (+ p0 1))
         (set! p1 (+ p1 1))]
        [(= (list-ref nums p1) white)
         (set! p1 (+ p1 1))]
        [(= (list-ref nums p1) blue)
         (set! p2 (- p2 1))
         (swap p1 p2)])))
  (dutchNationalFlag)
  nums)