(define (min-window s t)
  (define (count-char str)
    (define counts (make-hash))
    (for-each (lambda (c) (hash-set! counts c (+ (hash-ref counts c 0) 1))) (string->list str))
    counts)

  (define target (count-char t))
  (define current (make-hash))
  (define have 0)
  (define need (hash-count target))
  (define left 0)
  (define min-len +inf.0)
  (define result "")

  (for ((right (in-range (string-length s))))
    (let ((char (string-ref s right)))
      (when (hash-has-key? target char)
        (hash-set! current char (+ (hash-ref current char 0) 1))
        (when (<= (hash-ref current char 0) (hash-ref target char 0))
          (set! have (+ have 1)))))

    (while (and (>= have need) (<= left right))
      (when (< (- right left) min-len)
        (set! min-len (- right left))
        (set! result (substring s left (+ right 1))))
      (let ((lchar (string-ref s left)))
        (when (hash-has-key? target lchar)
          (hash-set! current lchar (- (hash-ref current lchar 0) 1))
          (when (< (hash-ref current lchar 0) (hash-ref target lchar 0))
            (set! have (- have 1)))))
      (set! left (+ left 1))))

  result)