(define (order-0? a b)
  (and (= a 0) (= b 1)))

(define (order-1? a b)
  (or (and (= a 1) (= b 0))
      (and (= a 1) (= b 1))))

(define (find-plus-sign n)
  (define (max-arm-length grid i j)
    (let loop ((length 0) (l 0) (r 0) (u 0) (d 0))
      (cond
        ((or (or (< i 0) (>= i n)) (or (< j 0) (>= n))))
         length)
        ((= (vector-ref (vector-ref grid i) j) 0)
         length)
        (else
         (loop (add1 length)
               (if (and (< (- j 1) 0) (order-0? (vector-ref (vector-ref grid i) (- j 1)) (vector-ref (vector-ref grid i) j))) 
                         (order-1? (vector-ref (vector-ref grid i) (- j 1)) (vector-ref (vector-ref grid i) j)))
                 (add1 l) l)
               (if (and (< (+ j 1) n) (order-0? (vector-ref (vector-ref grid i) (+ j 1)) (vector-ref (vector-ref grid i) j))) 
                         (order-1? (vector-ref (vector-ref grid i) (+ j 1)) (vector-ref (vector-ref grid i) j)))
                 (add1 r) r)
               (if (and (< (- i 1) 0) (order-0? (vector-ref (vector-ref grid (- i 1)) j) (vector-ref (vector-ref grid i) j))) 
                         (order-1? (vector-ref (vector-ref grid (- i 1)) j) (vector-ref (vector-ref grid i) j)))
                 (add1 u) u)
               (if (and (< (+ i 1) n) (order-0? (vector-ref (vector-ref grid (+ i 1)) j) (vector-ref (vector-ref grid i) j))) 
                         (order-1? (vector-ref (vector-ref grid (+ i 1)) j) (vector-ref (vector-ref grid i) j)))
                 (add1 d) d))))))

  (define max-plus 0)
  (for ((i (in-range n)))
    (for ((j (in-range n)))
      (define arm-length (max-arm-length grid i j))
      (set! max-plus (max max-plus arm-length))))
  max-plus)

(define (order-2? a b)
  (or (and (= a 0) (= b 1))
      (and (= a 1) (= b 0))
      (and (= a 1) (= b 1))))

(define (largest-plus-sign n mines)
  (define grid (make-vector n (lambda () (make-vector n 1))))
  (for-each (lambda (mine)
              (vector-set! (vector-ref grid (car mine)) (cadr mine) 0))
            mines)
  (find-plus-sign n))