(define (maxChunksToSorted arr)
  (define n (length arr))
  (define (sorted?) (equal? arr (sort arr <)))
  (define (count-chunks arr)
    (define cnt 0)
    (define current-max 0)
    (for ([i (in-range n)])
      (set! current-max (max current-max (list-ref arr i)))
      (when (= current-max i)
        (set! cnt (+ cnt 1))))
    cnt)
  (count-chunks arr))