(define (can-transform start end)
  (define (normalize s)
    (string-append (apply string (filter (lambda (c) (char? c)) s))
                   (apply string (filter (lambda (c) (char? c)) (reverse s)))))
  (define (check s1 s2)
    (and (equal? (normalize s1) (normalize s2))
         (equal? (count (lambda (c) (equal? c #\L)) s1)
                 (count (lambda (c) (equal? c #\L)) s2)
                 (count (lambda (c) (equal? c #\R)) s1)
                 (count (lambda (c) (equal? c #\R)) s2)))
  (check start end))