(define (moves-to-chessboard board)
  (define n (length board))
  (define (count-ones lst)
    (length (filter (lambda (x) (= x 1)) lst)))
  (define row-ones (count-ones (car board)))
  (define col-ones (count-ones (map car board)))
  (define (valid-count count)
    (or (= count n) (= count (+ n (- 1 count)))))
  (if (and (valid-count row-ones) (valid-count col-ones))
      (let loop ((i 0) (j 0) (row-sum 0) (col-sum 0))
        (cond
          ((= i n) (if (= row-sum (quotient n 2)) (if (= col-sum (quotient n 2)) 0 1) 1))
          (else
           (set! row-sum (+ row-sum (if (= (list-ref (car board) i) 1) 1 0)))
           (set! col-sum (+ col-sum (if (= (list-ref (map car board) j) 1) 1 0)))
           (if (or (and (even? i) (not (= (list-ref (car board) i) (if (even? row-ones) 1 0))))
                   (and (odd? i) (not (= (list-ref (car board) i) (if (even? row-ones) 0 1))))
                   (and (even? j) (not (= (list-ref (map car board) j) (if (even? col-ones) 1 0))))
                   (and (odd? j) (not (= (list-ref (map car board) j) (if (even? col-ones) 0 1)))))
               (loop (add1 i) j row-sum col-sum)
               (loop i (add1 j) row-sum col-sum)))))
      -1))