(define (min-swap A B)
  (define n (length A))
  (define (helper prev i)
    (if (>= i n)
        (values 0 0)
        (let-values ([(no-swap no-swap-1) (helper (list-ref A i) (+ i 1))])
          (let-values ([(swap swap-1) (helper (list-ref B i) (+ i 1))])
            (define swap (add1 swap))
            (define no-swap (add1 no-swap))
            (if (or (>= (list-ref A i) prev) (>= (list-ref B i) prev))
                (values no-swap swap)
                (values (add1 swap-1) (add1 no-swap-1)))))))
  (let-values ([(no-swap swap) (helper (sub1 (list-ref A 0)) 0)])
    (min no-swap swap)))