(define (unique-char-count s)
  (define n (string-length s))
  (define (count-unique-starting-at i)
    (define seen (make-hash))
    (define count 0)
    (for/list ((j (in-range i n)))
      (define char (string-ref s j))
      (when (not (hash-has? seen char))
        (hash-set! seen char #t)
        (set! count (+ count 1)))
      count))
  (define total 0)
  (for ((i (in-range n)))
    (set! total (+ total (count-unique-starting-at i))))
  total)

(define (count-unique-characters s)
  (unique-char-count s))