(define (maskPII S)
  (define (mask-email email)
    (define parts (string-split email "@"))
    (define name (substring (first parts) 0 1))
    (define masked-name (string-append name "***" (substring (first parts) (- (string-length (first parts)) 1))))
    (string-append masked-name "@" (second parts)))

  (define (mask-phone phone)
    (define digits (filter (lambda (c) (char-numeric? c)) (string->list phone)))
    (define num-count (length digits))
    (define masked-prefix (if (> num-count 10) 
                              (string-append "***-***-") 
                              "***-"))
    (define masked-suffix (if (> num-count 10) 
                              (substring (list->string digits) (- num-count 4) num-count)
                              (substring (list->string digits) (- num-count 7) num-count)))
    (string-append "+-" (substring (list->string digits) (- num-count 10) (- num-count 7)) "-" masked-prefix masked-suffix))

  (if (string-contains? S "@")
      (mask-email S)
      (mask-phone S)))