(define (longest-mountain arr)
  (define n (length arr))
  (define longest 0)
  (define (is-mountain? start)
    (define left (sublist arr 0 start))
    (define right (sublist arr start))
    (and (not (null? left))
         (not (null? right))
         (for/or ([i (in-range (sub1 (length left)))])
           (> (list-ref left i) (list-ref left (add1 i))))
         (for/or ([i (in-range (sub1 (length right)))])
           (< (list-ref right i) (list-ref right (add1 i)))))

  (for ([i (in-range 1 (sub1 n))])
    (when (and (> (list-ref arr i) (list-ref arr (sub1 i)))
               (> (list-ref arr (add1 i)) (list-ref arr i)))
      (define start i)
      (while (and (> start 0) (> (list-ref arr start) (list-ref arr (sub1 start))))
        (set! start (sub1 start)))
      (define end i)
      (while (and (< end (sub1 n)) (< (list-ref arr end) (list-ref arr (add1 end))))
        (set! end (add1 end)))
      (set! longest (max longest (- end start 1))))
  longest)