(define (min-cost-to-hire-workers quality wage K)
  (define n (length quality))
  (define workers (map vector quality wage))
  (define (compare a b)
    (let* ((q1 (vector-ref a 0))
           (w1 (vector-ref a 1))
           (q2 (vector-ref b 0))
           (w2 (vector-ref b 1)))
      (< (/ w1 q1) (/ w2 q2))))
  (define sorted-workers (sort workers compare))
  (define (calculate-cost selected)
    (let* ((total-quality (apply + (map vector-ref selected 0)))
           (total-wage (apply + (map (lambda (x) (* (/ (vector-ref x 1) (vector-ref x 0)) total-quality)) selected))))
           (cost (/ total-wage total-quality)))
      cost))
  (define (min-cost k)
    (let loop ((i 0) (selected '()))
      (if (= i n)
          (if (= (length selected) k)
              (calculate-cost selected)
              +inf.0)
          (let ((with-current (loop (+ i 1) (cons (list-ref sorted-workers i) selected)))
                (without-current (loop (+ i 1) selected)))
            (min with-current without-current)))))
  (min-cost K))