#lang racket

(define (shortest-subarray A K)
  (define n (length A))
  (define prefix-sum (make-vector (+ n 1) 0))
  (for ([i (in-range n)])
    (vector-set! prefix-sum (+ i 1) (+ (vector-ref prefix-sum i) (list-ref A i))))
  (define min-length +inf.0)
  (define deque (make-vector n))
  (define front 0)
  (define back 0)
  (for ([i (in-range (+ n 1))])
    (when (and (> i 0) (>= (vector-ref prefix-sum i) K))
      (let loop ([j front])
        (when (< j back)
          (define sum (- (vector-ref prefix-sum i) (vector-ref prefix-sum (vector-ref deque j))))
          (when (>= sum K)
            (set! min-length (min min-length (- i (vector-ref deque j)))
            (loop (+ j 1)))))
      (while (and (> back front) (>= (vector-ref prefix-sum i) (vector-ref prefix-sum (vector-ref deque (- back 1))))) 
        (set! back (- back 1)))
      (vector-set! deque back i)
      (set! back (+ back 1))))
  (if (= min-length +inf.0) -1 min-length))

(define (shortestSubarray A K)
  (shortest-subarray A K))