(define (len-of-longest-fib-subseq A)
  (define n (length A))
  (define index-map (make-hash))
  (for ([i (in-range n)])
    (hash-set! index-map (list-ref A i) i))
  (define dp (make-vector n (make-vector n 0)))
  (define max-len 0)
  (for ([i (in-range n)])
    (for ([j (in-range i)])
      (define k (+ (list-ref A i) (list-ref A j)))
      (when (hash-has-key? index-map k)
        (define k-index (hash-ref index-map k))
        (vector-set! dp i k-index (max (vector-ref dp i k-index) (+ (vector-ref dp j k-index) 1)))
        (set! max-len (max max-len (vector-ref dp i k-index))))))
  (if (> max-len 2) max-len 0))

(len-of-longest-fib-subseq (vector 1 2 3 4 5 6 7 8))