(define (decode-at-index s k)
  (define (get-length s)
    (foldl (lambda (c acc)
              (if (char-numeric? c)
                  (* acc (string->number (string c)))
                  (+ acc 1)))
            0
            s))

  (define (find-char s k)
    (let loop ((i (sub1 (string-length s)))
               (length (get-length s)))
      (if (zero? i)
          (if (= k 0) (string-ref s 0) #f)
          (let ((c (string-ref s i)))
            (if (char-numeric? c)
                (let ((num (string->number (string c))))
                  (set! length (/ length num))
                  (if (< k length)
                      (loop (sub1 i) length)
                      (set! k (modulo k length))))
                (if (< k (sub1 length))
                    (string-ref s i)
                    (loop (sub1 i) length)))))))

  (find-char s (sub1 k)))