(define (spiralMatrixIII R C r0 c0)
  (define directions '((0 1) (1 0) (0 -1) (-1 0)))
  (define result '())
  (define (in-bounds? r c)
    (and (>= r 0) (< r R) (>= c 0) (< c C)))
  (define (next-spiral r c d steps)
    (when (in-bounds? r c)
      (set! result (cons (list r c) result)))
    (for ((i (in-range steps)))
      (when (in-bounds? r c)
        (set! result (cons (list r c) result)))
      (set! r (+ r (car (list-ref directions d))))
      (set! c (+ c (cadr (list-ref directions d)))))
    (if (= d 3) (values r c (+ steps 2)) (values r c steps)))
  (define r r0)
  (define c c0)
  (define steps 1)
  (while (< (length result) (* R C))
    (define-values (r c steps) (next-spiral r c (modulo steps 4) steps)))
  (reverse result))

(spiralMatrixIII 1 4 0 0)