(define (total-fruits fruits)
  (define (helper start end fruit-count)
    (if (>= end (length fruits))
        (if (<= (length fruit-count) 2)
            (sub1 end)
            (sub1 (or (hash-ref fruit-count (car (hash-keys fruit-count))) 0))))
    (define fruit (vector-ref fruits end))
    (hash-set! fruit-count fruit (+ 1 (hash-ref fruit-count fruit 0)))
    (if (<= (length fruit-count) 2)
        (helper start (add1 end) fruit-count)
        (begin
          (while (> (length fruit-count) 2)
            (define start-fruit (vector-ref fruits start))
            (hash-set! fruit-count start-fruit (- (hash-ref fruit-count start-fruit 0) 1))
            (if (= (hash-ref fruit-count start-fruit 0) 0)
                (hash-remove! fruit-count start-fruit))
            (set! start (add1 start)))
          (helper start end fruit-count))))
  (let loop ([end 0] [fruit-count (make-hash)])
    (helper 0 end fruit-count)))

(define (max-fruits fruits)
  (total-fruits fruits))