(define (top-voted-candidate persons times)
  (define n (length persons))
  (define votes (make-vector n 0))
  (define winner 0)
  (define max-votes 0)
  (define last-winner 0)

  (for ((i (in-range n)))
    (vector-set! votes (vector-ref persons i) (+ 1 (vector-ref votes (vector-ref persons i))))
    (when (> (vector-ref votes (vector-ref persons i)) max-votes)
      (set! max-votes (vector-ref votes (vector-ref persons i)))
      (set! winner (vector-ref persons i))
      (set! last-winner i))
    (when (= (vector-ref votes (vector-ref persons i)) max-votes)
      (set! last-winner i)))

  (define (find-winner-at-time t)
    (for ((i (in-range n)))
      (when (<= (vector-ref times i) t)
        (if (= (vector-ref persons i) winner)
            (set! last-winner i))))
    (vector-ref persons last-winner))

  (lambda (t)
    (find-winner-at-time t)))