(define (reorder-log-files logs)
  (define (log-key log)
    (let* ((parts (string-split log))
           (id (car parts))
           (content (string-append (apply string-append (cdr parts)) " ")))
      (if (char? (string-ref (string-trim content) 0))
          (list 'digit id)
          (list 'letter content id))))

  (define sorted-logs (sort (map log-key logs) 
                            (lambda (a b)
                              (cond ((equal? (car a) 'letter) 
                                     (if (equal? (car b) 'letter) 
                                         (let ((content-a (cadr a))
                                               (content-b (cadr b)))
                                           (or (string<? content-a content-b)
                                               (and (string=? content-a content-b)
                                                    (string<? (caddr a) (caddr b)))))
                                         #t))
                                    ((equal? (car a) 'digit) #f)))))

  (map (lambda (log) (if (equal? (car log) 'digit)
                        (cadr log)
                        (string-append (caddr log) " " (cadr log))))
       sorted-logs))

(reorder-log-files '("dig1 8 1 5 1", "let1 art can", "dig2 3 6", "let2 own kit dig", "let3 art zero"))