(define (generateTrees n)
  (define (generate range)
    (if (null? range)
        '(())
        (apply append
               (map (lambda (i)
                      (map (lambda (left)
                             (map (lambda (right)
                                    (list i left right))
                                  (generate (append (filter (lambda (x) (< x i)) range)
                                                    (filter (lambda (x) (> x i)) range)))))
                           (generate (filter (lambda (x) (< x i)) range))))
                    range))))
  (if (= n 0)
      '()
      (map (lambda (x) (list (car x) (cadr x) (caddr x)))
           (generate (build-list n (lambda (x) (+ x 1)))))))

(define (build-list n f)
  (if (= n 0)
      '()
      (cons (f (- n 1)) (build-list (- n 1) f))))