(define (is-equal-rational(S T))
  (define (parse-rational str)
    (define parts (string-split str #\.))
    (define integer-part (if (null? parts) "0" (car parts)))
    (define fractional-part (if (null? (cdr parts)) "" (cadr parts)))
    (define (expand-fractional frac)
      (define len (string-length frac))
      (if (string-contains? frac "(")
          (let* ((pos (string-index frac #\())))
            (define non-repeating (substring frac 0 pos))
            (define repeating (substring frac (+ pos 1) (- (string-length frac) 1)))
            (define expanded (string-append non-repeating (make-string (expt 10 len) #\0)))
            (define repeat-portion (make-string (string-length repeating) #\0))
            (values (string->number integer-part) (string->number expanded) (string->number repeat-portion)))
          (values (string->number integer-part) (string->number (string-append fractional-part "0")) 0))))
    (define-values (int frac repeat) (expand-fractional (or fractional-part "")))
    (if (= repeat 0)
        (+ int (/ frac (expt 10 (string-length fractional-part))))
        (+ int (/ (string->number (string-append (number->string frac) repeat)) (expt 10 (string-length fractional-part))))))
  (= (parse-rational S) (parse-rational T)))

(define (equal-rational-numbers S T)
  (is-equal-rational S T))