(define (min-cost-tickets days costs)
  (define n (length days))
  (define dp (make-vector (+ 1 (car (last days))) +inf.0))
  (vector-set! dp 0 0)
  (define (get-cost day)
    (for/fold ([min-cost +inf.0]) ([i 0] (in-range n))
      (if (>= (vector-ref dp day) (vector-ref dp (vector-ref days i)))
          (begin
            (set! min-cost (min min-cost (+ (vector-ref costs i) (vector-ref dp (vector-ref days i)))))
            (set! i (+ i 1)))
          min-cost)))
  (for ([i (in-range (length dp))])
    (when (and (not (zero? (vector-ref dp i))) (< i (car (last days))))
      (let ([cost (get-cost i)])
        (vector-set! dp (+ i 1) (min (vector-ref dp (+ i 1)) cost)))))
  (vector-ref dp (car (last days))))