(define (intervalIntersection A B)
  (define (intersect a b)
    (if (and (not (null? a)) (not (null? b)))
        (let* ((start-a (car (car a)))
               (end-a (cdr (car a)))
               (start-b (car (car b)))
               (end-b (cdr (car b)))
               (start-int (max start-a start-b))
               (end-int (min end-a end-b)))
          (if (<= start-int end-int)
              (cons (list start-int end-int)
                    (intersect (if (< end-a end-b) (cdr a) a)
                               (if (< end-a end-b) b (cdr b))))
              (intersect (if (< end-a end-b) (cdr a) a)
                         (if (< end-a end-b) b (cdr b)))))
        '()))
  (intersect A B))