(define (vertical-order-traversal root)
  (define (dfs node x y)
    (when node
      (set! nodes (cons (list x y (car node)) nodes))
      (dfs (cdr node) (sub1 x) (add1 y))
      (dfs (cadr node) (add1 x) (add1 y))))

  (define nodes '())
  (dfs root 0 0)
  (define sorted-nodes (sort nodes (lambda (a b)
                                     (if (= (car a) (car b))
                                         (if (= (cadr a) (cadr b))
                                             (< (caddr a) (caddr b))
                                             (< (cadr a) (cadr b))
                                         (< (car a) (car b))))))
  (define result '())
  (define grouped '())
  (for-each (lambda (node)
              (define x (car node))
              (when (null? (assoc x grouped))
                (set! grouped (cons (list x) grouped)))
              (set-cdr! (assoc x grouped) (cons (caddr node) (cdr (assoc x grouped)))))
            sorted-nodes)
  (for-each (lambda (g) (set! result (cons (cdr g) result))) grouped)
  (reverse result))