(define (subarrays-with-k-different-integers nums k)
  (define (at-most-k k)
    (define count 0)
    (define freq (hash))
    (define left 0)
    (for ([right (in-range (length nums))])
      (hash-update! freq (list-ref nums right) add1)
      (while (> (hash-count freq) k)
        (hash-update! freq (list-ref nums left) sub1)
        (when (= (hash-ref freq (list-ref nums left) 0) 0)
          (hash-remove! freq (list-ref nums left)))
        (set! left (+ left 1)))
      (set! count (+ count (- right left 1))))
    count)

  (+ (at-most-k k) (at-most-k (- k 1)))
)