(define (numSquarefulPerms A)
  (define (is-squareful? x y)
    (let ([sum (+ x y)])
      (= (exact->inexact (sqrt sum)) (inexact->exact (sqrt sum))))
    )

  (define (backtrack path used)
    (if (= (length path) (length A))
      (begin
        (set! count (+ count 1))
        )
      (for ([i (in-range (length A))])
        (unless (vector-ref used i)
          (when (or (null? path) (is-squareful? (vector-ref A (car path)) (vector-ref A i)))
            (vector-set! used i #t)
            (set! path (cons (vector-ref A i) path))
            (backtrack path used)
            (set! path (cdr path))
            (vector-set! used i #f)
            )
          )
        )
      )
    )

  (define count 0)
  (define used (make-vector (length A) #f))
  (set! A (vector->list (sort (list->vector A) <)))
  (backtrack '() used)
  count)

(define (numSquarefulArrays A)
  (numSquarefulPerms A))