(define (checkWin moves)
  (define (in-line? a b c)
    (and (= (car a) (car b)) (= (car b) (car c))))
  (define (in-column? a b c)
    (and (= (cdr a) (cdr b)) (= (cdr b) (cdr c))))
  (define (in-diagonal? a b c)
    (and (= (abs (- (car a) (car b))) (abs (- (cdr a) (cdr b)))) 
         (not (in-line? a b c))
         (not (in-column? a b c))))
  (define (winner? m)
    (or (in-line? (list-ref m 0) (list-ref m 1) (list-ref m 2))
        (in-column? (list-ref m 0) (list-ref m 1) (list-ref m 2))
        (in-diagonal? (list-ref m 0) (list-ref m 1) (list-ref m 2))))
  (define (check-all-players moves)
    (define player1 (filter (lambda (move) (= (car move) 1)) moves))
    (define player2 (filter (lambda (move) (= (car move) 2)) moves))
    (or (winner? player1) (winner? player2)))
  (check-all-players moves))

(checkWin '((1 0) (2 0) (1 1) (2 1) (1 2)))