(define (num-similar-groups strs)
  (define (are-similar s1 s2)
    (let loop ((i 0) (diff 0))
      (cond
        ((= i (string-length s1)) (= diff 2))
        ((char=? (string-ref s1 i) (string-ref s2 i)) (loop (+ i 1) diff))
        (else (loop (+ i 1) (+ diff 1))))))

  (define (union-find)
    (define parent (make-vector (length strs)))
    (define (find x)
      (if (not (= (vector-ref parent x) x))
          (let ([root (find (vector-ref parent x))])
            (vector-set! parent x root)
            root)
          x))
    (define (union x y)
      (define rootX (find x))
      (define rootY (find y))
      (if (not (= rootX rootY))
          (vector-set! parent rootX rootY)))
    (define (init)
      (do ((i 0 (+ i 1)))
          ((= i (length strs)))
        (vector-set! parent i i)))
    (init)
    (for ([i (in-range (length strs))])
      (for ([j (in-range (+ i 1) (length strs))])
        (when (are-similar (list-ref strs i) (list-ref strs j))
          (union i j))))
    (define roots (make-hash))
    (do ((i 0 (+ i 1)))
        ((= i (length strs)))
      (define root (find i))
      (hash-set! roots root 1))
    (hash-count roots))

  (union-find))