(define (countDigitOne n)
  (define (count-ones x)
    (if (= x 0)
        0
        (let* ((factor 1)
               (count 0)
               (current 0)
               (lower 0)
               (higher 0))
          (while (> x 0)
            (set! current (modulo x 10))
            (set! x (quotient x 10))
            (set! higher x)
            (set! lower (+ lower (* current factor)))
            (if (= current 0)
                (set! count (+ count (* higher factor)))
                (if (= current 1)
                    (set! count (+ count (+ higher factor lower)))
                    (set! count (+ count (* (+ higher 1) factor)))))
            (set! factor (* factor 10))))
          count)))
  (count-ones n))