(define (canCompletePlan A)
  (define (helper A k)
    (define (dp i rest)
      (if (= i (length A))
          (if (= rest 0) #t #f)
          (or (dp (+ i 1) rest)
              (and (>= rest (list-ref A i))
                   (dp (+ i 1) (- rest (list-ref A i)))))))
    (dp 0 k))
  (define (sum lst)
    (foldl + 0 lst))
  (define (max lst)
    (foldl max 0 lst))
  (define total (sum A))
  (define maximum (max A))
  (if (> total (* 2 maximum)) #f #t))

(define (trainingPlan II)
  (let ((n (read)))
    (let ((A (for/list ((i n)) (read))))
      (canCompletePlan A))))