(define (openLock deadends target)
  (define (bfs)
    (define visited (make-hash))
    (define queue (list '("0000" 0)))
    (hash-set! visited "0000" #t)

    (define (add-next-positions position)
      (for ([i (in-range 4)])
        (define digit (string-ref position i))
        (for ([d (list -1 1)])
          (define new-digit (modulo (+ (char->integer digit) d 10) 10))
          (define new-position (string-append (substring position 0 i) 
                                              (string (integer->char new-digit)) 
                                              (substring position (+ i 1))))
          (unless (hash-ref visited new-position #f)
            (hash-set! visited new-position #t)
            (set! queue (append queue (list (list new-position (+ 1 (cadr (car queue)))))))))))

    (while (not (null? queue))
      (define current (car queue))
      (set! queue (cdr queue))
      (define position (car current))
      (define steps (cadr current))
      (when (not (member position deadends))
        (when (equal? position target)
          (return steps)))
      (add-next-positions position)))

  (bfs))