(define (canConstruct ransomNote magazine)
  (let ([magazine-map (make-hash)])
    (for-each (lambda (char) (hash-set! magazine-map char (+ (hash-ref magazine-map char 0) 1))) magazine)
    (for-each (lambda (char)
                (let ([count (hash-ref magazine-map char 0)])
                  (if (zero? count)
                      (error "Not enough characters")
                      (hash-set! magazine-map char (- count 1)))))
              ransomNote)
    #t))