(define (findMaxLength nums)
  (define (helper lst acc)
    (if (null? lst)
        (if (null? acc) 0 (max (length acc) (helper (cdr lst) (if (= (car lst) 0) (cdr acc) (cons (car lst) acc)))))
        (let ([current (car lst)])
          (if (= current 0)
              (helper (cdr lst) (if (null? acc) (list 1) (cons (add1 (car acc)) (cdr acc))))
              (helper (cdr lst) (if (null? acc) (list -1) (cons (add1 (car acc)) (cdr acc))))))))
  (let loop ([s 0] [map (make-hash)] [max-len 0])
    (for ([num nums])
      (set! s (+ s (if (= num 0) -1 1)))
      (if (hash-has-key? map s)
          (set! max-len (max max-len (- (hash-ref map s) (length nums)))) 
          (hash-set! map s (length nums))))
    max-len))

(findMaxLength '(0 1 0 1 0 1))