(define (decrypt nums)
  (define (char->num c) (- (char->integer c) (char->integer #\a)))
  (define (num->char n) (integer->char (+ n (char->integer #\a))))
  (define (decrypt-helper lst)
    (if (null? lst)
        '()
        (let* ((n (car lst))
               (first (modulo n 10))
               (second (quotient n 10)))
          (cons (num->char first) (decrypt-helper (cdr lst))))))
  (decrypt-helper (map char->num (string->list nums))))