(define (relativeSortArray arr1 arr2)
  (define counts (make-hash))
  (for-each (lambda (x) (hash-set! counts x (+ 1 (hash-ref counts x 0)))) arr1)
  (define result '())
  (for-each (lambda (x)
              (let ([count (hash-ref counts x 0)])
                (set! result (append result (make-list count x)))))
            arr2)
  (for-each (lambda (x)
              (when (not (hash-has? counts x))
                (set! result (append result (list x)))))
            (sort (hash-keys counts) <))
  result)

(relativeSortArray '(2 1 2 5 3 1) '(2 1 4))