(define (lenLongestFibSubseq A)
  (let* ((n (length A))
         (index (make-hash))
         (dp (make-vector n #f)))
    (for ([i (in-range n)])
      (hash-set! index (vector-ref A i) i))
    (for ([i (in-range n)])
      (for ([j (in-range i)])
        (let* ((x (vector-ref A j))
               (y (vector-ref A i))
               (z (+ x y)))
          (when (hash-has? index z)
            (define k (hash-ref index z))
            (vector-set! dp k (max (if (vector-ref dp k) (vector-ref dp k) 2)
                                    (+ (if (vector-ref dp j) (vector-ref dp j) 2) 1)))))))
    (apply max (vector->list dp)))

(define (lengthOfLIS A)
  (lenLongestFibSubseq A))