(define (longest-consecutive nums)
  (let ([num-set (set nums)])
    (define (longest-seq num)
      (let loop ([current num] [length 0])
        (if (set-member? num-set current)
            (loop (+ current 1) (+ length 1))
            length)))
    (foldl (lambda (num acc)
              (max acc (longest-seq num)))
            0 (set->list num-set))))