(define (find-target root k)
  (define (inorder-traversal node)
    (if (null? node)
        '()
        (append (inorder-traversal (node-left node))
                (list (node-value node))
                (inorder-traversal (node-right node)))))

  (define (two-sum nums target)
    (define seen (make-hash))
    (for-each (lambda (num)
                (let ((complement (- target num)))
                  (when (hash-has-key? seen complement)
                    (set! found #t)))
                (hash-set! seen num))
              nums))

  (define nums (inorder-traversal root))
  (define found #f)
  (two-sum nums k)
  found)