(define (minimum-total triangle)
  (define n (length triangle))
  (for ([i (in-range (- n 2) -1 -1)])
    (for ([j (in-range (add1 i))])
      (set! (list-ref triangle i j) 
            (+ (list-ref (list-ref triangle (+ i 1)) j)
               (min (list-ref (list-ref triangle (+ i 1)) j)
                    (list-ref (list-ref triangle (+ i 1)) (add1 j))))))
  (car (list-ref triangle 0)))