(define (findDuplicate paths)
  (define file-map (make-hash))
  (for ([path paths])
    (define parts (string-split path))
    (define dir (car parts))
    (for ([file (cdr parts)])
      (define file-name (last (string-split file " ")))
      (define full-path (string-append dir "/" file-name))
      (define content (string-join (cdr (string-split file " ")) " "))
      (define existing (hash-ref file-map content '()))
      (hash-set! file-map content (cons full-path existing))))
  (define result (filter (lambda (x) (> (length x) 1)) (hash-values file-map)))
  (map (lambda (x) (list-ref x 0)) result))