(define (is-match s p)
  (let ((m (string-length s))
        (n (string-length p)))
    (letrec ((dp (make-vector (add1 m) (make-vector (add1 n) #f))))
      (vector-set! (vector-ref dp 0) 0 #t)
      (for ([j (in-range 1 (add1 n))])
        (when (and (> j 1) (char=? (string-ref p (sub1 j)) #\*))
          (vector-set! (vector-ref dp 0) j (vector-ref (vector-ref dp 0) (- j 2)))))
      (for ([i (in-range 1 (add1 m))])
        (for ([j (in-range 1 (add1 n))])
          (if (char=? (string-ref p (sub1 j)) #\*)
              (vector-set! (vector-ref dp i) j
                           (or (vector-ref (vector-ref dp i) (- j 2))
                               (and (vector-ref (vector-ref dp (sub1 i)) j)
                                    (or (char=? (string-ref p (- j 2)) #\.)
                                        (char=? (string-ref p (- j 2)) (string-ref s (sub1 i)))))))
              (vector-set! (vector-ref dp i) j
                           (and (vector-ref (vector-ref dp (sub1 i)) (sub1 j))
                                    (or (char=? (string-ref p (sub1 j)) #\.)
                                        (char=? (string-ref p (sub1 j)) (string-ref s (sub1 i)))))))))
      (vector-ref (vector-ref dp m) n))))