(define (smallest-equivalent-string s1 s2 baseStr)
  (let ((parent (make-vector 26 0)))
    (for ([i 26])
      (vector-set! parent i i))
    (define (find u)
      (if (= (vector-ref parent u) u)
          u
          (let ((pu (find (vector-ref parent u))))
            (vector-set! parent u pu)
            pu)))
    (for ([a s1] [b s2])
      (let ((u (- (char->integer a) 97))
            (v (- (char->integer b) 97)))
        (let ((pu (find u))
              (pv (find v)))
          (if (< pu pv)
              (vector-set! parent pv pu)
              (vector-set! parent pu pv)))))
    (list->string
     (for/list ([c baseStr])
       (let ((u (- (char->integer c) 97)))
         (integer->char (+ (find u) 97)))))))