(define (add-negabinary arr1 arr2)
  (let loop ((i (sub1 (length arr1)))
             (j (sub1 (length arr2)))
             (carry 0)
             (result '()))
    (if (and (>= i 0) (>= j 0))
        (let* ((sum (+ (list-ref arr1 i) (list-ref arr2 j) carry))
          (loop (sub1 i) (sub1 j) (quotient (- sum) 2) (cons (modulo sum 2) result)))
        (if (>= i 0)
            (let* ((sum (+ (list-ref arr1 i) carry)))
              (loop (sub1 i) j (quotient (- sum) 2) (cons (modulo sum 2) result)))
            (if (>= j 0)
                (let* ((sum (+ (list-ref arr2 j) carry)))
                  (loop i (sub1 j) (quotient (- sum) 2) (cons (modulo sum 2) result)))
                (if (not (zero? carry))
                    (loop i j (quotient (- carry) 2) (cons (modulo carry 2) result))
                    (let ((trimmed (dropf result (lambda (x) (zero? x)))))
                      (if (null? trimmed) '(0) trimmed)))))))))