(define (shortest-common-supersequence str1 str2)
  (let* ((m (string-length str1))
         (n (string-length str2))
         (dp (make-vector (add1 m) (make-vector (add1 n) ""))))
    (for ([i (in-range 1 (add1 m))])
      (vector-set! (vector-ref dp i) 0 (string-append (vector-ref dp (sub1 i) 0) (substring str1 (sub1 i) i))))
    (for ([j (in-range 1 (add1 n))])
      (vector-set! (vector-ref dp 0) j (string-append (vector-ref dp 0 (sub1 j)) (substring str2 (sub1 j) j))))
    (for ([i (in-range 1 (add1 m))])
      (for ([j (in-range 1 (add1 n))])
        (if (equal? (string-ref str1 (sub1 i)) (string-ref str2 (sub1 j)))
            (vector-set! (vector-ref dp i) j (string-append (vector-ref dp (sub1 i) (sub1 j)) (substring str1 (sub1 i) i)))
            (let ((s1 (vector-ref dp (sub1 i) j))
                 (s2 (vector-ref dp i (sub1 j))))
              (if (< (string-length s1) (string-length s2))
                  (vector-set! (vector-ref dp i) j (string-append s1 (substring str1 (sub1 i) i)))
                  (vector-set! (vector-ref dp i) j (string-append s2 (substring str2 (sub1 j) j))))))))
    (vector-ref (vector-ref dp m) n)))