(define/contract (string-matching words)
  (-> (listof string?) (listof string?))
  (define result '())
  (for ([word1 words])
    (for ([word2 words])
      (when (and (not (equal? word1 word2)) (string-contains? word2 word1))
        (set! result (cons word1 result))
        ))
  (remove-duplicates (reverse result)))