(define/contract (process-queries queries m)
  (-> (listof exact-integer?) exact-integer? (listof exact-integer?))
  (define p (build-list m (lambda (i) (add1 i))))
  (define result '())
  (for ([q (in-list queries)])
    (define idx (index-of p q))
    (set! result (cons idx result))
    (set! p (cons q (remove q p))))
  (reverse result))