(define (count-triplets arr)
  (let loop ([i 0] [count 0])
    (if (>= i (length arr))
        count
        (let loop2 ([j (add1 i)] [count count])
          (if (>= j (length arr))
              (loop (add1 i) count)
              (let loop3 ([k j] [a 0] [b 0] [count count])
                (if (> k (length arr))
                    (loop2 (add1 j) count)
                    (let ([a (bitwise-xor a (list-ref arr (sub1 k)))])
                      (if (= a b)
                          (loop3 (add1 k) a b (add1 count))
                          (loop3 (add1 k) a b count)))))))))