(define (concatenated-binary n)
  (define MOD 1000000007)
  (define (helper i res len shift)
    (if (> i n)
        res
        (helper (add1 i) 
                (modulo (+ (arithmetic-shift res shift) i) MOD)
                (if (zero? (bitwise-and i (sub1 i)))
                    (add1 len)
                    len)
                (if (zero? (bitwise-and i (sub1 i)))
                    (add1 shift)
                    shift))))
  (helper 1 0 0 0))