(define (minimum-boxes n)
  (let loop ([k 1] [total 0] [level 1])
    (if (>= total n)
        (let ([remaining (- n (- total level))])
          (let loop2 ([i 1] [sum 0])
            (if (>= sum remaining)
                (- (+ (quotient (* level (sub1 level)) 2) i) 1)
                (loop2 (add1 i) (+ sum i)))))
        (loop (add1 k) (+ total k) (add1 level)))))