(define/contract (min-operations boxes)
  (-> string? (listof exact-integer?))
  (define n (string-length boxes))
  (define result (make-list n 0))
  (for ([i (in-range n)])
    (for ([j (in-range n)])
      (when (char=? (string-ref boxes j) #\1)
        (list-set! result i (+ (list-ref result i) (abs (- i j))))))
  result)