(define (beauty-sum s)
  (define n (string-length s))
  (define sum 0)
  (for ([i (in-range n)])
    (define freq (make-hash))
    (for ([j (in-range i n)])
      (define c (string-ref s j))
      (hash-update! freq c add1 0)
      (define values-list (hash-values freq))
      (define max-freq (apply max values-list))
      (define min-freq (apply min values-list))
      (set! sum (+ sum (- max-freq min-freq)))))
  sum)