(define/contract (number-of-unique-good-subsequences binary)
  (-> string? exact-integer?)
  (define mod 1000000007)
  (define n (string-length binary))
  (define dp (make-hash))
  (hash-set! dp "" 1)
  (for ([i (in-range n)])
    (define c (string-ref binary i))
    (define new-entries (make-hash))
    (for ([(s cnt) (in-hash dp)])
      (define new-s (string-append s (string c)))
      (hash-set! new-entries new-s cnt))
    (for ([(s cnt) (in-hash new-entries)])
    (for ([(s cnt) (in-hash new-entries)])
    (for ([(s cnt) (in-hash new-entries)])
      (hash-update! dp s (lambda (v) (modulo (+ v cnt) mod)) (void)))
  (define result 0)
  (for ([(s cnt) (in-hash dp)])
  (for ([(s cnt) (in-hash dp)])
    (when (and (> (string-length s) 0)
               (or (not (string-prefix? s "0"))
                   (= (string-length s) 1)))
      (set! result (modulo (+ result cnt) mod))))
  result)