(define (count-quadruplets nums)
  (let loop ([i 0] [count 0])
    (if (>= i (- (length nums) 3))
        count
        (let loop2 ([j (+ i 1)] [count count])
          (if (>= j (- (length nums) 2))
              (loop (+ i 1) count)
              (let loop3 ([k (+ j 1)] [count count])
                (if (>= k (- (length nums) 1))
                    (loop2 (+ j 1) count)
                    (let loop4 ([l (+ k 1)] [count count])
                      (if (>= l (length nums))
                          (loop3 (+ k 1) count)
                          (if (= (+ (list-ref nums i) (list-ref nums j) (list-ref nums k)) (list-ref nums l))
                              (loop4 (+ l 1) (+ count 1))
                              (loop4 (+ l 1) count))))))))))