(define (count-distinct nums k p)
  (define n (length nums))
  (define seen (mutable-set))
  (for ([i (in-range n)])
    (define cnt 0)
    (define current-subarray '())
    (for ([j (in-range i n)])
      (when (zero? (modulo (list-ref nums j) p))
        (set! cnt (add1 cnt)))
      (when (> cnt k)
        (break))
      (set! current-subarray (cons (list-ref nums j) current-subarray))
      (set-add! seen (reverse current-subarray))))
  (set-count seen))