(define/contract (arithmetic-triplets nums diff)
  (-> (listof exact-integer?) exact-integer? exact-integer?)
  (let loop ([i 0] [count 0])
    (if (>= i (length nums))
        count
        (let loop-j ([j (+ i 1)] [count count])
          (if (>= j (length nums))
              (loop (+ i 1) count)
              (let loop-k ([k (+ j 1)] [count count])
                (if (>= k (length nums))
                    (loop-j (+ j 1) count)
                    (if (and (= (- (list-ref nums j) (list-ref nums i)) diff)
                         (= (- (list-ref nums k) (list-ref nums j)) diff))
                        (loop-k (+ k 1) (+ count 1))
                        (loop-k (+ k 1) count))))))))