(define (count-good-strings low high zero one)
  (define mod 1000000007)
  (define dp (make-vector (+ high 1) 0))
  (vector-set! dp 0 1)
  (for ([i (in-range 1 (+ high 1))])
    (if (>= i zero)
        (vector-set! dp i (modulo (+ (vector-ref dp i) (vector-ref dp (- i zero))) mod))
        (void))
    (if (>= i one)
        (vector-set! dp i (modulo (+ (vector-ref dp i) (vector-ref dp (- i one))) mod))
        (void)))
  (let loop ([i low] [sum 0])
    (if (> i high)
        sum
        (loop (+ i 1) (modulo (+ sum (vector-ref dp i)) mod)))))