(define/contract (subarray-lcm nums k)
  (-> (listof exact-integer?) exact-integer? exact-integer?)
  (define n (length nums))
  (define count 0)
  (for ([i (in-range n)])
    (define current-lcm 1)
    (for ([j (in-range i n)])
      (set! current-lcm (lcm current-lcm (list-ref nums j)))
      (when (> current-lcm k) (break))
      (when (= current-lcm k) (set! count (add1 count)))
    )
  )
  count
)