(define (nth-ugly-number n)
  (let loop ([i 1] [uglies (make-hash)] [next2 2] [next3 3] [next5 5] [i2 1] [i3 1] [i5 1])
    (hash-set! uglies 1 1)
    (if (> i n)
        (hash-ref uglies n)
        (let ([next (min next2 next3 next5)])
          (hash-set! uglies i next)
          (when (= next next2)
            (set! i2 (add1 i2))
            (set! next2 (* (hash-ref uglies i2) 2)))
          (when (= next next3)
            (set! i3 (add1 i3))
            (set! next3 (* (hash-ref uglies i3) 3)))
          (when (= next next5)
            (set! i5 (add1 i5))
            (set! next5 (* (hash-ref uglies i5) 5)))
          (loop (add1 i) uglies next2 next3 next5 i2 i3 i5)))))