(define/contract (sort-vowels s)
  (-> string? string?)
  (define vowels (list #\a #\e #\i #\o #\u #\A #\E #\I #\O #\U))
  (define vowel-list (filter (lambda (c) (member c vowels)) (string->list s)))
  (define sorted-vowels (sort vowel-list char<?))
  (define (helper lst sorted-vowels)
    (if (null? lst)
        '()
        (let ((c (car lst)))
          (if (member c vowels)
              (cons (car sorted-vowels) (helper (cdr lst) (cdr sorted-vowels)))
              (cons c (helper (cdr lst) sorted-vowels)))))))
  (list->string (helper (string->list s) sorted-vowels))))