(define (count-pairs coordinates k)
  (let ((count 0)
        (n (length coordinates)))
    (for ([i (in-range n)])
      (for ([j (in-range (add1 i) n)])
        (let ((x1 (list-ref (list-ref coordinates i) 0))
              (y1 (list-ref (list-ref coordinates i) 1))
              (x2 (list-ref (list-ref coordinates j) 0))
              (y2 (list-ref (list-ref coordinates j) 1)))
          (if (= (+ (abs (- x1 x2)) (abs (- y1 y2))) k)
              (set! count (add1 count)))))
    count))