(define/contract (maximum-triplet-value nums)
  (-> (listof exact-integer?) exact-integer?)
  (let loop ([i 0] [max1 -inf.0] [max2 -inf.0] [res -inf.0])
    (if (>= i (length nums))
        (if (>= res 0) res 0)
        (let ([num (list-ref nums i)])
          (loop (add1 i)
                (max max1 num)
                (max max2 (- max1 num))
                (max res (* max2 num)))))))