(define (maximum-strong-pair-xor nums)
  (define max-xor 0)
  (define n (length nums))
  (for ([i (in-range n)])
    (for ([j (in-range i n)])
      (when (<= (abs (- (list-ref nums i) (list-ref nums j))) (min (list-ref nums i) (list-ref nums j)))
        (define current-xor (bitwise-xor (list-ref nums i) (list-ref nums j)))
        (when (> current-xor max-xor)
          (set! max-xor current-xor))))
  max-xor)