(define/contract (find-peaks mountain)
  (-> (listof exact-integer?) (listof exact-integer?))
  (let loop ([i 1] [res '()] [m mountain])
    (if (>= i (- (length mountain) 1))
        (reverse res)
        (if (and (> (list-ref mountain i) (list-ref mountain (- i 1)))
                 (> (list-ref mountain i) (list-ref mountain (+ i 1))))
            (loop (+ i 1) (cons i res) m)
            (loop (+ i 1) res m)))))