(define/contract (maximum-length s)
  (-> string? exact-integer?)
  (define n (string-length s))
  (define (count-max c)
    (let loop ([i 0] [cnt 0] [res '()])
      (if (>= i n)
          (if (> cnt 0) (reverse (cons cnt res)) (reverse res))
          (if (char=? (string-ref s i) c)
              (loop (add1 i) (add1 cnt) res)
              (loop (add1 i) 0 (if (> cnt 0) (cons cnt res) res))))))
  (define (get-max-three lst)
    (let loop ([lst (sort lst >)] [res 0] [cnt 0])
      (if (or (null? lst) (>= cnt 3))
          res
          (let ([val (car lst)])
            (loop (cdr lst)
                  (max res (if (>= val 3) (- val 2) (if (>= val 2) 1 0)))
                  (add1 cnt))))))
  (let ([max-len 0])
    (for ([c (in-string s)])
      (let ([counts (count-max c)])
        (when (>= (length counts) 3)
          (set! max-len (max max-len (get-max-three counts))))))
    max-len))