(define (minimize-or nums)
  (define (helper mask res)
    (if (< mask 1)
        res
        (let loop ((i 0) (current-mask mask) (new-res res))
          (if (>= i (vector-length nums))
              (helper (arithmetic-shift mask -1) new-res)
              (if (zero? (bitwise-and (vector-ref nums i) mask))
                  (loop (add1 i) current-mask new-res)
                  (let ((temp (bitwise-and res (bitwise-not mask))))
                    (if (<= temp new-res)
                        (loop (add1 i) (bitwise-xor current-mask mask) temp)
                        (loop (add1 i) current-mask new-res))))))))
  (helper (arithmetic-shift 1 30) (bitwise-ior (vector-ref nums 0) 0)))