(define (make-string-empty s)
  (let* ((counts (make-hash))
         (n (string-length s)))
    (for ([c (in-string s)])
      (hash-update! counts c add1 0))
    (let ((max-count (apply max (hash-values counts))))
      (let loop ((i 0)
                 (res '()))
        (if (= i n)
            (list->string (reverse res))
            (let ((c (string-ref s i)))
              (if (= (hash-ref counts c) max-count)
                  (loop (add1 i) (cons c res))
                  (loop (add1 i) res))))))))