(define (shortest-subarray-or nums k)
  (let loop ((i 0) (min-len +inf.0))
    (if (>= i (length nums))
        (if (= min-len +inf.0) -1 min-len)
        (let inner ((j i) (current-or 0) (current-len 0))
          (if (>= j (length nums))
              (loop (+ i 1) min-len)
              (let ((new-or (bitwise-ior current-or (list-ref nums j)))
                (if (>= new-or k)
                    (loop (+ i 1) (min min-len (+ current-len 1)))
                    (inner (+ j 1) new-or (+ current-len 1)))))))))