(define (minimum-or-difference nums k)
  (define min-diff +inf.0)
  (define n (length nums))
  (for ([i (in-range n)])
    (define current-or 0)
    (for ([j (in-range i n)])
      (set! current-or (bitwise-ior current-or (list-ref nums j)))
      (define diff (abs (- current-or k)))
      (when (< diff min-diff)
        (set! min-diff diff))
      (when (zero? min-diff)
        (return min-diff))))
  min-diff)