(define (smallest-string s)
  (let loop ((s (string->list s))
             (i 0)
             (min-char #\z)
             (min-idx 0))
    (if (>= i (length s))
        (list->string s)
        (let ((current-char (list-ref s i)))
          (if (char<? current-char min-char)
              (loop s (+ i 1) current-char i)
              (loop s (+ i 1) min-char min-idx))))))