(define (count-monotonic-pairs nums)
  (let loop ([i 0] [count 0])
    (if (>= i (length nums))
        count
        (let inner-loop ([j (+ i 1)] [current-count count])
          (if (>= j (length nums))
              (loop (+ i 1) current-count)
              (if (and (<= (list-ref nums i) (list-ref nums j))
                       (>= (list-ref nums i) (list-ref nums j)))
                  (inner-loop (+ j 1) (+ current-count 1))
                  (inner-loop (+ j 1) current-count)))))))