(define/contract (max-result nums)
  (-> (listof exact-integer?) exact-integer?)
  (let ([n (length nums)])
    (if (= n 1)
        (first nums)
        (let ([dp (make-vector n -inf.0)])
          (vector-set! dp 0 (first nums))
          (for ([i (in-range n)])
            (for ([j (in-range 1 (add1 (min 2 (- n i 1))))])
              (let ([next (+ i j)])
                (when (< next n)
                  (vector-set! dp next (max (vector-ref dp next)
                                           (+ (vector-ref dp i) (list-ref nums next))))))))
          (vector-ref dp (sub1 n))))))