(define (max-product nums)
  (define n (length nums))
  (define max-len 0)
  (for ([i n])
    (define product 1)
    (for ([j (in-range i n)])
      (set! product (* product (list-ref nums j)))
      (when (zero? product)
        (set! product 1)
        (set! j n))
      (when (= product 1)
        (set! max-len (max max-len (- j i -1))))))
  max-len)