(define (max-difference nums)
  (define n (length nums))
  (define max-diff -1)
  (for ([i n])
    (define current (list-ref nums i))
    (for ([j (in-range (add1 i) (+ i n))])
      (define next (list-ref nums (modulo j n)))
      (when (and (< current next) (> (- next current) max-diff))
        (set! max-diff (- next current))))
  (if (> max-diff -1) max-diff -1))