(define (smallest-string n k)
  (let loop ((res (make-string n #\a))
             (i (sub1 n)))
    (if (< i 0)
        res
        (let ((max-char (min (char->integer #\z)
                             (+ (char->integer (string-ref res i))
                                (if (and (> i 0)
                                         (< (abs (- (char->integer (string-ref res i))
                                                    (char->integer (string-ref res (sub1 i)))))
                                            k))
                                     (- k (abs (- (char->integer (string-ref res i))
                                                  (char->integer (string-ref res (sub1 i))))))
                                     0))))))
          (if (>= max-char (char->integer #\a))
              (loop (string-set res i (integer->char max-char)) (sub1 i))
              res)))))