(define/contract (get-money-amount n)
  (-> exact-integer? exact-integer?)
  (define dp (make-vector (add1 n) (make-vector (add1 n) 0)))
  (for ([len (in-range 2 (add1 n))])
    (for ([i (in-range 1 (- (add1 n) len -1))])
      (define j (+ i len -1))
      (vector-set! (vector-ref dp i) j +inf.0)
      (for ([k (in-range i j)])
        (define cost (+ k (max (vector-ref (vector-ref dp i) (sub1 k))
                               (vector-ref (vector-ref dp (add1 k)) j))))
        (when (< cost (vector-ref (vector-ref dp i) j))
          (vector-set! (vector-ref dp i) j cost)))))
  (vector-ref (vector-ref dp 1) n))