(define (add-strings num1 num2)
  (let loop ((i (sub1 (string-length num1)))
             ((j (sub1 (string-length num2)))
              (carry 0)
              (res '()))
    (if (and (< i 0) (< j 0) (= carry 0))
        (if (null? res) "0" (list->string res))
        (let* ((d1 (if (>= i 0) (- (char->integer (string-ref num1 i)) (char->integer #\0)) 0))
               (d2 (if (>= j 0) (- (char->integer (string-ref num2 j)) (char->integer #\0)) 0))
               (sum (+ d1 d2 carry))
               (digit (modulo sum 10))
               (new-carry (quotient sum 10)))
          (loop (sub1 i) (sub1 j) new-carry (cons (integer->char (+ digit (char->integer #\0))) res)))))