(define/contract (find132pattern nums)
  (-> (listof exact-integer?) boolean?)
  (let ([stack '()]
        [s3 -inf.0])
    (for ([num (reverse nums)])
      (when (< num s3)
        (return #t))
      (let loop ()
        (when (and (not (null? stack)) (> num (car stack)))
          (set! s3 (car stack))
          (set! stack (cdr stack))
          (loop)))
      (set! stack (cons num stack)))
    #f))