(define/contract (strange-printer s)
  (-> string? exact-integer?)
  (let* ([n (string-length s)]
         [dp (make-vector (* n n) 0)])
    (for ([i (in-range (- n 1) -1 -1)])
      (vector-set! dp (+ i (* i n)) 1)
      (for ([j (in-range (+ i 1) n)])
        (if (equal? (string-ref s i) (string-ref s j))
            (vector-set! dp (+ i (* j n)) (vector-ref dp (+ i (* (- j 1) n))))
            (let ([min-val +inf.0])
              (for ([k (in-range i j)])
                (set! min-val (min min-val (+ (vector-ref dp (+ i (* k n))) (vector-ref dp (+ (+ k 1) (* j n))))))
              (vector-set! dp (+ i (* j n)) min-val)))))
    (vector-ref dp (- n 1))))