(define/contract (find-anagrams s p)
  (-> string? string? (listof exact-integer?))
  (define s-len (string-length s))
  (define p-len (string-length p))
  (define result '())
  (when (>= s-len p-len)
    (define p-count (make-vector 26 0))
    (define s-count (make-vector 26 0))
    (for ([i (in-range p-len)])
      (vector-set! p-count (- (char->integer (string-ref p i)) 97)
                   (add1 (vector-ref p-count (- (char->integer (string-ref p i)) 97))))
      (vector-set! s-count (- (char->integer (string-ref s i)) 97)
                   (add1 (vector-ref s-count (- (char->integer (string-ref s i)) 97)))))
    (when (equal? p-count s-count)
      (set! result (cons 0 result)))
    (for ([i (in-range p-len s-len)])
      (vector-set! s-count (- (char->integer (string-ref s (- i p-len))) 97)
                   (sub1 (vector-ref s-count (- (char->integer (string-ref s (- i p-len))) 97))))
      (vector-set! s-count (- (char->integer (string-ref s i)) 97)
                   (add1 (vector-ref s-count (- (char->integer (string-ref s i)) 97))))
      (when (equal? p-count s-count)
        (set! result (cons (- i (- p-len 1)) result)))))
  (reverse result))