(define/contract (copy-random-list head)
  (-> (or/c null? (box/c (list/c exact-integer? (or/c null? (box/c any/c)) (or/c null? (box/c any/c))))))
      (or/c null? (box/c (list/c exact-integer? (or/c null? (box/c any/c)) (or/c null? (box/c any/c))))))
  (if (null? head)
      null
      (let ([m (make-hash)])
        (let loop ([node head])
          (when (not (null? node))
            (hash-set! m node (box (list (first (unbox node)) null null)))
            (loop (third (unbox node)))))
        (let loop ([node head])
          (when (not (null? node))
            (let ([new-node (hash-ref m node)])
            (unless (null? (second (unbox node)))
              (set-box! (second (unbox new-node)) (hash-ref m (second (unbox node)))))
            (unless (null? (third (unbox node)))
              (set-box! (third (unbox new-node)) (hash-ref m (third (unbox node)))))
            (loop (third (unbox node)))))
        (hash-ref m head))))