(define/contract (min-cost-climbing-stairs cost)
  (-> (listof exact-integer?) exact-integer?)
  (let loop ([i (length cost)] [dp (make-hash '((0 . 0) (1 . 0)))])
    (if (<= i 1)
        (hash-ref dp i)
        (let ([cost-i (list-ref cost (- i 1))])
          (loop (- i 1)
                (hash-set dp i (min (+ (hash-ref dp (- i 1)) cost-i)
                                    (+ (hash-ref dp (- i 2)) cost-i))))))))