(define (gridIllumination n lamps queries)
  (define lamps-set (make-hash))
  (define row-count (make-hash))
  (define col-count (make-hash))
  (define diag1-count (make-hash)) ; row + col
  (define diag2-count (make-hash)) ; row - col

  (for ([lamp lamps])
    (define row (first lamp))
    (define col (second lamp))
    (hash-set! lamps-set (cons row col) #t)
    (hash-update row-count row (lambda (v) (+ v 1)) 0)
    (hash-update col-count col (lambda (v) (+ v 1)) 0)
    (hash-update diag1-count (+ row col) (lambda (v) (+ v 1)) 0)
    (hash-update diag2-count (- row col) (lambda (v) (+ v 1)) 0))

  (define (illuminate? row col)
    (or (hash-ref row-count row 0)
        (hash-ref col-count col 0)
        (hash-ref diag1-count (+ row col) 0)
        (hash-ref diag2-count (- row col) 0)))

  (define (turn-off row col)
    (define lamps-to-remove '())
    (for ([dr '(-1 -1 -1 0 0 0 1 1 1)])
      (for ([dc '(-1 0 1 -1 0 1 -1 0 1)])
        (define new-row (+ row dr))
        (define new-col (+ col dc))
        (when (and (>= new-row 0) (< new-row n) (>= new-col 0) (< new-col n)
                   (hash-has-key? lamps-set (cons new-row new-col)))
          (set! lamps-to-remove (cons (cons new-row new-col) lamps-to-remove)))))
    (for ([lamp lamps-to-remove])
      (define r (car lamp))
      (define c (cdr lamp))
      (hash-remove! lamps-set (cons r c))
      (hash-update row-count r (lambda (v) (- v 1)) 0)
      (hash-update col-count c (lambda (v) (- v 1)) 0)
      (hash-update diag1-count (+ r c) (lambda (v) (- v 1)) 0)
      (hash-update diag2-count (- r c) (lambda (v) (- v 1)) 0)))

  (define result '())
  (for ([query queries])
    (define row (first query))
    (define col (second query))
    (set! result (cons (if (illuminate? row col) 1 0) result))
    (turn-off row col))
  (reverse result))