(define (num-pairsDivisibleBy60 time)
  (let* ((remainders (make-vector 60 0))
         (count 0))
    (for-each (lambda (t)
                (let ((remainder (modulo t 60)))
                  (set! count (+ count (vector-ref remainders (modulo (- 60 remainder) 60))))
                  (vector-set! remainders remainder (+ 1 (vector-ref remainders remainder)))))
              time)
    count))