(define (min-height-shelves books shelf-width)
  (define n (length books))
  (define dp (make-vector (+ n 1) 0))
  (for ([i (in-range 1 (+ n 1))])
    (define width 0)
    (define height 0)
    (define min-height (vector-ref dp (- i 1)) )
    (for ([j (in-range (- i 1) -1 -1)])
      (define book (list-ref books j))
      (define book-width (car book))
      (define book-height (cadr book))
      (set! width (+ width book-width))
      (if (> width shelf-width)
          (void)
          (begin
            (set! height (max height book-height))
            (set! min-height (min min-height (+ height (vector-ref dp j)))))))
    (vector-set! dp i min-height))
  (vector-ref dp n))