(define (max-rep-opt1 s)
  (let* ((n (string-length s))
         (counts (make-hash))
         (max-count 0))
    (for ([i (in-range n)])
      (let ((char (string-ref s i)))
        (hash-update! counts char (λ (v) (+ v 1)) 1)
        (set! max-count (max max-count (hash-ref counts char)))))
    (let loop ([i 0] [max-len 0])
      (if (= i n)
          max-len
          (let ((c (string-ref s i)))
            (let loop2 ([j i] [diff 0] [curr-len 0])
              (cond
                ((= j n)
                 (max (if (< diff 1) curr-len (min curr-len (hash-ref counts c))) max-len))
                ((= diff 0)
                 (if (char=? c (string-ref s j))
                     (loop2 (+ j 1) diff (+ curr-len 1))
                     (loop2 (+ j 1) (+ diff 1) (+ curr-len 1))))
                ((= diff 1)
                 (if (char=? c (string-ref s j))
                     (loop2 (+ j 1) diff (+ curr-len 1))
                     (max (min curr-len (hash-ref counts c)) max-len)))
                (else
                 (max (min curr-len (hash-ref counts c)) max-len)))))
            (loop (+ i 1) max-len)))))