(define (max-level-sum root)
  (letrec ((levels (lambda (node level)
                     (cond
                       ((null? node) '())
                       (else (cons (cons level (node->value node))
                                   (append (levels (node->left node) (+ level 1))
                                           (levels (node->right node) (+ level 1))))))))
           (group-by-level (lambda (data)
                              (let ((levels '()))
                                (for-each (lambda (item)
                                            (let ((level (car item))
                                                  (value (cdr item)))
                                              (set! levels
                                                    (cons (cons level (cons value (if (assq level levels) (cdr (assq level levels)) '()))) levels))))
                                          data)
                                (map (lambda (item) (cons (car item) (apply + (cdr item)))) levels))))
           (find-max-level (lambda (grouped-data)
                              (let ((max-level (car (car grouped-data)))
                                    (max-sum (cdr (car grouped-data))))
                                (for-each (lambda (item)
                                            (let ((level (car item))
                                                  (sum (cdr item)))
                                              (if (> sum max-sum)
                                                  (begin
                                                    (set! max-level level)
                                                    (set! max-sum sum)))))
                                          (cdr grouped-data))
                                max-level))))
    (find-max-level (group-by-level (levels root 1)))))