(define (minimum-total triangle)
  (let* ((n (length triangle))
         (dp (make-vector (add1 n) 0)))
    (for/fold ((dp dp))
              ((i (reverse (range n))))
      (let ((row (list->vector (list-ref triangle i))))
        (for/fold ((dp dp))
                  ((j (range (length row))))
          (vector-set! dp j (+ (vector-ref row j) (min (vector-ref dp j) (vector-ref dp (add1 j)))))
          dp))
      dp)
    (vector-ref dp 0)))