(define (dining-philosophers)
  (define n 5)
  (define forks (make-vector n #t))
  (define philosophers (make-vector n (lambda (i)
                                      (lambda ()
                                        (define left i)
                                        (define right (modulo (+ i 1) n))
                                        (define (eat)
                                          (when (and (vector-ref forks left)
                                                     (vector-ref forks right))
                                            (vector-set! forks left #f)
                                            (vector-set! forks right #f)
                                            (thread-sleep 1) ; simulate eating
                                            (vector-set! forks left #t)
                                            (vector-set! forks right #t)
                                            (void)))
                                        (let loop ()
                                          (eat)
                                          (loop))))))
  (for ([i (in-range n)])
    (future ((vector-ref philosophers i) i)))
  (void))