(define (suggested-products products search-word)
  (let* ((sorted-products (sort products string<?))
         (n (string-length search-word))
         (result '()))
    (for ([i (in-range 1 (add1 n))])
      (let* ((prefix (substring search-word 0 i))
             (candidates (filter (lambda (product) (string=? prefix (substring product 0 (min i (string-length product))))) sorted-products))
             (suggestions (take candidates (min 3 (length candidates)))))
        (set! result (append result (list suggestions)))))
    result))