(define (clone-graph graph)
  (if (null? graph)
      null
      (let* ((node-map (make-hash))
             (clone-node (lambda (node)
                           (if (hash-has-key? node-map node)
                               (hash-ref node-map node)
                               (let ((cloned-node (make-node (node-val node))))
                                 (hash-set! node-map node cloned-node)
                                 cloned-node)))))
        (let loop ((q (list graph))
                   (visited (make-hash)))
          (if (null? q)
              (hash-ref node-map graph)
              (let* ((node (car q))
                     (cloned-node (clone-node node)))
                (unless (hash-has-key? visited node)
                  (hash-set! visited node #t)
                  (set-node-neighbors! cloned-node (map clone-node (node-neighbors node)))
                  (loop (append (cdr q) (filter (λ (n) (not (hash-has-key? visited n))) (node-neighbors node))) visited)))))))))