(define (find-the-city n edges distance-threshold)
  (let* ((dist-matrix (make-matrix n n (lambda (i j) (if (= i j) 0 #inf.0))))
         (update-dist-matrix
          (for-each (lambda (edge)
                      (let ((u (car edge))
                            (v (cadr edge))
                            (weight (caddr edge)))
                        (matrix-set! dist-matrix u v weight)
                        (matrix-set! dist-matrix v u weight)))
                    edges))
         (floyd-warshall
          (for* ((k (in-range n))
                 (i (in-range n))
                 (j (in-range n)))
            (matrix-set! dist-matrix i j (min (matrix-ref dist-matrix i j)
                                                (+ (matrix-ref dist-matrix i k)
                                                   (matrix-ref dist-matrix k j)))))))
    (let loop ((city 0)
               (min-reachable n)
               (best-city 0))
      (if (= city n)
          best-city
          (let ((reachable-count (length (filter (lambda (d) (and (real? d) (<= d distance-threshold)))
                                                  (vector->list (matrix-row dist-matrix city))))))
            (if (< reachable-count min-reachable)
                (loop (+ city 1) reachable-count city)
                (loop (+ city 1) min-reachable best-city)))))))