(define (minSetSize arr)
  (let* ((n (length arr))
         (counts (make-hash))
         (half (/ n 2)))
    (for ([x arr])
      (hash-update! counts x (λ (v) (+ v 1)) 1))
    (let* ((sorted-counts (sort (hash-values counts) >))
           (removed 0)
           (count 0))
      (for ([c sorted-counts])
        (set! count (+ count c))
        (set! removed (+ removed 1))
        (when (>= count half)
          (return removed))))))