(define (tweet-counts-per-frequency tweetName tweetTime frequency startTime endTime)
  (let* ((interval (cond ((equal? frequency "minute") 60)
                         ((equal? frequency "hour") 3600)
                         ((equal? frequency "day") 86400)))
         (counts (make-vector (quotient (- endTime startTime) interval) 0)))
    (for ((time tweetTime))
      (when (and (>= time startTime) (<= time endTime))
        (let ((index (quotient (- time startTime) interval)))
          (vector-set! counts index (+ (vector-ref counts index) 1)))))
    (vector->list counts)))

(define tweet-counts-per-frequency-class
  (class object%
    (super-new)
    (define tweets (make-hash))
    (define/public (record-tweet tweetName time)
      (hash-update! tweets tweetName
                     (lambda (old-list) (sort (cons time old-list) <))
                     (list time)))
    (define/public (get-tweets-counts-per-frequency tweetName frequency startTime endTime)
      (let* ((tweet-times (hash-ref tweets tweetName '()))
             (interval (cond ((equal? frequency "minute") 60)
                              ((equal? frequency "hour") 3600)
                              ((equal? frequency "day") 86400)))
             (num-intervals (quotient (+ (- endTime startTime) interval -1) interval))
             (counts (make-vector num-intervals 0)))
        (for ((time tweet-times))
          (when (and (>= time startTime) (<= time endTime))
            (let ((index (quotient (- time startTime) interval)))
              (vector-set! counts index (+ (vector-ref counts index) 1)))))
        (vector->list counts)))))