(define (candy ratings)
  (let* ((n (length ratings))
         (candies (make-vector n 1)))
    (for/list ((i (in-range 1 n)))
      (when (> (list-ref ratings i) (list-ref ratings (- i 1)))
        (vector-set! candies i (+ (vector-ref candies (- i 1)) 1))))
    (for/list ((i (in-range (- n 2) -1 -1)))
      (when (and (> (list-ref ratings i) (list-ref ratings (+ i 1)))
                 (<= (vector-ref candies i) (vector-ref candies (+ i 1))))
        (vector-set! candies i (+ (vector-ref candies (+ i 1)) 1))))
    (apply + (vector->list candies))))