(define (largest-multiple-of-three digits)
  (let* ((sum (apply + digits))
         (rem (modulo sum 3))
         (ones (filter (lambda (x) (= (modulo x 3) 1)) (sort digits <)))
         (twos (filter (lambda (x) (= (modulo x 3) 2)) (sort digits <))))
    (cond
      ((= rem 0)
       (let ((res (string-join (map number->string (reverse (sort digits >))) "")))
         (if (and (>= (string-length res) 1) (equal? (substring res 0 1) "0"))
             (if (ormap (lambda (x) (not (equal? x #\0))) (string->list res))
                 (let loop ((lst (string->list res)))
                   (cond
                     ((null? lst) "0")
                     ((equal? (car lst) #\0) (loop (cdr lst)))
                     (else (list->string lst)))))
             res)))
      ((= rem 1)
       (cond
         ((>= (length ones) 1)
          (let ((new-digits (remove (list (car ones)) digits #:count 1)))
            (let ((res (string-join (map number->string (reverse (sort new-digits >))) "")))
              (if (and (>= (string-length res) 1) (equal? (substring res 0 1) "0"))
                  (if (ormap (lambda (x) (not (equal? x #\0))) (string->list res))
                      (let loop ((lst (string->list res)))
                        (cond
                          ((null? lst) "0")
                          ((equal? (car lst) #\0) (loop (cdr lst)))
                          (else (list->string lst)))))
                  res))))
         ((>= (length twos) 2)
          (let ((new-digits (remove (list (car twos) (cadr twos)) digits #:count 2)))
            (let ((res (string-join (map number->string (reverse (sort new-digits >))) "")))
              (if (and (>= (string-length res) 1) (equal? (substring res 0 1) "0"))
                  (if (ormap (lambda (x) (not (equal? x #\0))) (string->list res))
                      (let loop ((lst (string->list res)))
                        (cond
                          ((null? lst) "0")
                          ((equal? (car lst) #\0) (loop (cdr lst)))
                          (else (list->string lst)))))
                  res))))
         (else "")))
      (else
       (cond
         ((>= (length twos) 1)
          (let ((new-digits (remove (list (car twos)) digits #:count 1)))
            (let ((res (string-join (map number->string (reverse (sort new-digits >))) "")))
              (if (and (>= (string-length res) 1) (equal? (substring res 0 1) "0"))
                  (if (ormap (lambda (x) (not (equal? x #\0))) (string->list res))
                      (let loop ((lst (string->list res)))
                        (cond
                          ((null? lst) "0")
                          ((equal? (car lst) #\0) (loop (cdr lst)))
                          (else (list->string lst)))))
                  res))))
         ((>= (length ones) 2)
          (let ((new-digits (remove (list (car ones) (cadr ones)) digits #:count 2)))
            (let ((res (string-join (map number->string (reverse (sort new-digits >))) "")))
              (if (and (>= (string-length res) 1) (equal? (substring res 0 1) "0"))
                  (if (ormap (lambda (x) (not (equal? x #\0))) (string->list res))
                      (let loop ((lst (string->list res)))
                        (cond
                          ((null? lst) "0")
                          ((equal? (car lst) #\0) (loop (cdr lst)))
                          (else (list->string lst)))))
                  res))))
         (else "")))))
  )