(define (find-the-longest-substring s)
  (let* ((n (string-length s))
         (vowels (string->list "aeiou"))
         (vowel-indices (make-hash '((#\a . 0) (#\e . 1) (#\i . 2) (#\o . 3) (#\u . 4))))
         (prefix-masks (make-vector (+ n 1) 0))
         (first-seen (make-vector 32 -1)))
    (vector-set! first-seen 0 0)
    (let loop ((i 0) (mask 0))
      (if (= i n)
          (let loop2 ((j 0) (max-len 0))
            (if (= j (+ n 1))
                max-len
                (let* ((m (vector-ref prefix-masks j)))
                  (let loop3 ((k 0) (current-max max-len))
                    (if (= k 32)
                        (loop2 (+ j 1) current-max)
                        (let ((first-occurrence (vector-ref first-seen k)))
                          (if (not (= first-occurrence -1))
                              (loop3 (+ k 1) (max current-max (- j first-occurrence)))
                              (loop3 (+ k 1) current-max)))))))
            )
          (let* ((c (string-ref s i))
                 (new-mask (if (hash-has-key? vowel-indices c)
                               (bitwise-xor mask (arithmetic-shift 1 (hash-ref vowel-indices c)))
                               mask)))
            (vector-set! prefix-masks (+ i 1) new-mask)
            (when (= (vector-ref first-seen new-mask) -1)
              (vector-set! first-seen new-mask (+ i 1)))
            (loop (+ i 1) new-mask)))))