(define (min-subsequence nums)
  (let* ((sorted-nums (sort nums >))
         (total-sum (apply + nums))
         (current-sum 0)
         (result '()))
    (for ([num (in-list sorted-nums)])
      (set! result (cons num result))
      (set! current-sum (+ current-sum num))
      (set! total-sum (- total-sum num))
      (when (> current-sum total-sum)
        (reverse result)))))