(define (display-table orders)
  (define items (sort (remove-duplicates (map second orders)) string<?))
  (define tables (sort (remove-duplicates (map first orders)) <))
  (define header (cons "Table" items))
  (define table-data
    (map (lambda (table)
           (cons (number->string table)
                 (map (lambda (item)
                        (number->string (count (lambda (order)
                                                  (and (= (first order) table)
                                                       (equal? (second order) item)))
                                                orders)))
                      items)))
         tables))
  (cons header table-data))