(define (dest-city paths)
  (define starts (make-hash))
  (define ends (make-hash))
  (for ([path paths])
    (hash-set! starts (car path) #t)
    (hash-set! ends (cadr path) #t))
  (for ([k (hash-keys ends)])
    (unless (hash-has-key? starts k)
      (return k))))