(define (count-triplets arr)
  (let* ((n (length arr))
         (count 0))
    (for* ((i (in-range 0 n))
           (j (in-range (+ i 1) n))
           (k (in-range (+ j 1) (+ n 1)))
           #:when (equal? (foldl xor 0 (take (drop arr i) (- j i)))
                         (foldl xor 0 (take (drop arr j) (- k j)))))
      (set! count (+ count 1)))
    count))