(define (people-whose-list-of-favorite-companies-is-not-a-subset-of-another-list favoriteCompanies)
  (define n (length favoriteCompanies))
  (define result '())
  (for ([i (in-range n)])
    (define is-subset? #f)
    (for ([j (in-range n)])
      (when (and (!= i j)
                 (set-subset? (list->set (list-ref favoriteCompanies i))
                              (list->set (list-ref favoriteCompanies j))))
        (set! is-subset? #t)
        (break)))
    (when (not is-subset?)
      (set! result (append result (list i)))))
  result)