(define (pseudo-palindromic-paths root)
  (letrec ((count-paths (lambda (node path)
                           (if (null? node)
                               0
                               (let ((new-path (cons (car node) path)))
                                 (if (and (null? (cadr node)) (null? (caddr node)))
                                     (if (is-pseudo-palindrome? new-path) 1 0)
                                     (+ (count-paths (cadr node) new-path)
                                        (count-paths (caddr node) new-path)))))))
           (is-pseudo-palindrome? (lambda (path)
                                    (let ((counts (make-hash)))
                                      (for-each (lambda (x)
                                                  (hash-update! counts x (lambda (v) (+ v 1)) 1))
                                                path)
                                      (let ((odd-count 0))
                                        (hash-for-each counts (lambda (k v)
                                                                (if (odd? v)
                                                                    (set! odd-count (+ odd-count 1)))))
                                        (<= odd-count 1))))))
    (if (null? root)
        0
        (count-paths root '()))))