(define (course-schedule-iv n prerequisites queries)
  (define adj (make-vector n null))
  (for ([p prerequisites])
    (vector-set! adj (first p) (cons (second p) (vector-ref adj (first p))))
    )
  (define reachable (make-vector n (make-hash)))
  (define (bfs start)
    (unless (hash-has-key? (vector-ref reachable start) start)
      (define q (list start))
      (hash-set! (vector-ref reachable start) start #t)
      (define visited (make-set (list start)))
      (define (helper q)
        (cond [(null? q) (void)]
              [else
               (let ([curr (car q)])
                 (for ([neighbor (vector-ref adj curr)])
                   (unless (set-member? visited neighbor)
                     (set! visited (set-add visited neighbor))
                     (hash-set! (vector-ref reachable start) neighbor #t)
                     (set! q (append q (list neighbor)))))
                 (helper (cdr q)))]))
      (helper q)))

  (for ([i (range n)])
    (bfs i))
  (map (lambda (q)
         (hash-has-key? (vector-ref reachable (first q)) (second q)))
       queries))