(define (max-area horizontalCuts verticalCuts h w)
  (let* ((horizontalCuts (sort horizontalCuts <))
         (verticalCuts (sort verticalCuts <))
         (max-h (max (car horizontalCuts) (- h (last horizontalCuts))))
         (max-v (max (car verticalCuts) (- w (last verticalCuts)))))
    (for/fold ((prev 0) (max-diff 0)) ((cut (in-list horizontalCuts)))
      (let ((diff (- cut prev)))
        (values cut (max max-diff diff))))
    (let* ((max-h (for/fold ((prev 0) (max-diff 0)) ((cut (in-list horizontalCuts)))
                     (let ((diff (- cut prev)))
                       (values cut (max max-diff diff)))
                     (values 0 (max max-diff (- h (last horizontalCuts))))))
           (max-v (for/fold ((prev 0) (max-diff 0)) ((cut (in-list verticalCuts)))
                     (let ((diff (- cut prev)))
                       (values cut (max max-diff diff)))
                     (values 0 (max max-diff (- w (last verticalCuts)))))))
      (modulo (* max-h max-v) 1000000007))))