(define (get-min-dist positions)
  (let* ((n (length positions))
         (x-coords (sort (map car positions) <))
         (y-coords (sort (map cdr positions) <))
         (median-x (list-ref x-coords (quotient n 2)))
         (median-y (list-ref y-coords (quotient n 2)))
         (best-x median-x)
         (best-y median-y))
    (let loop ((curr-x best-x) (curr-y best-y) (step 100) (best-dist (calc-dist positions curr-x curr-y)))
      (if (<= step 1e-6)
          best-dist
          (let* ((dx '(-1 0 1))
                 (dy '(-1 0 1))
                 (next-points (for*/list ((dx dx) (dy dy))
                                (list (+ curr-x (* step dx)) (+ curr-y (* step dy)))))
                 (min-dist best-dist)
                 (new-x curr-x)
                 (new-y curr-y))
            (for ((point next-points))
              (let ((x (car point)) (y (cdr point)) (dist (calc-dist positions x y)))
                (when (< dist min-dist)
                  (set! min-dist dist)
                  (set! new-x x)
                  (set! new-y y))))
            (if (= min-dist best-dist)
                (loop curr-x curr-y (/ step 2) best-dist)
                (loop new-x new-y step min-dist)))))))

(define (calc-dist positions x y)
  (foldl + 0 (map (lambda (pos) (sqrt (+ (expt (- x (car pos)) 2) (expt (- y (cdr pos)) 2)))) positions)))

(define (get-min-dist-optimized positions)
  (let ((n (length positions)))
    (let loop ((l 0) (r 100))
      (if (< (- r l) 1e-6)
          l
          (let ((m1 (+ l (/ (- r l) 3)))
                (m2 (- r (/ (- r l) 3))))
            (if (< (calc-dist-1d positions m1) (calc-dist-1d positions m2))
                (loop l m2)
                (loop m1 r))))))

(define (calc-dist-1d positions x)
  (foldl + 0 (map (lambda (pos) (abs (- x pos))) positions)))

(define (minTotalDistance positions)
  (let* ((x-coords (map car positions))
         (y-coords (map cdr positions)))
    (let ((median-x (get-min-dist-optimized x-coords))
          (median-y (get-min-dist-optimized y-coords)))
      (round (calc-dist positions median-x median-y)))))