(define (maximum-network-quality towers radius)
  (define (calculate-quality x y)
    (apply + (map (lambda (tower)
                     (let ((tx (car tower))
                           (ty (cadr tower))
                           (q (caddr tower)))
                       (let ((distance (sqrt (+ (expt (- tx x) 2) (expt (- ty y) 2)))))
                         (if (<= distance radius)
                             (floor (/ q (+ 1 distance)))
                             0))))
                   towers)))

  (define (find-max-quality)
    (let* ((min-x (apply min (map car towers)))
           (max-x (apply max (map car towers)))
           (min-y (apply min (map cadr towers)))
           (max-y (apply max (map cadr towers)))
           (best-x (list 0))
           (best-y (list 0))
           (max-quality (list 0)))
      (for ((x (in-range min-x (+ max-x 1)))
            (y (in-range min-y (+ max-y 1))))
           (let ((quality (calculate-quality x y)))
             (when (> quality (car max-quality))
               (set! max-quality (list quality))
               (set! best-x (list x))
               (set! best-y (list y)))))
      (list (car best-x) (car best-y))))

  (find-max-quality))