(define (max-profit inventory orders)
  (define (count-balls val)
    (foldl + 0 (map (lambda (ball) (if (> ball val) (- ball val) 0)) inventory)))

  (define (calculate-profit val)
    (foldl + 0 (map (lambda (ball)
                       (if (> ball val)
                           (let ((count (- ball val)))
                             (* (+ ball (+ val 1)) (/ count 2)))
                           0))
                     inventory)))

  (define (calculate-profit-exact val count)
      (foldl + 0 (map (lambda (ball)
                         (if (> ball val)
                             (let ((take (min (- ball val) count)))
                                (* (+ ball (+ ball (- take 1))) (/ take 2)))
                             0))
                       inventory)))

  (define (find-max-value left right)
    (if (= left right)
        left
        (let ((mid (floor (/ (+ left right) 2))))
          (if (>= (count-balls mid) orders)
              (find-max-value left mid)
              (find-max-value (+ mid 1) right)))))

  (let ((max-val (apply max inventory)))
    (let ((min-val (find-max-value 1 max-val)))
      (define (calculate-result)
        (let ((total-profit (calculate-profit min-val)))
          (let ((balls-taken (count-balls min-val)))
            (if (> balls-taken orders)
                (let ((profit-exact (calculate-profit-exact min-val (- balls-taken orders))))
                    (modulo (- total-profit profit-exact) 1000000007))
                (modulo total-profit 1000000007))))))
      (calculate-result))))