(define queue%
  (class object%
    (init)
    (super-new)
    (define front '())
    (define back '())
    (define (size) (+ (length front) (length back)))
    (define (rebalance)
      (when (> (abs (- (length front) (length back))) 1)
        (if (> (length front) (length back))
            (begin
              (set! back (cons (car front) back))
              (set! front (cdr front)))
            (begin
              (set! front (cons (car back) front))
              (set! back (cdr back))))))
    (public
     (define/public (pushFront x)
       (set! front (cons x front))
       (rebalance))
     (define/public (pushMiddle x)
       (let ((s (size)))
         (if (even? s)
             (let ((half (/ s 2)))
               (set! front (append (reverse (take front half)) (list x) (drop front half))))
             (let ((half (floor (/ s 2))))
               (set! front (append (reverse (take front half)) (list x) (drop front half))))))
       (set! front (reverse front))
       (rebalance))
     (define/public (pushBack x)
       (set! back (cons x back))
       (rebalance))
     (define/public (popFront)
       (if (zero? (size))
           -1
           (let ((val (car front)))
             (set! front (cdr front))
             (rebalance)
             val)))
     (define/public (popMiddle)
       (if (zero? (size))
           -1
           (let ((s (size)))
             (if (even? s)
                 (let ((half (/ s 2)))
                   (let ((val (list-ref front (- (length front) half) )))
                     (set! front (remove val front #:count 1))
                     (set! front (reverse front))
                     (rebalance)
                     val))
                 (let ((half (floor (/ s 2))))
                   (let ((val (list-ref front (- (length front) (+ half 1)))))
                     (set! front (remove val front #:count 1))
                     (set! front (reverse front))
                     (rebalance)
                     val))))))
     (define/public (popBack)
       (if (zero? (size))
           -1
           (let ((val (car back)))
             (set! back (cdr back))
             (rebalance)
             val)))))