(define (minimum-number-of-removals nums)
  (let* ((n (length nums))
         (inc (make-vector n 1))
         (dec (make-vector n 1)))
    (for ((i (in-range 1 n)))
      (for ((j (in-range 0 i)))
        (when (>= (list-ref nums i) (list-ref nums j))
          (set! (vector-ref inc i) (max (vector-ref inc i) (+ (vector-ref inc j) (if (< (list-ref nums i) (list-ref nums j)) 0 1)))))))
    (for ((i (in-range (- n 2) -1 -1)))
      (for ((j (in-range (+ i 1) n)))
        (when (>= (list-ref nums i) (list-ref nums j))
          (set! (vector-ref dec i) (max (vector-ref dec i) (+ (vector-ref dec j) (if (< (list-ref nums i) (list-ref nums j)) 0 1)))))))
    (let ((max-len 0))
      (for ((i (in-range 0 n)))
        (when (> (vector-ref inc i) 1)
          (when (> (vector-ref dec i) 1)
            (set! max-len (max max-len (+ (vector-ref inc i) (vector-ref dec i) -1)))))
      (- n max-len))))