(define (min-moves nums limit)
  (let* ((n (length nums))
         (diff (make-vector (* 2 limit) 0)))
    (for ([i (in-range (quotient n 2))])
      (let* ((a (list-ref nums i))
             (b (list-ref nums (- n i 1)))
             (lo (+ 1 (min a b)))
             (hi (+ limit (max a b))))
        (vector-set! diff lo (+ (vector-ref diff lo) 1))
        (when (<= hi (- (* 2 limit) 1))
          (vector-set! diff (+ hi 1) (- (vector-ref diff (+ hi 1)) 1)))
        (vector-set! diff (+ a b) (- (vector-ref diff (+ a b)) 1))
        (when (<= (+ a b) (- (* 2 limit) 1))
          (vector-set! diff (+ a b 1) (+ (vector-ref diff (+ a b 1)) 1)))))
    (let loop ([i 1] [curr 0] [ans (quotient n 2)])
      (if (= i (* 2 limit))
          ans
          (let* ((new-curr (+ curr (vector-ref diff i)))
                 (new-ans (min ans (+ (quotient n 2) new-curr))))
            (loop (+ i 1) new-curr new-ans))))))