(define (max-height cuboids)
  (let* ((sorted-cuboids (map sort cuboids))
         (n (length sorted-cuboids))
         (dp (make-vector n 1)))
    (define (can-stack? c1 c2)
      (and (<= (list-ref c1 0) (list-ref c2 0))
           (<= (list-ref c1 1) (list-ref c2 1))
           (<= (list-ref c1 2) (list-ref c2 2))))
    (for ([i (in-range 1 n)])
      (for ([j (in-range 0 i)])
        (when (can-stack? (vector-ref sorted-cuboids j) (vector-ref sorted-cuboids i))
          (vector-set! dp i (max (vector-ref dp i) (+ (vector-ref dp j) 1))))))
    (apply max (map (lambda (i) (* (list-ref (vector-ref sorted-cuboids i) 2) (vector-ref dp i))) (range n)))))