(define (minSwaps k nums)
  (define ones (filter (lambda (x) (= x 1)) (range (length nums))))
  (define m (length ones))
  (if (< m k) 0
      (let* ((medians (for/list ((i (in-range (- m k) 1 -1)))
                         (list-ref ones (+ i (quotient k 2)))))
             (prefix-sum (make-vector (+ m 1) 0)))
        (for ((i (in-range m)))
          (vector-set! prefix-sum (+ i 1) (+ (vector-ref prefix-sum i) (list-ref ones i))))
        (define (cost i)
          (let* ((median (list-ref medians i))
                 (left-start (- median (quotient (- k 1) 2)))
                 (right-end (+ median (quotient k 2))))
            (-
             (if (even? k) 0 (list-ref ones (+ i (quotient k 2))))
             (let ((left-count (quotient k 2)))
               (- (* (+ left-count 1) left-start)
                  (- (vector-ref prefix-sum (+ i (quotient k 2) 1))
                     (vector-ref prefix-sum i))))
             (- (- (vector-ref prefix-sum (+ i k))
                   (vector-ref prefix-sum (+ i (quotient k 2) 1)))
                (* (- k (quotient k 2) -1) (+ left-start 1))))))
        (apply min (for/list ((i (in-range (- m k) 1 -1))) (cost i))))))