(define (min-side-jumps obstacles)
  (define n (vector-length obstacles))
  (define dp (make-vector 3 (lambda (i) (if (= i 1) 0 1))))
  (for ([i (in-range 1 n)])
    (define obs (vector-ref obstacles i))
    (vector-set! dp (- obs 1) #f)
    (for ([j (in-range 3)])
      (when (not (vector-ref dp j))
        (vector-set! dp j 1000000000)))
    (for ([j (in-range 3)])
      (when (vector-ref dp j)
        (for ([k (in-range 3)])
          (when (and (vector-ref dp k) (!= j k))
            (vector-set! dp k (min (vector-ref dp k) (+ 1 (vector-ref dp j))))))))
    )
  (apply min (vector->list dp)))