(define (get-permutation str k)
  (let loop ((str (string->list str)) (k k) (result '()))
    (if (null? str)
        (list->string (reverse result))
        (let* ((n (length str))
               (fact (factorial (- n 1))))
          (let ((index (floor (/ k fact))))
            (loop (remove-nth str index) (remainder k fact) (cons (list-ref str index) result)))))))

(define (factorial n)
  (if (= n 0)
      1
      (* n (factorial (- n 1)))))

(define (remove-nth lst n)
  (cond ((= n 0) (cdr lst))
        (else (cons (car lst) (remove-nth (cdr lst) (- n 1))))))

(define (minimum-swaps str k)
  (let* ((num (string->list str))
         (kth (string->list (get-permutation str k)))
         (swaps 0))
    (let loop ((num num) (kth kth) (swaps swaps))
      (if (null? kth)
          swaps
          (let ((first-kth (car kth)))
            (let ((index (list-index num first-kth)))
              (if (= index 0)
                  (loop (cdr num) (cdr kth) swaps)
                  (let loop2 ((lst num) (i 0) (swaps swaps))
                    (if (= i index)
                        (loop (append (list first-kth) (take lst i) (drop lst (+ i 1))) (cdr kth) (+ swaps index))
                        (loop2 (cdr lst) (+ i 1) swaps)))))))))))

(define (list-index lst val)
  (let loop ((lst lst) (i 0))
    (cond ((null? lst) #f)
          ((equal? (car lst) val) i)
          (else (loop (cdr lst) (+ i 1))))))