(define (max-profit k prices)
  (define n (length prices))
  (if (or (null? prices) (zero? k))
      0
      (if (>= k (/ n 2))
          (let loop ((i 1) (profit 0) (buy 0))
            (if (>= i n)
                profit
                (let ((diff (- (list-ref prices i) (list-ref prices (- i 1)))))
                  (if (> diff 0)
                      (loop (+ i 1) (+ profit diff) buy)
                      (loop (+ i 1) profit buy)))))
          (let ((dp (make-vector (+ k 1) (make-vector 2 0))))
            (for ((i (in-range 1 (+ k 1))))
              (vector-set! (vector-ref dp i) 1 (- (car prices)))
              (vector-set! (vector-ref dp i) 0 0))
            (for ((price (in-list (cdr prices))))
              (for ((i (in-range 1 (+ k 1))))
                (vector-set! (vector-ref dp i) 1 (max (vector-ref (vector-ref dp i) 1) (- price (vector-ref (vector-ref dp (- i 1)) 0))))
                (vector-set! (vector-ref dp i) 0 (max (vector-ref (vector-ref dp i) 0) (+ price (vector-ref (vector-ref dp i) 1))))))
            (vector-ref (vector-ref dp k) 0)))))