(define (areOccurrencesEqual s)
  (let* ((counts (hash))
         (chars (string->list s)))
    (for-each (lambda (c)
                (hash-update! counts c (lambda (k v) (+ v 1)) 1))
              chars)
    (let ((first-count (hash-ref counts (car chars))))
      (for-each (lambda (c)
                  (when (not (= (hash-ref counts c) first-count))
                    (return #f)))
                chars)
      #t)))