(define (minSpaceWastedKResizingOperations nums k)
  (define n (length nums))
  (define dp (make-vector (+ k 1) (make-vector n #inf.0)))
  (vector-set! (vector-ref dp 0) 0 0)

  (for ([i (in-range n)])
    (define max-val (list-ref nums i))
    (define sum-val (list-ref nums i))
    (for ([j (in-range i -1)])
      (set! max-val (max max-val (list-ref nums j)))
      (set! sum-val (+ sum-val (list-ref nums j)))
      (define wasted (* max-val (+ i (- j) 1)) (- sum-val))
      (vector-set! (vector-ref dp 0) i (min (vector-ref (vector-ref dp 0) i) wasted))))

  (for ([i (in-range 1 (+ k 1))])
    (for ([j (in-range n)])
      (for ([l (in-range j)])
        (define max-val (list-ref nums j))
        (define sum-val (list-ref nums j))
        (for ([m (in-range j l -1)])
          (set! max-val (max max-val (list-ref nums m)))
          (set! sum-val (+ sum-val (list-ref nums m)))
          (define wasted (+ (* max-val (+ j (- m) 1)) (- sum-val) (vector-ref (vector-ref dp (- i 1)) (- m 1))))
          (vector-set! (vector-ref dp i) j (min (vector-ref (vector-ref dp i) j) wasted))))))

  (inexact->exact (vector-ref (vector-ref dp k) (- n 1))))