(define (count-highest-score-nodes root)
  (let* ((n (vector-length (vector-ref root 0)))
         (counts (make-vector n 0))
         (max-score (box 0)))

    (define (dfs node)
      (let* ((left (vector-ref root 1 node))
             (right (vector-ref root 2 node))
             (left-count (if (= left -1) 0 (dfs left)))
             (right-count (if (= right -1) 0 (dfs right)))
             (remaining (- n 1 left-count right-count))
             (score (if (= remaining 0) 1 (* (if (= left-count 0) 1 left-count)
                                               (if (= right-count 0) 1 right-count)
                                               (if (= remaining 0) 1 remaining)))))
        (cond
          ((> score (unbox max-score))
           (set-box! max-score score)
           (vector-set! counts 0 1)
           )
          ((= score (unbox max-score))
           (vector-set! counts 0 (+ (vector-ref counts 0) 1)))
          (else #f))
        (+ left-count right-count 1)))

    (dfs 0)
    (vector-ref counts 0)))