(define (good-days-to-rob bank k)
  (let* ((n (length bank))
         (left (make-vector n 0))
         (right (make-vector n 0)))
    (for/fold (prev) ([i (in-range 1 n)]
                     [prev 0])
      (if (<= (list-ref bank (- i 1)) (list-ref bank i))
          (+ prev 1)
          0))
    (for ([i (in-range 1 n)])
      (vector-set! left i (if (<= (list-ref bank (- i 1)) (list-ref bank i))
                              (+ (vector-ref left (- i 1)) 1)
                              0)))
    (for/fold (prev) ([i (in-range (- n 2) -1 -1)]
                     [prev 0])
      (if (<= (list-ref bank (+ i 1)) (list-ref bank i))
          (+ prev 1)
          0))
    (for ([i (in-range (- n 2) -1 -1)])
      (vector-set! right i (if (<= (list-ref bank (+ i 1)) (list-ref bank i))
                               (+ (vector-ref right (+ i 1)) 1)
                               0)))
    (for/list ([i (in-range k (- n k))])
      (if (and (>= (vector-ref left i) k)
               (>= (vector-ref right i) k))
          i
          #f))))