(define (sub-array-ranges nums)
  (let* ((n (length nums))
         (total-sum (box 0)))
    (for* ((i (in-range n))
           (j (in-range i n)))
      (let* ((sub-array (list->vector (take (drop nums i) (- j i 1))))
             (min-val (apply min (vector->list sub-array)))
             (max-val (apply max (vector->list sub-array))))
        (box-set! total-sum (+ (unbox total-sum) (- max-val min-val)))))
    (unbox total-sum)))