(define (divide-string s k fill)
  (let* ((n (string-length s))
         (num-groups (ceiling (/ n k)))
         (result (make-vector num-groups "")))
    (for ((i (in-range num-groups)))
      (let* ((start (* i k))
             (end (min (* (add1 i) k) n))
             (group-str (substring s start end)))
        (if (= (string-length group-str) k)
            (vector-set! result i group-str)
            (let ((padding-needed (- k (string-length group-str))))
              (vector-set! result i (string-append group-str (make-string padding-needed fill)))))))
    (vector->list result)))