(define (minimum-cost cost)
  (let* ((n (length cost))
         (sorted-cost (sort cost >))
         (total-cost 0))
    (for/fold ((i 0) (total-cost 0))
              ((c (in-list sorted-cost)))
      (if (< i n)
          (let ((new-total-cost (+ total-cost c)))
            (if (and (>= (+ i 1) 2) (= (modulo (+ i 1) 3) 0))
                (values (+ i 1) total-cost)
                (values (+ i 1) new-total-cost)))
          (values i total-cost)))))