(define (max-score-indices nums)
  (define n (length nums))
  (define scores (make-vector (+ n 1) 0))
  (define ones (foldl + 0 nums))
  (vector-set! scores 0 ones)
  (for/fold ([zeros 0]) ([i (in-range 0 n)])
    (let ([num (vector-ref nums i)])
      (vector-set! scores (+ i 1) (+ (vector-ref scores i) (- 1 num)))
      (if (= num 0)
          (+ zeros 1)
          zeros)))
  (define max-score (apply max (vector->list scores)))
  (for/list ([i (in-range 0 (+ n 1))]
             #:when (= (vector-ref scores i) max-score))
    i))