(define (cells-in-range s)
  (let* ((c1 (string-ref s 0))
         (r1 (string->number (string (string-ref s 1))))
         (c2 (string-ref s 3))
         (r2 (string->number (string (string-ref s 4))))
         (result '()))
    (for* ((c (in-range (char->integer c1) (+ 1 (char->integer c2))))
           (r (in-range r1 (+ 1 r2))))
      (set! result (cons (string-append (string (integer->char c)) (number->string r)) result)))
    (reverse result)))