(define (minimal-k-sum nums k)
  (let* ((sorted-nums (sort (remove-duplicates nums) <))
         (sum 0)
         (curr 1)
         (i 0))
    (while (and (< i (length sorted-nums)) (> k 0))
      (if (< curr (list-ref sorted-nums i))
          (let ((count (min k (- (list-ref sorted-nums i) curr))))
            (set! sum (+ sum (/ (* (+ curr (- curr 1) count) count) 2)))
            (set! k (- k count))
            (set! curr (+ curr count)))
          (set! curr (+ (list-ref sorted-nums i) 1)))
      (set! i (+ i 1)))
    (if (> k 0)
        (set! sum (+ sum (/ (* (+ curr (- curr 1) k) k) 2))))
    sum))