(define (number-of-ways s)
  (define n (string-length s))
  (define ones-prefix (make-vector (add1 n) 0))
  (define zeros-prefix (make-vector (add1 n) 0))
  (for ([i (in-range 1 (add1 n))])
    (vector-set! ones-prefix i (+ (vector-ref ones-prefix (sub1 i)) (if (char=? (string-ref s (sub1 i)) #\1) 1 0)))
    (vector-set! zeros-prefix i (+ (vector-ref zeros-prefix (sub1 i)) (if (char=? (string-ref s (sub1 i)) #\0) 1 0))))
  (define ans 0)
  (for ([i (in-range 1 (sub1 n))])
    (if (char=? (string-ref s i) #\0)
        (set! ans (+ ans (* (vector-ref ones-prefix i) (- (vector-ref ones-prefix n) (vector-ref ones-prefix (add1 i))))))
        (set! ans (+ ans (* (vector-ref zeros-prefix i) (- (vector-ref zeros-prefix n) (vector-ref zeros-prefix (add1 i))))))))
  ans)