(define (maximum-product-after-k-increments nums k)
  (define h (make-heap <))
  (for-each (lambda (x) (heap-add! h x)) nums)
  (for ([i (in-range k)])
    (define min-val (heap-remove-min! h))
    (heap-add! h (+ min-val 1)))
  (define product 1)
  (define mod (expt 10 9 7))
  (for ([i (in-heap h)])
    (set! product (modulo (* product i) mod)))
  product)