(define stack
  (let ((q1 (make-queue))
        (q2 (make-queue)))
    (define (push x)
      (queue-enqueue! q1 x))
    (define (pop)
      (when (queue-empty? q1)
        (error "Stack is empty"))
      (let loop ()
        (when (= (queue-size q1) 1)
          (let ((result (queue-dequeue! q1)))
            (begin
              (swap! q1 q2)
              result)))
        (queue-enqueue! q2 (queue-dequeue! q1))
        (loop)))
    (define (top)
      (when (queue-empty? q1)
        (error "Stack is empty"))
      (let loop ()
        (when (= (queue-size q1) 1)
          (let ((result (queue-peek q1)))
            result))
        (queue-enqueue! q2 (queue-dequeue! q1))
        (loop)
      (let ()
        (swap! q1 q2))))
    (define (empty?)
      (queue-empty? q1))
    (define (swap! q1 q2)
      (let ((temp q1))
        (set! q1 q2)
        (set! q2 temp)))
    (struct stack-ops (push pop top empty?))
    (stack-ops push pop top empty?)))

(define (make-stack)
  (stack))

(provide make-stack)