(define (count-rectangles rectangles points)
  (define sorted-rects (sort rectangles (lambda (a b) (> (car a) (car b)))))
  (define (count-rect point)
    (define x (car point))
    (define y (cadr point))
    (define count 0)
    (for ([rect sorted-rects])
      (define width (car rect))
      (define height (cadr rect))
      (if (and (>= width x) (>= height y))
          (set! count (+ count 1))
          (if (< width x) (break))))
    count)
  (map count-rect points))