(define (array-replace nums operations)
  (let ([m (make-hash)])
    (for/list ([i (in-range (length nums))])
      (hash-set! m (list-ref nums i) i))
    (for ([op (in-list operations)])
      (let ([index (hash-ref m (first op))])
        (hash-remove! m (first op))
        (hash-set! m (second op) index)
        (list-set! nums index (second op))))
    nums))