(define (min-sum-square-diff nums1 nums2 k1 k2)
  (let* ((diffs (map (lambda (x y) (abs (- x y))) nums1 nums2))
         (counts (make-hash))
         (n (length diffs)))
    (for-each (lambda (x) (hash-update! counts x (lambda (v) (if v (+ v 1) 1)) 0)) diffs)
    (let loop ((k (+ k1 k2)))
      (if (<= k 0)
          (sum (map (lambda (x) (* x x)) diffs))
          (let* ((max-diff (apply max (hash-keys counts)))
                 (count (hash-ref counts max-diff)))
            (if (>= k count)
                (begin
                  (hash-remove! counts max-diff)
                  (if (> max-diff 0)
                      (hash-update! counts (- max-diff 1) (lambda (v) (if v (+ v count) count)) 0))
                  (loop (- k count)))
                (begin
                  (hash-set! counts max-diff (- count k))
                  (if (> max-diff 0)
                      (hash-update! counts (- max-diff 1) (lambda (v) (if v (+ v k) k)) 0))
                  (set! diffs (map (lambda (x) (if (= x max-diff) (- x 1) x)) diffs))
                  (loop 0)))))))
    (sum (map (lambda (x) (* x x)) diffs))))