(define (query-kth-smallest-trimmed-number nums queries)
  (map (lambda (query)
         (let* ((k (car query))
                (trim (cadr query))
                (n (length nums))
                (trimmed-nums (map (lambda (num)
                                     (substring num (- (string-length num) trim) (string-length num)))
                                   nums))
                (indexed-trimmed-nums (map (lambda (i trimmed-num)
                                             (list trimmed-num i))
                                           (range n)
                                           trimmed-nums))
                (sorted-indexed-trimmed-nums (sort indexed-trimmed-nums (lambda (a b)
                                                                          (if (string<? (car a) (car b))
                                                                              #t
                                                                              (and (string=? (car a) (car b))
                                                                                   (< (cadr a) (cadr b))))))))
           (cadr (list-ref sorted-indexed-trimmed-nums (- k 1)))))
       queries))