(define (k-sum nums k)
  (define sorted-nums (sort nums <))
  (define total-sum (apply + sorted-nums))
  (define pq (make-heap (λ (x y) (> (car x) (car y)))))
  (heap-add! pq (list total-sum 0))
  (define result '())
  (for ([i (in-range k)])
    (define current (heap-remove-min! pq))
    (set! result (cons (car current) result))
    (define current-sum (car current))
    (define current-index (cadr current))
    (when (< current-index (sub1 (length sorted-nums)))
      (heap-add! pq (list (- current-sum (list-ref sorted-nums current-index)) (add1 current-index)))
      (heap-add! pq (list (- current-sum (list-ref sorted-nums current-index) (list-ref sorted-nums (add1 current-index)))) (add1 current-index)))))
  (reverse result))

(define (make-heap less-than?)
  (let ([heap (vector)])
    (define (heap-add! val)
      (vector-push-back! heap val)
      (heapify-up! (sub1 (vector-length heap))))
    (define (heap-remove-min!)
      (when (zero? (vector-length heap)) (error "Heap is empty"))
      (define min-val (vector-ref heap 0))
      (vector-swap! heap 0 (sub1 (vector-length heap)))
      (vector-pop-back! heap)
      (when (not (zero? (vector-length heap)))
        (heapify-down! 0))
      min-val)
    (define (heapify-up! i)
      (when (> i 0)
        (define parent (floor (/ (- i 1) 2)))
        (when (less-than? (vector-ref heap i) (vector-ref heap parent))
          (vector-swap! heap i parent)
          (heapify-up! parent))))
    (define (heapify-down! i)
      (define left (+ (* i 2) 1))
      (define right (+ (* i 2) 2))
      (define smallest i)
      (when (< left (vector-length heap))
        (when (less-than? (vector-ref heap left) (vector-ref heap smallest))
          (set! smallest left)))
      (when (< right (vector-length heap))
        (when (less-than? (vector-ref heap right) (vector-ref heap smallest))
          (set! smallest right)))
      (when (not (= smallest i))
        (vector-swap! heap i smallest)
        (heapify-down! smallest)))
    (define (empty?)
      (zero? (vector-length heap)))
    (struct heap-methods (add! remove-min! empty?))
    (heap-methods heap-add! heap-remove-min! empty?)))