(define (diff-ways-to-compute expr)
  (define (helper s)
    (let loop ((i 0) (res '()))
      (if (= i (string-length s))
          (if (empty? res)
              (list (string->number s))
              res)
          (let ((c (string-ref s i)))
            (if (or (char=? c '+') (char=? c '-') (char=? c '*'))
                (let ((left (helper (substring s 0 i)))
                      (right (helper (substring s (+ i 1)))))
                  (append! res
                           (for*/list ((l left) (r right))
                             (cond
                               ((char=? c '+') (+ l r))
                               ((char=? c '-') (- l r))
                               ((char=? c '*') (* l r))))))
                (loop (+ i 1) res))))))
  (helper expr))