(define (smallest-subarrays nums)
  (let* ((n (length nums))
         (ans (make-vector n 1))
         (last (make-vector 32 -1)))
    (for/list ((i (in-range n)))
      (for/list ((j (in-range 32)))
        (when (bitwise-bit-set? (vector-ref nums i) j)
          (vector-set! last j i)))
      (let ((rightmost (for/fold (max 0) ((j (in-range 32)))
                         (max rightmost (vector-ref last j)))))
        (vector-set! ans i (+ 1 (- rightmost i)))))
    (vector->list ans)))