(define (reverse-odd-levels root)
  (letrec (
    (reverse-levels (node level)
      (if (null? node)
        '()
        (cons (list node level) (append (reverse-levels (car node) (+ level 1)) (reverse-levels (cdr node) (+ level 1))))
      )
    )
    (build-tree (levels)
      (let* (
        (odd-levels (filter (lambda (level) (odd? (cadr level))) levels))
        (values (map car odd-levels))
        (reversed-values (reverse values))
      )
        (for ([level-info levels] [reversed-value reversed-values])
          (when (odd? (cadr level-info))
            (set! (car level-info) (car reversed-value)))
        )
        (levels)
      )
    )
    (rebuild-tree (levels))

    (rebuild-tree (levels)
      (for/list ([level levels])
        (car level))
    )

    (rebuild-levels (node level)
      (if (null? node)
        '()
        (cons (list node level) (append (rebuild-levels (car node) (+ level 1)) (rebuild-levels (cdr node) (+ level 1))))
      )
    )

    (rebuild-tree (levels))

    (apply-changes (levels))
    (apply-changes (levels)
      (for/list ([level levels])
        (car level)))
    )
    (let* (
      (levels (reverse-levels root 0))
      (odd-levels (filter (lambda (level) (odd? (cadr level))) levels))
      (values (map car odd-levels))
      (reversed-values (reverse values))
      (new-levels (for/list ([level-info levels] [reversed-value (in-cycle reversed-values)])
          (if (odd? (cadr level-info))
            (list reversed-value (cadr level-info))
            level-info)))
      (result (rebuild-tree new-levels)))
      (if (null? root)
        root
        (letrec (
          (build (nodes levels)
            (if (null? nodes)
              null
              (let ((node (car nodes)))
                (cond
                  [(null? node) null]
                  [else
                   (set-car! node (build (filter (lambda (level) (and (= (cadr level) (+ 1 (cadr (assoc node levels))) ) (= (car level) (car node)))) levels) levels))
                   (set-cdr! node (build (filter (lambda (level) (and (= (cadr level) (+ 1 (cadr (assoc node levels))) ) (= (car level) (cdr node)))) levels) levels))
                   node])))
            )))
            (let* ((levels (reverse-levels root 0))
                   (odd-levels (filter (lambda (level) (odd? (cadr level))) levels))
                   (values (map car odd-levels))
                   (reversed-values (reverse values))
                   (new-levels (map (lambda (level reversed-value)
                                       (if (odd? (cadr level))
                                           (set-car! level reversed-value)
                                           level))
                                     levels reversed-values))
                   (node-levels (map (lambda (level) (cons (car level) (cadr level))) levels))
                   (result (build (list root) node-levels)))
              root))))