(define (max-hourglass-sum grid)
  (let* ((rows (length grid))
         (cols (length (car grid)))
         (max-sum (if (and (>= rows 3) (>= cols 3)) (-inf) 0)))
    (for ([i (in-range (- rows 2))])
      (for ([j (in-range (- cols 2))])
        (let* ((sum (+ (list-ref (list-ref grid i) j)
                       (list-ref (list-ref grid i) (+ j 1))
                       (list-ref (list-ref grid i) (+ j 2))
                       (list-ref (list-ref grid (+ i 1)) (+ j 1))
                       (list-ref (list-ref grid (+ i 2)) j)
                       (list-ref (list-ref grid (+ i 2)) (+ j 1))
                       (list-ref (list-ref grid (+ i 2)) (+ j 2)))))
          (set! max-sum (max max-sum sum)))))
    max-sum))