(define (destroySequentialTargets nums space)
  (let* ((remainders (make-hash))
         (result 0))
    (for-each (lambda (num)
                (let ((remainder (modulo num space)))
                  (unless (hash-has-key? remainders remainder)
                    (hash-set! remainders remainder (list num)))))
              nums)
    (let loop ((keys (hash-keys remainders)))
      (if (null? keys)
          result
          (let ((key (car keys))
                (values (hash-ref remainders key)))
            (if (> (length values) result)
                (loop (cdr keys) (length values))
                (loop (cdr keys) result)))))))