(define (distinct-averages nums)
  (let* ((sorted-nums (sort nums <))
         (n (length sorted-nums))
         (seen (make-hash)))
    (let loop ((left 0) (right (- n 1)))
      (if (> left right)
          (hash-count seen)
          (let* ((num1 (list-ref sorted-nums left))
                 (num2 (list-ref sorted-nums right))
                 (avg (/ (+ num1 num2) 2)))
            (hash-set! seen avg #t)
            (loop (+ left 1) (- right 1)))))))