(define (maximum-tastiness price tastiness k)
  (let* ((candies (map list price tastiness))
         (sorted-candies (sort candies (lambda (x y) (< (car x) (car y))))))
    (define (check tastiness-threshold)
      (let loop ((count 1)
                 (last-price (caar sorted-candies))
                 (remaining-candies (cdr sorted-candies)))
        (cond
          ((>= count k) #t)
          ((null? remaining-candies) #f)
          (else
           (let ((current-candy (car remaining-candies)))
             (if (>= (- (car current-candy) last-price) tastiness-threshold)
                 (loop (+ count 1) (car current-candy) (cdr remaining-candies))
                 (loop count last-price (cdr remaining-candies))))))))

    (let loop ((left 0)
               (right (apply max price)))
      (if (<= left right)
          (let ((mid (floor (+ left right) 2)))
            (if (check mid)
                (loop (+ mid 1) right)
                (loop left (- mid 1))))
          right))))