(define (left-right-difference nums)
  (let* ((n (length nums))
         (left-sum (make-vector n 0))
         (right-sum (make-vector n 0))
         (result (make-vector n 0)))
    (for ((i (in-range 1 n)))
      (vector-set! left-sum i (+ (vector-ref left-sum (- i 1)) (vector-ref nums (- i 1)))))
    (for ((i (in-range (- n 2) -1 -1)))
      (vector-set! right-sum i (+ (vector-ref right-sum (+ i 1)) (vector-ref nums (+ i 1)))))
    (for ((i (in-range n)))
      (vector-set! result i (abs (- (vector-ref left-sum i) (vector-ref right-sum i)))))
    (vector->list result)))