(define (number-of-ways target types)
  (define n (length types))
  (define dp (make-vector (+ target 1) 0))
  (vector-set! dp 0 1)
  (for ([i (in-range n)])
    (define count (list-ref types i))
    (define marks (list-ref types i))
    (for ([j (in-range marks 1 (+ marks 1))])
      (for ([k (in-range j (+ target 1))] #:when (>= k j))
        (vector-set! dp k (+ (vector-ref dp k) (vector-ref dp (- k j)))))))
  (vector-ref dp target))