(define (max-cost-substring s chars costs)
  (define char-cost (make-hash))
  (for ([i (in-range (length chars))])
    (hash-set! char-cost (string-ref chars i) (list-ref costs i)))
  (define (get-cost c)
    (if (hash-has-key? char-cost c)
        (hash-ref char-cost c)
        (- (char->integer c) (char->integer #\a) 0)))
  (define (max-subarray arr)
    (define (helper arr current-max max-so-far)
      (cond [(empty? arr) max-so-far]
            [else (let ([new-current-max (max 0 (+ current-max (car arr)))])
                    (helper (cdr arr) new-current-max (max max-so-far new-current-max)))]))
    (helper arr 0 0))
  (max-subarray (map get-cost (string->list s))))