(define (nth-ugly-number n)
  (define ugly-numbers (make-vector n 0))
  (vector-set! ugly-numbers 0 1)
  (define i2 0)
  (define i3 0)
  (define i5 0)
  (for ([i (in-range 1 n)])
    (define next-multiple-of-2 (* 2 (vector-ref ugly-numbers i2)))
    (define next-multiple-of-3 (* 3 (vector-ref ugly-numbers i3)))
    (define next-multiple-of-5 (* 5 (vector-ref ugly-numbers i5)))
    (define next-ugly-no (min next-multiple-of-2 next-multiple-of-3 next-multiple-of-5))
    (vector-set! ugly-numbers i next-ugly-no)
    (when (= next-ugly-no next-multiple-of-2) (set! i2 (+ i2 1)))
    (when (= next-ugly-no next-multiple-of-3) (set! i3 (+ i3 1)))
    (when (= next-ugly-no next-multiple-of-5) (set! i5 (+ i5 1))))
  (vector-ref ugly-numbers (- n 1)))