(define (sliding-subarray-beauty nums k x)
  (let* ((n (length nums))
         (result '()))
    (for ((i (in-range (- n k) 1)))
      (let* ((subarray (take (drop nums i) k))
             (negatives (filter (lambda (num) (< num 0)) subarray))
             (sorted-negatives (sort negatives <))
             (beauty (if (>= (length sorted-negatives) x)
                         (list-ref sorted-negatives (- x 1))
                         0)))
        (set! result (append result (list beauty)))))
    result))