(define (count-adjacent-same-color n queries)
  (let* ((colors (make-vector n 0))
         (result (list)))
    (for ([query queries])
      (let* ((index (car query))
             (color (cadr query))
             (prev-color (vector-ref colors index)))
        (vector-set! colors index color)
        (let ((count (let loop ([i 0] [c 0])
                       (cond
                         ((= i (- n 1)) c)
                         ((= (vector-ref colors i) (vector-ref colors (+ i 1))) (loop (+ i 1) (+ c 1)))
                         (else (loop (+ i 1) c))))))
          (set! result (cons count result)))))
    (reverse result)))