(define (maximum-sum-queries nums1 nums2 queries)
  (define n (length nums1))
  (define pairs (sort (for/list ([i (in-range n)]) (list (list-ref nums1 i) (list-ref nums2 i))) > #:key car))
  (define ans (make-vector (length queries) -1))
  (define sorted-queries (sort (for/list ([i (in-range (length queries))]) (list (list-ref queries i 0) (list-ref queries i 1) i)) > #:key car))
  (define stack '())
  (define j 0)
  (for ([q (in-list sorted-queries)])
    (define x (car q))
    (define y (list-ref q 1))
    (define idx (list-ref q 2))
    (begin
      (for ([i (in-range j n)])
        (define p (list-ref pairs i))
        (define a (car p))
        (define b (cadr p))
        (when (>= a x)
          (begin
            (define sum (+ a b))
            (define to-remove '())
            (for ([s (in-list stack)])
              (define sa (car s))
              (define sb (cadr s))
              (when (and (>= sb b) (<= (+ sa sb) sum))
                (set! to-remove (cons s to-remove))))
            (for ([r (in-list to-remove)])
              (set! stack (remove r stack)))
            (set! stack (cons (list a b) stack))
            (set! j (+ i 1))))
        (unless (>= a x) (break)))

      (define max-sum -1)
      (for ([s (in-list stack)])
        (define sa (car s))
        (define sb (cadr s))
        (when (>= sb y)
          (set! max-sum (max max-sum (+ sa sb)))))
      (vector-set! ans idx max-sum)))
  (vector->list ans))