(define (h-index citations)
  (define n (length citations))
  (define (count-at-least k)
    (length (filter (lambda (c) (>= c k)) citations)))
  (let loop ((h 0))
    (if (>= h n)
        (if (>= (count-at-least n) n) n h)
        (if (>= (count-at-least (+ h 1)) (+ h 1))
            (loop (+ h 1))
            h))))