(define (maximum-number-of-string-pairs words)
  (let ((count 0)
        (seen (make-hash)))
    (for ([word words])
      (let ((reversed-word (list->string (reverse (string->list word)))))
        (when (hash-has-key? seen reversed-word)
          (set! count (+ count 1))
          (hash-remove! seen reversed-word))
        (unless (hash-has-key? seen word)
          (hash-set! seen word #t))))
    count))