(define (count-complete-subarrays nums)
  (define n (length nums))
  (define distinct-count (length (remove-duplicates nums)))
  (define count 0)
  (for ([i (in-range n)])
    (define current-distinct-count 0)
    (define seen (make-hash))
    (for ([j (in-range i n)])
      (let ([num (list-ref nums j)])
        (unless (hash-has-key? seen num)
          (hash-set! seen num #t)
          (set! current-distinct-count (+ current-distinct-count 1))))
      (when (= current-distinct-count distinct-count)
        (set! count (+ count 1)))))
  count)