(define (minimumSeconds arr)
  (let* ((n (length arr))
         (pos-map (make-hash))
         (max-freq 0))
    (for/list ((i (in-range n)))
      (let ((num (list-ref arr i)))
        (hash-update! pos-map num (λ (v) (cons i v)) '()))))

    (for/list ((num (hash-keys pos-map)))
      (let* ((pos-list (hash-ref pos-map num))
             (freq (length pos-list))
             (max-dist 0))
        (for/list ((i (in-range freq)))
          (let* ((curr-pos (list-ref pos-list i))
                 (next-pos (list-ref pos-list (modulo (+ i 1) freq)))
                 (dist (if (< next-pos curr-pos)
                           (+ next-pos (- n curr-pos))
                           (- next-pos curr-pos))))
            (set! max-dist (max max-dist dist))))
        (set! max-freq (max max-freq (ceiling (/ max-dist 2))))))

    max-freq))