(define (minimum-edge-weight-equilibrium-queries queries edges n)
  (define adj (make-vector (add1 n) '()))
  (for-each (lambda (e)
              (let ((u (car e)) (v (cadr e)) (w (caddr e)))
                (vector-set! adj u (cons (list v w) (vector-ref adj u)))
                (vector-set! adj v (cons (list u w) (vector-ref adj v)))))
            edges)

  (define parent (make-vector (add1 n) 0))
  (define depth (make-vector (add1 n) 0))
  (define weight (make-vector (add1 n) 0))
  (define visited (make-vector (add1 n) #f))

  (define (dfs u d p w)
    (vector-set! visited u #t)
    (vector-set! depth u d)
    (vector-set! parent u p)
    (vector-set! weight u w)
    (for-each (lambda (neighbor)
                (let ((v (car neighbor)) (w (cadr neighbor)))
                  (if (not (vector-ref visited v))
                      (dfs v (add1 d) u w))))
              (vector-ref adj u)))

  (dfs 1 0 0 0)

  (define (lca u v)
    (define (up u v)
      (let ((du (vector-ref depth u)) (dv (vector-ref depth v)))
        (if (> du dv)
            (up (vector-ref parent u) v)
            (if (< du dv)
                (up u (vector-ref parent v))
                (if (eqv? u v)
                    u
                    (up (vector-ref parent u) (vector-ref parent v)))))))
    (up u v))

  (define (path-weights u v)
    (let ((l (lca u v)))
      (define (get-weights node target)
        (if (eqv? node target)
            '()
            (cons (vector-ref weight node) (get-weights (vector-ref parent node) target))))
      (append (get-weights u l) (get-weights v l))))

  (map (lambda (q)
         (let ((u (car q)) (v (cadr q)))
           (let ((w (path-weights u v)))
             (if (null? w)
                 0
                 (let ((counts (make-hash)))
                   (for-each (lambda (x)
                               (hash-update! counts x (lambda (y) (add1 y)) 1))
                             w)
                   (let ((max-count 0) (total-weight (length w)))
                     (hash-for-each counts (lambda (k v) (if (> v max-count) (set! max-count v))))
                     (- total-weight max-count))))))))
       queries))