(define (min-array-length arr)
  (let* ((n (length arr))
         (counts (make-hash))
         (max-count 0))
    (for-each (lambda (x)
                (let ((count (hash-ref counts x 0)))
                  (hash-set! counts x (+ count 1))
                  (set! max-count (max max-count (+ count 1)))))
              arr)
    (if (> max-count (/ n 2))
        (- (* 2 max-count) n)
        (modulo n 2))))