(define (count-paths n edges values)
  (define adj (make-vector (add1 n) '()))
  (for-each (lambda (edge)
              (let ((u (first edge))
                    (v (second edge)))
                (vector-set! adj u (cons v (vector-ref adj u)))
                (vector-set! adj v (cons u (vector-ref adj v)))))
            edges)

  (define (dfs u parent max-val)
    (let* ((current-val (vector-ref values (sub1 u)))
           (new-max-val (max max-val current-val))
           (count (if (>= current-val max-val) 1 0))
           (children (filter (lambda (v) (not (equal? v parent))) (vector-ref adj u))))
      (for-each (lambda (v)
                  (set! count (+ count (dfs v u new-max-val))))
                children)
      count))

  (let loop ((root 1) (total 0))
    (if (> root n)
        total
        (loop (add1 root) (+ total (dfs root -1 0)))))
  )