(define (drop-duplicate-rows df)
  (define seen (make-hash))
  (define result '())
  (for ([row df])
       (let ([row-str (string-join (map (lambda (x) (if (number? x) (number->string x) x)) row) ",")])
            (unless (hash-ref seen row-str #f)
              (hash-set! seen row-str #t)
              (set! result (cons row result)))))
  (reverse result))