(define (rename-columns data columns)
  (let ((dt (table-from-list (cdr data) #:header (car data))))
    (define new-header (map (lambda (old new)
                               (if (string? old)
                                   (string->symbol new)
                                   (error "Old column name must be a string")))
                             (table-header dt)
                             columns))
    (table-header-set! dt new-header)
    (cons (map symbol->string (table-header dt))
          (table->list dt))))