(define (difference n m)
  (let loop ([i 1] [divisible-sum 0] [non-divisible-sum 0])
    (if (> i n)
        (- non-divisible-sum divisible-sum)
        (loop (+ i 1)
              (if (zero? (modulo i m))
                  (+ divisible-sum i)
                  divisible-sum)
              (if (not (zero? (modulo i m)))
                  (+ non-divisible-sum i)
                  non-divisible-sum)))))