(define (minimum-processing-time processorTime tasks)
  (define sorted-processorTime (sort processorTime <))
  (define sorted-tasks (sort tasks >))
  (define n (length processorTime))
  (define m (length tasks))
  (define (helper i j acc)
    (if (= i n)
        acc
        (let ([max-time (apply max (list (+ (list-ref sorted-processorTime i) (list-ref sorted-tasks (+ j 0)))
                                         (+ (list-ref sorted-processorTime i) (list-ref sorted-tasks (+ j 1)))
                                         (+ (list-ref sorted-processorTime i) (list-ref sorted-tasks (+ j 2)))
                                         (+ (list-ref sorted-processorTime i) (list-ref sorted-tasks (+ j 3))))])
          (helper (+ i 1) (+ j 4) (max acc max-time)))))
  (helper 0 0 0))