(define (maximumSumOfSquares ops nums k)
  (define n (length nums))
  (define ones (make-vector 30 0))
  (for ([num nums])
    (for ([i (in-range 30)])
      (when (bitwise-bit-set? num i)
        (vector-set! ones i (+ (vector-ref ones i) 1)))))
  (define result 0)
  (for ([i (in-range k)])
    (define current 0)
    (for ([j (in-range 30)])
      (when (> (vector-ref ones j) 0)
        (set! current (bitwise-ior current (arithmetic-shift 1 j)))
        (vector-set! ones j (- (vector-ref ones j) 1))))
    (set! result (+ result (* current current))))
  result)