(define (find-indices nums indexDifference valueDifference)
  (let loop ([i 0])
    (if (= i (length nums))
        '(-1 -1)
        (let loop2 ([j 0])
          (if (= j (length nums))
              (loop (+ i 1))
              (if (and (<= (abs (- i j)) indexDifference)
                       (<= (abs (- (list-ref nums i) (list-ref nums j))) valueDifference))
                  (list i j)
                  (loop2 (+ j 1)))))))
  )