(define (product-except-self nums)
  (let* ((n (length nums))
         (prefix (make-vector n 1))
         (suffix (make-vector n 1))
         (result (make-vector n 1)))
    (for ((i (in-range 1 n)))
      (vector-set! prefix i (* (vector-ref prefix (- i 1)) (list-ref nums (- i 1)))))
    (for ((i (in-range (- n 2) -1 -1)))
      (vector-set! suffix i (* (vector-ref suffix (+ i 1)) (list-ref nums (+ i 1)))))
    (for ((i (in-range n)))
      (vector-set! result i (* (if (= i 0) 1 (vector-ref prefix (- i 1)))
                                (if (= i (- n 1)) 1 (vector-ref suffix (+ i 1))))))
    (vector->list result)))