(define (minimum-sum-mountain-triplet nums)
  (let* ((n (length nums))
         (min-sum #f))
    (for* ((i (in-range 0 (- n 2)))
           (j (in-range (+ i 1) (- n 1)))
           (k (in-range (+ j 1) n))
           #:when (and (< (list-ref nums i) (list-ref nums j))
                       (> (list-ref nums k) (list-ref nums j))))
      (let ((current-sum (+ (list-ref nums i) (list-ref nums j) (list-ref nums k))))
        (set! min-sum (if min-sum (min min-sum current-sum) current-sum))))
    (if min-sum min-sum -1)))