(define (find-k-or nums k)
  (define n (length nums))
  (define result 0)
  (for ([i (in-range 31)])
    (define count 0)
    (for ([num (in-list nums)])
      (if (positive? (bitwise-and num (arithmetic-shift 1 i)))
          (set! count (+ count 1))))
    (if (>= count k)
        (set! result (+ result (arithmetic-shift 1 i)))))
  result)