(define (minimum-increment-operations nums k)
  (let* ((n (length nums))
         (dp (make-vector (add1 n) 0)))
    (for/fold ((i 1))
              ((num (in-list nums)))
      (let ((dp_i-1 (vector-ref dp (sub1 i))))
        (vector-set! dp i dp_i-1)
        (when (>= i 3)
          (vector-set! dp i (min (vector-ref dp i) (+ (vector-ref dp (- i 3)) (max 0 (- k (apply max (list (list-ref nums (- i 1)) (list-ref nums (- i 2)) (list-ref nums (- i 3))))))))))
        (add1 i)))
    (vector-ref dp n)))