(define (minimum-coins fruits)
  (let* ((n (length fruits))
         (dp (make-vector (add1 n) 0)))
    (for ((i (in-range (sub1 n) -1 -1)))
      (vector-set! dp i (min (+ (vector-ref fruits i) (vector-ref dp (add1 i)))
                             (if (>= (+ i (add1 i)) n)
                                 (vector-ref fruits i)
                                 (+ (vector-ref fruits i) (vector-ref dp (+ i (add1 i)))))))
    (vector-ref dp 0)))