(define (count-the-number-of-good-partitions nums)
  (define n (length nums))
  (define last-occurrence (make-hash))
  (for/list ([i (in-range n)])
    (hash-set! last-occurrence (list-ref nums i) i))
  (define (solve)
    (define-values (partitions max-index)
      (let loop ([i 0] [max-reach 0] [count 0])
        (if (= i n)
            (values count max-reach)
            (let ([current-max (hash-ref last-occurrence (list-ref nums i))])
              (if (> current-max max-reach)
                  (loop (+ i 1) current-max count)
                  (if (= i max-reach)
                      (loop (+ i 1) max-reach (+ count 1))
                      (loop (+ i 1) max-reach count)))))))
    (define num-partitions partitions)
    (if (= num-partitions 0)
        0
        (modulo (expt 2 (- num-partitions 1)) 1000000007)))
  (solve))