(define (find-substring s words)
  (define n (string-length s))
  (define num-words (length words))
  (if (or (zero? n) (zero? num-words))
      '()
      (let* ((word-length (string-length (car words)))
             (total-length (* num-words word-length))
             (result '()))
        (if (> total-length n)
            '()
            (let loop ((i 0))
              (if (>= i (- n total-length -1))
                  result
                  (let* ((seen (make-hash))
                         (match #t))
                    (let check-words ((j 0))
                      (if (not match)
                          #f
                          (if (= j num-words)
                              (begin
                                (set! result (append result (list i)))
                                #t)
                              (let* ((start (+ i (* j word-length)))
                                     (sub (substring s start (+ start word-length))))
                                (if (not (member sub words))
                                    (set! match #f)
                                    (let ((count (hash-ref seen sub 0)))
                                      (if (> (+ count 1) (count-occurrences sub words))
                                          (set! match #f)
                                          (begin
                                            (hash-set! seen sub (+ count 1))
                                            (check-words (+ j 1)))))))))))
                    (loop (+ i 1)))))))))

(define (count-occurrences word words)
  (foldl (lambda (w acc) (if (equal? w word) (+ acc 1) acc)) 0 words))