(define (NumArray nums)
  (let* ((n (length nums))
         (sums (make-vector (+ n 1) 0)))
    (for/fold ((i 1))
              ((num (in-list nums)))
      (vector-set! sums i (+ (vector-ref sums (- i 1)) num))
      (+ i 1))
    (λ (i j)
      (- (vector-ref sums (+ j 1)) (vector-ref sums i)))))