(define (numSubmatrixSumTarget matrix k)
  (define rows (length matrix))
  (define cols (length (car matrix)))
  (define prefix-sum (make-matrix (+ rows 1) (+ cols 1) 0))
  (for ([i (in-range rows)])
    (for ([j (in-range cols)])
      (matrix-set! prefix-sum (+ i 1) (+ j 1) (+ (list-ref (list-ref matrix i) j)
                                                 (matrix-ref prefix-sum i (+ j 1))
                                                 (matrix-ref prefix-sum (+ i 1) j)
                                                 (- (matrix-ref prefix-sum i j))))))
  (define count (box 0))
  (for ([r1 (in-range rows)])
    (for ([c1 (in-range cols)])
      (for ([r2 (in-range r1 rows)])
        (for ([c2 (in-range c1 cols)])
          (define sum (- (matrix-ref prefix-sum (+ r2 1) (+ c2 1))
                         (matrix-ref prefix-sum r1 (+ c2 1))
                         (matrix-ref prefix-sum (+ r2 1) c1)
                         (- (matrix-ref prefix-sum r1 c1))))
          (when (< sum k)
            (set-box! count (+ 1 (unbox count))))))))
  (unbox count))