(define (find-median-of-uniqueness-array arr)
  (let* ((unique-arr (remove-duplicates arr))
         (n (length unique-arr)))
    (if (odd? n)
        (list-ref (sort unique-arr <) (quotient n 2))
        (let ((mid (quotient n 2)))
          (/ (+ (list-ref (sort unique-arr <) (- mid 1))
                (list-ref (sort unique-arr <) mid))
             2.0)))))