(define (closest-subarray-bitwise-or nums k)
  (define n (length nums))
  (define (abs-diff x) (abs (- x k)))
  (define (solve)
    (let loop ((i 0) (min-diff +inf) (result 0))
      (if (= i n)
          result
          (let loop2 ((j i) (curr-or 0))
            (if (= j n)
                (loop (+ i 1) min-diff result)
                (let ((new-or (bitwise-ior curr-or (list-ref nums j))))
                  (let ((diff (abs-diff new-or)))
                    (if (< diff min-diff)
                        (loop (+ i 1) diff new-or)
                        (if (= diff min-diff)
                            (loop (+ i 1) min-diff (min result new-or))
                            (loop2 (+ j 1) new-or))))))))))
  (solve))