(define (longest-valid-parentheses s)
  (let* ([n (string-length s)]
         [dp (make-vector (add1 n) 0)])
    (for/fold ([i 1] [result 0])
              ([i (in-range 1 (add1 n))])
      (let ([char (string-ref s (sub1 i))])
        (if (char=? char #\))
            (let ([prev (- i (vector-ref dp (sub1 i)) 1)])
              (if (and (>= prev 0) (char=? (string-ref s prev) #\())
                  (let ([curr-len (+ 2 (vector-ref dp (sub1 i)) (if (>= (+ 1 prev) 0) (vector-ref dp prev) 0))])
                    (vector-set! dp i curr-len)
                    (values (add1 i) (max result curr-len)))
                  (values (add1 i) result)))
            (values (add1 i) result))))))