(define (count-range-sum nums lower upper)
  (define (merge-sort arr)
    (if (<= (length arr) 1)
        arr
        (let* ((mid (quotient (length arr) 2))
               (left (subvector arr 0 mid))
               (right (subvector arr mid (length arr)))
               (sorted-left (merge-sort left))
               (sorted-right (merge-sort right))
               (merged (vector)))
          (let loop ((l 0) (r 0) (m 0))
            (cond
              ((= l (vector-length sorted-left))
               (for ((i r (+ r (- (vector-length sorted-right) r))))
                 (vector-set! merged m (vector-ref sorted-right i))
                 (set! m (+ m 1))))
              ((= r (vector-length sorted-right))
               (for ((i l (+ l (- (vector-length sorted-left) l))))
                 (vector-set! merged m (vector-ref sorted-left i))
                 (set! m (+ m 1))))
              ((<= (vector-ref sorted-left l) (vector-ref sorted-right r))
               (vector-set! merged m (vector-ref sorted-left l))
               (loop (+ l 1) r (+ m 1)))
              (else
               (vector-set! merged m (vector-ref sorted-right r))
               (loop l (+ r 1) (+ m 1)))))
          merged)))

  (define (count-split-inv arr lower upper)
    (if (<= (length arr) 1)
        0
        (let* ((mid (quotient (length arr) 2))
               (left (subvector arr 0 mid))
               (right (subvector arr mid (length arr)))
               (count-left (count-split-inv left lower upper))
               (count-right (count-split-inv right lower upper))
               (sorted-left (merge-sort left))
               (sorted-right (merge-sort right)))
          (let loop ((i 0) (j 0) (k 0) (count 0))
            (if (= i (vector-length sorted-left))
                count
                (begin
                  (let next-j ((j j))
                    (if (and (< j (vector-length sorted-right))
                             (<= (- (vector-ref sorted-right j) (vector-ref sorted-left i)) upper))
                        (next-j (+ j 1))
                        (let next-k ((k k))
                          (if (and (< k (vector-length sorted-right))
                                   (< (- (vector-ref sorted-right k) (vector-ref sorted-left i)) lower))
                              (next-k (+ k 1))
                              (loop (+ i 1) j k (+ count (- j k))))))))))))

  (let* ((sums (vector 0))
         (n (length nums)))
    (for ((i 0 n))
      (vector-set! sums (+ i 1) (+ (vector-ref sums i) (list-ref nums i))))
    (count-split-inv (subvector sums 0 (vector-length sums)) lower upper)))