(define (count-balanced-permutations n)
  (let ((memo (make-hash)))
    (define (factorial x)
      (if (= x 0)
          1
          (* x (factorial (- x 1)))))
    (define (dp mask)
      (cond
        ((= mask (expt 2 n) -1) 1)
        ((hash-has-key? memo mask) (hash-ref memo mask))
        (else
         (let ((count 0))
           (for ((i (in-range n)))
             (when (zero? (bitwise-and mask (expt 2 i)))
               (let ((new-mask (bitwise-ior mask (expt 2 i))))
                 (for ((j (in-range n)))
                   (when (and (zero? (bitwise-and new-mask (expt 2 j)))
                              (not (= i j)))
                     (let ((new-mask2 (bitwise-ior new-mask (expt 2 j))))
                       (when (= (abs (- i j)) 1)
                         (set! count (+ count (dp new-mask2))))))))))
           (hash-set! memo mask count)
           count))))
    (dp 0)))