(define (max-total-fruits fruits start-pos k)
  (define (solve l r)
    (let ((total-distance (+ (abs (- (car (list-ref fruits l)) start-pos))
                               (abs (- (car (list-ref fruits r)) start-pos))
                               (- (abs (- (car (list-ref fruits l)) start-pos))
                                  (min (abs (- (car (list-ref fruits l)) start-pos))
                                       (abs (- (car (list-ref fruits r)) start-pos)))))))
      (if (<= total-distance k)
          (foldr + 0 (map cdr (list-ref (list fruits) (range l (+ r 1)))))
          0)))

  (let* ((n (length fruits))
         (max-fruits 0))
    (for*/fold ((max-fruits max-fruits))
               ((i (in-range n)))
      (for*/fold ((max-fruits max-fruits))
                 ((j (in-range i n)))
        (let ((current-fruits (solve i j)))
          (max max-fruits current-fruits))))))