(define (diagonal-sort matrix)
  (let* ((m (length matrix))
         (n (length (car matrix)))
         (diagonals (make-hash)))
    (for ([i (in-range m)])
      (for ([j (in-range n)])
        (let ((diagonal-index (- i j)))
          (hash-update! diagonals diagonal-index (lambda (v) (cons (list i j) v)) '()))))
    (for ([diagonal-index (in-list (hash-keys diagonals))])
      (let* ((coords (hash-ref diagonals diagonal-index))
             (values (sort (map (lambda (coord) (list-ref (list-ref matrix (car coord)) (cadr coord))) coords) <))
             (sorted-coords (sort coords (lambda (a b) (< (list-ref a 0) (list-ref b 0))))))
        (for ([i (in-range (length sorted-coords))])
          (let* ((coord (list-ref sorted-coords i))
                 (row (car coord))
                 (col (cadr coord))
                 (value (list-ref values i)))
            (set! (list-ref (list-ref matrix row) col) value)))))
    matrix))