(define (count-substrings-divisible-by-last-digit s)
  (let* ((n (string-length s))
         (result 0))
    (for* ((i (in-range n))
           (j (in-range i n)))
      (let* ((sub (substring s i (+ j 1)))
             (last-digit (string->number (substring s j (+ j 1))))
             (sub-num (string->number sub)))
        (when (and (> (string-length sub) 0)
                   (not (zero? last-digit))
                   (zero? (modulo sub-num last-digit)))
          (set! result (+ result 1)))))
    result))