(define (longest-common-prefix strs)
  (if (null? strs)
      ""
      (let loop ([i 0])
        (if (or (null? (car strs))
                (>= i (string-length (car strs))))
            (substring (car strs) 0 i)
            (let ([char (string-ref (car strs) i)])
              (if (andmap (lambda (str)
                             (and (< i (string-length str))
                                  (char=? char (string-ref str i))))
                           strs)
                  (loop (+ i 1))
                  (substring (car strs) 0 i)))))))

(define (solve strs k)
  (let ([n (length strs)])
    (if (or (null? strs) (= n 0) (<= k 0) (> k n))
        ""
        (let loop ([prefix ""])
          (define lcp (longest-common-prefix strs))
          (if (string=? lcp "")
              ""
              (let ([len (string-length lcp)])
                (let ([max-len 0])
                  (for ([i (in-range len 1 (add1 len))])
                    (let ([sub (substring lcp 0 i)])
                      (let ([count (count (lambda (str) (string-prefix? sub str)) strs)])
                        (if (>= count k)
                            (set! max-len (max max-len i))
                            #f))))
                  (if (= max-len 0)
                      ""
                      (substring lcp 0 max-len)))))))))