(define (minimumCost a k)
  (define n (vector-length a))
  (define dp (make-vector (add1 n) 0))
  (for ([i (in-range 1 (add1 n))])
    (define min-cost (add1 (* 1000000000 10)))
    (for ([j (in-range 1 (add1 i))])
      (define cost (+ k (length (remove-duplicates (list->vector (list-ref (vector->list a) (sub1 j) (sub1 i)))))))
      (set! min-cost (min min-cost (+ (vector-ref dp (sub1 j)) cost))))
    (vector-set! dp i min-cost))
  (vector-ref dp n))