(define (find-x-value arr)
  (define n (length arr))
  (if (= n 1)
      (car arr)
      (let loop ([arr arr])
        (if (= (length arr) 1)
            (car arr)
            (let ([new-arr (list)])
              (for ([i (range 0 (sub1 (length arr))) 2])
                (define a (list-ref arr i))
                (define b (list-ref arr (+ i 1)))
                (define c (abs (- a b)))
                (set! new-arr (append new-arr (list c))))
              (loop new-arr))))))