(define (getMoneyAmount n)
  (let ((dp (make-vector (+ n 2) (make-vector (+ n 2) 0))))
    (for ((len (in-range 2 (+ n 1))))
      (for ((i (in-range 1 (- (+ n 1) len))))
        (let ((j (+ i len -1)))
          (let ((min-cost (add1 n)))
            (for ((k (in-range i (+ j 1))))
              (let ((cost (+ k (max (vector-ref (vector-ref dp i) (- k 1))
                                     (vector-ref (vector-ref dp (+ k 1)) j)))))
                (set! min-cost (min min-cost cost))))
            (vector-set! (vector-ref dp i) j min-cost)))))
    (vector-ref (vector-ref dp 1) n)))