(define (find-the-difference s t)
  (let* ((s-chars (string->list s))
         (t-chars (string->list t))
         (s-counts (make-hash))
         (t-counts (make-hash)))
    (for-each (lambda (c) (hash-update! s-counts c (lambda (v) (+ v 1)) 1)) s-chars)
    (for-each (lambda (c) (hash-update! t-counts c (lambda (v) (+ v 1)) 1)) t-chars)
    (for-each (lambda (c)
                (if (not (hash-has-key? s-counts c))
                    (return c)
                    (let ((s-count (hash-ref s-counts c)))
                      (let ((t-count (hash-ref t-counts c)))
                        (if (> t-count s-count)
                            (return c)
                            (void)))))) t-chars)))