(define (find-anagrams s p)
  (define s-len (string-length s))
  (define p-len (string-length p))
  (if (< s-len p-len)
      '()
      (let* ((p-freq (make-vector 26 0))
             (s-freq (make-vector 26 0))
             (result '()))
        (define (char->index char)
          (- (char->integer char) (char->integer #\a)))

        (for ((i (in-range p-len)))
          (vector-set! p-freq (char->index (string-ref p i))
                       (+ (vector-ref p-freq (char->index (string-ref p i))) 1))
          (vector-set! s-freq (char->index (string-ref s i))
                       (+ (vector-ref s-freq (char->index (string-ref s i))) 1)))

        (define (vectors-equal? v1 v2)
          (for/and ((i (in-range (vector-length v1))))
            (= (vector-ref v1 i) (vector-ref v2 i))))

        (when (vectors-equal? p-freq s-freq)
          (set! result (cons 0 result)))

        (for ((i (in-range 1 (- s-len p-len -1))))
          (let ((left-char (string-ref s (- i 1)))
                (right-char (string-ref s (+ i p-len -1))))
            (vector-set! s-freq (char->index left-char)
                         (- (vector-ref s-freq (char->index left-char)) 1))
            (vector-set! s-freq (char->index right-char)
                         (+ (vector-ref s-freq (char->index right-char)) 1))
            (when (vectors-equal? p-freq s-freq)
              (set! result (cons i result)))))

        (reverse result))))