(define (findKthNumber n k)
  (letrec ((helper (λ (prefix k)
                     (let ((count (count-nodes prefix n)))
                       (cond ((<= k count)
                              prefix)
                             (else
                              (helper (+ prefix 1) (- k count))))))
           (count-nodes (λ (prefix n)
                          (let loop ((cur prefix)
                                     (next (+ prefix 1))
                                     (count 0))
                            (cond ((> cur n) count)
                                  (else (loop (* cur 10)
                                              (* next 10)
                                              (+ count (min (- next cur) (- n cur -1))))))))))
    (helper 1 k)))