(define (find-duplicates nums)
  (define n (length nums))
  (define result '())
  (for ([i (in-range n)])
    (let* ([index (abs (list-ref nums i))])
      (if (< index 1)
          (void)
          (let ([actual-index (- index 1)])
            (if (negative? (list-ref nums actual-index))
                (set! result (cons index result))
                (list-set! nums actual-index (- (list-ref nums actual-index)))))))))
  result)