(define (number-of-arithmetic-slices nums)
  (let* ((n (length nums))
         (dp (make-vector n '())))
    (for* ((i (in-range n))
           (j (in-range 0 i)))
      (let* ((diff (- (list-ref nums i) (list-ref nums j)))
             (count (hash-ref (vector-ref dp j) diff 0)))
        (vector-ref dp i)
        (set! (vector-ref dp i)
              (let ((h (if (null? (vector-ref dp i))
                           (make-hash)
                           (vector-ref dp i))))
                (hash-set h diff (+ count (hash-ref h diff 0)))
                h))))
    (let loop ((i 0) (result 0))
      (if (= i n)
          result
          (let ((h (vector-ref dp i)))
            (if (null? h)
                (loop (+ i 1) result)
                (let ((keys (hash-keys h)))
                  (loop (+ i 1) (+ result (apply + (map (lambda (k) (- (hash-ref h k) 1)) keys)))))))))))