(define (repeated-substring-pattern s)
  (define n (string-length s))
  (for/or ([i (in-range 1 (add1 (quotient n 2)))])
    (and (= 0 (remainder n i))
         (let ([sub (substring s 0 i)])
           (let loop ([j i])
             (or (= j n)
                 (and (string=? sub (substring s j (+ j i)))
                      (loop (+ j i)))))))))