(define (island-perimeter grid)
  (let* ((rows (length grid))
         (cols (length (car grid)))
         (perimeter 0))
    (for* ((i (in-range rows))
           (j (in-range cols)))
      (when (= (list-ref (list-ref grid i) j) 1)
        (set! perimeter (+ perimeter 4))
        (when (and (> i 0) (= (list-ref (list-ref grid (- i 1)) j) 1))
          (set! perimeter (- perimeter 2)))
        (when (and (> j 0) (= (list-ref (list-ref grid i) (- j 1)) 1))
          (set! perimeter (- perimeter 2)))))
    perimeter))