(define (find-max-form strs m n)
  (let* ((len (length strs))
         (dp (make-vector (+ 1 m) (make-vector (+ 1 n) 0))))
    (for* ((s (in-list strs)))
      (let* ((zeros (string-count s "0"))
             (ones (string-count s "1")))
        (for* ((i (in-range m (- zeros -1) -1))
               (j (in-range n (- ones -1) -1)))
          (vector-set! (vector-ref dp i) j (max (vector-ref (vector-ref dp i) j)
                                                 (+ 1 (vector-ref (vector-ref dp (- i zeros)) (- j ones))))))))
    (vector-ref (vector-ref dp m) n)))