(define (rotate matrix)
  (let* ([n (length matrix)])
    (for ([i (in-range n)])
      (for ([j (in-range i n)])
        (let ([temp (list-ref (list-ref matrix i) j)])
          (set! (list-ref (list-ref matrix i) j) (list-ref (list-ref matrix j) i))
          (set! (list-ref (list-ref matrix j) i) temp))))
    (for ([i (in-range n)])
      (for ([j (in-range (/ n 2))])
        (let ([temp (list-ref (list-ref matrix i) j)])
          (set! (list-ref (list-ref matrix i) j) (list-ref (list-ref matrix i) (- n 1 j)))
          (set! (list-ref (list-ref matrix i) (- n 1 j)) temp))))
    matrix))