(define (next-greater-elements nums)
  (let* ((n (length nums))
         (result (make-vector n -1))
         (stack '()))
    (for ((i (in-range (* 2 n))))
      (let ((idx (modulo i n)))
        (while (and (not (empty? stack))
                    (< (vector-ref nums (car stack)) (vector-ref nums idx)))
          (let ((top (car stack)))
            (set! stack (cdr stack))
            (vector-set! result top (vector-ref nums idx))))
        (set! stack (cons idx stack))))
    (vector->list result)))