(define (least-bricks wall)
  (let ([counts (make-hash)])
    (for ([row wall])
      (let loop ([row row] [width 0])
        (if (null? (cdr row))
            (void)
            (let ([brick (car row)])
              (set! width (+ width brick))
              (hash-update! counts width add1 0)
              (loop (cdr row) width)))))
    (if (hash-empty? counts)
        (length wall)
        (- (length wall) (apply max (hash-values counts))))))