(define (matrix-reshape mat r c)
  (let* ((m (length mat))
         (n (length (car mat)))
         (total-elements (* m n)))
    (if (= total-elements (* r c))
        (let loop ((i 0) (j 0) (new-mat '()))
          (if (= i total-elements)
              (reverse new-mat)
              (let* ((row (quotient i n))
                     (col (remainder i n))
                     (new-row (quotient i c))
                     (new-col (remainder i c)))
                (if (= new-col 0)
                    (loop (add1 i) 0 (cons (list (list-ref (list-ref mat row) col)) new-mat))
                    (loop (add1 i) 0 (cons (cons (list-ref (list-ref mat row) col) (car new-mat)) (cdr new-mat)))))))
        mat)))