(define (cherry-pickup grid)
  (let* ((n (vector-length grid))
         (dp (make-vector (+ n n -1) (make-vector (+ n n -1) -1))))
    (vector-set! dp 0 (make-vector (+ n n -1) -1))
    (vector-set! (vector-ref dp 0) 0 (vector-ref (vector-ref grid 0) 0))

    (define (get-dp r1 r2)
      (if (and (>= r1 0) (>= r2 0) (< r1 n) (< r2 n))
          (vector-ref (vector-ref dp r1) r2)
          -1))

    (define (set-dp r1 r2 v)
      (if (and (>= r1 0) (>= r2 0) (< r1 n) (< r2 n))
          (vector-set! (vector-ref dp r1) r2 v)
          #f))

    (for* ((k (in-range 1 (+ n n -1)))
           (r1 (in-range (min n (+ k 1))))
           #:when (and (>= r1 0) (< r1 n))
           #:let ((c1 (- k r1)))
           #:when (and (>= c1 0) (< c1 n))
           (r2 (in-range (min n (+ k 1))))
           #:when (and (>= r2 0) (< r2 n))
           #:let ((c2 (- k r2)))
           #:when (and (>= c2 0) (< c2 n)))
      (when (and (not (= (vector-ref (vector-ref grid r1) c1) -1))
                 (not (= (vector-ref (vector-ref grid r2) c2) -1)))
        (let* ((prev-max (max (max (get-dp (- r1 1) (- r2 1))
                                    (get-dp r1 (- r2 1)))
                              (max (get-dp (- r1 1) r2)
                                   (get-dp r1 r2))))
               (val (if (= prev-max -1)
                        -1
                        (+ prev-max (vector-ref (vector-ref grid r1) c1)
                           (if (= r1 r2)
                               0
                               (vector-ref (vector-ref grid r2) c2))))))
          (set-dp r1 r2 val))))

    (max 0 (get-dp (- n 1) (- n 1)))))