(define (orderOfLargestPlusSign n mines)
  (define grid (make-vector n (make-vector n #t)))
  (for ([mine mines])
    (vector-set! (vector-ref grid (car mine)) (cadr mine) #f))

  (define (check-plus-sign row col k)
    (and (>= row k-1) (< row n-k) (>= col k-1) (< col n-k)
         (let loop ([i 1])
           (or (> i k)
               (and (vector-ref (vector-ref grid row (+ col i)) #t)
                    (vector-ref (vector-ref grid row (- col i)) #t)
                    (vector-ref (vector-ref grid (+ row i) col) #t)
                    (vector-ref (vector-ref grid (- row i) col) #t)
                    (loop (+ i 1)))))))

  (define (find-max-k row col)
    (let loop ([k 1])
      (if (check-plus-sign row col k)
          (loop (+ k 1))
          (- k 1))))

  (let loop ([row 0] [max-k 0])
    (if (= row n)
        max-k
        (let loop2 ([col 0])
          (if (= col n)
              (loop (+ row 1) max-k)
              (loop2 (+ col 1) (max max-k (find-max-k row col)))))))
  )