(define (champagneTower poured row query_row query_glass)
  (let ([tower (make-vector 101 (make-vector 101 0.0))])
    (vector-set! (vector-ref tower 0) 0 (real->double poured))
    (for ([i (in-range 0 row)])
      (for ([j (in-range 0 (+ i 1))])
        (let ([excess (- (vector-ref (vector-ref tower i) j) 1.0)])
          (when (> excess 0.0)
            (let ([half-excess (/ excess 2.0)])
              (vector-set! (vector-ref tower (+ i 1)) j (+ (vector-ref (vector-ref tower (+ i 1)) j) half-excess))
              (vector-set! (vector-ref tower (+ i 1)) (+ j 1) (+ (vector-ref (vector-ref tower (+ i 1)) (+ j 1)) half-excess)))))))
    (min 1.0 (vector-ref (vector-ref tower query_row) query_glass))))