(define (large-group-positions s)
  (let loop ([i 0] [start 0] [result '()])
    (if (= i (string-length s))
        (if (>= (- i start) 3)
            (cons (list start (- i 1)) result)
            result)
        (if (or (= i 0) (not (char=? (string-ref s i) (string-ref s (- i 1)))))
            (if (and (> i 0) (>= (- i start) 3))
                (loop (+ i 1) i (cons (list start (- i 1)) result))
                (loop (+ i 1) i result))
            (loop (+ i 1) start result)))))