(define (maskPII s)
  (define at-index (string-index s "@"))
  (if at-index
      (let* ((name (substring s 0 at-index))
             (domain (substring s (+ at-index 1)))
             (first-name (string-downcase (substring name 0 1)))
             (last-name (string-downcase (substring name (- (string-length name) 1))))
             (masked-name (string-append first-name "*****" last-name)))
        (string-append masked-name "@" (string-downcase domain)))
      (let* ((digits (filter char-numeric? (string->list s)))
             (num-digits (length digits))
             (last-digits (list->string (take (reverse digits) 4)))
             (masked-number (string-append "***-***-" last-digits)))
        (cond
          ((= num-digits 10) masked-number)
          ((= num-digits 11) (string-append "+*-" masked-number))
          ((= num-digits 12) (string-append "+**-" masked-number))
          ((= num-digits 13) (string-append "+***-" masked-number))
          (else "")))))