(define (matrix-score matrix)
  (let* ((rows (length matrix))
         (cols (length (car matrix)))
         (flipped-matrix (for/list ((i (in-range rows)))
                           (if (= (list-ref (list-ref matrix i) 0) 0)
                               (map (lambda (x) (if (= x 0) 1 0)) (list-ref matrix i))
                               (list-ref matrix i)))))
    (let loop ((col 0) (score 0))
      (if (= col cols)
          score
          (let* ((ones (for/sum ((row (in-range rows)))
                          (list-ref (list-ref flipped-matrix row) col)))
                 (zeros (- rows ones))
                 (most-common (if (> ones zeros) 1 0)))
            (loop (+ col 1) (+ score (* (expt 2 (- cols col 1))
                                         (if (> ones zeros) ones zeros)))))))))