(define (num-decodings s)
  (define n (string-length s))
  (define dp (make-vector (add1 n) 0))
  (vector-set! dp 0 1)
  (vector-set! dp 1 (if (string=? (substring s 0 1) "0") 0 1))
  (for ([i (in-range 2 (add1 n))])
    (define one-digit (string->number (substring s (sub1 i) i)))
    (define two-digits (string->number (substring s (- i 2) i)))
    (when (and (>= one-digit 1) (<= one-digit 9))
      (vector-set! dp i (+ (vector-ref dp i) (vector-ref dp (sub1 i)))))
    (when (and (>= two-digits 10) (<= two-digits 26))
      (vector-set! dp i (+ (vector-ref dp i) (vector-ref dp (- i 2))))))
  (vector-ref dp n))