(define (num-unique-emails emails)
  (define (normalize-email email)
    (define (split-email email)
      (string-split email "@"))
    (define (normalize-local local-name)
      (define (remove-dots s)
        (string-replace* s "." ""))
      (define (remove-plus s)
        (substring s 0 (or (string-index s "+") (string-length s))))
      (remove-dots (remove-plus local-name)))
    (let ([parts (split-email email)])
      (string-append (normalize-local (car parts)) "@" (cadr parts))))
  (length (remove-duplicates (map normalize-email emails) string=?)))