(define (minDeletionSize s)
  (define n (vector-length (vector-ref s 0)))
  (define m (vector-length s))
  (define dp (make-vector n 1))
  (for ([i (in-range 1 n)])
    (for ([j (in-range i)])
      (define sorted? #t)
      (for ([k (in-range m)])
        (when (> (vector-ref (vector-ref s k) j) (vector-ref (vector-ref s k) i))
          (set! sorted? #f)
          (break)))
      (when sorted?
        (vector-set! dp i (max (vector-ref dp i) (+ (vector-ref dp j) 1))))))
  (- n (apply max (vector->list dp))))