(define (traffic-hub n roads)
  (define (count-incoming node)
    (length (filter (lambda (road) (= (second road) node)) roads)))
  (define (count-outgoing node)
    (length (filter (lambda (road) (= (first road) node)) roads)))
  (define (check-hub node)
    (and (= (count-incoming node) (- n 1)) (= (count-outgoing node) 0)))
  (define (check-possible)
    (for/or ([node (in-range 1 (+ n 1))])
      (check-hub node)))
  (if (check-possible) 0 -1))