(define (infiniteBoardGame board)
  (define (bfs start)
    (define visited (make-hash))
    (define queue (list start))
    (hash-set! visited start #t)
    (define (explore)
      (if (null? queue)
          #f
          (let* ((curr (car queue))
                 (next-queue (cdr queue))
                 (x (car curr))
                 (y (cadr curr)))
            (if (or (< x 0) (< y 0))
                (explore)
                (if (equal? (list x y) '(0 0))
                    #t
                    (let* ((dx (car board))
                           (dy (cadr board))
                           (next1 (list (- x dx) (- y dy)))
                           (next2 (list (- x dy) (- y dx))))
                      (cond
                        ((and (not (hash-has-key? visited next1)))
                         (hash-set! visited next1 #t)
                         (set! queue (append next-queue (list next1))))
                        (else #f))
                      (cond
                        ((and (not (hash-has-key? visited next2)))
                         (hash-set! visited next2 #t)
                         (set! queue (append queue (list next2))))
                        (else #f))
                      (set! queue next-queue)
                      (explore)))))))
    (explore))

  (bfs (list 100 100)))