(define (num-ways n relations k)
  (let* ((graph (make-hash))
         (q (list 0))
         (dist (make-vector n #f)))
    (vector-set! dist 0 0)
    (for ([r relations])
      (hash-update! graph (first r) (lambda (x) (append x (list (second r)))) (list (second r))))
    (for ([i (in-range k)])
      (let ((new-q '()))
        (for ([node q])
          (when (hash-has-key? graph node)
            (for ([neighbor (hash-ref graph node)])
              (if (vector-ref dist neighbor)
                  (vector-set! dist neighbor (+ (vector-ref dist neighbor) (vector-ref dist node)))
                  (vector-set! dist neighbor (vector-ref dist node)))
              (set! new-q (append new-q (list neighbor))))))
        (set! q (remove-duplicates new-q)))))
    (if (vector-ref dist (- n 1)) (vector-ref dist (- n 1)) 0)))