(define (min-number-of-booths demand)
  (let* ((n (length demand))
         (prefix-sum (make-vector (+ n 1) 0)))
    (for/list ((i (in-range n)))
      (let ((start (string->int (substring (list-ref demand i) 0 1)))
            (end (string->int (substring (list-ref demand i) 2 3))))
        (vector-set! prefix-sum start (+ (vector-ref prefix-sum start) 1))
        (when (< end 26)
          (vector-set! prefix-sum (+ end 1) (- (vector-ref prefix-sum (+ end 1)) 1)))))
    (let loop ((i 1) (current 0) (max-booths 0))
      (if (> i 26)
          max-booths
          (let ((new-current (+ current (vector-ref prefix-sum i))))
            (loop (+ i 1) new-current (max max-booths new-current)))))))