(define (min-cost-to-reach-destination max-trips costs start finish)
  (let* ((n (vector-length costs))
         (dist (make-vector n (make-vector n #inf)))
         (q (make-vector n #f)))
    (for* ((i (in-range n)))
      (vector-set! (vector-ref dist i) i 0))
    (for* ((i (in-range n))
           (j (in-range n))
           #:when (< (vector-ref (vector-ref costs i) j) #inf))
      (vector-set! (vector-ref dist i) j (vector-ref (vector-ref costs i) j)))
    (for* ((k (in-range n))
           (i (in-range n))
           (j (in-range n)))
      (vector-set! (vector-ref dist i) j (min (vector-ref (vector-ref dist i) j)
                                               (+ (vector-ref (vector-ref dist i) k)
                                                  (vector-ref (vector-ref dist k) j)))))
    (vector-ref (vector-ref dist start) finish)))