(define (findKthLargest nums k)
  (define (partition nums left right pivotIndex)
    (let* ((pivotValue (list-ref nums pivotIndex))
           (storeIndex left))
      (swap! nums pivotIndex right)
      (for ((i (in-range left right)))
        (when (< (list-ref nums i) pivotValue)
          (swap! nums storeIndex i)
          (set! storeIndex (+ storeIndex 1))))
      (swap! nums right storeIndex)
      storeIndex))

  (define (swap! nums i j)
    (let ((temp (list-ref nums i)))
      (list-set! nums i (list-ref nums j))
      (list-set! nums j temp)))

  (define (quickselect nums left right k_smallest)
    (if (= left right)
        (list-ref nums left)
        (let* ((pivotIndex right)
               (pivotIndex (partition nums left right pivotIndex))
               (kth_index (- k_smallest 1)))
          (cond
            ((= kth_index pivotIndex) (list-ref nums kth_index))
            ((> kth_index pivotIndex) (quickselect nums (+ pivotIndex 1) right k_smallest))
            (else (quickselect nums left (- pivotIndex 1) k_smallest))))))

  (quickselect nums 0 (- (length nums) 1) (- (length nums) k -1)))