(define (dynamic-password s p)
  (define n (string-length s))
  (define m (string-length p))
  (define dp (make-vector (+ n 1) #f))
  (vector-set! dp 0 #t)
  (for ([i (in-range 1 (+ n 1))])
    (for ([j (in-range 1 (+ m 1))])
      (when (and (>= i j) (vector-ref dp (- i j))
                 (equal? (substring s (- i j) i) p))
        (vector-set! dp i #t)
        (break))))
  (if (vector-ref dp n) "true" "false"))