(define (is-interleave s1 s2 s3)
  (define len1 (string-length s1))
  (define len2 (string-length s2))
  (define len3 (string-length s3))

  (if (!= (+ len1 len2) len3)
      #f
      (let ([dp (make-vector (+ len2 1) #f)])
        (vector-set! dp 0 #t)
        (for ([j (in-range 1 (+ len2 1))])
          (vector-set! dp j (and (vector-ref dp (- j 1))
                                 (char=? (string-ref s2 (- j 1)) (string-ref s3 (- j 1))))))
        (for ([i (in-range 1 (+ len1 1))])
          (vector-set! dp 0 (and (vector-ref dp 0)
                                 (char=? (string-ref s1 (- i 1)) (string-ref s3 (- i 1)))))
          (for ([j (in-range 1 (+ len2 1))])
            (vector-set! dp j (or (and (vector-ref dp (- j 1))
                                       (char=? (string-ref s2 (- j 1)) (string-ref s3 (+ i j -2))))
                                   (and (vector-ref dp j)
                                       (char=? (string-ref s1 (- i 1)) (string-ref s3 (+ i j -2))))))))
        (vector-ref dp len2))))