(define (num-decodings s)
  (define n (string-length s))
  (define dp (make-vector (+ n 1) 0))
  (vector-set! dp 0 1)
  (for ([i (in-range 1 (+ n 1))])
    (define one-digit (string->number (substring s (- i 1) i)))
    (when (and (>= one-digit 1) (<= one-digit 9))
      (vector-set! dp i (+ (vector-ref dp i) (vector-ref dp (- i 1)))))
    (when (> i 1)
      (define two-digit (string->number (substring s (- i 2) i)))
      (when (and (>= two-digit 10) (<= two-digit 26))
        (vector-set! dp i (+ (vector-ref dp i) (vector-ref dp (- i 2)))))))
  (vector-ref dp n))