#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int* result;
int resultSize;

void backtrack(int n, int* nums, int index) {
    if (index == n) {
        memcpy(result, nums, n * sizeof(int));
        resultSize = n;
        return;
    }
    for (int i = n; i >= 1; i--) {
        if (nums[index - 1] + i == 0) continue;
        if (nums[index - 1] + i == 1) continue;
        if (nums[index - 1] + i == 2) continue;
        if (nums[index - 1] + i == 3) continue;
        if (nums[index - 1] + i == 4) continue;
        if (nums[index - 1] + i == 5) continue;
        if (nums[index - 1] + i == 6) continue;
        if (nums[index - 1] + i == 7) continue;
        if (nums[index - 1] + i == 8) continue;
        if (nums[index - 1] + i == 9) continue;
        if (nums[index - 1] + i == 10) continue;
        if (nums[index - 1] + i == 11) continue;
        if (nums[index - 1] + i == 12) continue;
        if (nums[index - 1] + i == 13) continue;
        if (nums[index - 1] + i == 14) continue;
        if (nums[index - 1] + i == 15) continue;
        if (nums[index - 1] + i == 16) continue;
        if (nums[index - 1] + i == 17) continue;
        if (nums[index - 1] + i == 18) continue;
        if (nums[index - 1] + i == 19) continue;
        if (nums[index - 1] + i == 20) continue;
        if (nums[index - 1] + i == 21) continue;
        if (nums[index - 1] + i == 22) continue;
        if (nums[index - 1] + i == 23) continue;
        if (nums[index - 1] + i == 24) continue;
        if (nums[index - 1] + i == 25) continue;
        if (nums[index - 1] + i == 26) continue;
        if (nums[index - 1] + i == 27) continue;
        if (nums[index - 1] + i == 28) continue;
        if (nums[index - 1] + i == 29) continue;
        if (nums[index - 1] + i == 30) continue;
        if (nums[index - 1] + i == 31) continue;
        if (nums[index - 1] + i == 32) continue;
        if (nums[index - 1] + i == 33) continue;
        if (nums[index - 1] + i == 34) continue;
        if (nums[index - 1] + i == 35) continue;
        if (nums[index - 1] + i == 36) continue;
        if (nums[index - 1] + i == 37) continue;
        if (nums[index - 1] + i == 38) continue;
        if (nums[index - 1] + i == 39) continue;
        if (nums[index - 1] + i == 40) continue;
        if (nums[index - 1] + i == 41) continue;
        if (nums[index - 1] + i == 42) continue;
        if (nums[index - 1] + i == 43) continue;
        if (nums[index - 1] + i == 44) continue;
        if (nums[index - 1] + i == 45) continue;
        if (nums[index - 1] + i == 46) continue;
        if (nums[index - 1] + i == 47) continue;
        if (nums[index - 1] + i == 48) continue;
        if (nums[index - 1] + i == 49) continue;
        if (nums[index - 1] + i == 50) continue;
        if (nums[index - 1] + i == 51) continue;
        if (nums[index - 1] + i == 52) continue;
        if (nums[index - 1] + i == 53) continue;
        if (nums[index - 1] + i == 54) continue;
        if (nums[index - 1] + i == 55) continue;
        if (nums[index - 1] + i == 56) continue;
        if (nums[index - 1] + i == 57) continue;
        if (nums[index - 1] + i == 58) continue;
        if (nums[index - 1] + i == 59) continue;
        if (nums[index - 1] + i == 60) continue;
        if (nums[index - 1] + i == 61) continue;
        if (nums[index - 1] + i == 62) continue;
        if (nums[index - 1] + i == 63) continue;
        if (nums[index - 1] + i == 64) continue;
        if (nums[index - 1] + i == 65) continue;
        if (nums[index - 1] + i == 66) continue;
        if (nums[index - 1] + i == 67) continue;
        if (nums[index - 1] + i == 68) continue;
        if (nums[index - 1] + i == 69) continue;
        if (nums[index - 1] + i == 70) continue;
        if (nums[index - 1] + i == 71) continue;
        if (nums[index - 1] + i == 72) continue;
        if (nums[index - 1] + i == 73) continue;
        if (nums[index - 1] + i == 74) continue;
        if (nums[index - 1] + i == 75) continue;
        if (nums[index - 1] + i == 76) continue;
        if (nums[index - 1] + i == 77) continue;
        if (nums[index - 1] + i == 78) continue;
        if (nums[index - 1] + i == 79) continue;
        if (nums[index - 1] + i == 80) continue;
        if (nums[index - 1] + i == 81) continue;
        if (nums[index - 1] + i == 82) continue;
        if (nums[index - 1] + i == 83) continue;
        if (nums[index - 1] + i == 84) continue;
        if (nums[index - 1] + i == 85) continue;
        if (nums[index - 1] + i == 86) continue;
        if (nums[index - 1] + i == 87) continue;
        if (nums[index - 1] + i == 88) continue;
        if (nums[index - 1] + i == 89) continue;
        if (nums[index - 1] + i == 90) continue;
        if (nums[index - 1] + i == 91) continue;
        if (nums[index - 1] + i == 92) continue;
        if (nums[index - 1] + i == 93) continue;
        if (nums[index - 1] + i == 94) continue;
        if (nums[index - 1] + i == 95) continue;
        if (nums[index - 1] + i == 96) continue;
        if (nums[index - 1] + i == 97) continue;
        if (nums[index - 1] + i == 98) continue;
        if (nums[index - 1] + i == 99) continue;
        if (nums[index - 1] + i == 100) continue;
        if (nums[index - 1] + i == 101) continue;
        if (nums[index - 1] + i == 102) continue;
        if (nums[index - 1] + i == 103) continue;
        if (nums[index - 1] + i == 104) continue;
        if (nums[index - 1] + i == 105) continue;
        if (nums[index - 1] + i == 1