#include <stdio.h>
#include <stdlib.h>

int minMovesToCaptureTheQueen(int* rook, int* bishop, int* queen, int* your_king) {
    int dx = abs(rook[0] - bishop[0]);
    int dy = abs(rook[1] - bishop[1]);
    if (dx == dy) {
        int x = rook[0], y = rook[1];
        int qx = queen[0], qy = queen[1];
        int kx = your_king[0], ky = your_king[1];
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy) || (x == kx && y == ky)) return 2;
        if ((x == qx && y == qy)