#lang racket

(define (longestDupSubstring s)
  (define (search len)
    (define seen (make-hash))
    (define base 256)
    (define mod (expt 2 63))
    (define hash 0)
    (define h 1)
    (for ([i len])
      (set! hash (mod (+ (* hash base) (char->integer (string-ref s i))) mod))
      (when (> i 0) (set! h (mod (* h base) mod))))
    (hash-set! seen hash 0)
    (for ([start (in-range 1 (+ 1 (string-length s) (- len)))])
      (when (< start (string-length s))
        (set! hash (mod (- hash (mod (* (char->integer (string-ref s (- start 1))) h) mod)) mod))
        (set! hash (mod (+ (* hash base) (char->integer (string-ref s (+ start len -1)))) mod))
        (when (hash-has? seen hash)
          (define prev (hash-ref seen hash))
          (if (equal? (substring s prev (+ prev len)) (substring s start (+ start len)))
              (set! longest (max longest len)))
          (hash-set! seen hash start))))
    longest)

  (define longest 0)
  (define low 1)
  (define high (string-length s))
  (define result "")
  (while (< low high)
    (define mid (quotient (+ low high) 2))
    (define len (search mid))
    (if (> len 0)
        (begin
          (set! result (substring s (hash-ref seen len) (+ (hash-ref seen len) mid)))
          (set! low (+ mid 1)))
        (set! high mid)))
  result)

(longestDupSubstring "banana")