(define (maxEqualRowsAfterFlips matrix)
  (define (normalize row)
    (if (= (car row) 1)
        (map (lambda (x) (if (= x 0) 1 0)) row)
        row))
  (define normalized-rows (map normalize matrix))
  (define row-count (make-hash))
  (for-each (lambda (row)
              (define key (vector->list row))
              (hash-set! row-count key (add1 (hash-ref row-count key 0))))
            normalized-rows)
  (apply max (hash-values row-count)))

(maxEqualRowsAfterFlips '((0 0 0) (1 1 0) (0 0 0) (1 1 1)))