(define (find-occs-after-bigram text first second)
  (define words (string-split text))
  (define len (length words))
  (define result '())
  (for ([i (in-range (- len 1))])
    (when (and (= (list-ref words i) first)
               (= (list-ref words (+ i 1)) second))
      (when (< (+ i 2) len)
        (set! result (cons (list-ref words (+ i 2)) result)))))
  (reverse result))