(define (duplicateZeros arr)
  (define len (length arr))
  (define result (make-vector len 0))
  (define j 0)
  (for ([i 0 len])
    (if (= (vector-ref arr i) 0)
        (begin
          (when (< j (- len 1))
            (vector-set! result j 0)
            (set! j (+ j 1)))
          (when (< j (- len 1))
            (vector-set! result j 0)
            (set! j (+ j 1))))
        (when (< j (- len 1))
          (vector-set! result j (vector-ref arr i))
          (set! j (+ j 1)))))
  (for ([i 0 len])
    (vector-set! arr i (vector-ref result i)))
  arr)