(define (carPooling trips capacity)
  (define changes (make-vector 1001 0))
  (for-each (lambda (trip)
              (define passengers (vector-ref trip 0))
              (define start (vector-ref trip 1))
              (define end (vector-ref trip 2))
              (vector-set! changes start (+ (vector-ref changes start) passengers))
              (vector-set! changes end (- (vector-ref changes end) passengers)))
            trips)
  (define current 0)
  (for-each (lambda (x)
              (set! current (+ current x))
              (when (> current capacity) (return #f)))
            changes)
  #t)