(define (longest-well-performing-interval hours)
  (define n (length hours))
  (define prefix-sum (make-vector (+ n 1) 0))
  (for ([i n])
    (vector-set! prefix-sum (+ i 1) (+ (vector-ref prefix-sum i) (if (> (vector-ref hours i) 8) 1 -1))))
  (define max-length 0)
  (define hash (make-hash))
  (for ([i (+ n 1)])
    (define sum (vector-ref prefix-sum i))
    (when (not (hash-has-key? hash sum))
      (hash-set! hash sum i))
    (when (hash-has-key? hash (- sum 1))
      (set! max-length (max max-length (- i (hash-ref hash (- sum 1)))))))
  max-length)