(define (num-equivalent-domino-pairs dominoes)
  (define counts (make-hash))
  (for-each (lambda (domino)
              (let* ((a (car domino))
                     (b (cadr domino))
                     (key (if (> a b) (list b a) (list a b))))
                (hash-set! counts key (add1 (hash-ref counts key 0)))))
            dominoes)
  (define total 0)
  (for-each (lambda (count)
              (set! total (+ total (/ (* count (- count 1)) 2))))
            (hash-values counts))
  total)

(num-equivalent-domino-pairs '((1 2) (2 1) (3 4) (5 6)))