(define (path-sum-ii root sum)
  (define (helper node sum path)
    (if (null? node)
        '()
        (let* ((new-path (cons (node-value node) path))
               (left (helper (node-left node) (- sum (node-value node)) new-path))
               (right (helper (node-right node) (- sum (node-value node)) new-path)))
          (if (and (null? (node-left node))
                   (null? (node-right node))
                   (= sum (node-value node)))
              (cons (reverse new-path) (append left right))
              (append left right)))))
  (helper root sum '()))