(define (dayOfTheWeek day month year)
  (define month-index (vector 0 3 2 5 0 3 5 1 4 6 2 4))
  (define adjusted-year (if (< month 3) (- year 1) year))
  (define k (modulo (+ year (quotient adjusted-year 4) (quotient adjusted-year 400) (vector-ref month-index (sub1 month)) day) 7))
  (vector-ref (vector "Sunday" "Monday" "Tuesday" "Wednesday" "Thursday" "Friday" "Saturday") k))