(define (uniqueOccurrences arr)
  (define counts (make-hash))
  (for-each (lambda (x)
              (hash-set! counts x (add1 (hash-ref counts x 0))))
            arr)
  (define occurrences (hash->list counts))
  (define unique-counts (map second occurrences))
  (define unique-set (set unique-counts))
  (= (length unique-set) (length unique-counts)))