(define (dieSimulator n rolls)
  (define mod 1000000007)
  (define dp (make-vector (+ 1 n) (make-vector 7 0)))
  (for ([i 1 7])
    (vector-set! (vector-ref dp 1) i 1))
  (for ([i 2 (+ n 1)])
    (for ([j 1 7])
      (for ([k 1 7])
        (when (not (= j k))
          (vector-set! (vector-ref dp i) j
                        (mod (+ (vector-ref (vector-ref dp (- i 1)) k) (vector-ref (vector-ref dp i) j)) mod)))))
    (for ([j 1 7])
      (vector-set! (vector-ref dp i) j (mod (vector-ref (vector-ref dp i) j) mod))))
  (apply + (map (lambda (x) (vector-ref (vector-ref dp n) x)) (range 1 7))))