(define (minimum-swaps s t)
  (define n (string-length s))
  (define (count-mismatches)
    (define count (make-vector 2 0))
    (for ([i (in-range n)])
      (when (not (= (string-ref s i) (string-ref t i)))
        (let ([index (if (= (string-ref s i) #\a) 0 1)])
          (vector-set! count index (+ 1 (vector-ref count index))))))
    count)
  (define mismatches (count-mismatches))
  (define a-mismatches (vector-ref mismatches 0))
  (define b-mismatches (vector-ref mismatches 1))
  (if (even? (+ a-mismatches b-mismatches))
      (/ (+ a-mismatches b-mismatches) 2)
      -1))