(define (number-of-nice-subarrays nums k)
  (define (at-most-k k)
    (define count 0)
    (define left 0)
    (for ([right (in-range (length nums))])
      (when (= (vector-ref nums right) 1)
        (set! k (- k 1)))
      (when (< k 0)
        (while (>= k 0)
          (when (= (vector-ref nums left) 1)
            (set! k (+ k 1)))
          (set! left (+ left 1))))
      (set! count (+ count (- right left 1))))
    count)
  (- (at-most-k k) (at-most-k (- k 1))))