(define (palindrome-partitioning-iii s k)
  (define (is-palindrome str)
    (equal? str (string-reverse str)))

  (define (min-cut str)
    (define n (string-length str))
    (define cuts (make-vector n (lambda () n)))
    (define pal (make-vector n #f))

    (for ([i (in-range n)])
      (for ([j (in-range (add1 i))])
        (when (and (is-palindrome (substring str j (add1 i)))
                   (zero? j))
          (vector-set! pal i #t)
          (vector-set! cuts i (min (vector-ref cuts i) 0)))
        (when (and (is-palindrome (substring str j (add1 i)))
                   (not (zero? j)))
          (vector-set! cuts i (min (vector-ref cuts i) (add1 (vector-ref cuts j))))))
      (when (vector-ref pal i)
        (vector-set! cuts i 0)))
    (vector-ref cuts (sub1 n)))

  (define m (min-cut s))
  (- m k))