(define (group-the-people groupSizes)
  (define (helper sizes)
    (define groups (make-hash))
    (for ([i (in-range (length sizes))])
      (let ([size (list-ref sizes i)])
        (if (hash-has-key? groups size)
            (hash-set! groups size (cons i (hash-ref groups size)))
            (hash-set! groups size (list i)))))
    (define result '())
    (for ([size (hash-keys groups)])
      (let ([members (hash-ref groups size)])
        (for ([chunk (in-chunks size members)])
          (set! result (cons chunk result)))))
    (reverse result))
  (define (in-chunks size lst)
    (if (null? lst)
        '()
        (cons (take lst size) (in-chunks size (drop lst size)))))
  (helper groupSizes))