(define (minimumDistance word1 word2)
  (define n (string-length word1))
  (define m (string-length word2))
  (define dp (make-vector (+ n 1) (lambda () (make-vector (+ m 1) 0))))
  (for ([i (in-range (+ n 1))])
    (vector-set! dp i (make-vector (+ m 1) 0)))
  (for ([i (in-range (+ n 1))])
    (vector-set! (vector-ref dp i) 0 i))
  (for ([j (in-range (+ m 1))])
    (vector-set! (vector-ref dp 0) j j))
  (for ([i (in-range 1 (+ n 1))])
    (for ([j (in-range 1 (+ m 1))])
      (define c1 (string-ref word1 (- i 1)))
      (define c2 (string-ref word2 (- j 1)))
      (define dist1 (+ (vector-ref (vector-ref dp (- i 1)) j) 1))
      (define dist2 (+ (vector-ref (vector-ref dp i) (- j 1)) 1))
      (define dist3 (+ (vector-ref (vector-ref dp (- i 1)) (- j 1)) (if (= c1 c2) 0 1)))
      (vector-set! (vector-ref dp i) j (min dist1 dist2 dist3))))
  (vector-ref (vector-ref dp n) m))

(minimumDistance "hello" "world")