(define (min-taps n ranges)
  (define (helper start end taps)
    (if (>= start n) taps
        (let loop ((i start) (min-tap (min (+ start 1) n)) (max-reach start) (tap-count taps))
          (if (and (null? min-tap) (< i end))
              (loop (+ i 1) (min (+ i 1) n) max-reach tap-count)
              (if (null? min-tap)
                  (if (>= max-reach i)
                      (if (< tap-count (+ 1)) (loop (+ i 1) (min (+ i 1) n) (max max-reach (if (< i n) (+ i (vector-ref ranges i))) 0)) (+ tap-count 1))
                          (loop (+ i 1) (min (+ i 1) n) max-reach tap-count))
                  (loop (+ i 1) min-tap max-reach tap-count))))))
  (define max-reach (make-vector (+ n 1) 0))
  (for ((i (in-range (vector-length ranges))))
    (let ((r (vector-ref ranges i)))
      (if (< (+ i r) (vector-length max-reach))
          (vector-set! max-reach (+ i r) (max (vector-ref max-reach (+ i r)) (- (+ i r) i))))))
  (helper 0 0 0))

(define (min-taps n ranges)
  (define dp (make-vector (+ n 1) +inf.0))
  (vector-set! dp 0 0)
  (for ((i (in-range (vector-length ranges))))
    (let ((r (vector-ref ranges i)))
      (for ((j (max 0 (- i r))) (in-range (+ i 1 (min r (- n i))))))
        (vector-set! dp j (min (vector-ref dp j) (+ (vector-ref dp (- j r)) 1))))))
  (if (= (vector-ref dp n) +inf.0) -1 (vector-ref dp n)))

(min-taps n ranges)