(define (diagonalSort matrix)
  (define (sort-diagonal i j)
    (define lst '())
    (define x i)
    (define y j)
    (while (and (< x (length matrix)) (< y (length (vector-ref matrix x))))
      (set! lst (cons (vector-ref (vector-ref matrix x) y) lst))
      (set! x (+ x 1))
      (set! y (+ y 1)))
    (define sorted (sort lst <))
    (set! x i)
    (set! y j)
    (define idx 0)
    (while (and (< x (length matrix)) (< y (length (vector-ref matrix x))))
      (vector-set! (vector-ref matrix x) y (list-ref sorted idx))
      (set! x (+ x 1))
      (set! y (+ y 1))
      (set! idx (+ idx 1))))

  (for ([i (in-range (length matrix))])
    (sort-diagonal i 0))
  (for ([j (in-range 1 (length (vector-ref matrix 0)))])
    (sort-diagonal 0 j))
  matrix)