(define (candy ratings)
  (define n (length ratings))
  (define candies (make-vector n 1))
  (for ([i (in-range 1 n)])
    (when (> (vector-ref ratings i) (vector-ref ratings (- i 1)))
      (vector-set! candies i (+ 1 (vector-ref candies (- i 1))))))
  (for ([i (in-range (- n 2) -1 -1)])
    (when (> (vector-ref ratings i) (vector-ref ratings (+ i 1)))
      (vector-set! candies i (max (vector-ref candies i) (+ 1 (vector-ref candies (+ i 1)))))))
  (apply + (vector->list candies)))