(define (num-teams rating)
  (define (count-teams count1 count2 count3)
    (+ (* count1 count2 count3) (* count3 count2 count1)))
  (define (count-by-direction lst)
    (define n (length lst))
    (define count 0)
    (for ([i (in-range n)])
      (for ([j (in-range i)])
        (for ([k (in-range j)])
          (when (and (< (list-ref lst i) (list-ref lst j))
                     (< (list-ref lst j) (list-ref lst k)))
            (set! count (+ count 1)))))
      (for ([j (in-range i)])
        (for ([k (in-range j)])
          (when (and (> (list-ref lst i) (list-ref lst j))
                     (> (list-ref lst j) (list-ref lst k)))
            (set! count (+ count 1))))))
    count)
  (count-by-direction rating))