(define (findMinFibonacciNumbers k)
  (define fibs (list 1 1))
  (define (generate-fibs n)
    (let loop ((a 1) (b 1))
      (if (> b n)
          '()
          (cons b (loop b (+ a b))))))
  (set! fibs (append fibs (generate-fibs k)))
  (define count 0)
  (define sum 0)
  (for ((f (reverse fibs)))
    (while (and (> k 0) (>= k f))
      (set! k (- k f))
      (set! count (+ count 1))))
  count)