(define (checkIfCanBreak s1 s2)
  (define (can-break s1 s2)
    (let loop ((s1 (sort s1 <)) (s2 (sort s2 <)) (i 0))
      (if (and (< i (length s1)) (< i (length s2)))
          (if (<= (list-ref s1 i) (list-ref s2 i))
              (loop s1 s2 (add1 i))
              #f)
          #t)))
  (or (can-break s1 s2) (can-break s2 s1)))

(define (sort lst cmp)
  (if (null? lst)
      '()
      (cons (car lst) (sort (filter (lambda (x) (cmp x (car lst))) (cdr lst)) cmp))))