(define (longest-subarray nums limit)
  (define (max-heap)
    (let ((data '()))
      (define (insert x)
        (set! data (cons x data))
        (set! data (sort data >)))
      (define (remove-max)
        (set! data (cdr data)))
      (define (max)
        (car data))
      (define (size)
        (length data))
      (define (clear)
        (set! data '()))
      (define (elements)
        data)
      (values insert remove-max max size clear elements)))

  (define (min-heap)
    (let ((data '()))
      (define (insert x)
        (set! data (cons x data))
        (set! data (sort data <)))
      (define (remove-min)
        (set! data (cdr data)))
      (define (min)
        (car data))
      (define (size)
        (length data))
      (define (clear)
        (set! data '()))
      (define (elements)
        data)
      (values insert remove-min min size clear elements)))

  (define (helper nums limit)
    (define (check-heap max-h min-h left right)
      (let ((max-val (max-h)) (min-val (min-h)))
        (if (<= (- max-val min-val) limit)
            (values #t left right)
            (begin
              (remove-min)
              (check-heap max-h min-h left (+ left 1)))))
      )
    (define max-h (max-heap))
    (define min-h (min-heap))
    (define (iter left right max-length)
      (if (>= right (length nums))
          max-length
          (begin
            (insert-max (list-ref nums right))
            (insert-min (list-ref nums right))
            (let-values (((valid left right) (check-heap max-h min-h left right)))
              (if valid
                  (iter left (+ right 1) (max max-length (- right left 1)))
                  (begin
                    (remove-max)
                    (iter (+ left 1) right max-length))))))
      )
    (iter 0 0 0))

  (helper nums limit))