(define (maxPoints points)
  (define (gcd a b)
    (if (= b 0)
        a
        (gcd b (modulo a b))))

  (define (slope p1 p2)
    (let ((dy (- (cadr p2) (cadr p1)))
          (dx (- (car p2) (car p1))))
      (if (= dx 0)
          (list 'inf (if (< dy 0) -1 1))
          (let* ((g (gcd dy dx))
                 (dy' (/ dy g))
                 (dx' (/ dx g)))
            (list dy' dx')))))

  (define (count-points i)
    (define slopes (make-hash))
    (define same-point 1)
    (define n (length points))
    (for ((j (in-list (range n))))
      (when (not (= i j))
        (if (= (car (list-ref points i)) (car (list-ref points j)))
            (set! same-point (+ same-point 1))
            (let ((s (slope (list-ref points i) (list-ref points j))))
              (hash-set! slopes s (add1 (hash-ref slopes s 0))))))
    (apply max (cons same-point (hash-map slopes (lambda (k v) v)))))

  (define max-count 0)
  (define n (length points))
  (for ((i (in-list (range n))))
    (set! max-count (max max-count (count-points i))))
  max-count)