(define (findMaxValueOfEquation points k)
  (define (maxValue q)
    (if (null? q) 0
        (let* ((x1 (car (car q)))
               (y1 (cadr (car q)))
               (x2 (car (cadr q)))
               (y2 (cadr (cadr q))))
          (+ y1 y2 (- x2 x1)))))
  (define max (lambda ()
                 (let loop ((q '()) (i 0) (result -inf))
                   (if (= i (length points))
                       result
                       (let* ((x (car (list-ref points i)))
                              (y (cadr (list-ref points i)))
                              (new-result (if (and (not (null? q))
                                                   (<= (- x (car (car q))) k))
                                              (maxValue q)
                                              -inf)))
                         (set! result (max result new-result))
                         (set! q (filter (lambda (p) (<= (- x (car p)) k)) q))
                         (set! q (cons (list x y) q))
                         (loop q (+ i 1) result))))))
  (max))