(define (reformat-date date)
  (define months '(("Jan" "01") ("Feb" "02") ("Mar" "03") 
                   ("Apr" "04") ("May" "05") ("Jun" "06") 
                   ("Jul" "07") ("Aug" "08") ("Sep" "09") 
                   ("Oct" "10") ("Nov" "11") ("Dec" "12")))
  (define parts (string-split date " "))
  (define day (string-drop (first parts) 0))
  (define month (second parts))
  (define year (third parts))
  (define month-number (cdr (assoc month months)))
  (string-append year "-" month-number "-" (format "~2d" (string->number day))))

(reformat-date "20th Oct 2052")