(define (maxProbability n edges start end)
  (define graph (make-vector n '()))
  (for-each (lambda (edge)
              (define u (car edge))
              (define v (cadr edge))
              (define p (caddr edge))
              (vector-set! graph u (cons (cons v p) (vector-ref graph u)))
              (vector-set! graph v (cons (cons u p) (vector-ref graph v))))
            edges)

  (define (dijkstra)
    (define dist (make-vector n 0.0))
    (define pq (make-queue))
    (vector-set! dist start 1.0)
    (queue-enqueue! pq (cons start 1.0))

    (let loop ()
      (if (queue-empty? pq)
          (vector-ref dist end)
          (let* ((current (queue-dequeue! pq))
                 (node (car current))
                 (prob (cdr current)))
            (for-each (lambda (neighbor)
                        (define v (car neighbor))
                        (define p (cdr neighbor))
                        (define new-prob (* prob p))
                        (when (> new-prob (vector-ref dist v))
                          (vector-set! dist v new-prob)
                          (queue-enqueue! pq (cons v new-prob))))
                      (vector-ref graph node))
            (loop)))))

  (dijkstra))