(define (count-good-triplets arr a b c)
  (define (count-pairs i)
    (define (inside? x y z)
      (and (< x y) (< y z)))
    (define count 0)
    (for ([j (in-range (+ i 1) (length arr))])
      (for ([k (in-range (+ j 1) (length arr))])
        (when (inside? (vector-ref arr i) (vector-ref arr j) (vector-ref arr k))
          (when (and (<= (- (vector-ref arr j) (vector-ref arr i)) a)
                     (<= (- (vector-ref arr k) (vector-ref arr j)) b)
                     (<= (- (vector-ref arr k) (vector-ref arr i)) c))
            (set! count (+ count 1)))))
    count)

  (define total-count 0)
  (for ([i (in-range (length arr))])
    (set! total-count (+ total-count (count-pairs i))))
  total-count)