(define (min-swaps grid)
  (define n (vector-length grid))
  (define (count-zeroes row)
    (let loop ((i 0) (count 0))
      (if (< i n)
          (if (= (vector-ref row i) 0)
              (loop (+ i 1) (+ count 1))
              count)
          count)))
  (define (rows-to-swap row)
    (let ((zeroes (count-zeroes row)))
      (- n zeroes)))
  (define rows (map rows-to-swap (vector->list grid)))
  (define swaps 0)
  (define (can-swap idx)
    (and (< idx n) (>= (list-ref rows idx) (- (length rows) idx))))
  (for ((i (in-range n)))
    (if (not (can-swap i))
        (begin
          (define j (find (lambda (x) (can-swap x)) (in-range i n)))
          (if j
              (begin
                (set! swaps (+ swaps (- j i)))
                (vector-swap! rows i j)))))
    (set! rows (vector->list (vector (apply vector rows)))))
  swaps)

(define (vector-swap! v i j)
  (define temp (vector-ref v i))
  (vector-set! v i (vector-ref v j))
  (vector-set! v j temp))