(define (longest-awesome s)
  (define (helper s)
    (define len (string-length s))
    (define max-len 0)
    (define prefix (make-vector 1024 0))
    (vector-set! prefix 0 -1)
    (define mask 0)

    (for* ([i (in-range len)])
      (define ch (string-ref s i))
      (define idx (- (char->integer ch) (char->integer #\0)))
      (set! mask (bit-xor mask (ash 1 idx)))
      (define current (vector-ref prefix mask))
      (when (not (= current 0))
        (set! max-len (max max-len (- i current))))
      (for* ([j (in-range 10)])
        (define new-mask (bit-xor mask (ash 1 j)))
        (define new-current (vector-ref prefix new-mask))
        (when (not (= new-current 0))
          (set! max-len (max max-len (- i new-current)))))
      (when (= 0 (vector-ref prefix mask))
        (vector-set! prefix mask i)))
    max-len))

(longest-awesome "3242415")