(define (maxCoins piles)
  (define (helper piles)
    (define sorted-piles (sort piles >))
    (define n (length sorted-piles))
    (define total 0)
    (for ([i (in-range (/ n 3))])
      (set! total (+ total (list-ref sorted-piles (+ (* 2 i) 1)))))
    total))
(maxCoins piles)