(define (num-ways s)
  (define mod 1000000007)
  (define n (string-length s))
  (define count-a (foldl (lambda (c ch) (if (equal? ch #\a) (+ c 1) c)) 0 s))
  (if (zero? count-a)
      (modulo (expt 2 (- n 1)) mod)
      (if (zero? (mod count-a 3))
          (let* ((part-count (/ count-a 3))
                 (first-pos (filter (lambda (i) (equal? (string-ref s i) #\a)) (range n)))
                 (second-pos (filter (lambda (i) (equal? (string-ref s i) #\a)) (range n))))
            (define first-count (length (filter (lambda (i) (>= i part-count)) first-pos)))
            (define second-count (length (filter (lambda (i) (>= i (* 2 part-count))) second-pos)))
            (modulo (* first-count second-count) mod))
          0))))