(define (num-special mat)
  (define rows (length mat))
  (define cols (length (first mat)))
  (define row-sums (map (lambda (r) (apply + r)) mat))
  (define col-sums (map (lambda (c) (apply + (map (lambda (r) (list-ref r c)) mat))) (range cols)))
  (define (is-special? r c)
    (and (= (list-ref (list-ref mat r) c) 1)
         (= (list-ref row-sums r) 1)
         (= (list-ref col-sums c) 1)))
  (define (count-special r c acc)
    (if (>= r rows)
        acc
        (if (>= c cols)
            (count-special (+ r 1) 0 acc)
            (count-special r (+ c 1) (if (is-special? r c) (+ acc 1) acc)))))
  (count-special 0 0 0))