(define (maxSumRangeQuery nums requests)
  (define n (length nums))
  (define freq (make-vector (add1 n) 0))
  (for-each (lambda (req)
              (define start (car req))
              (define end (cadr req))
              (vector-set! freq start (add1 (vector-ref freq start)))
              (vector-set! freq (add1 end) (sub1 (vector-ref freq (add1 end)))))
            requests)
  (define counts (vector->list (vector-map (lambda (x)
                                              (if (zero? x) 0 (+ (vector-ref freq x) (vector-ref freq (sub1 x)))))
                                            (iota n))))
  (define sorted-nums (sort nums >))
  (define sorted-counts (sort counts >))
  (define total 0)
  (for ((i (in-range n)))
    (set! total (+ total (* (list-ref sorted-nums i) (list-ref sorted-counts i)))))
  (modulo total (expt 10 9))
)