(define (isPrintable color)
  (define (canPrint color)
    (for/fold ([b #t]) ([i (in-range (length color))])
      (if (or (not (vector-ref color i)) (not (vector-ref (vector-ref color i) 0)))
          b
          (begin
            (set! (vector-ref color i) #f)
            (for ((j (in-range (length color))))
              (when (and (vector-ref color j) (not (vector-ref (vector-ref color j) 0)))
                (set! (vector-ref (vector-ref color j) 0) #f))))
            b)))
  (define (check colors)
    (for ((i (in-range (length colors))))
      (when (canPrint colors)
        (for ((j (in-range (length colors))))
          (if (vector-ref colors j)
              (set! (vector-ref colors j) #f)))))
    (for ((i (in-range (length colors))))
      (when (vector-ref colors i)
        (set! (vector-ref colors i) #f))))
  (let ((colors (vector (vector 0 1) (vector 1 0) (vector 1 1) (vector 0 1))))
    (check colors)
    (for ((i (in-range (length colors))))
      (if (vector-ref colors i)
          (set! (vector-ref colors i) #f))))
    (for ((i (in-range (length colors))))
      (when (vector-ref colors i)
        (set! (vector-ref colors i) #f))))
    (for ((i (in-range (length colors))))
      (when (vector-ref colors i)
        (set! (vector-ref colors i) #f))))
    (for ((i (in-range (length colors))))
      (when (vector-ref colors i)
        (set! (vector-ref colors i) #f))))
    (for ((i (in-range (length colors))))
      (when (vector-ref colors i)
        (set! (vector-ref colors i) #f))))
    (for ((i (in-range (length colors))))
      (when (vector-ref colors i)
        (set! (vector-ref colors i) #f))))
    (for ((i (in-range (length colors))))
      (when (vector-ref colors i)
        (set! (vector-ref colors i) #f))))
    (for ((i (in-range (length colors))))
      (when (vector-ref colors i)
        (set! (vector-ref colors i) #f))))
    (define ans #t)
    (for ((i (in-range (length colors))))
      (when (vector-ref colors i)
        (set! ans #f)))
    ans))

(define (strangePrinter colors)
  (isPrintable colors))

(define (strangePrinterII color)
  (strangePrinter color))