(define (best-team-score scores ages)
  (define n (length scores))
  (define players (map list scores ages))
  (define sorted-players (sort players (lambda (a b) (or (> (second a) (second b)) (and (= (second a) (second b)) (> (first a) (first b)))))))
  (define dp (make-vector n 0))
  (for ([i (in-range n)])
    (vector-set! dp i (first (vector-ref sorted-players i))))
  (for ([i (in-range 1 n)])
    (for ([j (in-range i)])
      (when (<= (second (vector-ref sorted-players j)) (second (vector-ref sorted-players i)))
        (vector-set! dp i (max (vector-ref dp i) (+ (vector-ref dp j) (first (vector-ref sorted-players i))))))))
  (apply max (vector->list dp)))

(define (bestTeamWithNoConflicts scores ages)
  (best-team-score scores ages))