(define (areConnected n threshold edges queries)
  (define graph (make-vector (+ n 1) '()))
  (for ([edge edges])
    (let ([u (car edge)] [v (cadr edge)])
      (when (and (>= u threshold) (>= v threshold))
        (vector-set! graph u (cons v (vector-ref graph u)))
        (vector-set! graph v (cons u (vector-ref graph v))))))
  (define (dfs visited node)
    (set! visited (cons node visited))
    (for ([neighbor (vector-ref graph node)])
      (unless (member neighbor visited)
        (dfs visited neighbor)))
    visited)
  (define components '())
  (define visited (make-vector (+ n 1) #f))
  (for ([i (in-range 1 (+ n 1))])
    (when (and (not (vector-ref visited i)) (>= i threshold))
      (let ([component (dfs '() i)])
        (for ([node component])
          (vector-set! visited node #t))
        (set! components (cons (set component) components)))))
  (map (lambda (query)
         (let ([u (car query)] [v (cadr query)])
           (some (lambda (component)
                   (and (set-member? component u)
                        (set-member? component v)))
                 components)))
       queries))