(define (furthest-building heights bricks ladders)
  (define (can-reach-furthest heights bricks ladders)
    (define used-ladders 0)
    (define brick-usage '())
    (for-each (lambda (i)
                (when (and (< i (length heights)) 
                           (< (list-ref heights i) (list-ref heights (+ i 1))))
                  (define diff (- (list-ref heights (+ i 1)) (list-ref heights i)))
                  (if (and (> diff bricks) (< used-ladders ladders))
                      (begin
                        (set! used-ladders (+ used-ladders 1))
                        (set! brick-usage (cons diff brick-usage)))
                      (if (> diff bricks)
                          (return #f)
                          (set! bricks (- bricks diff)))))
                (when (>= i (length heights))
                  (return #t)))
              (range (sub1 (length heights))))
    #t)

  (define (binary-search lo hi)
    (if (< lo hi)
        (let ((mid (quotient (+ lo hi) 2)))
          (if (can-reach-furthest (sublist heights 0 (add1 mid)) bricks ladders)
              (binary-search (add1 mid) hi)
              (binary-search lo mid)))
        lo))

  (binary-search 0 (sub1 (length heights))))