(define (minimum-removals A)
  (define (lis seq)
    (define n (length seq))
    (define dp (make-vector n 1))
    (for ((i (in-range n)))
      (for ((j (in-range i)))
        (when (> (vector-ref seq i) (vector-ref seq j))
          (vector-set! dp i (max (vector-ref dp i) (+ 1 (vector-ref dp j)))))))
    (apply max (vector->list dp)))

  (define (lds seq)
    (define n (length seq))
    (define dp (make-vector n 1))
    (for ((i (in-range n)))
      (for ((j (in-range i)))
        (when (> (vector-ref seq j) (vector-ref seq i))
          (vector-set! dp i (max (vector-ref dp i) (+ 1 (vector-ref dp j)))))))
    (apply max (vector->list dp)))

  (define n (length A))
  (define max-lis (lis A))
  (define max-lds (lds (vector->list (vector-reverse (list->vector A)))))
  (- n (+ max-lis max-lds 1)))

(minimum-removals (vector 2 1 1 5 6 2 3 1))