(define (maxKSumPairs nums k)
  (define counts (make-hash))
  (for-each (lambda (num) 
              (hash-update! counts num (lambda (x) (+ x 1)) 0)) 
            nums)
  (define result 0)
  (for-each (lambda (num)
              (when (hash-has-key? counts num)
                (let ((complement (- k num)))
                  (when (hash-has-key? counts complement)
                    (define pairs (min (hash-ref counts num) (hash-ref counts complement)))
                    (set! result (+ result pairs))
                    (hash-set! counts num 0)
                    (hash-set! counts complement 0))))))
            nums)
  result)