(define (boxDelivering boxes ports maxBoxes maxWeight)
  (define n (length boxes))
  (define dp (make-vector (+ n 1) 0))
  (define weight 0)
  (define boxes-count 0)
  (define last-port -1)

  (for ([i (in-range 1 (+ n 1))])
    (set! weight (+ weight (vector-ref boxes (- i 1 0))))
    (set! boxes-count (+ boxes-count 1))

    (when (not (= (vector-ref ports (- i 1 0)) last-port))
      (set! last-port (vector-ref ports (- i 1 0)))
      (set! dp[i] (+ (if (> i 1) (vector-ref dp (- i 1)) 0) 1)))
      (set! boxes-count 1)
      (set! weight (vector-ref boxes (- i 1 0))))

    (when (or (> boxes-count maxBoxes) (> weight maxWeight))
      (set! boxes-count 1)
      (set! weight (vector-ref boxes (- i 1 0)))
      (set! dp[i] (+ (if (> i 1) (vector-ref dp (- i 1)) 0) 1)))
      (for ([j (in-range (- i 1) 0 -1)])
        (when (and (<= (+ (vector-ref boxes (- j 1)) weight) maxWeight)
                   (<= (+ (vector-ref boxes (- j 1)) boxes-count) maxBoxes))
          (set! dp[i] (min (vector-ref dp i) (+ (if (> j 1) (vector-ref dp j) 0) 1)))
          (set! weight (+ weight (vector-ref boxes (- j 1 0))))
          (set! boxes-count (+ boxes-count 1))))))

  (vector-ref dp n))