(define (letter-combinations digits)
  (define mappings '((2 . ("a" "b" "c"))
                     (3 . ("d" "e" "f"))
                     (4 . ("g" "h" "i"))
                     (5 . ("j" "k" "l"))
                     (6 . ("m" "n" "o"))
                     (7 . ("p" "q" "r" "s"))
                     (8 . ("t" "u" "v"))
                     (9 . ("w" "x" "y" "z"))))

  (define (combos prefix remaining)
    (if (null? remaining)
        (list prefix)
        (let* ((digit (car remaining))
               (letters (cdr (assoc digit mappings))))
          (apply append (map (lambda (letter) (combos (string-append prefix letter) (cdr remaining))) letters)))))

  (if (string=? digits "")
      '()
      (combos "" (map string->number (string->list digits)))))