(define (count-good-meals deliciousness)
  (define mod 1000000007)
  (define count (make-hash))
  (for-each (lambda (x) (hash-set! count x (+ 1 (hash-ref count x 0 0)))) deliciousness)
  (define good-meal-count 0)
  (for-each (lambda (x)
              (for-each (lambda (y)
                          (when (= (bitwise-and x y) y)
                            (set! good-meal-count (mod (+ good-meal-count (mod (* (hash-ref count x 0) (hash-ref count y 0)) mod) ) mod))))
                        (hash-keys count)))
            (hash-keys count))
  (mod good-meal-count mod))

(define (countGoodMeals deliciousness)
  (count-good-meals deliciousness))