(define (ways-to-split-array nums)
  (define n (length nums))
  (define prefix-sum (vector->list (vector (apply + nums))))
  (for ([i (in-range 1 n)])
    (set! (list-ref prefix-sum i) (+ (list-ref prefix-sum (- i 1)) (list-ref nums (- i 1)))))
  (define total (list-ref prefix-sum (- n 1)))
  (define count 0)
  (for ([i (in-range 1 (- n 1))])
    (when (and (>= (list-ref prefix-sum i) (/ total 3))
               (<= (list-ref prefix-sum i) (/ total 3)))
      (set! count (+ count (length (filter (lambda (j) (>= (list-ref prefix-sum j) (+ (list-ref prefix-sum i) (/ total 3)))) (in-range i (+ 1 n))))))))
  count)