(define (tupleSameProduct nums)
  (define (count-pairs lst)
    (let loop ((lst lst) (count 0) (map (make-hash) '()))
      (if (null? lst)
          count
          (let* ((x (car lst))
                 (rest (cdr lst)))
            (for-each (lambda (y)
                        (let ((product (* x y)))
                          (hash-set! map product (+ (hash-ref map product 0 0) 1))))
                      rest)
            (loop rest count map)))))
  (define counts (count-pairs nums))
  (define total (apply + (hash-map counts (lambda (k v) (* v (- v 1))))))
  (/ total 2))