(define (min-teach n languages friendships)
  (define language-set (make-vector (+ n 1) #f))
  (for ([i (in-range (length languages))])
    (for ([lang (in-list (vector-ref languages i))])
      (vector-set! language-set lang #t)))
  (define friends (make-vector (+ n 1) #f))
  (for ([f (in-list friendships)])
    (define a (first f))
    (define b (second f))
    (when (and (vector-ref language-set a) (vector-ref language-set b))
      (vector-set! friends a #t)
      (vector-set! friends b #t)))
  (define people-to-teach (for/sum ([i (in-range 1 (+ n 1))] #:when (not (vector-ref friends i))) 1))
  people-to-teach)

(define (teach n languages friendships)
  (min-teach n languages friendships))