(define (maxValue events)
  (define n (length events))
  (define dp (make-vector (+ n 1) (make-vector (+ n 1) 0)))
  (for ([i (in-range 1 (+ n 1))])
    (for ([j (in-range 1 (+ n 1))])
      (define current-event (list-ref events (- i 1)))
      (define start (car current-event))
      (define end (cadr current-event))
      (define value (caddr current-event))
      (define prev (find-prev-event events start))
      (set! (vector-ref dp i j) (max (vector-ref dp (- i 1) j)
                                      (if (<= j (car current-event)) 
                                          value 
                                          (+ value (vector-ref dp prev (- j 1))))))))
  (vector-ref dp n n))

(define (find-prev-event events start-time)
  (for/fold ([last 0]) ([event events])
    (let ([end (cadr event)])
      (if (<= end start-time)
          (max last (+ 1 (index-of events event)))
          last))))

(define (index-of lst item)
  (for/fold ([index 0]) ([elem lst])
    (if (equal? elem item)
        (begin (set! index (+ index 1)) index)
        (set! index (+ index 1)))))

(maxValue '((1 2 4) (3 4 3) (2 3 4)))