(define (longestPalindromeSubseq s)
  (define n (string-length s))
  (define dp (make-vector n (make-vector n 0)))
  (for ([i (in-range n)])
    (vector-set! dp i i 1))
  (for ([length (in-range 2 (add1 n))])
    (for ([i (in-range (- n length 1))])
      (define j (+ i length))
      (if (char=? (string-ref s i) (string-ref s j))
          (vector-set! dp i j (+ 2 (vector-ref dp (+ i 1) (- j 1))))
          (vector-set! dp i j (max (vector-ref dp i (+ j -1)) (vector-ref dp (+ i 1) j))))))
  (vector-ref dp 0 (- n 1)))

(define (maxPalindromeLengthFromSubsequences s1 s2)
  (define l1 (longestPalindromeSubseq s1))
  (define l2 (longestPalindromeSubseq s2))
  (+ l1 l2))

(define (maximizePalindromeLength s1 s2)
  (maxPalindromeLengthFromSubsequences s1 s2))