(define (countRestrictedPaths n edges)
  (define graph (make-vector (+ n 1) '()))
  (for ([edge edges])
    (let ([u (car edge)] [v (cadr edge)] [w (caddr edge)])
      (vector-set! graph u (cons (list v w) (vector-ref graph u)))
      (vector-set! graph v (cons (list u w) (vector-ref graph v)))))

  (define distances (make-vector (+ n 1) +inf.0))
  (vector-set! distances n 0)

  (define (dijkstra)
    (define pq (make-priority-queue))
    (priority-queue-insert! pq (list 0 n))
    (let loop ()
      (when (not (priority-queue-empty? pq))
        (define-values (dist node) (priority-queue-extract-min! pq))
        (for ([neighbor (vector-ref graph node)])
          (define next-node (car neighbor))
          (define weight (cadr neighbor))
          (when (< (+ dist weight) (vector-ref distances next-node))
            (vector-set! distances next-node (+ dist weight))
            (priority-queue-insert! pq (list (+ dist weight) next-node))))
        (loop))))

  (dijkstra)

  (define (count-ways)
    (define dp (make-vector (+ n 1) 0))
    (vector-set! dp n 1)
    (for ([i (in-range n 0 -1)])
      (for ([neighbor (vector-ref graph i)])
        (define next-node (car neighbor))
        (when (< (vector-ref distances i) (vector-ref distances next-node))
          (vector-set! dp i (+ (vector-ref dp i) (vector-ref dp next-node))))))
    (vector-ref dp 1))

  (count-ways))

(define n 5)
(define edges '((1 2 1) (2 3 2) (3 4 3) (4 5 4) (1 3 5)))
(countRestrictedPaths n edges)