(define (countPoints points queries)
  (define (inside-circle x y radius)
    (<= (+ (* x x) (* y y)) (* radius radius)))
  (map (lambda (q)
         (let ((x (car q))
               (y (cadr q))
               (r (caddr q)))
           (length (filter (lambda (p)
                             (inside-circle (car p) (cadr p) r))
                           points))))
       queries))

(define (countPointsWrapper points queries)
  (countPoints (map (lambda (p) (list (car p) (cadr p))) points)
                 (map (lambda (q) (list (car q) (cadr q) (caddr q))) queries)))