(define (maxFrequency nums k)
  (define sorted (sort nums <))
  (define (can-increment count start end)
    (let loop ((sum 0) (i start) (j start) (count count))
      (if (< i (length sorted))
          (let ((new-sum (+ sum (vector-ref sorted i))))
            (if (>= (+ new-sum (* (add1 count) (vector-ref sorted j))) (+ (vector-ref sorted j) k))
                (loop (+ new-sum (vector-ref sorted i)) (add1 i) j (add1 count))
                (if (>= (+ new-sum (* (add1 count) (vector-ref sorted j))) (+ (vector-ref sorted j) k))
                    (loop sum (add1 j) j count)
                    count)))
          count)))
  (define max-count (can-increment 0 0 0))
  max-count)

(define (solution nums k)
  (maxFrequency nums k))