(define (minSpaceWastedPacking A B)
  (define n (length A))
  (define dp (make-vector (+ n 1) 0))
  (define prefix-sum (vector 0))
  (for ([i (in-range n)])
    (vector-set! prefix-sum (+ i 1) (+ (vector-ref prefix-sum i) (vector-ref A i))))
  (for ([i (in-range n)])
    (define total 0)
    (for ([j (in-range i n)])
      (set! total (+ total (vector-ref A j)))
      (when (<= total B)
        (define wasted (+ (- (* (add1 (- j i)) B) total) (vector-ref dp i)))
        (set! dp (vector-set! dp (add1 j) (if (zero? (vector-ref dp (add1 j))) wasted (min wasted (vector-ref dp (add1 j)))))))))
  (if (zero? (vector-ref dp n)) -1 (vector-ref dp n)))