(define (makeEqual words)
  (define char-count (make-vector 26 0))
  (for-each (lambda (word)
              (for-each (lambda (ch)
                          (vector-set! char-count (- (char->integer ch) (char->integer #\a)) 
                                        (+ 1 (vector-ref char-count (- (char->integer ch) (char->integer #\a)))))))
                        word))
            words)
  (define total-count (apply + (vector->list char-count)))
  (and (zero? (modulo total-count (length words))) (for/for ([i (in-range 26)]) (zero? (modulo (vector-ref char-count i) (length words))))))