(define (findPeakElement matrix)
  (define (binary-search-horizontal row)
    (define (search l r)
      (if (>= l r)
          l
          (let* ((mid (quotient (+ l r) 2))
                 (is-peak? (and (or (= mid 0) (> (matrix-ref matrix mid) (matrix-ref matrix (- mid 1))))
                                (or (= mid (sub1 (vector-length (vector-ref matrix 0)))) (> (matrix-ref matrix mid) (matrix-ref matrix (+ mid 1))))))
                 (next (if is-peak? mid (if (> (matrix-ref matrix mid) (matrix-ref matrix (+ mid 1))) (search l (- mid 1)) (search (+ mid 1) r)))))
            next)))
    (define (matrix-ref m i j) (vector-ref (vector-ref m i) j))
    (define rows (vector-length matrix))
    (define cols (vector-length (vector-ref matrix 0)))
    (define (find-peak l r)
      (if (>= l r)
          (vector l (binary-search-horizontal l))
          (let ((mid (quotient (+ l r) 2)))
            (let ((max-column (binary-search-horizontal mid)))
              (if (or (= max-column 0) (> (matrix-ref matrix mid max-column) (matrix-ref matrix mid (- max-column 1))))
                  (if (or (= max-column (sub1 cols)) (> (matrix-ref matrix mid max-column) (matrix-ref matrix mid (+ max-column 1)))
                      (vector mid max-column)
                      (find-peak l (- mid 1)))
                  (find-peak (+ mid 1) r))))))
    (find-peak 0 (sub1 rows)))