(define (number-of-full-rounds startTime finishTime)
  (define (time-to-minutes time)
    (let* ((parts (map string->number (string-split time ":")))
           (hours (first parts))
           (minutes (second parts)))
      (+ (* hours 60) minutes)))
  (define start-minutes (time-to-minutes startTime))
  (define finish-minutes (time-to-minutes finishTime))
  (if (< finish-minutes start-minutes)
      (+ (- finish-minutes 1440) start-minutes)
      (- finish-minutes start-minutes)))

(define (fullRounds startTime finishTime)
  (number-of-full-rounds startTime finishTime))