(define (rotate-grid grid k)
  (define (rotate-layer layer)
    (let* ((n (length layer))
           (rotated (list->vector (append (vector->list (vector-ref layer (- n 1)))
                                           (subvector layer 0 (- n 1))))))
      (for ([i (in-range (length layer))])
        (vector-set! layer i (vector-ref rotated (modulo (+ i k) n))))
      layer))

  (define (get-layers grid)
    (let loop ((i 0) (layers '()))
      (if (< i (min (length grid) (length (vector-ref grid 0)) 1))
          (let* ((layer (vector (for/list ([j (in-range i (sub1 (- (length grid) i)))])
                                  (vector (for/list ([k (in-range i (sub1 (- (length (vector-ref grid 0) i)))])
                                                  (vector-ref (vector-ref grid j) k))))))
                 (layers (cons layer layers)))
            (loop (add1 i) layers))
          (reverse layers))))

  (define layers (get-layers grid))
  (for ([layer layers])
    (rotate-layer layer))
  (define result (vector (for ([row (in-range (length grid))])
                           (vector (for ([col (in-range (length (vector-ref grid row)))])
                                     (let* ((layer (find-layer row col layers))
                                            (layer-row (modulo (+ row (length layers)) (length layer)))
                                            (layer-col (modulo (+ col (length (vector-ref layer 0))) (length (vector-ref layer 0)))))
                                       (vector-ref (vector-ref layer layer-row) layer-col))))))
  result)

(define (find-layer row col layers)
  (for*/first ([layer layers])
    (when (and (<= (vector-ref layer 0) row)
               (< row (vector-ref layer 1))
               (<= (vector-ref layer 2) col)
               (< col (vector-ref layer 3)))
      layer)))

(define (main)
  (let* ((grid (vector (vector 1 2 3 4)
                       (vector 5 6 7 8)
                       (vector 9 10 11 12)
                       (vector 13 14 15 16)))
         (k 2))
    (rotate-grid grid k)))

(main)