(define (maximum-number s change)
  (define (apply-change s changes)
    (if (null? changes)
        s
        (let* ((index (car changes))
               (digit (string-ref s index))
               (new-digit (if (and (not (= index (length s))) 
                                   (< (string->number (string (string-ref s index))) (string->number (string (car (cdr changes)))))) 
                               (car (cdr changes)) 
                               digit)))
          (apply-change (string-set! s index new-digit) (cdr (cdr changes))))))
  (define (find-changes s)
    (let loop ((i 0) (changes '()))
      (if (< i (string-length s))
          (if (and (>= (string->number (string (string-ref s i))) 0)
                   (< (string->number (string (string-ref s i))) 10))
              (loop (+ i 1) (cons i changes))
              (loop (+ i 1) changes))
          (reverse changes))))
  (let ((changes (find-changes s)))
    (apply-change (string-copy s) (cons changes (list "9")))))

(define (largest-number-after-mutating-substring s change)
  (maximum-number s (map string->number (string->list change))))

(largest-number-after-mutating-substring "1234" "9")