(define (isPrefixString s words)
  (define (helper s words)
    (if (or (null? words) (string=? s ""))
        (string=? s "")
        (let ((word (car words)))
          (if (string-prefix? s word)
              (helper (substring s (string-length word)) (cdr words))
              #f))))
  (helper s words))