(define (num-ways s)
  (define n (string-length s))
  (define (is-valid-prefix prefix)
    (let ((len (string-length prefix)))
      (and (not (= len 0))
           (not (and (= len 1) (char=? (string-ref prefix 0) #\0)))))))

  (define (check-lengths len1 len2 start)
    (let loop ((i 0) (j 0) (index start))
      (if (>= index n)
          (= i 0)
          (let* ((num1 (string->number (substring s start (+ start len1))))
                 (num2 (string->number (substring s (+ start len1) (+ start len1 len2)))))
            (if (or (not (is-valid-prefix (substring s start (+ start len1))))
                    (not (is-valid-prefix (substring s (+ start len1) (+ start len1 len2)))))
                (loop i j (+ start len1))
                (if (= num1 num2)
                    (loop (+ i 1) j (+ start len1))
                    (loop i (+ j 1) (+ start len1)))))))))

  (define count 0)
  (for ((len1 (in-range 1 (quotient n 2))))
    (for ((len2 (in-range 1 (+ 1 (quotient (- n len1) 2)))))
      (when (check-lengths len1 len2 0)
        (set! count (+ count 1)))))
  count)