(define (addTwoNumbers l1 l2)
  (define (list-to-number lst)
    (foldl (lambda (x acc) (+ (* 10 acc) x)) 0 (reverse lst)))
  (define (number-to-list n)
    (if (= n 0) '(0)
        (let loop ((n n) (acc '()))
          (if (= n 0)
              (reverse acc)
              (loop (quotient n 10) (cons (modulo n 10) acc)))))
    )
  (define num1 (list-to-number (map cdr l1)))
  (define num2 (list-to-number (map cdr l2)))
  (number-to-list (+ num1 num2)))