(define (finalValueAfterOperations operations)
  (define final-value 0)
  (for-each (lambda (op)
              (cond ((string=? op "++X") (set! final-value (+ final-value 1)))
                    ((string=? op "X++") (set! final-value (+ final-value 1)))
                    ((string=? op "--X") (set! final-value (- final-value 1)))
                    ((string=? op "X--") (set! final-value (- final-value 1)))))
            operations)
  final-value)