(define (missing-observations observations n)
  (let* ((m (length observations))
         (total-sum (* n (+ 1 n) 0.5))
         (observed-sum (apply + observations))
         (missing-sum (- total-sum observed-sum))
         (missing-count (- n m)))
    (if (= missing-count 0)
        '()
        (list (/ missing-sum missing-count)))))