(define (stoneGameIX stones)
  (define count (make-vector 3 0))
  (for-each (lambda (x) (vector-set! count (modulo x 3) (+ 1 (vector-ref count (modulo x 3))))) stones)
  (let ((c0 (vector-ref count 0))
        (c1 (vector-ref count 1))
        (c2 (vector-ref count 2)))
    (or (and (> c1 0) (> c2 0))
        (and (= c0 0) (or (> c1 2) (> c2 2)))
        (and (> c0 0) (or (= c1 0) (= c2 0))))))