(define (twoOutOfThree nums1 nums2 nums3)
  (define (to-list-set lst)
    (foldl (lambda (x acc) (if (member x acc) acc (cons x acc))) '() lst))
  (define set1 (to-list-set nums1))
  (define set2 (to-list-set nums2))
  (define set3 (to-list-set nums3))
  (define combined (append set1 set2 set3))
  (define count (lambda (x) (+ (if (member x set1) 1 0)
                                (if (member x set2) 1 0)
                                (if (member x set3) 1 0))))
  (define result (filter (lambda (x) (= (count x) 2)) combined))
  (to-list-set result))