(define SimpleBank
  (lambda ()
    (define accounts '())
    (define (create-account accountNumber balance)
      (if (not (assoc accountNumber accounts))
          (begin
            (set! accounts (cons (cons accountNumber balance) accounts))
            #t)
          #f))
    (define (transfer(sender receiver amount)
      (let ((sender-balance (cdr (assoc sender accounts)))
            (receiver-balance (cdr (assoc receiver accounts))))
        (if (and sender-balance receiver-balance (>= sender-balance amount))
            (begin
              (set! accounts (map (lambda (acc)
                                    (cond ((equal? (car acc) sender) (cons sender (- sender-balance amount)))
                                          ((equal? (car acc) receiver) (cons receiver (+ receiver-balance amount)))
                                          (else acc)))
                                  accounts))
              #t)
            #f)))
    (define (deposit(accountNumber amount)
      (let ((account (assoc accountNumber accounts)))
        (if account
            (begin
              (set! accounts (map (lambda (acc)
                                    (if (equal? (car acc) accountNumber)
                                        (cons accountNumber (+ (cdr acc) amount))
                                        acc))
                                  accounts))
              #t)
            #f)))
    (define (withdraw(accountNumber amount)
      (let ((account (assoc accountNumber accounts)))
        (if (and account (>= (cdr account) amount))
            (begin
              (set! accounts (map (lambda (acc)
                                    (if (equal? (car acc) accountNumber)
                                        (cons accountNumber (- (cdr acc) amount))
                                        acc))
                                  accounts))
              #t)
            #f)))
    (define (get-balance(accountNumber)
      (cdr (assoc accountNumber accounts)))
    (lambda (op . args)
      (cond ((equal? op 'create-account) (apply create-account args))
            ((equal? op 'transfer) (apply transfer args))
            ((equal? op 'deposit) (apply deposit args))
            ((equal? op 'withdraw) (apply withdraw args))
            ((equal? op 'get-balance) (apply get-balance args))))))