(define (countHighestScoreNodes parents)
  (define n (length parents))
  (define (count-children node)
    (apply + (map (lambda (i) (if (= (list-ref parents i) node) 1 0)) (range n))))
  (define (dfs node)
    (define children (filter (lambda (i) (= (list-ref parents i) node)) (range n)))
    (define child-sizes (map dfs children))
    (define size (apply + child-sizes))
    (define score (if (null? children)
                     1
                     (apply * (map (lambda (s) (if (= s 0) 1 s)) (cons (- n 1 size) child-sizes)))))
    (set! max-score (max max-score score))
    (set! score-count (if (= score max-score) (+ score-count 1) score-count))
    (+ size 1))

  (define max-score 0)
  (define score-count 0)
  (dfs 0)
  score-count)