(define (minNumberOfSemesters n relations k)
  (define (topological-sort graph)
    (define in-degrees (make-vector n 0))
    (define adj (make-vector n '()))
    (for ([i relations])
      (let ([u (car i)]
            [v (cadr i)])
        (vector-set! adj (sub1 v) (cons (sub1 u) (vector-ref adj (sub1 v))))
        (vector-set! in-degrees (sub1 v) (+ 1 (vector-ref in-degrees (sub1 v))))))
    (define queue (make-queue))
    (for ([i (in-range n)])
      (when (= (vector-ref in-degrees i) 0)
        (enqueue queue i)))
    (define order '())
    (define (process)
      (when (not (empty? queue))
        (define v (dequeue queue))
        (set! order (cons v order))
        (for ([u (vector-ref adj v)])
          (vector-set! in-degrees u (- (vector-ref in-degrees u) 1))
          (when (= (vector-ref in-degrees u) 0)
            (enqueue queue u)))
        (process)))
    (process)
    (reverse order))

  (define order (topological-sort relations))
  (define dp (make-vector n 0))
  (for ([i order])
    (define count (if (= i 0) 1 (max (vector-ref dp (sub1 i)) 0)))
    (for ([j (vector-ref relations)])
      (when (= (car j) (add1 i))
        (define prerequisite (sub1 (cadr j)))
        (set! count (max count (+ (vector-ref dp prerequisite) 1)))))
    (vector-set! dp i count))
  (apply max (vector->list dp)))

(minNumberOfSemesters 4 '((2 1) (3 1) (1 4)) 2)