(define (maximumPathQuality values edges maxTime)
  (define graph (make-hash))
  (for-each (lambda (edge)
              (define u (car edge))
              (define v (cadr edge))
              (define time (caddr edge))
              (hash-set! graph u (cons (list v time) (hash-ref graph u '())))
              (hash-set! graph v (cons (list u time) (hash-ref graph v '())))))
            edges)

  (define (dfs node visited time quality)
    (if (and (equal? time maxTime) (not (hash-ref visited node #f)))
        (begin
          (set! maxQuality (max maxQuality quality))
          (set! visited (hash-set visited node #t)))
        (for-each (lambda (neighbor)
                    (define next-node (car neighbor))
                    (define travel-time (cadr neighbor))
                    (if (<= (+ time travel-time) maxTime)
                        (dfs next-node (hash-set visited node #t) 
                             (+ time travel-time) 
                             (if (equal? node next-node) quality (+ quality (hash-ref values next-node))))))
                  (hash-ref graph node '())))

  (define maxQuality 0)
  (dfs 0 (hash-set) 0 (hash-ref values 0))
  maxQuality)