(define (maxDistance colors)
  (define n (length colors))
  (define first-color (car colors))
  (define last-color (car (reverse colors)))
  (define left (if (equal? first-color last-color) 0 (sub1 n)))
  (define right (if (equal? first-color last-color) 0 (sub1 n)))
  (for/fold ([result 0]) ([i (in-range n)])
    (if (and (not (equal? (list-ref colors i) first-color))
             (not (equal? (list-ref colors i) last-color)))
        (max result (abs (- i left)) (abs (- i right)))
        result)))