(define (countWords words1 words2)
  (define (count-occurrences words)
    (foldl (lambda (word counts)
             (hash-update! counts word (lambda (x) (+ x 1)) 0))
           (make-hash)
           words))
  (define counts1 (count-occurrences words1))
  (define counts2 (count-occurrences words2))
  (define (count-unique-occurrences counts)
    (foldl (lambda (key acc)
             (if (= (hash-ref counts key) 1) 
                 (+ acc 1) 
                 acc))
           0
           (hash-keys counts)))
  (define unique-counts1 (count-unique-occurrences counts1))
  (define unique-counts2 (count-unique-occurrences counts2))
  (define common-counts 
    (foldl (lambda (key acc)
             (if (and (= (hash-ref counts1 key) 1) 
                      (= (hash-ref counts2 key) 1)) 
                 (+ acc 1) 
                 acc))
           0
           (hash-keys counts1)))
  common-counts)