(define (maxFruits fruits k)
  (define (helper left right sum)
    (if (and (>= right (length fruits)) (>= sum k))
        0
        (if (< right (length fruits))
            (let ((new-sum (+ sum (if (< right (length fruits)) (list-ref fruits right) 0))))
              (if (<= new-sum k)
                  (let ((next-fruits (helper left (+ right 1) new-sum)))
                    (max (+ new-sum (if (< left (length fruits)) (list-ref fruits left) 0)) next-fruits))
                  (if (< left right)
                      (let ((next-fruits (helper (+ left 1) right (- sum (list-ref fruits left)))))
                        next-fruits)
                      (helper left right (- sum (list-ref fruits left))))))
            sum)))
  (helper 0 0 0))