(define (recoverArray changed)
  (define (helper offset)
    (let ((map (make-hash)))
      (for-each (lambda (x) (hash-set! map x (+ (hash-ref map x 0) 1))) changed)
      (define (find-pairs)
        (for/fold ([result '()]) ([x changed])
          (if (hash-ref map x 0)
              (begin
                (hash-set! map x (- (hash-ref map x) 1))
                (if (> (hash-ref map (+ x offset)) 0)
                    (begin
                      (hash-set! map (+ x offset) (- (hash-ref map (+ x offset)) 1))
                      (cons (list x (+ x offset)) result))
                    result))
              result)))
      (if (null? (find-pairs))
          '()
          (map car (find-pairs)))))
  (define offsets (list (* 2 (apply max changed)) (* 2 (apply min changed))))
  (for/or ([offset offsets])
    (let ((result (helper offset)))
      (if (and (not (null? result)) (= (length result) (/ (length changed) 2)))
          (map first result)
          #f))))