(define (asteroidCollision asteroids)
  (define (helper stack asteroids)
    (if (null? asteroids)
        stack
        (let ((current (car asteroids)))
          (cond
            ((and (positive? current) (not (null? stack)) (negative? (car stack)))
             (let loop ()
               (if (and (not (null? stack)) (negative? (car stack)))
                   (let ((top (car stack)))
                     (if (> top (abs current))
                         (loop)
                         (if (= top (abs current))
                             (helper (cdr stack) (cdr asteroids))
                             (helper (cdr stack) asteroids)))
                     )
                   (helper (cons current stack) (cdr asteroids))))
            (else (helper (cons current stack) (cdr asteroids)))))))
  (reverse (helper '() asteroids)))