(define (capitalize-title title)
  (define (capitalize-word word)
    (if (>= (string-length word) 2)
        (string-append (string-upcase (substring word 0 1)) (string-downcase (substring word 1)))
        (string-downcase word)))
  (define (process-word word)
    (if (or (= (string-length word) 1) (= (string-length word) 0))
        (string-downcase word)
        (capitalize-word word)))
  (define words (string-split title))
  (define capitalized-words (map process-word words))
  (define title-case (map (lambda (word)
                             (if (or (= (string-length word) 1) (= (string-length word) 0))
                                 (string-downcase word)
                                 (capitalize-word word)))
                           capitalized-words))
  (string-join title-case " "))