(define (find-k-distant-indices nums key k)
  (define n (length nums))
  (define indices '())
  (for ((i (in-range n)))
    (when (or (equal? (list-ref nums i) key)
              (and (> i k) (equal? (list-ref nums (- i k)) key))
              (and (< i (- n k)) (equal? (list-ref nums (+ i k)) key)))
      (set! indices (cons i indices))))
  (sort indices <))