(define (count-ways buildings)
  (define n (length buildings))
  (define prefix-sum (make-vector (+ n 1) 0))
  (for ((i (in-range n)))
    (vector-set! prefix-sum (+ i 1) (+ (vector-ref prefix-sum i) (if (= (list-ref buildings i) 1) 1 0))))
  (define total-ones (vector-ref prefix-sum n))
  (define result 0)
  (for ((i (in-range n)))
    (when (= (list-ref buildings i) 1)
      (define left-ones (vector-ref prefix-sum i))
      (define right-ones (- total-ones left-ones 1))
      (set! result (+ result (* left-ones right-ones)))))
  result)