(define (maximum-total-importance n roads)
  (define importance (make-vector n 0))
  (for-each (lambda (road)
              (vector-set! importance (car road) (+ (vector-ref importance (car road)) 1))
              (vector-set! importance (cadr road) (+ (vector-ref importance (cadr road)) 1)))
            roads)
  (define sorted-importance (sort (vector->list importance) >))
  (define total-importance 0)
  (for-each-index (lambda (idx val)
                    (set! total-importance (+ total-importance (* val (+ idx 1)))))
                  sorted-importance)
  total-importance)