(define (distribute-cookies cookies k)
  (define (backtrack index distribution)
    (if (= index (length cookies))
      (apply max (map (lambda (x) (apply + x)) distribution))
      (define best (infinity))
      (for ([i (in-range k)])
        (set! (list-ref distribution i) (+ (list-ref distribution i) (list-ref cookies index)))
        (set! best (min best (backtrack (+ index 1) distribution)))
        (set! (list-ref distribution i) (- (list-ref distribution i) (list-ref cookies index))))
      best))
  (backtrack 0 (make-vector k 0)))