(define (distinct-names ideas)
  (define idea-set (set ideas))
  (define (count-valid-names first-char)
    (define suffixes (filter (lambda (s) (not (string=? (string (string-ref s 0)) first-char))) ideas))
    (define counts (map (lambda (s) (string->number (substring s 1))) suffixes))
    (length (filter (lambda (s) (not (set-member? idea-set s))) 
                    (map (lambda (s) (string-append (string first-char) s)) suffixes))))
  (define total 0)
  (for-each (lambda (idea)
              (set! total (+ total (count-valid-names (string (string-ref idea 0))))))
            ideas)
  (/ total 2))

(define (distinct-names ideas)
  (distinct-names ideas))