(define (decode-message key message)
  (define mapping (make-vector 26 #\space))
  (define idx 0)
  (for-each (lambda (char)
              (when (and (char? char) (not (= char #\space)))
                (define pos (- (char->integer char) (char->integer #\a)))
                (when (char=? (vector-ref mapping pos) #\space)
                  (vector-set! mapping pos (integer->char (+ (char->integer #\a) idx)))
                  (set! idx (+ idx 1)))))
            (string->list key))
  (apply string (map (lambda (char)
                       (if (char=? char #\space)
                           #\space
                           (vector-ref mapping (- (char->integer char) (char->integer #\a)))))
                     (string->list message)))