(define (count-digit-one n)
  (define (count-ones x)
    (if (= x 0)
        0
        (let ((count 0)
              (factor 1)
              (current x)
              (next 0))
          (while (> current 0)
            (set! next (modulo current 10))
            (set! current (quotient current 10))
            (if (= next 1)
                (set! count (+ count (+ (quotient current 10) (* factor (1+ (modulo (quotient x (expt 10 (add1 (length (number->string current)))) 10)))))))
                (if (> next 1)
                    (set! count (+ count (* (1+ (quotient current 10)) factor)))
                    (set! count (+ count (quotient current 10) (* factor (modulo x (expt 10 (add1 (length (number->string current)))))))))))
            (set! factor (* factor 10)))
          count)))
  (count-ones n))

(count-digit-one 13)