(define (countExcellentPairs nums k)
  (define freq (make-hash))
  (for-each (lambda (x)
              (hash-set! freq x (add1 (hash-ref freq x 0))))
            nums)
  (define bit-counts (map (lambda (x) (integer->bit-count x)) (hash-keys freq)))
  (define max-bits (apply max bit-counts))
  (define count (make-vector (+ max-bits 1) 0))
  (for-each (lambda (b) (vector-set! count b (add1 (vector-ref count b))))
            bit-counts)
  (define result 0)
  (for-each (lambda (b)
              (when (>= (+ b k) 0)
                (set! result (+ result (vector-ref count (+ b k))))))
            (hash-keys freq))
  result)

(define (integer->bit-count n)
  (if (= n 0) 0
      (1+ (integer->bit-count (bitwise-arithmetic-shift-right n 1)))))