(define (valid-partition nums)
  (define n (length nums))
  (define dp (make-vector (+ n 1) #f))
  (vector-set! dp 0 #t)

  (for ([i (in-range 1 (+ n 1))])
    (when (and (>= i 1) (equal? (vector-ref nums (- i 1)) (vector-ref nums (- i 2))))
      (vector-set! dp i (or (vector-ref dp i) (vector-ref dp (- i 2)))))
    (when (and (>= i 2) (equal? (vector-ref nums (- i 1)) (vector-ref nums (- i 2)))
               (equal? (vector-ref nums (- i 1)) (vector-ref nums (- i 3))))
      (vector-set! dp i (or (vector-ref dp i) (vector-ref dp (- i 2)))))
    (when (and (>= i 3) (equal? (vector-ref nums (- i 1)) (vector-ref nums (- i 2)))
               (equal? (vector-ref nums (- i 2)) (vector-ref nums (- i 3))))
      (vector-set! dp i (or (vector-ref dp i) (vector-ref dp (- i 2)))))
  (vector-ref dp n))