(define (min-group-count intervals)
  (define points '())
  (for ([interval intervals])
    (define start (car interval))
    (define end (cadr interval))
    (set! points (cons (list start #t) points))
    (set! points (cons (list end #f) points)))
  (define sorted-points (sort points (lambda (a b) (if (= (car a) (car b))
                                                    (not (cadr a))
                                                    (< (car a) (car b)))))
  (define groups 0)
  (define current-groups 0)
  (for ([point sorted-points])
    (if (cadr point)
        (set! current-groups (+ current-groups 1))
        (set! current-groups (- current-groups 1)))
    (set! groups (max groups current-groups)))
  groups)

(min-group-count '((1 3) (2 4) (3 5) (5 6)))