(define (smallest-subarrays nums)
  (define n (length nums))
  (define result (make-vector n 0))
  (define (max-bitwise-or arr)
    (foldl (lambda (x y) (logior x y)) 0 arr))
  (define (find-lengths)
    (for ([i (in-range n)])
      (define current-or (max-bitwise-or (sublist nums i n)))
      (define j i)
      (define temp-or 0)
      (while (< j n)
        (set! temp-or (logior temp-or (vector-ref nums j)))
        (if (= temp-or current-or)
            (begin
              (vector-set! result i (+ 1 (- j i)))
              (break))
            (set! j (+ j 1))))))
    result)
  (find-lengths)
  (vector->list result))