(define (reverseOddLevels root)
  (define (helper level nodes)
    (if (null? nodes)
        '()
        (if (even? level)
            (cons (map car nodes) (helper (+ level 1) (map cdr nodes)))
            (let* ([vals (map car nodes)]
                   [reversed (reverse vals)])
              (cons reversed (helper (+ level 1) (map cdr nodes)))))))
  (define (build-tree nodes)
    (if (null? nodes)
        '()
        (cons (car nodes) (list (build-tree (cadr nodes)) (build-tree (caddr nodes))))))
  (define (flatten lst)
    (if (null? lst)
        '()
        (append (car lst) (flatten (cdr lst)))))
  (define (update-tree tree levels)
    (if (null? tree) 
        '() 
        (let* ([level (car levels)]
               [updated (if (even? (car level))
                            (car level)
                            (car (cadr level)))])
          (cons updated (map update-tree (cdr tree) levels)))))
  (define levels (helper 0 (list (list root))))
  (define updated-levels (map (lambda (x) (if (null? x) '() (reverse x))) levels))
  (update-tree root updated-levels))