(define (minCostToMakeArrayEqual A target)
  (define n (length A))
  (define sum (apply + A))
  (define total (+ (* n target) (* (length A) (1- target))))
  (define cost (apply + (map (lambda (x) (abs (- x target))) A)))
  (min cost total))

(define (minCost A)
  (define n (length A))
  (define median (if (even? n)
                    (round (/ (+ (list-ref (sort A < (/ n 2))
                                    (quotient n 2))
                                (list-ref (sort A < (/ n 2 -1)))
                               ) 2))
                    (list-ref (sort A < (/ n 2))))
  (minCostToMakeArrayEqual A median))

(define (minCostToMakeArrayEqual A)
  (minCost A))