(define (countPalindromicSubsequences s)
  (define n (string-length s))
  (define dp (make-vector n))
  (for ([i (in-range n)])
    (vector-set! dp i (make-vector n 0)))
  (for ([len (in-range 1 (+ 1 n))])
    (for ([i (in-range (- n len 1) (+ 1 n))])
      (define j (+ i len -1))
      (if (= (string-ref s i) (string-ref s j))
          (begin
            (if (= len 1)
                (vector-set! (vector-ref dp i) j 1)
                (vector-set! (vector-ref dp i) j (+ 2 (vector-ref (vector-ref dp (+ i 1)) j) (vector-ref (vector-ref dp i) (+ j -1)) (if (= (+ i 1) j) 0 1))))
            )
          (vector-set! (vector-ref dp i) j (+ (vector-ref (vector-ref dp (+ i 1)) j) (vector-ref (vector-ref dp i) (+ j -1)) (- (vector-ref (vector-ref dp (+ i 1)) (+ j -1)) (if (= (+ i 1) j) 0 0))))
          ))
      ))
  (vector-ref (vector-ref dp 0) (- n 1)))