(define (minimizeArrayValue nums)
  (define (helper nums)
    (define n (length nums))
    (define max-val (apply max nums))
    (define total 0)
    (for-each (lambda (x)
                (set! total (+ total x)))
              nums)
    (if (<= total max-val n)
        max-val
        (for/fold ([min-possible max-val])
                   ([i (in-range n)])
          (define new-val (max (if (zero? (list-ref nums i)) 
                                    0 
                                    (max (list-ref nums i) 
                                         (if (positive? min-possible) 
                                             (sub1 min-possible) 
                                             min-possible)))))
            (set! min-possible (min min-possible new-val))
            min-possible))))
  (helper nums))