(define (countCollisions directions)
  (define count 0)
  (define n (string-length directions))
  (define lst (string->list directions))
  (for ([i (in-range n)])
    (cond
      [(or (and (= (list-ref lst i) #\L) (and (> i 0) (= (list-ref lst (- i 1)) #\R))) 
           (and (= (list-ref lst i) #\R) (and (< i (- n 1)) (= (list-ref lst (+ i 1)) #\L))) 
           (and (= (list-ref lst i) #\S) (or (and (> i 0) (= (list-ref lst (- i 1)) #\R)) 
                                              (and (< i (- n 1)) (= (list-ref lst (+ i 1)) #\L))))))
        (set! count (+ count 1))))
  count)

(define (countCollisions directions)
  (define lst (string->list directions))
  (define n (length lst))
  (define count 0)
  (for ([i (in-range n)])
    (when (or (and (eq? (list-ref lst i) #\L) (and (> i 0) (eq? (list-ref lst (- i 1)) #\R)))
                (and (eq? (list-ref lst i) #\R) (and (< i (- n 1)) (eq? (list-ref lst (+ i 1)) #\L)))
                (and (eq? (list-ref lst i) #\S) (or (and (> i 0) (eq? (list-ref lst (- i 1)) #\R))
                                                     (and (< i (- n 1)) (eq? (list-ref lst (+ i 1)) #\L)))))
      (set! count (+ count 1))))
  count)