(define (minimum-score s t) 
  (define n (string-length s))
  (define m (string-length t))
  (define dp (make-vector (add1 n) (make-vector (add1 m) +inf.0)))
  (for ([i (in-range (add1 n))])
    (vector-set! dp i 0))
  (for ([j (in-range (add1 m))])
    (vector-set! (vector-ref dp 0) j 0))
  (for ([i (in-range 1 (add1 n))])
    (for ([j (in-range 1 (add1 m))])
      (if (char=? (string-ref s (sub1 i)) (string-ref t (sub1 j)))
          (vector-set! dp i j (min (vector-ref dp (sub1 i) j) (vector-ref dp i (sub1 j)))
          (vector-set! dp i j (min (vector-ref dp (sub1 i) j)
                                    (vector-ref dp i (sub1 j)
                                    (add1 (vector-ref dp (sub1 i) (sub1 j)))))))))
  (define min-score (for/fold ([min +inf.0]) ([i (in-range (add1 n))])
                   (min min (vector-ref dp i m))))
  (if (= min-score +inf.0) -1 min-score))

(minimum-score "abc" "abdc")