(define (merge-arrays A B)
  (define merged (make-hash))
  (for-each (lambda (pair)
              (let ((index (car pair))
                    (value (cadr pair)))
                (hash-set! merged index (+ (hash-ref merged index 0) value))))
            A)
  (for-each (lambda (pair)
              (let ((index (car pair))
                    (value (cadr pair)))
                (hash-set! merged index (+ (hash-ref merged index 0) value))))
            B)
  (define result (hash->list merged))
  (sort result (lambda (x y) (< (car x) (car y)))))

(define (hash->list h)
  (map (lambda (k) (list k (hash-ref h k))) (hash-keys h)))