(define (even-odd-bits n)
  (define even 0)
  (define odd 0)
  (let loop ((num n) (bit 0))
    (if (= num 0)
        (list even odd)
        (begin
          (if (even? bit)
              (set! even (+ even (bitwise-and num 1)))
              (set! odd (+ odd (bitwise-and num 1)))
          )
          (loop (ash num -1) (+ bit 1))
        )
    )
  )
)