(define (smallestMissingValue nums)
  (define (helper nums)
    (define (mark nums)
      (for ([i (in-range (length nums))])
        (let ([n (list-ref nums i)])
          (when (and (>= n 0) (< n (length nums)))
            (set! (list-ref nums n) -1)))))
    (mark nums)
    (for ([i (in-range (length nums))])
      (when (>= (list-ref nums i) 0)
        (return i)))
    (length nums))
  (helper nums))