(define (make-k-subarray-sums-equal arr k)
  (define n (length arr))
  (define total-sum (apply + arr))
  (define target (/ total-sum k))
  (define (can-make-k-sums sum count)
    (if (zero? count)
        (= sum 0)
        (let loop ((i 0) (current-sum 0) (current-count count))
          (cond
            ((= i n) (and (= current-sum 0) (zero? current-count)))
            ((> current-sum target) #f)
            ((= current-sum target) (loop (+ i 1) 0 (- current-count 1)))
            (else (loop (+ i 1) (+ current-sum (list-ref arr i)) current-count))))))
  (can-make-k-sums total-sum k))