(define (modifyGraphEdges n edges)
  (define (find-weight edge)
    (if (equal? (caddr edge) -1)
        (let loop ((w 1))
          (if (or (member w (map (lambda (e) (caddr e)) edges))
                  (or (equal? w (car edge))
                      (equal? w (cadr edge))))
              (loop (+ w 1))
              w))
        (caddr edge)))

  (map (lambda (edge)
         (list (car edge) (cadr edge) (find-weight edge)))
       edges))