(define (maxStrength nums)
  (define (product lst)
    (foldl * 1 lst))
  (define positives (filter positive? nums))
  (define negatives (filter negative? nums))
  (define neg-count (length negatives))
  (if (even? neg-count)
      (product (append positives negatives))
      (product (append positives (butlast negatives)))))