(define (min-painting-cost costs)
  (define n (length costs))
  (define dp (make-vector n 0))
  (vector-set! dp 0 (vector-ref costs 0))
  (for ([i (in-range 1 n)])
    (vector-set! dp i
      (+ (vector-ref costs i)
         (min (if (zero? i) 0 (vector-ref dp (- i 1))) 
              (if (< i 2) 0 (vector-ref dp (- i 2))))))))
  (vector-ref dp (- n 1)))