(define (sum-of-imbalance-numbers nums)
  (define n (length nums))
  (define total-imbalance 0)
  (for ([i (in-range n)])
    (for ([j (in-range i (+ i 1 n))])
      (define subarray (sublist nums i j))
      (define imbalance 0)
      (for ([k (in-range (length subarray))])
        (for ([l (in-range k (+ k 1 (length subarray)))])
          (when (and (< (list-ref subarray k) (list-ref subarray l))
                     (not (= (list-ref subarray k) (list-ref subarray l))))
            (set! imbalance (+ imbalance 1)))))
      (set! total-imbalance (+ total-imbalance imbalance))))
  total-imbalance)

(sum-of-imbalance-numbers '(1 3 2 4))