#lang racket

(define (minEdgeWeightEquilibriumQueries edges queries)
  (define graph (make-hash))
  (for ([edge edges])
    (define a (first edge))
    (define b (second edge))
    (define w (third edge))
    (hash-set! graph a (cons (list b w) (hash-ref graph a '())))
    (hash-set! graph b (cons (list a w) (hash-ref graph b '()))))
  (define (dfs node parent)
    (define weights '())
    (for ([neighbor (hash-ref graph node '())])
      (define next-node (first neighbor))
      (define weight (second neighbor))
      (if (not (= next-node parent))
          (begin
            (define child-weights (dfs next-node node))
            (set! weights (cons weight child-weights)))))
    (set! weights (cons (apply max weights) 0))
    weights)
  (define max-weights (dfs (first (hash-keys graph)) #f))
  (for ([query queries])
    (define x (first query))
    (define y (second query))
    (if (and (hash-has-key? graph x) (hash-has-key? graph y))
        (min (list (hash-ref max-weights x) (hash-ref max-weights y)))
        -1)))

(define edges '((1 2 3) (2 3 2) (2 4 1) (4 5 4)))
(define queries '((1 3) (2 4) (3 5)))
(minEdgeWeightEquilibriumQueries edges queries)