(define (findMinShifts nums)
  (define (count-shifts arr)
    (define (count-bad-shifts arr)
      (define (helper arr prev count)
        (if (null? arr)
            count
            (if (> (car arr) prev)
                (helper (cdr arr) (car arr) count)
                (helper (cdr arr) (car arr) (+ count 1)))))
      (helper arr (car arr) 0))
    (let ((bad-shifts (count-bad-shifts arr)))
      (if (= bad-shifts 0)
          0
          (if (= bad-shifts 1)
              (length arr)
              (if (= bad-shifts (length arr))
                  (length arr)
                  (if (= (car arr) (apply max arr))
                      (length arr)
                      bad-shifts))))))
  (count-shifts nums))

(define (minimumRightShiftsToSort arr)
  (findMinShifts arr))