(define (modifyColumns matrix)
  (define (swap-columns m j1 j2)
    (map (lambda (row) 
           (let ([temp (list-ref row j1)])
             (set! (list-ref row j1) (list-ref row j2))
             (set! (list-ref row j2) temp)))
         m))
  (for ([j (in-range (length (car matrix)))])
    (if (odd? j)
        (set! matrix (swap-columns matrix j (- (length (car matrix)) 1 j)))))
  matrix)