(define (minNumberOfGroups assignments)
  (define (count-groups assignments)
    (define n (length assignments))
    (define dp (make-vector (add1 n) (make-vector (add1 n) 0)))
    (for ([i (in-range n)])
      (for ([j (in-range i)])
        (when (and (not (vector-ref dp (add1 i) (add1 j))) 
                   (not (vector-ref dp (add1 j) (add1 i))))
          (vector-set! dp (add1 i) (add1 j) 1)))
      (for ([j (in-range (add1 n))])
        (vector-set! dp (add1 i) (add1 j) (max (vector-ref dp (add1 i) (add1 j))
                                               (vector-ref dp (add1 j) (add1 i))))))
      (vector-set! dp (add1 i) 0 (add1 i)))
    (define groups 0)
    (for ([i (in-range n)])
      (when (vector-ref dp (add1 i) 0)
        (set! groups (add1 groups))))
    groups))