(define (subarraysDistinctElementSumOfSquares nums)
  (define n (length nums))
  (define total-sum 0)
  (for ([i (in-range n)])
    (define seen (make-hash))
    (define sum-squares 0)
    (for ([j (in-range i n)])
      (hash-set! seen (list-ref nums j) #t)
      (set! sum-squares (+ sum-squares (expt (list-ref nums j) 2)))
      (when (equal? (hash-count seen) (- j i -1))
        (set! total-sum (+ total-sum sum-squares)))))
  total-sum)