(define (min-increment-for-beautiful arr)
  (define n (length arr))
  (define (helper arr)
    (define total 0)
    (for ((i (in-range 1 n)))
      (when (> (list-ref arr i) (list-ref arr (- i 1)))
        (set! total (+ total (- (list-ref arr i) (list-ref arr (- i 1))))))
      (when (= (list-ref arr i) (list-ref arr (- i 1)))
        (set! total (+ total 1))
        (set! (list-ref arr i) (+ (list-ref arr i) 1))))
    total))
  (helper arr))