(define (count-substrings words pattern)
  (define (can-rearrange str p)
    (let ([freq (make-vector 26 0)]
          [p-freq (make-vector 26 0)])
      (for-each (lambda (c) (vector-set! p-freq (- (char->integer c) (char->integer #\a)) (+ 1 (vector-ref p-freq (- (char->integer c) (char->integer #\a))))))
                p)
      (for-each (lambda (c) (vector-set! freq (- (char->integer c) (char->integer #\a)) (+ 1 (vector-ref freq (- (char->integer c) (char->integer #\a))))))
                str)
      (for ([i (in-range 26)])
        (if (> (vector-ref freq i) (vector-ref p-freq i))
            (begin (set! freq (vector 0))
                   (set! p-freq (vector 0))
                   (return #f))))
      #t))

  (define count 0)
  (for-each (lambda (word) 
              (when (can-rearrange word pattern)
                (set! count (+ count 1))))
            words)
  count)

(define (num-of-strings words pattern)
  (count-substrings words pattern))