(define (minNumberOfCoins coins amount)
  (define dp (make-vector (+ amount 1) +inf.0))
  (vector-set! dp 0 0)
  (for ([i (in-range 1 (+ amount 1))])
    (for ([coin coins])
      (when (>= i coin)
        (vector-set! dp i (min (vector-ref dp i) (+ 1 (vector-ref dp (- i coin))))))))
  (define result (vector-ref dp amount))
  (if (= result +inf.0) -1 result))

(define (minCoins coins amount)
  (minNumberOfCoins coins amount))