(define (countCompleteSubstrings s)
  (define (count-char s)
    (foldl (lambda (c acc)
             (hash-update! acc c (lambda (v) (add1 v)) 0))
             (make-hash) s))
  (define char-count (count-char s))
  (define total-unique (hash-count char-count))
  (define (is-complete? sub)
    (= (hash-count (count-char sub)) total-unique))
  (define (count-complete len)
    (for/fold ([count 0]) ([i (in-range 0 (- (string-length s) len 1))])
      (let ([sub (substring s i (+ i len))])
        (if (is-complete? sub)
            (+ count 1)
            count)))
  (for/fold ([total 0] [len 1]) ([len (in-range 1 (+ total-unique 1))])
    (+ total (count-complete len))))