(define (numSubarraysWithSum A S)
  (define (count-subarrays-with-sum sum)
    (define count 0)
    (define prefix-sum 0)
    (define freq (make-hash '((0 . 1))))
    (for-each (lambda (x)
                (set! prefix-sum (+ prefix-sum x))
                (set! count (+ count (hash-ref freq (- prefix-sum sum) 0)))
                (hash-set! freq prefix-sum (+ (hash-ref freq prefix-sum 0) 1)))
              A)
    count)

  (define (count-in-range start end)
    (if (< start 0)
        0
        (- (count-subarrays-with-sum end)
           (count-subarrays-with-sum (- start 1)))))

  (count-in-range (car (last A)) (cadr (last A)))
)

(define (numSubarraysThatMatchPattern A L M)
  (define (count-patterns A L M)
    (define n (length A))
    (define total 0)
    (for ([start (in-range n)])
      (for ([end (in-range start n)])
        (define sum (apply + (sublist A start (+ end 1))))
        (when (and (>= sum L) (<= sum M))
          (set! total (+ total 1)))))
    total)
  (count-patterns A L M)
)