(define (minOperations A B)
  (define n (length A))
  (define total (apply + A))
  (define threshold (+ (/ total 2) 1))
  (define ops (vector-ref (vector (make-vector n 0)) 0))
  (define (helper A B ops total)
    (if (>= total threshold)
        ops
        (let loop ((i 0) (total total) (ops ops))
          (if (= i n)
              (if (>= total threshold)
                  ops
                  (vector-ref (vector (make-vector n 0)) 0))
              (loop (+ i 1) (+ total (if (< (vector-ref B i) (* 2 (vector-ref A i)))
                                         (vector-ref B i)
                                         0))
                    (if (< (vector-ref B i) (* 2 (vector-ref A i)))
                        (+ ops 1)
                        ops))))))
  (helper A B ops total))