(define (most-frequent-ids ids)
  (define counts (make-hash))
  (for-each (lambda (id)
              (hash-set! counts id (+ 1 (hash-ref counts id 0))))
            ids)
  (define max-count (apply max (hash-values counts)))
  (define result '())
  (hash-for-each (lambda (id count)
                   (when (= count max-count)
                     (set! result (cons id result))))
                 counts)
  (sort result <))