(define (shortest-subarray arr k)
  (define n (length arr))
  (define dp (make-vector (add1 n) (lambda () +inf.0)))
  (vector-set! dp 0 0)
  (define min-length +inf.0)
  (for ([i (in-range n)])
    (define or-so-far 0)
    (for ([j i (in-range -1 -1 (-1))])
      (set! or-so-far (logior or-so-far (vector-ref arr j)))
      (when (>= or-so-far k)
        (set! min-length (min min-length (- (add1 i) j))))))
    (for ([j (in-range (add1 n))])
      (when (>= (vector-ref dp j) (add1 i))
        (vector-set! dp j (min (vector-ref dp j) (add1 i))))))
    (for ([j (in-range (add1 n))])
      (when (and (not (= (vector-ref dp j) +inf.0)) (>= (vector-ref dp j) (add1 i)))
        (set! min-length (min min-length (- i j)))))))
  (if (= min-length +inf.0) -1 min-length))

(shortest-subarray (vector 1 2 3 4) 6)