(define (minRectangles points)
  (define (rects points)
    (define unique-points (remove-duplicates points))
    (define rectangles '())
    (for-each (lambda (p1)
                (for-each (lambda (p2)
                            (when (and (not (equal? p1 p2))
                                       (<= (car p1) (car p2))
                                       (<= (cadr p1) (cadr p2)))
                              (set! rectangles (cons (list (car p1) (cadr p1) (car p2) (cadr p2)) rectangles))))
                          unique-points))
              unique-points)
    rectangles)

  (define rects (rects points))
  (length rects))

(define (minRectangles points)
  (minRectangles points))