(define (count-right-triangles points)
  (define (squared-distance p1 p2)
    (+ (sqr (- (car p1) (car p2)))
       (sqr (- (cadr p1) (cadr p2))))

  (define (is-right-triangle p1 p2 p3)
    (let* ((d1 (squared-distance p1 p2))
           (d2 (squared-distance p1 p3))
           (d3 (squared-distance p2 p3))
           (dists (sort (list d1 d2 d3) <)))
      (equal? (+ (car dists) (cadr dists)) (caddr dists))))

  (define (count)
    (define n (length points))
    (define count 0)
    (for ([i (in-range n)])
      (for ([j (in-range n)])
        (for ([k (in-range n)])
          (when (and (not (= i j)) (not (= i k)) (not (= j k)))
            (when (is-right-triangle (list-ref points i)
                                      (list-ref points j)
                                      (list-ref points k))
              (set! count (+ count 1)))))))
    count))

(count-right-triangles points)