(define (permutation-difference s1 s2)
  (define (count-char s)
    (foldl (lambda (c acc)
             (hash-update! acc c (lambda (x) (if x (+ x 1) 1)) 0))
             acc)
           (make-hash) s))
  (define count1 (count-char s1))
  (define count2 (count-char s2))
  (define (char-diff c)
    (abs (- (hash-ref count1 c 0) (hash-ref count2 c 0))))
  (foldl (lambda (c acc) (+ acc (char-diff c))) 0 (hash-keys count1))
)

(define (get-difference s1 s2)
  (permutation-difference s1 s2))