(define (remove-duplicate-letters s)
  (define (helper s seen stack last)
    (if (string-empty? s)
        (string-append (reverse stack))
        (let* ((ch (string-ref s 0))
               (remaining (substring s 1))
               (last-index (string-index remaining ch)))
          (if (or (string-contains? seen ch)
                  (and (not (string-empty? last))
                       (> (string-index last ch)
                          (string-index last (car stack)))))
              (helper remaining seen stack last)
              (begin
                (set! seen (string-append seen (string ch)))
                (set! stack (cons ch stack))
                (helper remaining seen stack (string-append last (string ch))))))))
  (helper s "" '() ""))

(define (removeDuplicateLetters s)
  (remove-duplicate-letters s))