(define (compress s k)
  (define (helper s k)
    (if (or (null? s) (<= k 0))
        (string-length s)
        (let* ((n (string-length s))
               (dp (make-vector (+ n 1) #f)))
          (vector-set! dp 0 0)
          (for/each ([i (in-range 1 (+ n 1))])
            (for/each ([j (in-range i)])
              (let* ((current (substring s j i))
                     (len (string-length current))
                     (count (count-occurrences s j i)))
                (when (<= count k)
                  (vector-set! dp i (if (vector-ref dp j)
                                        (min (vector-ref dp j) 
                                             (+ (vector-ref dp j) 
                                                (if (> count 1) 
                                                    (+ 1 (string-length (number->string count))) 
                                                    0)))
                                        (+ (if (> count 1) 
                                               (+ 1 (string-length (number->string count))) 
                                               0) 
                                           (vector-ref dp j))))))))
          (vector-ref dp n))))

  (define (count-occurrences s start end)
    (let loop ((i start) (count 0))
      (if (>= i end)
          count
          (if (equal? (string-ref s start) (string-ref s i))
              (loop (+ i 1) (+ count 1))
              (loop (+ i 1) count)))))

  (helper s k))