(define (min-area-rect points)
  (define point-set (set points))
  (define (find-rectangle p1 p3)
    (let* ((x1 (car p1)) (y1 (cadr p1))
           (x3 (car p3)) (y3 (cadr p3))
           (p2 (list x1 y3))
           (p4 (list x3 y1)))
      (if (and (set-member? point-set p2) (set-member? point-set p4))
          (* (abs (- x1 x3)) (abs (- y1 y3)))
          #f)))
  (define min-area +inf.0)
  (for ([i (in-range (length points))])
    (for ([j (in-range (+ i 1) (length points))])
      (define area (find-rectangle (list-ref points i) (list-ref points j)))
      (when (and area (< area min-area))
        (set! min-area area))))
  (if (= min-area +inf.0) 0 min-area))