(define (countMonotonicPairs nums)
  (define n (length nums))
  (define count 0)
  (for ([i (in-range n)])
    (for ([j (in-range i)])
      (when (or (<= (list-ref nums i) (list-ref nums j))
                (>= (list-ref nums i) (list-ref nums j)))
        (set! count (+ count 1)))))
  count)

(countMonotonicPairs '(1 2 2 1 3))