(define (count-substrings s k)
  (define (count-with-char-count n)
    (define counts (make-vector 26 0))
    (define (count-substrings-with-n n)
      (define total 0)
      (define left 0)
      (for ([right (in-range (string-length s))])
        (let* ([char-index (- (string-ref s right) #\a)]
               [current-count (+ (vector-ref counts char-index) 1)])
          (vector-set! counts char-index current-count)
          (while (> (apply + (vector->list (vector-map (lambda (x) (if (> x 0) 1 0)) counts))) n)
            (let ([left-char-index (- (string-ref s left) #\a)])
              (vector-set! counts left-char-index (sub1 (vector-ref counts left-char-index)))
              (set! left (add1 left)))
            )
          (set! total (+ total (- right left 1)))
          )
        )
      total)
  (count-substrings-with-n k))