(define (maximum-xor-score nums queries)
  (define n (length nums))
  (define m (length queries))
  (define results (make-vector m 0))
  (define sorted-queries (map (lambda (i) (list (vector-ref queries i 0) (vector-ref queries i 1) i)) (range m)))
  (define sorted-queries (sort sorted-queries (lambda (x y) (< (car x) (car y)))))
  (define (xor-trie-insert trie num)
    (for-each (lambda (bit)
                (set! trie (if (null? trie) (list (list num)) (cons (cons num (car trie)) (cdr trie)))))
              (list-ref (list num) 0)))
  (define (xor-trie-max trie num)
    (define current 0)
    (for-each (lambda (bit)
                (set! current (if (null? trie) current
                                 (if (car trie)
                                     (car trie)
                                     (cdr trie)))))
              (list-ref (list num) 0))
    current)
  (define trie '())
  (define j 0)
  (for-each (lambda (query)
              (define x (car query))
              (define limit (cadr query))
              (while (and (< j n) (<= (car (vector-ref nums j)) limit))
                (xor-trie-insert trie (vector-ref nums j))
                (set! j (+ j 1)))
              (vector-set! results (caddr query) (xor-trie-max trie x)))
            sorted-queries)
  (vector->list results))

(maximum-xor-score (vector 1 2 3 4) (vector (vector 1 2) (vector 2 3)))