(define (maximumMoves board)
  (define (count-pawns row)
    (foldl (lambda (cell acc)
             (if (equal? cell \P)
                 (+ acc 1)
                 acc))
           0 row))
  (define (count-possible-moves row)
    (foldl (lambda (cell acc)
             (if (equal? cell \P)
                 (+ acc (if (or (equal? (vector-ref row (+ 1 (vector-index row cell))) \.)
                                 (equal? (vector-ref row (+ 2 (vector-index row cell))) \.)) 1 0))
                 acc))
           0 row))
  (define pawn-count (apply + (map count-pawns board)))
  (if (= pawn-count 0) 
      0 
      (apply + (map count-possible-moves board))))