(define (find-itinerary tickets)
  (define graph (make-hash))
  (for-each (lambda (ticket)
              (let ((from (car ticket))
                    (to (cadr ticket)))
                (if (hash-has-key? graph from)
                    (hash-set! graph from (cons to (hash-ref graph from)))
                    (hash-set! graph from (list to)))))
            tickets)

  (define result '())
  (define (dfs airport)
    (if (hash-has-key? graph airport)
        (let ((destinations (sort (hash-ref graph airport) string<?)))
          (for-each (lambda (next)
                      (hash-set! graph airport (remove first (hash-ref graph airport)))
                      (set! result (cons airport result))
                      (dfs next)
                      (set! result (cons airport result)))
                    destinations)))

  (dfs "JFK")
  (reverse (cons "JFK" result)))

(define (find-itinerary tickets)
  (let ((result (find-itinerary tickets)))
    (if result (reverse result) '())))