(define (x-sum k arr)
  (define n (length arr))
  (define (prefix-sum)
    (let loop ((i 0) (s 0) (ps '()))
      (if (< i n)
          (loop (+ i 1) (+ s (list-ref arr i)) (cons s ps))
          (reverse ps))))
  (define ps (prefix-sum))
  (define (sum-range l r)
    (if (<= l r)
        (- (list-ref ps r) (if (> l 0) (list-ref ps (- l 1)) 0))
        0))
  (define (compute-sums)
    (let loop ((i 0) (total 0))
      (if (<= i (- n k))
          (loop (+ i 1) (+ total (sum-range i (+ i k -1))))
          total)))
  (compute-sums))

(define (findXSum arr k)
  (x-sum k arr))