(define (maxAreaRect points)
  (define (det p1 p2)
    (if (and (not (equal? p1 p2)))
        (let ([x1 (car p1)] [y1 (cadr p1)]
              [x2 (car p2)] [y2 (cadr p2)])
          (abs (- (* x1 y2) (* x2 y1))))
        0))
  (define (max-area points)
    (define point-set (make-hash))
    (for-each (lambda (pt) (hash-set! point-set (list-ref pt 0) (list-ref pt 1))) points)
    (define max-area 0)
    (for ([i (in-range (length points))])
      (for ([j (in-range (length points))])
        (when (not (= i j))
          (let ([p1 (list-ref points i)] [p2 (list-ref points j)])
            (let ([x1 (car p1)] [y1 (cadr p1)]
                  [x2 (car p2)] [y2 (cadr p2)])
              (when (and (not (= x1 x2)) (not (= y1 y2)))
                (when (and (hash-has? point-set (list x1 y2))
                           (hash-has? point-set (list x2 y1)))
                  (set! max-area (max max-area (det p1 p2))))))))))
    max-area)
  (max-area points))