(define (maxFrequency nums k)
  (define (can-increase x)
    (define total 0)
    (define left 0)
    (for ([right (in-range (length nums))])
      (set! total (+ total (list-ref nums right)))
      (while (> (- (* (+ x 1) (add1 (- right left)))) total)
        (set! total (- total (list-ref nums left)))
        (set! left (add1 left)))
      (when (>= (- (* (+ x 1) (add1 (- right left)))) total)
        (set! max (max max (- right left 1)))))
    max)

  (define max 0)
  (define sorted-nums (sort nums <))
  (for ([x (in-range (add1 (apply max sorted-nums)))])
    (can-increase x))
  max)