(define (maxManhattanDistance A B K)
  (define (manhattan x1 y1 x2 y2)
    (+ (abs (- x1 x2)) (abs (- y1 y2))))
  (define (calculate-max a b)
    (max 
      (manhattan (car a) (cadr a) (car b) (cadr b))
      (manhattan (car a) (cadr a) (+ (car b) K) (+ (cadr b) K))
      (manhattan (+ (car a) K) (+ (cadr a) K) (car b) (cadr b))
      (manhattan (+ (car a) K) (+ (cadr a) K) (+ (car b) K) (+ (cadr b) K))
      (manhattan (car a) (cadr a) (+ (car b) K) (cadr b))
      (manhattan (car a) (cadr a) (car b) (+ (cadr b) K))
      (manhattan (+ (car a) K) (+ (cadr a) K) (car b) (cadr b))
      (manhattan (+ (car a) K) (+ (cadr a) K) (+ (car b) K) (cadr b)))
  (apply max (map (lambda (a) (map (lambda (b) (calculate-max a b)) B)) A)))