(define (total-fruits fruits)
  (define (max-fruits left right)
    (define counts (make-vector 10001 0))
    (define max-fruit 0)
    (define unique-fruits 0)
    (do ((i left (+ i 1)))
        ((> i right))
      (if (= (vector-ref counts (vector-ref fruits i)) 0)
          (set! unique-fruits (+ unique-fruits 1)))
      (vector-set! counts (vector-ref fruits i) (+ (vector-ref counts (vector-ref fruits i)) 1))
      (set! max-fruit (max max-fruit (+ 1 (- i left)))))
    (do ((i left (+ i 1)))
        ((> i right))
      (if (<= unique-fruits 2)
          (set! max-fruit (max max-fruit (+ 1 (- i left)))))
      (if (> (vector-ref counts (vector-ref fruits i)) 1)
          (vector-set! counts (vector-ref fruits i) (- (vector-ref counts (vector-ref fruits i)) 1))
          (begin
            (set! unique-fruits (- unique-fruits 1))
            (set! left (+ left 1))
            (set! i left)
            (for ((j left (+ j 1)))
              (if (= (vector-ref counts (vector-ref fruits j)) 0)
                  (set! unique-fruits (- unique-fruits 1)))
              (if (<= unique-fruits 2)
                  (set! max-fruit (max max-fruit (+ 1 (- j left))))))))
    max-fruit)
  (max-fruits 0 (- (vector-length fruits) 1)))