(define (get-organization-hierarchy employees)
  (define (build-hierarchy emp-list)
    (define emp-map (for/fold ([m '()]) ([emp emp-list])
                        (let ([id (hash-ref emp 'id)]
                              [subordinates (hash-ref emp 'subordinates)])
                          (hash-set m id subordinates))))
    (define (helper id)
      (let ([subordinates (hash-ref emp-map id '())])
        (map (lambda (sub-id)
               (cons sub-id (helper sub-id)))
             subordinates)))
    (hash-map (for/list ([emp emp-list]) (hash-ref emp 'id)) 
              (lambda (id) (helper id))))
  (build-hierarchy employees))