(define (longest-special-path grid)
  (define (valid? x y)
    (and (>= x 0) (< x (length grid))
         (>= y 0) (< y (length (vector-ref grid x)))))

  (define (dfs x y visited)
    (if (not (valid? x y))
        0
        (let* ((current (vector-ref (vector-ref grid x) y))
               (new-visited (cons (list x y) visited))
               (longest 0))
          (for-each (lambda (dx dy)
                      (let ((nx (+ x dx))
                            (ny (+ y dy)))
                        (when (and (valid? nx ny)
                                   (not (member (list nx ny) visited))
                                   (> (vector-ref (vector-ref grid nx) ny) current))
                          (set! longest (max longest (dfs nx ny new-visited))))))
                    (list 1 0 -1 0 0 1 0 -1))
          (+ 1 longest))))

  (define max-length 0)
  (for-each (lambda (i)
              (for-each (lambda (j)
                          (when (> (vector-ref (vector-ref grid i) j) 0)
                            (set! max-length (max max-length (dfs i j '())))))
                        (range (length (vector-ref grid i)))))
            (range (length grid)))
  max-length)

(define grid (vector (vector 1 2 3) (vector 4 5 6) (vector 7 8 9)))
(longest-special-path grid)