(define (intersect nums1 nums2)
  (define counts (make-hash))
  (for ([num nums1])
    (hash-update! counts num (lambda (x) (add1 x)) 1))
  (define result '())
  (for ([num nums2])
    (when (hash-has-key? counts num)
      (define count (hash-ref counts num))
      (when (> count 0)
        (set! result (cons num result))
        (hash-set! counts num (sub1 count)))))
  (reverse result))