(define (mostCommonResponse responses)
  (define counts (make-hash))
  (for-each (lambda (response)
              (hash-set! counts response (+ 1 (hash-ref counts response 0))))
            responses)
  (define max-count 0)
  (define most-common-response '())
  (hash-for-each (lambda (key value)
                   (when (> value max-count)
                     (set! max-count value)
                     (set! most-common-response key)))
                 counts)
  most-common-response)