(define (maxWeightedKEdgePath edges k)
  (define graph (make-hash))
  (for-each (lambda (edge)
              (let ((u (car edge))
                    (v (cadr edge))
                    (w (caddr edge)))
                (hash-set! graph u (cons (list v w) (hash-ref graph u '())))
                (hash-set! graph v (cons (list u w) (hash-ref graph v '())))))
            edges)
  (define (dfs node visited k)
    (if (zero? k)
        0
        (apply max (cons 0
                        (for/list ((neighbor (hash-ref graph node '()))
                                   #:when (not (member (car neighbor) visited)))
                          (+ (cadr neighbor)
                             (dfs (car neighbor) (cons (car neighbor) visited) (sub1 k)))))))
  (apply max (for/list ((start (hash-keys graph)))
               (dfs start (list start) k))))