(define (count-ways edges)
  (define mod 1000000007)
  (define n (+ 1 (apply max (apply append edges))))
  (define adj (make-vector n '()))
  (for ([e edges])
    (let ([u (car e)] [v (cadr e)])
      (vector-set! adj u (cons v (vector-ref adj u)))
      (vector-set! adj v (cons u (vector-ref adj v)))))
  (define (dfs node parent)
    (define count 1)
    (for ([neighbor (vector-ref adj node)])
      (when (not (= neighbor parent))
        (define subcount (dfs neighbor node))
        (set! count (+ count subcount))))
    count)
  (define total-ways (modulo (dfs 0 -1) mod))
  (modulo (expt 2 total-ways) mod))

(define (numberOfWays edges)
  (count-ways edges))