(define (seasonal-sales-analysis sales)
  (define (group-by-month sales)
    (foldl (lambda (sale acc)
             (let* ((month (second sale))
                    (amount (first sale)))
               (if (assoc month acc)
                   (begin
                     (set-cdr! (assoc month acc) (+ (cdr (assoc month acc)) amount))
                     acc)
                   (cons (cons month amount) acc))))
           '() sales))
  (define (average sales)
    (if (null? sales) 0
        (/ (foldl (lambda (x acc) (+ x acc)) 0 (map cdr sales))
           (length sales)))
    )
  (define grouped-sales (group-by-month sales))
  (let ((avg (average grouped-sales)))
    (map (lambda (x)
           (if (>= (cdr x) avg) (car x) '()))
         grouped-sales)))