(define (maxSumSubmatrix matrix k)
  (define (max-sum-rectangle row-start row-end)
    (let* ((n (length (vector-ref matrix 0)))
           (sums (make-vector n 0))
           (max-sum -1))
      (for ([col (in-range n)])
        (for ([row (in-range row-start (+ row-end 1))])
          (vector-set! sums col (+ (vector-ref sums col) (vector-ref (vector-ref matrix row) col))))
        (let ((current-max (find-max-sum sums k)))
          (when (and current-max (<= current-max k))
            (set! max-sum (max max-sum current-max)))))
      max-sum))

  (define (find-max-sum sums k)
    (let* ((sorted (sort sums <))
           (prefix-sums (vector->list (foldl (lambda (acc x) (cons (+ x (if (null? acc) 0 (car acc))) acc)) '(0) sorted))))
           (result -1))
      (for ([x (in-range (length prefix-sums))])
        (for ([y (in-range x)])
          (let ((target (- (vector-ref prefix-sums x) k)))
            (when (and (<= target (car prefix-sums)) (>= (vector-ref prefix-sums y) target))
              (set! result (max result (- (vector-ref prefix-sums x) (vector-ref prefix-sums y))))))))
      result))

  (define rows (length matrix))
  (define max-sum -1)
  (for ([row-start (in-range rows)])
    (for ([row-end (in-range row-start rows)])
      (let ((current-max (max-sum-rectangle row-start row-end)))
        (when (and current-max (<= current-max k))
          (set! max-sum (max max-sum current-max))))))
  max-sum)