(define (k-smallest-pairs nums1 nums2 k)
  (define (pair-sum p1 p2)
    (list (+ (car p1) (car p2)) p1 p2))
  (define pq (make-queue))
  (for ([i (in-range (min (length nums1) k))])
    (for ([j (in-range (min (length nums2) k))])
      (enqueue! pq (pair-sum (list-ref nums1 i) (list-ref nums2 j)))))
  (define result '())
  (for ([_ (in-range k)])
    (if (empty? pq)
        (break))
    (define smallest (dequeue! pq))
    (set! result (cons (list (second smallest) (third smallest)) result))
    (define next-index (add1 (index-of nums2 (third smallest))))
    (for ([j (in-range next-index (min (length nums2) (+ next-index k)))])
      (enqueue! pq (pair-sum (second smallest) (list-ref nums2 j)))))
  (reverse result))