(define (decodeString s)
  (define (helper s index)
    (define (get-number)
      (let loop ((i index) (num 0))
        (if (and (< i (string-length s)) (char-numeric? (string-ref s i)))
            (loop (+ i 1) (+ (* num 10) (- (char->integer (string-ref s i)) (char->integer #\0))))
            (values num i)))
    (define (get-string)
      (let loop ((i index) (result '()))
        (cond
          ((= i (string-length s)) (list->string (reverse result)))
          ((char=? (string-ref s i) #\]) (values (list->string (reverse result)) (+ i 1)))
          (else (loop (+ i 1) (cons (string-ref s i) result))))))
    (define (get-decoded)
      (let-values (((num new-index) (get-number)))
        (let-values (((decoded new-index) (get-string)))
          (values (string-append (make-string num decoded) (helper s new-index)) new-index))))
    (if (< index (string-length s))
        (let-values (((decoded new-index) (get-decoded)))
          (string-append decoded (helper s new-index)))
        "")))