(define (reconstructQueue people)
  (define (sort-people p)
    (sort p (lambda (a b)
               (or (> (car a) (car b))
                   (and (= (car a) (car b))
                        (< (cadr a) (cadr b))))))
    )
  (define sorted-people (sort-people people))
  (define result '())
  (for-each (lambda (person)
              (define h (car person))
              (define k (cadr person))
              (set! result (append (take result k) (list person) (drop result k))))
            sorted-people)
  result)

(define (queueReconstructionByHeight people)
  (reconstructQueue people))