(define (findMaximumXOR nums)
  (define (insert trie num)
    (define current trie)
    (for ((i (in-range 31 -1 -1)))
      (define bit (if (zero? (bitwise-and num (ash 1 i))) 0 1))
      (define next (if (= bit 0) 0 1))
      (set! current (if (null? (list-ref current next))
                       (begin (set! (list-ref current next) (list)) (list-ref current next))
                       (list-ref current next)))
      (set! current (list-ref current next)))
    current)

  (define (search trie num)
    (define current trie)
    (define max-xor 0)
    (for ((i (in-range 31 -1 -1)))
      (define bit (if (zero? (bitwise-and num (ash 1 i))) 0 1))
      (define toggle (if (= bit 0) 1 0))
      (if (not (null? (list-ref current toggle)))
          (begin (set! max-xor (bitwise-ior max-xor (ash 1 i)))
                 (set! current (list-ref current toggle)))
          (set! current (list-ref current bit))))
    max-xor)

  (define trie (make-vector 2))
  (for ((num nums))
    (insert trie num))
  (define result 0)
  (for ((num nums))
    (set! result (max result (search trie num))))
  result)