(define (originalDigits s)
  (define counts (make-vector 26 0))
  (for ([c (in-string s)])
    (vector-set! counts (- (char->integer c) (char->integer #\a)) (+ 1 (vector-ref counts (- (char->integer c) (char->integer #\a))))))
  (define (count-digit char count)
    (if (zero? count)
        0
        (begin
          (for ([c (in-string char)])
            (vector-set! counts (- (char->integer c) (char->integer #\a)) (- (vector-ref counts (- (char->integer c) (char->integer #\a))) 1)))
          count)))
  (define digit-counts (vector 0 0 0 0 0 0 0 0 0 0))
  (vector-set! digit-counts 0 (count-digit "zero" (vector-ref counts (- (char->integer #\z) (char->integer #\a)))))
  (vector-set! digit-counts 2 (count-digit "two" (vector-ref counts (- (char->integer #\w) (char->integer #\a)))))
  (vector-set! digit-counts 4 (count-digit "four" (vector-ref counts (- (char->integer #\u) (char->integer #\a)))))
  (vector-set! digit-counts 6 (count-digit "six" (vector-ref counts (- (char->integer #\x) (char->integer #\a)))))
  (vector-set! digit-counts 8 (count-digit "eight" (vector-ref counts (- (char->integer #\g) (char->integer #\a)))))
  (vector-set! digit-counts 3 (count-digit "three" (vector-ref counts (- (char->integer #\h) (char->integer #\a)))))
  (vector-set! digit-counts 5 (count-digit "five" (vector-ref counts (- (char->integer #\f) (char->integer #\a)))))
  (vector-set! digit-counts 7 (count-digit "seven" (vector-ref counts (- (char->integer #\s) (char->integer #\a)))))
  (vector-set! digit-counts 1 (count-digit "one" (vector-ref counts (- (char->integer #\n) (char->integer #\a)))))
  (vector-set! digit-counts 9 (count-digit "nine" (vector-ref counts (- (char->integer #\i) (char->integer #\a)))))
  (define result "")
  (for ([i (in-range 10)])
    (set! result (string-append result (make-string (vector-ref digit-counts i) #\0))))
  result)