(define (number-of-boomerangs points)
  (define (distance-squared p1 p2)
    (+ (expt (- (car p1) (car p2)) 2)
       (expt (- (cadr p1) (cadr p2)) 2)))
  (define (count-boomerangs point)
    (let loop ((distances (hash)))
      (define d (distance-squared point (car points)))
      (hash-set! distances d (add1 (hash-ref distances d 0)))
      (if (null? (cdr points))
          (for/sum ((count (hash-values distances)))
            (* count (sub1 count)))
          (loop (cdr points)))))
  (for/sum ((point points))
    (count-boomerangs point)))