(define (fourSumCount A B C D)
  (define hash (make-hash))
  (for ([a A])
    (for ([b B])
      (hash-set! hash (+ a b) (add1 (hash-ref hash (+ a b) 0)))))
  (define count 0)
  (for ([c C])
    (for ([d D])
      (set! count (+ count (hash-ref hash (- 0 (+ c d)) 0)))))
  count)