(define (permute-unique nums)
  (define (backtrack path used)
    (if (= (length path) (length nums))
        (begin
          (set! result (cons (reverse path) result)))
        (for-each (lambda (i)
                    (unless (or (vector-ref used i)
                                (and (> i 0) 
                                     (= (vector-ref nums i) (vector-ref nums (- i 1))) 
                                     (vector-ref used (- i 1)))))
                      (begin
                        (vector-set! used i #t)
                        (backtrack (cons (vector-ref nums i) path) used)
                        (vector-set! used i #f)))
                  (range (length nums)))))
  (define result '())
  (define nums (vector->list (sort (list->vector nums) <)))
  (backtrack '() (make-vector (length nums) #f))
  result)