(define (totalHammingDistance nums)
  (define n (length nums))
  (define total 0)
  (for ([i (in-range 32)])
    (define count0 0)
    (define count1 0)
    (for ([num nums])
      (if (zero? (bitwise-and num (ash 1 i)))
          (set! count0 (+ count0 1))
          (set! count1 (+ count1 1))))
    (set! total (+ total (* count0 count1))))
  total)