(define (rotate matrix)
  (define n (length matrix))
  (for ([i (in-range n)])
    (for ([j (in-range i n)])
      (let ([temp (list-ref (list-ref matrix i) j)])
        (set! (matrix-ref matrix i j) (list-ref (list-ref matrix j) i))
        (set! (matrix-ref matrix j i) temp))))
  (for ([i (in-range n)])
    (set! (matrix-ref matrix i) (reverse (matrix-ref matrix i)))))