(define (smallest-good-base n)
  (define n (string->number n))
  (define (check-base b)
    (define sum 0)
    (define p 1)
    (let loop ((k 0))
      (set! sum (+ sum p))
      (if (> sum n)
          #f
          (if (= sum n)
              #t
              (loop (+ k 1) (set! p (* p b)))))))
  (define max-k (floor (log n 2)))
  (for/fold ([res ""]) ([k max-k 1 -1])
    (if (check-base (expt 2 k))
        (number->string (sub1 (expt 2 k)))
        res)))

(define (smallest-good-base n)
  (define max-k (floor (log (string->number n) 2)))
  (for/fold ([res ""]) ([k max-k 1 -1])
    (let ([base (expt 2 k)])
      (if (and (check-base base) (string<=? res ""))
          (number->string (sub1 base))
          res))))