(define (solve-n-queens n)
  (define (place-queens col queens)
    (if (= (length queens) n)
        (list (map (lambda (r) (string-append (make-string r #\.) "Q" (make-string (- n r 1) #\.))) queens))
        (for/fold ([results '()]) ([row (in-range n)])
          (if (not (or (member row queens)
                       (member (- row (- (length queens) 1)) (map - queens (in-range (length queens))))
                       (member (+ row (- (length queens) 1)) (map + queens (in-range (length queens))))))
              (place-queens (+ col 1) (append queens (list row)))
              results)))
  (place-queens 0 '()))

(define (solve-n-queens-wrapper n)
  (if (and (number? n) (>= n 1))
      (solve-n-queens n)
      '()))