(define (change amount coins)
  (define dp (make-vector (+ amount 1) 0))
  (vector-set! dp 0 1)
  (for-each (lambda (coin)
              (for-each (lambda (j)
                          (when (>= j coin)
                            (vector-set! dp j (+ (vector-ref dp j) (vector-ref dp (- j coin))))))
                        (range (add1 amount))))
            coins)
  (vector-ref dp amount))