(define (findMaxLength nums)
  (define (helper lst index count-map max-length)
    (if (null? lst)
        max-length
        (let* ((num (car lst))
               (updated-count (if (= num 0) (sub1 count) (add1 count)))
               (updated-max-length (if (hash-has-key? count-map updated-count)
                                       (max max-length (- index (hash-ref count-map updated-count)))
                                       max-length)))
          (hash-set! count-map count index)
          (helper (cdr lst) (add1 index) count-map updated-max-length))))
  (let ((count-map (make-hash)))
    (hash-set! count-map 0 -1)
    (helper nums 0 0 count-map 0)))