(define (findPairs nums k)
  (define (count-pairs nums k)
    (let ([count 0]
          [num-set (make-hash)])
      (for-each (lambda (num)
                  (hash-set! num-set num))
                nums)
      (if (= k 0)
          (for-each (lambda (num)
                      (when (> (hash-ref num-set num 0) 1)
                        (set! count (+ count 1))))
                    (hash-keys num-set))
          (for-each (lambda (num)
                      (when (hash-ref num-set (+ num k) 0)
                        (set! count (+ count 1))))
                    (hash-keys num-set)))
      count))
  (count-pairs nums k))