(define (findCircleNum isConnected)
  (define (dfs node)
    (set! visited (set-add visited node))
    (for-each (lambda (i)
                (when (and (= (list-ref (list-ref isConnected node) i) 1)
                           (not (set-member? visited i)))
                  (dfs i)))
              (range (length isConnected))))

  (define provinces 0)
  (define visited (set))
  (for-each (lambda (i)
              (when (not (set-member? visited i))
                (dfs i)
                (set! provinces (+ provinces 1))))
            (range (length isConnected)))
  provinces)