(define (leastBricks wall)
  (define (count-gaps wall)
    (foldl (lambda (row acc)
             (let ([sum 0])
               (for-each (lambda (brick)
                           (set! sum (+ sum brick))
                           (hash-set! acc sum))
                         row)
               acc))
           (make-hash)
           wall))

  (define gap-count (count-gaps wall))
  (define total-rows (length wall))
  (define max-gaps (apply max (hash-values gap-count)))
  (- total-rows max-gaps))