(define (matrixReshape mat r c)
  (let* ((rows (length mat))
         (cols (length (car mat)))
         (total (+ (* rows cols) 0)))
    (if (or (not (= total (* r c))) (zero? total))
        mat
        (let loop ((i 0) (j 0) (result '()))
          (if (>= i rows)
              (reverse result)
              (let* ((new-i (quotient (+ (* i cols) j) c))
                     (new-j (modulo (+ (* i cols) j) c)))
                (loop (if (= j (- cols 1)) (+ i 1) i)
                      (if (= j (- cols 1)) 0 (+ j 1))
                      (cons (list-ref (list-ref mat i) j) result)))))))))