(define (isValid(s))
  (define (is-tag? s)
    (and (string? s) 
         (string-prefix? "<" s)
         (string-suffix? ">" s)
         (not (string-contains? s " "))))

  (define (get-tag s)
    (substring s 1 (- (string-length s) 1)))

  (define (valid-tag? tag)
    (and (not (string-contains? tag "/"))
         (not (string-contains? tag ">"))))

  (define (pop-tag stack tag)
    (if (and (not (null? stack)) (equal? (car stack) tag))
        (cdr stack)
        '()))

  (define (check-tags stack s)
    (if (string-empty? s)
        (null? stack)
        (let* ((close-tag (string-contains s "</"))
               (open-tag (string-contains s "<"))
               (tag (if close-tag (substring s (+ close-tag 2) (string-index s ">" close-tag))
                        (substring s (add1 open-tag) (string-index s ">" open-tag)))))
          (if (is-tag? tag)
              (if (valid-tag? tag)
                  (if (string-prefix? "</" tag)
                      (check-tags (pop-tag stack (get-tag tag)) (substring s (+ (string-length tag) 1)))
                      (check-tags (cons (get-tag tag) stack) (substring s (+ (string-length tag) 1))))
                  (check-tags stack (substring s (+ (string-length tag) 1)))
              (check-tags stack (substring s (+ (string-length tag) 1)))))))

  (check-tags '() s))