(define (findLHS nums)
  (define counts (make-hash))
  (for-each (lambda (num) (hash-set! counts num (+ 1 (hash-ref counts num 0)))) nums)
  (define max-length 0)
  (for-each (lambda (key)
              (when (hash-contains? counts (+ key 1))
                (define length (+ (hash-ref counts key) (hash-ref counts (+ key 1))))
                (set! max-length (max max-length length))))
            (hash-keys counts))
  max-length)