(define (averageOfLevels root)
  (define (helper nodes)
    (if (null? nodes)
        '()
        (let* ((next-level (apply append (map (lambda (n) (list-ref n 1)) nodes)))
               (sum (apply + (map (lambda (n) (list-ref n 0)) nodes)))
               (avg (/ (exact->inexact sum) (length nodes))))
          (cons avg (helper next-level)))))
  (helper (list (list (exact->inexact (car root)) (cdr root)))))