(define (numDecodings s)
  (define mod 1000000007)
  (define n (string-length s))
  (define dp (make-vector (+ n 1) 0))
  (vector-set! dp 0 1)
  (for ([i (in-range 1 (+ n 1))])
    (define current (string-ref s (- i 1)))
    (define prev (if (> i 1) (string-ref s (- i 2)) #\0))
    (cond
      [(char=? current #\*) 
       (vector-set! dp i (modulo (* (vector-ref dp (- i 1)) 9) mod))
       (when (or (char=? prev #\1) (char=? prev #\2))
         (vector-set! dp i (modulo (+ (vector-ref dp i) (vector-ref dp (- i 2)) 6) mod)))
       (when (char=? prev #\*) 
         (vector-set! dp i (modulo (+ (vector-ref dp i) (vector-ref dp (- i 2)) 15) mod)))
       ]
      [(char=? current #\0) 
       (vector-set! dp i 0)
       (when (or (char=? prev #\1) (char=? prev #\2))
         (vector-set! dp i (vector-ref dp (- i 2))))
       (when (char=? prev #\*) 
         (vector-set! dp i (modulo (+ (vector-ref dp i) (vector-ref dp (- i 2))) 2) mod))
       ]
      [else 
       (vector-set! dp i (modulo (vector-ref dp (- i 1)) mod))
       (when (or (char=? prev #\1) (and (char=? prev #\2) (<= (string->number (string (string-ref s i))) 6)))
         (vector-set! dp i (modulo (+ (vector-ref dp i) (vector-ref dp (- i 2))) mod)))
       (when (char=? prev #\*) 
         (vector-set! dp i (modulo (+ (vector-ref dp i) (vector-ref dp (- i 2))) 9) mod))
       )]))
  (vector-ref dp n))