(define (findMaxAverage nums k)
  (define (sum lst)
    (apply + lst))
  (define max-sum (sum (take nums k)))
  (define current-sum max-sum)
  (for ([i (in-range k (length nums))])
    (set! current-sum (+ current-sum (list-ref nums i) (- (list-ref nums (- i k)))))
    (set! max-sum (max max-sum current-sum)))
  (/ max-sum k))