(define (strangePrinter s)
  (define n (string-length s))
  (define dp (make-vector n (make-vector n 0)))
  (define (helper i j)
    (if (>= i j) 0)
    (if (> (vector-ref dp i j) 0) (vector-ref dp i j))
    (define min-count (if (= i j) 1 (+ 1 (helper i (+ j -1)))))
    (for ([k (in-range (+ i 1) j)])
      (if (char=? (string-ref s i) (string-ref s k))
          (set! min-count (min min-count (helper i (+ k -1)) (helper (+ k 1) j)))))
    (vector-set! dp i j min-count)
    min-count))
  (helper 0 (- n 1)))