(define (isIdealPermutation A)
  (let loop ([i 0] [local-inversions 0] [global-inversions 0])
    (if (= i (length A))
        (= local-inversions global-inversions)
        (let ([current (list-ref A i)])
          (loop (+ i 1)
                (if (and (> i 0) (> current (list-ref A (- i 1)))) 
                    (+ local-inversions 1) 
                    local-inversions)
                (+ global-inversions (length (filter (lambda (x) (> x current)) (sublist A (+ i 1))))))))))

(define (sublist lst start)
  (if (or (= start (length lst)) (null? lst))
      '()
      (cons (list-ref lst start) (sublist lst (+ start 1)))))