(define (isBipartite graph)
  (define (bipartite? node color)
    (if (hash-has-key? colors node)
        (equal? (hash-ref colors node) color)
        (begin
          (hash-set! colors node color)
          (for-each (lambda (neighbor)
                      (if (not (bipartite? neighbor (if (equal? color 1) 2 1)))
                          (set! result #f)))
                    (hash-ref graph node))
          result)))

  (define colors (make-hash))
  (define result #t)
  (for-each (lambda (node)
              (if (not (hash-has-key? colors node))
                  (bipartite? node 1)))
            (hash-keys graph))
  result)

(define (createGraph edges)
  (define graph (make-hash))
  (for-each (lambda (edge)
              (let ((u (car edge))
                    (v (cadr edge)))
                (hash-set! graph u (if (hash-has-key? graph u) (hash-ref graph u) '()))
                (hash-set! graph v (if (hash-has-key? graph v) (hash-ref graph v) '()))
                (set! (hash-ref graph u) (cons v (hash-ref graph u)))
                (set! (hash-ref graph v) (cons u (hash-ref graph v)))))
            edges)
  graph)

(define (bipartiteGraph edges)
  (isBipartite (createGraph edges)))