(define (raceCar target)
  (define (bfs)
    (define queue (list (list 0 1)))
    (define visited (make-hash))
    (hash-set! visited 0 #t)
    (define steps 0)
    (let loop ()
      (when (not (null? queue))
        (define length (length queue))
        (for ([i (in-range length)])
          (define car (car queue))
          (define pos (car car))
          (define speed (cadr car))
          (define new-pos (+ pos speed))
          (define new-speed (* speed 2))
          (define new-speed-reverse (if (= speed 1) -1 1))
          (when (not (hash-ref visited new-pos #f))
            (if (= new-pos target)
                (return steps)
                (when (and (>= new-pos 0) (< new-pos (* 2 target)))
                  (hash-set! visited new-pos #t)
                  (set! queue (append (cdr queue) (list (list new-pos new-speed))))))
            (when (not (hash-ref visited (+ pos new-speed-reverse) #f))
              (hash-set! visited (+ pos new-speed-reverse) #t)
              (set! queue (append (cdr queue) (list (list pos new-speed-reverse)))))))
        (set! steps (+ steps 1))
        (loop))))
  (bfs))