(define (numFriendRequests ages)
  (define (canSendRequest age1 age2)
    (and (> age1 (/ age2 2))
         (< age1 (+ age2 7))))
  (define (countRequests ages)
    (foldl (lambda (age1 acc)
             (+ acc (foldl (lambda (age2 inner-acc)
                             (if (canSendRequest age1 age2)
                                 (+ inner-acc 1)
                                 inner-acc))
                           0 ages)))
           0 ages))
  (countRequests ages))