(define (maxProfitAssignment difficulty profit worker)
  (define tasks (map list difficulty profit))
  (define sorted-tasks (sort tasks (lambda (x y) (> (second x) (second y)))))
  (define sorted-workers (sort worker >))
  (define (assign-tasks workers tasks)
    (define max-profit 0)
    (define current-task 0)
    (for-each (lambda (w)
                (let loop ()
                  (when (and (< current-task (length tasks))
                             (<= (first (list-ref tasks current-task)) w))
                    (set! max-profit (+ max-profit (second (list-ref tasks current-task)))
                    (set! current-task (+ current-task 1))
                    (loop))))
              workers)
    max-profit)
  (assign-tasks sorted-workers sorted-tasks))

(maxProfitAssignment '(2 4 6 8 10) '(10 20 30 40 50) '(4 5 6 7))