(define (large-group-positions s)
  (define result '())
  (define (find-groups start end)
    (when (>= end (string-length s))
      (if (>= (- end start) 3)
          (set! result (cons (list start end) result))))
    (when (< end (string-length s))
      (if (equal? (string-ref s start) (string-ref s end))
          (find-groups start (+ end 1))
          (find-groups (+ start 1) (+ start 2)))))
  (find-groups 0 1)
  (reverse result))

(large-group-positions "abbxxxxzzy")