(define (sum-of-distances-in-tree n edges)
  (define (build-tree edges)
    (define tree (make-vector n '()))
    (for-each (lambda (edge)
                (let ((u (car edge))
                      (v (cadr edge)))
                  (vector-set! tree u (cons v (vector-ref tree u)))
                  (vector-set! tree v (cons u (vector-ref tree v)))))
              edges)
    tree)

  (define (dfs1 node parent)
    (define count 1)
    (define total 0)
    (for-each (lambda (neighbor)
                (when (not (= neighbor parent))
                  (let-values (((sub-count sub-total) (dfs1 neighbor node)))
                    (set! count (+ count sub-count))
                    (set! total (+ total sub-total (+ sub-count)))))
                )
              (vector-ref tree node))
    (values count total))

  (define (dfs2 node parent n total)
    (define result (make-vector n 0))
    (vector-set! result node total)
    (for-each (lambda (neighbor)
                (when (not (= neighbor parent))
                  (let ((child-count (vector-ref counts neighbor)))
                    (let ((child-total (+ (vector-ref result node)
                                           (- n child-count)))))
                    (vector-set! result neighbor child-total)
                    (dfs2 neighbor node n child-total))))
              (vector-ref tree node))
    result)

  (define tree (build-tree edges))
  (define counts (make-vector n 0))
  (define total (dfs1 0 -1))
  (define result (dfs2 0 -1 n (vector-ref counts 0)))
  result)