(define (new21Game N K W)
  (define dp (make-vector (+ N 1) 0))
  (vector-set! dp 0 1.0)
  (for ([i (in-range 1 (+ N 1))])
    (for ([j (in-range 1 (min W i))])
      (vector-set! dp i (+ (vector-ref dp i) (* (vector-ref dp (- i j)) (/ 1.0 W)))))
    (if (< i K)
        (vector-set! dp i (+ (vector-ref dp i) (vector-ref dp (- i 1))))))
  (for ([i (in-range K (+ N 1))])
    (if (>= i K)
        (vector-set! dp i (+ (vector-ref dp i) (vector-ref dp (- i 1))))))
  (apply + (for/list ([i (in-range K (+ N 1))]) (vector-ref dp i))))

(new21Game N K W)