(define (canVisitAllRooms rooms)
  (define (dfs visited room)
    (unless (vector-ref visited room)
      (vector-set! visited room #t)
      (for-each (lambda (key) (dfs visited key)) (vector-ref rooms room))))
  (let ((visited (make-vector (vector-length rooms) #f)))
    (dfs visited 0)
    (for/all ([i (in-range (vector-length rooms))])
      (vector-ref visited i))))