(define (superEggDrop k n)
  (define (dp k n)
    (if (or (= n 0) (= k 1)) n)
    (define (helper eggs floors)
      (if (= eggs 1) floors)
      (if (= floors 0) 0)
      (define low 1)
      (define high floors)
      (define result floors)
      (while (<= low high)
        (define mid (quotient (+ low high) 2))
        (define break (helper (- eggs 1) (- mid 1)))
        (define not-break (helper eggs (- floors mid)))
        (define worst-case (+ 1 (max break not-break)))
        (if (< worst-case result)
            (set! result worst-case)
            (set! high (- mid 1)))
        (set! low (+ mid 1)))
      result)
    (helper k n))
  (dp k n))

(superEggDrop 2 100)