(define (subarrayBitwiseORs A)
  (define (helper arr)
    (define result (make-hash))
    (define current-or 0)
    (for-each (lambda (x)
                (set! current-or (bitwise-ior current-or x))
                (hash-set! result current-or #t))
              arr)
    (hash-keys result))

  (define unique-or (make-hash))
  (for-each (lambda (x)
              (define ors (helper (list x)))
              (for-each (lambda (o) (hash-set! unique-or o #t)) ors))
            A)
  (hash-keys unique-or))