(define (sortArrayByParityII A)
  (define n (length A))
  (define result (make-vector n))
  (define even-index 0)
  (define odd-index 1)
  (for-each (lambda (x)
              (if (even? x)
                  (vector-set! result even-index x)
                  (vector-set! result odd-index x))
              (if (even? x)
                  (set! even-index (+ even-index 2))
                  (set! odd-index (+ odd-index 2))))
            A)
  (vector->list result))