(define (min-area-rectangle points)
  (define point-set (make-hash))
  (for-each (lambda (point)
              (hash-set! point-set (car point) (cadr point)))
            points)
  (define min-area +inf.0)
  (define (check-rectangle p1 p2)
    (let ((area (abs (- (car p1) (car p2)) * (- (cadr p1) (cadr p2)))))
      (when (and (< area min-area) (not (= area 0)))
        (set! min-area area))))
  (for-each (lambda (p1)
              (for-each (lambda (p2)
                          (when (and (not (= p1 p2))
                                     (hash-ref point-set (car p1) #f)
                                     (hash-ref point-set (car p2) #f))
                            (check-rectangle p1 p2)))
                        points))
            points)
  (if (= min-area +inf.0) 0 min-area))