(define (sumEvenAfterQueries A queries)
  (define (sum-even lst)
    (foldl (lambda (x acc) (if (even? x) (+ x acc) acc)) 0 lst))
  (define even-sum (sum-even A))
  (define results '())
  (for ([i (in-range (length queries))])
    (define idx (car (list-ref queries i)))
    (define val (cadr (list-ref queries i)))
    (set! A (vector-set! A idx (+ (vector-ref A idx) val)))
    (set! even-sum (if (even? (+ (vector-ref A idx) val))
                       (+ even-sum val)
                       (if (even? (vector-ref A idx))
                           (+ even-sum (vector-ref A idx))
                           (- even-sum (vector-ref A idx)))))
    (set! results (append results (list even-sum))))
  results)

(define (sumEvenAfterQueries A queries)
  (sumEvenAfterQueries (vector->list A) (map (lambda (x) (vector->list x)) queries)))