(define (numBreakfastCombinations staple drinks x)
  (define mod (expt 10 9))
  (define staples (filter (lambda (s) (<= s x)) staple))
  (define drinks (filter (lambda (d) (<= d x)) drinks))
  (define count-staples (length staples))
  (define count-drinks (length drinks))
  (define (count-ways lst limit)
    (define (count-helper lst limit)
      (if (null? lst)
          1
          (let ((first (car lst)))
            (if (<= first limit)
                (+ (count-helper (cdr lst) limit)
                   (count-helper (cdr lst) (- limit first)))
                (count-helper (cdr lst) limit)))))
    (count-helper lst limit))
  (modulo (+ (count-ways staples x)
              (count-ways drinks x))
              mod))