(define (permuteUnique nums)
  (define (backtrack path used)
    (if (= (length path) (length nums))
      (begin (set! result (cons (list->vector path) result)))
      (for-each (lambda (i)
                  (when (not (vector-ref used i))
                    (when (or (= i 0) (not (= (vector-ref nums i) (vector-ref nums (- i 1)))))
                      (vector-set! used i #t)
                      (backtrack (cons (vector-ref nums i) path) used)
                      (vector-set! used i #f))))
                (iota (vector-length nums))))
  (set! result '())
  (set! nums (vector (sort (list->vector nums) <)))
  (set! used (make-vector (vector-length nums) #f))
  (backtrack '() used)
  (map vector->list result))

(define (permute-unique-nums nums)
  (permuteUnique nums))