(define (increasing-order-search-tree root)
  (define (inorder node)
    (if (null? node)
        '()
        (append (inorder (tree-left node))
                (list (tree-val node))
                (inorder (tree-right node)))))
  (define vals (inorder root))
  (define (build-tree vals)
    (if (null? vals)
        '()
        (cons (car vals) (build-tree (cdr vals)))))
  (build-tree vals))