(define (min-moves-to-sort books)
  (define n (length books))
  (define dp (make-vector (add1 n) (lambda () (make-vector (add1 n) 0))))
  (for ([i (in-range n)])
    (for ([j (in-range i)])
      (when (< (vector-ref books i) (vector-ref books j))
        (vector-set! (vector-ref dp (+ i 1)) (+ j 1) (max (vector-ref (vector-ref dp (+ i 1)) (+ j 1)) (+ 1 (vector-ref (vector-ref dp (+ i 1)) j)))))))
  (for ([i (in-range n)])
    (for ([j (in-range n)])
      (when (< (vector-ref books i) (vector-ref books j))
        (vector-set! (vector-ref dp (+ j 1)) (+ i 1) (max (vector-ref (vector-ref dp (+ j 1)) (+ i 1)) (+ 1 (vector-ref (vector-ref dp (+ j 1)) i)))))))
  (- n (apply max (vector->list (vector-ref dp n)))))