(define MedianFinder
  (let ((max-heap '())
        (min-heap '()))
    (lambda ()
      (define (addNum num)
        (if (or (null? max-heap) (<= num (car max-heap)))
            (set! max-heap (cons num max-heap))
            (set! min-heap (cons num min-heap)))
        (set! max-heap (sort max-heap >))
        (set! min-heap (sort min-heap <))
        (if (> (length max-heap) (+ (length min-heap) 1))
            (let ((moved (car max-heap)))
              (set! max-heap (cdr max-heap))
              (set! min-heap (cons moved min-heap)))
            (if (> (length min-heap) (length max-heap))
                (let ((moved (car min-heap)))
                  (set! min-heap (cdr min-heap))
                  (set! max-heap (cons moved max-heap))))))
      (define (findMedian)
        (if (= (length max-heap) (length min-heap))
            (/ (+ (car max-heap) (car min-heap)) 2.0)
            (car max-heap)))
      (define (getMaxHeap) max-heap)
      (define (getMinHeap) min-heap)
      (list addNum findMedian))))

(define medianFinder (MedianFinder))

(define (addNum num)
  ((car medianFinder) num))

(define (findMedian)
  ((cadr medianFinder)))