(define (peakIndexInMountainArray A)
  (define (binary-search left right)
    (if (> left right)
        (sub1 left)
        (let ([mid (quotient (+ left right) 2)])
          (if (> (vector-ref A mid) (vector-ref A (add1 mid)))
              (binary-search left (sub1 mid))
              (binary-search (add1 mid) right)))))
  (binary-search 0 (sub1 (vector-length A))))