#lang racket

(define (merge-stones stones)
  (define n (length stones))
  (define cost (make-vector n (make-vector n 0)))
  (define dp (make-vector n (make-vector n 0)))
  (define (get-cost i j)
    (if (= i j)
        0
        (+ (vector-ref (vector-ref cost i) j) (get-cost i (- j 1)))))
  (for ([i (in-range n)])
    (for ([j (in-range i (+ n 1))])
      (when (< i j)
        (vector-set! (vector-ref cost i) j (+ (vector-ref (vector-ref cost i) (- j 1)) (list-ref stones j))))))
  (for ([k (in-range 2 (+ n 1))])
    (for ([i (in-range 0 (- n k + 1))])
      (define j (+ i k -1))
      (vector-set! (vector-ref dp i) j (vector-ref (vector-ref dp i) (- j 1)))
      (for ([m (in-range i j)])
        (when (= (modulo (- j i) 3) 0)
          (define temp (+ (vector-ref (vector-ref dp i) m) (vector-ref (vector-ref dp (+ m 1) j))))
          (when (< temp (vector-ref (vector-ref dp i) j))
            (vector-set! (vector-ref dp i) j temp))))
      (when (= (modulo (- j i) 3) 0)
        (define temp (+ (vector-ref (vector-ref dp i) j) (vector-ref (vector-ref cost i) j)))
        (vector-set! (vector-ref dp i) j temp))))
  (vector-ref (vector-ref dp 0) (- n 1)))