(define (longest-ones-subarray nums k)
  (let ((n (length nums))
        (left 0)
        (max-length 0)
        (zero-count 0))
    (for ([right (in-range n)])
      (when (= (list-ref nums right) 0)
        (set! zero-count (+ zero-count 1)))
      (when (> zero-count k)
        (when (= (list-ref nums left) 0)
          (set! zero-count (- zero-count 1)))
        (set! left (+ left 1)))
      (set! max-length (max max-length (- right left 1))))
    max-length))

(define/contract (longest-repeating-character-replacement s k)
  (-> string? exact-integer? exact-integer?)
  (let ((n (string-length s))
        (left 0)
        (max-count 0)
        (count (make-hash)))
    (for ([right (in-range n)])
      (hash-set! count (string-ref s right) (+ (hash-ref count (string-ref s right) 0) 1))
      (set! max-count (max max-count (hash-ref count (string-ref s right) 0)))
      (when (> (- right left) (+ max-count k))
        (hash-set! count (string-ref s left) (- (hash-ref count (string-ref s left) 0) 1))
        (set! left (+ left 1))))
    (- n left)))

(define/contract (find-max-consecutive-ones nums k)
  (-> (listof exact-integer?) exact-integer? exact-integer?)
  (longest-repeating-character-replacement (apply string (map number->string nums)) k))