(define (largest-sum-after-k-negations nums k)
  (define (heap-compare a b)
    (< a b))
  (define heap (make-heap heap-compare))
  (for-each (lambda (n) (heap-add! heap n)) nums)
  (let loop ()
    (when (> k 0)
      (let ((min-val (heap-min heap)))
        (heap-remove! heap)
        (heap-add! heap (- min-val))
        (set! k (- k 1))))
    (apply + (heap->list heap))))