(define (remove-outermost-parentheses s)
  (define (helper s count result)
    (if (null? s)
        (list->string (reverse result))
        (let ((c (car s)))
          (if (= count 0)
              (helper (cdr s) 1 result)
              (let ((new-count (+ count (if (char=? c #\()) 1 -1))))
                (if (= new-count 0)
                    (helper (cdr s) 0 (append result (list c)))
                    (helper (cdr s) new-count (append result (list c)))))))))
  (helper (string->list s) 0 '()))