(define (video-stitching clips time-points)
  (define (compare a b)
    (< (car a) (car b)))
  (define sorted-clips (sort clips compare))
  (define n (length sorted-clips))
  (define result 0)
  (define i 0)
  (define current-end 0)
  (define next-end 0)
  (let loop ()
    (when (< i n)
      (if (<= (caar sorted-clips) current-end)
          (begin
            (set! next-end (max next-end (cadar sorted-clips)))
            (set! i (+ i 1))
            (loop))
          (begin
            (when (> next-end current-end)
              (set! result (+ result 1))
              (set! current-end next-end)
              (set! next-end 0)
              (loop))
            (when (>= current-end time-points)
              (break))
            (set! next-end 0)
            (set! i 0)
            (loop)))))
  (if (>= current-end time-points)
      result
      -1))