(define (min-score-triangulation values)
  (define n (length values))
  (define dp (make-vector n (make-vector n 0)))
  (for ([i (in-range (- n 1) -1 -1)])
    (for ([j (in-range (+ i 2) n)])
      (vector-set! (vector-ref dp i) j (apply min (for/list ([k (in-range (+ i 1) j)])
                                                   (+ (vector-ref (vector-ref dp i) k)
                                                      (vector-ref (vector-ref dp k) j)
                                                      (* (vector-ref values i)
                                                         (vector-ref values k)
                                                         (vector-ref values j))))))))
  (vector-ref (vector-ref dp 0) (- n 1)))