#lang racket

(define (longest-duplicate-substring s)
  (define n (string-length s))
  (define (build-suffix-array)
    (define (compare i j)
      (let loop ([k 0])
        (cond [(= k n) 0]
              [(char=? (string-ref s (+ i k)) (string-ref s (+ j k))) (loop (+ k 1))]
              [else (- (char->integer (string-ref s (+ i k))) (char->integer (string-ref s (+ j k))))])))
    (define suffixes (range n))
    (sort suffixes compare))

  (define (build-lcp sa)
    (define rank (make-vector n))
    (for ([i (in-range n)])
      (vector-set! rank (list-ref sa i) i))
    (define lcp (make-vector n -1))
    (define h 0)
    (for ([i (in-range n)])
      (when (and (> i 0) (> h 0))
        (set! h (- h 1))
        (let ([j (vector-ref rank (sub1 i))])
          (while (and (< h n) (< (+ i h) n) (char=? (string-ref s (+ i h)) (string-ref s (+ j h))))
            (set! h (+ h 1)))
          (vector-set! lcp i h)))
      (when (and (> i 0) (> h 0))
        (vector-set! lcp i h)))
    (vector->list lcp))

  (define sa (build-suffix-array))
  (define lcp (build-lcp sa))
  (define max-len 0)
  (define start 0)
  (for ([i (in-range 1 n)])
    (when (> (list-ref lcp i) max-len)
      (set! max-len (list-ref lcp i))
      (set! start (list-ref sa i))))
  (if (> max-len 0)
      (substring s start (+ start max-len))
      ""))