(define (max-flips rows)
  (define (row->key row)
    (let loop ([i 0] [prev (vector-ref row 0)])
      (if (= i (vector-length row))
          '()
          (cons (if (= (vector-ref row i) prev) 0 1)
                (loop (+ i 1) (vector-ref row i))))))
  (define freq (make-hash))
  (for/fold ([max 0]) ([row rows])
    (let ([key (row->key row)])
      (hash-set! freq key (+ 1 (hash-ref freq key 0)))
      (max max (hash-ref freq key))))
  (max-flips rows)
  (define (max-flips rows)
    (define (row->key row)
      (let loop ([i 0] [prev (vector-ref row 0)])
        (if (= i (vector-length row))
            '()
            (cons (if (= (vector-ref row i) prev) 0 1)
                  (loop (+ i 1) (vector-ref row i))))))
    (define freq (make-hash))
    (for/fold ([max 0]) ([row rows])
      (let ([key (row->key row)])
        (hash-set! freq key (+ 1 (hash-ref freq key 0)))
        (max max (hash-ref freq key)))))