#lang racket

(define (num-submatrices-target matrix target)
  (define rows (length matrix))
  (define cols (length (car matrix)))
  (define prefix (make-vector rows (make-vector cols 0)))
  (define (get-prefix i j)
    (if (or (< i 0) (< j 0)) 0
        (vector-ref (vector-ref prefix i) j)))
  (define (update-prefix i j val)
    (vector-set! (vector-ref prefix i) j val))
  (for ([i (in-range rows)])
    (for ([j (in-range cols)])
      (let ([val (if (and (> i 0) (> j 0))
                     (+ (vector-ref (vector-ref matrix i) j)
                        (get-prefix (- i 1) j)
                        (get-prefix i (- j 1))
                        (- (get-prefix (- i 1) (- j 1))))
                     (if (and (> i 0) (= j 0))
                         (+ (vector-ref (vector-ref matrix i) j) (get-prefix (- i 1) j))
                         (if (and (= i 0) (> j 0))
                             (+ (vector-ref (vector-ref matrix i) j) (get-prefix i (- j 1)))
                             (vector-ref (vector-ref matrix i) j))))])
        (update-prefix i j val))))
  (define (sum i1 j1 i2 j2)
    (+ (get-prefix i2 j2)
       (- (get-prefix (- i1 1) j2))
       (- (get-prefix i2 (- j1 1)))
       (+ (get-prefix (- i1 1) (- j1 1)))))
  (define count 0)
  (for ([i1 (in-range rows)])
    (for ([j1 (in-range cols)])
      (for ([i2 (in-range i1 rows)])
        (for ([j2 (in-range j1 cols)])
          (when (= (sum i1 j1 i2 j2) target)
            (set! count (+ count 1)))))))
  count)