(define (largest-square grid)
  (define (min a b) (if (< a b) a b))
  (define (max a b) (if (> a b) a b))
  (define rows (length grid))
  (define cols (if (> rows 0) (length (car grid)) 0))
  (define max-size 0)
  (define (is-border i j size)
    (let loop ((x i) (y j) (count 0))
      (cond ((= count size) #t)
            ((or (not (and (<= i x) (< x (+ i size))))
                 (not (and (<= j y) (< y (+ j size)))))
             #f)
            (else
             (let ((x2 (+ x (if (= count 0) 0 (- size 1))))
                   (y2 (+ y (if (= count 0) 0 (- size 1)))))
               (if (and (= (list-ref (list-ref grid x) y) 1)
                        (= (list-ref (list-ref grid x2) y) 1)
                        (= (list-ref (list-ref grid x) y2) 1)
                        (= (list-ref (list-ref grid x2) y2) 1))
                   (loop x y (+ count 1))
                   #f))))))
  (let loop ((i 0))
    (when (< i rows)
      (let loop2 ((j 0))
        (when (< j cols)
          (when (= (list-ref (list-ref grid i) j) 1)
            (let loop3 ((size (min (- rows i) (- cols j))))
              (when (>= size 1)
                (when (is-border i j size)
                  (set! max-size (max max-size size)))
                (loop3 (- size 1)))))
          (loop2 (+ j 1))))
      (loop (+ i 1))))
  max-size)