(define (num-distinct-subseq s)
  (define mod 1000000007)
  (define dp (make-vector 256 0))
  (define (char->index c) (- (char->integer c) 97))
  (vector-set! dp 0 1)
  (for ([c s])
    (let ([i (char->index c)])
      (let ([prev (vector-ref dp i)])
        (vector-set! dp i (modulo (+ (vector-ref dp i) (vector-ref dp 0)) mod))
        (vector-set! dp 0 (modulo (- (vector-ref dp 0) prev) mod)))))
  (vector-ref dp 0))