#lang racket

(define (make-hash . args)
  (if (null? args)
      (make-immutable-hash '())
      (apply make-immutable-hash args)))

(define (majority-requirement a b)
  (let ((count (hash)))
    (for-each (lambda (x) (hash-set! count x (+ 1 (hash-ref count x 0)))) a)
    (for-each (lambda (x) (hash-set! count x (- (hash-ref count x 0) 1))) b)
    (let ((max-count 0)
          (majority #f))
      (for-each (lambda (k v)
                  (when (> v max-count)
                    (set! max-count v)
                    (set! majority k)))
                count)
      majority)))

(define (query a b)
  (let ((count (hash)))
    (for-each (lambda (x) (hash-set! count x (+ 1 (hash-ref count x 0)))) a)
    (for-each (lambda (x) (hash-set! count x (- (hash-ref count x 0) 1))) b)
    (let ((max-count 0)
          (majority #f))
      (for-each (lambda (k v)
                  (when (> v max-count)
                    (set! max-count v)
                    (set! majority k)))
                count)
      majority)))

(define (on-line-majority-element-in-subarray)
  (let ((data (read)))
    (let ((n (vector-length data))
          (queries (vector-ref data 1)))
      (let ((result '()))
        (let loop ((i 0))
          (when (< i (vector-length queries))
            (let ((a (vector-ref queries i)))
              (let ((b (vector-ref queries (+ i 1))))
                (let ((res (query a b)))
                  (set! result (append result (list res)))))
            (loop (+ i 2))))
        result))))

(define (main)
  (let ((input (read)))
    (let ((n (vector-ref input 0))
          (queries (vector-ref input 1)))
      (let ((result '()))
        (let loop ((i 0))
          (when (< i (vector-length queries))
            (let ((a (vector-ref queries i)))
              (let ((b (vector-ref queries (+ i 1))))
                (let ((res (query a b)))
                  (set! result (append result (list res)))))
            (loop (+ i 2))))
        (display result)
        (newline)))))

(main)