(define (max-subarray-sum-with-one-deletion nums)
  (let loop ([i 0] [max-no-delete -inf.0] [max-with-delete -inf.0] [current-max -inf.0])
    (if (= i (length nums))
        (max max-no-delete max-with-delete)
        (let ([num (list-ref nums i)])
          (let ([new-current-max (max (+ current-max num) num)])
            (let ([new-max-no-delete (max max-no-delete new-current-max)])
              (let ([new-max-with-delete (max max-with-delete (+ current-max num) (- max-no-delete num))])
                (loop (+ i 1) new-max-no-delete new-max-with-delete new-current-max))))))))