(define (count-vowels-permutation n)
  (define mod 1000000007)
  (define dp (make-vector 5 0))
  (vector-set! dp 0 1)
  (vector-set! dp 1 1)
  (vector-set! dp 2 1)
  (vector-set! dp 3 1)
  (vector-set! dp 4 1)
  (for ([i (in-range 1 n)])
    (define new-dp (make-vector 5 0))
    (vector-set! new-dp 0 (modulo (+ (vector-ref dp 1) (vector-ref dp 2) (vector-ref dp 3) (vector-ref dp 4)) mod))
    (vector-set! new-dp 1 (modulo (+ (vector-ref dp 0) (vector-ref dp 2) (vector-ref dp 3) (vector-ref dp 4)) mod))
    (vector-set! new-dp 2 (modulo (+ (vector-ref dp 0) (vector-ref dp 1) (vector-ref dp 3) (vector-ref dp 4)) mod))
    (vector-set! new-dp 3 (modulo (+ (vector-ref dp 0) (vector-ref dp 1) (vector-ref dp 2) (vector-ref dp 4)) mod))
    (vector-set! new-dp 4 (modulo (+ (vector-ref dp 0) (vector-ref dp 1) (vector-ref dp 2) (vector-ref dp 3)) mod))
    (set! dp new-dp))
  (apply + (vector->list dp)) 1000000007)