(define (queens-that-can-attack-the-king queens)
  (define directions '((-1 -1) (-1 0) (-1 1) (0 -1) (0 1) (1 -1) (1 0) (1 1)))
  (define king-pos '(0 0))
  (define (get-queen-pos q)
    (list (car q) (cadr q)))
  (define (in-bounds? x y)
    (and (>= x 0) (< x 8) (>= y 0) (< y 8)))
  (define (find-attacking-queens dir)
    (let loop ((x (car king-pos)) (y (cadr king-pos)))
      (cond ((not (in-bounds? x y)) #f)
            ((member (list x y) queens) (list (list x y)))
            (else (loop (+ x (caar dir)) (+ y (cadar dir)))))))
  (define (process-direction dir)
    (let ((result (find-attacking-queens dir)))
      (if result result '())))
  (apply append (map process-direction directions)))