#lang racket

(define (max-equal-frequency nums)
  (define freq (make-hash))
  (define count (make-hash))
  (define max-freq 0)
  (define result 1)
  (for ([num nums])
    (hash-set! freq num (+ (hash-ref freq num 0) 1))
    (hash-set! count (hash-ref freq num 0) (+ (hash-ref count (hash-ref freq num 0) 0) 1))
    (when (> (hash-ref freq num 0) max-freq)
      (set! max-freq (hash-ref freq num 0)))
    (when (= (hash-count count) 1)
      (if (= max-freq 1)
          (set! result (length nums))
          (set! result (if (= (hash-ref count max-freq) 1)
                           (if (= max-freq 1)
                               (length nums)
                               (length nums))
                           (length nums))))
      (when (and (= (hash-ref count max-freq) 1)
                 (not (= max-freq 1)))
        (set! result (length nums))))
    (when (and (= (hash-count count) 2)
               (or (= (hash-ref count 1) 1)
                   (= (hash-ref count max-freq) 1)))
      (set! result (length nums))))
  result)