(define (findSolution f)
  (define (helper x y)
    (if (> x 100)
        '()
        (let ((res (f x y)))
          (cond ((= res 0) (list (list x y)))
                ((< res 0) (helper (add1 x) 1))
                (else (append (helper x (add1 y)) (helper (add1 x) 1)))))))
  (helper 1 1))