(define (find-circular-permutation permutation)
  (define n (length permutation))
  (define bits (make-vector n 0))
  (define (get-binary x)
    (let loop ((x x) (i 0))
      (if (= i n)
          (reverse (vector->list bits))
          (begin
            (vector-set! bits i (bitwise-and x 1))
            (loop (arithmetic-shift x -1) (+ i 1))))))
  (define (to-decimal bits)
    (let loop ((bits bits) (res 0) (i 0))
      (if (null? bits)
          res
          (loop (cdr bits) (+ res (* (car bits) (expt 2 (- n (+ i 1))))) (+ i 1)))))
  (define (cyclic-shift x)
    (let ((b (get-binary x)))
      (append (cdr b) (list (car b)))))
  (define (generate)
    (let loop ((current 0) (result '()))
      (if (= (length result) n)
          (reverse result)
          (let ((next (to-decimal (cyclic-shift current))))
            (loop next (cons next result))))))
  (generate))