#lang racket

(define (num-closed-islands grid)
  (define rows (length grid))
  (define cols (if (> rows 0) (length (first grid)) 0))
  (define visited (make-vector rows #f))
  (define (dfs r c)
    (when (and (<= 0 r rows) (<= 0 c cols) (not (vector-ref visited r)) (equal? (list-ref (list-ref grid r) c) 0))
      (vector-set! visited r #t)
      (dfs (+ r 1) c)
      (dfs (- r 1) c)
      (dfs r (+ c 1))
      (dfs r (- c 1))))
  (define (is-border r c)
    (or (= r 0) (= r (- rows 1)) (= c 0) (= c (- cols 1))))
  (define count 0)
  (for ([r (in-range rows)])
    (for ([c (in-range cols)])
      (when (and (equal? (list-ref (list-ref grid r) c) 0) (not (vector-ref visited r)))
        (when (not (is-border r c))
          (set! count (+ count 1)))
        (dfs r c))))
  count)