(define (num-ways n k)
  (define mod 1000000007)
  (define dp (make-vector (+ n 1) 0))
  (vector-set! dp 0 1)
  (for ([_ (in-range k)])
    (define new-dp (make-vector (+ n 1) 0))
    (for ([i (in-range n)])
      (when (> (vector-ref dp i) 0)
        (when (< i (sub1 n))
          (vector-set! new-dp (add1 i) (modulo (+ (vector-ref new-dp (add1 i)) (vector-ref dp i)) mod)))
        (when (> i 0)
          (vector-set! new-dp (sub1 i) (modulo (+ (vector-ref new-dp (sub1 i)) (vector-ref dp i)) mod)))))
    (set! dp new-dp))
  (vector-ref dp 0))