(define (count-squares matrix)
  (define rows (length matrix))
  (define cols (if (> rows 0) (length (car matrix)) 0))
  (define dp (make-vector rows (make-vector cols 0)))
  (define (get i j)
    (vector-ref (vector-ref dp i) j))
  (define (set!-dp i j val)
    (vector-set! (vector-ref dp i) j val))
  (let loop ((i 0))
    (when (< i rows)
      (let loop2 ((j 0))
        (when (< j cols)
          (if (or (= i 0) (= j 0))
              (set!-dp i j (if (= (vector-ref (vector-ref matrix i) j) 1) 1 0))
              (if (= (vector-ref (vector-ref matrix i) j) 1)
                  (set!-dp i j (+ (min (get (- i 1) j) (get i (- j 1)) (get (- i 1) (- j 1))) 1))
                  (set!-dp i j 0)))
          (loop2 (+ j 1))))
      (loop (+ i 1))))
  (let loop ((i 0) (sum 0))
    (if (= i rows)
        sum
        (loop (+ i 1) (+ sum (apply + (vector->list (vector-ref dp i))))))))