(define (make-combination-iterator)
  (let ((nums '())
        (current '())
        (index 0))
    (lambda (op . args)
      (cond ((eq? op 'next)
             (if (null? current)
                 (set! current (reverse (take nums index)))
                 (set! current (reverse (take nums index))))
             (set! index (+ index 1))
             (if (<= index (length nums))
                 (car current)
                 #f))
            ((eq? op 'has-next)
             (not (>= index (length nums)))))))

(define (combine n k)
  (let ((nums (range 1 (+ n 1))))
    (let ((iter (make-combination-iterator)))
      (set! (car (cdr iter)) nums)
      (set! (cadr (cdr iter)) '())
      (set! (caddr (cdr iter)) 0)
      iter)))