(define (min-falling-path-sum grid)
  (define n (length grid))
  (define dp (make-vector n (vector-ref grid 0)))
  (for ([i (in-range 1 n)])
    (define new-dp (make-vector n))
    (for ([j (in-range n)])
      (vector-set! new-dp j (+ (vector-ref grid i j) (apply min (for/list ([k (in-range n)] #:unless (= k j)) (vector-ref dp k)))))
    )
    (set! dp new-dp)
  )
  (apply min (vector->list dp))
)