(define (mutated-array-sum-closest-to-target nums target)
  (define (sum-mutated nums)
    (for/sum ([n nums])
      (if (> n 0) n (- n))))
  (define sorted (sort nums <))
  (define len (length sorted))
  (define-values (closest diff)
    (for/fold ([closest 0] [diff +inf.0])
              ([i (in-range len)])
      (define sum (sum-mutated (take sorted (add1 i))))
      (define current-diff (abs (- sum target)))
      (if (< current-diff diff)
          (values sum current-diff)
          (values closest diff))))
  closest)