(define (freq-alphabets s)
  (define (char->num c)
    (- (char->integer c) 48))
  (define (num->char n)
    (integer->char (+ n 96)))
  (define (decode s i)
    (if (>= i (string-length s))
        ""
        (let ((next1 (if (< (+ i 1) (string-length s)) (string-ref s (+ i 1)) #\0))
              (next2 (if (< (+ i 2) (string-length s)) (string-ref s (+ i 2)) #\0)))
          (if (and (char>=? next1 #\0) (char<=? next1 #\9)
                   (char>=? next2 #\0) (char<=? next2 #\9))
              (string-append (num->char (+ (* (char->num next1) 10) (char->num next2))) (decode s (+ i 3)))
              (string-append (num->char (char->num (string-ref s i))) (decode s (+ i 1)))))))
  (decode s 0))