#lang racket

(define (matrix-block-sum mat k)
  (define rows (length mat))
  (define cols (length (car mat)))
  (define sum (make-array (list rows cols) 0))
  (for ([i (in-range rows)])
    (for ([j (in-range cols)])
      (array-set! sum i j (array-ref mat i j))))
  (for ([i (in-range rows)])
    (for ([j (in-range cols)])
      (when (> i 0)
        (array-set! sum i j (+ (array-ref sum i j) (array-ref sum (- i 1) j))))
      (when (> j 0)
        (array-set! sum i j (+ (array-ref sum i j) (array-ref sum i (- j 1)))))
      (when (and (> i 0) (> j 0))
        (array-set! sum i j (- (array-ref sum i j) (array-ref sum (- i 1) (- j 1)))))))
  (define res (make-array (list rows cols) 0))
  (for ([i (in-range rows)])
    (for ([j (in-range cols)])
      (define x1 (max 0 (- i k)))
      (define y1 (max 0 (- j k)))
      (define x2 (min (- rows 1) (+ i k)))
      (define y2 (min (- cols 1) (+ j k)))
      (define val (array-ref sum x2 y2))
      (when (> x1 0)
        (set! val (- val (array-ref sum (- x1 1) y2))))
      (when (> y1 0)
        (set! val (- val (array-ref sum x2 (- y1 1)))))
      (when (and (> x1 0) (> y1 0))
        (set! val (+ val (array-ref sum (- x1 1) (- y1 1)))))
      (array-set! res i j val)))
  (array->list res))