(define (can-attend-meetings intervals)
  (define (sort-intervals intervals)
    (sort intervals (lambda (a b) (< (car a) (car b)))))

  (define (merge-intervals intervals)
    (if (null? intervals)
        '()
        (let loop ((current (car intervals))
                   (rest (cdr intervals))
                   (result '()))
          (if (null? rest)
              (cons current result)
              (let ((next (car rest)))
                (if (<= (cadr current) (car next))
                    (loop (list (car current) (max (cadr current) (cadr next)))
                          (cdr rest)
                          result)
                    (loop next (cdr rest) (cons current result))))))))

  (define (max-events intervals)
    (if (null? intervals)
        0
        (let ((sorted (sort-intervals intervals)))
          (let loop ((events sorted)
                     (count 0)
                     (last-end -1))
            (if (null? events)
                count
                (let ((start (caar events))
                      (end (cadar events)))
                  (if (>= start last-end)
                      (loop (cdr events) (+ count 1) end)
                      (loop (cdr events) count last-end))))))))

  (max-events (merge-intervals intervals)))