#lang racket

(define (validate-binary-tree-nodes left right)
  (define n (length left))
  (define visited (make-vector n #f))
  (define parent (make-vector n -1))
  (define (dfs node)
    (when (vector-ref visited node)
      (error "cycle"))
    (vector-set! visited node #t)
    (let ([l (vector-ref left node)])
      (when (not (= l -1))
        (when (= (vector-ref parent l) node)
          (error "invalid"))
        (vector-set! parent l node)
        (dfs l)))
    (let ([r (vector-ref right node)])
      (when (not (= r -1))
        (when (= (vector-ref parent r) node)
          (error "invalid"))
        (vector-set! parent r node)
        (dfs r))))
  (for ([i (in-range n)])
    (when (not (vector-ref visited i))
      (dfs i)))
  #t)