(define (number-of-times-binary-string-is-prefix-aligned s)
  (define len (string-length s))
  (define prefix (make-vector len #f))
  (define count 0)
  (define (update i)
    (vector-set! prefix i #t)
    (when (and (>= i 0) (vector-ref prefix i))
      (let loop ((j i))
        (when (and (<= j (- len 1)) (vector-ref prefix j))
          (set! count (+ count 1))
          (loop (+ j 1))))))
  (for ([i (in-range len)])
    (when (= (string-ref s i) #\1)
      (update i)))
  count)