(define (lucky-numbers matrix)
  (define (row-mins matrix)
    (map (lambda (row) (apply min row)) matrix))
  (define (col-maxs matrix)
    (let ((n (length matrix)))
      (if (= n 0)
          '()
          (let ((m (length (car matrix))))
            (for/list ((j (in-range m)))
              (apply max (map (lambda (i) (list-ref (list-ref matrix i) j)) (range n))))))))
  (define row-mins-val (row-mins matrix))
  (define col-maxs-val (col-maxs matrix))
  (filter (lambda (x) (and (member x row-mins-val) (member x col-maxs-val))) row-mins-val))