(define (longest-happy-prefix s)
  (define n (string-length s))
  (define lps (make-vector n 0))
  (define len 0)
  (for ([i (in-range 1 n)])
    (let loop ()
      (when (and (> i 0) (not (= (string-ref s (sub1 i)) (string-ref s len))))
        (set! len (vector-ref lps (sub1 len)))
        (when (and (> len 0) (not (= (string-ref s (sub1 i)) (string-ref s len))))
          (loop))))
    (when (= (string-ref s (sub1 i)) (string-ref s len))
      (set! len (+ len 1))
      (vector-set! lps i len)))
  (vector-ref lps (sub1 n)))