(define (max-score s)
  (define len (string-length s))
  (define (count-ones start end)
    (for/sum ([i (in-range start end)])
      (if (= #\1 (string-ref s i)) 1 0)))
  (define max-score 0)
  (for ([i (in-range 1 (- len 1))])
    (define left (count-ones 0 i))
    (define right (count-ones i len))
    (set! max-score (max max-score (+ left right))))
  max-score)