(define (max-difference n)
  (define (to-digits x)
    (map (lambda (c) (- (char->integer c) 48)) (string->list (number->string x))))
  (define (digits->number ds)
    (string->number (list->string (map (lambda (d) (integer->char (+ d 48))) ds))))
  (define digits (to-digits n))
  (define len (length digits))
  (define max-val (apply max digits))
  (define min-val (apply min digits))
  (if (= max-val min-val)
      0
      (let loop ((i 0) (max-idx -1) (min-idx -1))
        (cond ((= i len) (- (digits->number (map (lambda (d) (if (= d min-val) max-val d)) digits)) n))
              ((= (list-ref digits i) max-val) (loop (+ i 1) i min-idx))
              ((= (list-ref digits i) min-val) (loop (+ i 1) max-idx i))
              (else (loop (+ i 1) max-idx min-idx))))))