(define (people-who-owns-everyone-else lst)
  (define (is-subset? a b)
    (andmap (lambda (x) (member x b)) a))
  (define (not-subset-of-others? person)
    (not (ormap (lambda (other)
                  (and (not (equal? person other))
                       (is-subset? person other)))
                lst)))
  (filter not-subset-of-others? lst))