(define (least-unique-integers nums k)
  (define freq (make-hash))
  (for ([n nums])
    (hash-set! freq n (+ 1 (hash-ref freq n 0))))
  (define sorted (sort (hash-values freq) <))
  (define len (length sorted))
  (let loop ([i 0] [k k])
    (if (or (>= i len) (<= k 0))
        (- len i)
        (if (<= (list-ref sorted i) k)
            (loop (+ i 1) (- k (list-ref sorted i)))
            (- len i)))))