#lang racket

(define (avoid-flood rains)
  (define (solve)
    (define pos (make-hash))
    (define res (make-list (length rains) "none"))
    (define pq (priority-queue '()))
    (for ([i (in-range (length rains))])
      (define r (list-ref rains i))
      (when (not (equal? r "none"))
        (when (hash-has-key? pos r)
          (priority-queue-push! pq (hash-ref pos r)))
        (hash-set! pos r i))
      (when (equal? r "none")
        (when (priority-queue-empty? pq)
          (set! res (list-set res i "all"))
          (continue))
        (define idx (priority-queue-pop! pq))
        (set! res (list-set res idx "none"))
        (set! res (list-set res i "all")))
      (when (equal? r "none")
        (set! res (list-set res i "all"))))
    res)
  (solve))