#lang racket

(define (min-possible-integer s k)
  (define len (string-length s))
  (define lst (string->list s))
  (define (swap i j)
    (let ([tmp (list-ref lst i)])
      (set! lst (list-set lst i (list-ref lst j)))
      (set! lst (list-set lst j tmp))))
  (define (find-min-index start)
    (let loop ([i start] [min-i start])
      (if (>= i len)
          min-i
          (if (< (char->integer (list-ref lst i)) (char->integer (list-ref lst min-i)))
              (loop (+ i 1) i)
              (loop (+ i 1) min-i)))))
  (let loop ([k k] [start 0])
    (when (< start len)
      (let ([min-i (find-min-index start)])
        (when (and (< min-i len) (<= (- min-i start) k))
          (let loop ([i min-i])
            (when (> i start)
              (swap i (- i 1))
              (set! k (- k 1))
              (loop (- i 1)))))
        (loop k (+ start 1)))))
  (list->string lst))