(define (reformat-date date)
  (define month-map (list (cons "Jan" "01") (cons "Feb" "02") (cons "Mar" "03") (cons "Apr" "04") (cons "May" "05") (cons "Jun" "06") (cons "Jul" "07") (cons "Aug" "08") (cons "Sep" "09") (cons "Oct" "10") (cons "Nov" "11") (cons "Dec" "12")))
  (define (get-month m)
    (cdr (assoc m month-map)))
  (define (get-day d)
    (if (string-length d) (string-append "0" d) d))
  (let* ((parts (string-split date #\ ))
         (day (get-day (substring (car parts) 0 (sub1 (string-length (car parts)))))
         (month (get-month (cadr parts)))
         (year (caddr parts)))
    (string-append year "-" month "-" day)))