(define/contract (stone-game-iv n)
  (-> exact-integer? boolean?)
  (letrec ([dp (make-vector (+ n 1) #f)])
    (vector-set! dp 0 #t)
    (for ([i (in-range 1 (+ n 1))])
      (when (not (vector-ref dp i))
        (for ([j (in-range 1 (sqrt i))])
          (when (vector-ref dp (- i (* j j)))
            (vector-set! dp i #t)
            (break)))))
    (vector-ref dp n)))