(define (num-splits s)
  (define len (string-length s))
  (define cnt (make-vector 26 0))
  (define left (make-vector 26 0))
  (define right (make-vector 26 0))
  (for ([i (in-range len)])
    (vector-set! cnt (- (char->integer (string-ref s i)) 97) (+ (vector-ref cnt (- (char->integer (string-ref s i)) 97)) 1)))
  (define res 0)
  (for ([i (in-range len)])
    (define c (string-ref s i))
    (vector-set! left (- (char->integer c) 97) (+ (vector-ref left (- (char->integer c) 97)) 1))
    (vector-set! cnt (- (char->integer c) 97) (- (vector-ref cnt (- (char->integer c) 97)) 1))
    (define left-unique 0)
    (define right-unique 0)
    (for ([j (in-range 26)])
      (when (> (vector-ref left j) 0) (set! left-unique (+ left-unique 1)))
      (when (> (vector-ref cnt j) 0) (set! right-unique (+ right-unique 1))))
    (when (= left-unique right-unique) (set! res (+ res 1))))
  res)