(define (longest-odd s)
  (define n (string-length s))
  (define last-index (make-hash))
  (hash-set! last-index 0 -1)
  (define max-len 0)
  (define mask 0)
  (for ([i (in-range n)])
    (define bit (- (char->integer (string-ref s i)) 48))
    (set! mask (bitwise-xor mask (arithmetic-shift 1 bit)))
    (when (hash-has-key? last-index mask)
      (set! max-len (max max-len (- i (hash-ref last-index mask)))))
    (when (not (hash-has-key? last-index mask))
      (hash-set! last-index mask i))
    (for ([j (in-range 10)])
      (define tmp-mask (bitwise-xor mask (arithmetic-shift 1 j)))
      (when (hash-has-key? last-index tmp-mask)
        (set! max-len (max max-len (- i (hash-ref last-index tmp-mask))))))
    )
  max-len)

(define (longest-odd-substring s)
  (longest-odd s))

(longest-odd-substring "324235")