(define (num-ways s)
  (define MOD 1000000007)
  (define len (string-length s))
  (define cnt (make-vector len 0))
  (define total (make-vector len 0))
  (define (count-ones)
    (let loop ((i 0) (c 0))
      (if (= i len)
          c
          (loop (+ i 1) (+ c (if (= (string-ref s i) #\1) 1 0))))))
  (define ones (count-ones))
  (cond ((= ones 0) (modulo (* (- len 1) (- len 2)) MOD))
        ((< ones 2) 0)
        (else
         (let loop ((i 0) (c 0) (res 0))
           (if (= i len)
               res
               (begin
                 (when (= (string-ref s i) #\1)
                   (set! c (+ c 1)))
                 (when (and (> c 0) (< c ones))
                   (set! res (+ res (vector-ref cnt (- i 1)))))
                 (vector-set! cnt i c)
                 (loop (+ i 1) c res)))))))
  (define (get-total)
    (let loop ((i 0) (c 0) (res 0))
      (if (= i len)
          res
          (begin
            (when (= (string-ref s i) #\1)
              (set! c (+ c 1)))
            (when (and (> c 0) (< c ones))
              (set! res (+ res (vector-ref total (- i 1)))))
            (vector-set! total i c)
            (loop (+ i 1) c res)))))
  (if (= ones 0)
      (modulo (* (- len 1) (- len 2)) MOD)
      (let ((pre (make-vector len 0)))
        (let loop ((i 0) (c 0))
          (if (= i len)
              (void)
              (begin
                (when (= (string-ref s i) #\1)
                  (set! c (+ c 1)))
                (vector-set! pre i c)
                (loop (+ i 1) c))))
        (let loop ((i 0) (res 0))
          (if (= i len)
              res
              (begin
                (if (and (> (vector-ref pre i) 0) (< (vector-ref pre i) ones))
                    (set! res (+ res (vector-ref pre i))))
                (loop (+ i 1) res)))))))
  (define (solve)
    (let ((pre (make-vector len 0)))
      (let loop ((i 0) (c 0))
        (if (= i len)
            (void)
            (begin
              (when (= (string-ref s i) #\1)
                (set! c (+ c 1)))
              (vector-set! pre i c)
              (loop (+ i 1) c))))
      (let loop ((i 0) (res 0))
        (if (= i len)
            res
            (begin
              (if (and (> (vector-ref pre i) 0) (< (vector-ref pre i) ones))
                  (set! res (+ res (vector-ref pre i))))
              (loop (+ i 1) res)))))
  (if (= ones 0)
      (modulo (* (- len 1) (- len 2)) MOD)
      (let ((pre (make-vector len 0)))
        (let loop ((i 0) (c 0))
          (if (= i len)
              (void)
              (begin
                (when (= (string-ref s i) #\1)
                  (set! c (+ c 1)))
                (vector-set! pre i c)
                (loop (+ i 1) c))))
        (let loop ((i 0) (res 0))
          (if (= i len)
              res
              (begin
                (if (and (> (vector-ref pre i) 0) (< (vector-ref pre i) ones))
                    (set! res (+ res (vector-ref pre i))))
                (loop (+ i 1) res)))))))
  (if (= ones 0)
      (modulo (* (- len 1) (- len 2)) MOD)
      (let ((pre (make-vector len 0)))
        (let loop ((i 0) (c 0))
          (if (= i len)
              (void)
              (begin
                (when (= (string-ref s i) #\1)
                  (set! c (+ c 1)))
                (vector-set! pre i c)
                (loop (+ i 1) c))))
        (let loop ((i 0) (res 0))
          (if (= i len)
              res
              (begin
                (if (and (> (vector-ref pre i) 0) (< (vector-ref pre i) ones))
                    (set! res (+ res (vector-ref pre i))))
                (loop (+ i 1) res)))))))
  (if (= ones 0)
      (modulo (* (- len 1) (- len 2)) MOD)
      (let ((pre (make-vector len 0)))
        (let loop ((i 0) (c 0))
          (if (= i len)
              (void)
              (begin
                (when (= (string-ref s i) #\1)
                  (set! c (+ c 1)))
                (vector-set! pre i c)
                (loop (+ i 1) c))))
        (let loop ((i 0) (res 0))
          (if (= i len)
              res
              (begin
                (if (and (> (vector-ref pre i) 0) (< (vector-ref pre i) ones))
                    (set! res (+ res (vector-ref pre i))))
                (loop (+ i 1) res)))))))
  (if (= ones 0)
      (modulo (* (- len 1) (- len 2)) MOD)
      (let ((pre (make-vector len 0)))
        (let loop ((i 0) (c 0))
          (if (= i len)
              (void)
              (begin
                (when (= (string-ref s i) #\1)
                  (set! c (+ c 1)))
                (vector-set! pre i c)
                (loop (+ i 1) c))))
        (let loop ((i 0) (res 0))
          (if (= i len)
              res
              (begin
                (if (and (> (vector-ref pre i) 0) (< (vector-ref pre i) ones))
                    (set! res (+ res (vector-ref pre i))))
                (loop (+ i 1) res)))))))
  (if (= ones 0)
      (modulo (* (- len 1) (- len 2)) MOD)
      (let ((pre (make-vector len 0)))
        (let loop ((i 0) (c 0))
          (if (= i len)
              (void)
              (begin
                (when (= (string-ref s i) #\1)
                  (set! c (+ c 1)))
                (vector-set! pre i c)
                (loop (+ i 1) c))))
        (let loop ((i 0) (res 0))
          (if (= i len)
              res
              (begin
                (if (and (> (vector-ref pre i) 0) (< (vector-ref pre i) ones))
                    (set! res (+ res (vector-ref pre i))))
                (loop (+ i 1) res)))))))
  (if (= ones 0)
      (modulo (* (- len 1) (- len 2)) MOD)
      (let ((pre (make-vector len 0)))
        (let loop ((i 0) (c 0))
          (if (= i len)
              (void)
              (begin
                (when (= (string-ref s i) #\1)
                  (set! c (+ c 1)))
                (vector-set! pre i c)
                (loop (+ i 1) c))))
        (let loop ((i 0) (res 0))
          (if (= i len)
              res
              (begin
                (if (and (> (vector-ref pre i) 0) (< (vector-ref pre i) ones))
                    (set! res (+ res (vector-ref pre i))))
                (loop (+ i 1) res)))))))
  (if (= ones 0)
      (modulo (* (- len 1) (- len 2)) MOD)
      (let ((pre (make-vector len 0)))
        (let loop ((i 0) (c 0))
          (if (= i len)
              (void)
              (begin
                (when (= (string-ref s i) #\1)
                  (set! c (+ c 1)))
                (vector-set! pre i c)
                (loop (+ i 1) c))))
        (let loop ((i 0) (res 0))
          (if (= i len)
              res
              (begin
                (if (and (> (vector-ref pre i) 0) (< (vector-ref pre i) ones