#lang racket

(define (isPrintable robot)
  (define rows (length robot))
  (define cols (if (> rows 0) (length (car robot)) 0))
  (define color-set (set))
  (for ([i (in-range rows)])
    (for ([j (in-range cols)])
      (set-add! color-set (list-ref (list-ref robot i) j))))
  (define colors (set->list color-set))
  (define color-positions (make-hash))
  (for ([i (in-range rows)])
    (for ([j (in-range cols)])
      (define c (list-ref (list-ref robot i) j))
      (hash-update! color-positions c (λ (lst) (cons (cons i j) lst)) '())))
  (define (get-bounds color)
    (define positions (hash-ref color-positions color '()))
    (define min-row (apply min (map car positions)))
    (define max-row (apply max (map car positions)))
    (define min-col (apply min (map cdr positions)))
    (define max-col (apply max (map cdr positions)))
    (values min-row max-row min-col max-col))
  (define (check-color color)
    (define-values (min-r max-r min-c max-c) (get-bounds color))
    (for ([i (in-range min-r (add1 max-r))])
      (for ([j (in-range min-c (add1 max-c))])
        (unless (= (list-ref (list-ref robot i) j) color)
          (return #f))))
    #t)
  (andmap check-color colors))