(define (find-valid-matrix row-sums col-sums)
  (define rows (length row-sums))
  (define cols (length col-sums))
  (define matrix (make-vector rows (make-vector cols 0)))
  (for ([i (in-range rows)])
    (for ([j (in-range cols)])
      (vector-set! (vector-ref matrix i) j (min (vector-ref row-sums i) (vector-ref col-sums j)))
      (vector-set! row-sums i (- (vector-ref row-sums i) (vector-ref (vector-ref matrix i) j)))
      (vector-set! col-sums j (- (vector-ref col-sums j) (vector-ref (vector-ref matrix i) j)))))
  matrix)