(define (mean-of-array-after-removing-some-elements/1724 nums)
  (define (median lst)
    (let* ((sorted (sort lst <))
           (len (length sorted))
           (mid (quotient len 2)))
      (if (odd? len)
          (list-ref sorted mid)
          (/ (+ (list-ref sorted (- mid 1)) (list-ref sorted mid)) 2))))
  (define (remove-edges lst)
    (let ((len (length lst)))
      (take (drop lst 1) (- len 2))))
  (define cleaned (remove-edges nums))
  (if (null? cleaned)
      0
      (/ (apply + cleaned) (length cleaned))))