(define (slowest-key-presses key-time)
  (define (helper lst max-time char)
    (if (null? lst)
        (list char)
        (let* ((current (car lst))
               (time (cadr current))
               (char (car current)))
          (cond ((> time max-time) (helper (cdr lst) time char))
                ((= time max-time) (append (list char) (helper (cdr lst) time char)))
                (else (helper (cdr lst) max-time char))))))
  (apply min (map (lambda (x) (car x)) (helper key-time 0 #\a))))

(define (slowest-key key-time)
  (define (helper lst max-time char)
    (if (null? lst)
        (list char)
        (let* ((current (car lst))
               (time (cadr current))
               (char (car current)))
          (cond ((> time max-time) (helper (cdr lst) time char))
                ((= time max-time) (append (list char) (helper (cdr lst) time char)))
                (else (helper (cdr lst) max-time char))))))
  (let ((result (helper key-time 0 #\a)))
    (if (= (length result) 1)
        (car result)
        (apply min result))))