(define (close-strings word1 word2)
  (define (count-chars s)
    (for/fold ([counts (hash)]) ([c s])
      (hash-update counts c add1 0)))
  (define (get-freqs counts)
    (sort (hash-values counts) <))
  (and (= (string-length word1) (string-length word2))
       (equal? (get-freqs (count-chars word1)) (get-freqs (count-chars word2)))
       (equal? (set->list (hash-keys (count-chars word1))) (set->list (hash-keys (count-chars word2)))))
  )