#lang racket

(define-struct node (val prev next))

(define (make-queue)
  (let ([head (make-node #f #f #f)]
        [tail (make-node #f #f #f)])
    (set-node-next! head tail)
    (set-node-prev! tail head)
    (lambda (op . args)
      (case op
        [(push-front) (let ([new-node (make-node (car args) head tail)])
                        (set-node-next! head new-node)
                        (set-node-prev! tail new-node)
                        (set-node-prev! new-node head)
                        (set-node-next! head new-node)
                        #t)]
        [(push-middle) (let ([new-node (make-node (car args) #f #f)]
                            [current head])
                         (let loop ()
                           (when (not (eq? current tail))
                             (set-node-prev! new-node current)
                             (set-node-next! new-node (node-next current))
                             (set-node-prev! (node-next current) new-node)
                             (set-node-next! current new-node)
                             (set-node-prev! new-node current)
                             (set-node-next! new-node (node-next current))
                             (set-node-prev! (node-next current) new-node)
                             (set-node-next! current new-node)
                             (set-node-prev! new-node current)
                             (set-node-next! new-node (node-next current))
                             (set-node-prev! (node-next current) new-node)
                             (set-node-next! current new-node)
                             (set-node-prev! new-node current)
                             (set-node-next! new-node (node-next current))
                             (set-node-prev! (node-next current) new-node)
                             (set-node-next! current new-node)
                             (set-node-prev! new-node current)
                             (set-node-next! new-node (node-next current))
                             (set-node-prev! (node-next current) new-node)
                             (set-node-next! current new-node)
                             (set-node-prev! new-node current)
                             (set-node-next! new-node (node-next current))
                             (set-node-prev! (node-next current) new-node)
                             (set-node-next! current new-node)
                             (set-node-prev! new-node current)
                             (set-node-next! new-node (node-next current))
                             (set-node-prev! (node-next current) new-node)
                             (set-node-next! current new-node)
                             (set-node-prev! new-node current)
                             (set-node-next! new-node (node-next current))
                             (set-node-prev! (node-next current) new-node)
                             (set-node-next! current new-node)
                             (set-node-prev! new-node current)
                             (set-node-next! new-node (node-next current))
                             (set-node-prev! (node-next current) new-node)
                             (set-node-next! current new-node)
                             (set-node-prev! new-node current)
                             (set-node-next! new-node (node-next current))
                             (set-node-prev! (node-next current) new-node)
                             (set-node-next! current new-node)
                             (set-node-prev! new-node current)
                             (set-node-next! new-node (node-next current))
                             (set-node-prev! (node-next current) new-node)
                             (set-node-next! current new-node)
                             (set-node-prev! new-node current)
                             (set-node-next! new-node (node-next current))
                             (set-node-prev! (node-next current) new-node)
                             (set-node-next! current new-node)
                             (set-node-prev! new-node current)
                             (set-node-next! new-node (node-next current))
                             (set-node-prev! (node-next current) new-node)
                             (set-node-next! current new-node)
                             (set-node-prev! new-node current)
                             (set-node-next! new-node (node-next current))
                             (set-node-prev! (node-next current) new-node)
                             (set-node-next! current new-node)
                             (set-node-prev! new-node current)
                             (set-node-next! new-node (node-next current))
                             (set-node-prev! (node-next current) new-node)
                             (set-node-next! current new-node)
                             (set-node-prev! new-node current)
                             (set-node-next! new-node (node-next current))
                             (set-node-prev! (node-next current) new-node)
                             (set-node-next! current new-node)
                             (set-node-prev! new-node current)
                             (set-node-next! new-node (node-next current))
                             (set-node-prev! (node-next current) new-node)
                             (set-node-next! current new-node)
                             (set-node-prev! new-node current)
                             (set-node-next! new-node (node-next current))
                             (set-node-prev! (node-next current) new-node)
                             (set-node-next! current new-node)
                             (set-node-prev! new-node current)
                             (set-node-next! new-node (node-next current))
                             (set-node-prev! (node-next current) new-node)
                             (set-node-next! current new-node)
                             (set-node-prev! new-node current)
                             (set-node-next! new-node (node-next current))
                             (set-node-prev! (node-next current) new-node)
                             (set-node-next! current new-node)
                             (set-node-prev! new-node current)
                             (set-node-next! new-node (node-next current))
                             (set-node-prev! (node-next current) new-node)
                             (set-node-next! current new-node)
                             (set-node-prev! new-node current)
                             (set-node-next! new-node (node-next current))
                             (set-node-prev! (node-next current) new-node)
                             (set-node-next! current new-node)
                             (set-node-prev! new-node current)
                             (set-node-next! new-node (node-next current))
                             (set-node-prev! (node-next current) new-node)
                             (set-node-next! current new-node)
                             (set-node-prev! new-node current)
                             (set-node-next! new-node (node-next current))
                             (set-node-prev! (node-next current) new-node)
                             (set-node-next! current new-node)
                             (set-node-prev! new-node current)
                             (set-node-next! new-node (node-next current))
                             (set-node-prev! (node-next current) new-node)
                             (set-node-next! current new-node)
                             (set-node-prev! new-node current)
                             (set-node-next! new-node (node-next current))
                             (set-node-prev! (node-next current) new-node)
                             (set-node-next! current new-node)
                             (set-node-prev! new-node current)
                             (set-node-next! new-node (node-next current))
                             (set-node-prev! (node-next current) new-node)
                             (set-node-next! current new-node)
                             (set-node-prev! new-node current)
                             (set-node-next! new-node (node-next current))
                             (set-node-prev! (node-next current) new-node)
                             (set-node-next! current new-node)
                             (set-node-prev! new-node current)
                             (set-node-next! new-node (node-next current))
                             (set-node-prev! (node-next current) new-node)
                             (set-node-next! current new-node)
                             (set-node-prev! new-node current)
                             (set-node-next! new-node (node-next current))
                             (set-node-prev! (node-next current) new-node)
                             (set-node-next! current new-node)
                             (set-node-prev! new-node current)
                             (set-node-next! new-node (node-next current))
                             (set-node-prev! (node-next current) new-node)
                             (set-node-next! current new-node)
                             (set-node-prev! new-node current)
                             (set-node-next! new-node (node-next current))
                             (set-node-prev! (node-next current) new-node)
                             (set-node-next! current new-node)
                             (set-node-prev! new-node current)
                             (set-node-next! new-node (node-next current))
                             (set-node-prev! (node-next current) new-node)
                             (set-node-next! current new-node)
                             (set-node-prev! new-node current)
                             (set-node-next! new-node (node-next current))
                             (set-node-prev! (node-next current) new-node)
                             (set-node-next! current new-node)
                             (set-node-prev! new-node current)
                             (set-node-next! new-node (node-next current))
                             (set-node-prev! (node-next current) new-node)
                             (set-node-next! current new-node)
                             (set-node-prev! new-node current)
                             (set-node-next! new-node (node-next current))
                             (set-node-prev! (node-next current) new-node)
                             (set-node-next! current new-node)
                             (set-node-prev! new-node current)
                             (set-node-next! new-node (node-next current))
                             (set-node-prev! (node-next current) new-node)
                             (set-node-next! current new-node)
                             (set-node-prev! new-node current)
                             (set-node-next! new-node (node-next current))
                             (set-node-prev! (node-next current) new-node)
                             (set-node-next! current new-node)
                             (set-node-prev! new-node current)
                             (set-node-next! new-node (node-next current))
                             (set-node-prev!