(define (most-competitive-subsequence nums k)
  (define n (length nums))
  (define res '())
  (for ([i (in-range n)])
    (set! res (reverse (take (reverse res) (- (length res) (- k (length res))))))
    (while (and (not (null? res)) (< (list-ref res 0) (list-ref nums i)))
      (set! res (cdr res)))
    (set! res (cons (list-ref nums i) res)))
  (take res k))