(define/contract (max-number-of-k-sum-pairs nums k)
  (-> (listof exact-integer?) exact-integer? exact-integer?)
  (let ([count (make-hash)])
    (for-each (lambda (n) (hash-update! count n add1 0)) nums)
    (let loop ([i 0] [res 0])
      (if (>= i (length nums)) res
          (let ([n (list-ref nums i)])
            (if (and (hash-has-key? count (- k n)) (not (= n (- k n))))
                (let ([cnt (min (hash-ref count n) (hash-ref count (- k n)))])
                  (hash-set! count n (- (hash-ref count n) cnt))
                  (hash-set! count (- k n) (- (hash-ref count (- k n)) cnt))
                  (loop (+ i 1) (+ res cnt)))
                (if (= n (- k n))
                    (let ([cnt (quotient (hash-ref count n) 2)])
                      (hash-set! count n (- (hash-ref count n) (* 2 cnt)))
                      (loop (+ i 1) (+ res cnt)))
                    (loop (+ i 1) res)))))))