(define (sum-absolute-differences nums)
  (let* ((n (length nums))
         (prefix (make-vector n 0)))
    (vector-set! prefix 0 0)
    (for ([i (in-range 1 n)])
      (vector-set! prefix i (+ (vector-ref prefix (- i 1)) (list-ref nums (- i 1)))))
    (let ([res 0])
      (for ([i (in-range n)])
        (set! res (+ res (- (* (list-ref nums i) i) (vector-ref prefix i))
                      (- (vector-ref prefix (- n 1)) (vector-ref prefix i) (* (list-ref nums i) (- n 1))))))
      res)))