(define (average-waiting-time customers)
  (let loop ((customers customers) (current-time 0) (total-wait 0))
    (if (null? customers)
        (/ total-wait (length customers))
        (let* ((customer (car customers))
               (arrival (car customer))
               (time (cadr customer))
               (start (max current-time arrival))
               (end (+ start time))
               (wait (- end arrival)))
          (loop (cdr customers) end (+ total-wait wait))))))
(define (main)
  (define input '((2 3) (3 5) (7 4) (10 8) (11 6)))
  (display (average-waiting-time input)))