#lang racket

(define (min-trio-degree n edges)
  (define adj (make-hash))
  (for ([u (in-range 1 (add1 n))])
    (hash-set! adj u '()))
  (for ([e (in-list edges)])
    (define u (car e))
    (define v (cadr e))
    (hash-set! adj u (cons v (hash-ref adj u)))
    (hash-set! adj v (cons u (hash-ref adj v))))
  (define min-degree (expt 2 30))
  (for ([i (in-range 1 (add1 n))])
    (for ([j (in-range (add1 i) (add1 n))])
      (when (and (member j (hash-ref adj i)) (member i (hash-ref adj j)))
        (for ([k (in-range (add1 j) (add1 n))])
          (when (and (member k (hash-ref adj i)) (member k (hash-ref adj j)))
            (define deg (+ (length (hash-ref adj i)) (length (hash-ref adj j)) (length (hash-ref adj k))))
            (set! min-degree (min min-degree deg))))))
  min-degree)