(define/contract (highest-peak grid)
  (-> (listof (listof exact-integer?)) (listof (listof exact-integer?)))
  (let* ([m (length grid)]
         [n (if (null? grid) 0 (length (car grid)))])
    (define dist (make-vector m (make-vector n -1)))
    (define q (queue))
    (for ([i (in-range m)])
      (for ([j (in-range n)])
        (when (= (vector-ref (vector-ref grid i) j) 0)
          (vector-set! (vector-ref dist i) j 0)
          (queue-add! q (cons i j)))))
    (define dirs (list (cons 1 0) (cons -1 0) (cons 0 1) (cons 0 -1)))
    (let loop ()
      (when (not (queue-empty? q))
        (define p (queue-remove! q))
        (define i (car p))
        (define j (cdr p))
        (for-each
         (lambda (d)
           (define ni (+ i (car d)))
           (define nj (+ j (cdr d)))
           (when (and (<= 0 ni (- m 1)) (<= 0 nj (- n 1)) (= (vector-ref (vector-ref dist ni) nj) -1))
             (vector-set! (vector-ref dist ni) nj (+ (vector-ref (vector-ref dist i) j) 1))
             (queue-add! q (cons ni nj))))
         dirs)
        (loop)))
    (vector->list dist)))