(define (max-score nums ops)
  (define n (length nums))
  (define m (length ops))
  (define dp (make-vector m (make-vector m 0)))
  (define (get i j)
    (vector-ref (vector-ref dp i) j))
  (define (set! i j val)
    (vector-set! (vector-ref dp i) j val))
  (for ([i (in-range m)])
    (set! i 0 (max (* (list-ref nums i) (list-ref ops 0)) (* (list-ref nums (- n 1)) (list-ref ops 0)))))
  (for ([k (in-range 1 m)])
    (for ([i (in-range 0 (- m k))])
      (let ([j (- k i)])
        (set! i j (+ (max (* (list-ref nums i) (list-ref ops k)) (* (list-ref nums (- n j 1)) (list-ref ops k))) (get i (- j 1)))))))
  (vector-ref (vector-ref dp 0) (- m 1)))