(define (closest-dessert-cost target $)  
  (define (dfs cost index)
    (if (>= index (length $))
        (list cost)
        (append (dfs (+ cost (list-ref $ index)) (+ index 1))
                (dfs cost (+ index 1)))))
  (let ([all-costs (dfs 0 0)])
    (let loop ([diff +inf.0] [best +inf.0] [costs all-costs])
      (if (null? costs)
          best
          (let ([current (car costs)])
            (let ([current-diff (abs (- current target))])
              (if (< current-diff diff)
                  (loop current-diff current (cdr costs))
                  (if (= current-diff diff)
                      (loop diff (min best current) (cdr costs))
                      (loop diff best (cdr costs))))))))))