(define (count-nice-pairs nums)
  (define (reverse-digit n)
    (string->number (list->string (reverse (string->list (number->string n))))))
  (define (f x) (- x (reverse-digit x)))
  (define freq (make-hash))
  (for-each (lambda (x)
              (hash-update! freq (f x) add1 0))
            nums)
  (apply + (hash-values freq)))