#lang racket

(define (find-mk-average n k m)
  (define-struct queue (data size max-size))
  (define (make-queue max-size)
    (make-queue '() 0 max-size))
  (define (enqueue q x)
    (if (= (queue-size q) (queue-max-size q))
        q
        (make-queue (cons x (queue-data q)) (+ (queue-size q) 1) (queue-max-size q))))
  (define (dequeue q)
    (if (= (queue-size q) 0)
        q
        (make-queue (cdr (queue-data q)) (- (queue-size q) 1) (queue-max-size q))))
  (define (peek q)
    (if (= (queue-size q) 0)
        #f
        (car (queue-data q))))
  (define (get-data q)
    (queue-data q))

  (define (make-priority-queue compare-fn)
    (let ((heap '()))
      (define (insert x)
        (set! heap (sort (cons x heap) compare-fn)))
      (define (extract)
        (let ((x (car heap)))
          (set! heap (cdr heap))
          x))
      (define (peek)
        (if (null? heap) #f (car heap)))
      (define (size)
        (length heap))
      (define (get-heap)
        heap)
      (lambda (msg . args)
        (case msg
          ((insert) (insert (car args)))
          ((extract) (extract))
          ((peek) (peek))
          ((size) (size))
          ((get-heap) (get-heap))
          (else (error "Unknown message"))))))

  (define (mk-average)
    (let* ((q1 (make-queue n))
           (q2 (make-queue n))
           (q3 (make-queue n))
           (sum 0)
           (pq1 (make-priority-queue (lambda (a b) (< a b))))
           (pq2 (make-priority-queue (lambda (a b) (> a b))))
           (result '()))
      (define (add x)
        (when (>= (queue-size q1) n)
          (let ((old (peek q1)))
            (set! sum (- sum old))
            (dequeue q1)
            (when (<= (queue-size q2) m)
              (enqueue q2 old)
              (set! sum (+ sum old)))))
        (enqueue q1 x)
        (set! sum (+ sum x))
        (when (<= (queue-size q2) m)
          (enqueue q2 x)
          (set! sum (+ sum x)))
        (when (> (queue-size q2) m)
          (let ((old (peek q2)))
            (set! sum (- sum old))
            (dequeue q2)))
        (when (>= (queue-size q1) n)
          (let ((x (peek q1)))
            (pq1 'insert x)
            (pq2 'insert x)))
        (when (and (>= (queue-size q1) n) (>= (queue-size q2) m))
          (let ((x (pq1 'peek)))
            (pq1 'extract)
            (pq2 'insert x))
          (let ((x (pq2 'peek)))
            (pq2 'extract)
            (pq1 'insert x)))
        (when (>= (queue-size q1) n)
          (let ((x (pq1 'peek)))
            (pq1 'extract)
            (pq2 'insert x))
          (let ((x (pq2 'peek)))
            (pq2 'extract)
            (pq1 'insert x)))
        (when (>= (queue-size q1) n)
          (let ((x (pq1 'peek)))
            (pq1 'extract)
            (pq2 'insert x))
          (let ((x (pq2 'peek)))
            (pq2 'extract)
            (pq1 'insert x)))
        (when (>= (queue-size q1) n)
          (let ((x (pq1 'peek)))
            (pq1 'extract)
            (pq2 'insert x))
          (let ((x (pq2 'peek)))
            (pq2 'extract)
            (pq1 'insert x)))
        (when (>= (queue-size q1) n)
          (let ((x (pq1 'peek)))
            (pq1 'extract)
            (pq2 'insert x))
          (let ((x (pq2 'peek)))
            (pq2 'extract)
            (pq1 'insert x)))
        (when (>= (queue-size q1) n)
          (let ((x (pq1 'peek)))
            (pq1 'extract)
            (pq2 'insert x))
          (let ((x (pq2 'peek)))
            (pq2 'extract)
            (pq1 'insert x)))
        (when (>= (queue-size q1) n)
          (let ((x (pq1 'peek)))
            (pq1 'extract)
            (pq2 'insert x))
          (let ((x (pq2 'peek)))
            (pq2 'extract)
            (pq1 'insert x)))
        (when (>= (queue-size q1) n)
          (let ((x (pq1 'peek)))
            (pq1 'extract)
            (pq2 'insert x))
          (let ((x (pq2 'peek)))
            (pq2 'extract)
            (pq1 'insert x)))
        (when (>= (queue-size q1) n)
          (let ((x (pq1 'peek)))
            (pq1 'extract)
            (pq2 'insert x))
          (let ((x (pq2 'peek)))
            (pq2 'extract)
            (pq1 'insert x)))
        (when (>= (queue-size q1) n)
          (let ((x (pq1 'peek)))
            (pq1 'extract)
            (pq2 'insert x))
          (let ((x (pq2 'peek)))
            (pq2 'extract)
            (pq1 'insert x)))
        (when (>= (queue-size q1) n)
          (let ((x (pq1 'peek)))
            (pq1 'extract)
            (pq2 'insert x))
          (let ((x (pq2 'peek)))
            (pq2 'extract)
            (pq1 'insert x)))
        (when (>= (queue-size q1) n)
          (let ((x (pq1 'peek)))
            (pq1 'extract)
            (pq2 'insert x))
          (let ((x (pq2 'peek)))
            (pq2 'extract)
            (pq1 'insert x)))
        (when (>= (queue-size q1) n)
          (let ((x (pq1 'peek)))
            (pq1 'extract)
            (pq2 'insert x))
          (let ((x (pq2 'peek)))
            (pq2 'extract)
            (pq1 'insert x)))
        (when (>= (queue-size q1) n)
          (let ((x (pq1 'peek)))
            (pq1 'extract)
            (pq2 'insert x))
          (let ((x (pq2 'peek)))
            (pq2 'extract)
            (pq1 'insert x)))
        (when (>= (queue-size q1) n)
          (let ((x (pq1 'peek)))
            (pq1 'extract)
            (pq2 'insert x))
          (let ((x (pq2 'peek)))
            (pq2 'extract)
            (pq1 'insert x)))
        (when (>= (queue-size q1) n)
          (let ((x (pq1 'peek)))
            (pq1 'extract)
            (pq2 'insert x))
          (let ((x (pq2 'peek)))
            (pq2 'extract)
            (pq1 'insert x)))
        (when (>= (queue-size q1) n)
          (let ((x (pq1 'peek)))
            (pq1 'extract)
            (pq2 'insert x))
          (let ((x (pq2 'peek)))
            (pq2 'extract)
            (pq1 'insert x)))
        (when (>= (queue-size q1) n)
          (let ((x (pq1 'peek)))
            (pq1 'extract)
            (pq2 'insert x))
          (let ((x (pq2 'peek)))
            (pq2 'extract)
            (pq1 'insert x)))
        (when (>= (queue-size q1) n)
          (let ((x (pq1 'peek)))
            (pq1 'extract)
            (pq2 'insert x))
          (let ((x (pq2 'peek)))
            (pq2 'extract)
            (pq1 'insert x)))
        (when (>= (queue-size q1) n)
          (let ((x (pq1 'peek)))
            (pq1 'extract)
            (pq2 'insert x))
          (let ((x (pq2 'peek)))
            (pq2 'extract)
            (pq1 'insert x)))
        (when (>= (queue-size q1) n)
          (let ((x (pq