#lang racket

(define (min-interval queries intervals)
  (define sorted-intervals (sort intervals (lambda (a b) (< (car a) (car b)))))
  (define sorted-queries (sort (map (lambda (q) (cons q (index-of queries q))) queries) (lambda (a b) (< (car a) (car b)))))
  (define result (make-vector (length queries)))
  (define i 0)
  (for ([q sorted-queries])
    (define q-val (car q))
    (define q-index (cdr q))
    (while (and (< i (length sorted-intervals)) (< (car (list-ref sorted-intervals i)) q-val))
      (set! i (+ i 1)))
    (define min-len #f)
    (for ([j (in-range i (length sorted-intervals))])
      (define start (car (list-ref sorted-intervals j)))
      (define end (cadr (list-ref sorted-intervals j)))
      (when (<= start q-val)
        (define len (- end start 1))
        (if (or (not min-len) (< len min-len))
            (set! min-len len))))
    (vector-set! result q-index (if min-len min-len #f)))
  (vector->list result))