#lang racket

(define (largest-color-value s edges)
  (define n (string-length s))
  (define adj (make-vector n '()))
  (for-each (lambda (e)
              (vector-set! adj (car e) (cons (cadr e) (vector-ref adj (car e)))))
            edges)
  (define color-counts (make-vector n 0))
  (define visited (make-vector n #f))
  (define in-stack (make-vector n #f))
  (define max-color 0)
  (define (dfs u)
    (vector-set! in-stack u #t)
    (vector-set! visited u #t)
    (for-each (lambda (v)
                (when (not (vector-ref visited v))
                  (dfs v))
                (when (vector-ref in-stack v)
                  (error "cycle"))
                (define cnt (vector-ref color-counts u))
                (define new-cnt (add1 (vector-ref color-counts v)))
                (vector-set! color-counts u (max cnt new-cnt)))
              (vector-ref adj u))
    (vector-set! in-stack u #f))
  (for-each (lambda (u)
              (when (not (vector-ref visited u))
                (dfs u)))
            (range n))
  (apply max (vector->list color-counts)))