(define (sort-sentence s)
  (define (split-word word)
    (let ((pos (string->number (substring word (- (string-length word) 1)))))
      (values (substring word 0 (- (string-length word) 1)) pos)))
  (define (sort-pairs pairs)
    (sort pairs (lambda (a b) (< (cdr a) (cdr b)))))
  (define (build-string sorted-pairs)
    (apply string-append (map (lambda (p) (car p)) sorted-pairs)))
  (build-string (sort-pairs (map (lambda (word) (call-with-values (lambda () (split-word word)) list)) (string-split s " ")))) )