(define (rotate-grid grid r)
  (define rows (length grid))
  (define cols (length (car grid)))
  (define total (exact-round (* rows cols)))
  (define (index->pos idx)
    (let ((row (quotient idx cols))
          (col (remainder idx cols)))
      (cons row col)))
  (define (pos->index pos)
    (let ((row (car pos))
          (col (cdr pos)))
      (+ (* row cols) col)))
  (define (rotate-index idx)
    (let ((new-idx (modulo (+ idx r) total)))
      new-idx))
  (define result (make-vector total 0))
  (for-each
   (lambda (i)
     (let* ((pos (index->pos i))
            (new-idx (rotate-index i))
            (new-pos (index->pos new-idx)))
       (vector-set! result new-idx (vector-ref grid (car pos) (cdr pos)))))
   (range total))
  (define (vector->grid vec)
    (map
     (lambda (row)
       (map
        (lambda (col)
          (vector-ref vec (+ (* row cols) col)))
        (range cols)))
     (range rows)))
  (vector->grid result))