(define (number-of-wonderful-substrings s)
  (define cnt (make-hash))
  (hash-set! cnt 0 1)
  (define ans 0)
  (define mask 0)
  (for ([c s])
    (set! mask (bitwise-xor mask (arithmetic-shift 1 (- (char->integer c) (char->integer #\a)))))
    (for ([i (in-range 26)])
      (when (hash-has-key? cnt (bitwise-xor mask (arithmetic-shift 1 i)))
        (set! ans (+ ans (hash-ref cnt (bitwise-xor mask (arithmetic-shift 1 i)))))))
    (hash-update! cnt mask add1 0))
  ans)