#lang racket

(define (min-cost-to-reach-destination n roads time limit)
  (define graph (make-hash))
  (for ([road roads])
    (define u (car road))
    (define v (cadr road))
    (define cost (caddr road))
    (hash-update! graph u (λ (lst) (cons (cons v cost) lst)) '()))
  (define dp (make-vector (+ n 1) +inf.0))
  (vector-set! dp 0 0)
  (for ([i (in-range 1 (add1 n))])
    (for ([u (in-range 0 n)])
      (when (hash-has-key? graph u)
        (for ([edge (hash-ref graph u)])
          (define v (car edge))
          (define cost (cdr edge))
          (when (<= (+ (vector-ref dp u) cost) limit)
            (when (< (vector-ref dp v) (+ (vector-ref dp u) cost))
              (vector-set! dp v (+ (vector-ref dp u) cost)))))))
    (when (> (vector-ref dp i) +inf.0)
      (return +inf.0)))
  (vector-ref dp n))