(define (largest-number s)
  (define (char->int c) (- (char->integer c) (char->integer #\0)))
  (define (int->char i) (integer->char (+ i (char->integer #\0))))
  (define (max-digit s)
    (let loop ([i 0] [max-d 0])
      (if (= i (string-length s))
          max-d
          (let ([d (char->int (string-ref s i))])
            (if (> d max-d)
                (loop (+ i 1) d)
                (loop (+ i 1) max-d))))))
  (define (mutate s)
    (let ([max-d (max-digit s)])
      (let loop ([i 0] [res '()])
        (if (= i (string-length s))
            (list->string (reverse res))
            (let ([d (char->int (string-ref s i))])
              (if (= d max-d)
                  (loop (+ i 1) (cons (int->char max-d) res))
                  (loop (+ i 1) (cons (int->char d) res))))))))
  (mutate s))