#lang racket

(define (min-total-space-wasted k w)
  (define n (length w))
  (define dp (make-vector (+ k 1) (make-vector (+ n 1) 0)))
  (define pre (make-vector (+ n 1) 0))
  (for ([i (in-range 1 n)])
    (vector-set! pre i (+ (vector-ref pre (- i 1)) (vector-ref w (- i 1)))))
  (for ([k-i (in-range 0 (+ k 1))])
    (for ([j (in-range 1 (+ n 1))])
      (when (zero? k-i)
        (vector-set! (vector-ref dp k-i) j (- (vector-ref pre j) (vector-ref w (- j 1))))
        (continue))
      (for ([i (in-range 1 j)])
        (define cost (- (vector-ref pre j) (vector-ref pre i) (* (vector-ref w (- j 1)) (- j i))))
        (define prev (vector-ref (vector-ref dp (- k-i 1)) i))
        (define current (+ prev cost))
        (when (> (vector-ref (vector-ref dp k-i) j) current)
          (vector-set! (vector-ref dp k-i) j current)))))
  (vector-ref (vector-ref dp k) n))