(define (maximum-matrix-sum matrix)
  (let* ((n (length matrix))
         (m (length (car matrix)))
         (min-abs (make-vector (* n m) 0))
         (total 0)
         (min-val +inf.0))
    (for ([i (in-range n)])
      (for ([j (in-range m)])
        (let ([val (list-ref (list-ref matrix i) j)])
          (vector-set! min-abs (+ (* i m) j) (abs val))
          (set! total (+ total val))
          (when (< (abs val) min-val)
            (set! min-val (abs val))))))
    (if (even? (vector-count (lambda (x) (<= x 0)) min-abs))
        total
        (- total (* 2 min-val))))
  )