(define (find-unique-binary-string nums)
  (define (bit->int s)
    (string->number s 2))
  (define (int->bit n)
    (number->string n 2))
  (define len (string-length (car nums)))
  (define used (make-hash))
  (for-each (lambda (s) (hash-set! used (bit->int s) #t)) nums)
  (for ([i (in-range (expt 2 len))])
    (when (not (hash-has-key? used i))
      (return (string-pad (int->bit i) len #\0))))
  #f)