(define (find-farmland-Groups land)
  (define rows (length land))
  (define cols (if (> rows 0) (length (car land)) 0))
  (define visited (make-vector rows #f))
  (define (dfs i j)
    (when (and (< i rows) (< j cols) (not (vector-ref visited i)) (= (list-ref (list-ref land i) j) 1))
      (vector-set! visited i #t)
      (let ((down (if (< (+ i 1) rows) (list-ref (list-ref land (+ i 1)) j) 0)))
        (if (and (>= down 1) (= (list-ref (list-ref land i) j) 1))
            (dfs (+ i 1) j)
            (let ((right (if (< (+ j 1) cols) (list-ref (list-ref land i) (+ j 1)) 0)))
              (if (and (>= right 1) (= (list-ref (list-ref land i) j) 1))
                  (dfs i (+ j 1))
                  (let ((group (list i j)))
                    (let loop ((x i) (y j))
                      (when (and (< x rows) (< y cols) (= (list-ref (list-ref land x) y) 1))
                        (vector-set! visited x #t)
                        (loop (+ x 1) y)
                        (loop x (+ y 1)))
                    (list group))))))))
  (define result '())
  (for-each
   (lambda (i)
     (when (not (vector-ref visited i))
       (let ((j 0))
         (when (= (list-ref (list-ref land i) j) 1)
           (let ((group (dfs i j)))
             (set! result (cons group result))))))
   (range rows))
  (reverse result))