(define (sum-beauty nums)
  (define n (length nums))
  (define left (make-vector n 0))
  (define right (make-vector n 0))
  (define (get-left)
    (let loop ((i 1) (min-so-far (vector-ref nums 0)))
      (when (< i n)
        (vector-set! left i (if (< (vector-ref nums i) min-so-far) 0 1))
        (loop (+ i 1) (min min-so-far (vector-ref nums i))))))
  (define (get-right)
    (let loop ((i (- n 2)) (max-so-far (vector-ref nums (- n 1))))
      (when (>= i 0)
        (vector-set! right i (if (> (vector-ref nums i) max-so-far) 0 1))
        (loop (- i 1) (max max-so-far (vector-ref nums i))))))
  (get-left)
  (get-right)
  (apply + (map (lambda (l r) (+ l r)) (vector->list left) (vector->list right)))
)