#lang racket

(define (detect-squares points)
  (define point-count (make-hash))
  (define (add-point p)
    (hash-update! point-count p add1 0))
  (for-each add-point points)
  (define result 0)
  (for ([p1 points])
    (define x1 y1)
    (define x2 y2)
    (for ([p2 points])
      (when (and (not (equal? p1 p2)) (= (car p1) (car p2)) (= (cadr p1) (cadr p2)))
        (continue))
      (define x3 y3)
      (define x4 y4)
      (when (and (= x1 x3) (= y2 y4) (= x2 x4) (= y1 y3))
        (define count (hash-ref point-count (list x3 y3) 0))
        (set! result (+ result count))))
  result)