(define (grid-game grid)
  (define rows (length grid))
  (define cols (length (car grid)))
  (define (sum-row row idx)
    (if (>= idx (length row)) 0 (+ (list-ref row idx) (sum-row row (+ idx 1)))))
  (define (sum-col col idx)
    (if (>= idx (length col)) 0 (+ (list-ref col idx) (sum-col col (+ idx 1)))))
  (define (min-robot-score)
    (let loop ((i 0) (top 0) (bottom 0))
      (if (>= i cols)
          (min top bottom)
          (let ((top-sum (- (sum-row (list-ref grid 0) i) (sum-row (list-ref grid 0) (+ i 1))))
                (bottom-sum (- (sum-col (map (lambda (row) (list-ref row i)) grid) 1) (sum-col (map (lambda (row) (list-ref row i)) grid) (+ i 1)))))
            (loop (+ i 1) (min top (max top-sum bottom-sum)) (min bottom (max top-sum bottom-sum))))))
  (min-robot-score))