#lang racket

(define (can-finish num-courses prerequisites)
  (define graph (make-hash))
  (define in-degree (make-hash))
  (for ([i (in-range num-courses)])
    (hash-set! graph i '())
    (hash-set! in-degree i 0))
  (for ([prereq (in-list prerequisites)])
    (define course (second prereq))
    (define pre (first prereq))
    (hash-set! graph course (cons pre (hash-ref graph course)))
    (hash-set! in-degree pre (+ 1 (hash-ref in-degree pre))))
  (define queue (queue))
  (for ([i (in-range num-courses)])
    (when (= 0 (hash-ref in-degree i))
      (queue-add! queue i)))
  (define count 0)
  (while (not (queue-empty? queue))
    (define course (queue-remove! queue))
    (set! count (+ count 1))
    (for ([neighbor (hash-ref graph course)])
      (hash-set! in-degree neighbor (- (hash-ref in-degree neighbor) 1))
      (when (= 0 (hash-ref in-degree neighbor))
        (queue-add! queue neighbor))))
  (= count num-courses))