#lang racket

(define (max-tasks-possible tasks nums)
  (define (can-assign k)
    (define sorted-tasks (sort tasks <))
    (define sorted-nums (sort nums <))
    (define n (length sorted-tasks))
    (define m (length sorted-nums))
    (define i (- m 1))
    (define j (- n 1))
    (define count 0)
    (let loop ()
      (when (and (>= i 0) (>= j 0))
        (when (<= (list-ref sorted-tasks j) (list-ref sorted-nums i))
          (set! count (+ count 1))
          (set! j (- j 1)))
        (set! i (- i 1))
        (loop))
    count)
  )
  (define low 0)
  (define high (min (length tasks) (length nums)))
  (define answer 0)
  (let loop ()
    (when (<= low high)
      (define mid (quotient (+ low high) 2))
      (if (>= (can-assign mid) mid)
          (begin
            (set! answer mid)
            (set! low (+ mid 1)))
          (set! high (- mid 1))))
    (when (<= low high)
      (loop)))
  answer)