(define (max-distance colors)
  (define n (length colors))
  (define (distance i j)
    (abs (- i j)))
  (define (diff-colors? i j)
    (not (= (list-ref colors i) (list-ref colors j))))
  (define (helper i j max-dist)
    (if (>= i n)
        max-dist
        (if (>= j n)
            (helper (+ i 1) 0 max-dist)
            (if (diff-colors? i j)
                (helper i (+ j 1) (max max-dist (distance i j)))
                (helper i (+ j 1) max-dist)))))
  (helper 0 0 0))