(define (count-fertile-pyramids land)
  (define n (length land))
  (define m (if (> n 0) (length (car land)) 0))
  (define dp (make-vector n (make-vector m 0)))
  (define (max-pyramid-size i j)
    (if (or (= i (- n 1)) (= j 0) (= j (- m 1)) (not (= (vector-ref (vector-ref land i) j) 1)))
        0
        (let ((a (vector-ref (vector-ref dp (+ i 1) ) (- j 1)))
              (b (vector-ref (vector-ref dp (+ i 1) ) j))
              (c (vector-ref (vector-ref dp (+ i 1) ) (+ j 1))))
          (if (and (>= a 1) (>= b 1) (>= c 1))
              (+ 1 (min a b c))
              0))))
  (define (update-dp i j)
    (vector-set! (vector-ref dp i) j (max-pyramid-size i j)))
  (for ([i (in-range n)])
    (for ([j (in-range m)])
      (update-dp i j)))
  (define total 0)
  (for ([i (in-range n)])
    (for ([j (in-range m)])
      (set! total (+ total (vector-ref (vector-ref dp i) j)))))
  total)