#lang racket

(define (find-3-digit-even-numbers digits)
  (define (to-number a b c)
    (+ (* 100 a) (* 10 b) c))
  (define (is-even n)
    (= (modulo n 2) 0))
  (define (distinct? lst)
    (= (length lst) (length (remove-duplicates lst))))
  (define result '())
  (for ([i (in-range 0 (length digits))])
    (for ([j (in-range 0 (length digits))])
      (when (not (= i j))
        (for ([k (in-range 0 (length digits))])
          (when (and (not (= i k)) (not (= j k)))
            (let ([num (to-number (list-ref digits i) (list-ref digits j) (list-ref digits k))])
              (when (and (>= num 100) (is-even num))
                (set! result (cons num result))))))))
  (remove-duplicates (sort result <)))