(define (good-days-to-rob-bank security)
  (define n (length security))
  (if (= n 0) '() (let ((left (make-vector n 0))
                        (right (make-vector n 0)))
                    (for ([i (in-range 1 n)])
                      (when (<= (list-ref security (sub1 i)) (list-ref security i))
                        (vector-set! left i (+ (vector-ref left (sub1 i)) 1))))
                    (for ([i (in-range (sub1 n) -1 -1)])
                      (when (<= (list-ref security (add1 i)) (list-ref security i))
                        (vector-set! right i (+ (vector-ref right (add1 i)) 1))))
                    (filter (lambda (i) (and (>= (vector-ref left i) 1) (>= (vector-ref right i) 1)))
                            (range n)))))