(define (find-kth-largest nums k)
  (define (quick-select left right k)
    (let ((pivot (random-ref nums left right)))
      (let ((partitioned (partition nums left right pivot)))
        (let ((p (car partitioned)))
          (if (= p (- k 1))
              (list-ref nums p)
              (if (< p (- k 1))
                  (quick-select (+ p 1) right (- k p 1))
                  (quick-select left (- p 1) k))))))
  (define (random-ref nums left right)
    (list-ref nums (random (- right left) left)))
  (define (partition nums left right pivot)
    (let ((pivot-val (list-ref nums pivot)))
      (let ((swap (lambda (i j)
                    (let ((temp (list-ref nums i)))
                      (set! nums (list-set nums i (list-ref nums j)))
                      (set! nums (list-set nums j temp)))))
        (let ((store-index left))
          (let loop ((i left))
            (when (<= i right)
              (when (< (list-ref nums i) pivot-val)
                (swap i store-index)
                (set! store-index (+ store-index 1)))
              (loop (+ i 1))))
        (swap store-index right)
        (list store-index))))
  (quick-select 0 (- (length nums) 1) k))