#lang racket

(define (max-score nums)
  (define n (length nums))
  (define zeros (make-vector n 0))
  (define ones (make-vector n 0))
  (define current-zero 0)
  (define current-one 0)
  (for ([i (in-range n)])
    (if (= (list-ref nums i) 0)
        (set! current-zero (+ current-zero 1))
        (set! current-one (+ current-one 1)))
    (vector-set! zeros i current-zero)
    (vector-set! ones i current-one))
  (define max-score 0)
  (define result '())
  (for ([i (in-range (add1 n))])
    (define left-zero (if (= i 0) 0 (vector-ref zeros (- i 1))))
    (define left-one (if (= i 0) 0 (vector-ref ones (- i 1))))
    (define right-zero (- (vector-ref zeros (- n 1)) left-zero))
    (define right-one (- (vector-ref ones (- n 1)) left-one))
    (define score (+ left-zero right-one))
    (when (> score max-score)
      (set! max-score score)
      (set! result (list i)))
    (when (= score max-score)
      (set! result (append result (list i)))))
  result)