#lang racket

(define (sub-str-hashes s target)
  (define len (string-length s))
  (define base 256)
  (define mod 1000000007)
  (define pow (make-vector len 1))
  (for ([i (in-range 1 len)])
    (vector-set! pow i (modulo (* (vector-ref pow (- i 1)) base) mod)))
  (define hash (make-vector len 0))
  (vector-set! hash 0 (modulo (char->integer (string-ref s 0)) mod))
  (for ([i (in-range 1 len)])
    (vector-set! hash i (modulo (+ (* (vector-ref hash (- i 1)) base) (char->integer (string-ref s i))) mod)))
  (define (get-hash l r)
    (if (= l 0)
        (vector-ref hash r)
        (modulo (- (vector-ref hash r) (* (vector-ref hash (- l 1)) (vector-ref pow (- r l + 1)))) mod)))
  (define result -1)
  (for ([i (in-range len)])
    (when (>= (- len i) (string-length target))
      (define current-hash (get-hash i (+ i (string-length target) -1)))
      (when (= current-hash target)
        (set! result i))))
  result)

(define (main)
  (define input (read-line))
  (define target (string->number (read-line)))
  (define result (sub-str-hashes input target))
  (printf "~a\n" result))

(main)