(define (count-good-triplets arr)
  (define n (length arr))
  (define count 0)
  (for ([i (in-range n)])
    (for ([j (in-range (+ i 1) n)])
      (for ([k (in-range (+ j 1) n)])
        (when (and (<= (abs (- (list-ref arr i) (list-ref arr j))) 2)
                   (<= (abs (- (list-ref arr j) (list-ref arr k))) 2)
                   (<= (abs (- (list-ref arr i) (list-ref arr k))) 2))
          (set! count (+ count 1))))))
  count)