(define (count-artifacts artifacts,1,2)
  (define (count-ones lst)
    (foldl + 0 (map (lambda (x) (if (= x 1) 1 0)) lst)))
  (define (is-complete? row col)
    (and (<= 0 row (sub1 (length artifacts)))
         (<= 0 col (sub1 (length (list-ref artifacts row))))
         (= 1 (list-ref (list-ref artifacts row) col))))
  (define (check-cell row col)
    (if (is-complete? row col)
        1
        0))
  (define (process-row row)
    (define row-data (list-ref artifacts row))
    (define len (length row-data))
    (define (loop col res)
      (if (>= col len)
          res
          (loop (+ col 1) (+ res (check-cell row col)))))
    (loop 0 0))
  (define (loop-row r res)
    (if (>= r (length artifacts))
        res
        (loop-row (+ r 1) (+ res (process-row r)))))
  (loop-row 0 0))