#lang racket

(define (encrypt s)
  (define (char->code c)
    (- (char->integer c) 97))
  (define (code->char c)
    (integer->char (+ c 97)))
  (define (shift c shift)
    (mod (+ c shift) 26))
  (define (process-char c)
    (if (char-alphabetic? c)
        (code->char (shift (char->code c) 1))
        c))
  (list->string (map process-char (string->list s))))

(define (decrypt s)
  (define (char->code c)
    (- (char->integer c) 97))
  (define (code->char c)
    (integer->char (+ c 97)))
  (define (shift c shift)
    (mod (+ c shift) 26))
  (define (process-char c)
    (if (char-alphabetic? c)
        (code->char (shift (char->code c) 25))
        c))
  (list->string (map process-char (string->list s))))