(define (maximum-product nums k)
  (define (heapify arr)
    (let loop ([i 0])
      (when (< i (vector-length arr))
        (let ([left (+ (* i 2) 1)]
              [right (+ (* i 2) 2)])
          (when (and (< left (vector-length arr)) (> (vector-ref arr left) (vector-ref arr i)))
            (let ([temp (vector-ref arr i)])
              (vector-set! arr i (vector-ref arr left))
              (vector-set! arr left temp)
              (loop left)))
          (when (and (< right (vector-length arr)) (> (vector-ref arr right) (vector-ref arr i)))
            (let ([temp (vector-ref arr i)])
              (vector-set! arr i (vector-ref arr right))
              (vector-set! arr right temp)
              (loop right))))
        (loop (+ i 1)))))

  (define (heappop arr)
    (let ([val (vector-ref arr 0)])
      (vector-set! arr 0 (vector-ref arr (- (vector-length arr) 1)))
      (vector-set! arr (- (vector-length arr) 1) #f)
      (let loop ([i 0])
        (let ([left (+ (* i 2) 1)]
              [right (+ (* i 2) 2)])
          (when (and (< left (vector-length arr)) (> (vector-ref arr left) (vector-ref arr i)))
            (let ([temp (vector-ref arr i)])
              (vector-set! arr i (vector-ref arr left))
              (vector-set! arr left temp)
              (loop left)))
          (when (and (< right (vector-length arr)) (> (vector-ref arr right) (vector-ref arr i)))
            (let ([temp (vector-ref arr i)])
              (vector-set! arr i (vector-ref arr right))
              (vector-set! arr right temp)
              (loop right))))
      val))

  (define (heappush arr val)
    (vector-set! arr (vector-length arr) val)
    (let loop ([i (- (vector-length arr) 1)])
      (let ([parent (quotient (- i 1) 2)])
        (when (and (> i 0) (> (vector-ref arr i) (vector-ref arr parent)))
          (let ([temp (vector-ref arr i)])
            (vector-set! arr i (vector-ref arr parent))
            (vector-set! arr parent temp)
            (loop parent)))))

  (let ([heap (list->vector (sort nums >))])
    (heapify heap)
    (let loop ([k k])
      (when (> k 0)
        (let ([min (heappop heap)])
          (heappush heap (+ min 1))
          (loop (- k 1))))
    (apply * (vector->list heap))))