(define (count-unguarded-cells grid)
  (define rows (length grid))
  (define cols (if (> rows 0) (length (car grid)) 0))
  (define directions '((0 1) (1 0) (0 -1) (-1 0)))
  (define cell-set (make-hash))
  (for ([i (in-range rows)])
    (for ([j (in-range cols)])
      (hash-set! cell-set (cons i j) #f)))

  (define (mark-visited x y)
    (when (and (<= 0 x (- rows 1)) (<= 0 y (- cols 1)))
      (when (not (hash-ref cell-set (cons x y)))
        (hash-set! cell-set (cons x y) #t))))

  (for ([i (in-range rows)])
    (for ([j (in-range cols)])
      (when (= (list-ref (list-ref grid i) j) 1)
        (for ([d directions])
          (define dx (car d))
          (define dy (cadr d))
          (define x (+ i dx))
          (define y (+ j dy))
          (when (and (<= 0 x (- rows 1)) (<= 0 y (- cols 1)))
            (let loop ()
              (when (and (<= 0 x (- rows 1)) (<= 0 y (- cols 1)))
                (when (not (hash-ref cell-set (cons x y)))
                  (hash-set! cell-set (cons x y) #t))
                (set! x (+ x dx))
                (set! y (+ y dy))
                (loop)))))))

  (hash-count (lambda (k v) (not v)) cell-set))