(define (subarrays-with-k-divisible-elements nums k)
  (define n (length nums))
  (define result 0)
  (define (is-divisible? x)
    (= (remainder x k) 0))
  (define (count-subarrays start)
    (let loop ((end start) (count 0))
      (if (>= end n)
          count
          (if (is-divisible? (list-ref nums end))
              (loop (+ end 1) (+ count 1))
              (loop (+ end 1) count))))
    )
  (let loop ((i 0))
    (when (< i n)
      (set! result (+ result (count-subarrays i)))
      (loop (+ i 1))))
  result)