(define (maximum-white-tiles-covered-by-a-carpet tiles carpet-len)
  (define (compare a b)
    (< (car a) (car b)))
  (define sorted-tiles (sort tiles compare))
  (define n (length sorted-tiles))
  (define result (box 0))
  (define i 0)
  (define j 0)
  (define current 0)
  (define (add-tile x y)
    (set-box! current (+ current (- y x 1))))
  (define (remove-tile x y)
    (set-box! current (- current (- y x 1))))
  (define (get-end x)
    (+ x carpet-len -1))
  (define (get-start x)
    (- x carpet-len 1))
  (define (overlap? x y)
    (<= (get-start x) y (get-end x)))
  (define (process-j)
    (when (< j n)
      (let ((x (caar (list-ref sorted-tiles j)))
            (y (cadar (list-ref sorted-tiles j))))
        (if (<= (get-end x) (get-end (caar (list-ref sorted-tiles i))))
            (begin
              (add-tile x y)
              (set! j (+ j 1))
              (process-j))
            (begin
              (if (overlap? x y)
                  (begin
                    (add-tile x y)
                    (set! j (+ j 1))
                    (process-j))
                  (begin
                    (set-box! result (max (unbox result) (unbox current)))
                    (remove-tile (caar (list-ref sorted-tiles i)) (cadar (list-ref sorted-tiles i)))
                    (set! i (+ i 1))
                    (process-j)))))))
  (process-j)
  (unbox result))