(define (distinct-words words)
  (define (count-unique s)
    (let ([set (set)])
      (for ([c s])
        (set-add! set c))
      (set-count set)))
  (define freq (make-hash))
  (for ([word words])
    (let ([cnt (count-unique word)])
      (hash-update! freq cnt add1 0)))
  (hash-values freq))

(define (distinct-words2 words)
  (define (count-unique s)
    (let ([set (set)])
      (for ([c s])
        (set-add! set c))
      (set-count set)))
  (define freq (make-hash))
  (for ([word words])
    (let ([cnt (count-unique word)])
      (hash-update! freq cnt add1 0)))
  (hash-values freq))

(define (number-of-similar-strings words)
  (define (count-unique s)
    (let ([set (set)])
      (for ([c s])
        (set-add! set c))
      (set-count set)))
  (define freq (make-hash))
  (for ([word words])
    (let ([cnt (count-unique word)])
      (hash-update! freq cnt add1 0)))
  (define res 0)
  (for ([v (hash-values freq)])
    (when (> v 1)
      (set! res (+ res (* v (- v 1))))))
  res)

(define (distinct-words3 words)
  (define (count-unique s)
    (let ([set (set)])
      (for ([c s])
        (set-add! set c))
      (set-count set)))
  (define freq (make-hash))
  (for ([word words])
    (let ([cnt (count-unique word)])
      (hash-update! freq cnt add1 0)))
  (hash-values freq))

(define (distinct-words4 words)
  (define (count-unique s)
    (let ([set (set)])
      (for ([c s])
        (set-add! set c))
      (set-count set)))
  (define freq (make-hash))
  (for ([word words])
    (let ([cnt (count-unique word)])
      (hash-update! freq cnt add1 0)))
  (hash-values freq))

(define (distinct-words5 words)
  (define (count-unique s)
    (let ([set (set)])
      (for ([c s])
        (set-add! set c))
      (set-count set)))
  (define freq (make-hash))
  (for ([word words])
    (let ([cnt (count-unique word)])
      (hash-update! freq cnt add1 0)))
  (hash-values freq))

(define (distinct-words6 words)
  (define (count-unique s)
    (let ([set (set)])
      (for ([c s])
        (set-add! set c))
      (set-count set)))
  (define freq (make-hash))
  (for ([word words])
    (let ([cnt (count-unique word)])
      (hash-update! freq cnt add1 0)))
  (hash-values freq))

(define (distinct-words7 words)
  (define (count-unique s)
    (let ([set (set)])
      (for ([c s])
        (set-add! set c))
      (set-count set)))
  (define freq (make-hash))
  (for ([word words])
    (let ([cnt (count-unique word)])
      (hash-update! freq cnt add1 0)))
  (hash-values freq))

(define (distinct-words8 words)
  (define (count-unique s)
    (let ([set (set)])
      (for ([c s])
        (set-add! set c))
      (set-count set)))
  (define freq (make-hash))
  (for ([word words])
    (let ([cnt (count-unique word)])
      (hash-update! freq cnt add1 0)))
  (hash-values freq))

(define (distinct-words9 words)
  (define (count-unique s)
    (let ([set (set)])
      (for ([c s])
        (set-add! set c))
      (set-count set)))
  (define freq (make-hash))
  (for ([word words])
    (let ([cnt (count-unique word)])
      (hash-update! freq cnt add1 0)))
  (hash-values freq))

(define (distinct-words10 words)
  (define (count-unique s)
    (let ([set (set)])
      (for ([c s])
        (set-add! set c))
      (set-count set)))
  (define freq (make-hash))
  (for ([word words])
    (let ([cnt (count-unique word)])
      (hash-update! freq cnt add1 0)))
  (hash-values freq))

(define (distinct-words11 words)
  (define (count-unique s)
    (let ([set (set)])
      (for ([c s])
        (set-add! set c))
      (set-count set)))
  (define freq (make-hash))
  (for ([word words])
    (let ([cnt (count-unique word)])
      (hash-update! freq cnt add1 0)))
  (hash-values freq))

(define (distinct-words12 words)
  (define (count-unique s)
    (let ([set (set)])
      (for ([c s])
        (set-add! set c))
      (set-count set)))
  (define freq (make-hash))
  (for ([word words])
    (let ([cnt (count-unique word)])
      (hash-update! freq cnt add1 0)))
  (hash-values freq))

(define (distinct-words13 words)
  (define (count-unique s)
    (let ([set (set)])
      (for ([c s])
        (set-add! set c))
      (set-count set)))
  (define freq (make-hash))
  (for ([word words])
    (let ([cnt (count-unique word)])
      (hash-update! freq cnt add1 0)))
  (hash-values freq))

(define (distinct-words14 words)
  (define (count-unique s)
    (let ([set (set)])
      (for ([c s])
        (set-add! set c))
      (set-count set)))
  (define freq (make-hash))
  (for ([word words])
    (let ([cnt (count-unique word)])
      (hash-update! freq cnt add1 0)))
  (hash-values freq))

(define (distinct-words15 words)
  (define (count-unique s)
    (let ([set (set)])
      (for ([c s])
        (set-add! set c))
      (set-count set)))
  (define freq (make-hash))
  (for ([word words])
    (let ([cnt (count-unique word)])
      (hash-update! freq cnt add1 0)))
  (hash-values freq))

(define (distinct-words16 words)
  (define (count-unique s)
    (let ([set (set)])
      (for ([c s])
        (set-add! set c))
      (set-count set)))
  (define freq (make-hash))
  (for ([word words])
    (let ([cnt (count-unique word)])
      (hash-update! freq cnt add1 0)))
  (hash-values freq))

(define (distinct-words17 words)
  (define (count-unique s)
    (let ([set (set)])
      (for ([c s])
        (set-add! set c))
      (set-count set)))
  (define freq (make-hash))
  (for ([word words])
    (let ([cnt (count-unique word)])
      (hash-update! freq cnt add1 0)))
  (hash-values freq))

(define (distinct-words18 words)
  (define (count-unique s)
    (let ([set (set)])
      (for ([c s])
        (set-add! set c))
      (set-count set)))
  (define freq (make-hash))
  (for ([word words])
    (let ([cnt (count-unique word)])
      (hash-update! freq cnt add1 0)))
  (hash-values freq))

(define (distinct-words19 words)
  (define (count-unique s)
    (let ([set (set)])
      (for ([c s])
        (set-add! set c))
      (set-count set)))
  (define freq (make-hash))
  (for ([word words])
    (let ([cnt (count-unique word)])
      (hash-update! freq cnt add1 0)))
  (hash-values freq))

(define (distinct-words20 words)
  (define (count-unique s)
    (let ([set (set)])
      (for ([c s])
        (set-add! set c))
      (set-count set)))
  (define freq (make-hash))
  (for ([word words])
    (let ([cnt (count-unique word)])
      (hash-update! freq cnt add1 0)))
  (hash-values freq))

(define (distinct-words21 words)
  (define (count-unique s)
    (let ([set (set)])
      (for ([c s])
        (set-add! set c))
      (set-count set)))
  (define freq (make-hash))
  (