#lang racket

(define (make-food-rating-system)
  (define ratings (hash))
  (define cuisines (hash))
  (define (insert food cuisine rating)
    (hash-set! ratings food rating)
    (hash-update! cuisines cuisine (lambda (lst) (if lst (cons food lst) (list food))) '()))
  (define (change-rating food new-rating)
    (hash-set! ratings food new-rating))
  (define (highest-rank-cuisine cuisine)
    (let ((foods (hash-ref cuisines cuisine '())))
      (if (null? foods)
          #f
          (let loop ((foods foods) (max-food #f) (max-rating -1))
            (if (null? foods)
                max-food
                (let ((current-food (car foods)))
                  (let ((current-rating (hash-ref ratings current-food)))
                    (if (> current-rating max-rating)
                        (loop (cdr foods) current-food current-rating)
                        (loop (cdr foods) max-food max-rating))))))))
  (define (get-highest-rank-cuisine)
    (let loop ((cuisines (hash-keys cuisines)) (best-cuisine #f) (best-rating -1))
      (if (null? cuisines)
          best-cuisine
          (let* ((cuisine (car cuisines))
                 (foods (hash-ref cuisines cuisine))
                 (current-best (if (null? foods) -1 (let loop2 ((foods foods) (max-rating -1))
                                                    (if (null? foods)
                                                        max-rating
                                                        (let ((rating (hash-ref ratings (car foods))))
                                                          (loop2 (cdr foods) (max rating max-rating)))))))
            (if (> current-best best-rating)
                (loop (cdr cuisines) cuisine current-best)
                (loop (cdr cuisines) best-cuisine best-rating))))))
  (define (get-food-rating food)
    (hash-ref ratings food))
  (define (get-cuisines)
    (hash-keys cuisines))
  (lambda (op . args)
    (case op
      ((insert) (apply insert args))
      ((change-rating) (apply change-rating args))
      ((highest-rank-cuisine) (apply highest-rank-cuisine args))
      ((get-highest-rank-cuisine) (get-highest-rank-cuisine))
      ((get-food-rating) (apply get-food-rating args))
      ((get-cuisines) (get-cuisines)))))

(define (main)
  (define fs (make-food-rating-system))
  (fs 'insert "kimchi" "Korean" 8)
  (fs 'insert "miso" "Japanese" 7)
  (fs 'insert "sushi" "Japanese" 10)
  (fs 'insert "paella" "Spanish" 6)
  (fs 'insert "jajangmyeon" "Korean" 9)
  (fs 'insert "gimbap" "Korean" 8)
  (fs 'insert "ramen" "Japanese" 5)
  (fs 'insert "chocolate" "Spanish" 7)
  (fs 'insert "sashimi" "Japanese" 9)
  (fs 'insert "kimbap" "Korean" 6)
  (fs 'insert "donburi" "Japanese" 5)
  (fs 'insert "bibimbap" "Korean" 7)
  (fs 'insert "tacos" "Mexican" 8)
  (fs 'insert "nachos" "Mexican" 6)
  (fs 'insert "enchiladas" "Mexican" 7)
  (fs 'insert "tamales" "Mexican" 5)
  (fs 'insert "empanadas" "Mexican" 4)
  (fs 'insert "tacos" "Mexican" 7)
  (fs 'insert "burritos" "Mexican" 8)
  (fs 'insert "flautas" "Mexican" 6)
  (fs 'insert "churros" "Mexican" 7)
  (fs 'insert "tamales" "Mexican" 6)
  (fs 'insert "quesadillas" "Mexican" 7)
  (fs 'insert "pupusas" "Central American" 6)
  (fs 'insert "arepas" "South American" 5)
  (fs 'insert "pescado" "South American" 6)
  (fs 'insert "lomo" "South American" 7)
  (fs 'insert "arroz" "South American" 5)
  (fs 'insert "ceviche" "South American" 8)
  (fs 'insert "pisco" "South American" 6)
  (fs 'insert "caipirinha" "South American" 7)
  (fs 'insert "chicha" "South American" 5)
  (fs 'insert "papaya" "South American" 6)
  (fs 'insert "yucca" "South American" 5)
  (fs 'insert "ají" "South American" 7)
  (fs 'insert "choclo" "South American" 6)
  (fs 'insert "chicha" "South American" 6)
  (fs 'insert "pisco" "South American" 7)
  (fs 'insert "ceviche" "South American" 9)
  (fs 'insert "lomo" "South American" 8)
  (fs 'insert "arroz" "South American" 6)
  (fs 'insert "pescado" "South American" 7)
  (fs 'insert "arepas" "South American" 6)
  (fs 'insert "pupusas" "Central American" 7)
  (fs 'insert "flautas" "Mexican" 7)
  (fs 'insert "tamales" "Mexican" 7)
  (fs 'insert "tacos" "Mexican" 8)
  (fs 'insert "churros" "Mexican" 7)
  (fs 'insert "quesadillas" "Mexican" 8)
  (fs 'insert "burritos" "Mexican" 9)
  (fs 'insert "empanadas" "Mexican" 5)
  (fs 'insert "enchiladas" "Mexican" 8)
  (fs 'insert "nachos" "Mexican" 7)
  (fs 'insert "tamales" "Mexican" 7)
  (fs 'insert "flautas" "Mexican" 7)
  (fs 'insert "tacos" "Mexican" 8)
  (fs 'insert "churros" "Mexican" 7)
  (fs 'insert "quesadillas" "Mexican" 8)
  (fs 'insert "burritos" "Mexican" 9)
  (fs 'insert "empanadas" "Mexican" 5)
  (fs 'insert "enchiladas" "Mexican" 8)
  (fs 'insert "nachos" "Mexican" 7)
  (fs 'insert "tamales" "Mexican" 7)
  (fs 'insert "flautas" "Mexican" 7)
  (fs 'insert "tacos" "Mexican" 8)
  (fs 'insert "churros" "Mexican" 7)
  (fs 'insert "quesadillas" "Mexican" 8)
  (fs 'insert "burritos" "Mexican" 9)
  (fs 'insert "empanadas" "Mexican" 5)
  (fs 'insert "enchiladas" "Mexican" 8)
  (fs 'insert "nachos" "Mexican" 7)
  (fs 'insert "tamales" "Mexican" 7)
  (fs 'insert "flautas" "Mexican" 7)
  (fs 'insert "tacos" "Mexican" 8)
  (fs 'insert "churros" "Mexican" 7)
  (fs 'insert "quesadillas" "Mexican" 8)
  (fs 'insert "burritos" "Mexican" 9)
  (fs 'insert "empanadas" "Mexican" 5)
  (fs 'insert "enchiladas" "Mexican" 8)
  (fs 'insert "nachos" "Mexican" 7)
  (fs 'insert "tamales" "Mexican" 7)
  (fs 'insert "flautas" "Mexican" 7)
  (fs 'insert "tacos" "Mexican" 8)
  (fs 'insert "churros" "Mexican" 7)
  (fs 'insert "quesadillas" "Mexican" 8)
  (fs 'insert "burritos" "Mexican" 9)
  (fs 'insert "empanadas" "Mexican" 5)
  (fs 'insert "enchiladas" "Mex