(define (valid-subarray? arr start end)
  (and (<= start end)
       (or (and (= (- end start) 1)
                (= (list-ref arr start) (list-ref arr end)))
           (and (= (- end start) 2)
                (or (and (= (list-ref arr start) (list-ref arr (+ start 1)))
                         (= (list-ref arr (+ start 1)) (list-ref arr end)))
                    (and (= (list-ref arr start) (- (list-ref arr (+ start 1)) 1))
                         (= (list-ref arr (+ start 1)) (- (list-ref arr end) 1)))))
           (and (= (- end start) 3)
                (or (and (= (list-ref arr start) (list-ref arr (+ start 1)))
                         (= (list-ref arr (+ start 1)) (list-ref arr (+ start 2)))
                         (= (list-ref arr (+ start 2)) (list-ref arr end)))
                    (and (= (list-ref arr start) (- (list-ref arr (+ start 1)) 1))
                         (= (list-ref arr (+ start 1)) (- (list-ref arr (+ start 2)) 1))
                         (= (list-ref arr (+ start 2)) (- (list-ref arr end) 1))))))))

(define (valid-partition arr)
  (define n (length arr))
  (define dp (make-vector n #f))
  (vector-set! dp 0 #t)
  (for ([i (in-range 1 n)])
    (when (vector-ref dp (- i 1))
      (when (valid-subarray? arr (- i 1) i)
        (vector-set! dp i #t))
      (when (and (>= i 2)
                 (valid-subarray? arr (- i 2) i))
        (vector-set! dp i #t))
      (when (and (>= i 3)
                 (valid-subarray? arr (- i 3) i))
        (vector-set! dp i #t))))
  (vector-ref dp (- n 1)))