(define (min-number s)
  (define n (string-length s))
  (define res (make-vector (+ n 1) 0))
  (define (fill-d)
    (let loop ((i 0) (start 1))
      (when (< i n)
        (when (= (string-ref s i) #\D)
          (let ((j i))
            (let loop2 ()
              (when (and (< j n) (= (string-ref s j) #\D))
                (set! j (+ j 1)))
              (let ((end (+ j 1)))
                (let loop3 ((k end) (val start))
                  (when (>= k end)
                    (set! start (+ val 1)))
                  (vector-set! res k val)
                  (set! val (+ val 1))
                  (loop3 (- k 1) val))))))
        (loop (+ i 1) start))))
  (fill-d)
  (list->string (map (lambda (c) (integer->char (+ c 48))) (vector->list res))))