(define (product-of-array-except-self nums)
  (let* ((n (length nums))
         (result (make-vector n 1))
         (left 1)
         (right 1))
    (for ([i (in-range n)])
      (vector-set! result i left)
      (set! left (* left (vector-ref nums i))))
    (for ([i (in-range (- n 1) -1 -1)])
      (vector-set! result i (* (vector-ref result i) right))
      (set! right (* right (vector-ref nums i))))
    (vector->list result)))