(define (shifting-letters s shifts)
  (define n (string-length s))
  (define res (make-vector n #\a))
  (define shift (make-vector n 0))
  (for-each (lambda (i)
              (vector-set! shift i (modulo (apply + (take shifts i)) 26)))
            (range n))
  (for-each (lambda (i)
              (vector-set! res i (integer->char (+ (modulo (+ (char->integer (string-ref s i)) (vector-ref shift i)) 26) 97))))
            (range n))
  (list->string (vector->list res)))