(define (find-original-array a)
  (let ([n (length a)])
    (if (= n 0)
        '()
        (let ([res (make-vector n)])
          (vector-set! res 0 (vector-ref a 0))
          (for ([i (in-range 1 n)])
            (vector-set! res i (bitwise-xor (vector-ref res (- i 1)) (vector-ref a i))))
          (vector->list res)))))