(define (odd-string-diff words)
  (define (diff s)
    (for/list ([i (in-range 1 (string-length s))])
      (- (char->integer (string-ref s i)) (char->integer (string-ref s (sub1 i))))))
  (define (key w)
    (list->vector (diff w)))
  (define freq (make-hash))
  (for-each (lambda (w) (hash-update! freq (key w) add1 0)) words)
  (for/first ([w words] #:when (= 1 (hash-ref freq (key w))) #:unless (equal? w "")) w))