(define (can-cross stones)
  (define dp (make-hash))
  (for ([stone (in-list stones)])
    (hash-set! dp stone (set)))
  (for ([stone (in-list stones)])
    (for ([prev (in-set (hash-ref dp stone))])
      (for ([step (in-range 1 (add1 (abs (- stone prev))))])
        (when (hash-has-key? dp (+ stone step))
          (hash-set! dp (+ stone step) (set-add (hash-ref dp (+ stone step)) stone)))))
  (not (hash-empty? (hash-ref dp (last stones)))))