(define (longest-square-streak-in-an-array nums)
  (define num-set (list->set nums))
  (define (is-in-set x) (set-member? num-set x))
  (define (count-length x)
    (let loop ((current x) (count 0))
      (if (is-in-set current)
          (loop (* current current) (+ count 1))
          count)))
  (define max-length (apply max (map count-length nums)))
  (if (= max-length 1) -1 max-length))