#lang racket

(define/contract (similar-pairs words)
  (-> (listof string?) exact-integer?)
  (define (count-same s)
    (define sorted (sort (string->list s) char<?))
    (define key (list->string sorted))
    (hash-ref (make-hash) key 0))
  (define h (make-hash))
  (for-each (lambda (w)
              (define sorted (sort (string->list w) char<?))
              (define key (list->string sorted))
              (hash-set! h key (+ 1 (hash-ref h key 0))))
            words)
  (define total 0)
  (for ([(k v) (in-hash h)])
    (when (> v 1)
      (set! total (+ total (* v (- v 1))))))
  total)