(define (maximum-tastiness-candy-basket price)
  (define (check t)
    (let loop ([prev (car price)] [count 1])
      (if (>= count (length price))
          #t
          (let ([current (list-ref price count)])
            (if (<= (- current prev) t)
                (loop current count)
                (loop current (+ count 1)))))))
  (let ([sorted-price (sort price <)])
    (let loop ([low 0] [high (- (last sorted-price) (first sorted-price))])
      (if (> low high)
          (let ([mid (quotient (+ low high) 2)])
            (if (check mid)
                (loop (+ mid 1) high)
                (loop low (- mid 1))))
          (let ([mid (quotient (+ low high) 2)])
            (if (check mid)
                (loop (+ mid 1) high)
                (loop low (- mid 1))))))))