(define (max-subsequence-score nums1 nums2 k)
  (define n (length nums1))
  (define pairs (map (lambda (i) (list (list-ref nums1 i) (list-ref nums2 i))) (range n)))
  (define sorted-pairs (sort pairs (lambda (a b) (> (car a) (car b)))))
  (define top-k (take sorted-pairs k))
  (define sum1 (apply + (map car top-k)))
  (define sum2 (apply + (map cadr top-k)))
  (define (get-score i)
    (let ((sum1-i (+ sum1 (if (member (list-ref nums1 i) (map car top-k)) (- (list-ref nums1 i)) (list-ref nums1 i))))
          (sum2-i (+ sum2 (if (member (list-ref nums2 i) (map cadr top-k)) (- (list-ref nums2 i)) (list-ref nums2 i)))))
      (+ sum1-i sum2-i)))
  (apply max (map get-score (range n))))