(define (min-score-2 nums)
  (define (sort-list lst)
    (if (null? lst)
        '()
        (let ((min-val (apply min lst)))
          (cons min-val (sort-list (remove min-val lst))))))
  (define sorted (sort-list nums))
  (define len (length sorted))
  (if (< len 3)
      (apply - (take sorted 2))
      (min (- (list-ref sorted 2) (list-ref sorted 0))
           (- (list-ref sorted 1) (list-ref sorted 0))
           (- (list-ref sorted len 1) (list-ref sorted 1))
           (- (list-ref sorted len 1) (list-ref sorted 0)))))