(define (count-beautiful-subarrays nums)
  (define (count-subarrays-with-prefix prefix-map count)
    (if (null? nums)
        count
        (let* ((current (car nums))
               (new-count (bitwise-xor (car nums) (if (null? (cdr nums)) 0 (cadr nums))))
               (new-count (bitwise-xor new-count (if (null? (cddr nums)) 0 (caddr nums))))
               (new-count (bitwise-xor new-count (if (null? (cdddr nums)) 0 (cadddr nums))))
               (new-count (bitwise-xor new-count (if (null? (cddddr nums)) 0 (cadr (cddddr nums)))))
               (new-count (bitwise-xor new-count (if (null? (cdddddr nums)) 0 (cadr (cdddddr nums)))))
               (new-count (bitwise-xor new-count (if (null? (cddddddr nums)) 0 (cadr (cddddddr nums)))))
               (new-count (bitwise-xor new-count (if (null? (cdddddddr nums)) 0 (cadr (cdddddddr nums)))))
               (new-count (bitwise-xor new-count (if (null? (cddddddddd nums)) 0 (cadr (cddddddddd nums)))))
               (new-count (bitwise-xor new-count (if (null? (cddddddddd-r nums)) 0 (cadr (cddddddddd-r nums)))))
               (new-count (bitwise-xor new-count (if (null? (cddddddddd-rr nums)) 0 (cadr (cddddddddd-rr nums)))))
               (new-count (bitwise-xor new-count (if (null? (cddddddddd-rrr nums)) 0 (cadr (cddddddddd-rrr nums)))))
               (new-count (bitwise-xor new-count (if (null? (cddddddddd-rrrr nums)) 0 (cadr (cddddddddd-rrrr nums)))))
               (new-count (bitwise-xor new-count (if (null? (cddddddddd-rrrrr nums)) 0 (cadr (cddddddddd-rrrrr nums)))))
               (new-count (bitwise-xor new-count (if (null? (cddddddddd-rrrrrr nums)) 0 (cadr (cddddddddd-rrrrrr nums)))))
               (new-count (bitwise-xor new-count (if (null? (cddddddddd-rrrrrrr nums)) 0 (cadr (cddddddddd-rrrrrrr nums)))))
               (new-count (bitwise-xor new-count (if (null? (cddddddddd-rrrrrrrr nums)) 0 (cadr (cddddddddd-rrrrrrrr nums)))))
               (new-count (bitwise-xor new-count (if (null? (cddddddddd-rrrrrrrrr nums)) 0 (cadr (cddddddddd-rrrrrrrrr nums)))))
               (new-count (bitwise-xor new-count (if (null? (cddddddddd-rrrrrrrrrr nums)) 0 (cadr (cddddddddd-rrrrrrrrrr nums)))))
               (new-count (bitwise-xor new-count (if (null? (cddddddddd-rrrrrrrrrrr nums)) 0 (cadr (cddddddddd-rrrrrrrrrrr nums)))))
               (new-count (bitwise-xor new-count (if (null? (cddddddddd-rrrrrrrrrrrr nums)) 0 (cadr (cddddddddd-rrrrrrrrrrrr nums)))))
               (new-count (bitwise-xor new-count (if (null? (cddddddddd-rrrrrrrrrrrrr nums)) 0 (cadr (cddddddddd-rrrrrrrrrrrrr nums)))))
               (new-count (bitwise-xor new-count (if (null? (cddddddddd-rrrrrrrrrrrrrr nums)) 0 (cadr (cddddddddd-rrrrrrrrrrrrrr nums)))))
               (new-count (bitwise-xor new-count (if (null? (cddddddddd-rrrrrrrrrrrrrrr nums)) 0 (cadr (cddddddddd-rrrrrrrrrrrrrrr nums)))))
               (new-count (bitwise-xor new-count (if (null? (cddddddddd-rrrrrrrrrrrrrrrr nums)) 0 (cadr (cddddddddd-rrrrrrrrrrrrrrrr nums)))))
               (new-count (bitwise-xor new-count (if (null? (cddddddddd-rrrrrrrrrrrrrrrrr nums)) 0 (cadr (cddddddddd-rrrrrrrrrrrrrrrrr nums)))))
               (new-count (bitwise-xor new-count (if (null? (cddddddddd-rrrrrrrrrrrrrrrrrr nums)) 0 (cadr (cddddddddd-rrrrrrrrrrrrrrrrrr nums)))))
               (new-count (bitwise-xor new-count (if (null? (cddddddddd-rrrrrrrrrrrrrrrrrrr nums)) 0 (cadr (cddddddddd-rrrrrrrrrrrrrrrrrrr nums)))))
               (new-count (bitwise-xor new-count (if (null? (cddddddddd-rrrrrrrrrrrrrrrrrrrr nums)) 0 (cadr (cddddddddd-rrrrrrrrrrrrrrrrrrrr nums)))))
               (new-count (bitwise-xor new-count (if (null? (cddddddddd-rrrrrrrrrrrrrrrrrrrrr nums)) 0 (cadr (cddddddddd-rrrrrrrrrrrrrrrrrrrrr nums)))))
               (new-count (bitwise-xor new-count (if (null? (cddddddddd-rrrrrrrrrrrrrrrrrrrrrr nums)) 0 (cadr (cddddddddd-rrrrrrrrrrrrrrrrrrrrrr nums)))))
               (new-count (bitwise-xor new-count (if (null? (cddddddddd-rrrrrrrrrrrrrrrrrrrrrrr nums)) 0 (cadr (cddddddddd-rrrrrrrrrrrrrrrrrrrrrrr nums)))))
               (new-count (bitwise-xor new-count (if (null? (cddddddddd-rrrrrrrrrrrrrrrrrrrrrrrr nums)) 0 (cadr (cddddddddd-rrrrrrrrrrrrrrrrrrrrrrrr nums)))))
               (new-count (bitwise-xor new-count (if (null? (cddddddddd-rrrrrrrrrrrrrrrrrrrrrrrrr nums)) 0 (cadr (cddddddddd-rrrrrrrrrrrrrrrrrrrrrrrrr nums)))))
               (new-count (bitwise-xor new-count (if (null? (cddddddddd-rrrrrrrrrrrrrrrrrrrrrrrrrr nums)) 0 (cadr (cddddddddd-rrrrrrrrrrrrrrrrrrrrrrrrrr nums)))))
               (new-count (bitwise-xor new-count (if (null? (cddddddddd-rrrrrrrrrrrrrrrrrrrrrrrrrrr nums)) 0 (cadr (cddddddddd-rrrrrrrrrrrrrrrrrrrrrrrrrrr nums)))))
               (new-count (bitwise-xor new-count (if (null? (cddddddddd-rrrrrrrrrrrrrrrrrrrrrrrrrrrr nums)) 0 (cadr (cddddddddd-rrrrrrrrrrrrrrrrrrrrrrrrrrrr nums)))))
               (new-count (bitwise-xor new-count (if (null? (cddddddddd-rrrrrrrrrrrrrrrrrrrrrrrrrrrrr nums)) 0 (cadr (cddddddddd-rrrrrrrrrrrrrrrrrrrrrrrrrrrrr nums)))))
               (new-count (bitwise-xor new-count (if (null? (cddddddddd-rrrrrrrrrrrrrrrrrrrrrrrrrrrrrr nums)) 0 (cadr (cddddddddd-rrrrrrrrrrrrrrrrrrrrrrrrrrrrrr nums)))))
               (new-count (bitwise-xor new-count (if (null? (cddddddddd-rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr nums)) 0 (cadr (cddddddddd-rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr nums)))))
               (new-count (bitwise-xor new-count (if (null? (cddddddddd-rrrrrrrrrrrrrrrrrrrrrrrrrrrrrr