#lang racket

(define (distance-sum n)
  (define (sum-distances n)
    (define arr (range n))
    (define res (make-vector n 0))
    (define left (make-vector n 0))
    (define right (make-vector n 0))
    (define i 1)
    (define j (- n 2))
    (define l 1)
    (define r 1)
    (let loop ()
      (when (< i n)
        (vector-set! left i (+ (vector-ref left (- i 1)) (* i l)))
        (set! l (+ l 1))
        (set! i (+ i 1))
        (loop)))
    (let loop ()
      (when (>= j 0)
        (vector-set! right j (+ (vector-ref right (+ j 1)) (* (- n j -1) r)))
        (set! r (+ r 1))
        (set! j (- j 1))
        (loop)))
    (let loop ()
      (when (< (vector-length res) n)
        (vector-set! res (vector-length res) (+ (vector-ref left (vector-length res)) (vector-ref right (vector-length res))))
        (loop)))
    res)
  (sum-distances n))

(define (main)
  (define input (read))
  (define result (distance-sum input))
  (display (string-join (map number->string (vector->list result)) " ")))

(main)