(define (nth-ugly-number n)
  (define (merge a b)
    (cond ((null? a) b)
          ((null? b) a)
          ((< (car a) (car b)) (cons (car a) (merge (cdr a) b)))
          (else (cons (car b) (merge a (cdr b))))))
  (define (generate)
    (let loop ((ugly '(1)) (i 0))
      (if (= i n)
          (list-ref ugly (- n 1))
          (loop (merge (map (lambda (x) (* x 2)) ugly)
                       (merge (map (lambda (x) (* x 3)) ugly)
                              (map (lambda (x) (* x 5)) ugly)))
                (+ i 1)))))
  (generate))