#lang racket

(define (modify-graph-edge-weights n edges a b target)
  (define (dijkstra graph start end)
    (define dist (make-hash))
    (for ([i (in-range n)]) (hash-set! dist i +inf.0))
    (hash-set! dist start 0)
    (define pq (priority-queue '()))
    (priority-queue-add! pq (cons 0 start) #t)
    (let loop ()
      (when (not (priority-queue-empty? pq))
        (define-values (d u) (priority-queue-remove! pq))
        (when (= u end) (values d #f))
        (when (< d (hash-ref dist u))
          (for ([v (hash-ref graph u)])
            (define new-d (+ d v))
            (when (< new-d (hash-ref dist v))
              (hash-set! dist v new-d)
              (priority-queue-add! pq (cons new-d v) #t))))
        (loop)))
    (hash-ref dist end))
  (define graph (make-hash))
  (for ([i (in-range n)] [j (in-range n)]) (hash-set! graph i '()))
  (for ([e (in-list edges)])
    (define u (car e))
    (define v (cadr e))
    (define w (caddr e))
    (hash-set! graph u (append (hash-ref graph u) (list (cons v w))))
    (hash-set! graph v (append (hash-ref graph v) (list (cons u w)))))
  (define (get-dist x)
    (define (helper x)
      (if (equal? x '())
          0
          (apply + x)))
    (helper x))
  (define (update-edges)
    (for ([e (in-list edges)])
      (define u (car e))
      (define v (cadr e))
      (define w (caddr e))
      (when (and (not (= w a)) (not (= w b)))
        (set-car! (cddr e) a)
        (set-car! (cddr (reverse e)) b)))
    (void))
  (define (build-new-graph)
    (define new-graph (make-hash))
    (for ([i (in-range n)]) (hash-set! new-graph i '()))
    (for ([e (in-list edges)])
      (define u (car e))
      (define v (cadr e))
      (define w (caddr e))
      (hash-set! new-graph u (append (hash-ref new-graph u) (list w)))
      (hash-set! new-graph v (append (hash-ref new-graph v) (list w))))
    new-graph)
  (define new-graph (build-new-graph))
  (define d (dijkstra new-graph a b))
  (if (= d target)
      edges
      (begin
        (update-edges)
        edges)))