(define (max-strength nums)
  (let ((n (length nums)))
    (if (= n 1)
        (car nums)
        (let ((min1 0)
              (min2 0)
              (max1 0)
              (max2 0))
          (set! min1 (apply min nums))
          (set! max1 (apply max nums))
          (set! min2 (apply min (filter (lambda (x) (not (= x min1))) nums)))
          (set! max2 (apply max (filter (lambda (x) (not (= x max1))) nums)))
          (max (* min1 min2) (* max1 max2))))))