(define (minimum-cost s)
  (define n (string-length s))
  (define cnt (make-vector 26 0))
  (for-each (lambda (c) (vector-set! cnt (- (char->integer c) 97) (+ 1 (vector-ref cnt (- (char->integer c) 97))))) (string->list s))
  (define total (apply + (vector->list cnt)))
  (define mid (quotient total 2))
  (define res 0)
  (define i 0)
  (let loop ()
    (when (< i 26)
      (if (< (vector-ref cnt i) mid)
          (begin
            (set! res (+ res (* (- mid (vector-ref cnt i)) (abs (- i (char->integer #\a))))))
            (set! mid (- mid (vector-ref cnt i))))
          (begin
            (set! res (+ res (* (- (vector-ref cnt i) mid) (abs (- i (char->integer #\a))))))
            (set! mid 0)))
      (set! i (+ i 1))
      (loop)))
  res)