(define (min-possible-string words)
  (define (combine a b)
    (if (string=? (substring a (- (string-length a) 1)) (substring b 0 1))
        (string-append a b)
        (string-append a " " b)))
  (define (merge a b)
    (let ((ab (combine a b))
          (ba (combine b a)))
      (if (< (string-length ab) (string-length ba)) ab ba)))
  (define (fold-merge acc word)
    (merge acc word))
  (foldl fold-merge (car words) (cdr words)))