(define (number-of-beautiful-pairs nums)
  (define (gcd a b)
    (if (= b 0)
        a
        (gcd b (remainder a b))))
  (define (count-beautiful-pairs nums)
    (let ((n (length nums)))
      (for/fold ([count 0])
                ([i (in-range n)])
        (let ((a (list-ref nums i)))
          (for/fold ([count count])
                    ([j (in-range (+ i 1) n)])
            (let ((b (list-ref nums j)))
              (if (= (gcd a b) 1)
                  (+ count 1)
                  count)))))))
  (count-beautiful-pairs nums))