(define (h-index citations)
  (let loop ((left 0) (right (sub1 (length citations))))
    (if (> left right)
        (add1 left)
        (let* ((mid (quotient (+ left right) 2))
               (c (list-ref citations mid)))
          (if (>= c (- (length citations) mid))
              (loop left (sub1 mid))
              (loop (add1 mid) right))))))