(define (max-score nums k)
  (define n (length nums))
  (define-values (scores indices)
    (for/fold ([scores '()] [indices '()])
              ([i (in-range n)])
      (values (cons (* (list-ref nums i) (+ 1 (- n i))) scores)
              (cons i indices))))
  (define sorted (sort (map list scores indices) > #:key first))
  (define visited (make-vector n #f))
  (define res 0)
  (for ([i (in-range k)])
    (define idx (second (list-ref sorted i)))
    (vector-set! visited idx #t)
    (set! res (+ res (list-ref nums idx))))
  res)