#lang racket

(define (count-complete-subarrays nums)
  (define (count-subarrays-with-each-element-at-least-once)
    (define unique (set->list (apply set nums)))
    (define n (length nums))
    (define target-size (length unique))
    (define freq (make-hash))
    (define left 0)
    (define count 0)
    (for ([right (in-range n)])
      (hash-set! freq (list-ref nums right) (+ (hash-ref freq (list-ref nums right) 0) 1))
      (while (and (>= (hash-count freq) target-size) (< left right))
        (hash-set! freq (list-ref nums left) (- (hash-ref freq (list-ref nums left)) 1))
        (when (= (hash-ref freq (list-ref nums left) 0) 0)
          (hash-remove! freq (list-ref nums left)))
        (set! left (+ left 1)))
      (when (>= (hash-count freq) target-size)
        (set! count (+ count (- right left 1)))))
    count)
  (count-subarrays-with-each-element-at-least-once))