(define (max-sum-of-almost-unique-subarray nums k)
  (define n (length nums))
  (define freq (make-hash))
  (define sum (make-hash))
  (define (add-to-freq x)
    (hash-set! freq x (+ (hash-ref freq x 0) 1)))
  (define (remove-from-freq x)
    (hash-set! freq x (- (hash-ref freq x 0) 1))
    (when (= (hash-ref freq x 0) 0)
      (hash-remove! freq x)))
  (let loop ((i 0) (current-sum 0) (max-sum 0))
    (if (>= i n)
        max-sum
        (begin
          (when (and (>= i k) (> (hash-count freq) 1))
            (remove-from-freq (list-ref nums (- i k)))
            (set! current-sum (- current-sum (list-ref nums (- i k)))))
          (add-to-freq (list-ref nums i))
          (set! current-sum (+ current-sum (list-ref nums i)))
          (if (and (>= i (- k 1)) (= (hash-count freq) 1))
              (loop (+ i 1) current-sum (max max-sum current-sum))
              (loop (+ i 1) current-sum max-sum))))))