(define (minimum-moves grid)
  (define (manhattan a b)
    (+ (abs (- (car a) (car b))) (abs (- (cadr a) (cadr b)))))
  (define (coords n)
    (let loop ((i 0) (j 0) (res '()))
      (if (= n 0)
          res
          (if (= j (length grid))
              (loop (+ i 1) 0 res)
              (loop i (+ j 1) (cons (list i j) res))))))
  (define (count-ones)
    (let loop ((i 0) (j 0) (res '()))
      (if (= i (length grid))
          res
          (if (= j (length (list-ref grid 0)))
              (loop (+ i 1) 0 res)
              (loop i (+ j 1) (if (= (list-ref (list-ref grid i) j) 1)
                                  (cons (list i j) res)
                                  res))))))
  (let* ((ones (count-ones))
         (n (length ones))
         (coords (coords n)))
    (apply + (map (lambda (a b) (manhattan a b)) ones coords))))