(define (str-transformation s t)
  (define (char->index c)
    (- (char->integer c) (char->integer #\a)))
  (define (index->char i)
    (integer->char (+ i (char->integer #\a))))
  (define (transform c)
    (let ([i (char->index c)])
      (if (< i 13)
          (index->char (+ i 13))
          (index->char (- i 13)))))
  (list->string (map transform (string->list s))))