(define (last-visited-integers words)
  (define (helper words res)
    (if (null? words)
        (reverse res)
        (let loop ((lst (car words)) (temp '()))
          (if (null? lst)
              (helper (cdr words) (cons (reverse temp) res))
              (if (number? (car lst))
                  (loop (cdr lst) (cons (car lst) temp))
                  (loop (cdr lst) temp))))))
  (helper words '()))