#lang racket

(define/contract (construct-product-matrix (grid)
  (-> (listof (listof exact-integer?)) (listof (listof exact-integer?)))
  (define n (length grid))
  (define m (length (car grid)))
  (define total (* n m))
  (define nums (apply append grid))
  (define left (make-vector total 1))
  (define right (make-vector total 1))
  (for ([i (in-range 1 total)])
    (vector-set! left i (* (vector-ref left (- i 1)) (vector-ref nums (- i 1)))))
  (for ([i (in-range (- total 2) -1 -1)])
    (vector-set! right i (* (vector-ref right (+ i 1)) (vector-ref nums (+ i 1)))))
  (define res (make-vector total 1))
  (for ([i (in-range total)])
    (vector-set! res i (* (vector-ref left i) (vector-ref right i))))
  (define result (build-list n (lambda (i) (build-list m (lambda (j) (vector-ref res (+ (* i m) j)))))))
  result)