(define (min-changes s)
  (define (count-ones s)
    (for/sum ([c s]) (if (char=? c #\1) 1 0)))
  (define n (string-length s))
  (define half (quotient n 2))
  (define (get-changes i)
    (if (= (modulo i 2) 0)
        (if (char=? (string-ref s i) #\1) 1 0)
        (if (char=? (string-ref s i) #\0) 1 0)))
  (apply + (map get-changes (range 0 half))))