(define (min-increment-operations-to-make-array-beautiful nums k)
  (define n (length nums))
  (define dp (make-vector n 0))
  (vector-set! dp 0 (if (= (modulo (vector-ref nums 0) k) 0) 0 (- k (modulo (vector-ref nums 0) k))))
  (for ([i (in-range 1 n)])
    (vector-set! dp i (+ (vector-ref dp (- i 1)) (if (= (modulo (vector-ref nums i) k) 0) 0 (- k (modulo (vector-ref nums i) k)))))
    (when (> i 1)
      (vector-set! dp i (min (vector-ref dp i) (+ (vector-ref dp (- i 2)) (if (= (modulo (vector-ref nums i) k) 0) 0 (- k (modulo (vector-ref nums i) k))))))))
  (vector-ref dp (- n 1)))