#lang racket

(define (min-array nums k)
  (define n (length nums))
  (define arr (list->vector nums))
  (define (swap i j)
    (let ((temp (vector-ref arr i)))
      (vector-set! arr i (vector-ref arr j))
      (vector-set! arr j temp)))
  (define (find-min-index start end)
    (let loop ((i start) (min-i start))
      (if (> i end)
          min-i
          (if (< (vector-ref arr i) (vector-ref arr min-i))
              (loop (+ i 1) i)
              (loop (+ i 1) min-i)))))
  (let loop ((i 0) (k k))
    (when (< i n)
      (let ((min-i (find-min-index i (min (+ i k) (- n 1)))))
        (when (/= min-i i)
          (let ((swap-count (- min-i i)))
            (for ((j (in-range min-i i -1)))
              (swap j (- j 1)))
            (set! k (- k swap-count))))
        (loop (+ i 1) k))))
  (vector->list arr))