(define (max-area-of-longest-diagonal-rectangle rectangles)
  (define (distance x1 y1 x2 y2)
    (sqrt (+ (expt (- x2 x1) 2) (expt (- y2 y1) 2))))
  (define (key r)
    (let ([x1 (car r)] [y1 (cadr r)] [x2 (caddr r)] [y2 (cadddr r)])
      (distance x1 y1 x2 y2)))
  (define (area r)
    (let ([x1 (car r)] [y1 (cadr r)] [x2 (caddr r)] [y2 (cadddr r)])
      (* (- x2 x1) (- y2 y1))))
  (define sorted (sort rectangles (lambda (a b) (> (key a) (key b)))))
  (define max-diag (key (car sorted)))
  (define candidates (filter (lambda (r) (= (key r) max-diag)) sorted))
  (apply max (map area candidates)))