(define (split-array nums k)
  (define n (length nums))
  (define dp (make-vector n #inf.0))
  (vector-set! dp 0 0)
  (for ([i (in-range 1 n)])
    (for ([j (in-range 0 i)])
      (when (<= (- i j) k)
        (define cost (apply max (take nums j i)))
        (when (< (+ (vector-ref dp j) cost) (vector-ref dp i))
          (vector-set! dp i (+ (vector-ref dp j) cost))))))
  (vector-ref dp (sub1 n)))