(define (maximum-good-subarray-sum nums)
  (define n (length nums))
  (define dp (make-vector n 0))
  (vector-set! dp 0 (if (= (vector-ref nums 0) 1) 1 0))
  (define max-sum (vector-ref dp 0))
  (for ([i (in-range 1 n)])
    (if (= (vector-ref nums i) 1)
        (vector-set! dp i (+ (vector-ref dp (- i 1)) 1))
        (vector-set! dp i 0))
    (set! max-sum (max max-sum (vector-ref dp i))))
  max-sum)