#lang racket

(define (minimum-time-to-revert-word-to-initial-state s k)
  (define n (string-length s))
  (define (get-lps pattern)
    (define m (string-length pattern))
    (define lps (make-vector m 0))
    (define len 0)
    (for ([i (in-range 1 m)])
      (when (and (= (string-ref pattern len) (string-ref pattern i)) (not (= len -1)))
        (vector-set! lps i (add1 len))
        (set! len (add1 len)))
      (when (or (= len -1) (not (= (string-ref pattern len) (string-ref pattern i))))
        (set! len (vector-ref lps (sub1 len)))))
    lps)
  (define lps (get-lps s))
  (define (check-prefix? s1 s2)
    (and (= (string-length s1) (string-length s2))
         (equal? s1 s2)))
  (define (can-revert? s1 s2)
    (and (>= (string-length s1) k)
         (check-prefix? s1 (substring s2 0 (min k (string-length s2))))))
  (define (find-min-steps)
    (let loop ([steps 0] [current s])
      (if (check-prefix? current s)
          steps
          (loop (add1 steps) (substring current k)))))
  (find-min-steps))