(define (longest-repeating-char-replacement s k)
  (define (max-consecutive-elements s k)
    (define (helper left right max-count)
      (if (>= right (string-length s))
          (- (string-length s) left)
          (let* ((current-char (string-ref s right))
                 (count (hash-ref (make-hash) current-char 0))
                 (new-count (+ count 1))
                 (new-max-count (max max-count new-count)))
            (if (<= (- right left) (+ k new-max-count))
                (helper left (+ right 1) new-max-count)
                (helper (+ left 1) right max-count)))))
    (helper 0 0 0))
  (max-consecutive-elements s k))