(define (min-operations-to-make-median-of-array-equal-to-k nums k)
  (define sorted-nums (sort nums <))
  (define n (length nums))
  (define mid (quotient n 2))
  (if (<= (list-ref sorted-nums mid) k)
      (for/sum ([i (in-range mid n)])
        (- (list-ref sorted-nums i) k))
      (for/sum ([i (in-range 0 (add1 mid))])
        (- k (list-ref sorted-nums i)))))