(define (count-days-without-meetings days)
  (define (merge-intervals intervals)
    (if (null? intervals)
        '()
        (let* ((sorted (sort intervals (lambda (a b) (< (car a) (car b)))))
               (first (car sorted))
               (rest (cdr sorted)))
          (let loop ((current first) (remaining rest) (result '()))
            (if (null? remaining)
                (cons current result)
                (let ((next (car remaining)))
                  (if (<= (cadr current) (car next))
                      (loop (list (car current) (max (cadr current) (cadr next))) (cdr remaining) result)
                      (loop next (cdr remaining) (cons current result))))))))
  (define (intervals-to-days intervals)
    (apply + (map (lambda (i) (- (cadr i) (car i))) intervals)))
  (let ((merged (merge-intervals days)))
    (- 365 (intervals-to-days merged))))