(define (max-product words)
  (define (bitmask word)
    (let loop ([i 0] [mask 0])
      (if (= i (string-length word))
          mask
          (loop (+ i 1) (bitwise-ior mask (arithmetic-shift 1 (- (char->integer (string-ref word i)) 97)))))))
  (define masks (map bitmask words))
  (define n (length words))
  (define max-prod 0)
  (for ([i (in-range n)])
    (for ([j (in-range i n)])
      (when (zero? (bitwise-and (list-ref masks i) (list-ref masks j)))
        (set! max-prod (max max-prod (* (string-length (list-ref words i)) (string-length (list-ref words j)))))))
  max-prod)