#lang racket

(define (count-submatrices)
  (let* ([n (string->number (read-line))]
         [grid (for/list ([i n])
                 (map (lambda (c) (if (char=? c #\X) 1 (if (char=? c #\Y) -1 0)))
                      (string->list (read-line))))])
    (define (count-rectangles)
      (define rows (length grid))
      (define cols (length (car grid)))
      (define prefix (make-vector rows (make-vector cols 0)))
      (for ([i rows])
        (vector-set! (vector-ref prefix i) 0 (vector-ref (vector-ref grid i) 0))
        (for ([j (in-range 1 cols)])
          (vector-set! (vector-ref prefix i) j (+ (vector-ref (vector-ref grid i) j) (vector-ref (vector-ref prefix i) (- j 1))))))
      (define count 0)
      (for ([i rows])
        (for ([j cols])
          (define sum (vector-ref (vector-ref prefix i) j))
          (when (= sum 0)
            (set! count (+ count 1)))
          (for ([k (in-range i (- rows 1))])
            (define current-sum 0)
            (for ([l (in-range j cols)])
              (set! current-sum (+ current-sum (vector-ref (vector-ref grid (+ k 1)) l)))
              (when (= current-sum 0)
                (set! count (+ count 1))))))
      count)
    (count-rectangles)))