(define (lexicographically-smallest-string-after-a-swap s)
  (define len (string-length s))
  (define lst (string->list s))
  (for/fold ([res lst]) ([i (in-range len)])
    (for/fold ([current res]) ([j (in-range (add1 i) len)])
      (when (char<? (list-ref res j) (list-ref res i))
        (define new-res (copy-list res))
        (define temp (list-ref new-res i))
        (set! (list-ref new-res i) (list-ref new-res j))
        (set! (list-ref new-res j) temp)
        (set! current new-res)
        (break))
      current))
  (list->string res))