(define (non-special-numbers low high)
  (define (is-special? n)
    (let loop ((i 2) (count 0))
      (cond ((> i (sqrt n)) (= count 1))
            ((= (modulo n i) 0)
             (if (= i (quotient n i))
                 (loop (+ i 1) (+ count 1))
                 (loop (+ i 1) (+ count 2))))
            (else (loop (+ i 1) count)))))
  (- high low 1 (for/sum ((i (in-range (add1 low) (add1 high)))
                          #:when (is-special? i)) 1))