(define (number-of-substrings s)
  (define len (string-length s))
  (define count-1 (make-vector len 0))
  (define cnt 0)
  (define pos -1)
  (for ([i (in-range len)])
    (when (= (string-ref s i) #\1)
      (set! pos i)
      (vector-set! count-1 i 1)
      (when (> i 0)
        (vector-set! count-1 i (+ (vector-ref count-1 (- i 1)) 1)))))
  (for ([i (in-range len)])
    (when (and (>= (vector-ref count-1 i) 1) (<= (vector-ref count-1 i) len))
      (let ([k (vector-ref count-1 i)])
        (set! cnt (+ cnt (- len k 1))))))
  cnt)