(define (min-flips grid)
  (define (is-palindrome? row)
    (equal? row (reverse row)))
  (define (count-flips row)
    (define (helper i j)
      (if (>= i j)
          0
          (+ (if (= (list-ref row i) (list-ref row j)) 0 1)
             (helper (+ i 1) (- j 1)))))
    (helper 0 (- (length row) 1)))
  (define rows (map (lambda (r) (string->list r)) grid))
  (define cols (apply map list rows))
  (define (process-row row)
    (count-flips row))
  (define (process-col col)
    (count-flips col))
  (define row-flips (for/sum ([row rows]) (process-row row)))
  (define col-flips (for/sum ([col cols]) (process-col col)))
  (min row-flips col-flips))