(define (wiggle-sort nums)
  (let ((n (length nums)))
    (define (swap i j)
      (let ((temp (list-ref nums i)))
        (set! nums (list-set nums i (list-ref nums j)))
        (set! nums (list-set nums j temp))))
    (define (partition low high)
      (let ((pivot (list-ref nums high)))
        (let loop ((i low) (j low))
          (if (> j high)
              (- i 1)
              (if (<= (list-ref nums j) pivot)
                  (begin
                    (swap i j)
                    (loop (+ i 1) (+ j 1)))
                  (loop i (+ j 1))))))
    (define (quick-select k)
      (let loop ((low 0) (high (- n 1)))
        (let ((p (partition low high)))
          (cond ((= p k) nums)
                ((< p k) (loop (+ p 1) high))
                (else (loop low (- p 1))))))
    (quick-select (quotient n 2))
    (define (compare a b)
      (if (even? (car a)) (< (cadr a) (cadr b)) (> (cadr a) (cadr b))))
    (define sorted (sort (map (lambda (x) (cons x (index-of nums x))) nums) compare))
    (define result (make-list n 0))
    (let loop ((i 0) (j 0) (k 1))
      (when (< i n)
        (vector-set! result j (caar sorted))
        (vector-set! result k (cadar sorted))
        (loop (+ i 1) (+ j 2) (+ k 2))))
    (vector->list result)))