#lang racket

(define (maximize-score nums ranges)
  (define n (length nums))
  (define events (for/fold ([evts '()]) ([i (in-range n)])
                   (append evts (list (cons (car ranges) i)) (list (cons (+ (car ranges) 1) (- i 1))))))
  (set! events (sort events (lambda (a b) (< (car a) (car b)))))
  (define res (make-vector n 0))
  (define curr 0)
  (define idx 0)
  (define last -1)
  (for ([e (in-list events)])
    (define pos (car e))
    (define val (cdr e))
    (when (not (= pos last))
      (vector-set! res idx curr)
      (set! idx (add1 idx)))
    (set! curr (if (> val 0) (add1 curr) (sub1 curr)))
    (set! last pos))
  (apply + (for/list ([i (in-range n)]) (* (vector-ref res i) (list-ref nums i)))))