(define (two-sneaky-numbers nums)
  (let ((freq (make-hash)))
    (for-each (lambda (n)
                (hash-set! freq n (+ (hash-ref freq n 0) 1)))
              nums)
    (let loop ((i 1))
      (if (> i 9)
          '()
          (let ((count (hash-ref freq i 0)))
            (if (= count 2)
                (cons i (loop (+ i 1)))
                (loop (+ i 1))))))))