#lang racket

(define (is-vowel? c)
  (member c '(#\a #\e #\i #\o #\u)))

(define (count-substrings s k)
  (define len (string-length s))
  (define vowels '(#\a #\e #\i #\o #\u))
  (define consonants (filter (lambda (c) (not (is-vowel? c))) (string->list s)))
  (define vowel-count (make-hash))
  (for-each (lambda (v) (hash-set! vowel-count v 0)) vowels)
  (define (get-vowel-count)
    (for/sum ([v vowels]) (hash-ref vowel-count v)))
  (define (add-char c)
    (when (is-vowel? c)
      (hash-set! vowel-count c (+ 1 (hash-ref vowel-count c)))))
  (define (remove-char c)
    (when (is-vowel? c)
      (hash-set! vowel-count c (- (hash-ref vowel-count c) 1))))
  (define result 0)
  (define left 0)
  (define right 0)
  (define consonant-count 0)
  (define (check-consonant c)
    (when (not (is-vowel? c))
      (set! consonant-count (+ consonant-count 1))))
  (define (remove-consonant c)
    (when (not (is-vowel? c))
      (set! consonant-count (- consonant-count 1))))
  (for ([right (in-range len)])
    (add-char (string-ref s right))
    (check-consonant (string-ref s right))
    (while (and (>= consonant-count k) (<= left right))
      (when (= (get-vowel-count) 5)
        (set! result (+ result 1)))
      (remove-char (string-ref s left))
      (remove-consonant (string-ref s left))
      (set! left (+ left 1))))
  result)