#lang racket

(define (construct2DGrid grid)
  (define (build-adjacency-list)
    (define rows (length grid))
    (define cols (if (null? grid) 0 (length (car grid))))
    (define adj (make-hash))
    (for ([i (in-range rows)])
      (for ([j (in-range cols)])
        (define node (string-append (number->string i) "," (number->string j)))
        (hash-set! adj node '())
        (when (< j (- cols 1))
          (define right-node (string-append (number->string i) "," (number->string (+ j 1))))
          (hash-update! adj node (lambda (lst) (append lst (list right-node))))
          (hash-update! adj right-node (lambda (lst) (append lst (list node)))))
        (when (< i (- rows 1))
          (define down-node (string-append (number->string (+ i 1)) "," (number->string j)))
          (hash-update! adj node (lambda (lst) (append lst (list down-node))))
          (hash-update! adj down-node (lambda (lst) (append lst (list node))))))
    adj)
  (build-adjacency-list))