(define (k-long-subarrays-sums nums k)
  (define n (length nums))
  (define result '())
  (for ([i (in-range (- n k +1))])
    (define sub (take (drop nums i) k))
    (define sum (apply + sub))
    (set! result (cons sum result)))
  (reverse result))

(define (k-long-subarrays-x-sums nums k x)
  (define sums (k-long-subarrays-sums nums k))
  (define n (length sums))
  (define result '())
  (for ([i (in-range n)])
    (define current (list-ref sums i))
    (define total (if (>= current x) (+ current x) current))
    (set! result (cons total result)))
  (reverse result))

(define (find-x-sum-of-all-k-long-subarrays-i nums k x)
  (k-long-subarrays-x-sums nums k x))