(define (find-x-sum nums k x)
  (define n (length nums))
  (define result '())
  (define (sum-subarray i)
    (let loop ((j 0) (s 0))
      (if (= j k)
          s
          (loop (+ j 1) (+ s (list-ref nums (+ i j)))))))
  (define (process i)
    (when (< i (- n k))
      (let ((current-sum (sum-subarray i)))
        (set! result (append result (list current-sum)))
        (process (+ i 1)))))
  (process 0)
  (define sorted-result (sort result >))
  (apply + (take sorted-result x)))