(define (sub-strings-with-k-frequency-characters s k)
  (define n (string-length s))
  (define (count-k-freq? s k)
    (define freq (make-hash))
    (for ([c s])
      (hash-set! freq c (+ (hash-ref freq c 0) 1)))
    (for/and ([v (in-hash-values freq)])
      (= v k)))
  (define result 0)
  (for ([i (in-range n)])
    (for ([j (in-range i n)])
      (when (count-k-freq? (substring s i (add1 j)) k)
        (set! result (+ result 1)))))
  result)