(define (find-original-string s)
  (define (helper i res)
    (if (>= i (string-length s))
        (list->string (reverse res))
        (let ([c (string-ref s i)])
          (if (char=? c #\#)
              (helper (+ i 2) res)
              (helper (+ i 1) (cons c res))))))
  (helper 0 '()))