#lang racket

(define (max-subarray-sum nums k)
  (define n (length nums))
  (define prefix (make-vector (+ n 1) 0))
  (for ([i (in-range n)])
    (vector-set! prefix (+ i 1) (+ (vector-ref prefix i) (list-ref nums i))))
  (define dp (make-vector (+ n 1) -inf.0))
  (vector-set! dp 0 0)
  (define res -inf.0)
  (for ([i (in-range 1 (+ n 1))])
    (for ([j (in-range 0 i)])
      (when (= (modulo (- i j) k) 0)
        (vector-set! dp i (max (vector-ref dp i) (+ (vector-ref dp j) (- (vector-ref prefix i) (vector-ref prefix j))))))
      (when (and (>= i k) (= (modulo i k) 0))
        (set! res (max res (vector-ref dp i)))))
    (when (and (>= i k) (= (modulo i k) 0))
      (set! res (max res (vector-ref dp i)))))
  res)