#lang racket

(define (valid-email? s)
  (define (is-valid-char c)
    (or (char-alphabetic? c) (char-numeric? c) (char=? c #\_) (char=? c #\.) (char=? c #\-)))
  (define (split-at-last-dot s)
    (let ((idx (string-last-index-of s #\.)))
      (if (= idx -1) (values s "") (values (substring s 0 idx) (substring s (add1 idx))))))
  (define (is-domain-valid domain)
    (and (not (string=? domain ""))
         (let ((parts (string-split domain #\.)))
           (andmap (lambda (p) (and (not (string=? p ""))
                                   (char-alphabetic? (string-ref p 0))
                                   (for/and ([c (in-string p)])
                                     (is-valid-char c)))))))
  (define (is-local-part-valid local)
    (and (not (string=? local ""))
         (for/and ([c (in-string local)])
           (is-valid-char c))))
  (let* ((parts (string-split s #\@))
         (local (car parts))
         (domain (cadr parts)))
    (and (= (length parts) 2)
         (is-local-part-valid local)
         (is-domain-valid domain))))

(define (find-valid-emails emails)
  (filter valid-email? emails))