(define (lexicographically-smallest-string s)
  (define (helper lst)
    (cond ((null? lst) '())
          ((equal? (car lst) #\a)
           (cons #\a (helper (cdr lst))))
          ((equal? (car lst) #\b)
           (cons #\b (helper (cdr lst))))
          (else
           (let ((next (car lst)))
             (if (and (not (null? (cdr lst)))
                      (or (equal? (cadr lst) #\a)
                          (equal? (cadr lst) #\b)))
                 (cons next (helper (cdr lst)))
                 (cons next (helper (cdr lst))))))))
  (list->string (helper (string->list s))))