#lang racket

(define (num-islands grid)
  (define rows (length grid))
  (define cols (if (> rows 0) (length (car grid)) 0))
  (define visited (make-hash))
  (define (in-bound? r c)
    (and (>= r 0) (< r rows) (>= c 0) (< c cols)))
  (define (dfs r c)
    (when (and (in-bound? r c) (equal? (list-ref (list-ref grid r) c) "1") (not (hash-has-key? visited (cons r c))))
      (hash-set! visited (cons r c) #t)
      (for-each dfs (list (sub1 r) (add1 r) r r) (list c c (sub1 c) (add1 c)))))
  (define count 0)
  (for ([r (in-range rows)])
    (for ([c (in-range cols)])
      (when (and (equal? (list-ref (list-ref grid r) c) "1") (not (hash-has-key? visited (cons r c))))
        (set! count (add1 count))
        (dfs r c))))
  count)