(define (intersect nums1 nums2)
  (define count (lambda (lst)
                  (let ([ht (make-hash)])
                    (for-each (lambda (x) (hash-set! ht x (+ (hash-ref ht x 0) 1))) lst)
                    ht)))
  (define h1 (count nums1))
  (define h2 (count nums2))
  (define result '())
  (for ([k (in-hash-keys h1)])
    (when (hash-has-key? h2 k)
      (let ([min-count (min (hash-ref h1 k) (hash-ref h2 k))])
        (set! result (append result (make-list min-count k))))))
  result)