(define (count-triplets nums)
  (define n (length nums))
  (define result 0)
  (for ([i (in-range n)])
    (for ([j (in-range i n)])
      (for ([k (in-range j n)])
        (when (not (= (bitwise-xor (list-ref nums i) (list-ref nums j) (list-ref nums k)) 
                      (bitwise-xor (list-ref nums i) (list-ref nums k) (list-ref nums j))))
          (set! result (+ result 1))))))
  result)