#lang racket

(define/contract (min-operations nums)
  (-> (listof exact-integer?) exact-integer?)
  (define (count-ones n)
    (let loop ([n n] [count 0])
      (if (= n 0)
          count
          (loop (quotient n 2) (+ count (modulo n 2))))))
  (define (xor a b)
    (bitwise-xor a b))
  (define (add a b)
    (+ a b))
  (define (subtract a b)
    (- a b))
  (define (multiply a b)
    (* a b))
  (define (divide a b)
    (/ a b))
  (define (mod a b)
    (remainder a b))
  (define (and a b)
    (bitwise-and a b))
  (define (or a b)
    (bitwise-ior a b))
  (define (not a)
    (bitwise-not a))
  (define (shift-left a b)
    (arithmetic-shift a b))
  (define (shift-right a b)
    (arithmetic-shift a (- b)))
  (define (equal a b)
    (= a b))
  (define (not-equal a b)
    (not (= a b)))
  (define (greater a b)
    (> a b))
  (define (less a b)
    (< a b))
  (define (greater-equal a b)
    (>= a b))
  (define (less-equal a b)
    (<= a b))
  (define (if-then-else cond then else)
    (if cond then else))
  (define (for-each f lst)
    (for-each f lst))
  (define (map f lst)
    (map f lst))
  (define (foldl f init lst)
    (foldl f init lst))
  (define (foldr f init lst)
    (foldr f init lst))
  (define (filter f lst)
    (filter f lst))
  (define (reverse lst)
    (reverse lst))
  (define (length lst)
    (length lst))
  (define (append lst1 lst2)
    (append lst1 lst2))
  (define (cons a lst)
    (cons a lst))
  (define (car lst)
    (car lst))
  (define (cdr lst)
    (cdr lst))
  (define (null? lst)
    (null? lst))
  (define (list-ref lst i)
    (list-ref lst i))
  (define (list-set lst i val)
    (list-set lst i val))
  (define (make-list n val)
    (make-list n val))
  (define (vector-length vec)
    (vector-length vec))
  (define (vector-ref vec i)
    (vector-ref vec i))
  (define (vector-set! vec i val)
    (vector-set! vec i val))
  (define (vector->list vec)
    (vector->list vec))
  (define (list->vector lst)
    (list->vector lst))
  (define (current-seconds)
    (current-seconds))
  (define (random)
    (random))
  (define (error msg)
    (error msg))
  (define (display msg)
    (display msg))
  (define (newline)
    (newline))
  (define (read)
    (read))
  (define (read-line)
    (read-line))
  (define (open-input-string str)
    (open-input-string str))
  (define (read-char)
    (read-char))
  (define (close-input-port port)
    (close-input-port port))
  (define (string-length str)
    (string-length str))
  (define (string-ref str i)
    (string-ref str i))
  (define (string-set! str i c)
    (string-set! str i c))
  (define (substring str start end)
    (substring str start end))
  (define (string-append str1 str2)
    (string-append str1 str2))
  (define (number->string num)
    (number->string num))
  (define (string->number str)
    (string->number str))
  (define (char=? c1 c2)
    (char=? c1 c2))
  (define (char->integer c)
    (char->integer c))
  (define (integer->char i)
    (integer->char i))
  (define (symbol=? s1 s2)
    (eqv? s1 s2))
  (define (symbol->string s)
    (symbol->string s))
  (define (string->symbol s)
    (string->symbol s))
  (define (eqv? a b)
    (eqv? a b))
  (define (equal? a b)
    (equal? a b))
  (define (eq? a b)
    (eq? a b))
  (define (procedure? p)
    (procedure? p))
  (define (apply proc args)
    (apply proc args))
  (define (lambda args body)
    (lambda args body))
  (define (begin . args)
    (begin . args))
  (define (set! var val)
    (set! var val))
  (define (quote x)
    (quote x))
  (define (quasiquote x)
    (quasiquote x))
  (define (unquote x)
    (unquote x))
  (define (unquote-splicing x)
    (unquote-splicing x))
  (define (case key clauses)
    (case key clauses))
  (define (cond . clauses)
    (cond . clauses))
  (define (and . args)
    (and . args))
  (define (or . args)
    (or . args))
  (define (when test . body)
    (when test . body))
  (define (unless test . body)
    (unless test . body))
  (define (let vars vals body)
    (let vars vals body))
  (define (let* vars vals body)
    (let* vars vals body))
  (define (letrec vars vals body)
    (letrec vars vals body))
  (define (let-values vars vals body)
    (let-values vars vals body))
  (define (let*-values vars vals body)
    (let*-values vars vals body))
  (define (letrec-values vars vals body)
    (letrec-values vars vals body))
  (define (let/cc k body)
    (let/cc k body))
  (define (dynamic-wind before thunk after)
    (dynamic-wind before thunk after))
  (define (call-with-current-continuation proc)
    (call-with-current-continuation proc))
  (define (call-with-values producer consumer)
    (call-with-values producer consumer))
  (define (values . args)
    (values . args))
  (define (void)
    (void))
  (define (void? x)
    (void? x))
  (define (eof-object?)
    (eof-object?))
  (define (current-output-port)
    (current-output-port))
  (define (current-input-port)
    (current-input-port))
  (define (flush-output)
    (flush-output))
  (define (get-output-string)
    (get-output-string))
  (define (get-output-bytes)
    (get-output-bytes))
  (define (open-output-string)
    (open-output-string))
  (define (open-input-string str)
    (open-input-string str))
  (define (open-output-file filename)
    (open-output-file filename))
  (define (open-input-file filename)
    (open-input-file filename))
  (define (close-output-port port)
    (close-output-port port))
  (define (close-input-port port)
    (close-input-port port))
  (define (file-exists? filename)
    (file-exists? filename))
  (define (delete-file filename)
    (delete-file filename))
  (define (rename-file old new)
    (rename-file old new))
  (define (file-or-directory-modify-seconds path)
    (file-or-directory-modify-seconds path))
  (define (file-size path)
    (file-size path))
  (define (directory-list path)
    (directory-list path))
  (define (make-directory path)
    (make-directory path))
  (define (delete-directory path)
    (delete-directory path))
  (define (file-name? path)
    (file-name? path))
  (define (directory-name? path)
    (directory-name? path))
  (define (path? path)
    (path? path))
  (define (build-path . parts)
    (build-path . parts))
  (define (path->string path)
    (path->string path))
  (define (string->path str)
    (string->path str))
  (define (current-directory)
    (current-directory))
  (define (set-current-directory! path)
    (set-current-directory! path))
  (define (system command)
    (system command))
  (define (exit)
    (exit))
  (define (exit-code code)
    (exit code))
  (define (sleep seconds)
    (sleep seconds))
  (define (thread-start! thread)
    (thread-start! thread))
  (define (thread? obj