(define (min-deletions s k)
  (define freq (make-hash))
  (for ([c s])
    (hash-set! freq c (+ 1 (hash-ref freq c 0))))
  (define counts (sort (hash-values freq) >))
  (define total 0)
  (for ([count counts])
    (when (> count k)
      (set! total (+ total (- count k)))
      (set! k (- k 1))))
  total)