(define (minimum-swaps nums)
  (define n (length nums))
  (define sorted (sort nums <))
  (define pos (make-hash))
  (for ([i (in-range n)]
        [num (in-list nums)])
    (hash-set! pos num i))
  (define visited (make-vector n #f))
  (define swaps 0)
  (for ([i (in-range n)])
    (when (not (vector-ref visited i))
      (define cycle-size 0)
      (define current i)
      (define target (list-ref sorted i))
      (let loop ()
        (when (and (not (vector-ref visited current))
                   (not (= (list-ref nums current) target)))
          (vector-set! visited current #t)
          (set! cycle-size (+ cycle-size 1))
          (set! current (hash-ref pos (list-ref nums current)))
          (loop))))
      (when (> cycle-size 0)
        (set! swaps (+ swaps (- cycle-size 1))))))
  swaps)