(define (combination-sum-ii candidates target)
  (define (backtrack start path remaining)
    (if (= remaining 0)
        (list path)
        (if (> remaining 0)
            (for/fold ([result '()])
                      ([i (in-range start (length candidates))])
              (if (or (= i 0) (not (= (list-ref candidates i) (list-ref candidates (sub1 i)))))
                  (append result (backtrack (add1 i) (append path (list (list-ref candidates i))) (- remaining (list-ref candidates i))))
                  result))
            '())))
  (sort (backtrack 0 '() target) #:key (λ (x) (map (λ (y) y) x))))