(define (reconstruct-queue people)
  (define (compare a b)
    (if (= (car a) (car b))
        (<= (cadr a) (cadr b))
        (>= (car a) (car b))))
  (define sorted (sort people compare))
  (define (insert lst pos person)
    (if (= pos 0)
        (cons person lst)
        (cons (car lst) (insert (cdr lst) (- pos 1) person))))
  (define (build-queue lst result)
    (if (null? lst)
        result
        (build-queue (cdr lst) (insert result (cadr (car lst)) (car lst)))))
  (build-queue sorted '()))