(define (count-battleships board)
  (define (is-head? i j)
    (and (or (= i 0) (not (equal? (list-ref board (sub1 i)) (list-ref board i)) (list-ref (list-ref board (sub1 i)) j)))
         (or (= j 0) (not (equal? (list-ref (list-ref board i) (sub1 j)) #\X)))))
  (define (count i j)
    (if (>= i (length board))
        0
        (let ((row (list-ref board i)))
          (if (>= j (length row))
              (count (add1 i) 0)
              (if (and (equal? (list-ref row j) #\X) (is-head? i j))
                  (+ 1 (count i (add1 j)))
                  (count i (add1 j)))))))
  (count 0 0))