(define (original-digit s)
  (define (count-letters s)
    (let ((freq (make-hash)))
      (for-each (lambda (c) (hash-update! freq c add1)) (string->list s))
      freq))

  (define (get-digit count)
    (cond ((hash-has-key? count #\z) (cons 0 (hash-ref count #\z)))
          ((hash-has-key? count #\w) (cons 2 (hash-ref count #\w)))
          ((hash-has-key? count #\u) (cons 4 (hash-ref count #\u)))
          ((hash-has-key? count #\x) (cons 6 (hash-ref count #\x)))
          ((hash-has-key? count #\g) (cons 8 (hash-ref count #\g)))
          ((hash-has-key? count #\s) (cons 7 (hash-ref count #\s)))
          ((hash-has-key? count #\v) (cons 5 (hash-ref count #\v)))
          ((hash-has-key? count #\f) (cons 4 (hash-ref count #\f)))
          ((hash-has-key? count #\t) (cons 3 (hash-ref count #\t)))
          ((hash-has-key? count #\o) (cons 1 (hash-ref count #\o)))
          (else (cons -1 0))))

  (define (subtract-digit count d)
    (case d
      ((0) (for-each (lambda (c) (hash-update! count c sub1)) '(#\z #\e #\r #\o)))
      ((2) (for-each (lambda (c) (hash-update! count c sub1)) '(#\t #\w #\o)))
      ((4) (for-each (lambda (c) (hash-update! count c sub1)) '(#\f #\o #\r #\u)))
      ((6) (for-each (lambda (c) (hash-update! count c sub1)) '(#\s #\i #\x)))
      ((8) (for-each (lambda (c) (hash-update! count c sub1)) '(#\e #\i #\g #\h #\t)))
      ((7) (for-each (lambda (c) (hash-update! count c sub1)) '(#\s #\e #\v #\n)))
      ((5) (for-each (lambda (c) (hash-update! count c sub1)) '(#\f #\i #\v #\e)))
      ((3) (for-each (lambda (c) (hash-update! count c sub1)) '(#\t #\h #\r #\e #\e)))
      ((1) (for-each (lambda (c) (hash-update! count c sub1)) '(#\o #\n #\e)))
      (else #f)))

  (define count (count-letters s))
  (define result '())
  (let loop ()
    (let ((d (get-digit count)))
      (if (= (car d) -1)
          (list->string (reverse result))
          (begin
            (set! result (append (make-list (cdr d) (number->char (+ 48 (car d)))) result))
            (subtract-digit count (car d))
            (loop))))))