(define (find-disappeared-numbers nums)
  (let ((n (length nums)))
    (for-each (lambda (num)
                (let ((index (abs num)))
                  (when (positive? (list-ref nums (sub1 index)))
                    (set! nums (replace-at nums (sub1 index) (- (list-ref nums (sub1 index))))))))
              nums)
    (filter (lambda (i) (positive? (list-ref nums (sub1 i))))
            (range 1 (add1 n)))))

(define (replace-at lst index val)
  (if (zero? index)
      (cons val (cdr lst))
      (cons (car lst) (replace-at (cdr lst) (sub1 index) val))))