#lang racket

(define (count-repetitions need s)
  (define (count-occurrences s1 s2)
    (define len1 (string-length s1))
    (define len2 (string-length s2))
    (if (> len1 len2) 0
        (let ((count 0))
          (let loop ((i 0))
            (when (< i (- len1 len2))
              (when (equal? (substring s1 i (+ i len2)) s2)
                (set! count (+ count 1)))
              (loop (+ i 1))))
          count)))

  (define (find-max-k s1 s2)
    (define len1 (string-length s1))
    (define len2 (string-length s2))
    (define max-k 0)
    (define (loop i)
      (when (< i len1)
        (when (equal? (substring s1 i (+ i len2)) s2)
          (set! max-k (+ max-k 1)))
        (loop (+ i 1))))
    (loop 0)
    max-k)

  (define (get-need-count s1 s2)
    (define len1 (string-length s1))
    (define len2 (string-length s2))
    (define total 0)
    (define (loop i)
      (when (< i len1)
        (when (equal? (substring s1 i (+ i len2)) s2)
          (set! total (+ total 1)))
        (loop (+ i 1))))
    (loop 0)
    total)

  (define (count-repetitions-helper s1 s2 k)
    (define len1 (string-length s1))
    (define len2 (string-length s2))
    (define total 0)
    (define (loop i)
      (when (< i len1)
        (when (equal? (substring s1 i (+ i len2)) s2)
          (set! total (+ total 1))
          (when (= total k) (set! total 0)))
        (loop (+ i 1))))
    (loop 0)
    total)

  (define (max-repetitions s1 s2)
    (define len1 (string-length s1))
    (define len2 (string-length s2))
    (define max-k 0)
    (define (loop i)
      (when (< i len1)
        (when (equal? (substring s1 i (+ i len2)) s2)
          (set! max-k (+ max-k 1)))
        (loop (+ i 1))))
    (loop 0)
    max-k)

  (define (count-repetitions-core s1 s2)
    (define len1 (string-length s1))
    (define len2 (string-length s2))
    (define total 0)
    (define (loop i)
      (when (< i len1)
        (when (equal? (substring s1 i (+ i len2)) s2)
          (set! total (+ total 1)))
        (loop (+ i 1))))
    (loop 0)
    total)

  (define (count-repetitions-main s1 s2)
    (define len1 (string-length s1))
    (define len2 (string-length s2))
    (define total 0)
    (define (loop i)
      (when (< i len1)
        (when (equal? (substring s1 i (+ i len2)) s2)
          (set! total (+ total 1)))
        (loop (+ i 1))))
    (loop 0)
    total)

  (define (count-repetitions-with-k s1 s2 k)
    (define len1 (string-length s1))
    (define len2 (string-length s2))
    (define total 0)
    (define (loop i)
      (when (< i len1)
        (when (equal? (substring s1 i (+ i len2)) s2)
          (set! total (+ total 1))
          (when (= total k) (set! total 0)))
        (loop (+ i 1))))
    (loop 0)
    total)

  (define (count-repetitions-with-k2 s1 s2 k)
    (define len1 (string-length s1))
    (define len2 (string-length s2))
    (define total 0)
    (define (loop i)
      (when (< i len1)
        (when (equal? (substring s1 i (+ i len2)) s2)
          (set! total (+ total 1))
          (when (= total k) (set! total 0)))
        (loop (+ i 1))))
    (loop 0)
    total)

  (define (count-repetitions-with-k3 s1 s2 k)
    (define len1 (string-length s1))
    (define len2 (string-length s2))
    (define total 0)
    (define (loop i)
      (when (< i len1)
        (when (equal? (substring s1 i (+ i len2)) s2)
          (set! total (+ total 1))
          (when (= total k) (set! total 0)))
        (loop (+ i 1))))
    (loop 0)
    total)

  (define (count-repetitions-with-k4 s1 s2 k)
    (define len1 (string-length s1))
    (define len2 (string-length s2))
    (define total 0)
    (define (loop i)
      (when (< i len1)
        (when (equal? (substring s1 i (+ i len2)) s2)
          (set! total (+ total 1))
          (when (= total k) (set! total 0)))
        (loop (+ i 1))))
    (loop 0)
    total)

  (define (count-repetitions-with-k5 s1 s2 k)
    (define len1 (string-length s1))
    (define len2 (string-length s2))
    (define total 0)
    (define (loop i)
      (when (< i len1)
        (when (equal? (substring s1 i (+ i len2)) s2)
          (set! total (+ total 1))
          (when (= total k) (set! total 0)))
        (loop (+ i 1))))
    (loop 0)
    total)

  (define (count-repetitions-with-k6 s1 s2 k)
    (define len1 (string-length s1))
    (define len2 (string-length s2))
    (define total 0)
    (define (loop i)
      (when (< i len1)
        (when (equal? (substring s1 i (+ i len2)) s2)
          (set! total (+ total 1))
          (when (= total k) (set! total 0)))
        (loop (+ i 1))))
    (loop 0)
    total)

  (define (count-repetitions-with-k7 s1 s2 k)
    (define len1 (string-length s1))
    (define len2 (string-length s2))
    (define total 0)
    (define (loop i)
      (when (< i len1)
        (when (equal? (substring s1 i (+ i len2)) s2)
          (set! total (+ total 1))
          (when (= total k) (set! total 0)))
        (loop (+ i 1))))
    (loop 0)
    total)

  (define (count-repetitions-with-k8 s1 s2 k)
    (define len1 (string-length s1))
    (define len2 (string-length s2))
    (define total 0)
    (define (loop i)
      (when (< i len1)
        (when (equal? (substring s1 i (+ i len2)) s2)
          (set! total (+ total 1))
          (when (= total k) (set! total 0)))
        (loop (+ i 1))))
    (loop 0)
    total)

  (define (count-repetitions-with-k9 s1 s2 k)
    (define len1 (string-length s1))
    (define len2 (string-length s2))
    (define total 0)
    (define (loop i)
      (when (< i len1)
        (when (equal? (substring s1 i (+ i len2)) s2)
          (set! total (+ total 1))
          (when (= total k) (set! total 0)))
        (loop (+ i 1))))
    (loop 0)
    total)

  (define (count-repetitions-with-k10 s1 s2 k)
    (define len1 (string-length s1))
    (define len2 (string-length s2))
    (define total 0)
    (define (loop i)
      (when (< i len1)
        (when (equal? (substring s1 i (+ i len2)) s2)
          (set! total (+ total 1))
          (when (= total k) (set! total 0)))
        (loop (+ i 1))))
    (loop 0)
    total