(define (insert-interval intervals new-interval)
  (define (merge a b)
    (if (<= (car b) (cadr a))
        (list (car a) (max (cadr a) (cadr b)))
        (list a b)))

  (define (merge-all lst)
    (if (null? lst)
        '()
        (let ((current (car lst))
              (rest (merge-all (cdr lst))))
          (if (null? rest)
              (list current)
              (let ((merged (merge current (car rest))))
                (if (= (length merged) 2)
                    (cons (car merged) (merge-all (cons (cadr merged) (cdr rest))))
                    (cons merged (merge-all (cdr rest))))))))

  (define (insert lst)
    (cond ((null? lst) (list new-interval))
          ((<= (cadr new-interval) (caar lst)) (cons new-interval lst))
          ((<= (caar lst) (cadr new-interval) (cadar lst)) (cons (merge (car lst) new-interval) (cdr lst)))
          (else (cons (car lst) (insert (cdr lst))))))

  (merge-all (insert intervals)))