(define (k-inverse-pairs-array n k)
  (define mod 1000000007)
  (define dp (make-vector (+ n 1) (make-vector (+ k 1) 0)))
  (vector-set! dp 0 0 1)
  (for ([i (in-range 1 (+ n 1))])
    (for ([j (in-range 0 (+ k 1))])
      (if (= j 0)
          (vector-set! dp i j 1)
          (begin
            (vector-set! dp i j (modulo (+ (vector-ref dp i j) (vector-ref dp (- i 1) (- j 1))) mod))
            (when (>= j i)
              (vector-set! dp i j (modulo (- (vector-ref dp i j) (vector-ref dp (- i 1) (- j i))) mod)))))))
  (vector-ref (vector-ref dp n) k))