(define (count-binary-substrings s)
  (define len (string-length s))
  (define count 0)
  (define prev 0)
  (define curr 1)
  (for ([i (in-range 1 len)])
    (when (equal? (string-ref s (sub1 i)) (string-ref s i))
      (set! curr (add1 curr))
      (set! count (add1 count)))
    (when (not (equal? (string-ref s (sub1 i)) (string-ref s i)))
      (set! prev curr)
      (set! curr 1)
      (set! count (add1 count))))
  count)