(define (max-length-of-repeated-subarray nums1 nums2)
  (define n (length nums1))
  (define m (length nums2))
  (define dp (make-vector (add1 n) (make-vector (add1 m) 0)))
  (define max-len 0)
  (for ([i (in-range n)])
    (for ([j (in-range m)])
      (when (= (list-ref nums1 i) (list-ref nums2 j))
        (vector-set! (vector-ref dp i) j (+ (vector-ref (vector-ref dp (sub1 i)) (sub1 j)) 1))
        (set! max-len (max max-len (vector-ref (vector-ref dp i) j)))))
  max-len)