(define (min a b c)
  (if (< a b)
      (if (< a c) a c)
      (if (< b c) b c)))

(define (edit-distance word1 word2)
  (let ((m (string-length word1))
        (n (string-length word2)))
    (let ((dp (make-vector (+ m 1) #f)))
      (do ((i 0 (+ i 1)))
          ((> i m) dp)
        (vector-set! dp i (make-vector (+ n 1) 0))
        (vector-set! (vector-ref dp i) 0 i))
      (do ((j 0 (+ j 1)))
          ((> j n) dp)
        (vector-set! (vector-ref dp 0) j j))
      (do ((i 1 (+ i 1)))
          ((> i m) dp)
        (do ((j 1 (+ j 1)))
            ((> j n) dp)
          (let ((cost (if (char=? (string-ref word1 (- i 1)) (string-ref word2 (- j 1))) 0 1)))
            (vector-set! (vector-ref dp i) j
                         (min (+ (vector-ref (vector-ref dp (- i 1)) j) 1)
                              (+ (vector-ref (vector-ref dp i) (- j 1)) 1)
                              (+ (vector-ref (vector-ref dp (- i 1)) (- j 1)) cost)))))))
    (vector-ref (vector-ref dp m) n)))