(define (set-zeroes matrix)
  (let* ((rows (length matrix))
         (cols (if (> rows 0) (length (car matrix)) 0))
         (zero-rows (make-set))
         (zero-cols (make-set)))
    (for ([i (in-range rows)])
      (for ([j (in-range cols)])
        (when (= (list-ref (list-ref matrix i) j) 0)
          (set-add! zero-rows i)
          (set-add! zero-cols j))))
    (for ([i (in-range rows)])
      (for ([j (in-range cols)])
        (when (or (set-member? zero-rows i) (set-member? zero-cols j))
          (set! (list-ref (list-ref matrix i) j) 0))))
    matrix))