(define (count-different-palindromic-subsequences s)
  (define n (string-length s))
  (define dp (make-vector n (lambda () (make-vector n 0))))
  (define (is-pali? l r)
    (let loop ((i l) (j r))
      (cond ((>= i j) #t)
            ((char=? (string-ref s i) (string-ref s j)) (loop (+ i 1) (- j 1)))
            (else #f))))
  (define (count l r)
    (if (> l r) 0
        (if (= l r) 1
            (let ((res (vector-ref (vector-ref dp l) r)))
              (if (not (zero? res)) res
                  (let ((res (if (char=? (string-ref s l) (string-ref s r))
                                 (+ (count (+ l 1) (- r 1)) 2)
                                 (count (+ l 1) r)
                                 (count l (- r 1))
                                 (if (and (not (char=? (string-ref s l) (string-ref s r)))
                                          (is-pali? l r))
                                     (count (+ l 1) (- r 1))
                                     0)))))
                    (vector-set! (vector-ref dp l) r res)
                    res)))))
  (count 0 (- n 1)))