(define (next-greater-characters letters target)
  (define (char->int c) (- (char->integer c) (char->integer #\a)))
  (define (int->char i) (integer->char (+ i (char->integer #\a))))
  (define target-int (char->int target))
  (define sorted-letters (sort letters char<?))
  (let loop ((i 0))
    (if (= i (length sorted-letters))
        (int->char (modulo target-int 26))
        (let ((current-int (char->int (list-ref sorted-letters i))))
          (if (> current-int target-int)
              (list-ref sorted-letters i)
              (loop (+ i 1)))))))