#lang racket

(define (crack-safe n k)
  (define result '())
  (define visited #hash())
  (define (dfs node)
    (when (= (hash-count visited) (expt k n))
      (set! result (string->list node))
      #t)
    (for ([i (in-range k)])
      (define next-node (string-append node (number->string i)))
      (when (not (hash-has-key? visited next-node))
        (hash-set! visited next-node #t)
        (when (dfs next-node)
          (set! result (string->list next-node))
          (set! result (append (take-right result (- (string-length next-node) n)) result))
          (set! result (reverse result))
          (set! result (append (list (string-ref node (- (string-length node) 1))) result))
          #t)
        (hash-remove! visited next-node))))
  (if (= n 0)
      '()
      (begin
        (hash-set! visited (make-string n #\0) #t)
        (dfs (make-string n #\0))
        (list->string result))))