(define (intersection-size-at-least-two intervals)
  (define (cmp a b)
    (let ((a1 (car a)) (a2 (cadr a))
          (b1 (car b)) (b2 (cadr b)))
      (if (= a2 b2)
          (- a1 b1)
          (- a2 b2))))
  (define (merge intervals)
    (if (null? intervals)
        '()
        (let ((sorted (sort intervals cmp)))
          (let loop ((res (list (car sorted)))
                     (intervals (cdr sorted)))
            (if (null? intervals)
                res
                (let* ((last (car res))
                       (curr (car intervals))
                       (last-end (cadr last))
                       (curr-start (car curr))
                       (curr-end (cadr curr)))
                  (if (<= curr-start last-end)
                      (loop (cons (list (car last) (max last-end curr-end)) (cdr res))
                            (cdr intervals))
                      (loop (cons curr res)
                            (cdr intervals))))))))
  (define (solve intervals)
    (let loop ((intervals (merge intervals))
               (res '()))
      (if (null? intervals)
          (length res)
          (let* ((interval (car intervals))
                 (start (car interval))
                 (end (cadr interval)))
            (if (and (not (null? res))
                     (>= (cadr res) start))
                (loop (cdr intervals) res)
                (loop (cdr intervals) (cons end (cons end res)))))))
  (solve intervals))