(define (partition-labels s)
  (define last-index (make-hash))
  (for ([i (in-range (string-length s))])
    (hash-set! last-index (string-ref s i) i))
  (let loop ([start 0] [end 0] [result '()])
    (if (= start (string-length s))
        (reverse result)
        (let ([current-end (hash-ref last-index (string-ref s start))])
          (if (> current-end end)
              (loop start current-end result)
              (loop (+ end 1) end (cons (substring s start (+ end 1)) result)))))))