(define (couples-holding-hands c)
  (define n (length c))
  (define parent (make-vector n))
  (define (find x)
    (if (not (= (vector-ref parent x) x))
        (vector-set! parent x (find (vector-ref parent x)))
        x))
  (define (union x y)
    (vector-set! parent (find x) (find y)))
  (for ([i (in-range 0 n 2)])
    (union (vector-ref c i) (vector-ref c (add1 i))))
  (define (count-components)
    (for/fold ([count 0])
              ([i (in-range n)])
      (if (= i (find i)) (add1 count) count)))
  (count-components))