#lang racket

(define (swim-in-rising-water grid)
  (define n (length grid))
  (define visited (make-vector n #f))
  (define directions (list (cons 0 1) (cons 1 0) (cons 0 -1) (cons -1 0)))
  (define pq (priority-queue #:priority <))
  (vector-set! visited 0 #t)
  (for ([i (in-range n)])
    (priority-queue-add! pq (cons (vector-ref (vector-ref grid 0) i) (cons 0 i))))
  (let loop ()
    (when (not (priority-queue-empty? pq))
      (define current (priority-queue-remove! pq))
      (define val (car current))
      (define pos (cdr current))
      (define x (car pos))
      (define y (cdr pos))
      (when (and (= x (sub1 n)) (= y (sub1 n)))
        val)
      (for ([d (in-list directions)])
        (define nx (+ x (car d)))
        (define ny (+ y (cdr d)))
        (when (and (<= 0 nx (sub1 n)) (<= 0 ny (sub1 n)) (not (vector-ref visited nx)))
          (vector-set! visited nx #t)
          (priority-queue-add! pq (cons (max val (vector-ref (vector-ref grid nx) ny)) (cons nx ny)))))
      (loop))))

(define (main)
  (define input (read))
  (displayln (swim-in-rising-water input)))

(main)