#lang racket

(define (valid? board)
  (define n (length board))
  (define (is-chessboard? row col)
    (and (= (bitwise-xor (list-ref (list-ref board row) col) (list-ref (list-ref board row) (if (= col 0) 1 0))) 1)
         (= (bitwise-xor (list-ref (list-ref board row) col) (list-ref (list-ref board (if (= row 0) 1 0)) col)) 1)))
  (define (count-matches row col)
    (if (equal? (list-ref (list-ref board row) col) (if (even? (+ row col)) 0 1))
        1
        0))
  (define (count-rows)
    (define (helper r c cnt)
      (if (= r n)
          cnt
          (if (= (list-ref (list-ref board r) 0) (if (even? r) 0 1))
              (helper (+ r 1) 0 (+ cnt 1))
              (helper (+ r 1) 0 cnt))))
    (helper 0 0 0))
  (define (count-cols)
    (define (helper r c cnt)
      (if (= c n)
          cnt
          (if (= (list-ref (list-ref board 0) c) (if (even? c) 0 1))
              (helper 0 (+ c 1) (+ cnt 1))
              (helper 0 (+ c 1) cnt))))
    (helper 0 0 0))
  (and (<= (abs (- (count-rows) (count-cols))) 1)
       (andmap (lambda (r) (andmap (lambda (c) (is-chessboard? r c)) (range n))) (range n))))

(define (moves-to-chessboard board)
  (define n (length board))
  (if (not (valid? board)) -1
      (let* ((row-count (count-rows))
             (col-count (count-cols))
             (row-moves (if (= (modulo n 2) 1)
                             (if (= (remainder row-count 2) 1)
                                 (if (= (list-ref (list-ref board 0) 0) 0) (quotient row-count 2) (+ (quotient row-count 2) 1))
                                 (quotient row-count 2))
                             (if (= (remainder row-count 2) 1)
                                 (if (= (list-ref (list-ref board 0) 0) 0) (quotient row-count 2) (+ (quotient row-count 2) 1))
                                 (quotient row-count 2))))
             (col-moves (if (= (modulo n 2) 1)
                             (if (= (remainder col-count 2) 1)
                                 (if (= (list-ref (list-ref board 0) 0) 0) (quotient col-count 2) (+ (quotient col-count 2) 1))
                                 (quotient col-count 2))
                             (if (= (remainder col-count 2) 1)
                                 (if (= (list-ref (list-ref board 0) 0) 0) (quotient col-count 2) (+ (quotient col-count 2) 1))
                                 (quotient col-count 2))))
             (row-moves (if (= (modulo n 2) 1)
                             (if (= (remainder row-count 2) 1)
                                 (if (= (list-ref (list-ref board 0) 0) 0) (quotient row-count 2) (+ (quotient row-count 2) 1))
                                 (quotient row-count 2))
                             (if (= (remainder row-count 2) 1)
                                 (if (= (list-ref (list-ref board 0) 0) 0) (quotient row-count 2) (+ (quotient row-count 2) 1))
                                 (quotient row-count 2))))
             (col-moves (if (= (modulo n 2) 1)
                             (if (= (remainder col-count 2) 1)
                                 (if (= (list-ref (list-ref board 0) 0) 0) (quotient col-count 2) (+ (quotient col-count 2) 1))
                                 (quotient col-count 2))
                             (if (= (remainder col-count 2) 1)
                                 (if (= (list-ref (list-ref board 0) 0) 0) (quotient col-count 2) (+ (quotient col-count 2) 1))
                                 (quotient col-count 2))))
             (row-moves (if (= (modulo n 2) 1)
                             (if (= (remainder row-count 2) 1)
                                 (if (= (list-ref (list-ref board 0) 0) 0) (quotient row-count 2) (+ (quotient row-count 2) 1))
                                 (quotient row-count 2))
                             (if (= (remainder row-count 2) 1)
                                 (if (= (list-ref (list-ref board 0) 0) 0) (quotient row-count 2) (+ (quotient row-count 2) 1))
                                 (quotient row-count 2))))
             (col-moves (if (= (modulo n 2) 1)
                             (if (= (remainder col-count 2) 1)
                                 (if (= (list-ref (list-ref board 0) 0) 0) (quotient col-count 2) (+ (quotient col-count 2) 1))
                                 (quotient col-count 2))
                             (if (= (remainder col-count 2) 1)
                                 (if (= (list-ref (list-ref board 0) 0) 0) (quotient col-count 2) (+ (quotient col-count 2) 1))
                                 (quotient col-count 2)))))
        (if (= (modulo n 2) 1)
            (min row-moves col-moves)
            (min row-moves col-moves)))))

(define (count-rows)
  (define n (length board))
  (define (helper r cnt)
    (if (= r n)
        cnt
        (if (= (list-ref (list-ref board r) 0) (if (even? r) 0 1))
            (helper (+ r 1) (+ cnt 1))
            (helper (+ r 1) cnt))))
  (helper 0 0))

(define (count-cols)
  (define n (length board))
  (define (helper c cnt)
    (if (= c n)
        cnt
        (if (= (list-ref (list-ref board 0) c) (if (even? c) 0 1))
            (helper (+ c 1) (+ cnt 1))
            (helper (+ c 1) cnt))))
  (helper 0 0))

(define (moves-to-chessboard board)
  (define n (length board))
  (define (is-valid?)
    (define (check-row r)
      (define (check-col c)
        (and (= (bitwise-xor (list-ref (list-ref board r) c) (list-ref (list-ref board r) (if (= c 0) 1 0))) 1)
             (= (bitwise-xor (list-ref (list-ref board r) c) (list-ref (list-ref board (if (= r 0) 1 0)) c)) 1)))
      (andmap check-col (range n)))
    (andmap check-row (range n)))
  (if (not (is-valid?)) -1
      (let* ((row-count (count-rows))
             (col-count (count-cols))
             (row-moves (if (= (modulo n 2) 1)
                             (if (= (remainder row-count 2) 1)
                                 (if (= (list-ref (list-ref board 0) 0) 0) (quotient row-count 2) (+ (quotient row-count 2) 1))
                                 (quotient row-count 2))
                             (if (= (remainder row-count 2) 1)
                                 (if (= (list-ref (list-ref board 0) 0) 0) (quotient row-count 2) (+ (quotient row-count 2) 1))
                                 (quotient row-count 2))))
             (col-moves (if (= (modulo n 2) 1)
                             (if (= (remainder col-count 2) 1)
                                 (if (= (list-ref (list-ref board 0) 0) 0) (quotient col-count 2) (+ (quotient col-count 2) 1))
                                 (quotient col-count 2))
                             (if (= (remainder col-count 2) 1)
                                 (if (= (list-ref (list-ref board 0) 0) 0) (quotient col-count 2) (+ (quotient col-count 2) 1))
                                 (quotient col-count 2))))
             (row-moves (