(define (is-bipartite graph)
  (define color (make-hash))
  (define (dfs node c)
    (if (hash-has-key? color node)
        (= (hash-ref color node) c)
        (begin
          (hash-set! color node c)
          (andmap (lambda (nei)
                    (dfs nei (- 1 c)))
                  (vector-ref graph node)))))
  (define (bfs node)
    (let ((queue (list node)))
      (hash-set! color node 0)
      (let loop ((q queue))
        (if (null? q)
            #t
            (let* ((current (car q))
                   (neighbors (vector-ref graph current)))
              (for-each (lambda (nei)
                          (if (hash-has-key? color nei)
                              (when (!= (hash-ref color nei) (- 1 (hash-ref color current)))
                                (set! queue #f)))
                              (begin
                                (hash-set! color nei (- 1 (hash-ref color current)))
                                (set! queue (append (cdr q) (list nei)))))
                        neighbors)
              (loop (cdr q))))))
  (let loop ((i 0))
    (if (>= i (vector-length graph))
        #t
        (if (hash-has-key? color i)
            (loop (+ i 1))
            (if (dfs i 0)
                (loop (+ i 1))
                #f)))))