(define (custom-sort-string order s)
  (define freq (make-hash))
  (for-each (lambda (c) (hash-set! freq c (+ 1 (hash-ref freq c 0)))) (string->list s))
  (define result '())
  (for-each (lambda (c)
              (when (hash-has-key? freq c)
                (set! result (append result (make-list (hash-ref freq c) c)))))
            (string->list order))
  (for-each (lambda (c)
              (when (hash-has-key? freq c)
                (set! result (append result (make-list (hash-ref freq c) c))))
            (remove* (string->list order) (string->list s)))
  (list->string result))