(define (largest-sum-of-averages nums n)
  (define len (length nums))
  (define dp (make-vector len (make-vector (add1 n) 0.0)))
  (define prefix (make-vector len 0.0))
  (for ([i (in-range len)])
    (vector-set! prefix i (if (= i 0) (vector-ref nums i) (+ (vector-ref prefix (- i 1)) (vector-ref nums i))))
  )
  (for ([i (in-range len)])
    (vector-set! (vector-ref dp i) 1 (/ (vector-ref prefix i) (add1 i)))
  )
  (for ([i (in-range len)])
    (for ([k (in-range 2 (add1 n))])
      (for ([j (in-range k (- i 1))])
        (define current-avg (- (vector-ref prefix i) (vector-ref prefix j)))
        (define avg (/ current-avg (- i j)))
        (vector-set! (vector-ref dp i) k (max (vector-ref (vector-ref dp i) k) (+ (vector-ref (vector-ref dp j) (- k 1)) avg)))
      )
    )
  )
  (vector-ref (vector-ref dp (- len 1)) n))