#lang racket

(define (race-car target)
  (define (bfs)
    (define queue (queue))
    (queue-add! queue (cons 0 0))
    (define visited (set))
    (set-add! visited 0)
    (let loop ()
      (when (not (queue-empty? queue))
        (define current (queue-remove! queue))
        (define pos (car current))
        (define speed (cdr current))
        (when (= pos target)
          (return (cdr current)))
        (define next-pos (+ pos speed))
        (define next-speed (* speed 2))
        (when (and (<= next-pos target) (not (set-member? visited next-pos)))
          (set-add! visited next-pos)
          (queue-add! queue (cons next-pos next-speed)))
        (define next-pos2 (- pos speed))
        (define next-speed2 (- speed 1))
        (when (and (>= next-pos2 0) (not (set-member? visited next-pos2)))
          (set-add! visited next-pos2)
          (queue-add! queue (cons next-pos2 next-speed2)))
        (loop))))
  (bfs))