(define (overlapping-rectangle rec1 rec2)
  (let* ((x1 (car rec1))
         (y1 (cadr rec1))
         (x2 (caddr rec1))
         (y2 (cadddr rec1))
         (x3 (car rec2))
         (y3 (cadr rec2))
         (x4 (caddr rec2))
         (y4 (cadddr rec2)))
    (and (< x1 x4)
         (> x2 x3)
         (< y1 y4)
         (> y2 y3))))