(define (new21game n k m)
  (define dp (make-vector (add1 n) 0.0))
  (vector-set! dp 0 1.0)
  (define window-sum 1.0)
  (define i 1)
  (define j 1)
  (when (<= k n)
    (let loop ()
      (when (<= i n)
        (when (<= i k)
          (vector-set! dp i (if (>= i m) (- window-sum (vector-ref dp (- i m))) window-sum)))
        (when (<= j n)
          (set! window-sum (+ window-sum (vector-ref dp i)))
          (when (<= i m)
            (set! window-sum (- window-sum (vector-ref dp (- i m)))))
          (set! j (+ j 1)))
        (set! i (+ i 1))
        (loop))))
  (apply + (map (lambda (x) (vector-ref dp x)) (range k n 1))))