(define (push-dominoes dominoes)
  (define n (string-length dominoes))
  (define left (make-vector n 0))
  (define right (make-vector n 0))
  (define (apply-force dir i)
    (let loop ((i i) (f 0))
      (when (< i n)
        (if (char=? (string-ref dominoes i) #\L)
            (when (> f 0) (vector-set! left i f))
            (when (> f 0) (vector-set! right i f))
            (loop (+ i dir) (if (char=? (string-ref dominoes i) #\.) (+ f 1) 0)))))
  (let loop ((i 0))
    (when (< i n)
      (when (char=? (string-ref dominoes i) #\R)
        (apply-force 1 i))
      (loop (+ i 1))))
  (let loop ((i (- n 1)))
    (when (>= i 0)
      (when (char=? (string-ref dominoes i) #\L)
        (apply-force -1 i))
      (loop (- i 1))))
  (define (compare a b)
    (cond ((= a b) #\.)
          ((> a b) #\R)
          (else #\L)))
  (list->string (for/list ((i (in-range n)))
                  (char-upcase (compare (vector-ref left i) (vector-ref right i))))))