(define (can-visit-all? rooms)
  (define visited (make-hash))
  (define (dfs room)
    (hash-set! visited room #t)
    (for-each (lambda (next-room)
                (when (not (hash-has-key? visited next-room))
                  (dfs next-room)))
              (hash-ref rooms room)))
  (dfs 0)
  (= (hash-count visited) (length rooms)))