(define (shifting-letters s shifts)
  (define len (string-length s))
  (define shift-array (list->vector shifts))
  (define result (make-vector len #\a))
  (define total-shift 0)
  (for ([i (in-range (sub1 len) -1 -1)])
    (set! total-shift (+ total-shift (vector-ref shift-array i)))
    (vector-set! result i (integer->char (+ (modulo (+ (- (char->integer (vector-ref result i)) total-shift) 26) 26) 97))))
  (list->string (vector->list result)))