(define (lemonade-change bills)
  (let loop ((bills bills) (five 0) (ten 0))
    (cond ((null? bills) #t)
          ((= (car bills) 5) (loop (cdr bills) (+ five 1) ten))
          ((and (= (car bills) 10) (> five 0))
           (loop (cdr bills) (- five 1) (+ ten 1)))
          ((and (= (car bills) 20) (> ten 0) (> five 0))
           (loop (cdr bills) (- five 1) (- ten 1)))
          ((and (= (car bills) 20) (> five 2))
           (loop (cdr bills) (- five 2) ten))
          (else #f))))