(define (matrix-score grid)
  (let* ([n (length grid)]
         [m (length (car grid))])
    (for-each (lambda (row)
                (when (not (= (list-ref row 0) 1))
                  (for-each (lambda (i)
                              (set! (list-ref row i) (- 1 (list-ref row i))))
                            (range m))))
              grid)
    (for-each (lambda (j)
                (let ([count (apply + (map (lambda (row) (list-ref row j)) grid))])
                  (when (< count (/ n 2))
                    (for-each (lambda (i)
                                (set! (list-ref (list-ref grid i) j) (- 1 (list-ref (list-ref grid i) j))))
                              (range n)))))
              (range m))
    (apply + (map (lambda (row) (apply + row)) grid))))