(define (min-eating-speed piles h)
  (define (can-eat speed)
    (let loop ((piles piles) (time 0))
      (if (null? piles)
          (<= time h)
          (loop (cdr piles) (+ time (quotient (car piles) speed) (if (not (zero? (remainder (car piles) speed))) 1 0))))))
  (let loop ((left 1) (right (apply max piles)))
    (if (<= left right)
        (let ((mid (quotient (+ left right) 2)))
          (if (can-eat mid)
              (loop left (sub1 mid))
              (loop (add1 mid) right)))
        left)))