(define (fair-candy-swap alice-swaps bob-swaps)
  (let* ((sum-alice (apply + alice-swaps))
         (sum-bob (apply + bob-swaps))
         (diff (- sum-alice sum-bob)))
    (define target (/ diff 2))
    (define bob-set (list->set bob-swaps))
    (for/first ((a alice-swaps)
                (b (in-list bob-swaps))
                #:when (= (+ a (- b)) (+ sum-alice (- b) a)))
      (list a b))))