(define (sum-subarray-mins A)
  (define MOD 1000000007)
  (define n (length A))
  (define left (make-vector n -1))
  (define right (make-vector n n))
  (define stack '())
  (for ([i (in-range n)])
    (let loop ()
      (when (and (not (null? stack)) (< (vector-ref A (car stack)) (vector-ref A i)))
        (vector-set! left i (car stack))
        (set! stack (cdr stack))
        (loop))))
  (set! stack '())
  (for ([i (in-range n -1 -1)])
    (let loop ()
      (when (and (not (null? stack)) (<= (vector-ref A (car stack)) (vector-ref A i)))
        (vector-set! right i (car stack))
        (set! stack (cdr stack))
        (loop))))
  (define res 0)
  (for ([i (in-range n)])
    (define l (- i (vector-ref left i)))
    (define r (- (vector-ref right i) i))
    (set! res (+ res (* (vector-ref A i) l r)) )
    (set! res (modulo res MOD)))
  res)