(define (num-decode s)
  (define memo (make-hash))
  (define (dp i)
    (cond ((= i (string-length s)) 1)
          ((hash-has-key? memo i) (hash-ref memo i))
          ((char=? #\0 (string-ref s i)) 0)
          (else
           (let ((res (dp (+ i 1))))
             (when (and (< i (- (string-length s) 1))
                        (<= (string->number (substring s i (+ i 2))) 26))
               (set! res (+ res (dp (+ i 2)))))
             (hash-set! memo i res)
             res))))
  (dp 0))