#lang racket

(define-struct node (val left right) #:mutable)

(define (is-complete-binary-tree root)
  (define q (queue))
  (queue-put! q root)
  (define flag #f)
  (let loop ()
    (when (not (queue-empty? q))
      (define node (queue-get! q))
      (when (and (node-left node) (node-right node))
        (queue-put! q (node-left node))
        (queue-put! q (node-right node)))
      (when (node-left node)
        (if (node-right node)
            (begin
              (queue-put! q (node-left node))
              (queue-put! q (node-right node)))
            (begin
              (queue-put! q (node-left node))
              (set! flag #t))))
      (when (and (not (node-left node)) (node-right node))
        (set! flag #t))
      (loop)))
  (not flag))

(define (complete-binary-tree-inserter root)
  (define lst '())
  (define (inorder node)
    (when node
      (inorder (node-left node))
      (set! lst (cons node lst))
      (inorder (node-right node))))
  (inorder root)
  (define idx 0)
  (define (get-parent i)
    (quotient (1- i) 2))
  (define (get-left i)
    (+ (* 2 i) 1))
  (define (get-right i)
    (+ (* 2 i) 2))
  (define (insert val)
    (define new-node (make-node val #f #f))
    (when (= idx 0)
      (set! lst (cons new-node lst))
      (set! idx 1)
      new-node)
    (let loop ()
      (define i (- idx 1))
      (define parent (list-ref lst i))
      (if (not (node-left parent))
          (begin
            (set-node-left! parent new-node)
            (set! lst (append lst (list new-node)))
            (set! idx (+ idx 1))
            new-node)
          (if (not (node-right parent))
              (begin
                (set-node-right! parent new-node)
                (set! lst (append lst (list new-node)))
                (set! idx (+ idx 1))
                new-node)
              (begin
                (set! idx (+ idx 1))
                (loop)))))
    new-node)
  (define (is-complete)
    (is-complete-binary-tree (car lst)))
  (lambda (x) (if (eqv? x 'insert) insert (if (eqv? x 'is-complete) is-complete #f))))