(define (min-area-rectangle points)
  (define point-set (list->set points))
  (define (contains? p) (set-member? point-set p))
  (define (distance-squared p1 p2)
    (+ (expt (- (car p1) (car p2)) 2) (expt (- (cadr p1) (cadr p2)) 2)))
  (let loop ([i 0] [min-area #f])
    (if (= i (length points))
        (if min-area min-area #f)
        (let ([p1 (list-ref points i)])
          (loop (+ i 1)
                (let ([current-min min-area])
                  (let loop2 ([j (+ i 1)])
                    (if (= j (length points))
                        current-min
                        (let ([p2 (list-ref points j)])
                          (let ([d (distance-squared p1 p2)])
                            (if (and (not (= d 0))
                                     (contains? (list (- (car p1) (car p2)) (- (cadr p1) (cadr p2))))
                                     (contains? (list (+ (car p1) (car p2)) (+ (cadr p1) (cadr p2)))))
                                (let ([area (* (abs (- (car p1) (car p2))) (abs (- (cadr p1) (cadr p2))))])
                                  (loop2 (+ j 1) (if (or (not current-min) (< area current-min)) area current-min)))
                                (loop2 (+ j 1) current-min)))))))))))