(define (valid-mountain-array arr)
  (define n (length arr))
  (when (< n 3) #f)
  (define i 0)
  (let loop ()
    (when (< i (- n 1))
      (when (< (list-ref arr i) (list-ref arr (+ i 1)))
        (set! i (+ i 1))
        (loop))))
  (if (= i (- n 1)) #f #t)
  (define j (- n 1))
  (let loop2 ()
    (when (> j 0)
      (when (< (list-ref arr j) (list-ref arr (- j 1)))
        (set! j (- j 1))
        (loop2))))
  (and (= i j) (> i 0) (< i (- n 1))))