(define (can-construct-array nums)
  (define freq (make-hash))
  (for-each (lambda (n) (hash-update! freq n add1 0)) nums)
  (define sorted (sort (hash-keys freq) <))
  (for/and ([n sorted])
    (if (even? n)
        (let ([count (hash-ref freq n)])
          (if (>= (hash-ref freq (* 2 n) 0) count)
              (begin
                (hash-set! freq (* 2 n) (- (hash-ref freq (* 2 n)) count))
                #t)
              #f))
        #t)))
  (for/and ([n sorted])
    (if (even? n)
        (let ([count (hash-ref freq n)])
          (if (>= (hash-ref freq (* 2 n) 0) count)
              (begin
                (hash-set! freq (* 2 n) (- (hash-ref freq (* 2 n)) count))
                #t)
              #f))
        #t)))

(define (can-reorder-doubled nums)
  (define freq (make-hash))
  (for-each (lambda (n) (hash-update! freq n add1 0)) nums)
  (define sorted (sort (hash-keys freq) <))
  (for/and ([n sorted])
    (if (even? n)
        (let ([count (hash-ref freq n)])
          (if (>= (hash-ref freq (* 2 n) 0) count)
              (begin
                (hash-set! freq (* 2 n) (- (hash-ref freq (* 2 n)) count))
                #t)
              #f))
        #t)))
  (for/and ([n sorted])
    (if (even? n)
        (let ([count (hash-ref freq n)])
          (if (>= (hash-ref freq (* 2 n) 0) count)
              (begin
                (hash-set! freq (* 2 n) (- (hash-ref freq (* 2 n)) count))
                #t)
              #f))
        #t)))

(define (can-reorder-doubled nums)
  (define freq (make-hash))
  (for-each (lambda (n) (hash-update! freq n add1 0)) nums)
  (define sorted (sort (hash-keys freq) <))
  (for/and ([n sorted])
    (if (even? n)
        (let ([count (hash-ref freq n)])
          (if (>= (hash-ref freq (* 2 n) 0) count)
              (begin
                (hash-set! freq (* 2 n) (- (hash-ref freq (* 2 n)) count))
                #t)
              #f))
        #t)))

(define (can-reorder-doubled nums)
  (define freq (make-hash))
  (for-each (lambda (n) (hash-update! freq n add1 0)) nums)
  (define sorted (sort (hash-keys freq) <))
  (for/and ([n sorted])
    (if (even? n)
        (let ([count (hash-ref freq n)])
          (if (>= (hash-ref freq (* 2 n) 0) count)
              (begin
                (hash-set! freq (* 2 n) (- (hash-ref freq (* 2 n)) count))
                #t)
              #f))
        #t)))

(define (can-reorder-doubled nums)
  (define freq (make-hash))
  (for-each (lambda (n) (hash-update! freq n add1 0)) nums)
  (define sorted (sort (hash-keys freq) <))
  (for/and ([n sorted])
    (if (even? n)
        (let ([count (hash-ref freq n)])
          (if (>= (hash-ref freq (* 2 n) 0) count)
              (begin
                (hash-set! freq (* 2 n) (- (hash-ref freq (* 2 n)) count))
                #t)
              #f))
        #t)))

(define (can-reorder-doubled nums)
  (define freq (make-hash))
  (for-each (lambda (n) (hash-update! freq n add1 0)) nums)
  (define sorted (sort (hash-keys freq) <))
  (for/and ([n sorted])
    (if (even? n)
        (let ([count (hash-ref freq n)])
          (if (>= (hash-ref freq (* 2 n) 0) count)
              (begin
                (hash-set! freq (* 2 n) (- (hash-ref freq (* 2 n)) count))
                #t)
              #f))
        #t)))

(define (can-reorder-doubled nums)
  (define freq (make-hash))
  (for-each (lambda (n) (hash-update! freq n add1 0)) nums)
  (define sorted (sort (hash-keys freq) <))
  (for/and ([n sorted])
    (if (even? n)
        (let ([count (hash-ref freq n)])
          (if (>= (hash-ref freq (* 2 n) 0) count)
              (begin
                (hash-set! freq (* 2 n) (- (hash-ref freq (* 2 n)) count))
                #t)
              #f))
        #t)))

(define (can-reorder-doubled nums)
  (define freq (make-hash))
  (for-each (lambda (n) (hash-update! freq n add1 0)) nums)
  (define sorted (sort (hash-keys freq) <))
  (for/and ([n sorted])
    (if (even? n)
        (let ([count (hash-ref freq n)])
          (if (>= (hash-ref freq (* 2 n) 0) count)
              (begin
                (hash-set! freq (* 2 n) (- (hash-ref freq (* 2 n)) count))
                #t)
              #f))
        #t)))

(define (can-reorder-doubled nums)
  (define freq (make-hash))
  (for-each (lambda (n) (hash-update! freq n add1 0)) nums)
  (define sorted (sort (hash-keys freq) <))
  (for/and ([n sorted])
    (if (even? n)
        (let ([count (hash-ref freq n)])
          (if (>= (hash-ref freq (* 2 n) 0) count)
              (begin
                (hash-set! freq (* 2 n) (- (hash-ref freq (* 2 n)) count))
                #t)
              #f))
        #t)))

(define (can-reorder-doubled nums)
  (define freq (make-hash))
  (for-each (lambda (n) (hash-update! freq n add1 0)) nums)
  (define sorted (sort (hash-keys freq) <))
  (for/and ([n sorted])
    (if (even? n)
        (let ([count (hash-ref freq n)])
          (if (>= (hash-ref freq (* 2 n) 0) count)
              (begin
                (hash-set! freq (* 2 n) (- (hash-ref freq (* 2 n)) count))
                #t)
              #f))
        #t)))

(define (can-reorder-doubled nums)
  (define freq (make-hash))
  (for-each (lambda (n) (hash-update! freq n add1 0)) nums)
  (define sorted (sort (hash-keys freq) <))
  (for/and ([n sorted])
    (if (even? n)
        (let ([count (hash-ref freq n)])
          (if (>= (hash-ref freq (* 2 n) 0) count)
              (begin
                (hash-set! freq (* 2 n) (- (hash-ref freq (* 2 n)) count))
                #t)
              #f))
        #t)))

(define (can-reorder-doubled nums)
  (define freq (make-hash))
  (for-each (lambda (n) (hash-update! freq n add1 0)) nums)
  (define sorted (sort (hash-keys freq) <))
  (for/and ([n sorted])
    (if (even? n)
        (let ([count (hash-ref freq n)])
          (if (>= (hash-ref freq (* 2 n) 0) count)
              (begin
                (hash-set! freq (* 2 n) (- (hash-ref freq (* 2 n)) count))
                #t)
              #f))
        #t)))

(define (can-reorder-doubled nums)
  (define freq (make-hash))
  (for-each (lambda (n) (hash-update! freq n add1 0)) nums)
  (define sorted (sort (hash-keys freq) <))
  (for/and ([n sorted])
    (if (even? n)
        (let ([count (hash-ref freq n)])
          (if (>= (hash-ref freq (* 2 n) 0) count)
              (begin
                (hash-set! freq (* 2 n) (- (hash-ref freq (* 2 n)) count))
                #t)
              #f))
        #t)))

(define (can-reorder-d