(define (delete-columns-to-make-sorted strs)
  (define n (length strs))
  (define m (if (> n 0) (string-length (car strs)) 0))
  (define cols (make-vector m #t))
  (for ([i (in-range m)])
    (for ([j (in-range 1 n)])
      (when (char<? (string-ref (list-ref strs (- j 1)) i)
                    (string-ref (list-ref strs j) i))
        (vector-set! cols i #f))))
  (for/sum ([c cols] #:when c) 1))