#lang racket

(define (regions-cutter grid)
  (define n (length grid))
  (define size (* n 3))
  (define parent (make-vector (* size size) 0))
  (define (find x) (if (= (vector-ref parent x) x) x (find (vector-ref parent x))))
  (define (union x y) (vector-set! parent (find x) (find y)))
  (for ([i (in-range size)])
    (vector-set! parent i i))
  (for ([i (in-range size)])
    (when (< i (- size 1)) (union i (+ i 1)))
    (when (< i (- size 1 3)) (union i (+ i 3))))
  (for ([r (in-range n)])
    (for ([c (in-range n)])
      (when (equal? (list-ref (list-ref grid r) c) #\/)
        (let ([a (+ (* r 3) c)]
              [b (+ (* (+ r 1) 3) (+ c 1))])
          (union a b)))
      (when (equal? (list-ref (list-ref grid r) c) #\|)
        (let ([a (+ (* r 3) (+ c 1))]
              [b (+ (* (+ r 1) 3) c)])
          (union a b)))))
  (define (count-roots)
    (define roots (set))
    (for ([i (in-range size)])
      (set-add! roots (find i)))
    (set-count roots))
  (count-roots))