(define (subarrays-div-by-k nums k)
  (let ((prefix-remainders (make-hash))
        (count 0)
        (current-sum 0))
    (hash-set! prefix-remainders 0 1)
    (for-each
     (lambda (num)
       (set! current-sum (+ current-sum num))
       (let ((remainder (modulo current-sum k)))
         (when (< remainder 0)
           (set! remainder (+ remainder k)))
         (let ((freq (hash-ref prefix-remainders remainder 0)))
           (set! count (+ count freq))
           (hash-set! prefix-remainders remainder (+ freq 1)))))
     nums)
    count))