(define (distribute-coins root)
  (define (dfs node)
    (if (not node)
        (values 0 0)
        (let* ((left-coins left-amount) (left-steps left-steps)
               (right-coins right-amount) (right-steps right-steps))
          (let ((total-coins (+ (node-val node) left-coins right-coins))
                (total-steps (+ left-steps right-steps (abs left-amount) (abs right-amount))))
            (values total-coins total-steps))))
  (let ((_, steps) (dfs root))
    steps))