(define (cyclist-competition positions)
  (let ((n (length positions)))
    (define (distance x y)
      (abs (- x y)))
    (define (compare a b)
      (let ((d1 (distance (car a) (cadr a)))
            (d2 (distance (car b) (cadr b))))
        (if (= d1 d2)
            (if (< (caddr a) (caddr b)) -1 1)
            (if (< d1 d2) -1 1))))
    (define sorted (sort (map (lambda (i) (list (list-ref positions i) i)) (range n)) compare))
    (map cadr sorted)))