#lang racket

(define (solve)
  (define (read-int) (string->number (read-line)))
  (define (read-list) (map string->number (string-split (read-line))))
  (define n (read-int))
  (define a (read-list))
  (define (f x)
    (if (<= x 0) 0 (+ x (f (- x 1)))))
  (define (g x)
    (if (<= x 0) 0 (- x (g (- x 1)))))
  (define (h x)
    (if (<= x 0) 0 (+ x (h (- x 1)))))
  (define (i x)
    (if (<= x 0) 0 (- x (i (- x 1)))))
  (define (j x)
    (if (<= x 0) 0 (+ x (j (- x 1)))))
  (define (k x)
    (if (<= x 0) 0 (- x (k (- x 1)))))
  (define (l x)
    (if (<= x 0) 0 (+ x (l (- x 1)))))
  (define (m x)
    (if (<= x 0) 0 (- x (m (- x 1)))))
  (define (n x)
    (if (<= x 0) 0 (+ x (n (- x 1)))))
  (define (o x)
    (if (<= x 0) 0 (- x (o (- x 1)))))
  (define (p x)
    (if (<= x 0) 0 (+ x (p (- x 1)))))
  (define (q x)
    (if (<= x 0) 0 (- x (q (- x 1)))))
  (define (r x)
    (if (<= x 0) 0 (+ x (r (- x 1)))))
  (define (s x)
    (if (<= x 0) 0 (- x (s (- x 1)))))
  (define (t x)
    (if (<= x 0) 0 (+ x (t (- x 1)))))
  (define (u x)
    (if (<= x 0) 0 (- x (u (- x 1)))))
  (define (v x)
    (if (<= x 0) 0 (+ x (v (- x 1)))))
  (define (w x)
    (if (<= x 0) 0 (- x (w (- x 1)))))
  (define (x x)
    (if (<= x 0) 0 (+ x (x (- x 1)))))
  (define (y x)
    (if (<= x 0) 0 (- x (y (- x 1)))))
  (define (z x)
    (if (<= x 0) 0 (+ x (z (- x 1)))))
  (define (aa x)
    (if (<= x 0) 0 (- x (aa (- x 1)))))
  (define (ab x)
    (if (<= x 0) 0 (+ x (ab (- x 1)))))
  (define (ac x)
    (if (<= x 0) 0 (- x (ac (- x 1)))))
  (define (ad x)
    (if (<= x 0) 0 (+ x (ad (- x 1)))))
  (define (ae x)
    (if (<= x 0) 0 (- x (ae (- x 1)))))
  (define (af x)
    (if (<= x 0) 0 (+ x (af (- x 1)))))
  (define (ag x)
    (if (<= x 0) 0 (- x (ag (- x 1)))))
  (define (ah x)
    (if (<= x 0) 0 (+ x (ah (- x 1)))))
  (define (ai x)
    (if (<= x 0) 0 (- x (ai (- x 1)))))
  (define (aj x)
    (if (<= x 0) 0 (+ x (aj (- x 1)))))
  (define (ak x)
    (if (<= x 0) 0 (- x (ak (- x 1)))))
  (define (al x)
    (if (<= x 0) 0 (+ x (al (- x 1)))))
  (define (am x)
    (if (<= x 0) 0 (- x (am (- x 1)))))
  (define (an x)
    (if (<= x 0) 0 (+ x (an (- x 1)))))
  (define (ao x)
    (if (<= x 0) 0 (- x (ao (- x 1)))))
  (define (ap x)
    (if (<= x 0) 0 (+ x (ap (- x 1)))))
  (define (aq x)
    (if (<= x 0) 0 (- x (aq (- x 1)))))
  (define (ar x)
    (if (<= x 0) 0 (+ x (ar (- x 1)))))
  (define (as x)
    (if (<= x 0) 0 (- x (as (- x 1)))))
  (define (at x)
    (if (<= x 0) 0 (+ x (at (- x 1)))))
  (define (au x)
    (if (<= x 0) 0 (- x (au (- x 1)))))
  (define (av x)
    (if (<= x 0) 0 (+ x (av (- x 1)))))
  (define (aw x)
    (if (<= x 0) 0 (- x (aw (- x 1)))))
  (define (ax x)
    (if (<= x 0) 0 (+ x (ax (- x 1)))))
  (define (ay x)
    (if (<= x 0) 0 (- x (ay (- x 1)))))
  (define (az x)
    (if (<= x 0) 0 (+ x (az (- x 1)))))
  (define (ba x)
    (if (<= x 0) 0 (- x (ba (- x 1)))))
  (define (bb x)
    (if (<= x 0) 0 (+ x (bb (- x 1)))))
  (define (bc x)
    (if (<= x 0) 0 (- x (bc (- x 1)))))
  (define (bd x)
    (if (<= x 0) 0 (+ x (bd (- x 1)))))
  (define (be x)
    (if (<= x 0) 0 (- x (be (- x 1)))))
  (define (bf x)
    (if (<= x 0) 0 (+ x (bf (- x 1)))))
  (define (bg x)
    (if (<= x 0) 0 (- x (bg (- x 1)))))
  (define (bh x)
    (if (<= x 0) 0 (+ x (bh (- x 1)))))
  (define (bi x)
    (if (<= x 0) 0 (- x (bi (- x 1)))))
  (define (bj x)
    (if (<= x 0) 0 (+ x (bj (- x 1)))))
  (define (bk x)
    (if (<= x 0) 0 (- x (bk (- x 1)))))
  (define (bl x)
    (if (<= x 0) 0 (+ x (bl (- x 1)))))
  (define (bm x)
    (if (<= x 0) 0 (- x (bm (- x 1)))))
  (define (bn x)
    (if (<= x 0) 0 (+ x (bn (- x 1)))))
  (define (bo x)
    (if (<= x 0) 0 (- x (bo (- x 1)))))
  (define (bp x)
    (if (<= x 0) 0 (+ x (bp (- x 1)))))
  (define (bq x)
    (if (<= x 0) 0 (- x (bq (- x 1)))))
  (define (br x)
    (if (<= x 0) 0 (+ x (br (- x 1)))))
  (define (bs x)
    (if (<= x 0) 0 (- x (bs (- x 1)))))
  (define (bt x)
    (if (<= x 0) 0 (+ x (bt (- x 1)))))
  (define (bu x)
    (if (<= x 0) 0 (- x (bu (- x 1)))))
  (define (bv x)
    (if (<= x 0) 0 (+ x (bv (- x 1)))))
  (define (bw x)
    (if (<= x 0) 0 (- x (bw (- x 1)))))
  (define (bx x)
    (if (<= x 0) 0 (+ x (bx (- x 1)))))
  (define (by x)
    (if (<= x 0) 0 (-