#lang racket

(define (escape-tower grid)
  (define rows (length grid))
  (define cols (length (car grid)))
  (define hp 1)
  (define dir (list (cons 0 1) (cons 1 0) (cons 0 -1) (cons -1 0)))
  (define (dfs x y)
    (when (and (<= 0 x (- rows 1)) (<= 0 y (- cols 1)) (>= hp 1))
      (set! hp (- hp (vector-ref (vector-ref grid x) y)))
      (when (and (<= 0 x (- rows 1)) (<= 0 y (- cols 1)) (>= hp 1))
        (for-each (lambda (d)
                    (let* ((nx (+ x (car d)))
                           (ny (+ y (cdr d))))
                      (dfs nx ny)))
                  dir))
      (set! hp (+ hp (vector-ref (vector-ref grid x) y))))
  (dfs 0 0)
  (>= hp 1))