#lang racket

(define (min-window s t)
  (define len-s (string-length s))
  (define len-t (string-length t))
  (when (or (= len-s 0) (= len-t 0) (> len-s len-t)) "")
  (define count (make-hash))
  (for ([c t])
    (hash-set! count c (+ (hash-ref count c 0) 1))
  )
  (define required (hash-count count))
  (define window (make-hash))
  (define formed 0)
  (define left 0)
  (define min-len +inf.0)
  (define result "")

  (define (add-to-window c)
    (hash-set! window c (+ (hash-ref window c 0) 1))
    (when (= (hash-ref window c 0) (hash-ref count c))
      (set! formed (+ formed 1))))

  (define (remove-from-window c)
    (hash-set! window c (- (hash-ref window c 0) 1))
    (when (= (hash-ref window c 0) (hash-ref count c))
      (set! formed (- formed 1))))

  (for ([right (in-range len-s)])
    (define c (string-ref s right))
    (add-to-window c)
    (while (and (>= formed required) (< left right))
      (define current-substring (substring s left (+ right 1)))
      (when (< (string-length current-substring) min-len)
        (set! min-len (string-length current-substring))
        (set! result current-substring))
      (define left-c (string-ref s left))
      (remove-from-window left-c)
      (set! left (+ left 1))))
  result)