(define (add-binary a b)
  (define (char->int c)
    (- (char->integer c) (char->integer #\0)))
  (define (int->char i)
    (integer->char (+ i (char->integer #\0))))
  (define (add-helper a b carry)
    (if (and (null? a) (null? b))
        (if (= carry 0) '() (list (int->char carry)))
        (let* ((digit-a (if (null? a) 0 (car a)))
               (digit-b (if (null? b) 0 (car b)))
               (sum (+ digit-a digit-b carry))
               (new-carry (if (> sum 1) 1 0))
               (current-digit (modulo sum 2)))
          (cons (int->char current-digit)
                (add-helper (cdr a) (cdr b) new-carry)))))
  (list->string
   (reverse
    (add-helper (map char->int (string->list a))
                (map char->int (string->list b))
                0))))