(define (subarray-sum nums k)
  (define count 0)
  (define prefix-sum 0)
  (define sum-count (make-hash))
  (hash-set! sum-count 0 1)
  (for-each
   (lambda (num)
     (set! prefix-sum (+ prefix-sum num))
     (let ((target (- prefix-sum k)))
       (when (hash-has-key? sum-count target)
         (set! count (+ count (hash-ref sum-count target)))))
     (hash-update! sum-count prefix-sum add1 0))
   nums)
  count)