(define (combination-sum4 nums target)
  (define memo (make-hash))
  (define (dp n)
    (if (hash-has-key? memo n)
        (hash-ref memo n)
        (let ((res 0))
          (for-each (lambda (num)
                      (when (<= num n)
                        (set! res (+ res (if (= (- n num) 0)
                                            1
                                            (dp (- n num)))))))
                    nums)
          (hash-set! memo n res)
          res)))
  (dp target))