(define (divide dividend divisor)
  (define (abs x)
    (if (< x 0) (- x) x))
  (define (sign x y)
    (if (or (and (> x 0) (> y 0)) (and (< x 0) (< y 0))) 1 -1))
  (define (helper a b)
    (let loop ((count 0) (current b))
      (if (> current a)
          count
          (loop (+ count 1) (* current 2)))))
  (if (and (= dividend 0) (= divisor 0))
      0
      (let* ((a (abs dividend))
             (b (abs divisor))
             (s (sign dividend divisor))
             (quotient (if (>= a b)
                           (helper a b)
                           0)))
        (if (> quotient (expt 2 31))
            (if (> s 0) (expt 2 31) (- (expt 2 31)))
            (* s quotient))))
  )