(define (attack-division-II attacks)
  (define (dfs path index)
    (if (= index (length attacks))
        (list path)
        (append (dfs (append path (list (list-ref attacks index))) (+ index 1))
                (if (and (not (null? path)) (= (last path) (list-ref attacks index)))
                    '()
                    (dfs path (+ index 1))))))
  (apply append (map (lambda (i) (dfs (list (list-ref attacks i)) (+ i 1))) (range (length attacks)))))