(define (minimum-length-string-encoding-words words)
  (define (suffix? s t)
    (and (>= (string-length t) (string-length s))
         (equal? s (substring t (- (string-length t) (string-length s))))))
  (define (remove-suffixes words)
    (let loop ([words words] [result '()])
      (if (null? words)
          result
          (let ([word (car words)])
            (if (any (lambda (w) (suffix? word w)) result)
                (loop (cdr words) result)
                (loop (cdr words) (cons word result))))))
  (define sorted-words (sort words string>))
  (let ([filtered (remove-suffixes sorted-words)])
    (apply + (map string-length filtered))))