(define (len-longest-fib-subseq nums)
  (define dp (make-hash))
  (define n (length nums))
  (define result 2)
  (for ([i (in-range n)])
    (for ([j (in-range i)])
      (define prev (- (list-ref nums i) (list-ref nums j)))
      (when (hash-has-key? dp prev)
        (define cnt (hash-ref dp prev (lambda () 0)))
        (hash-set! dp (cons (list-ref nums j) (list-ref nums i)) (+ cnt 1))
        (set! result (max result (+ cnt 1)))))
  result)