(define (remove-nth-from-end head n)
  (define (get-length node)
    (if (null? node)
        0
        (+ 1 (get-length (cdr node)))))
  (define len (get-length head))
  (define target (- len n))
  (define (remove node idx)
    (if (null? node)
        null
        (if (= idx 0)
            (cdr node)
            (cons (car node) (remove (cdr node) (- idx 1))))))
  (if (= target 0)
      (cdr head)
      (remove head target)))