(define (make-ordered-set)
  (let ((elements '())
        (index-map (make-hash)))
    (define (insert val)
      (if (hash-has-key? index-map val)
          #f
          (begin
            (set! elements (cons val elements))
            (hash-set! index-map val (length elements))
            #t)))
    (define (delete val)
      (if (not (hash-has-key? index-map val))
          #f
          (begin
            (let ((index (hash-ref index-map val)))
              (let ((last-val (car (reverse elements))))
                (set! elements (append (take elements index) (drop elements (+ index 1))))
                (hash-set! index-map last-val index)
                (hash-remove! index-map val))
            #t)))
    (define (get-random)
      (list-ref elements (random (length elements))))
    (lambda (op . args)
      (cond ((eq? op 'insert) (insert (car args)))
            ((eq? op 'delete) (delete (car args)))
            ((eq? op 'get-random) (get-random)))))

(define (main)
  (let ((obj (make-ordered-set)))
    (display (obj 'insert 1))
    (newline)
    (display (obj 'insert 2))
    (newline)
    (display (obj 'insert 3))
    (newline)
    (display (obj 'delete 2))
    (newline)
    (display (obj 'get-random))
    (newline)
    (display (obj 'delete 1))
    (newline)
    (display (obj 'get-random))
    (newline)))