(define (merge-intervals intervals)
  (if (null? intervals)
      '()
      (let* ((sorted (sort intervals (lambda (a b) (< (car a) (car b)))))
             (result (list (car sorted))))
        (for-each
         (lambda (interval)
           (let* ((last (car result))
                  (last-end (cadr last))
                  (current-start (car interval))
                  (current-end (cadr interval)))
             (if (<= current-start last-end)
                 (set-car! result (list (car last) (max last-end current-end)))
                 (set! result (append result (list interval))))))
         (cdr sorted))
        result)))