#lang racket

(define (restore-ip-addresses s)
  (define (is-valid? part)
    (and (not (string=? "" part))
         (or (<= (string-length part) 3)
             (and (char=? #\0 (string-ref part 0))
                  (= (string-length part) 1))))
    (and (<= (string->number part) 255)))
  (define (backtrack start parts result)
    (if (= (length parts) 4)
        (if (= (length s) start)
            (set! result (cons (string-join parts ".") result))
            #f)
        (for ([i (in-range (min (+ start 3) (string-length s)) (max start 0) -1)])
          (define part (substring s start i))
          (when (is-valid? part)
            (backtrack i (append parts (list part)) result)))))
  (define result '())
  (backtrack 0 '() result)
  result)