(define (find-colors colors)
  (define (count-colors lst)
    (let loop ((lst lst) (acc '()))
      (if (null? lst)
          acc
          (loop (cdr lst) (cons (car lst) acc)))))
  (define (get-max-count lst)
    (let loop ((lst lst) (max 0) (color ""))
      (if (null? lst)
          (cons max color)
          (let ((current (car lst)))
            (if (> (cadr current) max)
                (loop (cdr lst) (cadr current) (car current))
                (loop (cdr lst) max color))))))
  (define (get-second-max lst)
    (let loop ((lst lst) (max1 0) (color1 "") (max2 0) (color2 ""))
      (if (null? lst)
          (cons max2 color2)
          (let ((current (car lst)))
            (if (> (cadr current) max1)
                (loop (cdr lst) (cadr current) (car current) max1 color1)
                (if (and (> (cadr current) max2) (not (= (cadr current) max1)))
                    (loop (cdr lst) max1 color1 (cadr current) (car current))
                    (loop (cdr lst) max1 color1 max2 color2)))))))
  (let* ((counts (count-colors colors))
         (freq (map (lambda (x) (cons x (length (filter (lambda (y) (= y x)) colors)))) counts))
         (sorted (sort freq (lambda (a b) (> (cdr a) (cdr b)))))
         (max1 (get-max-count sorted))
         (max2 (get-second-max sorted)))
    (if (and (not (equal? (car max1) (car max2))) (> (cdr max1) 0) (> (cdr max2) 0))
        (list (car max1) (car max2))
        '())))

(define (main)
  (let ((input (read)))
    (display (find-colors input))))

(main)