(define/contract (minimumTotal triangle)
  (-> (listof (listof exact-integer?)) exact-integer?)
  (let loop ([i (sub1 (length triangle))] [prev-row (last triangle)])
    (if (< i 0)
        (car prev-row)
        (let ([current-row (list-ref triangle i)])
          (loop (sub1 i)
                (for/list ([j (in-range (length current-row))])
                  (+ (list-ref current-row j)
                     (min (list-ref prev-row j)
                          (list-ref prev-row (add1 j)))))))))