(define (max-size-slices slices)
  (define n (quotient (length slices) 3))
  (define (solve lst k)
    (define m (length lst))
    (define dp (make-vector (add1 m) (make-vector (add1 k) 0)))
    (for ([i (in-range 1 (add1 m))])
      (for ([j (in-range 1 (add1 k))])
        (if (<= i 2)
            (vector-set! (vector-ref dp i) j (max (vector-ref (vector-ref dp (sub1 i)) j) (list-ref lst (sub1 i))))
            (vector-set! (vector-ref dp i) j (max (vector-ref (vector-ref dp (sub1 i)) j) 
                                               (+ (vector-ref (vector-ref dp (- i 2)) (sub1 j)) (list-ref lst (sub1 i)))))))
    (vector-ref (vector-ref dp m) k))
  (max (solve (take slices (sub1 (length slices))) n) 
       (solve (cdr slices) n)))