(define/contract (find-min nums)
  (-> (listof exact-integer?) exact-integer?)
  (let loop ([left 0] [right (sub1 (length nums))])
    (if (< left right)
        (let ([mid (quotient (+ left right) 2)])
          (if (> (list-ref nums mid) (list-ref nums right))
              (loop (add1 mid) right)
              (loop left mid)))
        )
        (list-ref nums left))
  )
)