(define (min-insertions s)
  (let loop ([i 0] [left 0] [res 0])
    (if (= i (string-length s))
        (+ res (* 2 left))
        (let ([c (string-ref s i)])
          (if (char=? c #\()
              (loop (+ i 1) (+ left 1) res)
              (if (and (< i (- (string-length s) 1)) (char=? (string-ref s (+ i 1)) #\)))
                  (loop (+ i 2) (max (- left 1) 0) (if (> left 0) res (+ res 1)))
                  (loop (+ i 1) (max (- left 1) 0) (if (> left 0) (+ res 1) (+ res 2)))))))))