(define (modify-string s)
  (define (get-char prev next)
    (let loop ((c #\a))
      (if (or (equal? c prev) (equal? c next))
          (loop (integer->char (+ (char->integer c) 1)))
          c)))
  (define chars (string->list s))
  (define len (length chars))
  (define (helper i prev)
    (if (>= i len)
        (list->string chars)
        (let ((current (list-ref chars i)))
          (if (equal? current #\?)
              (let ((next (if (< (+ i 1) len)
                              (list-ref chars (+ i 1))
                              #\nul)))
                (let ((new-char (get-char prev next)))
                  (list-set! chars i new-char)
                  (helper (+ i 1) new-char)))
              (helper (+ i 1) current))))))
  (helper 0 #\nul))