(define/contract (total-money n)
  (-> exact-integer? exact-integer?)
  (let loop ([day 1] [current 1] [sum 0] [week 0])
    (if (> day n)
        sum
        (loop (add1 day)
              (if (= (modulo day 7) 1)
                  (add1 week)
                  (add1 current))
              (+ sum (if (= (modulo day 7) 1)
                        (add1 week)
                        current))
              (if (= (modulo day 7) 1)
                  (add1 week)
                  week)))))