(define (first-day-where-you-have-been-in-all-the-rooms next-visit)
  (define n (vector-length next-visit))
  (define dp (make-vector n 0))
  (define mod 1000000007)
  (vector-set! dp 0 2)
  (for ([i (in-range 1 n)])
    (define prev (vector-ref dp (- i 1)))
    (define next (vector-ref next-visit i))
    (define val (+ prev 1 (if (= next i) 0 (vector-ref dp (- i 1))) (- (vector-ref dp next) next) 1)))
    (vector-set! dp i (modulo (+ prev val) mod)))
  (modulo (vector-ref dp (- n 1)) mod))