(define (cells-in-range s)
  (let* ((parts (string-split s ":"))
         (c1 (string-ref (first parts) 0))
         (r1 (string-ref (first parts) 1))
         (c2 (string-ref (second parts) 0))
         (r2 (string-ref (second parts) 1))
         (result '()))
    (for ((col (in-range (char->integer c1) (add1 (char->integer c2)))))
      (for ((row (in-range (char->integer r1) (add1 (char->integer r2)))))
        (set! result (cons (format "~a~a" (integer->char col) (integer->char row)) result))))
    (reverse result)))