(define/contract (find-kdistant-indices nums k key)
  (-> (listof exact-integer?) exact-integer? (listof exact-integer?) (listof exact-integer?))
  (define key-indices (filter (lambda (i) (member (list-ref nums i) key)) (range (length nums))))
  (define result (mutable-set))
  (for ([i (in-range (length nums))])
    (for ([j (in-list key-indices)])
      (when (<= (abs (- i j)) k)
        (set-add! result i))))
  (sort (set->list result) <))