(define/contract (largest-combination candidates)
  (-> (listof exact-integer?) exact-integer?)
  (define max-bit 0)
  (for ([i (in-range 0 24)])
    (define cnt 0)
    (for ([num (in-list candidates)])
      (when (> (bitwise-and num (arithmetic-shift 1 i)) 0)
        (set! cnt (add1 cnt))))
    (set! max-bit (max max-bit cnt)))
  max-bit)