(define (is-strictly-palindromic n)
  (define (convert-base num base)
    (if (zero? num)
        '()
        (cons (remainder num base) (convert-base (quotient num base) base))))
  (define (is-palindrome? lst)
    (equal? lst (reverse lst)))
  (for/and ([base (in-range 2 (- n 1))])
    (is-palindrome? (convert-base n base))))