(define/contract (partition-string s)
  (-> string? exact-integer?)
  (define seen (make-hash))
  (define count 1)
  (for ([char (in-string s)])
    (when (hash-has-key? seen char)
      (set! count (add1 count))
      (set! seen (make-hash)))
    (hash-set! seen char #t))
  count)