(define/contract (unequal-triplets nums)
  (-> (listof exact-integer?) exact-integer?)
  (let loop ([i 0] [count 0])
    (if (>= i (- (length nums) 2))
        count
        (let loop2 ([j (+ i 1)] [count count])
          (if (>= j (- (length nums) 1))
              (loop (+ i 1) count)
              (let loop3 ([k (+ j 1)] [count count])
                (if (>= k (length nums))
                    (loop2 (+ j 1) count)
                    (if (and (not (= (list-ref nums i) (list-ref nums j)))
                             (not (= (list-ref nums i) (list-ref nums k)))
                             (not (= (list-ref nums j) (list-ref nums k))))
                          (loop3 (+ k 1) (+ count 1))
                          (loop3 (+ k 1) count))))))))