(define/contract (maximum-jumps nums target)
  (-> (listof exact-integer?) exact-integer? exact-integer?)
  (let ([n (length nums)])
    (let loop ([i 0] [jumps (make-vector n -1)])
      (if (= i (- n 1))
          (max 0 (vector-ref jumps (- n 1)))
          (if (>= (vector-ref jumps i) 0)
              (loop (+ i 1) jumps)
              (let ([max-jumps -1])
                (for ([k (in-range (+ i 1) n])
                  (when (and (<= (abs (- (list-ref nums k) (list-ref nums i))) target)
                             (>= (vector-ref jumps k) 0))
                    (set! max-jumps (max max-jumps (+ (vector-ref jumps k) 1)))))
                (vector-set! jumps i max-jumps)
                (loop (+ i 1) jumps))))))