(define (count-complete-subarrays nums)
  (define total-distinct (set-count (list->set nums)))
  (define n (length nums))
  (define count 0)
  (for ([i (in-range n)])
    (define distinct (mutable-set))
    (for ([j (in-range i n)])
      (set-add! distinct (list-ref nums j))
      (when (= (set-count distinct) total-distinct)
        (set! count (add1 count)))))
  count)