(define (min-absolute-difference nums x)
  (define n (length nums))
  (define min-diff +inf.0)
  (for ([i (in-range n)])
    (for ([j (in-range (+ i x) n)])
      (define diff (abs (- (list-ref nums i) (list-ref nums j))))
      (when (< diff min-diff)
        (set! min-diff diff)))
  (if (= min-diff +inf.0) -1 min-diff))