(define/contract (minimum-operations nums)
  (-> (listof exact-integer?) exact-integer?)
  (define n (length nums))
  (define dp (make-vector n (vector 0 0 0)))
  (for ([i (in-range n)])
    (define num (list-ref nums i))
    (define prev (if (= i 0) (vector 0 0 0) (vector-ref dp (- i 1))))
    (define curr (make-vector 3 0))
    (for ([j (in-range 3)])
      (define min-cost +inf.0)
      (for ([k (in-range (+ j 1))])
        (set! min-cost (min min-cost (vector-ref prev k))))
      (vector-set! curr j (+ min-cost (if (= j (- num 1)) 0 1)))
    (vector-set! dp i curr)
  (define last (vector-ref dp (- n 1)))
  (min (vector-ref last 0) (vector-ref last 1) (vector-ref last 2)))