(define (rename-columns data)
  (map (lambda (row)
         (let loop ([i 0] [new-row '()] [rest-row row])
           (if (null? rest-row)
               (reverse new-row)
               (loop (add1 i)
                     (cons (string-append (car rest-row) "_" (number->string i)) new-row)
                     (cdr rest-row)))))
       data))