(define/contract (difference-of-sums n m)
  (-> exact-integer? exact-integer? exact-integer?)
  (define num1 0)
  (define num2 0)
  (for ([i (in-range 1 (+ n 1))])
    (if (zero? (modulo i m))
        (set! num2 (+ num2 i))
        (set! num1 (+ num1 i))))
  (- num1 num2))