(define/contract (sum-counts nums)
  (-> (listof exact-integer?) exact-integer?)
  (define n (length nums))
  (define total 0)
  (for ([i (in-range n)])
    (for ([j (in-range i n)])
      (define sub (take (drop nums i) (+ (- j i) 1)))
      (define distinct-count (length (remove-duplicates sub)))
      (set! total (+ total (* distinct-count distinct-count)))))
  total)