(define/contract (sum-counts nums)
  (-> (listof exact-integer?) exact-integer?)
  (define n (length nums))
  (define MOD 1000000007)
  (define total 0)
  (for ([i (in-range n)])
    (define distinct (mutable-set))
    (for ([j (in-range i n)])
      (set-add! distinct (list-ref nums j))
      (set! total (modulo (+ total (* (set-count distinct) (set-count distinct))) MOD)))
  total)