(define/contract (count-incremovable-subarrays nums)
  (-> (listof exact-integer?) exact-integer?)
  (define n (length nums))
  (define count 0)
  (for ([i n])
    (for ([j (in-range i n)])
      (define sub (append (take nums i) (drop nums (add1 j))))
      (define sorted (sort sub <))
      (define unique (remove-duplicates sorted))
      (when (equal? sub unique)
        (set! count (add1 count)))))
  count)