(define/contract (next-permutation nums)
  (-> (listof exact-integer?) void?)
  (define (reverse! nums start)
    (let loop ([i start] [j (sub1 (length nums))])
      (when (< i j)
        (let ([tmp (list-ref nums i)])
          (list-set! nums i (list-ref nums j))
          (list-set! nums j tmp)
          (loop (add1 i) (sub1 j))))))
  (let ([n (length nums)])
    (let loop1 ([i (sub1 n)])
      (when (>= i 1)
        (if (< (list-ref nums (sub1 i)) (list-ref nums i))
            (let ([j (let loop2 ([j (sub1 n)])
                       (if (> (list-ref nums j) (list-ref nums (sub1 i)))
                           j
                           (loop2 (sub1 j))))])
              (let ([tmp (list-ref nums (sub1 i))])
                (list-set! nums (sub1 i) (list-ref nums j))
                (list-set! nums j tmp)
                (reverse! nums i)))
            (loop1 (sub1 i)))))
    (when (= (loop1 (sub1 n)) (sub1 n))
      (reverse! nums 0))))