(define/contract (occurrences-of-element nums keys index)
  (-> (listof exact-integer?) (listof exact-integer?) exact-integer? (listof exact-integer?))
  (define indices (make-hash))
  (for ([i (in-range (length nums))])
    (hash-set! indices (list-ref nums i) 
                (cons i (hash-ref indices (list-ref nums i) '()))))
  (for/list ([k keys])
    (define lst (hash-ref indices k '()))
    (if (>= (length lst) index)
        (list-ref lst (- index 1))
        -1)))