(define (number-of-pairs nums1 nums2 k)
  (define freq (make-hash))
  (for ([num nums2])
    (define key (quotient num k))
    (hash-update! freq key add1 (lambda () 0)))
  (define count 0)
  (for ([num nums1])
    (when (zero? (modulo num k))
      (define target (quotient num k))
      (set! count (+ count (hash-ref freq target 0)))))
  count)