(define (subarray-and nums k)
  (define n (length nums))
  (define count 0)
  (for ([i (in-range n)])
    (define current-and (list-ref nums i))
    (when (= current-and k)
      (set! count (add1 count)))
    (for ([j (in-range (add1 i) n)])
      (set! current-and (bitwise-and current-and (list-ref nums j)))
      (when (= current-and k)
        (set! count (add1 count)))))
  count)