(define/contract (maximum-product nums k)
  (-> (listof exact-integer?) exact-integer? exact-integer?)
  (define (multiply lst)
    (define m (apply min lst))
    (for/list ([x lst])
      (if (= x m) (add1 x) x)))
  (let loop ([nums nums] [k k])
    (if (zero? k)
        (apply * nums)
        (loop (multiply nums) (sub1 k)))))