(define/contract (find-original-string typed)
  (-> string? string?)
  (let loop ([i 0] [res '()])
    (if (>= i (string-length typed))
        (list->string (reverse res))
        (let ([c (string-ref typed i)])
          (if (and (< i (sub1 (string-length typed)))
                  (char=? c (string-ref typed (add1 i)))
              (loop (+ i 2) (cons c res))
              (loop (add1 i) (cons c res))))))