(define (count-substrings s)
  (define n (string-length s))
  (define count 0)
  (for ([i (in-range n)])
    (define num 0)
    (for ([j (in-range i n)])
      (set! num (+ (* num 10) (- (char->integer (string-ref s j)) 48)))
      (define last-digit (modulo num 10))
      (when (and (not (zero? last-digit)) (zero? (modulo num last-digit)))
        (set! count (add1 count)))))
  count)