(define (longest-palindrome s k)
  (let* ((n (string-length s))
         (dp (make-vector (add1 n) (make-vector (add1 n) 0)))
         (ops-dp (make-vector (add1 n) (make-vector (add1 n) (make-vector (add1 k) 0)))))
    (for ([i (in-range n)])
      (vector-set! (vector-ref dp i) i 1))
    (for ([len (in-range 2 (add1 n))])
      (for ([i (in-range 0 (- (add1 n) len))])
        (let ((j (+ i len -1)))
          (if (equal? (string-ref s i) (string-ref s j))
              (vector-set! (vector-ref dp i) j (+ 2 (vector-ref (vector-ref dp (add1 i)) (- j 1))))
              (vector-set! (vector-ref dp i) j (max (vector-ref (vector-ref dp (add1 i) j)
                                                   (vector-ref (vector-ref dp i) (- j 1))))))))
    (for ([i (in-range n)])
      (for ([j (in-range n)])
        (for ([op (in-range (add1 k))])
          (if (>= i j)
              (vector-set! (vector-ref (vector-ref ops-dp i) j) op (if (= i j) 1 0))
              (let ((cost (if (equal? (string-ref s i) (string-ref s j)) 0 1)))
                (if (<= cost op)
                    (vector-set! (vector-ref (vector-ref ops-dp i) j) op
                                 (max (+ 2 (vector-ref (vector-ref (vector-ref ops-dp (add1 i)) (- j 1)) (- op cost)))
                                      (vector-ref (vector-ref (vector-ref ops-dp (add1 i)) j) op)
                                      (vector-ref (vector-ref (vector-ref ops-dp i) (- j 1)) op)))
                    (vector-set! (vector-ref (vector-ref ops-dp i) j) op
                                 (max (vector-ref (vector-ref (vector-ref ops-dp (add1 i)) j) op)
                                      (vector-ref (vector-ref (vector-ref ops-dp i) (- j 1)) op)))))))))
    (vector-ref (vector-ref (vector-ref ops-dp 0) (- n 1)) k)))