(define (make-solution head)
  (let ([nodes '()])
    (let loop ([node head])
      (when (not (null? node))
        (set! nodes (cons (car node) nodes))
        (loop (cdr node))))
    (set! nodes (reverse nodes))
    (lambda ()
      (list-ref nodes (random (length nodes))))))