(define (predict-the-winner nums)
  (let ([n (length nums)])
    (let ([dp (make-vector (* n n) 0)])
      (for ([i (in-range n)])
        (vector-set! dp (+ i (* i n)) (list-ref nums i)))
      (for ([k (in-range 1 n)])
        (for ([i (in-range (- n k))])
          (let ([j (+ i k)])
            (vector-set! dp (+ i (* j n))
                         (max (- (list-ref nums i) (vector-ref dp (+ (+ i 1) (* j n))))
                              (- (list-ref nums j) (vector-ref dp (+ i (* (- j 1) n)))))))))
      (>= (vector-ref dp (- n 1)) 0))))