(define/contract (longest-palindrome s)
  (-> string? string?)
  (define n (string-length s))
  (define (expand l r)
    (let loop ([l l] [r r])
      (if (and (>= l 0) (< r n) (char=? (string-ref s l) (string-ref s r)))
          (loop (sub1 l) (add1 r))
          (substring s (add1 l) r))))
  (define res "")
  (for ([i (in-range n)])
    (define s1 (expand i i))
    (define s2 (if (< i (sub1 n)) (expand i (add1 i)) ""))
    (when (> (string-length s1) (string-length res))
      (set! res s1))
    (when (> (string-length s2) (string-length res))
      (set! res s2)))
  res)