(define (find-words words)
  (define (in-row? word rows)
    (for/or ([row rows])
      (for/and ([c (string->list (string-downcase word))])
        (string-contains? row (string c)))))
  (define row1 "qwertyuiop")
  (define row2 "asdfghjkl")
  (define row3 "zxcvbnm")
  (filter (lambda (word) (in-row? word (list row1 row2 row3))) words))