(define (get-permutation n k)
  (let* ((nums (build-list n (lambda (i) (+ i 1))))
         (fact (make-vector (+ n 1) 1)))
    (for ([i (in-range 2 (+ n 1))])
      (vector-set! fact i (* (vector-ref fact (- i 1)) i)))
    (let loop ((nums nums)
               (k (- k 1))
               (res '()))
      (if (null? nums)
          (list->string (map (lambda (x) (integer->char (+ x 48))) res))
          (let* ((m (length nums))
                 (f (vector-ref fact (- m 1)))
                 (i (quotient k f))
                 (num (list-ref nums i)))
            (loop (append (take nums i) (drop nums (+ i 1)))
                  (remainder k f)
                  (cons num res)))))))