(define (shopping-offer price special needs)
  (define (helper needs)
    (define (direct-price needs)
      (for/sum ([p price] [n needs]) (* p n)))
    (define min-cost (direct-price needs))
    (for ([s special])
      (define new-needs (for/list ([n needs] [s-item (car s)])
                         (if (>= n s-item) (- n s-item) -1))
      (when (not (member -1 new-needs))
        (set! min-cost (min min-cost (+ (cadr s) (helper new-needs))))))
    min-cost)
  (helper needs))