(define/contract (find-length nums1 nums2)
  (-> (listof exact-integer?) (listof exact-integer?) exact-integer?)
  (define m (length nums1))
  (define n (length nums2))
  (define dp (make-vector (add1 m) (make-vector (add1 n) 0)))
  (define max-len 0)
  (for ([i (in-range 1 (add1 m))])
    (for ([j (in-range 1 (add1 n))])
      (if (= (list-ref nums1 (sub1 i)) (list-ref nums2 (sub1 j)))
          (begin
            (vector-set! (vector-ref dp i) j (add1 (vector-ref (vector-ref dp (sub1 i)) (sub1 j))))
            (set! max-len (max max-len (vector-ref (vector-ref dp i) j))))
          (vector-set! (vector-ref dp i) j 0))))
  max-len)