(define/contract (all-paths-source-target graph)
  (-> (listof (listof exact-integer?)) (listof (listof exact-integer?)))
  (define n (length graph))
  (define result '())
  (define (dfs node path)
    (if (= node (- n 1))
        (set! result (cons (reverse path) result))
        (for ([neighbor (list-ref graph node)])
          (dfs neighbor (cons neighbor path)))))
  (dfs 0 '(0))
  (reverse result))