(define/contract (has-groups-size-x deck)
  (-> (listof exact-integer?) boolean?)
  (let* ((counts (make-hash))
         (gcd-val 0))
    (for ([card deck])
      (hash-update! counts card add1 0))
    (for ([(key val) (in-hash counts)])
      (set! gcd-val (gcd gcd-val val)))
      #:break (equal? gcd-val 1))
    (>= gcd-val 2)))