(define/contract (insert-into-max-tree root val)
  (-> (or/c null? tree-node?) exact-integer? (or/c null? tree-node?))
  (if (null? root)
      (make-tree-node val null null)
      (if (> val (tree-node-val root))
          (make-tree-node val root null)
          (make-tree-node (tree-node-val root)
                          (tree-node-left root)
                          (insert-into-max-tree (tree-node-right root) val)))))