(define/contract (minimum-operations leaves)
  (-> string? exact-integer?)
  (define n (string-length leaves))
  (define dp (make-vector n (make-vector 3 +inf.0)))
  (vector-set! (vector-ref dp 0) 0 (if (char=? (string-ref leaves 0) #\y) 1 0))
  (for ([i (in-range 1 n)])
    (define current (string-ref leaves i))
    (define prev-dp (vector-ref dp (- i 1)))
    (define current-dp (vector-ref dp i))
    (vector-set! current-dp 0 (+ (vector-ref prev-dp 0) (if (char=? current #\y) 1 0)))
    (vector-set! current-dp 1 (min (vector-ref prev-dp 0) (vector-ref prev-dp 1)) (if (char=? current #\r) 1 0)))
    (vector-set! current-dp 2 (min (vector-ref prev-dp 1) (vector-ref prev-dp 2)) (if (char=? current #\y) 1 0)))
  (vector-ref (vector-ref dp (- n 1)) 2))