(define/contract (len-longest-fib-subseq arr)
  (-> (listof exact-integer?) exact-integer?)
  (define n (length arr))
  (define index (make-hash))
  (for ([i (in-range n)])
    (hash-set! index (list-ref arr i) i))
  (define dp (make-hash))
  (define ans 0)
  (for ([k (in-range n)])
    (for ([j (in-range k)])
      (define i (hash-ref index (- (list-ref arr k) (list-ref arr j)) -1))
      (when (and (>= i 0) (< i j))
        (define val (hash-ref dp (cons i j) 2))
        (hash-set! dp (cons j k) (+ val 1))
        (set! ans (max ans (hash-ref dp (cons j k))))))))
  (if (>= ans 3) ans 0))