(define (nth-ugly-number n)
  (let loop ([i 1] [count 1] [uglies (make-hash)] [min-heap (heap (λ (a b) (< a b))])
    (hash-set! uglies 1 #t)
    (heap-add! min-heap 1)
    (let ([current (heap-min min-heap)])
      (when (< count n)
        (heap-remove-min! min-heap)
        (for ([factor (in-list '(2 3 5))])
          (let ([next (* current factor)])
            (unless (hash-has-key? uglies next)
              (hash-set! uglies next #t)
              (heap-add! min-heap next))))
        (loop (add1 i) (if (= current (heap-min min-heap)) count (add1 count)) uglies min-heap))
      current)))