(define (valid-subsequence s)
  (define (helper stack c)
    (cond ((null? stack) (cons c '()))
          ((char=? (car stack) c) (cdr stack))
          (else (cons c stack))))
  (define (loop s stack)
    (if (null? s)
        (null? stack)
        (loop (cdr s) (helper stack (car s)))))
  (loop (string->list s) '()))