(define (num-enclaves grid)
  (define (dfs i j)
    (when (and (<= 0 i (- (length grid) 1))
               (<= 0 j (- (length (car grid)) 1))
               (= 1 (list-ref (list-ref grid i) j)))
      (set! (list-ref grid i) (list-set (list-ref grid i) j 0))
      (dfs (+ i 1) j)
      (dfs (- i 1) j)
      (dfs i (+ j 1))
      (dfs i (- j 1))))
  (define (count)
    (for/sum ([row grid])
      (for/sum ([cell row])
        cell)))
  (for ([i (in-range (length grid))])
    (for ([j (in-range (length (car grid)))])
      (when (or (= i 0) (= i (- (length grid) 1)) (= j 0) (= j (- (length (car grid)) 1)))
        (dfs i j))))
  (count))