(define (color-border image color)
  (define rows (length image))
  (define cols (if (> rows 0) (length (car image)) 0))
  (define visited (make-vector rows #f))
  (define new-image (map (lambda (row) (vector->list row)) image))
  (define (is-valid r c)
    (and (>= r 0) (< r rows) (>= c 0) (< c cols)))
  (define (is-border r c original-color)
    (or (not (is-valid r c))
        (not (= (list-ref (list-ref new-image r) c) original-color))))
  (define (dfs r c original-color)
    (when (and (is-valid r c) (= (list-ref (list-ref new-image r) c) original-color) (not (vector-ref visited r)))
      (vector-set! visited r #t)
      (when (or (is-border (add1 r) c original-color)
                (is-border (sub1 r) c original-color)
                (is-border r (add1 c) original-color)
                (is-border r (sub1 c) original-color))
        (set! new-image (map (lambda (i row)
                               (if (= i r)
                                   (map (lambda (j val)
                                          (if (= j c) color val))
                                        row)
                                   row))
                             (range rows)
                             new-image)))
      (dfs (add1 r) c original-color)
      (dfs (sub1 r) c original-color)
      (dfs r (add1 c) original-color)
      (dfs r (sub1 c) original-color)))
  (for-each (lambda (r)
              (when (and (is-valid r 0) (= (list-ref (list-ref new-image r) 0) (list-ref (list-ref image r) 0)))
                (dfs r 0 (list-ref (list-ref image r) 0))))
            (range rows))
  new-image)