(define (max-sum-after-partitioning arr k)
  (let ((n (length arr)))
    (let ((dp (make-vector n 0)))
      (vector-set! dp 0 (car arr))
      (for ([i (in-range 1 n)])
        (let ((max-val (vector-ref dp (- i 1))))
          (for ([j (in-range 1 (min (+ i 1) (+ k 1)))])
            (set! max-val (max max-val (list-ref arr (- i j))))
            (vector-set! dp i (max (vector-ref dp i) (+ max-val (* (vector-ref dp (- i j)) (if (> j 0) 1 0))))))))
      (vector-ref dp (- n 1)))))