#lang racket

(define (print-zero-even-odd n)
  (define zero-sem (make-semaphore 1))
  (define even-sem (make-semaphore 0))
  (define odd-sem (make-semaphore 0))
  (define (zero)
    (for ([i (in-range n)])
      (semaphore-wait zero-sem)
      (display "0")
      (if (even? i)
          (semaphore-post even-sem)
          (semaphore-post odd-sem))))
  (define (even)
    (for ([i (in-range n)])
      (semaphore-wait even-sem)
      (display (format "~a" (* 2 (add1 i))))
      (semaphore-post zero-sem)))
  (define (odd)
    (for ([i (in-range n)])
      (semaphore-wait odd-sem)
      (display (format "~a" (+ 1 (* 2 i))))
      (semaphore-post zero-sem)))
  (thread zero)
  (thread even)
  (thread odd))