(define (num-rolls-to-target n k target)
  (define mod 1000000007)
  (define dp (make-vector (+ n 1) (make-vector (+ target 1) 0)))
  (vector-set! dp 0 0 1)
  (for ([i (in-range 1 (+ n 1))])
    (for ([j (in-range 1 (+ target 1))])
      (for ([x (in-range 1 (+ k 1))])
        (when (>= (- j x) 0)
          (vector-set! dp i j (modulo (+ (vector-ref dp i j) (vector-ref dp (- i 1) (- j x))) mod))))))
  (vector-ref (vector-ref dp n) target))