(define (last-substring s)
  (define len (string-length s))
  (define-values (i j k) (values 0 1 0))
  (let loop ()
    (when (< i len)
      (when (< j len)
        (let ((a (string-ref s i))
              (b (string-ref s j)))
          (if (= a b)
              (begin
                (set! k 0)
                (let loop2 ()
                  (when (< k len)
                    (let ((a (string-ref s (+ i k)))
                          (b (string-ref s (+ j k))))
                      (if (= a b)
                          (begin
                            (set! k (+ k 1))
                            (loop2))
                          (if (> a b)
                              (set! j (+ j k))
                              (set! i (+ j k)))
                          (when (>= k len)
                            (set! i len)))))
                (loop))
              (if (> a b)
                  (set! j (+ j k))
                  (set! i (+ j k)))
              (loop)))))
    (substring s i len))
  (substring s i len))