(define (nth-ugly-number n a b c)
  (define (gcd x y)
    (if (= y 0)
        x
        (gcd y (remainder x y))))
  (define (lcm x y)
    (/ (* x y) (gcd x y)))
  (define (count-ugly x)
    (- (+ (quotient x a) (quotient x b) (quotient x c))
       (+ (quotient x (lcm a b)) (quotient x (lcm a c)) (quotient x (lcm b c)))
       (quotient x (lcm (lcm a b) c))))
  (define (binary-search low high)
    (if (> low high)
        low
        (let ((mid (quotient (+ low high) 2)))
          (if (< (count-ugly mid) n)
              (binary-search (+ mid 1) high)
              (binary-search low (- mid 1))))))
  (binary-search 1 (expt 10 18)))