#lang racket

(define-struct philosopher (id left right))
(define-struct fork (id))

(define (dining-philosophers n)
  (define forks (build-list n (lambda (i) (make-fork i))))
  (define philosophers (build-list n (lambda (i) (make-philosopher i (list-ref forks i) (list-ref forks (modulo (+ i 1) n))))))
  (define (eat p)
    (when (and (not (eq? (philosopher-left p) #f)) (not (eq? (philosopher-right p) #f)))
      (printf "Philosopher ~a is eating\n" (philosopher-id p))
      (sleep 1)
      (set! (philosopher-left p) #f)
      (set! (philosopher-right p) #f)))
  (define (take-forks p)
    (when (and (not (eq? (philosopher-left p) #f)) (not (eq? (philosopher-right p) #f)))
      (printf "Philosopher ~a is thinking\n" (philosopher-id p))
      (sleep 1)
      (set! (philosopher-left p) #f)
      (set! (philosopher-right p) #f)))
  (define (run p)
    (take-forks p)
    (eat p)
    (run p))
  (for-each thread-start! (map (lambda (p) (thread (lambda () (run p)))) philosophers))
  (void))