(define (remove-subfolders folders)
  (define (compare a b)
    (string<? (car a) (car b)))
  (define sorted (sort folders compare))
  (define (helper prev result)
    (cond ((null? prev) result)
          ((and (not (null? result))
                (string-prefix? (car result) (car prev)))
                 (helper (cdr prev) result))
          (else (helper (cdr prev) (cons (car prev) result)))))
  (reverse (helper sorted '())))