(define (max-sum-div-three nums)
  (define (sum-div-three nums)
    (let loop ((nums nums) (dp (vector 0 0 0)))
      (if (null? nums)
          (vector-ref dp 0)
          (let* ((num (car nums))
                 (new-dp (vector (max (vector-ref dp 0) (vector-ref dp (modulo (- num 0) 3))) 
                                 (max (vector-ref dp 1) (vector-ref dp (modulo (- num 1) 3))) 
                                 (max (vector-ref dp 2) (vector-ref dp (modulo (- num 2) 3)))))
                 (new-dp (vector (max (vector-ref dp 0) (+ (vector-ref dp (modulo num 3)) num))
                                 (max (vector-ref dp 1) (+ (vector-ref dp (modulo (- num 1) 3)) num))
                                 (max (vector-ref dp 2) (+ (vector-ref dp (modulo (- num 2) 3)) num)))))
            (loop (cdr nums) new-dp)))))
  (sum-div-three nums))