(define (distinct-echo-substrings s)
  (define n (string-length s))
  (define result (make-hash))
  (define (is-echo i len)
    (let ((j (+ i len)))
      (and (< j n)
           (equal? (substring s i (+ i len))
                  (substring s j (+ j len))))))
  (for ([i (in-range n)])
    (for ([len (in-range 1 (floor (/ (- n i) 2)))])
      (when (is-echo i len)
        (hash-set! result (substring s i (+ i len)) #t))))
  (hash-count result))