#lang racket

(define (min-taps n)
  (define (solve)
    (define taps (make-vector (+ n 1) 0))
    (for ([i (in-range n)])
      (define a (car (string->number (list-ref (string-split (read-line)) 0))))
      (define b (car (string->number (list-ref (string-split (read-line)) 1))))
      (vector-set! taps a (max (vector-ref taps a) b)))
    (define res 0)
    (define i 0)
    (define end 0)
    (define next-end 0)
    (while (< i n)
      (when (> i end)
        (set! res -1)
        (break))
      (set! next-end (max next-end (vector-ref taps i)))
      (when (= i end)
        (set! res (+ res 1))
        (set! end next-end))
      (set! i (+ i 1)))
    (if (<= end n) res -1))
  (solve))