(define (can-complete-circuit gas cost)
  (define n (length gas))
  (define total-tank 0)
  (define curr-tank 0)
  (define start 0)
  (for ([i (in-range n)])
    (set! total-tank (+ total-tank (- (list-ref gas i) (list-ref cost i))))
    (set! curr-tank (+ curr-tank (- (list-ref gas i) (list-ref cost i))))
    (when (< curr-tank 0)
      (set! start (add1 i))
      (set! curr-tank 0)))
  (if (>= total-tank 0) start -1))