#lang racket

(define (max-students-taking-exam seats)
  (define n (length seats))
  (define m (if (> n 0) (length (car seats)) 0))
  (define graph (make-hash))
  (define (get-adjacent i j)
    (for/fold ([adj '()]) ([dx '(-1 0 1)] [dy '(-1 0 1)])
      (when (and (not (= dx 0) (not (= dy 0)))
                 (<= 0 (+ i dx) (- n 1))
                 (<= 0 (+ j dy) (- m 1))
                 (equal? (list-ref (list-ref seats (+ i dx)) (+ j dy)) #\#))
        (set! adj (cons (cons (+ i dx) (+ j dy)) adj))))
    adj)
  (define (bipartite-match u visited match-to)
    (for/first ([v (in-list (hash-ref graph u '()))]
                #:when (not (hash-ref visited v #f)))
      (hash-set! visited v #t)
      (when (or (not (hash-has-key? match-to v))
                (bipartite-match (hash-ref match-to v) visited match-to))
        (hash-set! match-to v u)
        #t))
    #f)
  (define (max-matching)
    (define match-to (make-hash))
    (define visited (make-hash))
    (for ([i (in-range n)])
      (for ([j (in-range m)])
        (when (equal? (list-ref (list-ref seats i) j) #\#)
          (hash-set! graph (cons i j) (get-adjacent i j)))))
    (for ([u (in-hash-keys graph)])
      (hash-clear! visited)
      (when (bipartite-match u visited match-to)
        #t))
    (hash-count match-to))
  (max-matching))