#lang racket

(define (is-vowel c)
  (member c '(#\a #\e #\i #\o #\u)))

(define (find-longest-substring-containing-vowels-in-even-counts s)
  (define vowels '(#\a #\e #\i #\o #\u))
  (define state (make-hash))
  (hash-set! state 0 -1)
  (define count (vector 0 0 0 0 0))
  (define max-len 0)
  (define idx -1)
  (for ([c s])
    (set! idx (add1 idx))
    (when (member c vowels)
      (let ([i (index-of vowels c)])
        (vector-set! count i (add1 (vector-ref count i)))))
    (define key (for/vector ([i (in-range 5)])
                  (remainder (vector-ref count i) 2)))
    (define key-str (string-join (map (lambda (x) (number->string x)) (vector->list key)) ""))
    (if (hash-has-key? state key-str)
        (set! max-len (max max-len (- idx (hash-ref state key-str))))
        (hash-set! state key-str idx)))
  max-len)