(define (num-teams rating)
  (define n (length rating))
  (define res 0)
  (for ([i (in-range n)])
    (for ([j (in-range n)])
      (when (and (< i j) (< (list-ref rating i) (list-ref rating j)))
        (for ([k (in-range n)])
          (when (and (< j k) (< (list-ref rating j) (list-ref rating k)))
            (set! res (+ res 1))))))
    (for ([j (in-range n)])
      (when (and (< i j) (> (list-ref rating i) (list-ref rating j)))
        (for ([k (in-range n)])
          (when (and (< j k) (> (list-ref rating j) (list-ref rating k)))
            (set! res (+ res 1)))))))
  res)