(define (can-break s1 s2)
  (define (sorted-str str)
    (list->string (sort (string->list str) char<?)))
  (define s1-sorted (sorted-str s1))
  (define s2-sorted (sorted-str s2))
  (and (for/and ([c1 (in-string s1-sorted)] [c2 (in-string s2-sorted)])
         (char<=? c1 c2))
       (or (for/and ([c1 (in-string s1-sorted)] [c2 (in-string s2-sorted)])
             (char<=? c1 c2))
           (for/and ([c1 (in-string s2-sorted)] [c2 (in-string s1-sorted)])
             (char<=? c1 c2)))))

(define (check-if-a-string-can-break-another-string s1 s2)
  (can-break s1 s2))