(define (cherry-pickup grid)
  (define rows (length grid))
  (define cols (length (car grid)))
  (define memo (make-hash))
  (define (dp r c1 c2)
    (let ((key (format "~a-~a-~a" r c1 c2)))
      (if (hash-has-key? memo key)
          (hash-ref memo key)
          (let ((res (if (= r (- rows 1))
                         (if (= c1 c2)
                             (list-ref (list-ref grid r) c1)
                             (+ (list-ref (list-ref grid r) c1) (list-ref (list-ref grid r) c2)))
                         (let ((curr (if (= c1 c2)
                                         (list-ref (list-ref grid r) c1)
                                         (+ (list-ref (list-ref grid r) c1) (list-ref (list-ref grid r) c2)))))
                           (let loop ((max-val 0) (dc1 '(-1 0 1)) (dc2 '(-1 0 1)))
                             (if (null? dc1)
                                 max-val
                                 (let ((new-c1 (+ c1 (car dc1)))
                                       (new-c2 (+ c2 (car dc2))))
                                   (if (and (<= 0 new-c1 (sub1 cols)) (<= 0 new-c2 (sub1 cols)))
                                       (loop (max max-val (+ curr (dp (+ r 1) new-c1 new-c2))) (cdr dc1) (cdr dc2))
                                       (loop max-val (cdr dc1) (cdr dc2)))))))))
            (hash-set! memo key res)
            res))))
  (max 0 (dp 0 0 (sub1 cols))))