(define (make-rectangle-queries init)
  (let ((rect init))
    (lambda (query)
      (let ((row1 (car query))
            (col1 (cadr query))
            (row2 (caddr query))
            (col2 (cadddr query)))
        (for*/fold ((sum 0))
                   ((r (in-range row1 (add1 row2)))
                    (c (in-range col1 (add1 col2))))
          (+ sum (list-ref (list-ref rect r) c)))))))

(define (subrectangle-queries rectangle queries)
  (let ((q (make-rectangle-queries rectangle)))
    (map q queries)))