#lang racket

(define (find-critical-pseudo-critical-edges n edges)
  (define (mst? edges include-edges exclude-edges)
    (define (kruskal edges include exclude)
      (define (sort-by-weight lst) (sort lst (lambda (a b) (< (second a) (second b)))))
      (define (find-parent parent x) (if (= parent x) x (find-parent parent (vector-ref parent x))))
      (define (union-parent parent rank x y)
        (define xroot (find-parent parent x))
        (define yroot (find-parent parent y))
        (when (not (= xroot yroot))
          (cond ((< (vector-ref rank xroot) (vector-ref rank yroot)) (vector-set! parent xroot yroot))
                ((> (vector-ref rank xroot) (vector-ref rank yroot)) (vector-set! parent yroot xroot))
                (else (vector-set! parent yroot xroot) (vector-set! rank xroot (+ (vector-ref rank xroot) 1))))))
      (define parent (build-vector n values))
      (define rank (build-vector n (lambda (_) 0)))
      (define total-weight 0)
      (define count 0)
      (for-each
       (lambda (e)
         (when (or (member e include) (not (member e exclude)))
           (define u (first e))
           (define v (second e))
           (define w (third e))
           (define x (find-parent parent u))
           (define y (find-parent parent v))
           (when (not (= x y))
             (union-parent parent rank x y)
             (set! total-weight (+ total-weight w))
             (set! count (+ count 1)))))
       (sort-by-weight edges))
      (if (= count (- n 1)) total-weight #f))
    (let ([total (kruskal edges include-edges exclude-edges)])
      (and total (= total (kruskal edges '() '())))))

  (define (is-critical e)
    (not (mst? edges '() (list e))))

  (define (is-pseudo-critical e)
    (and (mst? edges (list e) '()) (not (is-critical e))))

  (define critical (filter is-critical edges))
  (define pseudo-critical (filter is-pseudo-critical edges))
  (list (map (lambda (e) (index-of edges e)) critical) (map (lambda (e) (index-of edges e)) pseudo-critical)))