(define (can-be-divided-by-k arr k)
  (let ((freq (make-hash)))
    (for-each (lambda (num)
                (let ((mod (modulo num k)))
                  (hash-set! freq mod (+ 1 (hash-ref freq mod 0)))))
              arr)
    (if (= (modulo (car arr) k) 0)
        (and (even? (hash-ref freq 0 0))
             (for/and ((i (in-range 1 k)))
               (equal? (hash-ref freq i 0) (hash-ref freq (- k i) 0))))
        (for/and ((i (in-range 1 k)))
          (equal? (hash-ref freq i 0) (hash-ref freq (- k i) 0))))))