#lang racket

(define (find-latest-group-positions arr m)
  (define n (length arr))
  (define pos (make-vector n -1))
  (define len (make-hash))
  (define result -1)
  (for ([i (in-range n)])
    (define val (vector-ref arr i))
    (when (= val 1)
      (define left (if (> (- i 1) -1) (vector-ref pos (- i 1)) -1))
      (define right (if (< (+ i 1) n) (vector-ref pos (+ i 1)) -1))
      (define new-len (add1 (if (= left -1) 0 (hash-ref len left))))
      (when (= right -1)
        (set! new-len (add1 new-len)))
      (when (= left -1)
        (set! new-len (add1 new-len)))
      (when (> right -1)
        (set! new-len (add1 new-len)))
      (when (= right -1)
        (vector-set! pos i i)
        (hash-set! len i new-len)
        (when (= new-len m)
          (set! result i)))
      (when (> right -1)
        (vector-set! pos i (vector-ref pos right))
        (hash-set! len (vector-ref pos right) new-len)
        (hash-remove! len right)
        (when (= new-len m)
          (set! result i)))
      (when (> left -1)
        (vector-set! pos i (vector-ref pos left))
        (hash-set! len (vector-ref pos left) new-len)
        (hash-remove! len left)
        (when (= new-len m)
          (set! result i)))))
  result)

(define (find-latest-group arr m)
  (define n (length arr))
  (define pos (make-vector n -1))
  (define len (make-hash))
  (define result -1)
  (for ([i (in-range n)])
    (define val (vector-ref arr i))
    (when (= val 1)
      (define left (if (> (- i 1) -1) (vector-ref pos (- i 1)) -1))
      (define right (if (< (+ i 1) n) (vector-ref pos (+ i 1)) -1))
      (define new-len (add1 (if (= left -1) 0 (hash-ref len left))))
      (when (> right -1)
        (set! new-len (add1 new-len)))
      (when (> left -1)
        (set! new-len (add1 new-len)))
      (when (= right -1)
        (vector-set! pos i i)
        (hash-set! len i new-len)
        (when (= new-len m)
          (set! result i)))
      (when (> right -1)
        (vector-set! pos i (vector-ref pos right))
        (hash-set! len (vector-ref pos right) new-len)
        (hash-remove! len right)
        (when (= new-len m)
          (set! result i)))
      (when (> left -1)
        (vector-set! pos i (vector-ref pos left))
        (hash-set! len (vector-ref pos left) new-len)
        (hash-remove! len left)
        (when (= new-len m)
          (set! result i)))))
  result)

(define (main)
  (define input (read))
  (define m (read))
  (display (find-latest-group input m)))

(main)