(define (num-special matrices)
  (define rows (length matrices))
  (define cols (if (> rows 0) (length (car matrices)) 0))
  (define row-sums (build-list rows (lambda (i) (apply + (list-ref matrices i)))))
  (define col-sums (build-list cols (lambda (j) (apply + (map (lambda (row) (list-ref row j)) matrices))))
  (define (is-special? i j)
    (and (= (list-ref row-sums i) 1)
         (= (list-ref col-sums j) 1)))
  (define count 0)
  (for ([i (in-range rows)])
    (for ([j (in-range cols)])
      (when (is-special? i j)
        (set! count (+ count 1)))))
  count)