(define (max-unique-substrings s)
  (define (backtrack start seen result)
    (if (= start (string-length s))
        (set! result (max (or result 0) (set-count seen)))
        (for ([i (in-range (add1 start) (add1 (string-length s)))])
          (define substr (substring s start i))
          (when (not (set-member? seen substr))
            (backtrack i (set-add seen substr) result)))))
  (define result 0)
  (backtrack 0 (set) result)
  result)