(define (max-achievable-transfers requests)
  (define n (length requests))
  (define (count-ones bits)
    (if (= bits 0) 0 (+ (bitwise-and bits 1) (count-ones (arithmetic-shift bits -1)))))
  (define (valid? bits)
    (let loop ([i 0] [in-degree (make-vector n 0)])
      (if (= i n)
          (let ([sum (apply + (vector->list in-degree))])
            (= sum 0))
          (let ([req (list-ref requests i)])
            (if (bitwise-and bits (arithmetic-shift 1 i))
                (begin
                  (vector-set! in-degree (car req) (+ (vector-ref in-degree (car req)) 1))
                  (vector-set! in-degree (cadr req) (- (vector-ref in-degree (cadr req)) 1))
                  (loop (+ i 1) in-degree))
                (loop (+ i 1) in-degree))))))
  (define (helper max-count bits)
    (if (> bits (expt 2 n))
        max-count
        (let ([cnt (count-ones bits)])
          (if (valid? bits)
              (helper (max max-count cnt) (+ bits 1))
              (helper max-count (+ bits 1))))))
  (helper 0 0))