#lang racket

(define (max-network-rank edges n)
  (define deg (make-vector n 0))
  (for-each (lambda (e)
              (vector-set! deg (car e) (+ (vector-ref deg (car e)) 1))
              (vector-set! deg (cadr e) (+ (vector-ref deg (cadr e)) 1)))
            edges)
  (define adj (make-hash))
  (for-each (lambda (e)
              (hash-set! adj (car e) (cons (cadr e) (hash-ref adj (car e) '())))
              (hash-set! adj (cadr e) (cons (car e) (hash-ref adj (cadr e) '()))))
            edges)
  (define (connected? u v)
    (member v (hash-ref adj u '())))
  (define max-rank 0)
  (for ([i (in-range n)])
    (for ([j (in-range i n)])
      (define rank (+ (vector-ref deg i) (vector-ref deg j)))
      (when (connected? i j)
        (set! rank (- rank 1)))
      (set! max-rank (max max-rank rank))))
  max-rank)