(define (find-peak-element nums)
  (define (helper left right)
    (let ((mid (quotient (+ left right) 2)))
      (if (or (<= mid 0) (>= mid (- (length nums) 1)) (<= (list-ref nums mid) (list-ref nums (- mid 1))) (<= (list-ref nums mid) (list-ref nums (+ mid 1))))
          (if (<= (list-ref nums mid) (list-ref nums (+ mid 1)))
              (helper (+ mid 1) right)
              (helper left (- mid 1)))
          mid)))
  (helper 0 (- (length nums) 1)))