(define (lexicographically-smallest-string s a)
  (define (min-char c1 c2)
    (if (< (char->integer c1) (char->integer c2)) c1 c2))
  (define (apply-operations s)
    (let loop ((i 0) (s (string->list s)))
      (if (>= i (string-length s))
          (list->string s)
          (let* ((current (list-ref s i))
                 (next (if (< i (- (string-length s) 1)) (list-ref s (+ i 1)) #\0))
                 (rotated (list-ref s (modulo (+ i a) (string-length s))))
                 (option1 (min-char current next))
                 (option2 (min-char current rotated)))
            (loop (+ i 1) (list-set s i (min-char option1 option2)))))))
  (apply-operations s))