(define (compare-version-numbers version1 version2)
  (define (split-ver v)
    (map string->number (string-split v ".")))
  (define v1 (split-ver version1))
  (define v2 (split-ver version2))
  (define (cmp a b)
    (cond ((null? a) 0)
          ((null? b) 0)
          ((> (car a) (car b)) 1)
          ((< (car a) (car b)) -1)
          (else (cmp (cdr a) (cdr b)))))
  (cmp v1 v2))