(define (min-operations nums x)
  (define n (length nums))
  (define total (apply + nums))
  (define target (- total x))
  (if (<= target 0)
      (if (= target 0) 0 (- n))
      (let loop ([left 0] [current 0] [max-len 0])
        (if (>= left n)
            (- n max-len)
            (let ([right (min (- n 1) (+ left (quotient (- target current) (car nums))))])
              (let ([new-current (+ current (list-ref nums right))])
                (if (<= new-current target)
                    (loop left new-current (max max-len (- right left 1)))
                    (loop (+ left 1) (- current (list-ref nums left)) max-len))))))))