(define (stone-game-vi alice-values bob-values)
  (define values (map list alice-values bob-values))
  (define sorted-values (sort values (lambda (a b) (> (- (car a) (cadr a)) (- (car b) (cadr b))))))
  (define (sum-alice lst) (foldl + 0 (map car lst)))
  (define (sum-bob lst) (foldl + 0 (map cadr lst)))
  (let loop ([lst sorted-values] [alice 0] [bob 0])
    (if (null? lst)
        (- alice bob)
        (loop (cdr lst) (+ alice (caar lst)) (+ bob (cadar lst))))))