(define (reformat-number number)
  (define (split-group s n)
    (if (<= (string-length s) n)
        (list s)
        (cons (substring s 0 n)
              (split-group (substring s n) n))))
  (define groups (split-group number 3))
  (if (= (length groups) 1)
      (car groups)
      (string-join (append (take groups (- (length groups) 1)) (list (string-append (last groups) " "))) "")))