(define (car-fleet target positions speeds)
  (define (compare a b)
    (< (car a) (car b)))
  (define cars (map list positions speeds))
  (set! cars (sort cars compare))
  (define res '())
  (for ([i (in-range (length cars))])
    (define pos (list-ref cars i))
    (define p (car pos))
    (define s (cadr pos))
    (define time (/ (- target p) s))
    (when (or (null? res) (> time (caar res)))
      (set! res (cons (list time) res))))
  (length res))