(define (num-ways n index value)
  (define (min a b) (if (< a b) a b))
  (define (max a b) (if (> a b) a b))
  (define (sum a b)
    (if (> a b) 0 (* (- b a 1) (+ a b) 1/2)))
  (let* ((left (min index (- value 1)))
         (right (min (- n 1) (- value 1)))
         (left-sum (sum 1 left))
         (right-sum (sum 1 right))
         (total (+ left-sum right-sum (* value (- n (+ left right 1))))))
    total))

(define (is-possible n index max-value)
  (<= (num-ways n index max-value) 0))

(define (max-value-at-index n index max-value)
  (let loop ((low 1) (high max-value))
    (if (<= low high)
        (let ((mid (quotient (+ low high) 2)))
          (if (is-possible n index mid)
              (loop (add1 mid) high)
              (loop low (sub1 mid))))
        low)))

(define (main args)
  (let ((n (string->number (car args)))
        (index (string->number (cadr args)))
        (max-value (string->number (caddr args))))
    (display (max-value-at-index n index max-value))
    (newline)))