(define (minimum-sideway-jumps obstacles)
  (define (min a b c) (min (min a b) c))
  (define (solve dp i)
    (if (= i (vector-length obstacles))
        (min (vector-ref dp 0) (vector-ref dp 1) (vector-ref dp 2))
        (let ([next-dp (vector 0 0 0)])
          (vector-set! next-dp 0 (if (= (vector-ref obstacles i) 1) (vector-ref dp 0) (+ (vector-ref dp 0) 1)))
          (vector-set! next-dp 1 (if (= (vector-ref obstacles i) 2) (vector-ref dp 1) (+ (vector-ref dp 1) 1)))
          (vector-set! next-dp 2 (if (= (vector-ref obstacles i) 3) (vector-ref dp 2) (+ (vector-ref dp 2) 1)))
          (solve next-dp (+ i 1)))))
  (solve (vector 0 1 1) 0))