(define (xor-sum-of-all-pairs-bitwise-and nums)
  (define (bitwise-and a b) (bitwise-and a b))
  (define (bitwise-xor a b) (bitwise-xor a b))
  (define n (length nums))
  (define result 0)
  (for ([i (in-range n)])
    (for ([j (in-range n)])
      (set! result (bitwise-xor result (bitwise-and (list-ref nums i) (list-ref nums j))))))
  result)