(define (longest-substring s)
  (define vowels '(#\a #\e #\i #\o #\u))
  (define (is-vowel c) (member c vowels))
  (define (next-vowel-index c)
    (cond ((char=? c #\a) 0)
          ((char=? c #\e) 1)
          ((char=? c #\i) 2)
          ((char=? c #\o) 3)
          ((char=? c #\u) 4)
          (else -1)))
  (let loop ([i 0] [max-len 0] [current-len 0] [prev-index -1])
    (if (= i (string-length s))
        max-len
        (let ([c (string-ref s i)])
          (if (is-vowel c)
              (let ([idx (next-vowel-index c)])
                (if (>= idx prev-index)
                    (loop (+ i 1) (max max-len (+ current-len 1)) (+ current-len 1) idx)
                    (loop (+ i 1) max-len 1 idx)))
              (loop (+ i 1) max-len 0 -1))))))