(define/contract (can-reach s i j)
  (-> string? exact-integer? exact-integer? boolean?)
  (let ((n (string-length s)))
    (define dp (make-vector n #f))
    (vector-set! dp i #t)
    (for ([k (in-range n)])
      (when (vector-ref dp k)
        (when (and (< k (- n 1)) (= (string-ref s k) (string-ref s (+ k 1))) (not (vector-ref dp (+ k 1))))
          (vector-set! dp (+ k 1) #t))
        (when (and (> k 0) (= (string-ref s k) (string-ref s (- k 1))) (not (vector-ref dp (- k 1))))
          (vector-set! dp (- k 1) #t))))
    (vector-ref dp j))
  )