(define (stone-game-viii piles)
  (let ((n (length piles)))
    (let ((dp (make-vector n 0)))
      (vector-set! dp (- n 1) (vector-ref piles (- n 1)))
      (let loop ((i (- n 2)))
        (when (>= i 0)
          (vector-set! dp i (+ (vector-ref piles i) (vector-ref dp (+ i 1))))
          (loop (- i 1))))
      (vector-ref dp 0))))