(define (rotate nums k)
  (define n (length nums))
  (when (> n 0)
    (set! k (modulo k n))
    (define (reverse start end)
      (let loop ((i start) (j end))
        (when (<= i j)
          (let ((temp (list-ref nums i)))
            (list-set! nums i (list-ref nums j))
            (list-set! nums j temp)
            (loop (+ i 1) (- j 1)))))
    (reverse 0 (- n 1))
    (reverse 0 (- k 1))
    (reverse k (- n 1))))
  nums)