(define (count-sub-islands grid1 grid2)
  (define (dfs i j)
    (when (and (<= 0 i (- (length grid2) 1))
               (<= 0 j (- (length (car grid2)) 1))
               (= (list-ref (list-ref grid2 i) j) 1))
      (set! (list-ref (list-ref grid2 i) j) 0)
      (let ([val (= (list-ref (list-ref grid1 i) j) 1)])
        (when val
          (dfs (+ i 1) j)
          (dfs (- i 1) j)
          (dfs i (+ j 1))
          (dfs i (- j 1)))
        val)))
  (define count 0)
  (for ([i (in-range (length grid2))])
    (for ([j (in-range (length (car grid2)))])
      (when (= (list-ref (list-ref grid2 i) j) 1)
        (when (dfs i j)
          (set! count (+ count 1))))))
  count)