(define (count-good-numbers n)
  (define mod 1000000007)
  (define (pow a b)
    (cond ((= b 0) 1)
          ((even? b) (let ((temp (pow a (/ b 2))))
                       (modulo (* temp temp) mod)))
          (else (modulo (* a (pow a (- b 1))) mod))))
  (define even (pow 5 (quotient n 2)))
  (define odd (pow 4 (quotient n 2)))
  (modulo (* even odd) mod))