#lang racket

(define (count-palindromic-subsequence s)
  (define len (string-length s))
  (define count (make-hash))
  (for ([i (in-range len)])
    (define c (string-ref s i))
    (hash-set! count c (add1 (hash-ref count c 0))))
  (define result 0)
  (for ([i (in-range len)])
    (define c (string-ref s i))
    (when (> (hash-ref count c) 1)
      (define left (make-hash))
      (for ([j (in-range 0 i)])
        (define left-c (string-ref s j))
        (hash-set! left left-c #t))
      (define right (make-hash))
      (for ([j (in-range (+ i 1) len)])
        (define right-c (string-ref s j))
        (hash-set! right right-c #t))
      (for ([k (in-hash-keys left)])
        (when (hash-has-key? right k)
          (set! result (add1 result))))))
  result)