(define/contract (can-see-number-of-people-on-the-left heights)
  (-> (listof exact-integer?) (listof exact-integer?))
  (let ((n (length heights))
        (result (make-vector 0 0)))
    (define stack '())
    (for ([i (in-range n)])
      (let loop ()
        (when (and (not (null? stack)) (< (list-ref heights (car stack)) (list-ref heights i)))
          (vector-set! result (car stack) (+ (vector-ref result (car stack)) 1))
          (set! stack (cdr stack))
          (loop)))
      (when (not (null? stack))
        (vector-set! result i (+ (vector-ref result i) 1)))
      (set! stack (cons i stack)))
    (vector->list result))
  )