(define (make-fancy-string s)
  (define (helper s res)
    (if (null? s)
        (list->string res)
        (let ((current (car s)))
          (if (and (>= (length res) 2)
                   (= (car res) current)
                   (= (cadr res) current))
              (helper (cdr s) res)
              (helper (cdr s) (cons current res))))))
  (reverse (helper (string->list s) '())))