#lang racket

(define (min-sessions tasks session-time)
  (define n (length tasks))
  (define dp (make-vector (expt 2 n) #f))
  (vector-set! dp 0 #t)
  (define res (make-vector n #f))
  (for ([i (in-range n)])
    (vector-set! res i #t))
  (for ([mask (in-range (expt 2 n))])
    (when (vector-ref dp mask)
      (for ([i (in-range n)])
        (when (bitwise-bit-set? mask i)
          (for ([j (in-range n)])
            (when (not (bitwise-bit-set? mask j))
              (define new-mask (bitwise-ior mask (arithmetic-shift 1 j)))
              (define current-time (+ (vector-ref res i) (list-ref tasks j)))
              (when (<= current-time session-time)
                (vector-set! res j (min (vector-ref res j) current-time))
                (vector-set! dp new-mask #t)))))))
  (apply min (vector->list res)))