(define (num-islands grid)
  (define (dfs i j)
    (when (and (<= 0 i (sub1 (length grid)))
               (<= 0 j (sub1 (length (car grid))))
               (equal? (list-ref (list-ref grid i) j) "1"))
      (set! grid (map (lambda (row k)
                        (if (= k i)
                            (map (lambda (cell l)
                                   (if (= l j) "0" cell))
                                 row
                                 (range (length row)))
                            row))
                      grid
                      (range (length grid))))
      (dfs (add1 i) j)
      (dfs (sub1 i) j)
      (dfs i (add1 j))
      (dfs i (sub1 j))))
  (define (range n)
    (if (= n 0)
        '()
        (cons (sub1 n) (range (sub1 n)))))
  (let loop ((i 0) (count 0))
    (if (>= i (length grid))
        count
        (loop (add1 i)
              (let loop2 ((j 0) (count count))
                (if (>= j (length (car grid)))
                    count
                    (if (equal? (list-ref (list-ref grid i) j) "1")
                        (begin (dfs i j) (loop2 (add1 j) (add1 count)))
                        (loop2 (add1 j) count)))))))