(define (count-k-diff nums k)
  (define freq (make-hash))
  (for-each (lambda (n) (hash-set! freq n (+ (hash-ref freq n 0) 1))) nums)
  (define result 0)
  (for-each (lambda (n)
              (when (hash-has-key? freq (+ n k))
                (set! result (+ result (hash-ref freq (+ n k))))))
            nums)
  result)