(define (missing-observations a m)
  (let* ((total (apply + a))
         (expected (* m 3.5))
         (diff (- expected total)))
    (if (<= diff 0)
        '()
        (let* ((n (floor (/ diff 6)))
               (r (remainder diff 6)))
          (if (= r 0)
              (make-list n 6)
              (append (make-list n 6) (list r)))))))