(define (count-max-bitwise-or-subsets nums)
  (define max-or 0)
  (define count 0)
  (define n (length nums))
  (define (dfs idx curr)
    (when (< idx n)
      (let ((new-curr (bitwise-ior curr (list-ref nums idx))))
        (if (= new-curr max-or)
            (set! count (+ count 1))
            (when (> new-curr max-or)
              (set! max-or new-curr)
              (set! count 1)))
        (dfs (+ idx 1) new-curr)
        (dfs (+ idx 1) curr))))
  (dfs 0 0)
  count)