(define (possibly-encodes? s1 s2)
  (define (dfs i j memo)
    (cond [(and (= i (string-length s1)) (= j (string-length s2))) #t]
          [(or (= i (string-length s1)) (= j (string-length s2))) #f]
          [else
           (let ([key (cons i j)])
             (if (hash-has-key? memo key)
                 (hash-ref memo key)
                 (let ([res (or (and (char=? (string-ref s1 i) (string-ref s2 j))
                                   (dfs (+ i 1) (+ j 1) memo))
                                (and (char=? (string-ref s1 i) #\#)
                                     (let ([k (+ j 1)])
                                       (and (< k (string-length s2))
                                            (char=? (string-ref s2 j) #\#)
                                            (let loop ([m k] [n k])
                                              (and (<= n (string-length s2))
                                                   (or (and (= m (string-length s1))
                                                            (= n (string-length s2)))
                                                       (and (< m (string-length s1))
                                                            (char=? (string-ref s1 m) (string-ref s2 n))
                                                            (loop (+ m 1) (+ n 1)))
                                                       (and (>= n (string-length s2))
                                                            (dfs m n memo))
                                                       (and (>= m (string-length s1))
                                                            (dfs m n memo))
                                                       (and (not (= m (string-length s1)))
                                                            (not (= n (string-length s2)))
                                                            (char=? (string-ref s1 m) (string-ref s2 n))
                                                            (loop (+ m 1) (+ n 1)))))))))
                                 (let ([k (+ j 1)])
                                   (and (< k (string-length s2))
                                        (char=? (string-ref s2 j) #\#)
                                        (dfs i k memo)))]))
               (hash-set! memo key res)
               res))]))
  (dfs 0 0 (make-hash)))

(define/contract (possibly-encodes s1 s2)
  (-> string? string? boolean?)
  (possibly-encodes? s1 s2))