#lang racket

(define (decode-ciphertext encoded-text number-of-rows)
  (define len (string-length encoded-text))
  (define result (make-string len #\0))
  (define idx 0)
  (define step (* 2 (- number-of-rows 1)))
  (for ([i (in-range number-of-rows)])
    (when (not (= i 0))
      (define j (+ i (- step 1)))
      (when (< j len)
        (string-set! result idx (string-ref encoded-text j))
        (set! idx (+ idx 1))))
    (define j i)
    (when (< j len)
      (string-set! result idx (string-ref encoded-text j))
      (set! idx (+ idx 1)))
    (define j (+ i step))
    (while (< j len)
      (string-set! result idx (string-ref encoded-text j))
      (set! idx (+ idx 1))
      (set! j (+ j step))))
  (substring result 0 idx))