#lang racket

(define (find-all-people n meetings)
  (define (sort-meetings)
    (sort meetings (lambda (a b)
                     (or (< (car a) (car b))
                         (and (= (car a) (car b)) (< (cadr a) (cadr b)))))))

  (define (union-find)
    (let ((parent (make-vector n)))
      (for ([i (in-range n)])
        (vector-set! parent i i))
      (define (find x)
        (if (= x (vector-ref parent x))
            x
            (let ((p (find (vector-ref parent x))))
              (vector-set! parent x p)
              p)))
      (define (union x y)
        (let ((px (find x))
              (py (find y)))
          (when (/= px py)
            (vector-set! parent px py))))
      (values find union)))

  (define-values (find union) (union-find))

  (define sorted-meetings (sort-meetings))

  (define (process-meetings)
    (define result (make-hash))
    (define current-time -1)
    (define (process-group group)
      (for ([pair group])
        (let ((u (car pair))
              (v (cadr pair)))
          (union u v)))
      (for ([pair group])
        (let ((u (car pair))
              (v (cadr pair)))
          (when (= (find u) (find (car group)))
            (hash-set! result u #t))))
    (for ([meeting sorted-meetings])
      (let ((time (car meeting))
            (u (cadr meeting))
            (v (caddr meeting)))
        (if (= time current-time)
            (set! group (cons (list u v) group))
            (begin
              (when (and (not (null? group)) (> (length group) 0))
                (process-group group))
              (set! current-time time)
              (set! group (list (list u v))))))
      (when (and (not (null? group)) (> (length group) 0))
        (process-group group)))
    (hash-keys result))

  (process-meetings))