#lang racket

(define (find-order num-courses prerequisites)
  (define in-degree (make-vector num-courses 0))
  (define graph (make-vector num-courses '()))
  (for-each
   (lambda (prereq)
     (let ([a (car prereq)] [b (cadr prereq)])
       (vector-set! in-degree a (+ (vector-ref in-degree a) 1))
       (vector-set! graph b (cons a (vector-ref graph b)))))
   prerequisites)
  (define queue (queue))
  (for ([i (in-range num-courses)])
    (when (= (vector-ref in-degree i) 0)
      (enqueue! queue i)))
  (define result '())
  (let loop ()
    (when (not (queue-empty? queue))
      (let ([node (dequeue! queue)])
        (set! result (cons node result))
        (for-each
         (lambda (neighbor)
           (vector-set! in-degree neighbor (- (vector-ref in-degree neighbor) 1))
           (when (= (vector-ref in-degree neighbor) 0)
             (enqueue! queue neighbor)))
         (vector-ref graph node))
        (loop)))
  (if (= (length result) num-courses)
      (reverse result)
      '()))