(define (subroutine s)
  (define (count-rod c)
    (cond ((char=? c #\R) 0)
          ((char=? c #\G) 1)
          ((char=? c #\B) 2)
          (else 3)))
  (define counts (make-vector 3 0))
  (for ([i (in-range 0 (string-length s) 2)])
    (define c (string-ref s (+ i 1)))
    (vector-set! counts (count-rod c) (+ (vector-ref counts (count-rod c)) 1)))
  (vector->list counts))

(define (rings-and-rods s)
  (define counts (subroutine s))
  (length (filter (lambda (x) (>= x 1)) counts)))