(define (most-frequent-key-nums nums key)
  (define freq (make-hash))
  (for ([i (in-range (sub1 (length nums)))])
    (when (= (list-ref nums i) key)
      (let ([next (list-ref nums (add1 i))])
        (hash-update! freq next add1 0))))
  (define max-count 0)
  (define result #f)
  (for ([(k v) (in-hash freq)])
    (when (> v max-count)
      (set! max-count v)
      (set! result k)))
  result)