(define (minimum-white-tiles floors carpets)
  (define n (string-length floors))
  (define dp (make-vector (+ n 1) 0))
  (for ([i (in-range 1 (+ n 1))])
    (vector-set! dp i (if (= (string-ref floors (- i 1)) #\W) (add1 (vector-ref dp (- i 1))) (vector-ref dp (- i 1))))
    (when (and (>= i 1) (<= i (string-length carpets)))
      (when (= (string-ref carpets (- i 1)) #\C)
        (vector-set! dp i (min (vector-ref dp i) (vector-ref dp (- i 1)))))))
  (vector-ref dp n))