(define/contract (num-operations target-time current-time)
  (-> string? string? exact-integer?)
  (define (to-minutes time-str)
    (define parts (string-split time-str ":"))
    (+ (* (string->number (list-ref parts 0)) 60) (string->number (list-ref parts 1))))
  (define target (to-minutes target-time))
  (define current (to-minutes current-time))
  (define diff (abs (- target current)))
  (let loop ((remaining diff) (count 0))
    (cond ((= remaining 0) count)
          ((>= remaining 60) (loop (- remaining 60) (+ count 1)))
          ((>= remaining 15) (loop (- remaining 15) (+ count 1)))
          ((>= remaining 5) (loop (- remaining 5) (+ count 1)))
          (else (loop (- remaining 1) (+ count 1))))))