(define (maximum-candies candies-per-packet)
  (define (can-allocate? k mid)
    (let loop ((i 0) (count 0))
      (cond ((= i (length candies-per-packet)) (>= count k))
            ((<= mid (list-ref candies-per-packet i)) (loop (+ i 1) (+ count 1)))
            (else (loop (+ i 1) count)))))

  (let loop ((left 1) (right (apply + candies-per-packet)))
    (if (> left right)
        (- left 1)
        (let ((mid (quotient (+ left right) 2)))
          (if (can-allocate? (length candies-per-packet) mid)
              (loop (+ mid 1) right)
              (loop left (- mid 1)))))))