#lang racket

(define (longest-path-with-different-adjacent-characters)
  (define input (read-line))
  (define n (string-length input))
  (define adj (make-vector n '()))
  (for ([i (in-range n)])
    (when (< i (- n 1))
      (vector-set! adj i (cons (string-ref input (+ i 1)) (vector-ref adj i))))
    (when (> i 0)
      (vector-set! adj i (cons (string-ref input (- i 1)) (vector-ref adj i)))))
  (define visited (make-vector n #f))
  (define max-length 0)
  (define (dfs node char)
    (vector-set! visited node #t)
    (define res 1)
    (for ([neighbor (vector-ref adj node)])
      (when (not (equal? neighbor char))
        (define sub (dfs neighbor (string-ref input node)))
        (set! res (max res (+ sub 1)))))
    (vector-set! visited node #f)
    res)
  (for ([i (in-range n)])
    (set! max-length (max max-length (dfs i #\0))))
  max-length)