(define (count-texts pressed-keys)
  (define dp
    (let ((n (string-length pressed-keys)))
      (make-vector n 0)))
  (vector-set! dp 0 1)
  (when (> n 1)
    (vector-set! dp 1 (if (= (string-ref pressed-keys 0) (string-ref pressed-keys 1)) 2 1)))
  (when (> n 2)
    (vector-set! dp 2 (if (= (string-ref pressed-keys 1) (string-ref pressed-keys 2))
                          (+ (vector-ref dp 1) (vector-ref dp 0))
                          (vector-ref dp 1))))
  (when (> n 3)
    (vector-set! dp 3 (if (= (string-ref pressed-keys 2) (string-ref pressed-keys 3))
                          (+ (vector-ref dp 2) (vector-ref dp 1))
                          (vector-ref dp 2))))
  (when (> n 4)
    (vector-set! dp 4 (if (= (string-ref pressed-keys 3) (string-ref pressed-keys 4))
                          (+ (vector-ref dp 3) (vector-ref dp 2))
                          (vector-ref dp 3))))
  (when (> n 5)
    (vector-set! dp 5 (if (= (string-ref pressed-keys 4) (string-ref pressed-keys 5))
                          (+ (vector-ref dp 4) (vector-ref dp 3))
                          (vector-ref dp 4))))
  (when (> n 6)
    (vector-set! dp 6 (if (= (string-ref pressed-keys 5) (string-ref pressed-keys 6))
                          (+ (vector-ref dp 5) (vector-ref dp 4))
                          (vector-ref dp 5))))
  (when (> n 7)
    (vector-set! dp 7 (if (= (string-ref pressed-keys 6) (string-ref pressed-keys 7))
                          (+ (vector-ref dp 6) (vector-ref dp 5))
                          (vector-ref dp 6))))
  (when (> n 8)
    (vector-set! dp 8 (if (= (string-ref pressed-keys 7) (string-ref pressed-keys 8))
                          (+ (vector-ref dp 7) (vector-ref dp 6))
                          (vector-ref dp 7))))
  (when (> n 9)
    (vector-set! dp 9 (if (= (string-ref pressed-keys 8) (string-ref pressed-keys 9))
                          (+ (vector-ref dp 8) (vector-ref dp 7))
                          (vector-ref dp 8))))
  (vector-ref dp (- (string-length pressed-keys) 1)))