#lang racket

(define (sum-of-total-strength strength)
  (define MOD 1000000007)
  (define n (length strength))
  (define left (make-vector n -1))
  (define right (make-vector n n))
  (define stack '())
  (for ([i (in-range n)])
    (set! stack '())
    (for ([j (in-range i -1 -1)])
      (if (< (list-ref strength j) (list-ref strength i))
          (begin
            (vector-set! left i j)
            (set! stack '())
            (break))
          (set! stack (cons j stack))))
    (when (not (null? stack))
      (vector-set! left i (car stack))))
  (set! stack '())
  (for ([i (in-range n)])
    (set! stack '())
    (for ([j (in-range i n)])
      (if (< (list-ref strength j) (list-ref strength i))
          (begin
            (vector-set! right i j)
            (set! stack '())
            (break))
          (set! stack (cons j stack))))
    (when (not (null? stack))
      (vector-set! right i (car stack))))
  (define prefix (make-vector (+ n 1) 0))
  (for ([i (in-range n)])
    (vector-set! prefix (+ i 1) (modulo (+ (vector-ref prefix i) (list-ref strength i)) MOD)))
  (define suffix (make-vector (+ n 1) 0))
  (for ([i (in-range (- n 1) -1 -1)])
    (vector-set! suffix (+ i 1) (modulo (+ (vector-ref suffix (+ i 2)) (list-ref strength i)) MOD)))
  (define result 0)
  (for ([i (in-range n)])
    (define l (vector-ref left i))
    (define r (vector-ref right i))
    (define a (+ l 1))
    (define b (- r 1))
    (define sum-l (modulo (- (vector-ref prefix (+ i 1)) (vector-ref prefix a)) MOD))
    (define sum-r (modulo (- (vector-ref suffix (+ i 1)) (vector-ref suffix (+ b 2))) MOD))
    (define count-l (- i a))
    (define count-r (- b i))
    (define total (modulo (* (modulo (* sum-l (expt 2 count-l)) MOD) (modulo (* sum-r (expt 2 count-r)) MOD)) MOD))
    (set! result (modulo (+ result (* (list-ref strength i) total)) MOD)))
  result)