(define (min-max-game nums)
  (let loop ((nums nums))
    (if (= (length nums) 1)
        (car nums)
        (let ((new-nums '()))
          (let ((n (length nums)))
            (for ((i (in-range 0 n 2)))
              (let ((a (list-ref nums i))
                    (b (list-ref nums (+ i 1))))
                (set! new-nums (append new-nums (list (if (even? (quotient i 2)) (min a b) (max a b)))))))
            (loop new-nums)))))