(define (max-profit n m price)
  (define dp (make-vector (+ n 1) (make-vector (+ m 1) 0)))
  (for ([i (in-range 1 (+ n 1))])
    (for ([j (in-range 1 (+ m 1))])
      (when (and (>= i 1) (>= j 1))
        (vector-set! (vector-ref dp i) j (vector-ref (vector-ref dp (- i 1)) j))
        (vector-set! (vector-ref dp i) j (max (vector-ref (vector-ref dp i) j) (vector-ref (vector-ref dp (- j 1)) i)))
        (for ([k (in-range 1 i)])
          (vector-set! (vector-ref dp i) j (max (vector-ref (vector-ref dp i) j) (+ (vector-ref (vector-ref dp k) j) (vector-ref (vector-ref dp (- i k)) j)))))
        (for ([l (in-range 1 j)])
          (vector-set! (vector-ref dp i) j (max (vector-ref (vector-ref dp i) j) (+ (vector-ref (vector-ref dp i) l) (vector-ref (vector-ref dp i) (- j l))))))))
  (vector-ref (vector-ref dp n) m))