(define (max-score-of-spliced-array nums1 nums2)
  (define (max-diff a b)
    (let ((diff (map - a b))
          (current 0)
          (max-so-far 0))
      (for-each
       (lambda (d)
         (set! current (max d (+ current d)))
         (set! max-so-far (max max-so-far current)))
       diff)
      max-so-far))
  (define (sum lst)
    (apply + lst))
  (define s1 (sum nums1))
  (define s2 (sum nums2))
  (define m1 (max-diff nums1 nums2))
  (define m2 (max-diff nums2 nums1))
  (max (+ s1 m2) (+ s2 m1)))