#lang racket

(define (min-score-removals nums)
  (define n (vector-length nums))
  (define adj (make-vector n '()))
  (for ([i (in-range n)])
    (when (not (= i 0))
      (vector-set! adj i (cons (vector-ref nums i) (vector-ref adj i)))
      (vector-set! adj (vector-ref nums i) (cons i (vector-ref adj i)))))
  (define (dfs u parent)
    (let ([count 1])
      (for ([v (vector-ref adj u)])
        (when (not (= v parent))
          (set! count (+ count (dfs v u)))))
      count))
  (define total (apply + (vector->list nums)))
  (define res +inf.0)
  (for ([i (in-range n)])
    (define s (dfs i -1))
    (define left (- total s))
    (define right (- left (dfs (vector-ref nums i) i)))
    (set! res (min res (abs (- left right)))))
  res)