(define (maximum-groups nums)
  (define (count x)
    (let loop ([i 1] [total 0])
      (if (> total x)
          (- i 1)
          (loop (+ i 1) (+ total i)))))
  (let ([freq (make-hash)])
    (for-each (lambda (x) (hash-set! freq x (+ (hash-ref freq x 0) 1))) nums)
    (let loop ([i 1] [res 0])
      (if (>= i (add1 (hash-max-key freq)))
          res
          (let ([cnt (hash-ref freq i 0)])
            (if (<= cnt (count i))
                (loop (+ i 1) (+ res cnt))
                (loop (+ i 1) res)))))))