(define/contract (least-integer-amount tasks n)
  (-> (listof exact-integer?) exact-integer? exact-integer?)
  (let ((count (make-hash)))
    (for-each (lambda (task) (hash-set! count task (+ 1 (hash-ref count task 0)))) tasks)
    (let ((max-freq (apply max (hash-values count))))
      (let ((num-max-freq (length (filter (lambda (v) (= v max-freq)) (hash-values count)))))
        (+ (* (- max-freq 1) (+ n 1)) num-max-freq))))
  )
)