#lang racket

(define (count-special-integers n)
  (define digits (map (lambda (c) (- (char->integer c) 48)) (string->list (number->string n))))
  (define len (length digits))
  (define memo (make-hash))
  (define (dp pos tight leading-zero?)
    (if (= pos len)
        (if leading-zero? 0 1)
        (let ((limit (if tight (list-ref digits pos) 9)))
          (for/sum ((d (in-range 0 (add1 limit))))
            (if (and (not leading-zero?) (not (zero? d)))
                (if (and (not tight) (not leading-zero?))
                    (let ((key (format "~a-~a-~a" pos tight leading-zero?)))
                      (hash-ref memo key (lambda () (set! (hash-set! memo key (dp (add1 pos) #f #f))) (dp (add1 pos) #f #f)))
                    )
                (let ((new-tight (and tight (= d (list-ref digits pos))))
                      (new-leading-zero? (and leading-zero? (= d 0))))
                  (let ((key (format "~a-~a-~a" pos new-tight new-leading-zero?)))
                    (hash-ref memo key (lambda () (set! (hash-set! memo key (dp (add1 pos) new-tight new-leading-zero?))) (dp (add1 pos) new-tight new-leading-zero?)))))))))
  (dp 0 #t #t))