(define (longest-circular-substring s)
  (define (is-in-order a b)
    (char<=? a b))
  (define (max-length)
    (let loop ((i 0) (current-length 1) (max-length 1))
      (if (= i (string-length s))
          max-length
          (let ((next-char (string-ref s (add1 i))))
            (if (is-in-order (string-ref s i) next-char)
                (loop (add1 i) (add1 current-length) (max max-length current-length))
                (loop (add1 i) 1 max-length))))))
  (max (max-length) (if (and (>= (string-length s) 2)
                             (is-in-order (string-ref s (- (string-length s) 1)) (string-ref s 0)))
                         (+ (string-length s) 1)
                         1)))