(define (ones-minus-zeros grid)
  (define rows (length grid))
  (define cols (length (car grid)))
  (define row-ones (make-vector rows 0))
  (define col-ones (make-vector cols 0))
  (for ([i (in-range rows)])
    (for ([j (in-range cols)])
      (when (= (vector-ref (vector-ref grid i) j) 1)
        (vector-set! row-ones i (+ (vector-ref row-ones i) 1))
        (vector-set! col-ones j (+ (vector-ref col-ones j) 1)))))
  (for/list ([i (in-range rows)])
    (for/list ([j (in-range cols)])
      (- (* 2 (vector-ref row-ones i)) rows (* 2 (vector-ref col-ones j)) cols))))