(define (max-difference num)
  (define s (string->list (number->string num)))
  (define (to-number lst) (string->number (list->string lst)))
  (define (max-possible s)
    (let loop ([i 0] [s s])
      (if (= i (length s))
          (to-number s)
          (if (char=? (list-ref s i) #\9)
              (loop (+ i 1) s)
              (begin
                (set! s (append (take s i) (list #\9) (drop s (+ i 1))))
                (loop (+ i 1) s))))))
  (define (min-possible s)
    (let loop ([i 0] [s s])
      (if (= i (length s))
          (to-number s)
          (if (and (char=? (list-ref s i) #\0) (= i 0))
              (loop (+ i 1) s)
              (begin
                (set! s (append (take s i) (list #\0) (drop s (+ i 1))))
                (loop (+ i 1) s))))))
  (- (max-possible s) (min-possible s)))