(define/contract (divisibility-array num k)
  (-> string? exact-integer? (listof exact-integer?))
  (define n (string-length num))
  (define result (make-vector n 0))
  (define current-mod 0)
  (for ([i (in-range n)])
    (set! current-mod (modulo (+ (* current-mod 10) (- (char->integer (string-ref num i)) 48)) k))
    (vector-set! result i (if (= current-mod 0) 1 0)))
  (vector->list result))