#lang racket

(define (first-complete-paint rows cols)
  (define row-count (make-hash))
  (define col-count (make-hash))
  (define row-full #f)
  (define col-full #f)
  (define (check-row i)
    (hash-ref row-count i 0))
  (define (check-col j)
    (hash-ref col-count j 0))
  (define (update-row i)
    (hash-set! row-count i (+ 1 (check-row i)))
    (when (= (check-row i) cols)
      (set! row-full #t)))
  (define (update-col j)
    (hash-set! col-count j (+ 1 (check-col j)))
    (when (= (check-col j) rows)
      (set! col-full #t)))
  (for ([i (in-range rows)]
        [j (in-range cols)])
    (update-row i)
    (update-col j)
    (when (or row-full col-full)
      (break)))
  (if row-full 'row 'col))