(define/contract (special-permutations nums)
  (-> (listof exact-integer?) (listof (listof exact-integer?)))
  (define (backtrack path used)
    (if (= (length path) (length nums))
        (list path)
        (for/fold ([res '()])
                  ([i (in-range (length nums))])
          (if (and (not (member i used)) (or (null? path) (<= (list-ref nums (car path)) (list-ref nums i))))
              (append res (backtrack (cons i path) (cons i used)))
              res)))
  (apply append (backtrack '() '())))