(define (minimum-beautiful-substrings s)
  (define (is-beautiful? s)
    (let ((n (string-length s)))
      (and (even? n)
           (let loop ((i 0) (j (- n 1)))
             (or (>= i j)
                 (and (= (string-ref s i) (string-ref s j))
                      (loop (+ i 1) (- j 1))))))))
  (define dp (make-hash))
  (define (helper idx)
    (hash-ref dp idx (lambda ()
                       (if (= idx (string-length s))
                           0
                           (let ((min-val #f))
                             (for ((i (in-range (+ idx 1) (+ (string-length s) 1))))
                               (when (is-beautiful? (substring s idx i))
                                 (let ((res (helper i)))
                                   (when (not (false? res))
                                     (set! min-val (if (false? min-val)
                                                       res
                                                       (min min-val res)))))))
                             (if (false? min-val)
                                 #f
                                 (+ min-val 1))))))
  (helper 0))