#lang racket

(define (maximum-beauty nums k)
  (define sorted (sort nums <))
  (define n (length sorted))
  (define result 0)
  (define i 0)
  (define j 0)
  (define count (make-hash))
  (define max-count 0)
  (define (update-count x)
    (hash-set! count x (+ (hash-ref count x 0) 1))
    (when (> (hash-ref count x) max-count)
      (set! max-count (hash-ref count x))))
  (define (remove-count x)
    (hash-set! count x (- (hash-ref count x) 1))
    (when (= (hash-ref count x) 0)
      (hash-remove! count x)))
  (for ([x sorted])
    (while (and (< j n) (<= (- (list-ref sorted j) (list-ref sorted i)) k))
      (update-count (list-ref sorted j))
      (set! j (+ j 1)))
    (set! result (max result max-count))
    (remove-count (list-ref sorted i))
    (set! i (+ i 1)))
  result)