(define (split-array nums)
  (define n (length nums))
  (define prefix (make-vector n 0))
  (vector-set! prefix 0 (car nums))
  (for ([i (in-range 1 n)])
    (vector-set! prefix i (+ (vector-ref prefix (- i 1)) (list-ref nums i))))
  (define (sum l r)
    (- (vector-ref prefix r) (if (> l 0) (vector-ref prefix (- l 1)) 0)))
  (for ([i (in-range 1 (- n 1))])
    (when (and (= (sum 0 i) (sum (+ i 1) (- n 1)))
               (>= (sum 0 i) 1))
      (return #t)))
  #f)