#lang racket

(define (beautiful-towers heights)
  (define n (length heights))
  (define left (make-vector n 0))
  (define right (make-vector n 0))
  (define (max-increasing arr)
    (define res (make-vector (length arr) 0))
    (for ([i (in-range (length arr))])
      (when (> i 0)
        (when (< (list-ref arr i) (list-ref arr (sub1 i)))
          (vector-set! res i (+ (vector-ref res (sub1 i)) 1)))))
    res)
  (define (max-decreasing arr)
    (define res (make-vector (length arr) 0))
    (for ([i (in-range (sub1 (length arr)) -1 -1)])
      (when (< (list-ref arr i) (list-ref arr (add1 i)))
        (vector-set! res i (+ (vector-ref res (add1 i)) 1)))))
    res)
  (define left-vec (max-increasing heights))
  (define right-vec (max-decreasing heights))
  (for/sum ([i (in-range n)])
    (+ (vector-ref left-vec i) (vector-ref right-vec i))))