#lang racket

(define (maximum-triplet-value nums)
  (define n (length nums))
  (define max-values (make-vector n 0))
  (define max-so-far 0)
  (for ([i (in-range (sub1 n) -1 -1)])
    (vector-set! max-values i max-so-far)
    (when (> (list-ref nums i) max-so-far)
      (set! max-so-far (list-ref nums i))))
  (define result 0)
  (define current-max 0)
  (for ([i (in-range n)])
    (when (> (list-ref nums i) current-max)
      (set! current-max (list-ref nums i)))
    (when (< i (- n 1))
      (set! result (max result (+ (* (list-ref nums i) (vector-ref max-values (add1 i))) (- current-max (list-ref nums i))))))
    (when (< i (- n 2))
      (set! result (max result (+ (* (list-ref nums i) (vector-ref max-values (add1 i))) (- current-max (list-ref nums i)))))))
  result)