(define (rename-columns df)
  (define cols (vector-ref df 0))
  (define data (vector-drop df 1))
  (define new-cols (list "student_id" "name" "age"))
  (define (rename-row row)
    (map list-ref row (range 0 (length new-cols))))
  (vector-set! df 0 new-cols)
  (for-each (lambda (i) (vector-set! df (+ i 1) (rename-row (vector-ref df (+ i 1))))) (range 0 (vector-length data)))
  df)