#lang racket

(define (longest-unequal-adjacent-groups-subsequence n s)
  (define dp (make-vector n 1))
  (define prev (make-vector n #f))
  (define last (make-hash))
  (for ([i (in-range n)])
    (when (hash-has-key? last (vector-ref s i))
      (let ([p (hash-ref last (vector-ref s i))])
        (when (< (vector-ref dp p) (vector-ref dp i))
          (vector-set! dp i (vector-ref dp p))
          (vector-set! prev i p))))
    (hash-set! last (vector-ref s i) i))
  (define res '())
  (let loop ([i (vector-length dp -1)])
    (when (not (zero? i))
      (set! res (cons (vector-ref s i) res))
      (loop (vector-ref prev i))))
  res)