(define/contract (find-indices nums index difference)
  (-> (listof exact-integer?) exact-integer? exact-integer? (listof exact-integer?))
  (let loop ([i 0])
    (if (>= i (length nums))
        '()
        (let ([val (list-ref nums i)])
          (if (and (<= (abs (- i index)) difference) (<= (abs (- val (list-ref nums index))) difference))
              (list i index)
              (loop (+ i 1)))))))