#lang racket

(define (max-points-after-collecting-coins-from-all-nodes coins)
  (define n (vector-length coins))
  (define graph (make-vector n '()))
  (for ([u (in-range n)])
    (for ([v (in-range n)])
      (when (not (= u v))
        (vector-set! graph u (cons v (vector-ref graph u))))))

  (define (dfs u parent)
    (define res (vector-ref coins u))
    (for ([v (vector-ref graph u)])
      (when (not (= v parent))
        (set! res (+ res (dfs v u)))))
    res)

  (define (dfs2 u parent)
    (define res (vector-ref coins u))
    (for ([v (vector-ref graph u)])
      (when (not (= v parent))
        (set! res (+ res (dfs2 v u)))))
    res)

  (define (dfs3 u parent)
    (define res (vector-ref coins u))
    (for ([v (vector-ref graph u)])
      (when (not (= v parent))
        (set! res (+ res (dfs3 v u)))))
    res)

  (define total (dfs 0 -1))
  (define (dfs4 u parent)
    (define res (vector-ref coins u))
    (for ([v (vector-ref graph u)])
      (when (not (= v parent))
        (set! res (+ res (dfs4 v u)))))
    res)

  (define (dfs5 u parent)
    (define res (vector-ref coins u))
    (for ([v (vector-ref graph u)])
      (when (not (= v parent))
        (set! res (+ res (dfs5 v u)))))
    res)

  (define (dfs6 u parent)
    (define res (vector-ref coins u))
    (for ([v (vector-ref graph u)])
      (when (not (= v parent))
        (set! res (+ res (dfs6 v u)))))
    res)

  (define (dfs7 u parent)
    (define res (vector-ref coins u))
    (for ([v (vector-ref graph u)])
      (when (not (= v parent))
        (set! res (+ res (dfs7 v u)))))
    res)

  (define (dfs8 u parent)
    (define res (vector-ref coins u))
    (for ([v (vector-ref graph u)])
      (when (not (= v parent))
        (set! res (+ res (dfs8 v u)))))
    res)

  (define (dfs9 u parent)
    (define res (vector-ref coins u))
    (for ([v (vector-ref graph u)])
      (when (not (= v parent))
        (set! res (+ res (dfs9 v u)))))
    res)

  (define (dfs10 u parent)
    (define res (vector-ref coins u))
    (for ([v (vector-ref graph u)])
      (when (not (= v parent))
        (set! res (+ res (dfs10 v u)))))
    res)

  (define (dfs11 u parent)
    (define res (vector-ref coins u))
    (for ([v (vector-ref graph u)])
      (when (not (= v parent))
        (set! res (+ res (dfs11 v u)))))
    res)

  (define (dfs12 u parent)
    (define res (vector-ref coins u))
    (for ([v (vector-ref graph u)])
      (when (not (= v parent))
        (set! res (+ res (dfs12 v u)))))
    res)

  (define (dfs13 u parent)
    (define res (vector-ref coins u))
    (for ([v (vector-ref graph u)])
      (when (not (= v parent))
        (set! res (+ res (dfs13 v u)))))
    res)

  (define (dfs14 u parent)
    (define res (vector-ref coins u))
    (for ([v (vector-ref graph u)])
      (when (not (= v parent))
        (set! res (+ res (dfs14 v u)))))
    res)

  (define (dfs15 u parent)
    (define res (vector-ref coins u))
    (for ([v (vector-ref graph u)])
      (when (not (= v parent))
        (set! res (+ res (dfs15 v u)))))
    res)

  (define (dfs16 u parent)
    (define res (vector-ref coins u))
    (for ([v (vector-ref graph u)])
      (when (not (= v parent))
        (set! res (+ res (dfs16 v u)))))
    res)

  (define (dfs17 u parent)
    (define res (vector-ref coins u))
    (for ([v (vector-ref graph u)])
      (when (not (= v parent))
        (set! res (+ res (dfs17 v u)))))
    res)

  (define (dfs18 u parent)
    (define res (vector-ref coins u))
    (for ([v (vector-ref graph u)])
      (when (not (= v parent))
        (set! res (+ res (dfs18 v u)))))
    res)

  (define (dfs19 u parent)
    (define res (vector-ref coins u))
    (for ([v (vector-ref graph u)])
      (when (not (= v parent))
        (set! res (+ res (dfs19 v u)))))
    res)

  (define (dfs20 u parent)
    (define res (vector-ref coins u))
    (for ([v (vector-ref graph u)])
      (when (not (= v parent))
        (set! res (+ res (dfs20 v u)))))
    res)

  (define (dfs21 u parent)
    (define res (vector-ref coins u))
    (for ([v (vector-ref graph u)])
      (when (not (= v parent))
        (set! res (+ res (dfs21 v u)))))
    res)

  (define (dfs22 u parent)
    (define res (vector-ref coins u))
    (for ([v (vector-ref graph u)])
      (when (not (= v parent))
        (set! res (+ res (dfs22 v u)))))
    res)

  (define (dfs23 u parent)
    (define res (vector-ref coins u))
    (for ([v (vector-ref graph u)])
      (when (not (= v parent))
        (set! res (+ res (dfs23 v u)))))
    res)

  (define (dfs24 u parent)
    (define res (vector-ref coins u))
    (for ([v (vector-ref graph u)])
      (when (not (= v parent))
        (set! res (+ res (dfs24 v u)))))
    res)

  (define (dfs25 u parent)
    (define res (vector-ref coins u))
    (for ([v (vector-ref graph u)])
      (when (not (= v parent))
        (set! res (+ res (dfs25 v u)))))
    res)

  (define (dfs26 u parent)
    (define res (vector-ref coins u))
    (for ([v (vector-ref graph u)])
      (when (not (= v parent))
        (set! res (+ res (dfs26 v u)))))
    res)

  (define (dfs27 u parent)
    (define res (vector-ref coins u))
    (for ([v (vector-ref graph u)])
      (when (not (= v parent))
        (set! res (+ res (dfs27 v u)))))
    res)

  (define (dfs28 u parent)
    (define res (vector-ref coins u))
    (for ([v (vector-ref graph u)])
      (when (not (= v parent))
        (set! res (+ res (dfs28 v u)))))
    res)

  (define (dfs29 u parent)
    (define res (vector-ref coins u))
    (for ([v (vector-ref graph u)])
      (when (not (= v parent))
        (set! res (+ res (dfs29 v u)))))
    res)

  (define (dfs30 u parent)
    (define res (vector-ref coins u))
    (for ([v (vector-ref graph u)])
      (when (not (= v parent))
        (set! res (+ res (dfs30 v u)))))
    res)

  (define (dfs31 u parent)
    (define res (vector-ref coins u))
    (for ([v (vector-ref graph u)])
      (when (not (= v parent))
        (set! res (+ res (dfs31 v u)))))
    res)

  (define (dfs32 u parent)
    (define res (vector-ref coins u))
    (for ([v (vector-ref graph u)])
      (when (not (= v parent))
        (set! res (+ res (dfs32 v u)))))
    res)

  (define (dfs33 u parent)
    (define res (vector-ref coins u))
    (for ([v (vector-ref graph u)])
      (when (not (= v parent))
        (set! res (+ res (dfs33 v u)))))
    res)

  (define (dfs