(define (find-champion n edges)
  (define adj (make-hash))
  (for ([i (in-range n)])
    (hash-set! adj i '()))
  (for ([edge (in-list edges)])
    (define u (car edge))
    (define v (cadr edge))
    (hash-set! adj u (cons v (hash-ref adj u))))
  (define in-degree (make-hash))
  (for ([i (in-range n)])
    (hash-set! in-degree i 0))
  (for ([edge (in-list edges)])
    (define v (cadr edge))
    (hash-set! in-degree v (+ 1 (hash-ref in-degree v))))
  (define candidates (filter (lambda (i) (= 0 (hash-ref in-degree i))) (range n)))
  (if (= 1 (length candidates))
      (car candidates)
      #f))