#lang racket

(define (find-champion n edges)
  (define adj (make-hash))
  (for ([i (in-range n)])
    (hash-set! adj i '()))
  (for ([edge edges])
    (define u (car edge))
    (define v (cadr edge))
    (hash-set! adj u (cons v (hash-ref adj u))))
  (define in-degree (make-hash))
  (for ([i (in-range n)])
    (hash-set! in-degree i 0))
  (for ([edge edges])
    (define v (cadr edge))
    (hash-set! in-degree v (+ 1 (hash-ref in-degree v))))
  (define q (queue))
  (for ([i (in-range n)])
    (when (= (hash-ref in-degree i) 0)
      (queue-add! q i)))
  (define result '())
  (let loop ()
    (when (not (queue-empty? q))
      (define u (queue-remove! q))
      (set! result (cons u result))
      (for ([v (hash-ref adj u)])
        (hash-set! in-degree v (- (hash-ref in-degree v) 1))
        (when (= (hash-ref in-degree v) 0)
          (queue-add! q v)))
      (loop)))
  (if (= (length result) n)
      (car result)
      -1))