(define (count-beautiful-substrings s)
  (define n (string-length s))
  (define vowels #(#\a #\e #\i #\o #\u))
  (define (is-vowel c)
    (member c vowels))
  (define count 0)
  (for ([i (in-range n)])
    (when (is-vowel (string-ref s i))
      (for ([j (in-range (+ i 1) n)])
        (when (and (is-vowel (string-ref s j))
                   (= (substring s i (+ j 1)) (reverse (substring s i (+ j 1)))))
          (set! count (+ count 1))))))
  count)