(define (get-nums s)
  (let ((count (make-vector 10 0)))
    (for-each (lambda (c) (vector-set! count (- (char->integer c) 48) (+ (vector-ref count (- (char->integer c) 48)) 1))) (string->list s))
    count))

(define (get-bulls-and-cows secret guess)
  (let* ((bulls 0)
         (secret-count (get-nums secret))
         (guess-count (get-nums guess))
         (i 0))
    (let loop ()
      (when (< i (string-length secret))
        (if (= (char->integer (string-ref secret i)) (char->integer (string-ref guess i)))
            (begin
              (set! bulls (+ bulls 1))
              (vector-set! secret-count (- (char->integer (string-ref secret i)) 48) (- (vector-ref secret-count (- (char->integer (string-ref secret i)) 48)) 1))
              (vector-set! guess-count (- (char->integer (string-ref guess i)) 48) (- (vector-ref guess-count (- (char->integer (string-ref guess i)) 48)) 1)))
            #f)
        (set! i (+ i 1))
        (loop)))
    (let ((cows (apply + (map (lambda (s g) (min s g)) (vector->list secret-count) (vector->list guess-count))))
      (string-append (number->string bulls) "A" (number->string cows) "B"))))

(define/contract (game-secret guess)
  (-> string? string? string?)
  (get-bulls-and-cows secret guess))