(define (powerful-integers x y max-sum)
  (define result '())
  (define (helper a b)
    (when (<= (+ a b) max-sum)
      (set! result (cons (+ a b) result))))
  (let loop ([a 1])
    (when (<= a (expt x 20))
      (let loop2 ([b 1])
        (when (<= b (expt y 20))
          (helper a b)
          (loop2 (* b y))))
      (loop (* a x))))
  (remove-duplicates result))