(define (modify-matrix matrix)
  (define n (length matrix))
  (define m (length (car matrix)))
  (define result (make-list n (make-list m 0)))
  (define (get-value i j)
    (if (and (>= i 0) (< i n) (>= j 0) (< j m))
        (list-ref (list-ref matrix i) j)
        0))
  (define (set-value i j val)
    (set! result (list-set result i (list-set (list-ref result i) j val))))
  (for ([i (in-range n)])
    (for ([j (in-range m)])
      (let ([val (get-value i j)])
        (if (= val 0)
            (begin
              (set-value i j (+ (get-value (- i 1) j) (get-value (+ i 1) j) (get-value i (- j 1)) (get-value i (+ j 1)))))
            (set-value i j val)))))
  result)