(define (nth-super-ugly-number n primes)
  (define ugly (make-vector n 1))
  (define indices (make-vector (length primes) 0))
  (define (get-min)
    (let loop ([i 0] [min-val (vector-ref ugly 0)])
      (if (= i (vector-length primes))
          min-val
          (loop (+ i 1) (min min-val (vector-ref ugly (+ (vector-ref indices i) 1))))))
    )
  (define (update-indices)
    (for-each (lambda (i)
                (when (= (vector-ref ugly (+ (vector-ref indices i) 1)) (vector-ref primes i))
                  (vector-set! indices i (+ (vector-ref indices i) 1))))
              (range (vector-length primes)))
    )
  (for ([i (in-range 1 n)])
    (vector-set! ugly i (get-min))
    (update-indices))
  (vector-ref ugly (- n 1)))