#lang racket

(define (minimum-substring-partition s)
  (define n (string-length s))
  (define freq (make-hash))
  (define (get-freq c)
    (hash-ref freq c 0))
  (define (set-freq c v)
    (hash-set! freq c v))
  (for ([c (in-string s)])
    (set-freq c (+ (get-freq c) 1)))
  (define target (car (reverse (sort (hash-values freq) >))))
  (define result 0)
  (define current-freq (make-hash))
  (define (check)
    (for/and ([k (in-hash-keys freq)])
      (= (get-freq k) (hash-ref current-freq k 0))))
  (define (reset)
    (hash-clear current-freq))
  (define i 0)
  (define j 0)
  (define (add-char c)
    (set-freq c (+ (get-freq c) 1)))
  (define (remove-char c)
    (set-freq c (- (get-freq c) 1)))
  (define (count)
    (for/sum ([v (in-hash-values current-freq)])
      v))
  (define (valid?)
    (andmap (lambda (k) (= (hash-ref current-freq k 0) (get-freq k))) (hash-keys freq)))
  (let loop ()
    (when (< j n)
      (add-char (string-ref s j))
      (set-freq (string-ref s j) (+ (get-freq (string-ref s j)) 1))
      (set! j (+ j 1))
      (when (valid?)
        (set! result (min result (- j i)))
        (loop))
      (loop)))
  (if (= result 0) n result))