(define (find-permutation-difference s t)
  (define (char->index c)
    (- (char->integer c) (char->integer #\a)))
  (define s-indexes (for/vector #:length 26 ([i (in-range 26)]) 0))
  (define t-indexes (for/vector #:length 26 ([i (in-range 26)]) 0))
  (for ([i (in-range (string-length s))])
    (vector-set! s-indexes (char->index (string-ref s i)) i))
  (for ([i (in-range (string-length t))])
    (vector-set! t-indexes (char->index (string-ref t i)) i))
  (for/sum ([i (in-range 26)])
    (abs (- (vector-ref s-indexes i) (vector-ref t-indexes i)))))