(define (longest-valid-parentheses s)
  (define n (string-length s))
  (define dp (make-vector n 0))
  (define max-length 0)
  (for ([i (in-range 1 n)])
    (when (char=? (string-ref s i) #\))
      (when (char=? (string-ref s (- i 1)) #\())
        (vector-set! dp i (+ (if (> i 1) (vector-ref dp (- i 2)) 0) 2))
        (set! max-length (max max-length (vector-ref dp i))))
      (when (and (>= i 2) (char=? (string-ref s (- i 1)) #\)) (char=? (string-ref s (- i 2)) #\()))
        (let ([prev (vector-ref dp (- i 1))])
          (vector-set! dp i (+ prev (vector-ref dp (- i prev 1)) 2))
          (set! max-length (max max-length (vector-ref dp i))))))
  max-length)