(define (generate-binary-strings n)
  (define (backtrack s)
    (if (= (string-length s) n)
        (list s)
        (append (if (or (null? s) (not (char=? #\0 (string-ref s (- (string-length s) 1)))))
                   (backtrack (string-append s "0"))
                   '())
               (backtrack (string-append s "1")))))
  (backtrack ""))