(define (minimum-length-after-operations s)
  (define (helper s)
    (if (or (null? s) (null? (cdr s)))
        (length s)
        (let ((a (car s)) (b (cadr s)))
          (if (equal? a b)
              (helper (append (cddr s) (list (if (char=? a #\a) #\c (if (char=? a #\b) #\a #\b)))))
              (helper (cdr s))))))
  (helper (string->list s)))