(define (count-k-constraint s k)
  (define n (string-length s))
  (define (is-valid? a b)
    (and (<= (char->integer a) (+ (char->integer #\a) k))
         (<= (char->integer b) (+ (char->integer #\a) k))))
  (define count 0)
  (for ([i (in-range n)])
    (for ([j (in-range i n)])
      (define a (string-ref s i))
      (define b (string-ref s j))
      (when (is-valid? a b)
        (set! count (+ count 1)))))
  count)