(define (max-multiplication-score nums1 nums2)
  (define (score a b)
    (for/sum ([x a] [y b]) (* x y)))
  (define len (length nums1))
  (define max-score -inf.0)
  (for ([i (in-range len)])
    (define rotated (append (drop nums1 i) (take nums1 i)))
    (define current-score (score rotated nums2))
    (set! max-score (max max-score current-score)))
  max-score)