#lang racket

(define (count-substrings s p)
  (define len-p (string-length p))
  (define len-s (string-length s))
  (define (char->index c) (- (char->integer c) (char->integer #\a)))
  (define (get-counts str)
    (define counts (make-vector 26 0))
    (for ([c str])
      (vector-set! counts (char->index c) (+ (vector-ref counts (char->index c)) 1)))
    counts)
  (define p-counts (get-counts p))
  (define window-counts (make-vector 26 0))
  (for ([i (in-range len-p)])
    (vector-set! window-counts (char->index (string-ref s i)) (+ (vector-ref window-counts (char->index (string-ref s i))) 1)))
  (define result 0)
  (when (equal? window-counts p-counts) (set! result (+ result 1)))
  (for ([i (in-range len-p len-s)])
    (vector-set! window-counts (char->index (string-ref s (- i 1))) (- (vector-ref window-counts (char->index (string-ref s (- i 1)))) 1))
    (vector-set! window-counts (char->index (string-ref s i)) (+ (vector-ref window-counts (char->index (string-ref s i))) 1))
    (when (equal? window-counts p-counts) (set! result (+ result 1))))
  result)