#lang racket

(define (find-lexicographical-sequence n)
  (define nums (range 1 (add1 n)))
  (define res '())
  (define (backtrack path used)
    (when (and (null? path) (= (length used) n))
      (set! res path)
      #t)
    (for ([i (in-range n)])
      (when (not (list-ref used i))
        (define num (+ i 1))
        (when (or (null? path) (= (modulo (last path) num) 0))
          (set! used (list-set used i #t))
          (set! path (append path (list num)))
          (when (backtrack path used)
            (return #t))
          (set! path (reverse (rest (reverse path))))
          (set! used (list-set used i #f)))))
    #f)
  (backtrack '() (make-list n #f))
  res)