(define (find-kth-character n k)
  (define (helper n k)
    (if (= n 1)
        (integer->char (+ 96 k))
        (let* ((prev (helper (- n 1) (quotient (+ k 1) 2)))
               (c (char->integer prev)))
          (if (even? k)
              (integer->char (+ 96 c))
              (integer->char (+ 96 (- 26 c)))))))
  (char->integer (helper n k)))