#lang racket

(define (find-subtree-sizes-after-changes n edges)
  (define tree (make-hash))
  (for ([i (in-range n)])
    (hash-set! tree i '()))
  (for ([e (in-list edges)])
    (define u (car e))
    (define v (cadr e))
    (hash-set! tree u (cons v (hash-ref tree u)))
    (hash-set! tree v (cons u (hash-ref tree v))))
  (define parent (make-vector n -1))
  (define size (make-vector n 1))
  (define visited (make-vector n #f))
  (define (dfs u p)
    (vector-set! parent u p)
    (vector-set! visited u #t)
    (for ([v (hash-ref tree u)])
      (when (not (vector-ref visited v))
        (dfs v u)
        (vector-set! size u (+ (vector-ref size u) (vector-ref size v))))))
  (dfs 0 -1)
  (define res (make-vector n 0))
  (define (post-dfs u)
    (for ([v (hash-ref tree u)])
      (when (not (= (vector-ref parent v) u))
        (post-dfs v)
        (vector-set! res v (vector-ref size v))))
    (vector-set! res u (vector-ref size u))
    (for ([v (hash-ref tree u)])
      (when (not (= (vector-ref parent v) u))
        (vector-set! res u (- (vector-ref res u) (vector-ref res v))))))
  (post-dfs 0)
  (vector->list res))