#lang racket

(define (reverse-string s)
  (list->string (reverse (string->list s))))

(define (is-palindrome s)
  (equal? s (reverse-string s)))

(define (palindrome-pairs words)
  (define n (length words))
  (define word-map (for/hash ([i (in-range n)] [word words]) (values word i)))
  (define result '())
  (for ([i (in-range n)])
    (define word (list-ref words i))
    ((define len (string-length word))
    (for ([j (in-range (add1 len))])
      (define prefix (substring word 0 j))
      (define suffix (substring word j len))
      (when (is-palindrome prefix)
        (define suffix-rev (reverse-string suffix))
        (when (hash-has-key? word-map suffix-rev)
          (define k (hash-ref word-map suffix-rev))
          (unless (= k i)
            (set! result (cons (list k i) result)))))
      (when (is-palindrome suffix)
        (define prefix-rev (reverse-string prefix))
        (when (hash-has-key? word-map prefix-rev)
          (define k (hash-ref word-map prefix-rev))
          (unless (= k i)
            (set! result (cons (list i k) result))))))
  (reverse result))