(define (house-robber-iii root)
  (define (helper node)
    (if (not node)
        (values 0 0)
        (let* ((left (helper (car node)))
               (right (helper (cadr node)))
               (rob (+ (caddr node) (cdr left) (cdr right)))
               (not-rob (max (car left) (car right))))
          (values rob not-rob))))
  (car (helper root)))