#lang racket

(define (find-lexicographically-largest-string box)
  (define (char->int c) (- (char->integer c) (char->integer #\a)))
  (define (int->char i) (integer->char (+ i (char->integer #\a))))
  (define (swap! a i j)
    (let ((t (vector-ref a i)))
      (vector-set! a i (vector-ref a j))
      (vector-set! a j t)))
  (define (reverse! a start end)
    (let loop ((i start) (j end))
      (when (< i j)
        (swap! a i j)
        (loop (+ i 1) (- j 1)))))
  (define (get-max-digit digits)
    (let loop ((i 0) (max-d 0))
      (if (= i (vector-length digits))
          max-d
          (loop (+ i 1) (max max-d (vector-ref digits i))))))
  (define (get-min-digit digits)
    (let loop ((i 0) (min-d 9))
      (if (= i (vector-length digits))
          min-d
          (loop (+ i 1) (min min-d (vector-ref digits i))))))
  (define (sort-desc! digits)
    (let loop ((i 0))
      (when (< i (vector-length digits))
        (let ((max-i (argmax (lambda (j) (vector-ref digits j)) (range i (vector-length digits)))))
          (swap! digits i max-i)
          (loop (+ i 1))))))
  (define (get-digit-count digits d)
    (let loop ((i 0) (count 0))
      (if (= i (vector-length digits))
          count
          (loop (+ i 1) (+ count (if (= (vector-ref digits i) d) 1 0))))))
  (define (build-string digits)
    (list->string (map int->char (vector->list digits))))
  (define digits (list->vector (map char->int (string->list box))))
  (let ((max-digit (get-max-digit digits)))
    (if (= max-digit 9)
        (build-string digits)
        (let* ((min-digit (get-min-digit digits))
               (count-max (get-digit-count digits max-digit))
               (count-min (get-digit-count digits min-digit)))
          (if (> count-max count-min)
              (begin
                (sort-desc! digits)
                (build-string digits))
              (begin
                (let loop ((i 0))
                  (when (< i (vector-length digits))
                    (when (= (vector-ref digits i) min-digit)
                      (swap! digits i (vector-length digits))
                      (reverse! digits 0 (- (vector-length digits) 1)))
                    (loop (+ i 1))))
                (build-string digits)))))))