#lang racket

(define (find-pattern s p)
  (define n (string-length s))
  (define m (string-length p))
  (when (> m n) '())
  (define (kmp-failure)
    (define fail (make-vector m 0))
    (define j 0)
    (for ([i (in-range 1 m)])
      (set! j (vector-ref fail (- i 1)))
      (while (and (> j 0) (not (= (string-ref p i) (string-ref p j))))
        (set! j (vector-ref fail (- j 1))))
      (when (= (string-ref p i) (string-ref p j))
        (set! j (+ j 1)))
      (vector-set! fail i j))
    fail)
  (define fail (kmp-failure))
  (define res '())
  (define j 0)
  (for ([i (in-range n)])
    (set! j (vector-ref fail (- j 1)))
    (while (and (> j 0) (not (= (string-ref s i) (string-ref p j))))
      (set! j (vector-ref fail (- j 1))))
    (when (= (string-ref s i) (string-ref p j))
      (set! j (+ j 1)))
    (when (= j m)
      (set! j (vector-ref fail (- j 1)))
      (set! res (cons (- i m +1) res))))
  (reverse res))