#lang racket

(define (count-cells-in-overlapping-horizontal-and-vertical-substrings grid)
  (define rows (length grid))
  (define cols (if (> rows 0) (length (car grid)) 0))
  (define visited (make-hash))
  (define (is-valid r c)
    (and (<= 0 r (- rows 1)) (<= 0 c (- cols 1))))
  (define (mark-visited r c)
    (hash-set! visited (cons r c) #t))
  (define (is-visited r c)
    (hash-has-key? visited (cons r c)))
  (define (count-horizontal r c)
    (let loop ([c c] [count 0])
      (if (and (is-valid r c) (not (is-visited r c)))
          (begin
            (mark-visited r c)
            (loop (+ c 1) (+ count 1)))
          count)))
  (define (count-vertical r c)
    (let loop ([r r] [count 0])
      (if (and (is-valid r c) (not (is-visited r c)))
          (begin
            (mark-visited r c)
            (loop (+ r 1) (+ count 1)))
          count)))
  (define (process-cell r c)
    (when (and (is-valid r c) (not (is-visited r c)))
      (let ([h (count-horizontal r c)]
            [v (count-vertical r c)])
        (+ h v (- 1)))))
  (define total 0)
  (for ([r (in-range rows)])
    (for ([c (in-range cols)])
      (when (not (is-visited r c))
        (set! total (+ total (process-cell r c))))))
  total)