(define/contract (max-envelope enve)
  (-> (listof (listof exact-integer?)) exact-integer?)
  (let ((enve (sort enve (lambda (a b)
                           (if (= (car a) (car b))
                               (< (cadr a) (cadr b))
                               (< (car a) (car b)))))))
    (let loop ((enve enve) (dp '()))
      (if (null? enve)
          (length dp)
          (let ((h (caar enve)) (w (cadar enve)))
            (let ((idx (binary-search dp w)))
              (if (= idx (length dp))
                  (loop (cdr enve) (append dp (list w)))
                  (loop (cdr enve) (append (take dp idx) (list w) (drop dp (+ idx 1)))))))))))

(define (binary-search lst target)
  (let loop ((low 0) (high (length lst)))
    (if (>= low high)
        low
        (let ((mid (quotient (+ low high) 2)))
          (if (< (list-ref lst mid) target)
              (loop (+ mid 1) high)
              (loop low mid))))))