(define (lexicographically-smallest-string s)
  (define (helper lst)
    (if (null? lst)
        '()
        (let ((current (car lst)))
          (if (and (not (null? (cdr lst))) (= (char->integer current) (+ (char->integer (cadr lst)) 1)))
              (helper (cddr lst))
              (cons current (helper (cdr lst)))))))
  (list->string (helper (string->list s))))