(define (largest-divisible-subset nums)
  (define (cmp a b) (> a b))
  (define sorted (sort nums cmp))
  (define n (length sorted))
  (define dp (make-vector n 1))
  (define prev (make-vector n -1))
  (define max-len 1)
  (define max-index 0)
  (for ([i (in-range n)])
    (for ([j (in-range i)])
      (when (and (= (remainder (vector-ref sorted i) (vector-ref sorted j)) 0)
                 (> (+ (vector-ref dp j) 1) (vector-ref dp i)))
        (vector-set! dp i (+ (vector-ref dp j) 1))
        (vector-set! prev i j)))
    (when (> (vector-ref dp i) max-len)
      (set! max-len (vector-ref dp i))
      (set! max-index i)))
  (define result '())
  (let loop ([i max-index])
    (when (>= i 0)
      (set! result (cons (vector-ref sorted i) result))
      (loop (vector-ref prev i))))
  result)