(define (rotate-function nums)
  (let* ((n (length nums))
         (sum (apply + nums))
         (f (for/fold ((f 0)) ((i (in-range n)))
              (+ f (* i (list-ref nums i)))))
         (result (make-vector n 0)))
    (vector-set! result 0 f)
    (for/fold ((prev f)) ((i (in-range 1 n)))
      (let ((new-f (- (+ prev sum) (* n (list-ref nums (- n i))))))
        (vector-set! result i new-f)
        new-f))
    (vector-ref result (- n 1))))