(define (first-missing-positive nums)
  (define n (length nums))
  (for ([i (in-range n)])
    (let ([num (list-ref nums i)])
      (when (and (<= 1 num n) (not (= num (list-ref nums (sub1 num)))))
        (let ([temp (list-ref nums (sub1 num))])
          (list-set! nums (sub1 num) num)
          (list-set! nums i temp)))))
  (for ([i (in-range n)])
    (when (not (= (list-ref nums i) (add1 i)))
      (return (add1 i))))
  (add1 n))