(define (is-match s p)
  (define (helper s p)
    (cond ((and (null? s) (null? p)) #t)
          ((null? p) #f)
          ((null? s) (and (char=? (car p) #\*) (helper s (cdr p))))
          (else
           (cond ((char=? (car p) #\*)
                  (or (helper (cdr s) p)
                      (helper (cdr s) (cdr p))
                      (helper s (cdr p))))
                 ((char=? (car p) #\?)
                  (helper (cdr s) (cdr p)))
                 ((char=? (car s) (car p))
                  (helper (cdr s) (cdr p)))
                 (else #f)))))
  (helper (string->list s) (string->list p)))