(define (num-of-arithmetic-slices nums)
  (define n (length nums))
  (define dp (make-vector n #f))
  (define (init-dp i)
    (vector-set! dp i (make-hash)))
  (for-each init-dp (range n))
  (define (get-count i j)
    (hash-ref (vector-ref dp i) j 0))
  (define (add-count i j v)
    (hash-set! (vector-ref dp i) j (+ (get-count i j) v)))
  (define res 0)
  (for ([i (in-range n)])
    (for ([j (in-range i)])
      (define diff (- (list-ref nums i) (list-ref nums j)))
      (define cnt (get-count j diff))
      (set! res (+ res cnt))
      (add-count i diff cnt)))
  res)