(define (find-content-children g s)
  (define (sort-list lst)
    (if (null? lst)
        '()
        (let ((pivot (car lst)))
          (append (sort-list (filter (lambda (x) (< x pivot)) (cdr lst)))
                  (list pivot)
                  (sort-list (filter (lambda (x) (>= x pivot)) (cdr lst)))))))
  (define sorted-g (sort-list g))
  (define sorted-s (sort-list s))
  (define (helper g-sorted s-sorted count)
    (cond ((or (null? g-sorted) (null? s-sorted)) count)
          ((<= (car g-sorted) (car s-sorted))
           (helper (cdr g-sorted) (cdr s-sorted) (+ count 1)))
          (else (helper g-sorted (cdr s-sorted) count))))
  (helper sorted-g sorted-s 0))