#lang racket

(define (circular-array-loop nums)
  (define n (length nums))
  (define visited (make-vector n #f))

  (define (is-circular i)
    (define direction (> (vector-ref nums i) 0))
    (define slow i)
    (define fast i)
    (let loop ()
      (set! slow (modulo (+ slow (vector-ref nums slow)) n))
      (set! fast (modulo (+ fast (vector-ref nums fast)) n))
      (when (or (not (= (vector-ref nums fast) 0))
                (not (equal? (> (vector-ref nums fast) 0) direction)))
        (set! fast (modulo (+ fast (vector-ref nums fast)) n)))
      (when (and (not (equal? (> (vector-ref nums fast) 0) direction))
                 (not (= (vector-ref nums fast) 0)))
        (set! fast (modulo (+ fast (vector-ref nums fast)) n)))
      (when (and (not (equal? (> (vector-ref nums fast) 0) direction))
                 (not (= (vector-ref nums fast) 0)))
        (set! fast (modulo (+ fast (vector-ref nums fast)) n)))
      (when (and (not (equal? (> (vector-ref nums fast) 0) direction))
                 (not (= (vector-ref nums fast) 0)))
        (set! fast (modulo (+ fast (vector-ref nums fast)) n)))
      (when (and (not (equal? (> (vector-ref nums fast) 0) direction))
                 (not (= (vector-ref nums fast) 0)))
        (set! fast (modulo (+ fast (vector-ref nums fast)) n)))
      (when (and (not (equal? (> (vector-ref nums fast) 0) direction))
                 (not (= (vector-ref nums fast) 0)))
        (set! fast (modulo (+ fast (vector-ref nums fast)) n)))
      (when (and (not (equal? (> (vector-ref nums fast) 0) direction))
                 (not (= (vector-ref nums fast) 0)))
        (set! fast (modulo (+ fast (vector-ref nums fast)) n)))
      (when (and (not (equal? (> (vector-ref nums fast) 0) direction))
                 (not (= (vector-ref nums fast) 0)))
        (set! fast (modulo (+ fast (vector-ref nums fast)) n)))
      (when (and (not (equal? (> (vector-ref nums fast) 0) direction))
                 (not (= (vector-ref nums fast) 0)))
        (set! fast (modulo (+ fast (vector-ref nums fast)) n)))
      (when (and (not (equal? (> (vector-ref nums fast) 0) direction))
                 (not (= (vector-ref nums fast) 0)))
        (set! fast (modulo (+ fast (vector-ref nums fast)) n)))
      (when (and (not (equal? (> (vector-ref nums fast) 0) direction))
                 (not (= (vector-ref nums fast) 0)))
        (set! fast (modulo (+ fast (vector-ref nums fast)) n)))
      (when (and (not (equal? (> (vector-ref nums fast) 0) direction))
                 (not (= (vector-ref nums fast) 0)))
        (set! fast (modulo (+ fast (vector-ref nums fast)) n)))
      (when (and (not (equal? (> (vector-ref nums fast) 0) direction))
                 (not (= (vector-ref nums fast) 0)))
        (set! fast (modulo (+ fast (vector-ref nums fast)) n)))
      (when (and (not (equal? (> (vector-ref nums fast) 0) direction))
                 (not (= (vector-ref nums fast) 0)))
        (set! fast (modulo (+ fast (vector-ref nums fast)) n)))
      (when (and (not (equal? (> (vector-ref nums fast) 0) direction))
                 (not (= (vector-ref nums fast) 0)))
        (set! fast (modulo (+ fast (vector-ref nums fast)) n)))
      (when (and (not (equal? (> (vector-ref nums fast) 0) direction))
                 (not (= (vector-ref nums fast) 0)))
        (set! fast (modulo (+ fast (vector-ref nums fast)) n)))
      (when (and (not (equal? (> (vector-ref nums fast) 0) direction))
                 (not (= (vector-ref nums fast) 0)))
        (set! fast (modulo (+ fast (vector-ref nums fast)) n)))
      (when (and (not (equal? (> (vector-ref nums fast) 0) direction))
                 (not (= (vector-ref nums fast) 0)))
        (set! fast (modulo (+ fast (vector-ref nums fast)) n)))
      (when (and (not (equal? (> (vector-ref nums fast) 0) direction))
                 (not (= (vector-ref nums fast) 0)))
        (set! fast (modulo (+ fast (vector-ref nums fast)) n)))
      (when (and (not (equal? (> (vector-ref nums fast) 0) direction))
                 (not (= (vector-ref nums fast) 0)))
        (set! fast (modulo (+ fast (vector-ref nums fast)) n)))
      (when (and (not (equal? (> (vector-ref nums fast) 0) direction))
                 (not (= (vector-ref nums fast) 0)))
        (set! fast (modulo (+ fast (vector-ref nums fast)) n)))
      (when (and (not (equal? (> (vector-ref nums fast) 0) direction))
                 (not (= (vector-ref nums fast) 0)))
        (set! fast (modulo (+ fast (vector-ref nums fast)) n)))
      (when (and (not (equal? (> (vector-ref nums fast) 0) direction))
                 (not (= (vector-ref nums fast) 0)))
        (set! fast (modulo (+ fast (vector-ref nums fast)) n)))
      (when (and (not (equal? (> (vector-ref nums fast) 0) direction))
                 (not (= (vector-ref nums fast) 0)))
        (set! fast (modulo (+ fast (vector-ref nums fast)) n)))
      (when (and (not (equal? (> (vector-ref nums fast) 0) direction))
                 (not (= (vector-ref nums fast) 0)))
        (set! fast (modulo (+ fast (vector-ref nums fast)) n)))
      (when (and (not (equal? (> (vector-ref nums fast) 0) direction))
                 (not (= (vector-ref nums fast) 0)))
        (set! fast (modulo (+ fast (vector-ref nums fast)) n)))
      (when (and (not (equal? (> (vector-ref nums fast) 0) direction))
                 (not (= (vector-ref nums fast) 0)))
        (set! fast (modulo (+ fast (vector-ref nums fast)) n)))
      (when (and (not (equal? (> (vector-ref nums fast) 0) direction))
                 (not (= (vector-ref nums fast) 0)))
        (set! fast (modulo (+ fast (vector-ref nums fast)) n)))
      (when (and (not (equal? (> (vector-ref nums fast) 0) direction))
                 (not (= (vector-ref nums fast) 0)))
        (set! fast (modulo (+ fast (vector-ref nums fast)) n)))
      (when (and (not (equal? (> (vector-ref nums fast) 0) direction))
                 (not (= (vector-ref nums fast) 0)))
        (set! fast (modulo (+ fast (vector-ref nums fast)) n)))
      (when (and (not (equal? (> (vector-ref nums fast) 0) direction))
                 (not (= (vector-ref nums fast) 0)))
        (set! fast (modulo (+ fast (vector-ref nums fast)) n)))
      (when (and (not (equal? (> (vector-ref nums fast) 0) direction))
                 (not (= (vector-ref nums fast) 0)))
        (set! fast (modulo (+ fast (vector-ref nums fast)) n)))
      (when (and (not (equal? (> (vector-ref nums fast) 0) direction))
                 (not (= (vector-ref nums fast) 0)))
        (set! fast (modulo (+ fast (vector-ref nums fast)) n)))
      (when (and (not (equal? (> (vector-ref nums fast) 0) direction))
                 (not (= (vector-ref nums fast) 0)))
        (set! fast (modulo (+ fast (vector-ref nums fast)) n)))
      (when (and (not (equal? (> (vector-ref nums fast) 0) direction))
                 (not (= (vector-ref nums fast) 0)))
        (set! fast (modulo (+ fast (vector-ref nums fast)) n)))
      (when (and (not (equal? (> (vector-ref nums fast) 0) direction))
                 (not (= (vector-ref nums fast) 0)))
        (set! fast (modulo (+ fast (vector-ref nums fast)) n)))
      (when (and (not (equal? (> (vector-ref nums fast)