(define (non-decreasing-subsequences nums)
  (define result '())
  (define (backtrack start path)
    (when (>= (length path) 2)
      (set! result (cons (reverse path) result)))
    (define prev #f)
    (for ([i (in-range start (length nums))])
      (when (or (not prev) (<= (list-ref nums i) prev))
        (set! prev (list-ref nums i))
        (backtrack (+ i 1) (cons (list-ref nums i) path)))))
  (backtrack 0 '())
  (reverse result))