(define (find-target-sum-ways nums target)
  (define (helper index sum count)
    (cond ((= index (length nums)) (if (= sum target) 1 0))
          (else (+ (helper (+ index 1) (+ sum (list-ref nums index)) count)
                   (helper (+ index 1) (- sum (list-ref nums index)) count)))))
  (helper 0 0 0))