(define (find-words words)
  (define row1 #{"q" "w" "e" "r" "t" "y" "u" "i" "o" "p"})
  (define row2 #{"a" "s" "d" "f" "g" "h" "j" "k" "l"})
  (define row3 #{"z" "x" "c" "v" "b" "n" "m"})
  (define (in-row? word row)
    (andmap (lambda (c) (set-member? row (string-downcase c))) word))
  (filter (lambda (word) (or (in-row? word row1) (in-row? word row2) (in-row? word row3))) words))