(define (update-board board click)
  (let ((m (length board))
        (n (length (car board))))
    (let ((i (car click)) (j (cadr click)))
      (if (or (>= i m) (>= j n) (< i 0) (< j 0))
          board
          (let ((cell (list-ref (list-ref board i) j)))
            (if (char=? cell #\M)
                (begin
                  (set! (list-ref (list-ref board i) j) #\X)
                  board)
                (if (char=? cell #\E)
                    (let ((count (count-mines board i j)))
                      (if (> count 0)
                          (set! (list-ref (list-ref board i) j) (integer->char (+ 48 count)))
                          (begin
                            (set! (list-ref (list-ref board i) j) #\B)
                            (for-each (lambda (dx)
                                        (for-each (lambda (dy)
                                                    (update-board board (list (+ i dx) (+ j dy))))
                                      '(1 -1 0)))
                            board))
                      board)
                    board)))))))

(define (count-mines board i j)
  (let ((m (length board))
        (n (length (car board)))
        (count 0))
    (for-each (lambda (dx)
                (for-each (lambda (dy)
                            (when (and (<= 0 (+ i dx) (- m 1))
                                       (<= 0 (+ j dy) (- n 1)))
                              (when (char=? (list-ref (list-ref board (+ i dx)) (+ j dy)) #\M)
                                (set! count (+ count 1)))))
              '(1 -1 0)))
    count))