(define (update-matrix matrix)
  (define rows (length matrix))
  (define cols (if (> rows 0) (length (car matrix)) 0))
  (define dist (make-vector rows (make-vector cols 0)))
  (define q (queue))
  (for ([i (in-range rows)])
    (for ([j (in-range cols)])
      (if (= (vector-ref (vector-ref matrix i) j) 0)
          (begin
            (vector-set! (vector-ref dist i) j 0)
            (enqueue! q (cons i j)))
          (vector-set! (vector-ref dist i) j +inf.0))))
  (define directions (list (cons 1 0) (cons -1 0) (cons 0 1) (cons 0 -1)))
  (let loop ()
    (when (not (queue-empty? q))
      (define current (dequeue! q))
      (define i (car current))
      (define j (cdr current))
      (for ([d directions])
        (define ni (+ i (car d)))
        (define nj (+ j (cdr d)))
        (when (and (<= 0 ni (- rows 1)) (<= 0 nj (- cols 1)) (< (vector-ref (vector-ref dist ni) nj) +inf.0))
          (when (> (vector-ref (vector-ref dist i) j) (sub1 (vector-ref (vector-ref dist ni) nj)))
            (vector-set! (vector-ref dist ni) nj (add1 (vector-ref (vector-ref dist i) j)))
            (enqueue! q (cons ni nj)))))
      (loop)))
  (vector->list dist))