(define (solve-equation equation)
  (define (parse-eq eq)
    (let ((parts (string-split eq #\=)))
      (list (parse-part (car parts)) (parse-part (cadr parts)))))

  (define (parse-part part)
    (let ((tokens (regexp-match* #px"([+-]?[0-9]*[a-z])|([+-]?[0-9]+)" part)))
      (let loop ((tokens tokens) (x-coef 0) (const 0))
        (if (null? tokens)
            (list x-coef const)
            (let* ((token (car tokens))
                   (num (if (string=? (substring token 0 1) "+")
                            (substring token 1)
                            (if (string=? (substring token 0 1) "-")
                                (string-append "-" (substring token 1))
                                token))))
              (if (char-alphabetic? (string-ref num 0))
                  (loop (cdr tokens) (+ x-coef (if (string=? num "x") 1 (string->number num))) const)
                  (loop (cdr tokens) x-coef (+ const (string->number num))))))))

  (let* ((eq (parse-eq equation))
         (left (car eq))
         (right (cadr eq))
         (x-coef (- (car left) (car right)))
         (const (- (cadr left) (cadr right))))
    (cond ((= x-coef 0)
           (if (= const 0) "Infinite solutions" "No solution"))
          ((= const 0)
           "x=0")
          (else
           (string-append "x=" (number->string (/ (- const) x-coef))))))