(define (find-error-numbers nums)
  (define n (length nums))
  (define arr (make-vector n 0))
  (define result '())
  (for-each (lambda (num)
              (vector-set! arr (sub1 num) (+ 1 (vector-ref arr (sub1 num)))))
            nums)
  (for-each (lambda (i)
              (when (= (vector-ref arr i) 2)
                (set! result (cons (+ i 1) result))))
            (range n))
  (for-each (lambda (i)
              (when (= (vector-ref arr i) 0)
                (set! result (cons (+ i 1) result))))
            (range n))
  (reverse result))