(define (image-smoother img)
  (define rows (length img))
  (define cols (if (> rows 0) (length (car img)) 0))
  (define (get-pixel r c)
    (if (and (>= r 0) (< r rows) (>= c 0) (< c cols))
        (list-ref (list-ref img r) c)
        0))
  (define (average r c)
    (let* ((sum (+ (get-pixel (- r 1) (- c 1))
                   (get-pixel (- r 1) c)
                   (get-pixel (- r 1) (+ c 1))
                   (get-pixel r (- c 1))
                   (get-pixel r c)
                   (get-pixel r (+ c 1))
                   (get-pixel (+ r 1) (- c 1))
                   (get-pixel (+ r 1) c)
                   (get-pixel (+ r 1) (+ c 1))))
           (count 9))
      (floor (/ sum count))))
  (define (row->new-row r)
    (map (lambda (c) (average r c)) (range cols)))
  (map row->new-row (range rows)))