#lang racket

(define (knight-probability n k start-x start-y)
  (define directions (list (cons 2 1) (cons 1 2) (cons -1 2) (cons -2 1)
                           (cons -2 -1) (cons -1 -2) (cons 1 -2) (cons 2 -1)))
  (define dp (make-vector n (make-vector n 0.0)))
  (vector-set! dp start-x start-y 1.0)
  (for ([step (in-range k)])
    (define next-dp (make-vector n (make-vector n 0.0)))
    (for ([i (in-range n)])
      (for ([j (in-range n)])
        (when (> (vector-ref (vector-ref dp i j) 0) 0)
          (for ([d directions])
            (define ni (+ i (car d)))
            (define nj (+ j (cdr d)))
            (when (and (>= ni 0) (< ni n) (>= nj 0) (< nj n))
              (vector-set! (vector-ref next-dp ni) nj (+ (vector-ref (vector-ref next-dp ni) nj) (/ (vector-ref (vector-ref dp i j) 0) 8)))))))
    (set! dp next-dp))
  (apply + (for*/sum ([i (in-range n)] [j (in-range n)]) (vector-ref (vector-ref dp i j) 0))))