(define (max-sum-of-3-non-overlapping-subarrays nums k)
  (define n (length nums))
  (define res (make-vector 1 0))
  (define left (make-vector n 0))
  (define right (make-vector n 0))
  (define (get-sum i j)
    (if (= i 0) (apply + (take nums j)) (apply + (take-right nums (- j i)))))
  (let loop ([i 0])
    (when (< i (- n k))
      (vector-set! left i (get-sum i (+ i k)))
      (loop (+ i 1))))
  (let loop ([i (- n k 1)])
    (when (>= i 0)
      (vector-set! right i (get-sum i (+ i k)))
      (loop (- i 1))))
  (let loop ([i k] [max-left 0])
    (when (< i (- n k))
      (set! max-left (max max-left (vector-ref left (- i k))))
      (let ([current (get-sum i (+ i k))])
        (let ([right-sum (vector-ref right (+ i k))])
          (vector-set! res 0 (max (vector-ref res 0) (+ max-left current right-sum)))))
      (loop (+ i 1) max-left)))
  (vector-ref res 0))