(define-struct node (key value next) #:mutable)

(define (make-hash-map)
  (let ((size 1000))
    (let ((buckets (make-vector size #f)))
      (lambda (msg . args)
        (cond ((eq? msg 'put)
               (let ((key (car args))
                     (value (cadr args)))
                 (let ((index (modulo key size)))
                   (let loop ((curr (vector-ref buckets index)))
                     (if (not curr)
                         (begin
                           (vector-set! buckets index (make-node key value (vector-ref buckets index)))
                           #t)
                         (if (= (node-key curr) key)
                             (begin
                               (set-node-value! curr value)
                               #t)
                             (loop (node-next curr)))))))
               #t)
              ((eq? msg 'get)
               (let ((key (car args)))
                 (let ((index (modulo key size)))
                   (let loop ((curr (vector-ref buckets index)))
                     (if (not curr)
                         -1
                         (if (= (node-key curr) key)
                             (node-value curr)
                             (loop (node-next curr)))))))
               #t)
              ((eq? msg 'remove)
               (let ((key (car args)))
                 (let ((index (modulo key size)))
                   (let loop ((prev (vector-ref buckets index))
                              (curr (vector-ref buckets index)))
                     (if (not curr)
                         #f
                         (if (= (node-key curr) key)
                             (begin
                               (vector-set! buckets index (node-next curr))
                               #t)
                             (loop curr (node-next curr)))))))
               #t)
              (else #f)))))

(define hash-map (make-hash-map))