#lang racket

(define (make-random-pick-with-blacklist n blacklist)
  (define blist (set->list (apply set blacklist)))
  (define len (length blist))
  (define m (- n len))
  (define map (make-hash))
  (define idx 0)
  (for ([x (in-range n)])
    (when (and (< idx len) (= x (list-ref blist idx)))
      (set! idx (+ idx 1))
      (when (< idx len)
        (hash-set! map x (list-ref blist idx))))
    (when (not (hash-has-key? map x))
      (hash-set! map x x)))
  (lambda ()
    (let ([rand (random n)])
      (if (hash-has-key? map rand)
          (hash-ref map rand)
          rand))))