(define (flood-fill image sr sc new-color)
  (define (in-bounds? r c)
    (and (<= 0 r (- (length image) 1))
         (<= 0 c (- (length (list-ref image 0)) 1))))
  (define (fill r c old-color)
    (when (and (in-bounds? r c)
               (equal? (list-ref (list-ref image r) c) old-color))
      (set! image (append (take image r)
                          (list (append (take (list-ref image r) c)
                                        (list new-color)
                                        (drop (list-ref image r) (+ c 1))))
                          (drop image (+ r 1))))
      (fill (+ r 1) c old-color)
      (fill (- r 1) c old-color)
      (fill r (+ c 1) old-color)
      (fill r (- c 1) old-color)))
  (let ((old-color (list-ref (list-ref image sr) sc)))
    (when (not (equal? old-color new-color))
      (fill sr sc old-color)))
  image)