(define/contract (daily-temperatures temperatures)
  (-> (listof exact-integer?) (listof exact-integer?))
  (let ((n (length temperatures))
        (stack '()))
    (define result (make-vector n 0))
    (for ([i (in-range n)])
      (let loop ()
        (when (and (not (null? stack)) (< (vector-ref temperatures (car stack)) (vector-ref temperatures i)))
          (vector-set! result (car stack) (- i (car stack)))
          (set! stack (cdr stack))
          (loop))))
    (vector->list result))