#lang racket

(define (min-window s t)
  (define len-s (string-length s))
  (define len-t (string-length t))
  (when (> len-s len-t) #f)
  (define count (make-hash))
  (for ([c (in-string t)])
    (hash-set! count c (+ 1 (hash-ref count c 0))))
  (define required (hash-count count))
  (define formed 0)
  (define left 0)
  (define min-len +inf.0)
  (define result (cons 0 0))
  (define window (make-hash))
  (for ([right (in-range len-s)])
    (define c (string-ref s right))
    (hash-set! window c (+ 1 (hash-ref window c 0)))
    (when (and (hash-has-key? count c) (= (hash-ref window c) (hash-ref count c)))
      (set! formed (+ formed 1)))
    (when (= formed required)
      (while (and (< left right) (not (hash-has-key? count (string-ref s left))))
        (hash-set! window (string-ref s left) (- (hash-ref window (string-ref s left)) 1))
        (set! left (+ left 1)))
      (when (< (- right left) min-len)
        (set! min-len (- right left))
        (set! result (cons left right)))))
  (if (equal? result (cons 0 0)) #f (substring s (car result) (+ 1 (cdr result)))))