#lang racket

(define (reorganize-string s)
  (define len (string-length s))
  (define freq (make-hash))
  (for ([c s])
    (hash-set! freq c (+ 1 (hash-ref freq c 0))))
  (define sorted-chars
    (sort (hash->list freq) (lambda (a b) (> (cdr a) (cdr b)))))
  (define max-char (car sorted-chars))
  (define max-count (cdr max-char))
  (when (> max-count (add1 (quotient len 2)))
    (void))
  (define result (make-vector len #\space))
  (define idx 0)
  (for ([pair sorted-chars])
    (define c (car pair))
    (define count (cdr pair))
    (for ([i (in-range count)])
      (vector-set! result idx c)
      (set! idx (add1 idx))
      (when (= idx len)
        (set! idx 0))))
  (apply string (vector->list result)))