(define (num-tiles n)
  (define mod 1000000007)
  (define dp (make-vector (+ n 1) 0))
  (vector-set! dp 0 1)
  (when (> n 0) (vector-set! dp 1 1))
  (when (> n 1) (vector-set! dp 2 2))
  (for ([i (in-range 3 (+ n 1))])
    (vector-set! dp i (modulo (+ (* 2 (vector-ref dp (- i 1))) (vector-ref dp (- i 3))) mod)))
  (vector-ref dp n))