(define (all-paths-from-source-to-target graph)
  (define target (sub1 (length graph)))
  (define (dfs node path result)
    (if (= node target)
        (set! result (cons (reverse path) result))
        (for-each (lambda (neighbor)
                    (dfs neighbor (cons neighbor path) result))
                  (vector-ref graph node))))
  (let ([result '()])
    (dfs 0 (list 0) result)
    result))