(define (unique-characters s)
  (define n (string-length s))
  (define count (make-vector n 0))
  (define prev (make-hash))
  (define (update-prev c i)
    (hash-set! prev c i))
  (define (get-prev c)
    (if (hash-has-key? prev c)
        (hash-ref prev c)
        -1))
  (for ([i (in-range n)])
    (let ([c (string-ref s i)])
      (vector-set! count i (- i (get-prev c)))
      (update-prev c i)))
  (define (get-next c)
    (if (hash-has-key? prev c)
        (hash-ref prev c)
        n))
  (define next (make-hash))
  (for ([i (in-range n -1 -1)])
    (let ([c (string-ref s i)])
      (vector-set! count i (+ (vector-ref count i) (- (get-next c) i)))
      (hash-set! next c i)))
  (apply + (vector->list count)))