(define (find-and-replace-in-string s mappings)
  (define (make-map mappings)
    (for/hash ([m mappings])
      (values (car m) (cadr m))))
  (define map (make-map mappings))
  (define len (string-length s))
  (define result (make-vector len #\space))
  (for ([i (in-range len)])
    (vector-set! result i (string-ref s i)))
  (for ([mappings mappings])
    (define start (car mappings))
    (define end (cadr mappings))
    (define replacement (caddr mappings))
    (when (and (<= start end) (<= end len))
      (for ([i (in-range start end)])
        (vector-set! result i #\space))
      (define replacement-len (string-length replacement))
      (define new-i start)
      (for ([c (in-string replacement)])
        (when (< new-i len)
          (vector-set! result new-i c)
          (set! new-i (+ new-i 1))))))
  (list->string (vector->list result)))