(define (car-fleet target positions speeds)
  (define (compare a b)
    (< (car a) (car b)))
  (define sorted (sort (map (lambda (p s) (cons p s)) positions speeds) compare))
  (define (helper stack)
    (if (null? sorted)
        (length stack)
        (let* ((pos (caar sorted))
               (speed (cdar sorted))
               (time (/ (- target pos) speed))
               (new-stack (if (null? stack)
                              (list time)
                              (let ((last-time (car stack)))
                                (if (<= time last-time)
                                    stack
                                    (cons time stack)))))
          (helper (cdr sorted)))))
  (helper '()))