(define (decode-at-index s index)
  (define len (string-length s))
  (define (get-decoded-length i)
    (if (= i len)
        0
        (let ((c (string-ref s i)))
          (if (char-numeric? c)
              (+ (get-decoded-length (add1 i)) (* (- (char->integer c) 48) (get-decoded-length i)))
              (+ 1 (get-decoded-length (add1 i)))))))
  (define (find-char i current-len)
    (if (= i 0)
        (string-ref s 0)
        (let ((c (string-ref s i)))
          (if (char-numeric? c)
              (let ((num (- (char->integer c) 48)))
                (if (> current-len index)
                    (find-char (sub1 i) (quotient current-len num))
                    (find-char (sub1 i) (- current-len (* num (get-decoded-length (add1 i)))))))
              (if (> current-len index)
                  (find-char (sub1 i) (- current-len 1))
                  (find-char (sub1 i) (- current-len 1)))))))
  (find-char (sub1 len) (get-decoded-length 0)))