(define (spiral-matrix-iii n)
  (define directions '([0 1] [1 0] [0 -1] [-1 0]))
  (define (next-direction d) (modulo (+ d 1) 4))
  (define (step x y dx dy k)
    (let ((x2 (+ x dx)) (y2 (+ y dy)))
      (if (and (<= 0 x2 n) (<= 0 y2 n))
          (cons (list x2 y2) (step x2 y2 dx dy (+ k 1)))
          (let* ((d (next-direction dx))
                 (new-dx (car (list-ref directions d)))
                 (new-dy (cadr (list-ref directions d))))
            (step x2 y2 new-dx new-dy (+ k 1)))))
  (let loop ((x 0) (y 0) (dx 0) (dy 1) (k 1) (result '()))
    (if (= k (* n n))
        (reverse result)
        (let ((new-x (+ x dx)) (new-y (+ y dy)))
          (loop new-x new-y dx dy (+ k 1) (cons (list new-x new-y) result))))))