(define (find-and-replace-pattern words pattern)
  (define (match? word p)
    (define (helper w p m)
      (cond ((and (null? w) (null? p)) #t)
            ((or (null? w) (null? p)) #f)
            ((and (equal? (car w) (car p)) (hash-has-key? m (car w)))
             (helper (cdr w) (cdr p) m))
            ((and (equal? (car w) (car p)) (not (hash-has-key? m (car w))))
             (helper (cdr w) (cdr p) (hash-set m (car w) (car p))))
            ((and (not (equal? (car w) (car p))) (hash-has-key? m (car w)))
             (if (equal? (hash-ref m (car w)) (car p))
                 (helper (cdr w) (cdr p) m)
                 #f))
            (else
             (if (hash-has-key? m (car p))
                 (if (equal? (hash-ref m (car p)) (car w))
                     (helper (cdr w) (cdr p) m)
                     #f)
                 (helper (cdr w) (cdr p) (hash-set m (car p) (car w)))))))
    (let ([m (make-hash)])
      (and (helper (string->list word) (string->list p) m)
           (helper (string->list p) (string->list word) (make-hash)))))
  (filter (lambda (w) (match? w pattern)) words))