(define (num-special-equivalent s)
  (define (char->index c)
    (- (char->integer c) (char->integer #\a)))
  (define (sort-odd-even s)
    (let ((odd (list))
          (even (list)))
      (for-each (lambda (i c)
                  (if (even? i)
                      (set! even (cons c even))
                      (set! odd (cons c odd))))
                (range (string-length s))
                (string->list s))
      (string (append (sort (list->vector odd) char<?)
                      (sort (list->vector even) char<?)))))
  (let ((groups (make-hash)))
    (for-each (lambda (s)
                (let ((key (sort-odd-even s)))
                  (hash-set! groups key #t)))
              (string-split s ","))
    (hash-count groups)))

(define (num-special-equivalent-group s)
  (num-special-equivalent s))