(define (allPossibleFBT n)
  (if (odd? n)
      (letrec ((memo (make-hash)))
        (define (helper m)
          (if (= m 1)
              (list (cons 'TreeNode '()))
              (hash-ref memo m (lambda ()
                                 (let ((result '()))
                                   (for ([i (in-range 1 m 2)])
                                     (for-each (lambda (left)
                                                 (for-each (lambda (right)
                                                             (set! result (cons (cons 'TreeNode (cons left (cons right '()))) result)))
                                               (helper (- m i 1))))
                                   (hash-set! memo m result)
                                   result))))
        (helper n))
      '()))