#lang racket

(define (snakes-and-ladders board)
  (define n (length board))
  (define visited (make-hash))
  (define (get-position cell)
    (define row (- n (quotient (sub1 cell) n)))
    (define col (if (even? (quotient (sub1 cell) n))
                    (remainder (sub1 cell) n)
                    (- n 1 (remainder (sub1 cell) n))))
    (cons row col))

  (define (get-value cell)
    (define pos (get-position cell))
    (list-ref (list-ref board (car pos)) (cdr pos)))

  (define (bfs)
    (define queue (queue 1))
    (hash-set! visited 1 #t)
    (define steps 0)
    (let loop ()
      (when (not (queue-empty? queue))
        (define size (queue-length queue))
        (for ([i (in-range size)])
          (define cell (queue-dequeue! queue))
          (when (= cell (* n n))
            (set! steps (sub1 steps))
            (break))
          (for ([i (in-range 1 7)])
            (define next-cell (+ cell i))
            (when (<= next-cell (* n n))
              (define value (get-value next-cell))
              (when (not (hash-has-key? visited next-cell))
                (hash-set! visited next-cell #t)
                (queue-enqueue! queue next-cell)
                (when (= value (* n n))
                  (set! steps (add1 steps))
                  (break)))))
        (set! steps (add1 steps))
        (loop)))
    steps)

  (bfs))