(define (min-add-to-make-valid s)
  (define (helper left right)
    (if (null? s)
        (abs (- left right))
        (let ((c (car s)))
          (if (char=? c #\()
              (helper (+ left 1) right)
              (if (> right 0)
                  (helper left (- right 1))
                  (helper (+ left 1) right))))))
  (helper 0 0))