#lang racket

(define (knight-dialer n)
  (define dp
    (make-vector 10 1))
  (define next-dp
    (make-vector 10 0))
  (for ([i (in-range 1 n)])
    (vector-set! next-dp 0 0)
    (vector-set! next-dp 1 0)
    (vector-set! next-dp 2 0)
    (vector-set! next-dp 3 0)
    (vector-set! next-dp 4 0)
    (vector-set! next-dp 5 0)
    (vector-set! next-dp 6 0)
    (vector-set! next-dp 7 0)
    (vector-set! next-dp 8 0)
    (vector-set! next-dp 9 0)
    (vector-set! next-dp 0 (+ (vector-ref dp 4) (vector-ref dp 6)))
    (vector-set! next-dp 1 (+ (vector-ref dp 6) (vector-ref dp 8)))
    (vector-set! next-dp 2 (+ (vector-ref dp 7) (vector-ref dp 9)))
    (vector-set! next-dp 3 (+ (vector-ref dp 4) (vector-ref dp 8)))
    (vector-set! next-dp 4 (+ (vector-ref dp 0) (vector-ref dp 3) (vector-ref dp 9)))
    (vector-set! next-dp 5 0)
    (vector-set! next-dp 6 (+ (vector-ref dp 0) (vector-ref dp 1) (vector-ref dp 7)))
    (vector-set! next-dp 7 (+ (vector-ref dp 2) (vector-ref dp 6)))
    (vector-set! next-dp 8 (+ (vector-ref dp 1) (vector-ref dp 3)))
    (vector-set! next-dp 9 (+ (vector-ref dp 2) (vector-ref dp 4)))
    (set! dp next-dp)
    (set! next-dp (make-vector 10 0)))
  (apply + (vector->list dp)))