(define (distinct-subsequences s)
  (define mod 1000000007)
  (define dp (make-hash))
  (hash-set! dp "" 1)
  (for ([c (in-string s)])
    (define temp (make-hash))
    (for ([k (in-hash-keys dp)])
      (define new-k (string-append k (string c)))
      (hash-set! temp new-k (modulo (+ (hash-ref temp new-k 0) (hash-ref dp k)) mod)))
    (for ([k (in-hash-keys dp)])
      (hash-set! temp k (modulo (+ (hash-ref temp k 0) (hash-ref dp k)) mod)))
    (set! dp temp))
  (hash-ref dp "" 0))