(define (powerful-integers x y bound)
  (define result '())
  (define (helper a b)
    (when (<= (+ (expt x a) (expt y b)) bound)
      (set! result (cons (+ (expt x a) (expt y b)) result))))
  (let loop-a ((a 0))
    (when (<= (expt x a) bound)
      (let loop-b ((b 0))
        (when (<= (expt y b) (- bound (expt x a)))
          (helper a b)
          (loop-b (+ b 1))))
      (loop-a (+ a 1))))
  (remove-duplicates result))