(define (interval-list-intersections A B)
  (define (intersect a b)
    (let ((start (max (car a) (car b)))
          (end (min (cadr a) (cadr b))))
      (if (<= start end)
          (list (list start end))
          '())))
  (define (helper A B result)
    (cond ((or (null? A) (null? B)) result)
          (else
           (let ((a (car A))
                 (b (car B)))
             (if (<= (cadr a) (car b))
                 (helper (cdr A) B (append result (intersect a b)))
                 (helper A (cdr B) (append result (intersect a b))))))))
  (helper A B '()))