(define (equations-possible equations)
  (define parent (make-hash))
  (define (find x)
    (if (not (hash-has-key? parent x))
        x
        (let ((p (hash-ref parent x)))
          (if (= p x)
              x
              (let ((root (find p)))
                (hash-set! parent x root)
                root)))))
  (define (union x y)
    (let ((x-root (find x))
          (y-root (find y)))
      (when (not (= x-root y-root))
        (hash-set! parent y-root x-root))))
  (for-each (lambda (eq)
              (let ((a (string-ref eq 0))
                    (b (string-ref eq 3))
                    (op (string-ref eq 1)))
                (when (char=? op #\=)
                  (union a b))))
            equations)
  (for/and ((eq equations))
    (let ((a (string-ref eq 0))
          (b (string-ref eq 3))
          (op (string-ref eq 1)))
      (if (char=? op #\=)
          (= (find a) (find b))
          (not (= (find a) (find b))))))