(define (subarrays-with-k-different-integers nums k)
  (define (at-most k)
    (let ((count (make-hash))
          (left 0)
          (result 0))
      (for ([right (in-range (length nums))])
        (hash-set! count (list-ref nums right) (+ (hash-ref count (list-ref nums right) 0) 1))
        (while (and (<= left right) (> (hash-count count) k))
          (hash-set! count (list-ref nums left) (- (hash-ref count (list-ref nums left)) 1))
          (when (= (hash-ref count (list-ref nums left) 0) 0)
            (hash-remove! count (list-ref nums left)))
          (set! left (+ left 1)))
        (set! result (+ result (- right left 1))))
      result))
  (- (at-most k) (at-most (- k 1))))