(define (oranges-rotting grid)
  (define rows (length grid))
  (define cols (if (> rows 0) (length (car grid)) 0))
  (define rotting (make-hash))
  (define fresh 0)
  (for ([i (in-range rows)])
    (for ([j (in-range cols)])
      (cond [(= (list-ref (list-ref grid i) j) 2)
             (hash-set! rotting (cons i j) #t)]
            [(= (list-ref (list-ref grid i) j) 1)
             (set! fresh (+ fresh 1))])))
  (define directions '((0 1) (1 0) (-1 0) (0 -1)))
  (define time 0)
  (define queue (queue))
  (for ([i (in-range rows)])
    (for ([j (in-range cols)])
      (when (= (list-ref (list-ref grid i) j) 2)
        (enqueue! queue (cons i j)))))
  (let loop ()
    (when (not (queue-empty? queue))
      (define size (queue-length queue))
      (for ([_ (in-range size)])
        (define pos (dequeue! queue))
        (define i (car pos))
        (define j (cdr pos))
        (for ([d directions])
          (define ni (+ i (car d)))
          (define nj (+ j (cdr d)))
          (when (and (<= 0 ni (- rows 1)) (<= 0 nj (- cols 1)) (= (list-ref (list-ref grid ni) nj) 1))
            (set! fresh (- fresh 1))
            (list-set! (list-ref grid ni) nj 2)
            (enqueue! queue (cons ni nj)))))
      (set! time (+ time 1))
      (loop)))
  (if (= fresh 0) (- time 1) -1))