(define (min-area-rectangle points)
  (define (key x y) (+ (* x 1000000) y))
  (define point-set (make-hash))
  (for-each (lambda (p)
              (hash-set! point-set (key (car p) (cadr p)) #t))
            points)
  (define min-area (expt 2 30))
  (for-each (lambda (p1)
              (for-each (lambda (p2)
                          (when (and (not (= p1 p2))
                                     (hash-has-key? point-set (key (car p1) (cadr p2)))
                                     (hash-has-key? point-set (key (car p2) (cadr p1))))
                            (let ((x1 (car p1)) (y1 (cadr p1))
                                  (x2 (car p2)) (y2 (cadr p2)))
                              (when (and (not (= x1 x2)) (not (= y1 y2)))
                                (let ((area (abs (* (- x1 x2) (- y1 y2)))))
                                  (when (< area min-area)
                                    (set! min-area area)))))))
                        points))
            points)
  min-area)