#lang racket

(define (solve)
  (define input (current-input-port))
  (define n (read input))
  (define m (read input))
  (define grid (for/vector #:length n (λ () (for/vector #:length m (λ () (read input))))))
  (define visited (make-vector n #f))
  (define (bfs i j)
    (when (and (< i n) (>= i 0) (< j m) (>= j 0) (not (vector-ref visited i)) (= (vector-ref (vector-ref grid i) j) 1))
      (vector-set! visited i #t)
      (bfs (+ i 1) j)
      (bfs (- i 1) j)
      (bfs i (+ j 1))
      (bfs i (- j 1))))
  (for ([i (in-range n)])
    (when (and (= (vector-ref (vector-ref grid i) 0) 1) (not (vector-ref visited i)))
      (bfs i 0))
    (when (and (= (vector-ref (vector-ref grid i) (- m 1)) 1) (not (vector-ref visited i)))
      (bfs i (- m 1))))
  (for ([j (in-range m)])
    (when (and (= (vector-ref (vector-ref grid 0) j) 1) (not (vector-ref visited 0)))
      (bfs 0 j))
    (when (and (= (vector-ref (vector-ref grid (- n 1)) j) 1) (not (vector-ref visited (- n 1))))
      (bfs (- n 1) j)))
  (for/sum ([i (in-range n)] [v (in-vector visited)]) (if v 0 1)))

(solve)