#lang racket

(define (robotSim commands)
  (define directions '((0 1) (1 0) (0 -1) (-1 0)))
  (define (move x y dir obstacles)
    (let loop ((x x) (y y) (dir dir))
      (if (or (not (directions dir)) (not (directions (car directions))) (not (directions (cadr directions))) (not (directions (caddr directions))) (not (directions (cadddr directions))))
          (values x y dir)
          (let* ((dx (caar directions))
                 (dy (cdar directions))
                 (nx (+ x dx))
                 (ny (+ y dy)))
            (if (set-member? obstacles (cons nx ny))
                (values x y dir)
                (loop nx ny dir))))))
  (define obstacles (set))
  (for-each (lambda (cmd) (set! obstacles (set-add obstacles cmd))) commands)
  (define (simulate x y dir)
    (cond ((null? commands) (values x y))
          ((equal? (car commands) 'G)
           (let-values (((nx ny) (move x y dir obstacles)))
             (simulate nx ny dir)))
          ((equal? (car commands) 'L)
           (simulate x y (modulo (- dir 1) 4)))
          ((equal? (car commands) 'R)
           (simulate x y (modulo (+ dir 1) 4)))))
  (define-values (x y) (simulate 0 0 0))
  (sqrt (+ (* x x) (* y y))))