(define (num-matching-subseq s words)
  (define (count word)
    (let loop ((i 0) (j 0))
      (cond ((= j (string-length word)) #t)
            ((= i (string-length s)) #f)
            ((char=? (string-ref s i) (string-ref word j))
             (loop (+ i 1) (+ j 1)))
            (else (loop (+ i 1) j)))))
  (for/sum ((word words)) (if (count word) 1 0)))