(define (find-kth-largest nums k)
  (define (quick-select l r k)
    (let ((pivot (list-ref nums (random-integer (- r l 1))))
          (i l))
      (when (> l r) (error "invalid"))
      (let loop ()
        (when (<= i r)
          (when (>= (list-ref nums i) pivot)
            (let ((temp (list-ref nums i)))
              (set! nums (append (take nums i) (list pivot) (drop nums (+ i 1))))
              (set! i (+ i 1))))
          (set! i (+ i 1))
          (loop)))
      (let ((pos (- i 1)))
        (if (= pos (- k 1)) (list-ref nums pos)
            (if (< pos (- k 1)) (quick-select (+ pos 1) r (- k pos 1))
                (quick-select l (- pos 1) k))))))
  (quick-select 0 (- (length nums) 1) k))