(define (level-order root)
  (if (not root)
      '()
      (let loop ((queue (list root)) (result '()))
        (if (null? queue)
            (reverse result)
            (let* ((size (length queue))
                   (current-level '())
                   (next-queue '()))
              (let inner-loop ((i 0) (q queue))
                (if (>= i size)
                    (loop next-queue (cons (reverse current-level) result))
                    (let ((node (car q)))
                      (set! current-level (cons (node-val node) current-level))
                      (when (node-left node)
                        (set! next-queue (append next-queue (list (node-left node)))))
                      (when (node-right node)
                        (set! next-queue (append next-queue (list (node-right node)))))
                      (inner-loop (+ i 1) (cdr q))))))))))