#lang racket

(define (update-matrix matrix)
  (define rows (length matrix))
  (define cols (if (> rows 0) (length (car matrix)) 0))
  (define INF 1000000)
  (define dist (make-vector rows (make-vector cols INF)))
  (define q (queue))
  (for ([i (in-range rows)])
    (for ([j (in-range cols)])
      (when (= (vector-ref (vector-ref matrix i) j) 0)
        (vector-set! (vector-ref dist i) j 0)
        (enqueue! q (cons i j)))))
  (define directions (list (cons 1 0) (cons -1 0) (cons 0 1) (cons 0 -1)))
  (let loop ()
    (when (not (queue-empty? q))
      (define p (dequeue! q))
      (define i (car p))
      (define j (cdr p))
      (for ([d (in-list directions)])
        (define ni (+ i (car d)))
        (define nj (+ j (cdr d)))
        (when (and (<= 0 ni (- rows 1)) (<= 0 nj (- cols 1)))
          (when (> (vector-ref (vector-ref dist ni) nj) (+ (vector-ref (vector-ref dist i) j) 1))
            (vector-set! (vector-ref dist ni) nj (+ (vector-ref (vector-ref dist i) j) 1))
            (enqueue! q (cons ni nj)))))
      (loop)))
  (vector->list dist))