(define (all-paths-source-target grid)
  (define n (length grid))
  (define (dfs node path result)
    (if (= node (- n 1))
        (set! result (append result (list (reverse path))))
        (for-each (lambda (neighbor)
                    (dfs neighbor (cons neighbor path) result))
                  (filter (lambda (x) (not (equal? x node)))
                          (map (lambda (i) (if (equal? (list-ref (list-ref grid node) i) 1) i #f))
                               (range n)))))
  (let ([result '()])
    (dfs 0 (list 0) result)
    result))