(define (spiral-order matrix)
  (if (null? matrix)
      '()
      (let loop ((matrix matrix) (result '()))
        (if (null? matrix)
            (reverse result)
            (let* ((top (car matrix))
                   (bottom (last matrix))
                   (left (car (map car matrix)))
                   (right (last (map car matrix)))
                   (new-matrix (map (lambda (row) (cdr (reverse (cdr (reverse row))))) (cdr (reverse (cdr matrix))))))
              (loop new-matrix (append result top (cdr (reverse bottom)) (map last (cdr matrix)) (reverse (cdr left))))))))