(define (add-strings num1 num2)
  (define (char->digit c)
    (- (char->integer c) (char->integer #\0)))
  (define (digit->char d)
    (integer->char (+ d (char->integer #\0))))
  (define (add-helper i j carry)
    (if (and (= i -1) (= j -1) (= carry 0))
        '()
        (let* ((digit1 (if (> i -1) (char->digit (string-ref num1 i)) 0))
               (digit2 (if (> j -1) (char->digit (string-ref num2 j)) 0))
               (sum (+ digit1 digit2 carry))
               (new-carry (quotient sum 10))
               (current-digit (modulo sum 10)))
          (cons (digit->char current-digit)
                (add-helper (- i 1) (- j 1) new-carry)))))
  (list->string (reverse (add-helper (- (string-length num1) 1) (- (string-length num2) 1) 0))))