(define (min-cost-to-merge-stones stones k)
  (define n (length stones))
  (if (= 1 n)
      0
      (if (not (zero? (modulo (- n 1) (- k 1))))
          -1
          (let ((dp (make-vector (+ n 1) (make-vector (+ n 1) (make-vector (+ n 1) 0)))))
            (define prefix-sum (make-vector (+ n 1) 0))
            (for ((i (in-range 1 (+ n 1))))
                 (vector-set! prefix-sum i (+ (vector-ref prefix-sum (- i 1)) (list-ref stones (- i 1)))))
            (define (sum i j)
              (- (vector-ref prefix-sum j) (vector-ref prefix-sum i)))
            (for ((len (in-range (+ k 1) (+ n 1))))
              (for ((i (in-range 1 (- (+ n 1) len -1))))
                (let ((j (+ i len -1)))
                  (vector-set! (vector-ref dp i j) 1000000000)
                  (for ((m (in-range i j k)))
                    (vector-set! (vector-ref dp i j) (min (vector-ref (vector-ref dp i j) 0) (+ (vector-ref (vector-ref dp i m) 0) (vector-ref (vector-ref dp (+ m 1) j) 0)))))
                  (if (zero? (modulo (- len 1) (- k 1)))
                      (vector-set! (vector-ref dp i j) (+ (vector-ref (vector-ref dp i j) 0) (sum (- i 1) j)))))))
            (vector-ref (vector-ref dp 1 n) 0)))))