(define (distant-barcodes barcodes)
  (let* ((counts (make-hash))
         (n (length barcodes)))
    (for-each (lambda (barcode)
                (hash-update! counts barcode add1 0))
              barcodes)
    (let* ((heap (make-heap (lambda (a b) (> (hash-ref counts a) (hash-ref counts b)))))
           (heap-add (heap-add! heap))
           (heap-remove (heap-remove! heap))
           (result (make-vector n)))
      (for-each (lambda (barcode) (heap-add barcode)) (hash-keys counts))
      (let loop ((idx 0))
        (if (= idx n)
            (vector->list result)
            (let* ((barcode1 (heap-remove))
                   (count1 (hash-ref counts barcode1))
                   (barcode2 (if (empty? heap) #f (heap-remove)))
                   (count2 (if barcode2 (hash-ref counts barcode2) 0)))
              (vector-set! result idx barcode1)
              (hash-update! counts barcode1 sub1)
              (when (> (hash-ref counts barcode1) 0)
                (heap-add barcode1))
              (when barcode2
                (hash-update! counts barcode2 sub1)
                (when (> (hash-ref counts barcode2) 0)
                  (heap-add barcode2)))
              (loop (+ idx 1))))))))