(define (num-submatrix-sum-target matrix target)
  (define (prefix-sum m n)
    (define sums (make-matrix (+ m 1) (+ n 1) 0))
    (for ([i (in-range 1 (+ m 1))])
      (for ([j (in-range 1 (+ n 1))])
        (matrix-set! sums i j (+ (matrix-ref matrix (- i 1) (- j 1))
                                 (matrix-ref sums (- i 1) j)
                                 (matrix-ref sums i (- j 1))
                                 (- (matrix-ref sums (- i 1) (- j 1))))))
    sums)

  (define (count-submatrices-with-target sums row1 row2)
    (define counts (make-hash))
    (hash-set! counts 0 1)
    (define count 0)
    (for ([j (in-range 1 (+ (matrix-ncols matrix) 1))])
      (define current-sum (- (matrix-ref sums row2 j) (matrix-ref sums row1 j)))
      (define needed-sum (- current-sum target))
      (when (hash-has-key? counts needed-sum)
        (set! count (+ count (hash-ref counts needed-sum))))
      (define current-sum-count (hash-ref counts current-sum 0))
      (hash-set! counts current-sum (+ current-sum-count 1)))
    count)

  (define sums (prefix-sum (matrix-nrows matrix) (matrix-ncols matrix)))
  (define total-count 0)
  (for ([row1 (in-range 0 (matrix-nrows matrix))])
    (for ([row2 (in-range (+ row1 1) (+ (matrix-nrows matrix) 1))])
      (set! total-count (+ total-count (count-submatrices-with-target sums row1 row2)))))
  total-count)