(define (num-tile-possibilities tiles)
  (letrec ((count-unique-permutations
            (lambda (remaining used)
              (if (empty? remaining)
                  (set-count! used)
                  (let ((seen #f))
                    (foldl (lambda (tile acc)
                             (if (not seen)
                                 (let ((new-remaining (remove tile remaining #:count 1)))
                                   (set! seen #t)
                                   (count-unique-permutations new-remaining (set-add used (string tile))))
                                 acc))
                           '()
                           (remove-duplicates remaining #:same? string=?))))))
         (used (set))
         (set-count! (lambda (s) (set-count s))))
    (count-unique-permutations (string->list tiles) used)
    (- (set-count used) 1)))