(define (sorted-array-to-bst nums)
  (define (helper left right)
    (if (> left right)
        '()
        (let ((mid (quotient (+ left right) 2)))
          (list (list-ref nums mid)
                (helper left (- mid 1))
                (helper (+ mid 1) right)))))
  (helper 0 (- (length nums) 1)))