(define (largest-values-from-labels values labels num-wanted use-limit)
  (let* ((n (length values))
         (valid-indices (filter (lambda (i) (< i n)) (range n)))
         (pairs (map (lambda (i) (cons (list-ref values i) (list-ref labels i))) valid-indices))
         (sorted-pairs (sort pairs > #:key car)))
    (let loop ((remaining-pairs sorted-pairs)
               (used-labels (hash))
               (count 0)
               (sum 0))
      (cond
        ((or (null? remaining-pairs) (= count num-wanted)) sum)
        (else
         (let* ((current-pair (car remaining-pairs))
                (value (car current-pair))
                (label (cdr current-pair)))
           (if (and (hash-has-key? used-labels label)
                    (>= (hash-ref used-labels label) use-limit))
               (loop (cdr remaining-pairs) used-labels count sum)
               (let* ((new-used-labels (hash-update used-labels label (lambda (v) (+ v 1)) 1)))
                 (loop (cdr remaining-pairs) new-used-labels (+ count 1) (+ sum value))))))))))