(define (car-pooling trips capacity)
  (let* ((max-location (apply max (map (lambda (trip) (caddr trip)) trips)))
         (passengers (make-vector (add1 max-location) 0)))
    (for-each (lambda (trip)
                (let ((num-passengers (car trip))
                      (start-location (cadr trip))
                      (end-location (caddr trip)))
                  (for ((i (in-range start-location end-location)))
                    (vector-set! passengers i (+ (vector-ref passengers i) num-passengers)))))
              trips)
    (not (ormap (lambda (p) (> p capacity)) (vector->list passengers)))))