(define (foo-bar n)
  (let ([foo-lock (make-semaphore 1)]
        [bar-lock (make-semaphore 0)])
    (define (foo)
      (for ([i (in-range n)])
        (semaphore-wait foo-lock)
        (printf "foo")
        (semaphore-post bar-lock)))
    (define (bar)
      (for ([i (in-range n)])
        (semaphore-wait bar-lock)
        (printf "bar")
        (semaphore-post foo-lock)))
    (thread foo)
    (thread bar)))