(define (relative-sort-array arr1 arr2)
  (let* ([counts (make-hash)]
         [result '()])
    (for ([x arr1])
      (hash-update! counts x (lambda (v) (+ v 1)) 1))
    (for ([x arr2])
      (for ([i (range (hash-ref counts x))])
        (set! result (append result (list x)))
        )
      (hash-remove! counts x))
    (let* ([remaining (sort (hash-keys counts) <)])
      (for ([x remaining])
        (for ([i (range (hash-ref counts x))])
          (set! result (append result (list x))))))
    result))