(define (max-absolute-value-expression arr1 arr2)
  (define n (vector-length arr1))
  (define max1 (for/fold (number? #f) ([i (in-range n)])
                 (if (or (not max1) (> (+ (vector-ref arr1 i) (vector-ref arr2 i) i) max1))
                     (+ (vector-ref arr1 i) (vector-ref arr2 i) i)
                     max1)))
  (define min1 (for/fold (number? #f) ([i (in-range n)])
                 (if (or (not min1) (< (+ (vector-ref arr1 i) (vector-ref arr2 i) i) min1))
                     (+ (vector-ref arr1 i) (vector-ref arr2 i) i)
                     min1)))
  (define max2 (for/fold (number? #f) ([i (in-range n)])
                 (if (or (not max2) (> (+ (vector-ref arr1 i) (- (vector-ref arr2 i)) i) max2))
                     (+ (vector-ref arr1 i) (- (vector-ref arr2 i)) i)
                     max2)))
  (define min2 (for/fold (number? #f) ([i (in-range n)])
                 (if (or (not min2) (< (+ (vector-ref arr1 i) (- (vector-ref arr2 i)) i) min2))
                     (+ (vector-ref arr1 i) (- (vector-ref arr2 i)) i)
                     min2)))
  (define max3 (for/fold (number? #f) ([i (in-range n)])
                 (if (or (not max3) (> (- (vector-ref arr1 i)) (+ (vector-ref arr2 i)) i) max3))
                     (- (vector-ref arr1 i)) (+ (vector-ref arr2 i)) i
                     max3)))
  (define min3 (for/fold (number? #f) ([i (in-range n)])
                 (if (or (not min3) (< (- (vector-ref arr1 i)) (+ (vector-ref arr2 i)) i) min3))
                     (- (vector-ref arr1 i)) (+ (vector-ref arr2 i)) i
                     min3)))
  (define max4 (for/fold (number? #f) ([i (in-range n)])
                 (if (or (not max4) (> (- (vector-ref arr1 i)) (- (vector-ref arr2 i)) i) max4))
                     (- (vector-ref arr1 i)) (- (vector-ref arr2 i)) i
                     max4)))
  (define min4 (for/fold (number? #f) ([i (in-range n)])
                 (if (or (not min4) (< (- (vector-ref arr1 i)) (- (vector-ref arr2 i)) i) min4))
                     (- (vector-ref arr1 i)) (- (vector-ref arr2 i)) i
                     min4)))

  (max (- max1 min1) (- max2 min2) (- max3 min3) (- max4 min4)))