(define online-majority-element
  (lambda (arr)
    (let* ((n (length arr))
           (count-map (make-hash))
           (threshold (ceiling (/ n 2))))
      (define (update-count! x)
        (hash-update! count-map x (lambda (v) (+ v 1)) 1))
      (define (query left right threshold)
        (let* ((sub-array (list->vector (take (drop arr left) (- right left))))
               (sub-n (vector-length sub-array))
               (sub-threshold (ceiling (/ sub-n 2)))
               (candidates (remove-duplicates (vector->list sub-array))))
          (for/first ([candidate (in-list candidates)] #:when (> (count (lambda (x) (equal? x candidate)) (vector->list sub-array)) sub-threshold))
            candidate)
          -1))
      (define (most-frequent left right threshold)
        (query left right threshold))
      (struct online-majority-element-ds (arr update-count! most-frequent) #:transparent)
      (let ((ds (online-majority-element-ds arr update-count! most-frequent)))
        ds))))

(define (OnlineMajorityElement obj arr)
  (let ((ds (online-majority-element arr)))
    (struct online-majority-element-api (query) #:transparent)
    (let ((api (online-majority-element-api (lambda (left right threshold) ((online-majority-element-ds-most-frequent ds) left right threshold)))))
      api)))

(define (OnlineMajorityElement.query obj left right threshold)
  ((online-majority-element-api-query obj) left right threshold))