(define (max-number-of-balloons text)
  (define counts (make-hash))
  (for ([c (in-string text)])
    (hash-update! counts c (λ (v) (+ v 1)) 0))
  (define b (hash-ref counts #\b 0))
  (define a (hash-ref counts #\a 0))
  (define l (hash-ref counts #\l 0))
  (define o (hash-ref counts #\o 0))
  (define n (hash-ref counts #\n 0))
  (min b a (floor (/ l 2)) (floor (/ o 2)) n))