(define (get-maximum-gold grid)
  (define rows (length grid))
  (define cols (length (first grid)))
  (define (valid? r c)
    (and (>= r 0) (< r rows) (>= c 0) (< c cols)))
  (define (dfs r c visited)
    (if (or (not (valid? r c)) (hash-has-key? visited (cons r c)) (= (list-ref (list-ref grid r) c) 0))
        0
        (let* ((gold (list-ref (list-ref grid r) c))
               (new-visited (hash-copy visited))
               (_ (hash-set! new-visited (cons r c) #t))
               (up (dfs (- r 1) c new-visited))
               (down (dfs (+ r 1) c new-visited))
               (left (dfs r (- c 1) new-visited))
               (right (dfs r (+ c 1) new-visited)))
          (+ gold (apply max (list up down left right))))))
  (let loop ((r 0) (c 0) (max-gold 0))
    (cond
      ((= r rows) max-gold)
      ((= c cols) (loop (+ r 1) 0 max-gold))
      (else (let ((gold (dfs r c (make-hash))))
              (loop r (+ c 1) (max max-gold gold)))))))