(define (numWays steps arrLen)
  (let ((mod 1000000007))
    (let ((max-pos (min steps arrLen)))
      (let ((dp (make-vector (+ max-pos 1) (make-vector (+ steps 1) 0))))
        (vector-set! (vector-ref dp 0) 0 1)
        (for ((i (in-range 1 (+ steps 1))))
          (for ((j (in-range 0 (+ max-pos 1))))
            (let ((stay (vector-ref (vector-ref dp j) (- i 1)))
                  (left (if (= j 0) 0 (vector-ref (vector-ref dp (- j 1)) (- i 1))))
                  (right (if (= j max-pos) 0 (vector-ref (vector-ref dp (+ j 1)) (- i 1)))))
              (vector-set! (vector-ref dp j) i (modulo (+ stay left right) mod)))))
        (vector-ref (vector-ref dp 0) steps)))))