(define (make-connected n connections)
  (let ((num-edges (length connections)))
    (if (< num-edges (- n 1))
        -1
        (let ((parent (make-vector n #f)))
          (for ((i (in-range n)))
            (vector-set! parent i i))
          (define (find x)
            (if (equal? (vector-ref parent x) x)
                x
                (let ((root (find (vector-ref parent x))))
                  (vector-set! parent x root)
                  root)))
          (define (union x y)
            (let ((root-x (find x))
                  (root-y (find y)))
              (if (not (equal? root-x root-y))
                  (vector-set! parent root-x root-y)
                  #f)))
          (for ((edge (in-list connections)))
            (union (car edge) (cadr edge)))
          (let ((components (set)))
            (for ((i (in-range n)))
              (set-add! components (find i)))
            (- (set-count components) 1)))))))