(define (min-steps s t)
  (let* ((s-freq (make-vector 26 0))
         (t-freq (make-vector 26 0))
         (s-len (string-length s))
         (t-len (string-length t)))
    (for ([i s-len])
      (vector-set! s-freq (- (char->integer (string-ref s i)) (char->integer #\a)) (+ (vector-ref s-freq (- (char->integer (string-ref s i)) (char->integer #\a))) 1)))
    (for ([i t-len])
      (vector-set! t-freq (- (char->integer (string-ref t i)) (char->integer #\a)) (+ (vector-ref t-freq (- (char->integer (string-ref t i)) (char->integer #\a))) 1)))
    (let loop ([i 0] [steps 0])
      (if (= i 26)
          steps
          (let* ((s-count (vector-ref s-freq i))
                 (t-count (vector-ref t-freq i)))
            (loop (+ i 1) (+ steps (max 0 (- s-count t-count)))))))))