(define (make-underground-system)
  (let ((check-in-data (make-hash))
        (travel-times (make-hash)))
    (define (check-in id stationName t)
      (hash-set! check-in-data id (cons stationName t)))
    (define (check-out id stationName t)
      (let* ((check-in-info (hash-ref check-in-data id))
             (start-station (car check-in-info))
             (start-time (cdr check-in-info))
             (route (cons start-station stationName))
             (travel-time (- t start-time)))
        (hash-remove! check-in-data id)
        (if (hash-has-key? travel-times route)
            (let ((existing-data (hash-ref travel-times route)))
              (hash-set! travel-times route (cons (+ (car existing-data) travel-time) (+ (cdr existing-data) 1))))
            (hash-set! travel-times route (cons travel-time 1)))))
    (define (get-average-time startStation endStation)
      (let* ((route (cons startStation endStation))
             (travel-data (hash-ref travel-times route)))
        (/ (car travel-data) (cdr travel-data))))
    (define (dispatch method . args)
      (case (string->symbol method)
        [(checkIn) (apply check-in args)]
        [(checkOut) (apply check-out args)]
        [(getAverageTime) (apply get-average-time args)]
        [else (error "Unknown method: " method)]))
    dispatch))