(define (find-diagonal-order nums)
  (let* ((rows (length nums))
         (diagonals (make-hash))
         (max-diagonal 0))
    (for/list ((i (in-range rows)))
      (for/list ((j (in-range (length (list-ref nums i)))))
        (let ((diagonal (+ i j)))
          (hash-update! diagonals diagonal (λ (v) (cons (list-ref (list-ref nums i) j) v)) '())
          (set! max-diagonal (max max-diagonal diagonal)))))
    (let loop ((diagonal 0) (result '()))
      (if (> diagonal max-diagonal)
          (reverse result)
          (loop (+ diagonal 1) (append result (reverse (hash-ref diagonals diagonal '()))))))))