(define (reorder-list head)
  (if (or (null? head) (null? (cdr head)))
      head
      (let* ((slow head)
             (fast head)
             (queue (make-queue)))
        (while (and fast (cdr fast))
          (set! slow (cdr slow))
          (set! fast (cddr fast)))
        (let loop ((node slow))
          (if (not (null? node))
              (begin
                (enqueue! queue node)
                (loop (cdr node)))))
        (set-cdr! slow null)
        (let reorder-loop ((current head))
          (if (not (queue-empty? queue))
              (let ((next-node (dequeue! queue))
                    (temp (cdr current)))
                (set-cdr! current next-node)
                (set-cdr! next-node temp)
                (reorder-loop temp))
              (void))))
      head))