(define (lru-cache capacity)
  (let* ((cache (make-hash))
         (heap (make-heap #:<=? <))
         (time 0)
         (cap capacity))
    (define (get key)
      (cond
        [(hash-has-key? cache key)
         (let ((node (hash-ref cache key)))
           (heap-remove! heap node)
           (set! time (+ time 1))
           (let ((new-node (list time key (caddr node))))
             (hash-set! cache key new-node)
             (heap-add! heap new-node)
             (caddr new-node)))]
        [else -1]))
    (define (put key value)
      (cond
        [(hash-has-key? cache key)
         (let ((node (hash-ref cache key)))
           (heap-remove! heap node)
           (set! time (+ time 1))
           (let ((new-node (list time key value)))
             (hash-set! cache key new-node)
             (heap-add! heap new-node)))]
        [else
         (when (= (hash-count cache) cap)
           (let* ((lru-node (heap-remove-min! heap)))
             (hash-remove! cache (cadr lru-node))))
         (set! time (+ time 1))
         (let ((new-node (list time key value)))
           (hash-set! cache key new-node)
           (heap-add! heap new-node))]))
    (hash 'get get 'put put)))