(define (min-reorder n connections)
  (define adj (make-vector n '()))
  (define edges (make-hash))
  (for-each (lambda (c)
              (let ((u (car c)) (v (cadr c)))
                (vector-set! adj u (cons v (vector-ref adj u)))
                (vector-set! adj v (cons u (vector-ref adj v)))
                (hash-set! edges (list u v) #t)))
            connections)
  (define visited (make-vector n #f))
  (define q (make-queue))
  (enqueue! q 0)
  (vector-set! visited 0 #t)
  (define count 0)
  (while (not (queue-empty? q))
    (let ((u (dequeue! q)))
      (for-each (lambda (v)
                  (if (not (vector-ref visited v))
                      (begin
                        (if (hash-ref edges (list v u) #f)
                            (void)
                            (set! count (+ count 1)))
                        (vector-set! visited v #t)
                        (enqueue! q v))))
                (vector-ref adj u))))
  count)