(define (make-subrectangle-queries rectangle)
  (define rect rectangle)
  (define (update-subrectangle row1 col1 row2 col2 newValue)
    (for* ((i (in-range row1 (+ row2 1)))
           (j (in-range col1 (+ col2 1))))
      (set! (list-ref (list-ref rect i) j) newValue)))
  (define (get-value row col)
    (list-ref (list-ref rect row) col))
  (struct subrectangle-queries (update-subrectangle get-value))
  (subrectangle-queries update-subrectangle get-value))