(define min-stack%
  (class object%
    (init-field stack '())
    (init-field min-stack '())
    (define/public (push val)
      (set! stack (cons val stack))
      (if (or (empty? min-stack) (<= val (car min-stack)))
          (set! min-stack (cons val min-stack))
          (void)))
    (define/public (pop)
      (if (empty? stack)
          (void)
          (let ((popped (car stack)))
            (set! stack (cdr stack))
            (if (= popped (car min-stack))
                (set! min-stack (cdr min-stack))
                (void)))))
    (define/public (top)
      (if (empty? stack)
          (void)
          (car stack)))
    (define/public (get-min)
      (if (empty? min-stack)
          (void)
          (car min-stack)))))

(provide min-stack%)