(define (frequency-sort nums)
  (let* ((counts (make-hash))
         (n (length nums)))
    (for-each (lambda (num)
                (hash-update! counts num (lambda (k v) (+ v 1)) 1))
              nums)
    (sort nums (lambda (a b)
                  (let ((count-a (hash-ref counts a 0))
                        (count-b (hash-ref counts b 0)))
                    (if (= count-a count-b)
                        (> a b)
                        (< count-a count-b)))))))