(define (most-competitive nums k)
  (define n (length nums))
  (define stack (make-vector k))
  (define top -1)
  (for ([i (in-range n)])
    (while (and (> top -1)
                (> (vector-ref stack top) (list-ref nums i))
                (< (+ top 1) (- n k (+ i 1)))))
      (set! top (- top 1)))
    (if (< (+ top 1) k)
        (begin
          (set! top (+ top 1))
          (vector-set! stack top (list-ref nums i)))))
  (vector->list stack))