(define (tuple-same-product nums)
  (let ((count 0)
        (n (length nums)))
    (for* ((i (range n))
           (j (range (+ i 1) n)))
      (let ((product (* (list-ref nums i) (list-ref nums j))))
        (for* ((k (range (+ j 1) n))
               (l (range (+ k 1) n)))
          (when (= product (* (list-ref nums k) (list-ref nums l)))
            (set! count (+ count 8))))))
    count))