(define (largest-submatrix-with-rearrangements matrix)
  (let* ((rows (length matrix))
         (cols (length (car matrix)))
         (heights (make-vector cols 0))
         (max-area 0))
    (for ((i (in-range rows)))
      (for ((j (in-range cols)))
        (if (= (list-ref (list-ref matrix i) j) 0)
            (vector-set! heights j 0)
            (vector-set! heights j (+ (vector-ref heights j) 1))))
      (let ((sorted-heights (sort (vector->list heights) >)))
        (for ((k (in-range cols)))
          (set! max-area (max max-area (* (list-ref sorted-heights k) (+ k 1)))))))
    max-area))