(define (beauty-sum s)
  (let* ((n (string-length s))
         (total-beauty (for/sum ((i (in-range n)))
                          (for/sum ((j (in-range i n)))
                            (let* ((sub (substring s i (+ j 1)))
                                   (freq (make-vector 26 0)))
                              (for ((c (in-string sub)))
                                (vector-set! freq (- (char->integer c) (char->integer #\a))
                                             (+ 1 (vector-ref freq (- (char->integer c) (char->integer #\a))))))
                              (let* ((max-freq (apply max (vector->list freq)))
                                     (min-freq (let loop ((i 0) (min-val max-freq))
                                                  (if (= i 26)
                                                      min-val
                                                      (if (and (> (vector-ref freq i) 0) (< (vector-ref freq i) min-val))
                                                          (loop (+ i 1) (vector-ref freq i))
                                                          (loop (+ i 1) min-val)))))
                                (if (= max-freq 0)
                                    0
                                    (- max-freq min-freq)))))))))
    total-beauty))