(define (count-pairs-with-xor-in-range nums low high)
  (define (count-less-equal nums k)
    (define (trie-insert root num)
      (let loop ([root root] [num num] [bit 14])
        (if (< bit 0)
            root
            (let ([b (bitwise-bit-set? num bit)])
              (if b
                  (if (hash-has-key? root '1)
                      (loop (hash-ref root '1) num (- bit 1))
                      (let ([new-node (make-hash)])
                        (hash-set! root '1 new-node)
                        (loop new-node num (- bit 1))))
                  (if (hash-has-key? root '0)
                      (loop (hash-ref root '0) num (- bit 1))
                      (let ([new-node (make-hash)])
                        (hash-set! root '0 new-node)
                        (loop new-node num (- bit 1)))))))))

    (define (trie-query root num)
      (let loop ([root root] [num num] [bit 14] [count 0])
        (if (< bit 0)
            count
            (let ([b (bitwise-bit-set? num bit)])
              (if b
                  (if (hash-has-key? root '0)
                      (loop (hash-ref root '0) num (- bit 1) (+ count (hash-ref root '0 'count 0)))
                      (if (hash-has-key? root '1)
                          (loop (hash-ref root '1) num (- bit 1) count)
                          count))
                  (if (hash-has-key? root '1)
                      (loop (hash-ref root '1) num (- bit 1) (+ count (hash-ref root '1 'count 0)))
                      (if (hash-has-key? root '0)
                          (loop (hash-ref root '0) num (- bit 1) count)
                          count)))))))

    (let ([root (make-hash)])
      (for ([num nums])
        (let loop ([root root] [num num] [bit 14])
          (if (< bit 0)
              (hash-set! root 'count (+ (hash-ref root 'count 0) 1))
              (let ([b (bitwise-bit-set? num bit)])
                (if b
                    (if (hash-has-key? root '1)
                        (loop (hash-ref root '1) num (- bit 1))
                        (let ([new-node (make-hash)])
                          (hash-set! root '1 new-node)
                          (loop new-node num (- bit 1))))
                    (if (hash-has-key? root '0)
                        (loop (hash-ref root '0) num (- bit 1))
                        (let ([new-node (make-hash)])
                          (hash-set! root '0 new-node)
                          (loop new-node num (- bit 1)))))))))
      (let ([count 0])
        (for ([num nums])
          (set! count (+ count (trie-query root (bitwise-xor k num)))))
        (/ count 2)))))

  (- (count-less-equal nums high) (count-less-equal nums (- low 1))))