(define (maximum-xor queries m)
  (define (solve queries m)
    (let* ((nums (sort queries <))
           (max-xor (- (expt 2 m) 1))
           (result '())
           (current-xor 0))
      (for ([num (in-list nums)])
        (set! current-xor (bitwise-xor current-xor num)))
      (for ([i (in-range (length nums))])
        (set! result (append result (list (bitwise-xor current-xor max-xor))))
        (set! current_xor (bitwise-xor current_xor (list-ref nums i)))))
      (reverse result)))
  (solve queries m))