(define (closest-room rooms queries)
  (let* ((n (length rooms))
         (m (length queries))
         (indexed-queries (map (lambda (q i) (list (car q) (cadr q) i)) queries (range m)))
         (sorted-rooms (sort rooms (lambda (a b) (> (cadr a) (cadr b)))))
         (sorted-queries (sort indexed-queries (lambda (a b) (> (car a) (car b)))))
         (res (make-vector m)))
    (let loop ((i 0) (j 0) (available-rooms '()) )
      (if (= i m)
          (vector->list res)
          (let* ((query (list-ref sorted-queries i))
                 (pref-id (car query))
                 (min-size (cadr query))
                 (index (caddr query)))
            (let another-loop ((j j) (available-rooms available-rooms))
              (if (and (< j n) (>= (cadr (list-ref sorted-rooms j)) min-size))
                  (another-loop (+ j 1) (cons (list-ref sorted-rooms j) available-rooms))
                  (let* ((valid-rooms (sort available-rooms (lambda (a b) (< (car a) (car b)))))
                         (closest-room (find-closest-room pref-id valid-rooms)))
                    (vector-set! res index closest-room)
                    (loop (+ i 1) j available-rooms))))))))

(define (find-closest-room pref-id rooms)
  (cond
    [(null? rooms) -1]
    [else
     (let loop ((rooms rooms) (closest-room -1) (min-diff +inf.0))
       (if (null? rooms)
           closest-room
           (let* ((room (car rooms))
                  (room-id (car room))
                  (diff (abs (- pref-id room-id))))
             (if (< diff min-diff)
                 (loop (cdr rooms) room-id diff)
                 (if (= diff min-diff)
                     (loop (cdr rooms) (min closest-room room-id) diff)
                     (loop (cdr rooms) closest-room min-diff))))))]))