(define (rotate-matrix matrix)
  (let* ((n (length matrix))
         (rotated-matrix (make-vector n (make-vector n #f))))
    (for ((i (in-range n))
          (j (in-range n)))
      (vector-set! (vector-ref rotated-matrix j) (- n i 1) (vector-ref (vector-ref matrix i) j)))
    rotated-matrix))

(define (matrices-equal? m1 m2)
  (and (= (length m1) (length m2))
       (andmap (λ (i)
                 (and (= (length (vector-ref m1 i)) (length (vector-ref m2 i)))
                      (andmap (λ (j) (= (vector-ref (vector-ref m1 i) j) (vector-ref (vector-ref m2 i) j)))
                              (range 0 (length (vector-ref m1 i))))))
               (range 0 (length m1)))))

(define (solve matrix target)
  (or (matrices-equal? matrix target)
      (matrices-equal? (rotate-matrix matrix) target)
      (matrices-equal? (rotate-matrix (rotate-matrix matrix)) target)
      (matrices-equal? (rotate-matrix (rotate-matrix (rotate-matrix matrix))) target)))

(define (can-find-rotation matrix target)
  (solve matrix target))