(define (count-palindromic-subsequences s)
  (let* ((n (string-length s))
         (chars (remove-duplicates (string->list s)))
         (count 0))
    (for* ((c chars))
      (let* ((first-index (string-index s (string c)))
             (last-index (string-last-index s (string c))))
        (when (and first-index last-index (< first-index last-index))
          (let ((middle-chars (set)))
            (for ((i (in-range (+ first-index 1) last-index)))
              (set-add! middle-chars (string-ref s i)))
            (set! count (+ count (set-count middle-chars)))))))
    count))