(define (max-distance colors)
  (let* ((n (length colors))
         (left (for/first ([i (in-range n)])
                 (and (not (equal? (list-ref colors 0) (list-ref colors i)))
                      i)))
         (right (for/last ([i (in-range n 0 -1)])
                  (and (not (equal? (list-ref colors (- n 1)) (list-ref colors i)))
                       i))))
    (max (- left 0) (- (- n 1) right))))