(define (count-common-words word1 word2)
  (define (count-words words)
    (let ((counts (hash)))
      (for-each (lambda (word)
                  (hash-update! counts word (lambda (k v) (+ v 1)) 1))
                words)
      counts))

  (define counts1 (count-words word1))
  (define counts2 (count-words word2))

  (let ((common-count 0))
    (for-each (lambda (word)
                (when (and (hash-has-key? counts1 word)
                           (hash-has-key? counts2 word)
                           (= (hash-ref counts1 word) 1)
                           (= (hash-ref counts2 word) 1))
                  (set! common-count (+ common-count 1))))
              (set->list (list->set (append word1 word2))))
    common-count))