(define (find-order num-courses prerequisites)
  (define in-degree (make-vector num-courses 0))
  (define adj-list (make-vector num-courses '()))
  (for ([p prerequisites])
    (let ([course (car p)]
          [pre (cadr p)])
      (vector-set! in-degree course (+ (vector-ref in-degree course) 1))
      (vector-set! adj-list pre (cons course (vector-ref adj-list pre)))))

  (define q (list))
  (for ([i (range num-courses)])
    (if (= (vector-ref in-degree i) 0)
        (set! q (append q (list i)))))

  (define result '())
  (define count 0)

  (let loop ()
    (if (null? q)
        (if (= count num-courses)
            (reverse result)
            '())
        (let ([node (car q)])
          (set! q (cdr q))
          (set! result (cons node result))
          (set! count (+ count 1))
          (for ([neighbor (vector-ref adj-list node)])
            (vector-set! in-degree neighbor (- (vector-ref in-degree neighbor) 1))
            (if (= (vector-ref in-degree neighbor) 0)
                (set! q (append q (list neighbor)))))
          (loop))))
  (loop))