(define (possible-to-stamp grid stamp-height stamp-width)
  (define rows (length grid))
  (define cols (length (first grid)))

  (define need (make-vector rows (make-vector cols 0)))
  (define sum (make-vector (add1 rows) (make-vector (add1 cols) 0)))

  (for ([i (in-range rows)])
    (for ([j (in-range cols)])
      (vector-set! (vector-ref sum (add1 i)) (add1 j)
                   (+ (vector-ref (vector-ref sum (add1 i)) j)
                      (vector-ref (vector-ref sum i) (add1 j))
                      (- (vector-ref (vector-ref sum i) j))
                      (if (= (vector-ref (vector-ref grid i) j) 1) 1 0)))))

  (for ([i (in-range (- rows stamp-height -1))])
    (for ([j (in-range (- cols stamp-width -1))])
      (define rect-sum (- (vector-ref (vector-ref sum (+ i stamp-height)) (+ j stamp-width))
                           (vector-ref (vector-ref sum (+ i stamp-height)) j)
                           (vector-ref (vector-ref sum i) (+ j stamp-width))
                           (vector-ref (vector-ref sum i) j)))
      (if (= rect-sum 0)
          (for ([x (in-range i (+ i stamp-height))])
            (for ([y (in-range j (+ j stamp-width))])
              (vector-set! (vector-ref need x) y 1))))))

  (for ([i (in-range rows)])
    (for ([j (in-range cols)])
      (if (and (= (vector-ref (vector-ref grid i) j) 0)
               (= (vector-ref (vector-ref need i) j) 0))
          (return #f))))
  #t)