(define (find-lonely nums)
  (let* ((counts (make-hash))
         (result '()))
    (for-each (lambda (n)
                (hash-update! counts n (lambda (v) (+ v 1)) 1))
              nums)
    (for-each (lambda (n)
                (if (and (= (hash-ref counts n) 1)
                         (not (hash-has-key? counts (+ n 1)))
                         (not (hash-has-key? counts (- n 1))))
                    (set! result (cons n result))))
              nums)
    result))