(define (minimum-difference (nums (vectorof integer?)))
  (define n (vector-length nums))
  (define k (/ n 3))

  (define (sum-subvector v start end)
    (for/sum ((i (in-range start end)))
      (vector-ref v i)))

  (define (solve nums)
    (define min-heap (make-heap <))
    (define prefix-sums (make-vector (+ n 1) 0))
    (for ((i (in-range n)))
      (heap-add! min-heap (vector-ref nums i))
      (when (> (heap-count min-heap) k)
        (heap-remove-min! min-heap))
      (when (= (heap-count min-heap) k)
        (vector-set! prefix-sums (+ i 1) (+ (sum-subvector nums 0 (+ i 1)) (- (heap-sum min-heap)))))
    (define max-heap (make-heap >))
    (define suffix-sums (make-vector (+ n 1) 0))
    (for ((i (in-range (- n 1) -1 -1)))
      (heap-add! max-heap (vector-ref nums i))
      (when (> (heap-count max-heap) k)
        (heap-remove-max! max-heap))
      (when (= (heap-count max-heap) k)
        (vector-set! suffix-sums i (- (sum-subvector nums i n) (heap-sum max-heap)))))

    (define min-diff +inf.0)
    (for ((i (in-range k (- n k 1))))
      (set! min-diff (min min-diff (- (vector-ref prefix-sums (+ i 1)) (vector-ref suffix-sums (+ i 1))))))
    min-diff)

  (solve nums))