(define (get-skyline buildings)
  (define (sort-events events)
    (sort events (lambda (e1 e2)
                   (or (< (car e1) (car e2))
                       (and (= (car e1) (car e2))
                            (if (positive? (cadr e1))
                                (> (cadr e2) 0)
                                (< (cadr e2) 0)))))))

  (define (update-heap heap height)
    (if (positive? height)
        (heap-push! heap height)
        (heap-remove! heap (- height))))

  (define (get-max-height heap)
    (if (heap-empty? heap)
        0
        (heap-top heap)))

  (let* ((events (apply append (map (lambda (b)
                                       (list (list (car b) (cadr b))
                                             (list (cadr b) (- (caddr b)))))
                                   buildings)))
         (sorted-events (sort-events events))
         (heap (make-heap <))
         (result '())
         (current-height 0))
    (for ([event (in-list sorted-events)])
      (let* ((x (car event))
             (height (cadr event)))
        (update-heap heap height)
        (let ((max-height (get-max-height heap)))
          (if (not (= max-height current-height))
              (begin
                (set! result (append result (list (list x max-height))))
                (set! current-height max-height))))))
    result))