(define (get-ancestors n edges)
  (define adj (make-vector n '()))
  (for ([e edges])
    (let ([u (car e)] [v (cadr e)])
      (vector-set! adj v (cons u (vector-ref adj v)))))

  (define (dfs start node visited)
    (if (hash-has-key? visited node)
        (hash-ref visited node)
        (let ([ancestors (make-hash)])
          (hash-set! visited node ancestors)
          (for ([neighbor (vector-ref adj node)])
            (hash-set! ancestors neighbor #t)
            (for ([ancestor (hash-keys (dfs start neighbor visited))])
              (hash-set! ancestors ancestor #t)))
          ancestors)))

  (define result (make-vector n '()))
  (for ([i (range n)])
    (let ([ancestors (dfs i i (make-hash))])
      (vector-set! result i (sort (hash-keys ancestors) <))))
  result)