(define (max-value-of-coins piles k)
  (define n (length piles))
  (define dp (make-vector (+ k 1) 0))

  (for ([i (in-range n)])
    (define pile (list-ref piles i))
    (define m (length pile))
    (for ([j (in-range (add1 k) 0 -1)])
      (define current-sum 0)
      (for ([x (in-range (min (add1 m) (add1 j)))])
        (if (> x 0)
            (set! current-sum (+ current-sum (list-ref pile (- x 1)))))
        (set! (vector-ref dp j) (max (vector-ref dp j)
                                     (+ current-sum (vector-ref dp (- j x))))))))
  (vector-ref dp k))