(define (compute-area ax1 ay1 ax2 ay2 bx1 by1 bx2 by2)
  (let* ((areaA (* (- ax2 ax1) (- ay2 ay1)))
         (areaB (* (- bx2 bx1) (- by2 by1)))
         (left (max ax1 bx1))
         (right (min ax2 bx2))
         (bottom (max ay1 by1))
         (top (min ay2 by2))
         (overlap-width (max 0 (- right left)))
         (overlap-height (max 0 (- top bottom)))
         (overlap-area (* overlap-width overlap-height)))
    (- (+ areaA areaB) overlap-area)))