(define (count-texts pressed-keys)
  (let* ((n (string-length pressed-keys))
         (dp (make-vector (add1 n) 0))
         (mod (expt 10 9 7)))
    (vector-set! dp 0 1)
    (for ((i (in-range 1 (add1 n))))
      (let loop ((j (min i 4)))
        (when (positive? j)
          (let ((sub (substring pressed-keys (- i j) i)))
            (when (and (string=? sub (make-string j (string-ref pressed-keys (- i 1))))
                       (or (not (or (string=? (string-ref pressed-keys (- i 1)) #\7) (string=? (string-ref pressed-keys (- i 1)) #\9)))
                           (and (or (string=? (string-ref pressed-keys (- i 1)) #\7) (string=? (string-ref pressed-keys (- i 1)) #\9)) (= j 4))))
              (vector-set! dp i (modulo (+ (vector-ref dp i) (vector-ref dp (- i j))) mod))))
          (loop (- j 1)))))
    (vector-ref dp n)))