(define (make-text-editor)
  (let ((left '())
        (right '()))
    (define (move-cursor-left n)
      (cond
        ((zero? n) #t)
        ((empty? left) #t)
        (else (begin
                (set! right (cons (car left) right))
                (set! left (cdr left))
                (move-cursor-left (- n 1))))))
    (define (move-cursor-right n)
      (cond
        ((zero? n) #t)
        ((empty? right) #t)
        (else (begin
                (set! left (cons (car right) left))
                (set! right (cdr right))
                (move-cursor-right (- n 1))))))
    (define (insert-text text)
      (set! left (append (string->list text) left)))
    (define (delete-text n)
      (cond
        ((zero? n) #t)
        ((empty? left) #t)
        (else (begin
                (set! left (cdr left))
                (delete-text (- n 1))))))
    (define (cursor-left n)
      (move-cursor-left n)
      #t)
    (define (cursor-right n)
      (move-cursor-right n)
      #t)
    (define (insert text)
      (insert-text text)
      #t)
    (define (delete n)
      (delete-text n)
      #t)
    (define (text)
      (list->string (take (reverse left) (min 10 (length left)))))
    (define (dispatch method . args)
      (case method
        ((cursorLeft) (apply cursor-left args))
        ((cursorRight) (apply cursor-right args))
        ((insertText) (apply insert args))
        ((deleteText) (apply delete args))
        ((show) (text))
        (else (error "invalid method"))))
    dispatch))