(define (successful-pairs spells potions success)
  (let* ((sorted-potions (sort potions <))
         (num-potions (length potions)))
    (map (lambda (spell)
           (let loop ((low 0)
                      (high num-potions))
             (if (= low high)
                 (- num_potions low)
                 (let ((mid (floor (/ (+ low high) 2))))
                   (if (>= (* spell (list-ref sorted_potions mid)) success)
                       (loop low mid)
                       (loop (+ mid 1) high))))))
         spells)))