(define (equal-row-column-pairs grid)
  (let* ((n (length grid))
         (count 0))
    (for* ((i (in-range n))
           (j (in-range n)))
      (let ((row (list-ref grid i))
            (col (map (lambda (r) (list-ref r j)) grid)))
        (when (equal? row col)
          (set! count (+ count 1)))))
    count))