(define (arithmeticTriplets nums diff)
  (let ((count 0))
    (for* ((i (range (length nums)))
           (j (range (+ i 1) (length nums)))
           #:when (= (- (list-ref nums j) (list-ref nums i)) diff)
           (k (range (+ j 1) (length nums)))
           #:when (= (- (list-ref nums k) (list-ref nums j)) diff))
      (set! count (+ count 1)))
    count))