(define (build-matrix k rowConditions colConditions)
  (define (topological-sort adj)
    (define (dfs u visited stack)
      (set! visited (hash-set visited u #t))
      (for ([v (in-list (hash-ref adj u '()))])
        (when (not (hash-ref visited v #f))
          (dfs v visited stack)))
      (set! stack (cons u stack))
      stack)

    (define (get-adj-list lst)
      (define adj (make-hash))
      (for ([i (in-range 1 (+ k 1))])
        (hash-set! adj i '()))
      (for ([pair (in-list lst)])
        (define u (car pair))
        (define v (cdr pair))
        (hash-set! adj u (cons v (hash-ref adj u '()))))
      adj)

    (define adj (get-adj-list adj))
    (define visited (make-hash))
    (define stack '())
    (for ([i (in-range 1 (+ k 1))])
      (when (not (hash-ref visited i #f))
        (set! stack (dfs i visited stack))))
    stack)

  (define (create-matrix row-order col-order)
    (define row-pos (make-hash))
    (define col-pos (make-hash))
    (for ([i (in-range 0 k)])
      (hash-set! row-pos (list-ref row-order i) i)
      (hash-set! col-pos (list-ref col-order i) i))

    (define matrix (make-vector k (make-vector k 0)))
    (for ([i (in-range 1 (+ k 1))])
      (vector-set! (vector-ref matrix (hash-ref row-pos i)) (hash-ref col-pos i) i))
    matrix)

  (define row-order (topological-sort rowConditions))
  (define col-order (topological-sort colConditions))

  (if (and (= (length row-order) k) (= (length col-order) k))
      (create-matrix row-order col-order)
      '())
  )