(define (match-players-trainers players trainers)
  (let* ((sorted-players (sort players <))
         (sorted-trainers (sort trainers <))
         (player-idx 0)
         (trainer-idx 0)
         (match-count 0))
    (while (and (< player-idx (length sorted-players))
                (< trainer-idx (length sorted-trainers)))
      (if (<= (list-ref sorted-players player-idx) (list-ref sorted-trainers trainer-idx))
          (begin
            (set! match-count (+ match-count 1))
            (set! player-idx (+ player-idx 1))
            (set! trainer-idx (+ trainer-idx 1)))
          (set! trainer-idx (+ trainer-idx 1))))
    match-count))