(define (find-max-k nums)
  (let* ((s (set))
         (max-k -1))
    (for ([num nums])
      (set-add! s num))
    (for ([num nums])
      (when (and (> num 0) (set-member? s (- num)))
        (set! max-k (max max-k num))))
    max-k))