(define (most-popular-creator creators ids views)
  (let* ((creator-view-map (make-hash))
         (creator-id-map (make-hash))
         (n (length creators)))
    (for ([i (in-range n)])
      (let* ((creator (list-ref creators i))
             (view (list-ref views i))
             (id (list-ref ids i)))
        (hash-update! creator-view-map creator (λ (v) (+ v view)) 0)
        (hash-update! creator-id-map creator (λ (ids) (append ids (list (cons id view)))) (list))))
    (let* ((max-view (apply max (hash-values creator-view-map)))
           (popular-creators (filter (λ (c) (= (hash-ref creator-view-map c) max-view)) (hash-keys creator-view-map))))
      (map (λ (creator)
             (let* ((id-views (hash-ref creator-id-map creator))
                    (max-id (car (sort (λ (x y) (cond
                                                   ((> (cdr x) (cdr y)) #t)
                                                   ((< (cdr x) (cdr y)) #f)
                                                   (else (string<? (car x) (car y))))) id-views))))
               max-id)) popular-creators))))