(define (count-good-strings low high zero one)
  (define MOD 1000000007)
  (define dp (make-vector (+ high 1) 0))
  (vector-set! dp 0 1)
  (for ([i (in-range 1 (+ high 1))])
    (when (>= i zero)
      (vector-set! dp i (modulo (+ (vector-ref dp i) (vector-ref dp (- i zero))) MOD)))
    (when (>= i one)
      (vector-set! dp i (modulo (+ (vector-ref dp i) (vector-ref dp (- i one))) MOD))))
  (define result 0)
  (for ([i (in-range low (+ high 1))])
    (set! result (modulo (+ result (vector-ref dp i)) MOD)))
  result)