(define (max-score nums k)
  (define pq (mutable-priority-queue (λ (a b) (> a b))))
  (for-each (λ (x) (priority-queue-add! pq x)) nums)
  (define score 0)
  (for ([i (in-range k)])
    (define top (priority-queue-remove! pq))
    (set! score (+ score top))
    (priority-queue-add! pq (ceiling (/ top 3))))
  score)