(define (minimumSplitsCost nums k)
  (let* ((n (length nums))
         (dp (make-vector (add1 n) 0)))
    (for ((i (in-range 1 (add1 n))))
      (vector-set! dp i (vector-ref dp (sub1 i)) )
      (for ((j (in-range 0 i)))
        (let* ((sub-array (subvector nums j i))
               (freq (make-hash))
               (cost 0))
          (for ((num (in-vector sub-array)))
            (hash-update! freq num add1 0))
          (for ((num (in-vector sub-array)))
            (when (> (hash-ref freq num) k)
              (set! cost 1)))
          (vector-set! dp i (min (vector-ref dp i) (+ (vector-ref dp j) cost))))))
    (vector-ref dp n)))

(define (minimumCostSplitArray nums k)
  (minimumSplitsCost nums k))