(define (monkey-move-count n)
  (define mod 1000000007)
  (define (pow base exp mod)
    (cond ((= exp 0) 1)
          ((even? exp)
           (let ((half-pow (pow base (/ exp 2) mod)))
             (modulo (* half-pow half-pow) mod)))
          (else (modulo (* base (pow base (- exp 1) mod)) mod))))
  (modulo (- (pow 2 n mod) 2) mod))