(define (count-quadruplets nums)
  (define n (length nums))
  (let loop ([i 0] [count 0])
    (if (= i (- n 3))
        count
        (let loop2 ([j (+ i 1)] [count count])
          (if (= j (- n 2))
              (loop (+ i 1) count)
              (let loop3 ([k (+ j 1)] [count count])
                (if (= k (- n 1))
                    (loop2 (+ j 1) count)
                    (let loop4 ([l (+ k 1)] [count count])
                      (if (= l n)
                          (loop3 (+ k 1) count)
                          (if (and (< (list-ref nums i) (list-ref nums k))
                                   (> (list-ref nums k) (list-ref nums j))
                                   (> (list-ref nums j) (list-ref nums l)))
                              (loop4 (+ l 1) (+ count 1))
                              (loop4 (+ l 1) count)))))))))))