(define (make-k-subarray-sums-equal nums k)
  (define n (length nums))
  (define (gcd a b)
    (if (= b 0)
        a
        (gcd b (remainder a b))))
  (define k (gcd k n))
  (define groups (make-vector k '()))
  (for ([i (in-range n)])
    (vector-set! groups (remainder i k) (append (vector-ref groups (remainder i k)) (list (list-ref nums i)))))
  (define (median lst)
    (define sorted-lst (sort lst <))
    (define len (length sorted-lst))
    (if (odd? len)
        (list-ref sorted-lst (quotient len 2))
        (/ (+ (list-ref sorted-lst (quotient len 2)) (list-ref sorted-lst (- (quotient len 2) 1))) 2)))
  (define (min-moves lst)
    (define med (median lst))
    (foldl (lambda (x acc) (+ acc (abs (- x med)))) 0 lst))
  (foldl (lambda (group acc) (+ acc (min-moves group))) 0 (vector->list groups)))