(define (find-prefix-common-array A B)
  (let* ((n (length A))
         (result (make-vector n 0)))
    (for ([i (in-range n)])
      (let* ((common 0)
             (seen (make-hash)))
        (for ([j (in-range (+ 1 i))])
          (hash-set! seen (list-ref A j) #t))
        (for ([j (in-range (+ 1 i))])
          (when (hash-has-key? seen (list-ref B j))
            (set! common (+ common 1))))
        (vector-set! result i common)))
    (vector->list result)))