(define (count-complete-components n edges)
  (define g (make-digraph))
  (for-each (lambda (edge)
              (define u (car edge))
              (define v (cdr edge))
              (add-edge! g u v)
              (add-edge! g v u))
            edges)
  (define visited (make-vector (add1 n) #f))
  (define count 0)
  (define (dfs v component)
    (vector-set! visited v #t)
    (set! component (cons v component))
    (for-each (lambda (neighbor)
                (unless (vector-ref visited neighbor)
                  (dfs neighbor component)))
              (digraph->neighbors g v))
    component)
  (for ([i (in-range 1 (add1 n))])
    (unless (vector-ref visited i)
      (define component (dfs i '()))
      (define component-size (length component))
      (define num-edges 0)
      (for* ([u (in-list component)]
             [v (in-list component)])
        (when (and (not (= u v)) (digraph-has-edge? g u v))
          (set! num-edges (add1 num-edges))))
      (define expected-edges (* component-size (sub1 component-size)))
      (when (= num-edges expected-edges)
        (set! count (add1 count)))))
  count)