(define (count-black-blocks n m coordinates)
  (let* ((grid (make-hash))
         (result (make-vector 5 0)))
    (for ([coord coordinates])
      (let* ((row (car coord))
             (col (cdr coord)))
        (for ([i (in-range -1 1)])
          (for ([j (in-range -1 1)])
            (let ((r (+ row i))
                  (c (+ col j)))
              (when (and (>= r 1) (<= r (- n 1)) (>= c 1) (<= c (- m 1)))
                (dict-set! grid (cons r c) (add1 (dict-ref grid (cons r c) 0)))))))))
    (for-each (lambda (k v) (vector-set! result v (add1 (vector-ref result v)))) (hash->list grid))
    (let ((zero (- (* (- n 1) (- m 1)) (apply + (vector->list result)))))
      (vector-set! result 0 zero))
    (vector->list result)))