(define (min-edge-reversals n edges)
  (define adj (make-vector n '()))
  (define adj-rev (make-vector n '()))
  (for-each (lambda (edge)
              (vector-set! adj (car edge) (cons (cdr edge) (vector-ref adj (car edge)))))
            edges)
  (for-each (lambda (edge)
              (vector-set! adj-rev (car edge) (cons (cdr edge) (vector-ref adj-rev (car edge)))))
            edges)

  (define (bfs start)
    (define visited (make-vector n #f))
    (define queue (list start))
    (vector-set! visited start #t)
    (define count 0)
    (let loop ()
      (if (null? queue)
          count
          (let ((curr (car queue))
                (rest (cdr queue)))
            (for-each (lambda (neighbor)
                        (unless (vector-ref visited neighbor)
                          (vector-set! visited neighbor #t)
                          (set! queue (append queue (list neighbor)))))
                      (vector-ref adj curr))
            (set! queue rest)
            (loop))))
    )

  (define (count-reversals start)
    (define visited (make-vector n #f))
    (define queue (list start))
    (vector-set! visited start #t)
    (define count 0)
    (let loop ()
      (if (null? queue)
          count
          (let ((curr (car queue))
                (rest (cdr queue)))

            (for-each (lambda (neighbor)
                         (unless (vector-ref visited neighbor)
                           (vector-set! visited neighbor #t)
                           (set! queue (append queue (list neighbor)))))
                      (vector-ref adj curr))

            (for-each (lambda (neighbor)
                         (unless (vector-ref visited neighbor)
                           (vector-set! visited neighbor #t)
                           (set! count (+ count 1))
                           (set! queue (append queue (list neighbor)))))
                      (filter (lambda (x) (not (member x (vector-ref adj curr)))) (vector-ref adj-rev curr)))

            (set! queue rest)
            (loop))))
    )

  (map count-reversals (range 0 n))
  )