(define (fill-missing-data df)
  (let* ((n (dataframe-rows df))
         (date-col (dataframe-column df 'sale_date))
         (product-col (dataframe-column df 'product_id'))
         (sales-col (dataframe-column df 'units_sold)))
    (let loop ((i 0)
               (result '()))
      (if (= i n)
          (dataframe 'sale_date (list->vector (map car result))
                     'product_id (list->vector (map cadr result))
                     'units_sold (list->vector (map caddr result)))
          (let ((date (vector-ref date-col i))
                (product (vector-ref product-col i))
                (sales (vector-ref sales-col i)))
            (if (null? sales)
                (loop (+ i 1) (cons (list date product 0) result))
                (loop (+ i 1) (cons (list date product sales) result))))))))