(define (maximum-score-after-operations nums edges)
  (let* ((n (length nums))
         (graph (make-vector n '()))
         (total-sum (apply + nums)))
    (for-each (lambda (edge)
                (let ((u (car edge))
                      (v (cadr edge)))
                  (vector-set! graph u (cons v (vector-ref graph u)))
                  (vector-set! graph v (cons u (vector-ref graph v)))))
              edges)
    (letrec ((dfs (lambda (node parent)
                     (let ((children (filter (lambda (child) (not (equal? child parent))) (vector-ref graph node))))
                       (if (null? children)
                           (vector-ref nums node)
                           (let ((min-child-sums (map (lambda (child) (dfs child node)) children)))
                             (- (vector-ref nums node)
                                (apply + min-child-sums)
                                (+ (apply + (map (lambda (x) (max 0 x)) min-child-sums))))))))))
      (max 0 (dfs 0 -1)))))