(define (getHint secret guess)
  (let* ((secret-list (string->list secret))
         (guess-list (string->list guess))
         (bulls (count (λ (i) (equal? (list-ref secret-list i) (list-ref guess-list i))) (range 0 (string-length secret))))
         (secret-counts (make-hash))
         (guess-counts (make-hash)))
    (for ([i (in-range (string-length secret))])
      (unless (equal? (list-ref secret-list i) (list-ref guess-list i))
        (hash-update! secret-counts (list-ref secret-list i) (λ (v) (+ v 1)) 0)
        (hash-update! guess-counts (list-ref guess-list i) (λ (v) (+ v 1)) 0)))
    (let* ((cows (foldl + 0 (map (λ (k) (min (hash-ref secret-counts k 0) (hash-ref guess-counts k 0))) (hash-keys secret-counts))))
           (result (string-append (number->string bulls) "A" (number->string cows) "B")))
      result)))