(define (count-houses-at-certain-distance n houses adj)
  (define (bfs start)
    (define dist (make-vector (add1 n) -1))
    (vector-set! dist start 0)
    (define q (queue))
    (enqueue! q start)
    (while (not (queue-empty? q))
      (define u (dequeue! q))
      (for-each (lambda (v)
                  (when (= (vector-ref dist v) -1)
                    (vector-set! dist v (+ 1 (vector-ref dist u)))
                    (enqueue! q v)))
                (vector-ref adj u)))
    dist)

  (define dists (make-vector houses #f))
  (for ([i (in-range houses)])
    (vector-set! dists i (bfs (+ i 1))))

  (define result (make-vector n 0))
  (for ([i (in-range (add1 n))])
    (for ([j (in-range houses)])
      (define dist (vector-ref (vector-ref dists j) i))
      (vector-set! result (- dist 1) (+ 1 (vector-ref result (- dist 1))))))
  result)

(define (count-of-nodes n houses edges)
  (define adj (make-vector (add1 n) '()))
  (for ([edge (in-list edges)])
    (let ([u (car edge)] [v (cadr edge)])
      (vector-set! adj u (cons v (vector-ref adj u)))
      (vector-set! adj v (cons u (vector-ref adj v)))))

  (define houses-vec (make-vector houses 0))
  (for ([i (in-range houses)])
      (vector-set! houses-vec i (+ i 1)))

  (vector->list (count-houses-at-certain-distance n houses adj)))