(define (NumMatrix matrix)
  (let* ((rows (length matrix))
         (cols (if (null? matrix) 0 (length (car matrix))))
         (sum-matrix (make-matrix (+ rows 1) (+ cols 1) 0)))
    (for ([i (in-range 0 rows)])
      (for ([j (in-range 0 cols)])
        (matrix-set! sum-matrix (+ i 1) (+ j 1)
                     (+ (matrix-ref matrix i j)
                        (matrix-ref sum-matrix i (+ j 1))
                        (matrix-ref sum-matrix (+ i 1) j)
                        (- (matrix-ref sum-matrix i j))))))
    (lambda (row1 col1 row2 col2)
      (- (+ (matrix-ref sum-matrix (+ row2 1) (+ col2 1))
            (matrix-ref sum-matrix row1 col1))
         (+ (matrix-ref sum-matrix row1 (+ col2 1))
            (matrix-ref sum-matrix (+ row2 1) col1))))))