(define (most-frequent-ids ids)
  (let ((counts (make-hash)))
    (for-each (lambda (id)
                (hash-update! counts id (lambda (v) (+ v 1)) 1))
              ids)
    (let loop ((ids (hash-keys counts))
               (max-id #f)
               (max-count 0))
      (if (null? ids)
          (if (eq? max-id #f)
              '()
              (list max-id))
          (let ((id (car ids))
                (count (hash-ref counts id)))
            (if (> count max-count)
                (loop (cdr ids) id count)
                (if (= count max-count)
                    (loop (cdr ids) (if (< id max-id) id max-id) count)
                    (loop (cdr ids) max-id max-count))))))))