(define (find-min-height-trees n edges)
  (if (= n 1)
      '(0)
      (let* ((adj-list (make-vector n '()))
             (degrees (make-vector n 0)))
        (for-each (lambda (edge)
                    (let ((u (car edge))
                          (v (cadr edge)))
                      (vector-set! adj-list u (cons v (vector-ref adj-list u)))
                      (vector-set! adj-list v (cons u (vector-ref adj-list v)))
                      (vector-set! degrees u (+ 1 (vector-ref degrees u)))
                      (vector-set! degrees v (+ 1 (vector-ref degrees v)))))
                  edges)
        (let loop ((leaves (filter (lambda (i) (= 1 (vector-ref degrees i))) (range n)))
                   (remaining n))
          (if (<= remaining 2)
              leaves
              (let* ((new-leaves '()))
                (for-each (lambda (leaf)
                            (let ((neighbors (vector-ref adj-list leaf)))
                              (for-each (lambda (neighbor)
                                          (vector-set! degrees neighbor (- (vector-ref degrees neighbor) 1))
                                          (if (= 1 (vector-ref degrees neighbor))
                                              (set! new-leaves (cons neighbor new-leaves))))
                                        neighbors)))
                          leaves)
                (loop new-leaves (- remaining (length leaves)))))))))