(define (minimum-operations conditions)
  (let* ((n (length conditions))
         (adj (make-vector n '()))
         (indegrees (make-vector n 0)))
    (for-each (lambda (condition)
                (let ((i (car condition))
                      (j (cadr condition)))
                  (vector-set! adj i (cons j (vector-ref adj i)))
                  (vector-set! indegrees j (+ 1 (vector-ref indegrees j)))))
              conditions)
    (let loop ((queue (list))
               (count 0))
      (for ((i (in-range n)))
        (when (= 0 (vector-ref indegrees i))
          (set! queue (cons i queue))))
      (if (null? queue)
          (if (= count n)
              0
              -1)
          (let ((u (car queue))
                (rest (cdr queue)))
            (let ((neighbors (vector-ref adj u)))
              (for-each (lambda (v)
                          (vector-set! indegrees v (- (vector-ref indegrees v) 1)))
                        neighbors))
            (loop rest (+ 1 count)))))))