(define (check-if-grid-satisfies-conditions grid)
  (let* ((m (length grid))
         (n (length (car grid))))
    (and
     (for/and ((i (in-range m)))
       (let ((row (list-ref grid i)))
         (let ((sorted-row (sort row <)))
           (for/and ((j (in-range n)))
             (let ((num (list-ref row j)))
               (>= num (list-ref sorted-row j)))))))
     (for/and ((j (in-range n)))
       (let ((col (map (lambda (row) (list-ref row j)) grid)))
         (let ((sorted-col (sort col <)))
           (for/and ((i (in-range m)))
             (let ((num (list-ref col i)))
               (>= num (list-ref sorted-col i))))))))))