(define (minimum-average-of-smallest-and-largest nums k)
  (let* ((n (length nums))
         (sums (make-vector (+ n 1) 0)))
    (for/fold ((i 0))
              ((num nums)
               (idx (in-range n)))
      (vector-set! sums (+ idx 1) (+ (vector-ref sums idx) num))
      (+ i 1))
    (let loop ((i 0)
               (min-avg +inf.0))
      (if (> (+ i k) n)
          min-avg
          (let* ((sub-array (subvector nums i (+ i k)))
                 (smallest (apply min sub-array))
                 (largest (apply max sub-array))
                 (avg (/ (+ smallest largest) 2.0)))
            (loop (+ i 1) (min min-avg avg)))))))