(define (lexicographically-smallest-string-after-swap s pairs)
  (define n (string-length s))
  (define uf (union-find n))
  (for-each (lambda (pair)
              (union uf (car pair) (cdr pair)))
            pairs)
  (define groups (make-hash))
  (for ([i (in-range n)])
    (define root (find uf i))
    (hash-update! groups root (lambda (lst) (cons i lst)) '()))
  (define result (string #\space n))
  (for ([root (in-hash-keys groups)])
    (define indices (sort (hash-ref groups root) <))
    (define chars (sort (map (lambda (i) (string-ref s i)) indices) char<?))
    (for ([i (in-range (length indices))])
      (string-set! result (list-ref indices i) (list-ref chars i))))
  result)