(define (find-the-power-of-k-size-subarrays nums k)
  (let* ((n (length nums))
         (sum 0)
         (res 0))
    (for ((i (in-range n)))
      (set! sum (+ sum (list-ref nums i)))
      (when (>= i (- k 1))
        (set! res (+ res (* sum sum)))
        (set! sum (- sum (list-ref nums (- i k -1))))))
    res))