(define (max-rook-sum board)
  (define rows (length board))
  (define cols (length (first board)))
  (define (calculate-sum r1 c1 r2 c2 r3 c3)
    (let* ((used-rows (list r1 r2 r3))
           (used-cols (list c1 c2 c3))
           (sum 0))
      (if (or (equal? r1 r2) (equal? r1 r3) (equal? r2 r3)
              (equal? c1 c2) (equal? c1 c3) (equal? c2 c3))
          -inf.0
          (begin
            (set! sum (+ (list-ref (list-ref board r1) c1)
                         (list-ref (list-ref board r2) c2)
                         (list-ref (list-ref board r3) c3)))
            sum))))

  (define (find-max)
    (let loop ((i 0) (max-sum -inf.0))
      (if (= i rows)
          max-sum
          (let loop2 ((j 0))
            (if (= j cols)
                (loop (+ i 1) max-sum)
                (let loop3 ((k (+ i 1)))
                  (if (= k rows)
                      (loop2 (+ j 1))
                      (let loop4 ((l 0))
                        (if (= l cols)
                            (loop3 (+ k 1))
                            (let loop5 ((m (+ k 1)))
                              (if (= m rows)
                                  (loop4 (+ l 1))
                                  (let loop6 ((n 0))
                                    (if (= n cols)
                                        (loop5 (+ m 1))
                                        (let ((current-sum (calculate-sum i j k l m n)))
                                          (loop6 (+ n 1) (max max-sum current-sum))))))))))))))))
  (find-max))