(define (max-sequence-value nums)
  (define n (length nums))
  (define (calculate-value i j k)
    (+ (* (list-ref nums i) (list-ref nums j)) (list-ref nums k)))
  (if (<= n 2)
      0
      (let loop ([i 0] [max-val -inf.0])
        (if (= i n)
            max-val
            (let loop2 ([j 0])
              (if (= j n)
                  (loop (+ i 1) max-val)
                  (let loop3 ([k 0])
                    (if (= k n)
                        (loop2 (+ j 1))
                        (loop3 (+ k 1)
                               (let ([val (calculate-value i j k)])
                                 (loop2 (+ j 1))
                                 (max max-val val))))))))))))