(define (count-substrings s k)
  (let* ((n (string-length s))
         (count (box 0)))
    (for* ((i (in-range n))
           (j (in-range i n)))
      (let* ((sub (substring s i (+ j 1)))
             (sub-len (string-length sub))
             (char-counts (make-hash)))
        (for ((c (in-string sub)))
          (hash-update! char-counts c add1 0))
        (let ((k-count 0))
          (hash-for-each char-counts (lambda (key val)
                                       (when (= val k)
                                         (set! k-count (+ k-count 1)))))
          (when (= k-count (hash-count char-counts))
            (set-box! count (+ (unbox count) 1))))))
    (unbox count)))