(define (minimum-division-operations nums)
  (let* ((n (length nums))
         (dp (make-vector n #f)))
    (vector-set! dp 0 0)
    (for ((i (in-range 1 n)))
      (let ((min-ops #f))
        (for ((j (in-range i -1 -1)))
          (let ((current-ops (vector-ref dp j)))
            (let ((temp-nums (list->vector (vector->list nums))))
              (for ((k (in-range j i)))
                (vector-set! temp-nums k (floor (/ (vector-ref temp-nums k) 2)))))
              (let ((is-non-decreasing #t))
                (for ((k (in-range j i)))
                  (when (> (vector-ref temp-nums k) (vector-ref temp-nums (+ k 1)))
                    (set! is-non-decreasing #f)
                    (break)))
                (when is-non-decreasing
                  (if (or (not min-ops) (< current-ops min-ops))
                      (set! min-ops current-ops))))))))
        (vector-set! dp i (if min-ops min-ops (+ (vector-ref dp (- i 1)) 1)))))
    (vector-ref dp (- n 1))))