(define (min-positive-sum-subarray nums)
  (let loop ([i 0] [min-len #f])
    (if (= i (length nums))
        (if min-len min-len -1)
        (let loop2 ([j i] [sum 0] [len 0])
          (if (= j (length nums))
              (loop (+ i 1) min-len)
              (let ([new-sum (+ sum (list-ref nums j))])
                (if (positive? new-sum)
                    (let ([new-min-len (if min-len (min min-len (+ len 1)) (+ len 1))])
                      (loop2 (+ j 1) new-sum (+ len 1)))
                    (loop2 (+ j 1) new-sum (+ len 1)))))))))