(define (count-connected-components-in-lcm-graph n)
  (define uf (new-union-find n))
  (for ([i (in-range 2 (+ n 1))])
    (for ([j (in-range (* 2 i) (+ n 1) i)])
      (union-find-union! uf (- i 1) (- j 1))))
  (length (union-find-sets uf)))