(define (max-area-rect points)
  (let* ((n (length points))
         (xs (sort (remove-duplicates (map car points)) <))
         (ys (sort (remove-duplicates (map cdr points)) <))
         (x-index (make-hash))
         (y-index (make-hash))
         (max-area 0))
    (for ([i (in-range (length xs))])
      (hash-set! x-index (list-ref xs i) i))
    (for ([i (in-range (length ys))])
      (hash-set! y-index (list-ref ys i) i))
    (for ([i (in-range n)])
      (for ([j (in-range (+ i 1) n)])
        (let* ((x1 (car (list-ref points i)))
               (y1 (cdr (list-ref points i)))
               (x2 (car (list-ref points j)))
               (y2 (cdr (list-ref points j)))
               (min-x (min x1 x2))
               (max-x (max x1 x2))
               (min-y (min y1 y2))
               (max-y (max y1 y2))
               (count 0))
          (for ([k (in-range n)])
            (let ((x (car (list-ref points k)))
                  (y (cdr (list-ref points k))))
              (when (and (<= min-x x max-x) (<= min-y y max-y))
                (set! count (+ count 1)))))
          (when (= count n)
            (set! max-area (max max-area (* (- max-x min-x) (- max-y min-y))))))))
    max-area))