(define (count-subarrays nums k)
  (let* ((n (length nums))
         (count 0))
    (for ((i (in-range 0 (- n 2))))
      (let ((a (list-ref nums i))
            (b (list-ref nums (+ i 1)))
            (c (list-ref nums (+ i 2))))
        (if (and (< (abs (- a b)) k)
                 (< (abs (- b c)) k)
                 (< (abs (- a c)) k))
            (set! count (+ count 1)))))
    count))