(define (unique-middle-mode-subsequences nums)
  (let* ((n (length nums))
         (count (make-hash))
         (result (make-hash)))
    (for* ((i (range n))
           (j (range i n)))
      (let* ((sub (list-ref nums (in-range i j)))
             (len (length sub)))
        (when (odd? len)
          (let* ((mid (quotient len 2))
                 (mid-val (list-ref sub mid))
                 (mode-count (make-hash))
                 (max-count 0))
            (for ((num sub))
              (hash-update! mode-count num add1 0))
            (for ((k (hash-keys mode-count)))
              (set! max-count (max max-count (hash-ref mode-count k))))
            (let ((is-unique-mode #t)
                  (mode-val #f))
              (for ((k (hash-keys mode-count)))
                (when (= (hash-ref mode-count k) max-count)
                  (if mode-val
                      (set! is-unique-mode #f)
                      (set! mode-val k))))
              (when (and is-unique-mode (= mode-val mid-val))
                (hash-set! count (list->string (map number->string sub)) #t)))))))
    (hash-count count)))