(define (create-task-manager)
  (let ([tasks (make-hash)])
    (define (add-task id priority)
      (hash-set! tasks id priority))
    (define (remove-task id)
      (hash-remove! tasks id))
    (define (get-next-task)
      (if (hash-empty? tasks)
          -1
          (let* ([task-list (hash->list tasks)]
                 [sorted-tasks (sort task-list (lambda (a b) (> (cdr a) (cdr b))))])
            (car (car sorted-tasks)))))
    (struct task-manager (add-task remove-task get-next-task))
    (task-manager add-task remove-task get-next-task)))

(define (main args)
  (let ([tm (create-task-manager)])
    ((task-manager-add-task tm) 1 3)
    ((task-manager-add-task tm) 2 4)
    (displayln ((task-manager-get-next-task tm)))
    ((task-manager-remove-task tm) 2)
    (displayln ((task-manager-get-next-task tm)))
    ((task-manager-remove-task tm) 1)
    (displayln ((task-manager-get-next-task tm)))))