(define (min-window s t)
  (define (all-chars-present? window-freq t-freq)
    (for/and ((c (in-list (string->list t))))
      (>= (hash-ref window-freq c 0) (hash-ref t-freq c 0))))

  (define (string->frequency-hash str)
    (for/hash ((c (in-list (string->list str))))
      (values c (+ (hash-ref (current-result-set) c 0) 1))))

  (let* ((s-len (string-length s))
         (t-len (string-length t))
         (t-freq (string->frequency-hash t))
         (min-len +inf.0)
         (min-start 0)
         (window-start 0)
         (window-freq (make-hash)))
    (for ((window-end (in-range s-len)))
      (let ((c (string-ref s window-end)))
        (hash-update! window-freq c add1 0)
        (when (all-chars-present? window-freq t-freq)
          (let loop ()
            (let ((start-char (string-ref s window-start)))
              (if (not (>= (hash-ref window-freq start-char 0)
                           (hash-ref t-freq start-char 0)))
                  (begin
                    (let ((current-len (- window-end window-start -1)))
                      (when (< current-len min-len)
                        (set! min-len current-len)
                        (set! min-start window-start))))
                  (begin
                    (hash-update! window-freq start-char sub1 0)
                    (when (not (>= (hash-ref window-freq start-char 0)
                                   (hash-ref t-freq start-char 0)))
                      (let ((current-len (- window-end window-start -1)))
                        (when (< current-len min-len)
                          (set! min-len current-len)
                          (set! min-start window-start)))
                      (set! window-start (+ window-start 1)))
                    (loop))))
            (let ((current-len (- window-end window-start -1)))
              (when (< current-len min-len)
                (set! min-len current-len)
                (set! min-start window-start))))))
    (if (= min-len +inf.0)
        ""
        (substring s min-start (+ min-start min-len 1)))))