(define (solve dna patterns)
  (let* ((n (string-length dna))
         (m (length patterns))
         (result (make-vector n #f)))
    (for ((i (in-range n)))
      (for ((pattern (in-list patterns)))
        (let ((pattern-length (string-length pattern)))
          (if (and (<= pattern-length (- n i))
                   (string=? (substring dna i (+ i pattern-length)) pattern))
              (for ((j (in-range i (+ i pattern-length))))
                (vector-set! result j #t))))))
    (let ((count 0))
      (for ((i (in-range n)))
        (if (vector-ref result i)
            (set! count (+ count 1))))
      count)))