(define (analyze-subscription-conversion events)
  (let* ((user-events (group-by (lambda (event) (hash-ref event "user_id")) events))
         (converted-users (filter (lambda (user)
                                    (let ((events (sort (hash-map user-events user)
                                                        (lambda (e1 e2) (< (string->number (hash-ref e1 "subscription_date"))
                                                                             (string->number (hash-ref e2 "subscription_date")))))))
                                      (and (>= (length events) 2)
                                           (equal? (hash-ref (list-ref events 0) "plan") "basic")
                                           (equal? (hash-ref (list-ref events (- (length events) 1)) "plan") "premium"))))
                                  (hash-keys user-events)))
         (total-users (length (hash-keys user-events)))
         (conversion-rate (if (zero? total-users)
                              0.0
                              (exact->inexact (/ (length converted-users) total-users)))))
    (format "~$.2f" (* conversion-rate 100))))