(define (maximize-active-sections n arr)
  (let* ((n (length arr))
         (dp (make-vector (+ n 1) 0)))
    (for/fold ((i 1))
              ((a (in-range 0 n)))
      (let ((active (if (> a 0) (vector-ref arr (- a 1)) 0))
            (inactive (if (> a 0) (- 1 (vector-ref arr (- a 1))) 0)))
        (vector-set! dp i (max (vector-ref dp (- i 1))
                               (+ (vector-ref dp (- i 1))
                                  (if (= (vector-ref arr a) 1) 1 0))))
        (+ i 1)))
    (vector-ref dp n)))