(define (min-cost-to-reach-every-position costs)
  (let* ((n (vector-length costs))
         (dp (make-vector n #f)))
    (vector-set! dp 0 (vector-ref costs 0))
    (for ((i (in-range 1 n)))
      (let ((cost-i (vector-ref costs i)))
        (vector-set! dp i
                     (min (+ cost-i (vector-ref dp (- i 1)))
                          (if (>= i 2)
                              (+ cost-i (vector-ref dp (- i 2)))
                              +inf.0)
                          (if (>= i 3)
                              (+ cost-i (vector-ref dp (- i 3)))
                              +inf.0)))))
    (vector-ref dp (- n 1))))