(define (minOperations nums k)
  (let* ((n (length nums))
         (dp (make-vector (add1 n) (make-vector (add1 k) n)))
         (helper (lambda (i j)
                     (cond ((or (< i 0) (< j 0)) n)
                           ((= i 0) 0)
                           ((= j 0) n)
                           (else (vector-ref (vector-ref dp i) j))))))
    (for* ((i (in-range 1 (add1 n)))
           (j (in-range 1 (add1 k))))
      (vector-set! (vector-ref dp i) j
                   (min (+ (helper (sub1 i) j) 1)
                        (let loop ((l (sub1 i))
                                   (count 0))
                          (cond ((< l 0) n)
                                ((= (list-ref nums l) (list-ref nums (sub1 i)))
                                 (min (helper (sub1 i) j) (+ (helper l (sub1 j)) count)))
                                (else (loop (sub1 l) (add1 count))))))))
    (helper n k)))