(define (count-triplets nums)
  (let* ((n (length nums))
         (count (make-hash)))
    (for ([i (in-range n)])
      (hash-update! count (list-ref nums i) add1 0))
    (let loop ([i 0] [ans 0])
      (if (= i n)
          ans
          (let* ((a (list-ref nums i))
                 (count-a (hash-ref count a))
                 (new-count (hash-copy count)))
            (hash-update! new-count a sub1 0)
            (let loop2 ([j (add1 i)] [ans2 ans])
              (if (= j n)
                  ans2
                  (let* ((b (list-ref nums j))
                         (c (bitwise-xor a b))
                         (count-c (hash-ref new-count c 0)))
                    (loop2 (add1 j) (+ ans2 count-c))))))))))