(define (count-numbers-with-non-decreasing-digits n)
  (letrec ((dp (make-vector 11 (make-vector (+ n 1) 0))))
    (for ((i (in-range 0 10)))
      (vector-set! (vector-ref dp i) 1 1))
    (for ((i (in-range 2 (+ n 1))))
      (for ((j (in-range 0 10)))
        (for ((k (in-range 0 (+ j 1)))
          (set! (vector-ref dp j) i (+ (vector-ref dp j i) (vector-ref dp k) (- i 1))))))
    (let ((result 0))
      (for ((i (in-range 0 10)))
        (set! result (+ result (vector-ref dp i) n)))
      (+ result 1))))