(define (seasonal-sales-analysis sales-data)
  (define sales-by-season (make-hash))
  (for ([sale sales-data])
    (define product (hash-ref sale 'product_id))
    (define spend (hash-ref sale 'spend))
    (define season (hash-ref sale 'season))
    (hash-update! sales-by-season season (lambda (x) (+ x spend)) 0))
  (define sorted-seasons (sort (hash-keys sales-by-season) string<?))
  (define result '())
  (for ([season sorted-seasons])
    (define total-spend (hash-ref sales-by-season season))
    (set! result (cons (list season total-spend) result)))
  (reverse result))

(provide seasonal-sales-analysis)