(define (minimumAbsDifference submatrix k)
  (let* ((n (matrix-num-rows submatrix))
         (m (matrix-num-cols submatrix))
         (min-diff (if (and (= n k) (= m k))
                       #f
                       +inf.0)))
    (for* ((i (in-range (- n k) (+ 1 -1)))
           (j (in-range (- m k) (+ 1 -1))))
      (let* ((sub (make-vector (* k k) 0))
             (idx 0))
        (for ((row (in-range i (+ i k))))
          (for ((col (in-range j (+ j k))))
            (vector-set! sub idx (matrix-ref submatrix row col))
            (set! idx (+ idx 1))))
        (vector-sort! sub <)
        (for ((l (in-range (- (* k k) 1) (+ 1 -1))))
          (let ((diff (abs (- (vector-ref sub (+ l 1)) (vector-ref sub l)))))
            (set! min-diff (min min-diff diff)))))
      )
    min-diff))