(define (erase-overlap-intervals intervals)
  (let* ((sorted-intervals (sort intervals (lambda (a b) (< (car a) (car b)))))
         (count 0)
         (end (caar sorted-intervals)))
    (for/list ((interval (cdr sorted-intervals)))
      (if (>= (car interval) end)
          (set! end (cadr interval))
          (set! count (+ count 1))
          (set! end (min end (cadr interval)))))
    count))