(define (permute nums)
  (define (helper current-permutation remaining-nums)
    (if (null? remaining-nums)
        (list current-permutation)
        (foldr append '()
               (map (lambda (num)
                      (helper (append current-permutation (list num))
                              (remove num remaining-nums)))
                    remaining-nums))))
  (helper '() nums))