(define (postorder root)
  (letrec ((helper (lambda (node acc)
                     (if (null? node)
                         acc
                         (let ((children (hash-ref node 'children #f)))
                           (if (not children)
                               (cons (hash-ref node 'val) acc)
                               (let loop ((lst children) (acc2 acc))
                                 (if (null? lst)
                                     (cons (hash-ref node 'val) acc2)
                                     (loop (cdr lst) (helper (car lst) acc2))))))))))
    (if (null? root)
        '()
        (reverse (helper root '())))))