(define (findLHS nums)
  (let* ((counts (make-hash))
         (max-len 0))
    (for-each (lambda (num)
                (hash-update! counts num (lambda (v) (+ v 1)) 1))
              nums)
    (for-each-key (lambda (num)
                    (let ((count (hash-ref counts num)))
                      (when (hash-has-key? counts (+ num 1))
                        (let ((neighbor-count (hash-ref counts (+ num 1))))
                          (set! max-len (max max-len (+ count neighbor-count)))))))
                  counts)
    max-len))