(define (k-inverse-pairs n k)
  (define MOD 1000000007)
  (define dp (make-vector (+ k 1) 0))
  (vector-set! dp 0 1)
  (for ([i (in-range 2 (+ n 1))])
    (define new-dp (make-vector (+ k 1) 0))
    (define prefix-sum 0)
    (for ([j (in-range (+ k 1))])
      (set! prefix-sum (+ prefix-sum (vector-ref dp j)))
      (set! prefix-sum (modulo prefix-sum MOD))
      (vector-set! new-dp j prefix-sum))
    (set! dp new-dp)
    (for ([j (in-range i (+ k 1))])
      (vector-set! dp j (modulo (- (vector-ref dp j) (vector-ref new-dp (- j i))) MOD)))
  (vector-ref dp k))

(provide k-inverse-pairs)