(define (daily-temperatures temperatures)
  (let* ((n (length temperatures))
         (result (make-vector n 0))
         (stack '()))
    (for/list ((i (in-range n)))
      (let loop ((stack stack) (i i))
        (cond
          ((null? stack)
           (set! stack (cons (cons i (list (list (list (vector-ref temperatures i) i)))) stack))
           (vector-ref result i))
          ((< (vector-ref temperatures i) (vector-ref temperatures (car (car stack))))
           (set! stack (cons (cons i (list (list (list (vector-ref temperatures i) i)))) stack))
           (vector-ref result i))
          (else
           (let ((top (car stack)))
             (set! stack (cdr stack))
             (vector-set! result (car top) (- i (car top)))
             (loop stack i))))))
    result))