(define (delete-and-earn nums)
  (define (max-points nums)
    (let ((counts (make-hash)))
      (for-each (lambda (n) (hash-update! counts n (lambda (v) (+ v 1)) 0)) nums)
      (define nums-set (sort (hash-keys counts) <))
      (define (rob nums-set)
        (let loop ((i 0) (prev1 0) (prev2 0))
          (if (= i (length nums-set))
              prev1
              (let ((current-num (list-ref nums-set i))
                    (points (* current-num (hash-ref counts current-num))))
                (if (and (> i 0) (= (+ 1 (list-ref nums-set (- i 1))) current-num))
                    (loop (+ i 1) (max (+ prev2 points) prev1) prev1)
                    (loop (+ i 1) (max (+ prev1 points) prev1) prev1))))))
      (rob nums-set)))
  (max-points nums))