(define (WordFilter words)
  (let* ((trie (make-hash))
         (add-word (lambda (word index)
                      (let loop ((node trie) (i 0))
                        (if (= i (string-length word))
                            (hash-set! node #f index)
                            (let ((char (string-ref word i)))
                              (unless (hash-has-key? node char)
                                (hash-set! node char (make-hash)))
                              (loop (hash-ref node char) (add1 i)))))))
         (build-trie (lambda ()
                       (for/list ((word words) (i (in-range (length words))))
                         (add-word word i)))))
    (build-trie)
    (lambda (prefix suffix)
      (let loop ((node trie) (i 0) (prefix-len (string-length prefix)))
        (cond
          ((= i prefix-len)
           (let ((results (filter (lambda (v) (string-suffix? (list-ref words v) suffix))
                                  (hash-values (flatten (list node)))))
                 (if (empty? results)
                     -1
                     (apply max results))))
          ((hash-has-key? node (string-ref prefix i)))
          (else -1)
          (else (loop (hash-ref node (string-ref prefix i)) (add1 i) prefix-len)))))))