(define (subsets nums)
  (define (helper current-subset remaining-nums)
    (if (null? remaining-nums)
        (list current-subset)
        (let ((first-num (car remaining-nums))
              (rest-nums (cdr remaining-nums)))
          (append (helper current-subset rest-nums)
                  (helper (append current-subset (list first-num)) rest-nums)))))
  (helper '() nums))