(define (letter-case-permutation s)
  (define (permute str idx acc)
    (if (= idx (string-length str))
        (list str)
        (let ((c (string-ref str idx)))
          (if (char-alphabetic? c)
              (append (permute (string-copy str #:start idx #:end (+ idx 1) #:replace (string (list (char-downcase c)))) (+ idx 1) acc)
                      (permute (string-copy str #:start idx #:end (+ idx 1) #:replace (string (list (char-upcase c)))) (+ idx 1) acc))
              (permute str (+ idx 1) acc)))))
  (permute s 0 '()))