(define (max-increase-keeping-skyline grid)
  (let* ((n (length grid))
         (row-maxes (make-vector n 0))
         (col-maxes (make-vector n 0)))
    (for ((i (in-range n)))
      (for ((j (in-range n)))
        (vector-set! row-maxes i (max (vector-ref row-maxes i) (list-ref (list-ref grid i) j)))
        (vector-set! col-maxes j (max (vector-ref col-maxes j) (list-ref (list-ref grid i) j)))))
    (let ((total-increase 0))
      (for ((i (in-range n)))
        (for ((j (in-range n)))
          (set! total-increase (+ total-increase (- (min (vector-ref row-maxes i) (vector-ref col-maxes j)) (list-ref (list-ref grid i) j))))))
      total-increase)))