(define (largest-triangle-area points)
  (define (area p1 p2 p3)
    (abs (/ (+ (* (car p1) (- (cadr p2) (cadr p3)))
                (* (car p2) (- (cadr p3) (cadr p1)))
                (* (car p3) (- (cadr p1) (cadr p2))))
            2.0)))

  (let* ((n (length points))
         (max-area 0.0))
    (for* ((i (in-range n))
           (j (in-range (+ i 1) n))
           (k (in-range (+ j 1) n)))
      (set! max-area (max max-area (area (list-ref points i) (list-ref points j) (list-ref points k)))))
    max-area))