(define (numFriendRequests ages)
  (let* ([counts (make-vector 121 0)]
         [n (length ages)])
    (for ([age ages])
      (vector-set! counts age (+ 1 (vector-ref counts age))))
    (let loop ([i 1] [result 0])
      (if (> i 120)
          result
          (let ([count (vector-ref counts i)])
            (if (= count 0)
                (loop (+ i 1) result)
                (let loop2 ([j 1] [inner-result 0])
                  (if (> j 120)
                      (loop (+ i 1) (+ result inner-result))
                      (let ([count2 (vector-ref counts j)])
                        (if (= count2 0)
                            (loop2 (+ j 1) inner-result)
                            (if (and (<= (/ i 2.0) (+ j 7))
                                     (> j i))
                                (loop2 (+ j 1) inner-result)
                                (if (> j 100)
                                    (loop2 (+ j 1) inner-result)
                                    (if (<= j i)
                                        (if (= i j)
                                            (loop2 (+ j 1) (+ inner-result (* count (- count 1))))
                                            (loop2 (+ j 1) (+ inner-result (* count count2))))
                                        (loop2 (+ j 1) (+ inner-result (* count count2)))))))))))))))))