(define (is-rectangle-overlap rect1 rect2)
  (let ((x1 (vector-ref rect1 0))
        (y1 (vector-ref rect1 1))
        (x2 (vector-ref rect1 2))
        (y2 (vector-ref rect1 3))
        (x3 (vector-ref rect2 0))
        (y3 (vector-ref rect2 1))
        (x4 (vector-ref rect2 2))
        (y4 (vector-ref rect2 3)))
    (and (< x1 x4)
         (< x3 x2)
         (< y1 y4)
         (< y3 y2))))