(define (profitable-schemes n min-profit groups profits)
  (define MOD 1000000007)
  (define dp (make-vector (+ 1 n) (make-vector (+ 1 min-profit) 0)))
  (vector-set! (vector-ref dp 0) 0 1)
  (for ([i (in-range (length groups))])
    (define group (list-ref groups i))
    (define profit (list-ref profits i))
    (for ([j (in-range n -1 -1)])
      (for ([k (in-range min-profit -1 -1)])
        (define new-j (min (+ j group) n))
        (define new-k (min (+ k profit) min-profit))
        (vector-set! (vector-ref dp new-j) new-k
                     (modulo (+ (vector-ref (vector-ref dp new-j) new-k)
                                 (vector-ref (vector-ref dp j) k))
                              MOD)))))
  (let loop ([i 0] [total 0])
    (if (> i n)
        total
        (loop (+ i 1) (modulo (+ total (vector-ref (vector-ref dp i) min-profit)) MOD))))
)