(define (super-egg-drop k n)
  (let ((dp (make-vector (+ n 1) 0)))
    (for ((m (in-range 1 (+ n 1))))
      (for ((j (in-range k 1 -1)))
        (vector-update! dp m (+ (vector-ref dp m) (vector-ref dp (- m 1) (- j 1))) )
        )
      (vector-update! dp m (+ (vector-ref dp m) 1))
      (when (>= (vector-ref dp m) n)
        (return m)))
    n))