(define (all-possible-fbt n)
  (if (even? n)
      '()
      (if (= n 1)
          (list (list 'node))
          (let loop ((i 1))
            (if (> i (- n 1))
                '()
                (append (map (lambda (left)
                               (map (lambda (right)
                                      (list 'node left right))
                                    (all-possible-fbt (- n 1 i))))
                             (all-possible-fbt i))
                        (loop (+ i 2)))))))