(define (smallestRangeII nums k)
  (define n (length nums))
  (define sorted-nums (sort nums <))
  (define min-val (car sorted-nums))
  (define max-val (last sorted-nums))
  (define ans (- max-val min-val))
  (for ([i (in-range (- n 1))])
    (define a (list-ref sorted-nums i))
    (define b (list-ref sorted-nums (+ i 1)))
    (define high (max (+ max-val (- k)) (+ a k)))
    (define low (min (+ min-val k) (+ b (- k))))
    (set! ans (min ans (- high low))))
  ans)