(define (knight-dialer n)
  (define mod 1000000007)
  (define moves (vector (vector 4 6)
                       (vector 6 8)
                       (vector 7 9)
                       (vector 4 8)
                       (vector 0 3 9)
                       (vector)
                       (vector 0 1 7)
                       (vector 2 6)
                       (vector 1 3)
                       (vector 2 4)))
  (define (solve n)
    (define dp (make-vector 10 1))
    (for ([i (in-range (- n 1))])
      (define new-dp (make-vector 10 0))
      (for ([j (in-range 10)])
        (for ([next-digit (in-vector (vector-ref moves j))])
          (vector-set! new-dp next-digit (modulo (+ (vector-ref new-dp next-digit) (vector-ref dp j)) mod))))
      (set! dp new-dp))
    (foldl (lambda (x acc) (modulo (+ x acc) mod)) 0 dp))
  (solve n))