(define (num-trees n)
  (let ((dp (make-vector (+ n 1) 0)))
    (vector-set! dp 0 1)
    (vector-set! dp 1 1)
    (for ((i (in-range 2 (+ n 1))))
      (for ((j (in-range 1 (+ i 1))))
        (vector-set! dp i (+ (vector-ref dp i) (* (vector-ref dp (- j 1)) (vector-ref dp (- i j)))))))
    (vector-ref dp n)))