(define (subarray-sums-divisible k nums)
  (let ((n (length nums)))
    (let loop ((i 0) (prefix-sum 0) (count (make-vector k 0)))
      (if (= i n)
          (vector-fold + 0 count)
          (let* ((remainder (modulo (+ prefix-sum (list-ref nums i)) k))
                 (normalized-remainder (if (< remainder 0) (+ remainder k) remainder))
                 (current-count (vector-ref count normalized-remainder)))
            (vector-set! count normalized-remainder (+ current-count 1))
            (loop (+ i 1) (+ prefix-sum (list-ref nums i)) count))))))