(define (odd-even-jumps arr)
  (define n (length arr))
  (define (make-dp) (make-vector n #f))
  (define odd-dp (make-dp))
  (define even-dp (make-dp))
  (vector-set! odd-dp (- n 1) #t)
  (vector-set! even-dp (- n 1) #t)

  (define (build-next-greater)
    (define stack '())
    (define next-greater (make-vector n -1))
    (for ((i (in-range (- n 1) -1 -1)))
      (while (and (not (null? stack))
                  (> (vector-ref arr (car stack)) (vector-ref arr i)))
        (set! stack (cdr stack)))
      (when (not (null? stack))
        (vector-set! next-greater i (car stack)))
      (set! stack (cons i stack)))
    next-greater)

  (define (build-next-smaller)
    (define stack '())
    (define next-smaller (make-vector n -1))
    (for ((i (in-range (- n 1) -1 -1)))
      (while (and (not (null? stack))
                  (< (vector-ref arr (car stack)) (vector-ref arr i)))
        (set! stack (cdr stack)))
      (when (not (null? stack))
        (vector-set! next-smaller i (car stack)))
      (set! stack (cons i stack)))
    next-smaller)

  (define next-greater (build-next-greater))
  (define next-smaller (build-next-smaller))

  (for ((i (in-range (- n 2) -1 -1)))
    (let ((odd-next (vector-ref next-greater i))
          (even-next (vector-ref next-smaller i)))
      (when (>= odd-next 0)
        (vector-set! odd-dp i (vector-ref even-dp odd-next)))
      (when (>= even-next 0)
        (vector-set! even-dp i (vector-ref odd-dp even-next)))))

  (for/sum ((i (in-range n)))
    (if (vector-ref odd-dp i) 1 0)))