(define (jump nums)
  (let* ((n (length nums))
         (dp (make-vector n #f)))
    (vector-set! dp 0 0)
    (for/fold ((i 1))
              ((j (in-range 0 n)))
      (if (and (not (vector-ref dp i))
               (<= i (+ j (vector-ref nums j))))
          (begin (vector-set! dp i (+ 1 (vector-ref dp j)))
                 (if (= i (- n 1))
                     (void)
                     (set! i (add1 i))))
          i))
    (vector-ref dp (- n 1))))