(define (num-ways bottom height)
  (let ((mod 1000000007))
    (letrec ((f (make-vector (add1 height) 0)))
      (vector-set! f 0 1)
      (vector-set! f 1 2)
      (for ((i (in-range 2 (add1 height))))
        (vector-set! f i (modulo (+ (vector-ref f (- i 1))
                                    (vector-ref f (- i 2)))
                                mod)))
      (vector-ref f height))))