(define (solve a b)
  (define (nand x y)
    (not (and x y)))
  (define (not x)
    (nand x x))
  (define (and x y)
    (not (nand x y)))
  (define (or x y)
    (nand (not x) (not y)))
  (define (xor x y)
    (and (or x y) (not (and x y))))
  (xor a b))