(define (find-duplicate paths)
  (define hash (make-hash))
  (for ([path paths])
    (define parts (string-split path " "))
    (define root (car parts))
    (for ([part (cdr parts)])
      (define (extract-content filename)
        (define open-paren-index (string-index filename "("))
        (define close-paren-index (string-index filename ")"))
        (values (substring filename 0 open-paren-index)
                (substring filename (add1 open-paren-index) close-paren-index))))
      (define-values (filename content) (extract-content part))
      (define full-path (string-append root "/" filename))
      (hash-update! hash content (lambda (existing) (cons full-path existing)) (list full-path))))
  (filter (lambda (group) (> (length group) 1)) (hash-values hash)))