(define (longest-ones nums k)
  (let* ((n (length nums))
         (left 0)
         (num-zeros 0)
         (max-len 0))
    (for ([right (in-range n)])
      (when (= (list-ref nums right) 0)
        (set! num-zeros (+ num-zeros 1)))
      (while (> num-zeros k)
        (when (= (list-ref nums left) 0)
          (set! num-zeros (- num-zeros 1)))
        (set! left (+ left 1)))
      (set! max-len (max max-len (- right left -1))))
    max-len))