(define (two-city-sched-cost costs)
  (let* ((n (quotient (length costs) 2))
         (sorted-costs (sort costs (lambda (p1 p2)
                                     (< (- (car p1) (cadr p1))
                                        (- (car p2) (cadr p2))))))
         (first-n (take sorted-costs n))
         (last-n (drop sorted-costs n)))
    (+ (foldl (lambda (person acc) (+ acc (car person))) 0 first-n)
       (foldl (lambda (person acc) (+ acc (cadr person))) 0 last-n))))