(define (minimumTotal triangle)
  (let ((n (length triangle)))
    (cond
      ((zero? n) 0)
      ((= n 1) (car (car triangle)))
      (else
       (let loop ((i (- n 2))
                  (dp-row (list-ref triangle (- n 1))))
         (if (< i 0)
             (car dp-row)
             (let* ((current-triangle-row (list-ref triangle i))
                    (new-dp-row
                     (let update-row ((current-vals current-triangle-row)
                                      (dp-left dp-row)
                                      (dp-right (cdr dp-row))
                                      (acc '()))
                       (if (empty? current-vals)
                           (reverse acc)
                           (update-row (cdr current-vals)
                                       (cdr dp-left)
                                       (cdr dp-right)
                                       (cons (+ (car current-vals)
                                                (min (car dp-left) (car dp-right)))
                                             acc))))))
               (loop (- i 1) new-dp-row))))))))