(define (xor-queries arr queries)
  (let* ((prefix-xor-sums (for/fold ((acc (list 0)) (current-xor 0))
                                     #:result (reverse acc)
                                     ((val (in-list arr)))
                            (let ((new-xor (xor current-xor val)))
                              (values (cons new-xor acc) new-xor)))))
    (map (lambda (query)
           (let ((L (list-ref query 0))
                 (R (list-ref query 1)))
             (xor (list-ref prefix-xor-sums (+ R 1))
                  (list-ref prefix-xor-sums L))))
         queries)))