(define (is-leap-year? year)
  (and (= (remainder year 4) 0)
       (or (not (= (remainder year 100) 0))
           (= (remainder year 400) 0))))

(define days-in-month-vec
  '#(0 31 28 31 30 31 30 31 31 30 31 30 31))

(define (get-days-in-month month year)
  (if (= month 2)
      (if (is-leap-year? year) 29 28)
      (vector-ref days-in-month-vec month)))

(define (total-days-from-epoch year month day)
  (let loop ((y 1) (current-days 0))
    (if (= y year)
        (let loop-months ((m 1) (days-in-year current-days))
          (if (= m month)
              (+ days-in-year day)
              (loop-months (+ m 1) (+ days-in-year (get-days-in-month m y)))))
        (loop (+ y 1) (+ current-days (if (is-leap-year? y) 366 365))))))

(define (parse-date date-str)
  (let ((parts (string-split date-str "-")))
    (list (string->number (car parts))
          (string->number (cadr parts))
          (string->number (caddr parts)))))

(define (daysBetweenDates date1 date2)
  (let* ((parsed-date1 (parse-date date1))
         (y1 (car parsed-date1))
         (m1 (cadr parsed-date1))
         (d1 (caddr parsed-date1))
         (parsed-date2 (parse-date date2))
         (y2 (car parsed-date2))
         (m2 (cadr parsed-date2))
         (d2 (caddr parsed-date2)))
    (abs (- (total-days-from-epoch y1 m1 d1)
            (total-days-from-epoch y2 m2 d2)))))