(define (single-number-ii nums)
  (let ([result 0])
    (for ([i (in-range 32)])
      (let ([sum-bits 0])
        (for ([num nums])
          (when (not (zero? (bitwise-and num (expt 2 i))))
            (set! sum-bits (+ sum-bits 1))))
        (when (not (zero? (modulo sum-bits 3)))
          (set! result (bitwise-ior result (expt 2 i))))))
    result))