(struct browser-history (current-page history-back history-forward) #:mutable)

(define (browser-history-init homepage)
  (browser-history homepage '() '()))

(define (browser-history-visit this url)
  (set-browser-history-history-back! this (cons (browser-history-current-page this) (browser-history-history-back this)))
  (set-browser-history-current-page! this url)
  (set-browser-history-history-forward! this '()))

(define (browser-history-back this steps)
  (let* ((hb (browser-history-history-back this))
         (hf (browser-history-history-forward this))
         (cp (browser-history-current-page this)))
    (let loop ((s steps)
               (current-back-list hb)
               (current-forward-list hf)
               (current-page-val cp))
      (if (or (zero? s) (null? current-back-list))
          (begin
            (set-browser-history-history-back! this current-back-list)
            (set-browser-history-history-forward! this current-forward-list)
            (set-browser-history-current-page! this current-page-val)
            current-page-val)
          (loop (- s 1)
                (cdr current-back-list)
                (cons current-page-val current-forward-list)
                (car current-back-list))))))

(define (browser-history-forward this steps)
  (let* ((hb (browser-history-history-back this))
         (hf (browser-history-history-forward this))
         (cp (browser-history-current-page this)))
    (let loop ((s steps)
               (current-back-list hb)
               (current-forward-list hf)
               (current-page-val cp))
      (if (or (zero? s) (null? current-forward-list))
          (begin
            (set-browser-history-history-back! this current-back-list)
            (set-browser-history-history-forward! this current-forward-list)
            (set-browser-history-current-page! this current-page-val)
            current-page-val)
          (loop (- s 1)
                (cons current-page-val current-back-list)
                (cdr current-forward-list)
                (car current-forward-list))))))