(define (min-flips target)
  (let* ((n (string-length target))
         (initial-state #\0))
    (for/fold ((flips 0)
               (current-expected-char initial-state))
              ((i (in-range n)))
      (let ((target-char (string-ref target i)))
        (if (char=? target-char current-expected-char)
            (values flips current-expected-char)
            (values (+ flips 1)
                    (if (char=? current-expected-char #\0) #\1 #\0)))))))