(define (count-good-triplets arr a b c)
  (let* ((n (length arr))
         (good-triplets-count 0))
    (for ([i (in-range 0 (- n 2))])
      (let ((val-i (list-ref arr i)))
        (for ([j (in-range (+ i 1) (- n 1))])
          (let ((val-j (list-ref arr j)))
            (when (<= (abs (- val-i val-j)) a)
              (for ([k (in-range (+ j 1) n)])
                (let ((val-k (list-ref arr k)))
                  (when (and (<= (abs (- val-j val-k)) b)
                             (<= (abs (- val-i val-k)) c))
                    (set! good-triplets-count (+ good-triplets-count 1))))))))))
    good-triplets-count))