(define (diagonal-sum mat)
  (let* ((n (length mat))
         (total-sum 0))
    (for ([i (in-range n)])
      (set! total-sum (+ total-sum (list-ref (list-ref mat i) i)))
      (set! total-sum (+ total-sum (list-ref (list-ref mat i) (- (- n 1) i)))))
    (if (odd? n)
        (- total-sum (list-ref (list-ref mat (quotient n 2)) (quotient n 2)))
        total-sum)))