(define (interpret command)
  (let loop ((idx 0) (result '()))
    (if (>= idx (string-length command))
        (apply string-append (reverse result))
        (case (string-ref command idx)
          (#\G (loop (+ idx 1) (cons "G" result)))
          (#\( (if (char=? (string-ref command (+ idx 1)) #\))
                   (loop (+ idx 2) (cons "o" result))
                   (loop (+ idx 4) (cons "al" result))))))))