(define (nearest-valid-point x y points)
  (let loop ((idx 0)
             (min-dist +inf.0)
             (min-idx -1)
             (remaining-points points))
    (if (empty? remaining-points)
        min-idx
        (let* ((current-point (first remaining-points))
               (px (first current-point))
               (py (second current-point)))
          (if (or (= px x) (= py y))
              (let ((current-dist (+ (abs (- px x)) (abs (- py y)))))
                (if (< current-dist min-dist)
                    (loop (+ idx 1) current-dist idx (rest remaining-points))
                    (loop (+ idx 1) min-dist min-idx (rest remaining-points))))
              (loop (+ idx 1) min-dist min-idx (rest remaining-points)))))))