(define (maximum-score nums k)
  (let* ((n (vector-length nums))
         (left k)
         (right k)
         (min-val (vector-ref nums k))
         (max-score min-val))
    (let loop ()
      (set! max-score (max max-score (* min-val (- right left -1))))

      (cond
        ((and (= left 0) (= right (- n 1)))
         max-score)
        ((= left 0)
         (set! right (+ right 1))
         (set! min-val (min min-val (vector-ref nums right)))
         (loop))
        ((= right (- n 1))
         (set! left (- left 1))
         (set! min-val (min min-val (vector-ref nums left)))
         (loop))
        ((< (vector-ref nums (- left 1)) (vector-ref nums (+ right 1)))
         (set! right (+ right 1))
         (set! min-val (min min-val (vector-ref nums right)))
         (loop))
        (else
         (set! left (- left 1))
         (set! min-val (min min-val (vector-ref nums left)))
         (loop))))))