(define (count-points points queries)
  (define (point-in-circle? px py cx cy r-sq)
    (let* ((dx (- px cx))
           (dy (- py cy))
           (dist-sq (+ (* dx dx) (* dy dy))))
      (<= dist-sq r-sq)))

  (map (lambda (query)
         (let* ((cx (first query))
                (cy (second query))
                (r (third query))
                (r-sq (* r r)))
           (count (lambda (point)
                    (point-in-circle? (first point) (second point) cx cy r-sq))
                  points)))
       queries))