(define (count-good-substrings s)
  (let* ((n (string-length s))
         (count 0))
    (when (>= n 3)
      (for ((i (in-range (- n 2))))
        (let ((c1 (string-ref s i))
              (c2 (string-ref s (+ i 1)))
              (c3 (string-ref s (+ i 2))))
          (when (and (not (char=? c1 c2))
                     (not (char=? c1 c3))
                     (not (char=? c2 c3)))
            (set! count (+ count 1))))))
    count))