(define (count-palindromic-subsequences s)
  (let* ((n (string-length s))
         (chars (string->list s))
         (first-occurrence (make-hash))
         (last-occurrence (make-hash)))

    (for ([i (in-range n)])
      (let ((char (list-ref chars i)))
        (unless (hash-has-key? first-occurrence char)
          (hash-set! first-occurrence char i))
        (hash-set! last-occurrence char i)))

    (let loop ((unique-palindromes (set))
               (char-code (char->integer #\a)))
      (if (> char-code (char->integer #\z))
          (set-count unique-palindromes)
          (let* ((current-char (integer->char char-code))
                 (first-idx (hash-ref first-occurrence current-char #f))
                 (last-idx (hash-ref last-occurrence current-char #f)))
            (if (and first-idx last-idx (< first-idx last-idx))
                (let ((seen-middle-chars (set)))
                  (for ([j (in-range (+ first-idx 1) last-idx)])
                    (set! seen-middle-chars (set-add seen-middle-chars (list-ref chars j))))
                  (loop (set-union unique-palindromes seen-middle-chars)
                        (+ char-code 1)))
                (loop unique-palindromes
                      (+ char-code 1))))))))