(define (num-islands grid)
  (define rows (length grid))
  (if (zero? rows)
      0
      (let ([cols (length (car grid))])
        (if (zero? cols)
            0
            (let ()
              (define visited (make-hash))

              (define (dfs r c)
                (when (or (< r 0) (>= r rows)
                          (< c 0) (>= c cols)
                          (char=? #\0 (list-ref (list-ref grid r) c))
                          (hash-has-key? visited (cons r c)))
                  (void))
                (hash-set! visited (cons r c) #t)
                (dfs (+ r 1) c)
                (dfs (- r 1) c)
                (dfs r (+ c 1))
                (dfs r (- c 1)))

              (define island-count 0)
              (for ([r (in-range rows)])
                (for ([c (in-range cols)])
                  (when (and (char=? #\1 (list-ref (list-ref grid r) c))
                             (not (hash-has-key? visited (cons r c))))
                    (set! island-count (+ island-count 1))
                    (dfs r c))))
              island-count)))))