(define (remove-colored-pieces colors)
  (let* ((n (string-length colors))
         (alice-moves 0)
         (bob-moves 0))
    (for ((i (in-range (- n 2))))
      (let ((s1 (string-ref colors i))
            (s2 (string-ref colors (+ i 1)))
            (s3 (string-ref colors (+ i 2))))
        (cond
          ((and (char=? s1 #\A) (char=? s2 #\A) (char=? s3 #\A))
           (set! alice-moves (+ alice-moves 1)))
          ((and (char=? s1 #\B) (char=? s2 #\B) (char=? s3 #\B))
           (set! bob-moves (+ bob-moves 1))))))
    (> alice-moves bob-moves)))