(define (is-isomorphic s t)
  (let* ((len (string-length s))
         (s-to-t (make-vector 256 #f))
         (t-to-s (make-vector 256 #f)))
    (let loop ((i 0))
      (cond
        ((= i len) #t)
        (else
         (let* ((char-s (string-ref s i))
                (char-t (string-ref t i))
                (code-s (char->integer char-s))
                (code-t (char->integer char-t))
                (mapped-s-to-t (vector-ref s-to-t code-s))
                (mapped-t-to-s (vector-ref t-to-s code-t)))
           (cond
             ((not (eq? mapped-s-to-t #f))
              (if (= mapped-s-to-t code-t)
                  (if (not (eq? mapped-t-to-s #f))
                      (if (= mapped-t-to-s code-s)
                          (loop (+ i 1))
                          #f)
                      #f)
                  #f))
             ((not (eq? mapped-t-to-s #f))
              #f)
             (else
              (vector-set! s-to-t code-s code-t)
              (vector-set! t-to-s code-t code-s)
              (loop (+ i 1))))))))))