(define (maximize-number-of-subsequences pattern text)
  (let* ((p1-char (string-ref pattern 0))
         (p2-char (string-ref pattern 1))
         (text-len (string-length text)))
    (let-values (((_ total-p1 total-p2 current-subsequences)
                    (for/fold ((p1-running-count 0)
                               (total-p1-in-text 0)
                               (total-p2-in-text 0)
                               (subsequences-count 0))
                              ((i (in-range text-len)))
                      (let ((c (string-ref text i)))
                        (values
                         (if (char=? c p1-char) (+ p1-running-count 1) p1-running-count)
                         (if (char=? c p1-char) (+ total-p1-in-text 1) total-p1-in-text)
                         (if (char=? c p2-char) (+ total-p2-in-text 1) total-p2-in-text)
                         (if (char=? c p2-char) (+ subsequences-count p1-running-count) subsequences-count)
                         ))))))
        (max (+ current-subsequences total-p2)
             (+ current-subsequences total-p1))))