(define (compute-area ax1 ay1 ax2 ay2 bx1 by1 bx2 by2)
  (let* ((area1 (* (- ax2 ax1) (- ay2 ay1)))
         (area2 (* (- bx2 bx1) (- by2 by1)))
         (overlap-x1 (max ax1 bx1))
         (overlap-y1 (max ay1 by1))
         (overlap-x2 (min ax2 bx2))
         (overlap-y2 (min ay2 by2))
         (overlap-width (max 0 (- overlap-x2 overlap-x1)))
         (overlap-height (max 0 (- overlap-y2 overlap-y1)))
         (overlap-area (* overlap-width overlap-height)))
    (- (+ area1 area2) overlap-area)))