(define (min-max-game nums)
  (if (= (length nums) 1)
      (car nums)
      (let loop ((current-nums nums) (new-list '()) (op-index 0))
        (if (empty? current-nums)
            (min-max-game (reverse new-list))
            (let* ((val1 (car current-nums))
                   (val2 (cadr current-nums))
                   (result (if (even? op-index)
                               (min val1 val2)
                               (max val1 val2))))
              (loop (cddr current-nums) (cons result new-list) (+ op-index 1)))))))