(define (longest-task-employee n logs)
  (let loop ((logs logs)
             (prev-end-time 0)
             (max-duration 0)
             (result-employee-id -1))
    (if (empty? logs)
        result-employee-id
        (let* ((current-log (car logs))
               (employee-id (car current-log))
               (end-time (cadr current-log))
               (duration (- end-time prev-end-time)))
          (if (> duration max-duration)
              (loop (cdr logs) end-time duration employee-id)
              (if (= duration max-duration)
                  (loop (cdr logs) end-time max-duration (min result-employee-id employee-id))
                  (loop (cdr logs) end-time max-duration result-employee-id)))))))