(define (max-marked-indices nums)
  (let* ((n (length nums))
         (vec-nums (list->vector nums))
         (sorted-vec-nums (vector-sort < vec-nums))
         (half-n (quotient n 2)))
    (let loop ((i 0)
               (j half-n)
               (count 0))
      (if (or (>= i half-n)
              (>= j n))
          (* count 2)
          (let ((num-i (vector-ref sorted-vec-nums i))
                (num-j (vector-ref sorted-vec-nums j)))
            (if (<= (* 2 num-i) num-j)
                (loop (+ i 1) (+ j 1) (+ count 1))
                (loop i (+ j 1) count)))))))