(define (even-odd-bit-counts n)
  (let loop ((current-n n)
             (even-bits 0)
             (odd-bits 0)
             (bit-index 0))
    (if (= current-n 0)
        (list even-bits odd-bits)
        (let* ((lsb (bitwise-and current-n 1))
               (is-even-position (= (modulo bit-index 2) 0)))
          (loop (arithmetic-shift current-n -1)
                (if (and is-even-position (= lsb 1))
                    (add1 even-bits)
                    even-bits)
                (if (and (not is-even-position) (= lsb 1))
                    (add1 odd-bits)
                    odd-bits)
                (add1 bit-index))))))