(define (char-to-int c)
  (- (char->integer c) (char->integer #\a)))

(define (can-match? c1 c2)
  (let* ((i1 (char-to-int c1))
         (i2 (char-to-int c2)))
    (or (= i1 i2)
        (= (modulo (+ i1 1) 26) i2)
        (= (modulo (+ i1 2) 26) i2))))

(define (can-be-subsequence str1 str2)
  (let* ((n1 (string-length str1))
         (n2 (string-length str2))
         (j 0))
    (for ([i (in-range n1)])
      (when (and (< j n2)
                 (can-match? (string-ref str1 i) (string-ref str2 j)))
        (set! j (+ j 1))))
    (= j n2)))