(define (check-if-strings-can-be-made-equal s1 s2)
  (let* ((s1-even-chars (list (string-ref s1 0) (string-ref s1 2)))
         (s1-odd-chars  (list (string-ref s1 1) (string-ref s1 3)))
         (s2-even-chars (list (string-ref s2 0) (string-ref s2 2)))
         (s2-odd-chars  (list (string-ref s2 1) (string-ref s2 3))))
    (and (equal? (sort s1-even-chars char<?)
                 (sort s2-even-chars char<?))
         (equal? (sort s1-odd-chars char<?)
                 (sort s2-odd-chars char<?)))))