(define (rename-columns table rename-map)
  (if (empty? table)
      '()
      (let* ((header (car table))
             (data-rows (cdr table))
             (new-header (map (lambda (col-name)
                                (hash-ref rename-map col-name col-name))
                              header)))
        (cons new-header data-rows))))