(define (fill-missing-data data col-index)
  (let* (
         (column-values (map (lambda (row) (list-ref row col-index)) data))
         (non-missing-numbers (filter number? column-values))
         (sum-non-missing (apply + non-missing-numbers))
         (count-non-missing (length non-missing-numbers))
         (mean (if (> count-non-missing 0)
                   (/ sum-non-missing count-non-missing)
                   0)))
    (map (lambda (row)
           (let loop ((idx 0) (current-row row) (acc '()))
             (if (null? current-row)
                 (reverse acc)
                 (let ((current-val (car current-row)))
                   (if (= idx col-index)
                       (loop (+ idx 1) (cdr current-row) (cons (if (eq? current-val #f) mean current-val) acc))
                       (loop (+ idx 1) (cdr current-row) (cons current-val acc)))))))
         data)))