(define (divide dividend divisor)
  (define MAX_INT (- (expt 2 31) 1))
  (define MIN_INT (- (expt 2 31)))

  (if (and (= dividend MIN_INT) (= divisor -1))
      MAX_INT
      (let* ((negative (xor (< dividend 0) (< divisor 0)))
             (dvd (abs dividend))
             (dvs (abs divisor)))

        (let loop ((current-dvd dvd)
                   (quotient 0))
          (if (< current-dvd dvs)
              (let ((final-quotient (if negative (- quotient) quotient)))
                (cond ((> final-quotient MAX_INT) MAX_INT)
                      ((< final-quotient MIN_INT) MIN_INT)
                      (else final-quotient)))
              (let-values (((temp-dvs multiple)
                            (let inner-loop ((tdvs dvs) (mult 1))
                              (if (<= (arithmetic-shift tdvs 1) current-dvd)
                                  (inner-loop (arithmetic-shift tdvs 1) (arithmetic-shift mult 1))
                                  (values tdvs mult))))
                           )
                (loop (- current-dvd temp-dvs) (+ quotient multiple))))))))