(define (longest-unequal-adjacent-groups-subsequence groups nums)
  (if (empty? groups)
      '()
      (let loop ((current-groups (cdr groups))
                 (current-nums (cdr nums))
                 (last-group (car groups))
                 (result (list (car nums))))
        (if (empty? current-groups)
            (reverse result)
            (let ((current-group (car current-groups))
                  (current-num (car current-nums)))
              (if (= current-group last-group)
                  (loop (cdr current-groups)
                        (cdr current-nums)
                        last-group
                        result)
                  (loop (cdr current-groups)
                        (cdr current-nums)
                        current-group
                        (cons current-num result))))))))