(define (minimum-changes s)
  (let* ((n (string-length s))
         (changes 0))
    (for ((i (in-range 0 n 3)))
      (when (not (char=? (string-ref s i) #\0))
        (set! changes (+ changes 1)))
      (when (not (char=? (string-ref s (+ i 1)) #\1))
        (set! changes (+ changes 1)))
      (when (not (char=? (string-ref s (+ i 2)) #\0))
        (set! changes (+ changes 1))))
    changes))