(define (maximum-strong-pair-xor-i nums)
  (let* ((n (length nums))
         (max-xor 0))
    (for* ((i (in-range n))
           (j (in-range i n)))
      (let* ((x (list-ref nums i))
             (y (list-ref nums j))
             (smaller (min x y))
             (larger (max x y)))
        (when (<= larger (* 2 smaller))
          (set! max-xor (max max-xor (bitwise-xor x y))))))
    max-xor))