(define (count-beautiful-substrings s k)
  (define (is-vowel char)
    (or (char=? char #\a)
        (char=? char #\e)
        (char=? char #\i)
        (char=? char #\o)
        (char=? char #\u)))

  (let* ((n (string-length s))
         (beautiful-count 0))
    (for ((i (in-range n)))
      (let ((vowels 0)
            (consonants 0))
        (for ((j (in-range i n)))
          (let ((char (string-ref s j)))
            (if (is-vowel char)
                (set! vowels (+ vowels 1))
                (set! consonants (+ consonants 1))))

          (when (and (= vowels consonants)
                     (> vowels 0) ; Ensures non-empty and non-zero counts
                     (= (modulo (* vowels consonants) k) 0))
            (set! beautiful-count (+ beautiful-count 1))))))
    beautiful-count))