(define (satisfies grid r c)
  (let* ((c1 (list-ref (list-ref grid r) c))
         (c2 (list-ref (list-ref grid r) (+ c 1)))
         (c3 (list-ref (list-ref grid (+ r 1)) c))
         (c4 (list-ref (list-ref grid (+ r 1)) (+ c 1))))
    (and (char=? c1 c2)
         (char=? c1 c3)
         (char=? c1 c4))))

(define (make-square grid)
  (or (satisfies grid 0 0)
      (satisfies grid 0 1)
      (satisfies grid 1 0)
      (satisfies grid 1 1)))