(define (minimum-chairs s)
  (let loop ((index 0)
             (current-occupancy 0)
             (max-occupancy 0))
    (if (= index (string-length s))
        max-occupancy
        (let ((char (string-ref s index)))
          (if (char=? char #\E)
              (loop (+ index 1)
                    (+ current-occupancy 1)
                    (max max-occupancy (+ current-occupancy 1)))
              (loop (+ index 1)
                    (- current-occupancy 1)
                    max-occupancy))))))