(define (count-substrings s k)
  (let* ((n (string-length s))
         (ans 0)
         (left 0)
         (char-counts (make-hash))
         (distinct-count 0))

    (for ([right (in-range n)])
      (let* ((r-char (string-ref s right))
             (r-char-current-count (hash-ref char-counts r-char 0)))
        (when (zero? r-char-current-count)
          (set! distinct-count (+ distinct-count 1)))
        (hash-set! char-counts r-char (+ r-char-current-count 1))

        (do ()
            ((<= distinct-count k))
          (let* ((l-char (string-ref s left))
                 (l-char-current-count (hash-ref char-counts l-char)))
            (hash-set! char-counts l-char (- l-char-current-count 1))
            (when (= 1 l-char-current-count)
              (set! distinct-count (- distinct-count 1)))
            (set! left (+ left 1))))

        (set! ans (+ ans (- right left 0)))))
    ans))