(define (find-even-numbers digits)
  (define (count-digit-frequencies digit-list)
    (let ((counts (make-vector 10 0)))
      (for-each (lambda (d)
                  (vector-set! counts d (+ (vector-ref counts d) 1)))
                digit-list)
      counts))

  (define (count-number-frequencies num)
    (let ((counts (make-vector 10 0)))
      (let loop ((n num))
        (when (> n 0)
          (let ((digit (modulo n 10)))
            (vector-set! counts digit (+ (vector-ref counts digit) 1)))
          (loop (quotient n 10))))
      counts))

  (define (can-form-number? number-counts available-counts)
    (let loop ((i 0))
      (cond
        ((= i 10) #t)
        ((> (vector-ref number-counts i) (vector-ref available-counts i)) #f)
        (else (loop (+ i 1))))))

  (let* ((available-counts (count-digit-frequencies digits))
         (result '()))
    (for ((i (in-range 100 1000 2)))
      (let ((num-counts (count-number-frequencies i)))
        (when (can-form-number? num-counts available-counts)
          (set! result (cons i result)))))
    (reverse result)))