(define (remove-duplicates s)
  (let loop ((chars (string->list s))
             (stack '()))
    (if (empty? chars)
        (list->string (reverse stack))
        (let ((current-char (car chars)))
          (if (and (not (empty? stack))
                   (char=? current-char (car stack)))
              (loop (cdr chars) (cdr stack))
              (loop (cdr chars) (cons current-char stack)))))))