(define (count-battleships board)
  (let* ((rows (length board))
         (cols (if (null? board) 0 (length (car board))))
         (count 0))
    (for* ((i (in-range rows))
           (j (in-range cols)))
      (when (char=? (list-ref (list-ref board i) j) #\X)
        (let ((is-top-left #t))
          (when (> i 0)
            (when (char=? (list-ref (list-ref board (- i 1)) j) #\X)
              (set! is-top-left #f)))
          (when (> j 0)
            (when (char=? (list-ref (list-ref board i) (- j 1)) #\X)
              (set! is-top-left #f)))
          (when is-top-left
            (set! count (+ count 1))))))
    count))