(define (four-sum-count nums1 nums2 nums3 nums4)
  (let ((sum-freq (make-hash)))
    (for-each (lambda (n1)
                (for-each (lambda (n2)
                            (let ((s (+ n1 n2)))
                              (hash-update! sum-freq s (lambda (v) (+ v 1)) 0)))
                          nums2))
              nums1)

    (let ((count 0))
      (for-each (lambda (n3)
                  (for-each (lambda (n4)
                              (let* ((current-sum (+ n3 n4))
                                     (target-complement (- 0 current-sum)))
                                (set! count (+ count (hash-ref sum-freq target-complement 0)))))
                            nums4))
                nums3)
      count)))