(define (array-nesting nums)
  (define n (vector-length nums))
  (define visited (make-vector n #f))
  (define max-len 0)

  (for ([k (in-range n)])
    (when (not (vector-ref visited k))
      (define current-len 0)
      (define current-node k)
      (define start-node k)

      (let loop ()
        (vector-set! visited current-node #t)
        (set! current-len (+ current-len 1))
        (set! current-node (vector-ref nums current-node))
        (unless (= current-node start-node)
          (loop)))
      (set! max-len (max max-len current-len))))
  max-len)