(define (matrix-reshape mat r c)
  (let* ((m (length mat))
         (n (if (empty? mat) 0 (length (car mat))))
         (total-elements (* m n)))
    (if (not (= total-elements (* r c)))
        mat
        (let loop ((flat-list (apply append mat))
                   (rows-left r)
                   (acc '()))
          (if (zero? rows-left)
              (reverse acc)
              (let ((current-row (take flat-list c)))
                (loop (drop flat-list c)
                      (sub1 rows-left)
                      (cons current-row acc))))))))