(define (get-counts s)
  (let ((n (string-length s)))
    (if (= n 0)
        '()
        (let loop ((i 0)
                   (current-char (stringref s 0))
                   (current-count 0)
                   (acc '()))
          (if (= i n)
              (reverse (cons current-count acc))
              (let ((char (stringref s i)))
                (if (char=? char current-char)
                    (loop (+ i 1) current-char (+ current-count 1) acc)
                    (loop (+ i 1) char 1 (cons current-count acc)))))))))

(define (count-binary-substrings s)
  (let ((counts (get-counts s)))
    (let loop ((lst counts)
               (total 0))
      (if (< (length lst) 2)
          total
          (loop (cdr lst) (+ total (min (car lst) (cadr lst))))))))