(define (num-subarray-product-less-than-k nums k)
  (if (<= k 1)
      0
      (let* ((n (length nums))
             (left (make-parameter 0))
             (product (make-parameter 1))
             (count (make-parameter 0)))
        (for ([right (in-range n)])
          (product (* (product) (list-ref nums right)))
          (let loop ()
            (when (>= (product) k)
              (product (/ (product) (list-ref nums (left))))
              (left (+ (left) 1))
              (loop)))
          (count (+ (count) (- right (left) -1))))
        (count))))