#lang racket

(require racket/hash)

(define (parseLispExpression expression-string)
  (let ((expr (read (open-input-string expression-string))))
    (evaluate-expr expr (list (make-hash)))))

(define (evaluate-expr expr env)
  (cond
    ((integer? expr) expr)
    ((symbol? expr)
     (let loop ((current-env env))
       (if (null? current-env)
           (error "Undefined variable: " expr)
           (let ((frame (car current-env)))
             (if (hash-has-key? frame expr)
                 (hash-ref frame expr)
                 (loop (cdr current-env)))))))
    ((list? expr)
     (let ((op (car expr)))
       (cond
         ((eq? op 'let)
          (let* ((bindings-and-body (cdr expr))
                 (body (last bindings-and-body))
                 (bindings (take bindings-and-body (- (length bindings-and-body) 1)))
                 (new-frame (make-hash))
                 (new-env (cons new-frame env)))
            (let loop-bindings ((b bindings))
              (when (pair? b)
                (let ((var (car b))
                      (val-expr (cadr b)))
                  (let ((evaluated-val (evaluate-expr val-expr new-env)))
                    (hash-set! new-frame var evaluated-val)
                    (loop-bindings (cddr b))))))
            (evaluate-expr body new-env)))
         ((eq? op 'add)
          (+ (evaluate-expr (cadr expr) env)
             (evaluate-expr (caddr expr) env)))
         ((eq? op 'mult)
          (* (evaluate-expr (cadr expr) env)
             (evaluate-expr (caddr expr) env)))
         (else (error "Unknown operator: " op)))))
    (else (error "Invalid expression type: " expr))))