(define (sort-colors nums)
  (let* ((n (vector-length nums))
         (low 0)
         (mid 0)
         (high (- n 1)))

    (define (swap! vec i j)
      (let ((temp (vector-ref vec i)))
        (vector-set! vec i (vector-ref vec j))
        (vector-set! vec j temp)))

    (while (<= mid high)
      (let ((val (vector-ref nums mid)))
        (cond
          ((= val 0)
           (swap! nums low mid)
           (set! low (+ low 1))
           (set! mid (+ mid 1)))
          ((= val 1)
           (set! mid (+ mid 1)))
          ((= val 2)
           (swap! nums mid high)
           (set! high (- high 1))))))
    nums))