(define (numSubarrayBoundedMax nums left right)
  (define (count-less-equal bound)
    (let loop ((numbers nums)
               (total-count 0)
               (current-length 0))
      (if (empty? numbers)
          (+ total-count (/ (* current-length (+ current-length 1)) 2))
          (let ((num (first numbers)))
            (if (<= num bound)
                (loop (rest numbers) total-count (+ current-length 1))
                (loop (rest numbers)
                      (+ total-count (/ (* current-length (+ current-length 1)) 2))
                      0))))))
  (- (count-less-equal right)
     (count-less-equal (- left 1))))