(define (expressive-words s words)
  (define (get-char-counts str)
    (let* ((len (string-length str))
           (s-list (string->list str)))
      (define (loop current-list acc)
        (if (empty? current-list)
            (reverse acc)
            (let* ((char (car current-list))
                   (count (let count-char ((lst current-list) (c 0))
                            (if (and (not (empty? lst)) (eq? (car lst) char))
                                (count-char (cdr lst) (add1 c))
                                c)))
                   (rest (drop current-list count)))
              (loop rest (cons (cons char count) acc)))))
      (loop s-list '())))

  (define s-groups (get-char-counts s))

  (define (is-expressive? word)
    (let ((word-groups (get-char-counts word)))
      (define (compare-groups s-g-list w-g-list)
        (cond
          ((and (empty? s-g-list) (empty? w-g-list)) #t)
          ((or (empty? s-g-list) (empty? w-g-list)) #f)
          (else
           (let* ((s-char (caar s-g-list))
                  (s-count (cdar s-g-list))
                  (w-char (caar w-g-list))
                  (w-count (cdar w-g-list)))
             (and (eq? s-char w-char)
                  (>= s-count w-count)
                  (or (>= s-count 3) (= s-count w-count))
                  (compare-groups (cdr s-g-list) (cdr w-g-list)))))))
      (compare-groups s-groups word-groups)))

  (count is-expressive? words))