(define (peak-index-in-mountain-array arr)
  (let* ((n (length arr))
         (low 0)
         (high (- n 1)))
    (let loop ((low low) (high high))
      (if (< low high)
          (let* ((mid (+ low (quotient (- high low) 2))))
            (if (< (list-ref arr mid) (list-ref arr (+ mid 1)))
                (loop (+ mid 1) high)
                (loop low mid)))
          low))))