(define (lemonadeChange bills)
  (let loop ((remaining-bills bills)
             (fives 0)
             (tens 0))
    (cond
      ((empty? remaining-bills) #t)
      ((= (car remaining-bills) 5)
       (loop (cdr remaining-bills) (+ fives 1) tens))
      ((= (car remaining-bills) 10)
       (if (> fives 0)
           (loop (cdr remaining-bills) (- fives 1) (+ tens 1))
           #f))
      ((= (car remaining-bills) 20)
       (cond
         ((and (> tens 0) (> fives 0))
          (loop (cdr remaining-bills) (- fives 1) (- tens 1)))
         ((>= fives 3)
          (loop (cdr remaining-bills) (- fives 3) tens))
         (else #f)))
      (else #f))))