(define (min-operations leaves)
  (let* ((n (string-length leaves))
         (dp0 (if (char=? (string-ref leaves 0) #\y) 1 0))
         (dp1 +inf.0)
         (dp2 +inf.0))
    (for ([i (range 1 n)])
      (let* ((current-is-y (char=? (string-ref leaves i) #\y))
             (current-is-r (char=? (string-ref leaves i) #\r))
             (new-dp0 (+ dp0 (if current-is-y 1 0)))
             (new-dp1 (+ (min dp0 dp1) (if current-is-r 1 0)))
             (new-dp2 (+ (min dp1 dp2) (if current-is-y 1 0))))
        (set! dp0 new-dp0)
        (set! dp1 new-dp1)
        (set! dp2 new-dp2)))
    dp2))