-module(max_alloys).
-export([max_number, solve/3]).

max_number(N, K, budget, composition, stock) ->
    solve(N, K, budget, composition, stock).

solve(N, K, budget, Composition, Stock) ->
    solve(0, 200000000, N, K, budget, Composition, Stock).

solve(Low, High, N, K, Budget, Composition, Stock) ->
    if Low > High ->
        High;
    true ->
        Mid = (Low + High) div 2,
        if possible(Mid, N, K, Budget, Composition, Stock) ->
            solve(Mid + 1, High, N, K, Budget, Composition, Stock);
        true ->
            solve(Low, Mid - 1, N, K, Budget, Composition, Stock)
    end.

possible(Alloys, N, K, Budget, Composition, Stock) ->
    lists:any(fun(I) ->
        Cost = lists:sum([max(0, Alloys * lists:nth(J + 1, lists:nth(I + 1, Composition)) - lists:nth(J + 1, Stock))
                           * 1
                           || J <- lists:seq(0, N - 1)]),
        Cost = Cost - (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost = Cost + (Cost rem 1),
        Cost