(define (num-pairs-divisible-by-60 time)
  (let ((remainders (make-vector 60 0))
        (count 0))
    (for-each (lambda (t)
                (let* ((r (modulo t 60))
                       (target-r (if (= r 0) 0 (- 60 r))))
                  (set! count (+ count (vector-ref remainders target-r)))
                  (vector-set! remainders r (+ (vector-ref remainders r) 1))))
              time)
    count))