(struct Node (val left right next) #:mutable)

(define (connect root)
  (let loop ((level-start root))
    (when (not (null? level-start))
      (let inner-loop ((curr level-start))
        (when (not (null? curr))
          (when (not (null? (Node-left curr)))
            (set-Node-next! (Node-left curr) (Node-right curr)))
          (when (and (not (null? (Node-right curr)))
                     (not (null? (Node-next curr))))
            (set-Node-next! (Node-right curr) (Node-left (Node-next curr))))
          (inner-loop (Node-next curr))))
      (loop (Node-left level-start))))
  root)