(define (freq-alphabets s)
  (let* ((len (string-length s)))
    (let loop ((i (- len 1))
               (acc '()))
      (if (< i 0)
          (list->string (reverse acc))
          (let ((current-char (string-ref s i)))
            (if (char=? current-char #\#)
                (let* ((digit1-char (string-ref s (- i 2)))
                       (digit2-char (string-ref s (- i 1)))
                       (num-str (string digit1-char digit2-char))
                       (num (string->number num-str))
                       (decoded-char (integer->char (+ (char->integer #\a) (- num 1)))))
                  (loop (- i 3) (cons decoded-char acc)))
                (let* ((num-char-val (char->integer current-char))
                       (digit-value (- num-char-val (char->integer #\0)))
                       (decoded-char (integer->char (+ (char->integer #\a) (- digit-value 1)))))
                  (loop (- i 1) (cons decoded-char acc)))))))))