(define (num-times-binary-string-is-prefix-aligned flips)
  (let* ((n (vector-length flips)))
    (let loop ((i 0)
               (max-val 0)
               (aligned-count 0))
      (if (= i n)
          aligned-count
          (let* ((current-flip (vector-ref flips i))
                 (new-max-val (max max-val current-flip))
                 (k (+ i 1))
                 (new-aligned-count (if (= new-max-val k)
                                        (+ aligned-count 1)
                                        aligned-count)))
            (loop (+ i 1) new-max-val new-aligned-count))))))