(define (find-lucky arr)
  (define counts (make-hash))
  (for-each (lambda (x)
              (hash-set! counts x (+ 1 (hash-ref counts x 0))))
            arr)
  (define max-lucky -1)
  (for-each (lambda (num)
              (define freq (hash-ref counts num))
              (when (= num freq)
                (set! max-lucky (max max-lucky num))))
            (hash-keys counts))
  max-lucky)