(define (num-teams ratings)
  (let* ((n (length ratings))
         (ratings-vec (list->vector ratings))
         (count 0))
    (for ([i (in-range 0 n)])
      (for ([j (in-range (+ i 1) n)])
        (for ([k (in-range (+ j 1) n)])
          (let ((ri (vector-ref ratings-vec i))
                (rj (vector-ref ratings-vec j))
                (rk (vector-ref ratings-vec k)))
            (when (or (and (< ri rj) (< rj rk))
                      (and (> ri rj) (> rj rk)))
              (set! count (+ count 1)))))))
    count))