(define (find-min nums)
  (let* ((n (vector-length nums))
         (low 0)
         (high (- n 1)))
    (let loop ((l low) (h high))
      (if (= l h)
          (vector-ref nums l)
          (let ((mid (+ l (quotient (- h l) 2))))
            (if (> (vector-ref nums mid) (vector-ref nums h))
                (loop (+ mid 1) h)
                (loop l mid)))))))