(define (max-coins piles)
  (let* ((len (length piles))
         (n (/ len 3))
         (sorted-piles (vector-sort < (list->vector piles))))
    (let loop ((i 0)
               (current-coins 0)
               (right-idx (- len 1))
               (left-idx 0))
      (if (= i n)
          current-coins
          (let* ((my-pile-idx (- right-idx 1))
                 (my-pile (vector-ref sorted-piles my-pile-idx)))
            (loop (+ i 1)
                  (+ current-coins my-pile)
                  (- right-idx 2)
                  (+ left-idx 1)))))))