(define (min-cost-connect-points points-list)
  (let* ((n (length points-list))
         (points (list->vector points-list))
         (min-dist (make-vector n +inf.0))
         (visited (make-vector n #f)))
    (vector-set! min-dist 0 0)

    (let loop ((total-min-cost 0) (connected-nodes 0))
      (if (= connected-nodes n)
          total-min-cost
          (let* ((min-d-to-mst +inf.0)
                 (next-node-to-connect -1))
            (for ([i (in-range n)])
              (when (and (not (vector-ref visited i))
                         (< (vector-ref min-dist i) min-d-to-mst))
                (set! min-d-to-mst (vector-ref min-dist i))
                (set! next-node-to-connect i)))

            (vector-set! visited next-node-to-connect #t)
            (let* ((current-node-point (vector-ref points next-node-to-connect))
                   (current-node-x (list-ref current-node-point 0))
                   (current-node-y (list-ref current-node-point 1)))

              (for ([v (in-range n)])
                (when (not (vector-ref visited v))
                  (let* ((v-point (vector-ref points v))
                         (v-x (list-ref v-point 0))
                         (v-y (list-ref v-point 1))
                         (dist (+ (abs (- current-node-x v-x))
                                  (abs (- current-node-y v-y)))))
                    (when (< dist (vector-ref min-dist v))
                      (vector-set! min-dist v dist)))))
              (loop (+ total-min-cost min-d-to-mst) (+ connected-nodes 1)))))))