(define (maximum-visible-points points location angle)
  (let* ((posx (car location))
         (posy (cadr location))
         (pi (acos -1))
         (visible-at-location 0)
         (angles-list '()))

    (for-each (lambda (p)
                (let ((px (car p))
                      (py (cadr p)))
                  (if (and (= px posx) (= py posy))
                      (set! visible-at-location (+ visible-at-location 1))
                      (let* ((dx (- px posx))
                             (dy (- py posy))
                             (rad (atan dy dx))
                             (deg (* rad (/ 180 pi))))
                        (when (< deg 0) (set! deg (+ deg 360)))
                        (set! angles-list (cons deg angles-list))))))
              points)

    (let* ((sorted-angles (sort angles-list <))
           (extended-angles-vec (list->vector (append sorted-angles (map (lambda (a) (+ a 360)) sorted-angles))))
           (n (vector-length extended-angles-vec)))

      (let loop ((left 0)
                 (right 0)
                 (max-visible 0))
        (if (>= right n)
            (+ max-visible visible-at-location)
            (let* ((current-angle (vector-ref extended-angles-vec right))
                   (left-angle (vector-ref extended-angles-vec left)))
              (if (> (- current-angle left-angle) angle)
                  (loop (+ left 1) right max-visible)
                  (loop left
                        (+ right 1)
                        (max max-visible (- right left -1))))))))))