(define (getSmallestString n k)
  (let loop ((count n) (remaining-k k) (result-chars '()))
    (if (= count 0)
        (list->string (reverse result-chars))
        (let* ((min-char-val 1)
               (max-char-val 26)
               (remaining-slots (- count 1))
               (char-val (max min-char-val (- remaining-k (* remaining-slots max-char-val)))))
          (loop (- count 1)
                (- remaining-k char-val)
                (cons (integer->char (+ (char->integer #\a) (- char-val 1)))
                      result-chars))))))