(define (minimum-length s)
  (let* ((n (string-length s))
         (initial-left 0)
         (initial-right (- n 1)))
    (let loop ((l initial-left) (r initial-right))
      (if (or (>= l r)
              (not (char=? (string-ref s l) (string-ref s r))))
          (if (> l r)
              0
              (- r l -1))
          (let* ((ch (string-ref s l))
                 (next-l (let inner-l ((curr-l l))
                           (if (and (<= curr-l r) (char=? (string-ref s curr-l) ch))
                               (inner-l (+ curr-l 1))
                               curr-l)))
                 (next-r (let inner-r ((curr-r r))
                           (if (and (<= l curr-r) (char=? (string-ref s curr-r) ch))
                               (inner-r (- curr-r 1))
                               curr-r))))
            (loop next-l next-r))))))