(define (merge-triplets triplets target)
  (let* ((target-x (car target))
         (target-y (cadr target))
         (target-z (caddr target))
         (found-x #f)
         (found-y #f)
         (found-z #f))
    (for-each
     (lambda (triplet)
       (let* ((tx (car triplet))
              (ty (cadr triplet))
              (tz (caddr triplet)))
         (when (and (<= tx target-x)
                    (<= ty target-y)
                    (<= tz target-z))
           (when (= tx target-x) (set! found-x #t))
           (when (= ty target-y) (set! found-y #t))
           (when (= tz target-z) (set! found-z #t)))))
     triplets)
    (and found-x found-y found-z)))