(define (count-square-sum-triples n)
  (let ((count 0))
    (for ([a (in-range 1 (add1 n))])
      (for ([b (in-range 1 (add1 n))])
        (let* ((a-sq (sqr a))
               (b-sq (sqr b))
               (c-sq (+ a-sq b-sq))
               (c-double (sqrt c-sq))
               (c-int (exact-round c-double)))
          (when (and (= (sqr c-int) c-sq)
                     (<= 1 c-int n))
            (set! count (add1 count))))))
    count))