(define (min-swaps s)
  (let* ((len (string-length s))
         (loop (lambda (idx balance misplaced-closing)
                 (if (= idx len)
                     (quotient (+ misplaced-closing 1) 2)
                     (let ((char (string-ref s idx)))
                       (cond
                         ((char=? char #\[)
                          (loop (+ idx 1) (+ balance 1) misplaced-closing))
                         ((char=? char #\])
                          (if (< (- balance 1) 0)
                              (loop (+ idx 1) 0 (+ misplaced-closing 1))
                              (loop (+ idx 1) (- balance 1) misplaced-closing)))))))))
    (loop 0 0 0)))