(define (count-special-quadruplets nums)
  (let* ((n (length nums))
         (arr (list->vector nums))
         (count 0))
    (for ([a (in-range 0 (- n 3))])
      (for ([b (in-range (+ a 1) (- n 2))])
        (for ([c (in-range (+ b 1) (- n 1))])
          (for ([d (in-range (+ c 1) n)])
            (when (= (+ (vector-ref arr a)
                        (vector-ref arr b)
                        (vector-ref arr c))
                     (vector-ref arr d))
              (set! count (+ count 1)))))))
    count))