(define (sum-subarray-ranges nums)
  (let* ((n (length nums))
         (total-sum 0))
    (for ([i (in-range n)])
      (let ((current-min (list-ref nums i))
            (current-max (list-ref nums i)))
        (for ([j (in-range i n)])
          (let ((val (list-ref nums j)))
            (set! current-min (min current-min val))
            (set! current-max (max current-max val))
            (set! total-sum (+ total-sum (- current-max current-min)))))))
    total-sum))