(define (divide-string s k fill)
  (let* ((n (string-length s)))
    (for/list ((i (in-range 0 n k)))
      (let* ((end-idx (min (+ i k) n))
             (sub (substring s i end-idx))
             (sub-len (string-length sub)))
        (if (< sub-len k)
            (string-append sub (make-string (- k sub-len) fill))
            sub)))))