(define (minimum-lines stockPrices)
  (let ((n (length stockPrices)))
    (cond
      ((<= n 1) 0)
      (else
       (for/fold ((lines 1)
                  (p1 (list-ref stockPrices 0))
                  (p2 (list-ref stockPrices 1)))
                 ((p3-idx (in-range 2 n)))
         (let* ((p3 (list-ref stockPrices p3-idx))
                (x1 (list-ref p1 0))
                (y1 (list-ref p1 1))
                (x2 (list-ref p2 0))
                (y2 (list-ref p2 1))
                (x3 (list-ref p3 0))
                (y3 (list-ref p3 1)))
           (if (= (* (- y2 y1) (- x3 x2))
                  (* (- y3 y2) (- x2 x1)))
               (values lines p2 p3)
               (values (+ lines 1) p2 p3)))))))