(define (number-of-pairs nums)
  (let ([counts (make-hash)])
    (for-each (lambda (num)
                (hash-set! counts num (+ (hash-ref counts num 0) 1)))
              nums)
    (let-values ([(pairs leftovers)
                  (foldl (lambda (count acc)
                           (let-values ([(current-pairs current-leftovers) acc])
                             (values (+ current-pairs (quotient count 2))
                                     (+ current-leftovers (remainder count 2)))))
                         (values 0 0)
                         (hash-values counts))])
      (list pairs leftovers))))