(define (longest-subarray-with-maximum-bitwise-and nums)
  (let* ((max-val (apply max nums))
         (result (foldl (lambda (num state)
                          (let ((current-len (car state))
                                (max-len (cadr state)))
                            (if (= num max-val)
                                (let ((new-current-len (add1 current-len)))
                                  (list new-current-len (max new-current-len max-len)))
                                (list 0 max-len))))
                        (list 0 0)
                        nums)))
    (cadr result)))