(define (distinct-averages nums)
  (let* ((sorted-nums (sort nums <))
         (reversed-sorted-nums (reverse sorted-nums)))
    (let loop ((left-list sorted-nums)
               (right-list reversed-sorted-nums)
               (averages-set (set)))
      (if (empty? left-list)
          (set-count averages-set)
          (let* ((smallest (car left-list))
                 (largest (car right-list))
                 (avg (/ (+ smallest largest) 2.0)))
            (loop (cdr left-list)
                  (cdr right-list)
                  (set-add averages-set avg)))))))