(define (make-smallest-palindrome s)
  (let* ((len (string-length s))
         (char-vec (list->vector (string->list s))))
    (for ((i (range (quotient len 2))))
      (let* ((j (- (- len 1) i))
             (char-i (vector-ref char-vec i))
             (char-j (vector-ref char-vec j)))
        (if (< char-i char-j)
            (vector-set! char-vec j char-i)
            (vector-set! char-vec i char-j))))
    (list->string (vector->list char-vec))))