(define (maximize-score nums x)
  (let-values (((max-even-score max-odd-score)
                (foldl
                 (lambda (num current-scores)
                   (let ((me (car current-scores)))
                     (let ((mo (cadr current-scores)))
                       (let ((is-even (= (remainder num 2) 0)))
                         (if is-even
                             (let ((candidate-from-even (+ me num)))
                               (let ((candidate-from-odd (+ mo num (- x))))
                                 (let ((current-path-max-score (max num candidate-from-even candidate-from-odd)))
                                   (list (max me current-path-max-score) mo))))
                             (let ((candidate-from-odd (+ mo num)))
                               (let ((candidate-from-even (+ me num (- x))))
                                 (let ((current-path-max-score (max num candidate-from-odd candidate-from-even)))
                                   (list me (max mo current-path-max-score))))))))))
                 (list (- (expt 10 15)) (- (expt 10 15)))
                 nums)))
    (max max-even-score max-odd-score)))