(define/public (find-indices nums indexDifference valueDifference)
  (let* ((n (length nums)))
    (let loop-i ((i 0))
      (if (>= i n)
          (list -1 -1)
          (let loop-j ((j 0))
            (if (>= j n)
                (loop-i (+ i 1))
                (if (and (>= (abs (- i j)) indexDifference)
                         (>= (abs (- (list-ref nums i) (list-ref nums j))) valueDifference))
                    (list i j)
                    (loop-j (+ j 1)))))))))