(define (distribute-elements nums)
  (let loop ((remaining-nums (cddr nums))
             (rev-arr1 (list (car nums)))
             (rev-arr2 (list (cadr nums))))
    (if (empty? remaining-nums)
        (append (reverse rev-arr1) (reverse rev-arr2))
        (let ((current-num (car remaining-nums)))
          (if (> (car rev-arr1) (car rev-arr2))
              (loop (cdr remaining-nums) (cons current-num rev-arr1) rev-arr2)
              (loop (cdr remaining-nums) rev-arr1 (cons current-num rev-arr2)))))))