(define (count-complete-day-pairs hours)
  (let loop ((lst hours) (total-pairs 0))
    (if (null? lst)
        total-pairs
        (let* ((h1 (car lst))
               (remaining-hours (cdr lst)))
          (let inner-loop ((sub-lst remaining-hours) (current-total total-pairs))
            (if (null? sub-lst)
                (loop remaining-hours current-total)
                (let* ((h2 (car sub-lst))
                       (new-total (if (= (modulo (+ h1 h2) 24) 0)
                                      (add1 current-total)
                                      current-total)))
                  (inner-loop (cdr sub-lst) new-total))))))))