(define (min-operations-to-make-array-equal-to-target nums target)
  (let* ((n (vector-length nums)))
    (for/fold ((total-cost 0)
               (net-effect-at-prev-idx 0))
              ((i (in-range n)))
      (let* ((num-val (vector-ref nums i))
             (target-val (vector-ref target i))
             (needed-at-i (- target-val num-val))
             (diff-from-prev (- needed-at-i net-effect-at-prev-idx)))
        (values (+ total-cost (abs diff-from-prev))
                needed-at-i)))))