(define (count-substrings s)
  (let* ((n (string-length s))
         (count 0))
    (for ((i (range n)))
      (let ((has-a #f)
            (has-b #f)
            (has-c #f))
        (for ((j (range i n)))
          (case (string-ref s j)
            ((#\a) (set! has-a #t))
            ((#\b) (set! has-b #t))
            ((#\c) (set! has-c #t)))
          (when (and has-a has-b has-c)
            (set! count (+ count 1))))))
    count))