(define (is-valid s)
  (let loop ((idx 0) (stack '()))
    (if (= idx (string-length s))
        (null? stack)
        (let ((char (string-ref s idx)))
          (cond
            ((char=? char #\() (loop (+ idx 1) (cons char stack)))
            ((char=? char #\[) (loop (+ idx 1) (cons char stack)))
            ((char=? char #\{) (loop (+ idx 1) (cons char stack)))
            ((char=? char #\))
             (if (and (not (null? stack)) (char=? (car stack) #\())
                 (loop (+ idx 1) (cdr stack))
                 #f))
            ((char=? char #\])
             (if (and (not (null? stack)) (char=? (car stack) #\[))
                 (loop (+ idx 1) (cdr stack))
                 #f))
            ((char=? char #\})
             (if (and (not (null? stack)) (char=? (car stack) #\{))
                 (loop (+ idx 1) (cdr stack))
                 #f))
            (else
             (loop (+ idx 1) stack)))))))