(define (min-pair-removal-to-sort-array-i nums)
  (define n (length nums))
  (if (zero? n)
      0
      (let* ((tails (make-vector n 0))
             (lis-len 0))
        (define (binary-search-lower-bound arr val len)
          (let loop ((low 0) (high (- len 1)) (ans len))
            (if (<= low high)
                (let ((mid (quotient (+ low high) 2)))
                  (if (>= (vector-ref arr mid) val)
                      (loop low (- mid 1) mid)
                      (loop (+ mid 1) high ans)))
                ans)))
        (for-each
         (lambda (x)
           (let ((idx (binary-search-lower-bound tails x lis-len)))
             (vector-set! tails idx x)
             (when (= idx lis-len)
               (set! lis-len (+ lis-len 1)))))
         nums)
        (- n lis-len))))