(define (find-nth-digit n)
  (let loop ((n n)
             (digits 1)
             (count 9)
             (power-of-10 1))
    (if (> n (* digits count))
        (loop (- n (* digits count))
              (+ digits 1)
              (* count 10)
              (* power-of-10 10))
        (let* ((target-number-index (quotient (- n 1) digits))
               (target-number (+ power-of-10 target-number-index))
               (digit-index-in-number (remainder (- n 1) digits)))
          (let ((divisor (expt 10 (- digits 1 digit-index-in-number))))
            (remainder (quotient target-number divisor) 10))))))