(struct Node (val isLeaf topLeft topRight bottomLeft bottomRight))

(define (intersect quadTree1 quadTree2)
  (if (Node-isLeaf quadTree1)
      (if (Node-val quadTree1)
          (Node #t #t #f #f #f #f)
          quadTree2)
      (if (Node-isLeaf quadTree2)
          (if (Node-val quadTree2)
              (Node #t #t #f #f #f #f)
              quadTree1)
          (let* ((newTopLeft (intersect (Node-topLeft quadTree1) (Node-topLeft quadTree2)))
                 (newTopRight (intersect (Node-topRight quadTree1) (Node-topRight quadTree2)))
                 (newBottomLeft (intersect (Node-bottomLeft quadTree1) (Node-bottomLeft quadTree2)))
                 (newBottomRight (intersect (Node-bottomRight quadTree1) (Node-bottomRight quadTree2))))
            (if (and (Node-isLeaf newTopLeft)
                     (Node-isLeaf newTopRight)
                     (Node-isLeaf newBottomLeft)
                     (Node-isLeaf newBottomRight)
                     (eq? (Node-val newTopLeft) (Node-val newTopRight))
                     (eq? (Node-val newTopLeft) (Node-val newBottomLeft))
                     (eq? (Node-val newTopLeft) (Node-val newBottomRight)))
                (Node (Node-val newTopLeft) #t #f #f #f #f)
                (Node #f #f newTopLeft newTopRight newBottomLeft newBottomRight))))))