(define (reaching-points sx sy tx ty)
  (let loop ((current-tx tx) (current-ty ty))
    (cond
      ((and (= current-tx sx) (= current-ty sy)) #t)
      ((or (< current-tx sx) (< current-ty sy)) #f)
      ((= current-tx current-ty) #f)
      ((> current-tx current-ty)
       (if (= current-ty sy)
           (zero? (remainder (- current-tx sx) sy))
           (loop (remainder current-tx current-ty) current-ty)))
      ((> current-ty current-tx)
       (if (= current-tx sx)
           (zero? (remainder (- current-ty sy) sx))
           (loop current-tx (remainder current-ty current-tx))))
      (else #f))))