(define (consecutive-numbers-sum n)
  (let loop ((k 1) (count 0))
    (let* ((k-times-k-plus-1 (* k (+ k 1)))
           (two-n (* 2 n)))
      (if (<= k-times-k-plus-1 two-n)
          (let* ((term-sum-offset (quotient (* k (- k 1)) 2))
                 (numerator (- n term-sum-offset)))
            (if (zero? (remainder numerator k))
                (loop (+ k 1) (+ count 1))
                (loop (+ k 1) count)))
          count))))