(define (decode-string-at-index s k)
  (let loop-length ((idx 0) (current-len 0))
    (if (= idx (string-length s))
        (let reverse-loop ((i (sub1 (string-length s))) (current-len current-len) (current-k k))
          (let* ((char (string-ref s i))
                 (k-in-block (if (= (modulo current-k current-len) 0)
                                 current-len
                                 (modulo current-k current-len))))
            (if (char-numeric? char)
                (reverse-loop (sub1 i)
                              (/ current-len (char->digit char))
                              current-k)
                (if (= k-in-block current-len)
                    char
                    (reverse-loop (sub1 i)
                                  (sub1 current-len)
                                  current-k)))))
        (let* ((char (string-ref s idx))
               (char-val (char->digit char)))
          (if (char-numeric? char)
              (loop-length (add1 idx) (* current-len char-val))
              (loop-length (add1 idx) (add1 current-len)))))))