(define (deep-dark-fraction cont)
  (let loop ((lst (reverse cont))
             (num 0)
             (den 1))
    (if (null? lst)
        (let ((common-divisor (gcd num den)))
          (list (/ num common-divisor) (/ den common-divisor)))
        (let ((a (car lst)))
          (if (= num 0)
              (loop (cdr lst) a 1)
              (loop (cdr lst)
                    (+ (* a num) den)
                    num))))))