(define (rob nums)
  (let loop ((lst nums)
             (prev-max-excluding 0)
             (prev-max-including 0))
    (if (empty? lst)
        (max prev-max-excluding prev-max-including)
        (let* ((current-val (car lst))
               (next-lst (cdr lst))
               (current-including (+ current-val prev-max-excluding))
               (current-excluding (max prev-max-excluding prev-max-including)))
          (loop next-lst current-excluding current-including)))))